let ACodes = [														
	[`	ID	`,`	SYMPTOMS / PROBLEMS / ISSUES	`,`	SYSTEM	`],
	[`		`,`		`,`		`],
	[`	A00.0	`,`	Cholera due to Vibrio cholerae 01, biovar cholerae Classical cholera 	`,`	null	`],
	[`	A00.1	`,`	Cholera due to Vibrio cholerae 01, biovar eltor Cholera eltor 	`,`	null	`],
	[`	A00.9	`,`	Cholera, unspecified 	`,`	null	`],
	[`	A01	`,`	Typhoid and paratyphoid fevers 	`,`	null	`],
	[`	A01.0	`,`	Typhoid fever Infection due to Salmonella typhi 	`,`	null	`],
	[`	A01.1	`,`	Paratyphoid fever A 	`,`	null	`],
	[`	A01.2	`,`	Paratyphoid fever B 	`,`	null	`],
	[`	A01.3	`,`	Paratyphoid fever C 	`,`	null	`],
	[`	A01.4	`,`	Paratyphoid fever, unspecified Infection due to Salmonella paratyphi NOS 	`,`	null	`],
	[`	A02	`,`	Other salmonella infections Incl.: infection or foodborne intoxication due to any Salmonella species other than S. typhi and S. paratyphi 	`,`	null	`],
	[`	A02.0	`,`	Salmonella enteritis Salmonellosis 	`,`	null	`],
	[`	A02.1	`,`	Salmonella sepsis	`,`	null	`],
	[`	A02.2	`,`	Localized salmonella infections--Salmonella:--arthritis (M01.3*)---meningitis (G01*)----osteomyelitis (M90.2*)----pneumonia (J17.0*)----renal tubulo-interstitial disease (N16.0*)-- 	`,`	null	`],
	[`	A02.8	`,`	Other specified salmonella infections 	`,`	null	`],
	[`	A02.9	`,`	Salmonella infection, unspecified	`,`	null	`],
	[`	A03	`,`	Shigellosis 	`,`	null	`],
	[`	A03.0	`,`	Shigellosis due to Shigella dysenteriae Group A shigellosis [Shiga-Kruse dysentery]	`,`	null	`],
	[`	A03.1	`,`	Shigellosis due to Shigella flexneri Group B shigellosis 	`,`	null	`],
	[`	A03.2	`,`	Shigellosis due to Shigella boydii Group C shigellosis 	`,`	null	`],
	[`	A03.3	`,`	Shigellosis due to Shigella sonnei Group D shigellosis	`,`	null	`],
	[`	A03.8	`,`	Other shigellosis	`,`	null	`],
	[`	A03.9	`,`	Shigellosis, unspecified Bacillary dysentery NOS	`,`	null	`],
	[`	A04	`,`	Other bacterial intestinal infections Excl.: foodborne intoxications elsewhere classified tuberculous enteritis (A18.3) 	`,`	null	`],
	[`	A04.0	`,`	Enteropathogenic Escherichia coli infection	`,`	null	`],
	[`	A04.1	`,`	Enterotoxigenic Escherichia coli infection	`,`	null	`],
	[`	A04.2	`,`	Enteroinvasive Escherichia coli infection	`,`		`],
	[`	A04.3	`,`	Enterohaemorrhagic Escherichia coli infection	`,`	null	`],
	[`	A04.4	`,`	Other intestinal Escherichia coli infections Escherichia coli enteritis NOS	`,`	null	`],
	[`		`,`	Campylobacter enteritis	`,`		`],
	[`	A04.6	`,`	Enteritis due to Yersinia enterocolitica Excl.: extraintestinal yersiniosis (A28.2) 	`,`	null	`],
	[`	A04.7	`,`	Enterocolitis due to Clostridium difficile Foodborne intoxication by Clostridium difficile Pseudomembranous colitis	`,`	null	`],
	[`	A04.8	`,`	Other specified bacterial intestinal infections	`,`	null	`],
	[`	A04.9	`,`	Bacterial intestinal infection, unspecified Bacterial enteritis NOS 	`,`	null	`],
	[`	A05	`,`	Other bacterial foodborne intoxications, not elsewhere classified Excl.: Clostridium difficile foodborne intoxication and infection (A04.7) Escherichia coli infection (A04.0-A04.4) listeriosis (A32.-) salmonella foodborne intoxication and infection (A02.-) toxic effect of noxious foodstuffs (T61-T62) 	`,`	null	`],
	[`	A05.0	`,`		`,`	null	`],
	[`	A05.1	`,`	Botulism Classical foodborne intoxication due to Clostridium botulinum	`,`	null	`],
	[`	A05.2	`,`	Foodborne Clostridium perfringens [Clostridium welchii] intoxication Enteritis necroticans Pig-bel	`,`	null	`],
	[`	A05.3	`,`	Foodborne Vibrio parahaemolyticus intoxication	`,`	null	`],
	[`	A05.4	`,`	Foodborne Bacillus cereus intoxication	`,`	null	`],
	[`	A05.8	`,`	Other specified bacterial foodborne intoxications	`,`	null	`],
	[`	A05.9	`,`	Bacterial foodborne intoxication, unspecified	`,`	null	`],
	[`	A06	`,`	Amoebiasis Incl.: infection due to Entamoeba histolytica Excl.: other protozoal intestinal diseases (A07.-) 	`,`	null	`],
	[`	A06.0	`,`	Acute amoebic dysentery Acute amoebiasis Intestinal amoebiasis NOS 	`,`	null	`],
	[`	A06.1	`,`	Chronic intestinal amoebiasis	`,`	null	`],
	[`	A06.2	`,`	Amoebic nondysenteric colitis	`,`	null	`],
	[`	A06.3	`,`	Amoeboma of intestine Amoeboma NOS	`,`	null	`],
	[`	A06.4	`,`	Amoebic liver abscess Hepatic amoebiasis	`,`	null	`],
	[`	A06.5	`,`	Amoebic lung abscess (J99.8*) Amoebic abscess of lung (and liver)	`,`	null	`],
	[`	A06.6	`,`	Amoebic brain abscess (G07*) Amoebic abscess of brain (and liver)(and lung)	`,`	null	`],
	[`	A06.7	`,`	Cutaneous amoebiasis	`,`	null	`],
	[`	A06.8	`,`	Amoebic infection of other sites Amoebic: appendicitis balanitis (N51.2*) 	`,`	null	`],
	[`	A06.9	`,`	Amoebiasis, unspecified	`,`	null	`],
	[`	A07	`,`	Other protozoal intestinal diseases	`,`	null	`],
	[`	A07.0	`,`	Balantidiasis Balantidial dysentery	`,`	null	`],
	[`	A07.1	`,`	Giardiasis [lambliasis]	`,`	null	`],
	[`	A07.2	`,`	Cryptosporidiosis	`,`	null	`],
	[`	A07.3	`,`	Isosporiasis Infection due to Isospora belli and Isospora hominis Intestinal coccidiosis Isosporosis	`,`	null	`],
	[`	A07.8	`,`	Other specified protozoal intestinal diseases Intestinal trichomoniasis Sarcocystosis Sarcosporidiosis	`,`	null	`],
	[`	A07.9	`,`	Protozoal intestinal disease, unspecified Flagellate diarrhoea Protozoal: colitis diarrhoea dysentery	`,`	null	`],
	[`	A08	`,`	Viral and other specified intestinal infections Excl.: influenza with involvement of gastrointestinal tract (J09, J10.8, J11.8) 	`,`	null	`],
	[`	A08.0	`,`	Rotaviral enteritis 	`,`	null	`],
	[`	A08.1	`,`	Acute gastroenteropathy due to Norwalk agent Small round structured virus enteritis 	`,`	null	`],
	[`	A08.2	`,`	Adenoviral enteritis 	`,`	null	`],
	[`	A08.3	`,`	Other viral enteritis 	`,`	null	`],
	[`	A08.4	`,`	Viral intestinal infection, unspecified--Viral:--enteritis NOS--gastroenteritis NOS--gastroenteropathy NOS	`,`	null	`],
	[`	A08.5	`,`	Other specified intestinal infections	`,`	null	`],
	[`	A09	`,`	--Other gastroenteritis and colitis of infectious and unspecified origin-- --Excl.:--due to bacterial, protozoal, viral and other specified infectious agents (A00-A08)---noninfective (see noninfectious) diarrhoea (K52.9) -- noninfective (see noninfectious) diarrhoea--neonatal (P78.3) 	`,`	null	`],
	[`	A09.0	`,`	Other and unspecified gastroenteritis and colitis of infectious origin --Catarrh, enteric or intestinal --Diarrhoea:--acute bloody---acute hemorrhagic----acute watery----dysenteric----epidemic----Infectious or septic --colitis----enteritis----gastroenteritis----NOS----haemorrhagic Infectious diarrhoea NOS--	`,`	null	`],
	[`	A15	`,`	Respiratory tuberculosis, bacteriologically and histologically confirmed 	`,`	null	`],
	[`	A15.0	`,`	Tuberculosis of lung, confirmed by sputum microscopy with or without culture Tuberculous: bronchiectasis fibrosis of lung pneumonia pneumothorax confirmed by sputum microscopy with or without culture 	`,`	null	`],
	[`	A15.1	`,`	Tuberculosis of lung, confirmed by culture only Conditions listed in A15.0, confirmed by culture only 	`,`	null	`],
	[`	A15.2	`,`	Tuberculosis of lung, confirmed histologically Conditions listed in A15.0, confirmed histologically 	`,`	null	`],
	[`	A15.3	`,`	Tuberculosis of lung, confirmed by unspecified means Conditions listed in A15.0, confirmed but unspecified whether bacteriologically or histologically 	`,`	null	`],
	[`	A15.4	`,`	Tuberculosis of intrathoracic lymph nodes, confirmed bacteriologically and histologically Tuberculosis of lymph nodes: hilar mediastinal tracheobronchial confirmed bacteriologically and histologically Excl.: specified as primary (A15.7) 	`,`	null	`],
	[`	A15.5	`,`	Tuberculosis of larynx, trachea and bronchus, confirmed bacteriologically and histologically Tuberculosis of: bronchus glottis larynx trachea confirmed bacteriologically and histologically 	`,`	null	`],
	[`	A15.6	`,`	Tuberculous pleurisy, confirmed bacteriologically and histologically Tuberculosis of pleura Tuberculous empyema confirmed bacteriologically and histologically Excl.: in primary respiratory tuberculosis, confirmed bacteriologically and histologically (A15.7) 	`,`	null	`],
	[`	A15.7	`,`	Primary respiratory tuberculosis, confirmed bacteriologically and histologically 	`,`	null	`],
	[`	A15.8	`,`	Other respiratory tuberculosis, confirmed bacteriologically and histologically Mediastinal tuberculosis Nasopharyngeal tuberculosis Tuberculosis of: nose sinus [any nasal] confirmed bacteriologically and histologically 	`,`	null	`],
	[`	A15.9	`,`	Respiratory tuberculosis unspecified, confirmed bacteriologically and histologically 	`,`	null	`],
	[`	A16	`,`	Respiratory tuberculosis, not confirmed bacteriologically or histologically 	`,`	null	`],
	[`	A16.0	`,`	Tuberculosis of lung, bacteriologically and histologically negative Tuberculous: bronchiectasis fibrosis of lung pneumonia pneumothorax bacteriologically and histologically negative 	`,`	null	`],
	[`	A16.1	`,`	Tuberculosis of lung, bacteriological and histological examination not done Conditions listed in A16.0, bacteriological and histological examination not done 	`,`	null	`],
	[`	A16.2	`,`	Tuberculosis of lung, without mention of bacteriological or histological confirmation Tuberculosis of lung Tuberculous: bronchiectasis fibrosis of lung pneumonia pneumothorax NOS (without mention of bacteriological or histological confirmation) 	`,`	null	`],
	[`	A16.3	`,`	Tuberculosis of intrathoracic lymph nodes, without mention of bacteriological or histological confirmation Tuberculosis of lymph nodes: hilar intrathoracic mediastinal tracheobronchial NOS (without mention of bacteriological or histological confirmation) Excl.: when specified as primary (A16.7) 	`,`	null	`],
	[`	A16.4	`,`	Tuberculosis of larynx, trachea and bronchus, without mention of bacteriological or histological confirmation Tuberculosis of: bronchus glottis larynx trachea NOS (without mention of bacteriological or histological confirmation) 	`,`	null	`],
	[`	A16.5	`,`	Tuberculous pleurisy, without mention of bacteriological or histological confirmation Tuberculosis of pleura Tuberculous: empyema pleurisy NOS (without mention of bacteriological or histological confirmation) Excl.: in primary respiratory tuberculosis (A16.7) 	`,`	null	`],
	[`	A16.7	`,`	Primary respiratory tuberculosis without mention of bacteriological or histological confirmation Primary: respiratory tuberculosis NOS tuberculous complex 	`,`	null	`],
	[`	A16.8	`,`	Other respiratory tuberculosis, without mention of bacteriological or histological confirmation Mediastinal tuberculosis Nasopharyngeal tuberculosis Tuberculosis of: nose sinus [any nasal] NOS (without mention of bacteriological or histological confirmation) 	`,`	null	`],
	[`	A16.9	`,`	Respiratory tuberculosis unspecified, without mention of bacteriological or histological confirmation Respiratory tuberculosis NOS Tuberculosis NOS 	`,`	null	`],
	[`	A17	`,`	Tuberculosis of nervous system 	`,`	null	`],
	[`	A17.0	`,`	Tuberculous meningitis (G01*) Tuberculosis of meninges (cerebral)(spinal) Tuberculous leptomeningitis 	`,`	null	`],
	[`	A17.1	`,`	Meningeal tuberculoma (G07*) Tuberculoma of meninges 	`,`	null	`],
	[`	A17.8	`,`	Other tuberculosis of nervous system Tuberculoma Tuberculosis of brain (G07*) spinal cord (G07*) Tuberculous: abscess of brain (G07*) meningoencephalitis (G05.0*) myelitis (G05.0*) polyneuropathy (G63.0*) 	`,`	null	`],
	[`	A17.9	`,`	Tuberculosis of nervous system, unspecified (G99.8*) 	`,`	null	`],
	[`	A18	`,`	Tuberculosis of other organs 	`,`	null	`],
	[`	A18.0	`,`	Tuberculosis of bones and joints Tuberculosis of: hip (M01.1*) knee (M01.1*) vertebral column (M49.0*) Tuberculous: arthritis (M01.1*) mastoiditis (H75.0*) necrosis of bone (M90.0*) osteitis (M90.0*) osteomyelitis (M90.0*) synovitis (M68.0*) tenosynovitis (M68.0*) 	`,`	null	`],
	[`	A18.1	`,`	Tuberculosis of genitourinary system Tuberculosis of: bladder (N33.0*) cervix (N74.0*) kidney (N29.1*) male genital organs (N51.-*) ureter (N29.1*) Tuberculous female pelvic inflammatory disease (N74.1*) 	`,`	null	`],
	[`	A18.2	`,`	Tuberculous peripheral lymphadenopathy Tuberculous adenitis Excl.: tuberculosis of lymph nodes: intrathoracic (A15.4, A16.3) mesenteric and retroperitoneal (A18.3) tuberculous tracheobronchial adenopathy (A15.4, A16.3) 	`,`	null	`],
	[`	A18.3	`,`	Tuberculosis of intestines, peritoneum and mesenteric glands Tuberculosis (of): anus and rectum (K93.0*) intestine (large)(small) (K93.0*) retroperitoneal (lymph nodes) Tuberculous: ascites enteritis (K93.0*) peritonitis (K67.3*) 	`,`	null	`],
	[`	A18.4	`,`	Tuberculosis of skin and subcutaneous tissue Erythema induratum, tuberculous Lupus: exedens vulgaris: NOS of eyelid (H03.1*) Scrofuloderma Excl.: lupus erythematosus (L93.-) lupus erythematosus systemic (M32.-) 	`,`	null	`],
	[`	A18.5	`,`	Tuberculosis of eye Tuberculous: chorioretinitis (H32.0*) episcleritis (H19.0*) interstitial keratitis (H19.2*) iridocyclitis (H22.0*) keratoconjunctivitis (interstitial)(phlyctenular) (H19.2*) Excl.: lupus vulgaris of eyelid (A18.4) 	`,`	null	`],
	[`	A18.6	`,`	Tuberculosis of ear Tuberculous otitis media (H67.0*) Excl.: tuberculous mastoiditis (A18.0) 	`,`	null	`],
	[`	A18.7	`,`	Tuberculosis of adrenal glands (E35.1*) Addison disease, tuberculous 	`,`	null	`],
	[`	A18.8	`,`	Tuberculosis of other specified organs Tuberculosis of: endocardium (I39.8*) myocardium (I41.0*) oesophagus (K23.0*) pericardium (I32.0*) thyroid gland (E35.0*) Tuberculous cerebral arteritis (I68.1*) 	`,`	null	`],
	[`	A19	`,`	Miliary tuberculosis Incl.: tuberculosis: disseminated generalized tuberculous polyserositis 	`,`	null	`],
	[`	A19.0	`,`	Acute miliary tuberculosis of a single specified site 	`,`	null	`],
	[`	A19.1	`,`	Acute miliary tuberculosis of multiple sites 	`,`	null	`],
	[`	A19.2	`,`	Acute miliary tuberculosis, unspecified 	`,`	null	`],
	[`	A19.8	`,`	Other miliary tuberculosis 	`,`	null	`],
	[`	A19.9	`,`	Miliary tuberculosis, unspecified 	`,`	null	`],
	[`	A30.0	`,`	Indeterminate leprosy I leprosy 	`,`	null	`],
	[`	A30.1	`,`	Tuberculoid leprosy TT leprosy 	`,`	null	`],
	[`	A30.2	`,`	Borderline tuberculoid leprosy BT leprosy 	`,`	null	`],
	[`	A30.3	`,`	Borderline leprosy BB leprosy 	`,`	null	`],
	[`	A30.4	`,`	Borderline lepromatous leprosy BL leprosy 	`,`	null	`],
	[`	A30.5	`,`	Lepromatous leprosy LL leprosy 	`,`	null	`],
	[`	A30.8	`,`	Other forms of leprosy 	`,`	null	`],
	[`	A30.9	`,`	Leprosy, unspecified 	`,`	null	`],
	[`	A31	`,`	Infection due to other mycobacteria Excl.: leprosy (A30.-) tuberculosis (A15-A19) 	`,`	null	`],
	[`	A31.0	`,`	Pulmonary mycobacterial infection Infection due to Mycobacterium: avium intracellulare [Battey bacillus] kansasii 	`,`	null	`],
	[`	A31.1	`,`	Cutaneous mycobacterial infection Buruli ulcer Infection due to Mycobacterium: marinum ulcerans 	`,`	null	`],
	[`	A31.8	`,`	Other mycobacterial infections 	`,`	null	`],
	[`	A31.9	`,`	Mycobacterial infection, unspecified Atypical mycobacterium infection NOS Mycobacteriosis NOS 	`,`	null	`],
	[`	A32	`,`	Listeriosis Incl.: listerial foodborne infection Excl.: neonatal (disseminated) listeriosis (P37.2) 	`,`	null	`],
	[`	A32.0	`,`	Cutaneous listeriosis 	`,`	null	`],
	[`	A32.1	`,`	Listerial meningitis and meningoencephalitis Listerial: meningitis (G01*) meningoencephalitis (G05.0*) 	`,`	null	`],
	[`	A32.7	`,`	Listerial sepsis 	`,`	null	`],
	[`	A32.8	`,`	Other forms of listeriosis Listerial: cerebral arteritis (I68.1*) endocarditis (I39.8*) Oculoglandular listeriosis 	`,`	null	`],
	[`	A32.9	`,`	Listeriosis, unspecified 	`,`	null	`],
	[`	A33	`,`	Tetanus neonatorum 	`,`	null	`],
	[`	A34	`,`	Obstetrical tetanus 	`,`	null	`],
	[`	A35	`,`	Other tetanus Incl.: Tetanus NOS Excl.: tetanus: neonatorum (A33) obstetrical (A34) 	`,`	null	`],
	[`	A36	`,`	Diphtheria 	`,`	null	`],
	[`	A36.0	`,`	Pharyngeal diphtheria Diphtheritic membranous angina Tonsillar diphtheria 	`,`	null	`],
	[`	A36.1	`,`	Nasopharyngeal diphtheria 	`,`	null	`],
	[`	A36.2	`,`	Laryngeal diphtheria Diphtheritic laryngotracheitis 	`,`	null	`],
	[`	A36.3	`,`	Cutaneous diphtheria Excl.: erythrasma (L08.1) 	`,`	null	`],
	[`	A36.8	`,`	Other diphtheria Diphtheritic: conjunctivitis (H13.1*) myocarditis (I41.0*) polyneuritis (G63.0*) 	`,`	null	`],
	[`	A36.9	`,`	Diphtheria, unspecified 	`,`	null	`],
	[`	A37	`,`	Whooping cough 	`,`	null	`],
	[`	A37.0	`,`	Whooping cough due to Bordetella pertussis 	`,`	null	`],
	[`	A37.1	`,`	Whooping cough due to Bordetella parapertussis 	`,`	null	`],
	[`	A37.8	`,`	Whooping cough due to other Bordetella species 	`,`	null	`],
	[`	A37.9	`,`	Whooping cough, unspecified 	`,`	null	`],
	[`	A38	`,`	Scarlet fever Incl.: Scarlatina Excl.: streptococcal sore throat (J02.0) 	`,`	null	`],
	[`	A39	`,`	Meningococcal infection 	`,`	null	`],
	[`	A39.0	`,`	Meningococcal meningitis (G01*) 	`,`	null	`],
	[`	A39.1	`,`	Waterhouse-Friderichsen syndrome (E35.1*) Meningococcal haemorrhagic adrenalitis Meningococcic adrenal syndrome 	`,`	null	`],
	[`	A39.2	`,`	Acute meningococcaemia 	`,`	null	`],
	[`	A39.3	`,`	Chronic meningococcaemia 	`,`	null	`],
	[`	A39.4	`,`	Meningococcaemia, unspecified Meningococcal bacteraemia NOS 	`,`	null	`],
	[`	A39.5	`,`	Meningococcal heart disease Meningococcal: carditis NOS (I52.0*) endocarditis (I39.8*) myocarditis (I41.0*) pericarditis (I32.0*) 	`,`	null	`],
	[`	A39.8	`,`	Other meningococcal infections Meningococcal: arthritis (M01.0*) conjunctivitis (H13.1*) encephalitis (G05.0*) retrobulbar neuritis (H48.1*) Postmeningococcal arthritis (M03.0*) 	`,`	null	`],
	[`	A39.9	`,`	Meningococcal infection, unspecified Meningococcal disease NOS 	`,`	null	`],
	[`	A40	`,`	Streptococcal sepsis Use additional code (R57.2) if desired, to identify septic shock. Excl.: during labour (O75.3) following: abortion or ectopic or molar pregnancy (O03-O07, O08.0) immunization (T88.0) infusion, transfusion or therapeutic injection (T80.2) neonatal (P36.0-P36.1) postprocedural (T81.4) puerperal (O85) 	`,`	null	`],
	[`	A40.0	`,`	Sepsis due to streptococcus, group A 	`,`	null	`],
	[`	A40.1	`,`	Sepsis due to streptococcus, group B 	`,`	null	`],
	[`	A40.2	`,`	Sepsis due to streptococcus, group D 	`,`	null	`],
	[`	A40.3	`,`	Sepsis due to Streptococcus pneumoniae Pneumococcal sepsis 	`,`	null	`],
	[`	A40.8	`,`	Other streptococcal sepsis 	`,`	null	`],
	[`	A40.9	`,`	Streptococcal sepsis, unspecified 	`,`	null	`],
	[`	A41	`,`	Other sepsis Use additional code (R57.2) if desired, to identify septic shock. Excl.: bacteraemia NOS (A49.9) during labour (O75.3) following: abortion or ectopic or molar pregnancy (O03-O07, O08.0) immunization (T88.0) infusion, transfusion or therapeutic injection (T80.2) sepsis (due to)(in): actinomycotic (A42.7) anthrax (A22.7) candidal (B37.7) Erysipelothrix (A26.7) extraintestinal yersiniosis (A28.2) gonococcal (A54.8) herpesviral (B00.7) listerial (A32.7) meningococcal (A39.2-A39.4) neonatal (P36.-) postprocedural (T81.4) puerperal (O85) streptococcal (A40.-) tularaemia (A21.7) septic: melioidosis (A24.1) plague (A20.7) toxic shock syndrome (A48.3) 	`,`	null	`],
	[`	A41.0	`,`	Sepsis due to Staphylococcus aureus 	`,`	null	`],
	[`	A41.1	`,`	Sepsis due to other specified staphylococcus Sepsis due to coagulase-negative staphylococcus 	`,`	null	`],
	[`	A41.2	`,`	Sepsis due to unspecified staphylococcus 	`,`	null	`],
	[`	A41.3	`,`	Sepsis due to Haemophilus influenzae 	`,`	null	`],
	[`	A41.4	`,`	Sepsis due to anaerobes Excl.: gas gangrene (A48.0) 	`,`	null	`],
	[`	A41.5	`,`	Sepsis due to other Gram-negative organisms Gram-negative sepsis NOS 	`,`	null	`],
	[`	A41.8	`,`	Other specified sepsis 	`,`	null	`],
	[`	A41.9	`,`	Sepsis, unspecified Septicaemia 	`,`	null	`],
	[`	A42	`,`	Actinomycosis Excl.: actinomycetoma (B47.1) 	`,`	null	`],
	[`	A42.0	`,`	Pulmonary actinomycosis 	`,`	null	`],
	[`	A42.1	`,`	Abdominal actinomycosis 	`,`	null	`],
	[`	A42.2	`,`	Cervicofacial actinomycosis 	`,`	null	`],
	[`	A42.7	`,`	Actinomycotic sepsis 	`,`	null	`],
	[`	A42.8	`,`	Other forms of actinomycosis 	`,`	null	`],
	[`	A42.9	`,`	Actinomycosis, unspecified 	`,`	null	`],
	[`	A43	`,`	Nocardiosis 	`,`	null	`],
	[`	A43.0	`,`	Pulmonary nocardiosis 	`,`	null	`],
	[`	A43.1	`,`	Cutaneous nocardiosis 	`,`	null	`],
	[`	A43.8	`,`	Other forms of nocardiosis 	`,`	null	`],
	[`	A43.9	`,`	Nocardiosis, unspecified 	`,`	null	`],
	[`	A44	`,`	Bartonellosis 	`,`	null	`],
	[`	A44.0	`,`	Systemic bartonellosis Oroya fever 	`,`	null	`],
	[`	A44.1	`,`	Cutaneous and mucocutaneous bartonellosis Verruga peruana 	`,`	null	`],
	[`	A44.8	`,`	Other forms of bartonellosis 	`,`	null	`],
	[`	A44.9	`,`	Bartonellosis, unspecified 	`,`	null	`],
	[`	A46	`,`	Erysipelas Excl.: postpartum or puerperal erysipelas (O86.8) 	`,`	null	`],
	[`	A48	`,`	Other bacterial diseases, not elsewhere classified Excl.: actinomycetoma (B47.1) 	`,`	null	`],
	[`	A48.0	`,`	Gas gangrene Clostridial: cellulitis myonecrosis 	`,`	null	`],
	[`	A48.1	`,`	Legionnaires disease 	`,`	null	`],
	[`	A48.2	`,`	Nonpneumonic Legionnaires disease [Pontiac fever] 	`,`	null	`],
	[`	A48.3	`,`	Toxic shock syndrome Excl.: endotoxic shock NOS (R57.8) sepsis NOS (A41.9) 	`,`	null	`],
	[`	A48.4	`,`	Brazilian purpuric fever Systemic Haemophilus aegyptius infection 	`,`	null	`],
	[`	A48.8	`,`	Other specified bacterial diseases 	`,`	null	`],
	[`	A49	`,`	Bacterial infection of unspecified site Excl.: bacterial agents as the cause of diseases classified to other chapters (B95-B96) chlamydial infection NOS (A74.9) meningococcal infection NOS (A39.9) rickettsial infection NOS (A79.9) spirochaetal infection NOS (A69.9) 	`,`	null	`],
	[`	A49.0	`,`	Staphylococcal infection, unspecified site 	`,`	null	`],
	[`	A49.1	`,`	Streptococcal infection, unspecified site 	`,`	null	`],
	[`	A49.2	`,`	Haemophilus influenzae infection, unspecified site 	`,`	null	`],
	[`	A49.3	`,`	Mycoplasma infection, unspecified site 	`,`	null	`],
	[`	A49.8	`,`	Other bacterial infections of unspecified site 	`,`	null	`],
	[`	A49.9	`,`	Bacterial infection, unspecified Bacteraemia NOS 	`,`	null	`],
	[`	A50	`,`	Congenital syphilis	`,`	null	`],
	[`	A50.0	`,`	Early congenital syphilis, symptomatic Any congenital syphilitic condition specified as early or manifest less than two years after birth. Early congenital syphilis: cutaneous mucocutaneous visceral Early congenital syphilitic: laryngitis oculopathy osteochondropathy pharyngitis pneumonia rhinitis 	`,`	null	`],
	[`	A50.1	`,`	Early congenital syphilis, latent Congenital syphilis without clinical manifestations, with positive serological reaction and negative spinal fluid test, less than two years after birth. 	`,`	null	`],
	[`	A50.2	`,`	Early congenital syphilis, unspecified Congenital syphilis NOS less than two years after birth. 	`,`	null	`],
	[`	A50.3	`,`	Late congenital syphilitic oculopathy Late congenital syphilitic interstitial keratitis (H19.2*) Late congenital syphilitic oculopathy NEC (H58.8*) Excl.: Hutchinson triad (A50.5) 	`,`	null	`],
	[`	A50.4	`,`	Late congenital neurosyphilis [juvenile neurosyphilis] Dementia paralytica juvenilis Juvenile: general paresis tabes dorsalis taboparetic neurosyphilis Late congenital syphilitic: encephalitis (G05.0*) meningitis (G01*) polyneuropathy (G63.0*) Use additional code, if desired, to identify any associated mental disorder. Excl.: Hutchinson triad (A50.5) 	`,`	null	`],
	[`	A50.5	`,`	Other late congenital syphilis, symptomatic Any congenital syphilitic condition specified as late or manifest two years or more after birth. Clutton joints (M03.1*) Hutchinson: teeth triad Late congenital: cardiovascular syphilis (I98.0*) syphilitic: arthropathy (M03.1*) osteochondropathy (M90.2*) Syphilitic saddle nose 	`,`	null	`],
	[`	A50.6	`,`	Late congenital syphilis, latent Congenital syphilis without clinical manifestations, with positive serological reaction and negative spinal fluid test, two years or more after birth. 	`,`	null	`],
	[`	A50.7	`,`	Late congenital syphilis, unspecified Congenital syphilis NOS two years or more after birth. 	`,`	null	`],
	[`	A50.9	`,`	Congenital syphilis, unspecified	`,`	null	`],
	[`	A51	`,`	Early syphilis	`,`	null	`],
	[`	A51.0	`,`	Primary genital syphilis Syphilitic chancre NOS 	`,`	null	`],
	[`	A51.1	`,`	Primary anal syphilis	`,`	null	`],
	[`	A51.2	`,`	Primary syphilis of other sites	`,`	null	`],
	[`	A51.3	`,`	Secondary syphilis of skin and mucous membranes Condyloma latum Syphilitic: alopecia (L99.8*) leukoderma (L99.8*) mucous patch 	`,`	null	`],
	[`	A51.4	`,`	Other secondary syphilis Secondary syphilitic: female pelvic inflammatory disease (N74.2*) iridocyclitis (H22.0*) lymphadenopathy meningitis (G01*) myositis (M63.0*) oculopathy NEC (H58.8*) periostitis (M90.1*) 	`,`	null	`],
	[`	A51.5	`,`	Early syphilis, latent Syphilis (acquired) without clinical manifestations, with positive serological reaction and negative spinal fluid test, less than two years after infection. 	`,`	null	`],
	[`	A51.9	`,`	Early syphilis, unspecified	`,`	null	`],
	[`	A52	`,`	Late syphilis	`,`	null	`],
	[`	A52.0	`,`	Cardiovascular syphilis Cardiovascular syphilis NOS (I98.0*) Syphilitic: aneurysm of aorta (I79.0*) aortic incompetence (I39.1*) aortitis (I79.1*) arteritis, cerebral (I68.1*) endocarditis NOS (I39.8*) myocarditis (I41.0*) pericarditis (I32.0*) pulmonary regurgitation (I39.3*) 	`,`	null	`],
	[`	A52.1	`,`	Symptomatic neurosyphilis Charcot arthropathy (M14.6*) Late syphilitic: acoustic neuritis (H94.0*) encephalitis (G05.0*) meningitis (G01*) optic atrophy (H48.0*) polyneuropathy (G63.0*) retrobulbar neuritis (H48.1*) Syphilitic parkinsonism (G22*) Tabes dorsalis 	`,`	null	`],
	[`	A52.2	`,`	Asymptomatic neurosyphilis	`,`	null	`],
	[`	A52.3	`,`	Neurosyphilis, unspecified Gumma (syphilitic) Syphilis (late) Syphiloma of central nervous system NOS 	`,`	null	`],
	[`	A52.7	`,`	Other symptomatic late syphilis Glomerular disease in syphilis (N08.0*) Gumma (syphilitic) Late or tertiary syphilis any sites, except those classified to A52.0-A52.3 Late syphilitic: bursitis (M73.1*) chorioretinitis (H32.0*) episcleritis (H19.0*) female pelvic inflammatory disease (N74.2*) leukoderma (L99.8*) oculopathy NEC (H58.8*) peritonitis (K67.2*) Syphilis [stage unspecified] of: bone (M90.2*) liver (K77.0*) lung (J99.8*) muscle (M63.0*) synovium (M68.0*) 	`,`	null	`],
	[`	A52.8	`,`	Late syphilis, latent Syphilis (acquired) without clinical manifestations, with positive serological reaction and negative spinal fluid test, two years or more after infection. 	`,`	null	`],
	[`	A52.9	`,`	Late syphilis, unspecified	`,`	null	`],
	[`	A53	`,`	Other and unspecified syphilis	`,`	null	`],
	[`	A53.0	`,`	Latent syphilis, unspecified as early or late Latent syphilis NOS Positive serological reaction for syphilis 	`,`	null	`],
	[`	A53.9	`,`	Syphilis, unspecified Infection due to Treponema pallidum NOS Syphilis (acquired) NOS Excl.: syphilis NOS causing death under two years of age (A50.2) 	`,`	null	`],
	[`	A54	`,`	Gonococcal infection	`,`	null	`],
	[`	A54.0	`,`	Gonococcal infection of lower genitourinary tract without periurethral or accessory gland abscess Gonococcal: cervicitis NOS cystitis NOS urethritis NOS vulvovaginitis NOS Excl.: with: genitourinary gland abscess (A54.1) periurethral abscess (A54.1) 	`,`	null	`],
	[`	A54.1	`,`	Gonococcal infection of lower genitourinary tract with periurethral and accessory gland abscess Gonococcal Bartholin gland abscess 	`,`	null	`],
	[`	A54.2	`,`	Gonococcal pelviperitonitis and other gonococcal genitourinary infections Gonococcal: epididymitis (N51.1*) female pelvic inflammatory disease (N74.3*) orchitis (N51.1*) prostatitis (N51.0*) Excl.: gonococcal peritonitis (A54.8) 	`,`	null	`],
	[`	A54.3	`,`	Gonococcal infection of eye Gonococcal: conjunctivitis (H13.1*) iridocyclitis (H22.0*) Ophthalmia neonatorum due to gonococcus 	`,`	null	`],
	[`	A54.4	`,`	Gonococcal infection of musculoskeletal system Gonococcal: arthritis (M01.3*) bursitis (M73.0*) osteomyelitis (M90.2*) synovitis (M68.0*) tenosynovitis (M68.0*) 	`,`	null	`],
	[`	A54.5	`,`	Gonococcal pharyngitis	`,`	null	`],
	[`	A54.6	`,`	Gonococcal infection of anus and rectum	`,`	null	`],
	[`	A54.8	`,`	Other gonococcal infections Gonococcal: brain abscess (G07*) endocarditis (I39.8*) meningitis (G01*) myocarditis (I41.0*) pericarditis (I32.0*) peritonitis (K67.1*) pneumonia (J17.0*) sepsis skin lesions Excl.: gonococcal pelviperitonitis (A54.2) 	`,`	null	`],
	[`	A54.9	`,`	Gonococcal infection, unspecified	`,`	null	`],
	[`	A55	`,`	Chlamydial lymphogranuloma (venereum) Incl.: Climatic or tropical bubo Durand-Nicolas-Favre disease Esthiomene Lymphogranuloma inguinale 	`,`	null	`],
	[`	A56	`,`	Other sexually transmitted chlamydial diseases Incl.: sexually transmitted diseases due to Chlamydia trachomatis Excl.: chlamydial: lymphogranuloma (A55) neonatal: conjunctivitis (P39.1) pneumonia (P23.1) conditions classified to A74.- 	`,`	null	`],
	[`	A56.0	`,`	Chlamydial infection of lower genitourinary tract Chlamydial: cervicitis cystitis urethritis vulvovaginitis 	`,`	null	`],
	[`	A56.1	`,`	Chlamydial infection of pelviperitoneum and other genitourinary organs Chlamydial: epididymitis (N51.1*) female pelvic inflammatory disease (N74.4*) orchitis (N51.1*) 	`,`	null	`],
	[`	A56.2	`,`	Chlamydial infection of genitourinary tract, unspecified	`,`	null	`],
	[`	A56.3	`,`	Chlamydial infection of anus and rectum	`,`	null	`],
	[`	A56.4	`,`	Chlamydial infection of pharynx	`,`	null	`],
	[`	A56.8	`,`	Sexually transmitted chlamydial infection of other sites	`,`	null	`],
	[`	A57	`,`	Chancroid Incl.: Ulcus molle 	`,`	null	`],
	[`	A58	`,`	Granuloma inguinale Incl.: Donovanosis 	`,`	null	`],
	[`	A59	`,`	Trichomoniasis Excl.: intestinal trichomoniasis (A07.8) 	`,`	null	`],
	[`	A59.0	`,`	Urogenital trichomoniasis Leukorrhoea (vaginalis) Prostatitis (N51.0*) due to Trichomonas (vaginalis) 	`,`	null	`],
	[`	A59.8	`,`	Trichomoniasis of other sites	`,`	null	`],
	[`	A59.9	`,`	Trichomoniasis, unspecified	`,`	null	`],
	[`	A60	`,`	Anogenital herpesviral [herpes simplex] infection	`,`	null	`],
	[`	A60.0	`,`	Herpesviral infection of genitalia and urogenital tract Herpesviral infection of genital tract: female (N77.0-N77.1*) male (N51.-*) 	`,`	null	`],
	[`	A60.1	`,`	Herpesviral infection of perianal skin and rectum 	`,`	null	`],
	[`	A60.9	`,`	Anogenital herpesviral infection, unspecified 	`,`	null	`],
	[`	A63	`,`	Other predominantly sexually transmitted diseases, not elsewhere classified Excl.: molluscum contagiosum (B08.1) papilloma of cervix (D26.0) 	`,`	null	`],
	[`	A63.0	`,`	Anogenital (venereal) warts 	`,`	null	`],
	[`	A63.8	`,`	Other specified predominantly sexually transmitted diseases 	`,`	null	`],
	[`	A64	`,`	Unspecified sexually transmitted disease 	`,`	null	`],
	[`	A65	`,`	Nonvenereal syphilis Incl.: Bejel Endemic syphilis Njovera 	`,`	null	`],
	[`	A66	`,`	Yaws Incl.: bouba framboesia (tropica) pian 	`,`	null	`],
	[`	A66.0	`,`	Initial lesions of yaws Chancre of yaws Framboesia, initial or primary Initial framboesial ulcer Mother yaw 	`,`	null	`],
	[`	A66.1	`,`	Multiple papillomata and wet crab yaws Framboesioma Pianoma Plantar or palmar papilloma of yaws 	`,`	null	`],
	[`	A66.2	`,`	Other early skin lesions of yaws Cutaneous yaws, less than five years after infection Early yaws (cutaneous) (macular) (maculopapular) (micropapular) (papular) Framboeside of early yaws 	`,`	null	`],
	[`	A66.3	`,`	Hyperkeratosis of yaws Ghoul hand Hyperkeratosis, palmar or plantar (early)(late) due to yaws Worm-eaten soles 	`,`	null	`],
	[`	A66.4	`,`	Gummata and ulcers of yaws Gummatous framboeside Nodular late yaws (ulcerated) 	`,`	null	`],
	[`	A66.5	`,`	Gangosa Rhinopharyngitis mutilans 	`,`	null	`],
	[`	A66.6	`,`	Bone and joint lesions of yaws Ganglion Hydrarthrosis Osteitis Periostitis (hypertrophic) of yaws (early)(late) Goundou Gumma, bone Gummatous osteitis or periostitis of yaws (late) 	`,`	null	`],
	[`	A66.7	`,`	Other manifestations of yaws Juxta-articular nodules of yaws Mucosal yaws 	`,`	null	`],
	[`	A66.8	`,`	Latent yaws Yaws without clinical manifestations, with positive serology 	`,`	null	`],
	[`	A66.9	`,`	Yaws, unspecified 	`,`	null	`],
	[`	A67	`,`	Pinta [carate] 	`,`	null	`],
	[`	A67.0	`,`	Primary lesions of pinta Chancre (primary) Papule (primary) of pinta [carate] 	`,`	null	`],
	[`	A67.1	`,`	Intermediate lesions of pinta Erythematous plaques Hyperchromic lesions Hyperkeratosis of pinta [carate] Pintids 	`,`	null	`],
	[`	A67.2	`,`	Late lesions of pinta Cardiovascular lesions (I98.1*) Skin lesions: achromic cicatricial dyschromic of pinta [carate] 	`,`	null	`],
	[`	A67.3	`,`	Mixed lesions of pinta Achromic with hyperchromic skin lesions of pinta [carate] 	`,`	null	`],
	[`	A67.9	`,`	Pinta, unspecified 	`,`	null	`],
	[`	A68	`,`	Relapsing fevers Incl.: recurrent fever Excl.: Lyme disease (A69.2) 	`,`	null	`],
	[`	A68.0	`,`	Louse-borne relapsing fever Relapsing fever due to Borrelia recurrentis 	`,`	null	`],
	[`	A68.1	`,`	Tick-borne relapsing fever Relapsing fever due to any Borrelia species other than Borrelia recurrentis 	`,`	null	`],
	[`	A68.9	`,`	Relapsing fever, unspecified 	`,`	null	`],
	[`	A69	`,`	Other spirochaetal infections 	`,`	null	`],
	[`	A69.0	`,`	Necrotizing ulcerative stomatitis Cancrum oris Fusospirochaetal gangrene Noma Stomatitis gangrenosa 	`,`	null	`],
	[`	A69.1	`,`	Other Vincent infections Fusospirochaetal pharyngitis Necrotizing ulcerative (acute): gingivitis gingivostomatitis Spirochaetal stomatitis Trench mouth Vincent: angina gingivitis 	`,`	null	`],
	[`	A69.2	`,`	Lyme disease Erythema chronicum migrans due to Borrelia burgdorferi 	`,`	null	`],
	[`	A69.8	`,`	Other specified spirochaetal infections 	`,`	null	`],
	[`	A69.9	`,`	Spirochaetal infection, unspecified 	`,`	null	`],
	[`	A70	`,`	Chlamydia psittaci infection Incl.: Ornithosis Parrot fever Psittacosis 	`,`	null	`],
	[`	A71	`,`	Trachoma Excl.: sequelae of trachoma (B94.0) 	`,`	null	`],
	[`	A71.0	`,`	Initial stage of trachoma Trachoma dubium 	`,`	null	`],
	[`	A71.1	`,`	Active stage of trachoma Granular conjunctivitis (trachomatous) Trachomatous: follicular conjunctivitis pannus 	`,`	null	`],
	[`	A71.9	`,`	Trachoma, unspecified 	`,`	null	`],
	[`	A74	`,`	Other diseases caused by chlamydiae Excl.: chlamydial pneumonia (J16.0) neonatal chlamydial: conjunctivitis (P39.1) pneumonia (P23.1) sexually transmitted chlamydial diseases (A55-A56) 	`,`	null	`],
	[`	A74.0	`,`	Chlamydial conjunctivitis (H13.1*) Paratrachoma 	`,`	null	`],
	[`	A74.8	`,`	Other chlamydial diseases Chlamydial peritonitis (K67.0*) 	`,`	null	`],
	[`	A74.9	`,`	Chlamydial infection, unspecified Chlamydiosis NOS 	`,`	null	`],
	[`	A75	`,`	Typhus fever Excl.: rickettsiosis due to Ehrlichia sennetsu (A79.8) 	`,`	null	`],
	[`	A75.0	`,`	Epidemic louse-borne typhus fever due to Rickettsia prowazekii Classical typhus (fever) Epidemic (louse-borne) typhus 	`,`	null	`],
	[`	A75.1	`,`	Recrudescent typhus [Brill disease] Brill-Zinsser disease 	`,`	null	`],
	[`	A75.2	`,`	Typhus fever due to Rickettsia typhi Murine (flea-borne) typhus 	`,`	null	`],
	[`	A75.3	`,`	Typhus fever due to Rickettsia tsutsugamushi Scrub (mite-borne) typhus Tsutsugamushi fever 	`,`	null	`],
	[`	A75.9	`,`	Typhus fever, unspecified Typhus (fever) NOS 	`,`	null	`],
	[`	A77	`,`	Spotted fever [tick-borne rickettsioses] 	`,`	null	`],
	[`	A77.0	`,`	Spotted fever due to Rickettsia rickettsii Rocky Mountain spotted fever Sao Paulo fever 	`,`	null	`],
	[`	A77.1	`,`	Spotted fever due to Rickettsia conorii African tick typhus Boutonneuse fever India tick typhus Kenya tick typhus Marseilles fever Mediterranean tick fever 	`,`	null	`],
	[`	A77.2	`,`	Spotted fever due to Rickettsia sibirica North Asian tick fever Siberian tick typhus 	`,`	null	`],
	[`	A77.3	`,`	Spotted fever due to Rickettsia australis Queensland tick typhus 	`,`	null	`],
	[`	A77.8	`,`	Other spotted fevers 	`,`	null	`],
	[`	A77.9	`,`	Spotted fever, unspecified Tick-borne typhus NOS 	`,`	null	`],
	[`	A78	`,`	Q fever Incl.: Infection due to Coxiella burnetii Nine Mile fever Quadrilateral fever 	`,`	null	`],
	[`	A79	`,`	Other rickettsioses 	`,`	null	`],
	[`	A79.0	`,`	Trench fever Quintan fever Wolhynian fever 	`,`	null	`],
	[`	A79.1	`,`	Rickettsialpox due to Rickettsia akari Kew Garden fever Vesicular rickettsiosis 	`,`	null	`],
	[`	A79.8	`,`	Other specified rickettsioses Rickettsiosis due to Ehrlichia sennetsu 	`,`	null	`],
	[`	A79.9	`,`	Rickettsiosis, unspecified Rickettsial infection NOS 	`,`	null	`],
	[`	A80	`,`	Acute poliomyelitis 	`,`	null	`],
	[`	A80.0	`,`	Acute paralytic poliomyelitis, vaccine-associated 	`,`	null	`],
	[`	A80.1	`,`	Acute paralytic poliomyelitis, wild virus, imported 	`,`	null	`],
	[`	A80.2	`,`	Acute paralytic poliomyelitis, wild virus, indigenous 	`,`	null	`],
	[`	A80.3	`,`	Acute paralytic poliomyelitis, other and unspecified 	`,`	null	`],
	[`	A80.4	`,`	Acute nonparalytic poliomyelitis 	`,`	null	`],
	[`	A80.9	`,`	Acute poliomyelitis, unspecified 	`,`	null	`],
	[`	A81	`,`	Atypical virus infections of central nervous system Incl.: prion diseases of the central nervous system 	`,`	null	`],
	[`	A81.0	`,`	Creutzfeldt-Jakob disease Subacute spongiform encephalopathy 	`,`	null	`],
	[`	A81.1	`,`	Subacute sclerosing panencephalitis Dawson inclusion body encephalitis Van Bogaert sclerosing leukoencephalopathy 	`,`	null	`],
	[`	A81.2	`,`	Progressive multifocal leukoencephalopathy Multifocal leukoencephalopathy NOS 	`,`	null	`],
	[`	A81.8	`,`	Other atypical virus infections of central nervous system Kuru 	`,`	null	`],
	[`	A81.9	`,`	Atypical virus infection of central nervous system, unspecified Prion disease of central nervous system NOS 	`,`	null	`],
	[`	A82	`,`	Rabies 	`,`	null	`],
	[`	A82.0	`,`	Sylvatic rabies 	`,`	null	`],
	[`	A82.1	`,`	Urban rabies 	`,`	null	`],
	[`	A82.9	`,`	Rabies, unspecified 	`,`	null	`],
	[`	A83	`,`	Mosquito-borne viral encephalitis Incl.: mosquito-borne viral meningoencephalitis Excl.: Venezuelan equine encephalitis (A92.2) 	`,`	null	`],
	[`	A83.0	`,`	Japanese encephalitis 	`,`	null	`],
	[`	A83.1	`,`	Western equine encephalitis 	`,`	null	`],
	[`	A83.2	`,`	Eastern equine encephalitis 	`,`	null	`],
	[`	A83.3	`,`	St Louis encephalitis 	`,`	null	`],
	[`	A83.4	`,`	Australian encephalitis Kunjin virus disease 	`,`	null	`],
	[`	A83.5	`,`	California encephalitis California meningoencephalitis La Crosse encephalitis 	`,`	null	`],
	[`	A83.6	`,`	Rocio virus disease 	`,`	null	`],
	[`	A83.8	`,`	Other mosquito-borne viral encephalitis 	`,`	null	`],
	[`	A83.9	`,`	Mosquito-borne viral encephalitis, unspecified 	`,`	null	`],
	[`	A84	`,`	Tick-borne viral encephalitis Incl.: tick-borne viral meningoencephalitis 	`,`	null	`],
	[`	A84.0	`,`	Far Eastern tick-borne encephalitis [Russian spring-summer encephalitis] 	`,`	null	`],
	[`	A84.1	`,`	Central European tick-borne encephalitis 	`,`	null	`],
	[`	A84.8	`,`	Other tick-borne viral encephalitis Louping ill Powassan virus disease 	`,`	null	`],
	[`	A84.9	`,`	Tick-borne viral encephalitis, unspecified 	`,`	null	`],
	[`	A85	`,`	Other viral encephalitis, not elsewhere classified Incl.: specified viral: encephalomyelitis NEC meningoencephalitis NEC Excl.: benign myalgic encephalomyelitis (G93.3) encephalitis due to: herpesvirus [herpes simplex] (B00.4) measles virus (B05.0) mumps virus (B26.2) poliomyelitis virus (A80.-) zoster (B02.0) lymphocytic choriomeningitis (A87.2) 	`,`	null	`],
	[`	A85.0	`,`	Enteroviral encephalitis (G05.1*) Enteroviral encephalomyelitis 	`,`	null	`],
	[`	A85.1	`,`	Adenoviral encephalitis (G05.1*) Adenoviral meningoencephalitis 	`,`	null	`],
	[`	A85.2	`,`	Arthropod-borne viral encephalitis, unspecified 	`,`	null	`],
	[`	A85.8	`,`	Other specified viral encephalitis Encephalitis lethargica Von Economo-Cruchet disease 	`,`	null	`],
	[`	A86	`,`	Unspecified viral encephalitis Incl.: Viral: encephalomyelitis NOS meningoencephalitis NOS 	`,`	null	`],
	[`	A87	`,`	Viral meningitis Excl.: meningitis due to: herpesvirus [herpes simplex] (B00.3) measles virus (B05.1) mumps virus (B26.1) poliomyelitis virus (A80.-) zoster (B02.1) 	`,`	null	`],
	[`	A87.0	`,`	Enteroviral meningitis (G02.0*) Coxsackievirus meningitis Echovirus meningitis 	`,`	null	`],
	[`	A87.1	`,`	Adenoviral meningitis (G02.0*) 	`,`	null	`],
	[`	A87.2	`,`	Lymphocytic choriomeningitis Lymphocytic meningoencephalitis 	`,`	null	`],
	[`	A87.8	`,`	Other viral meningitis 	`,`	null	`],
	[`	A87.9	`,`	Viral meningitis, unspecified 	`,`	null	`],
	[`	A88	`,`	Other viral infections of central nervous system, not elsewhere classified Excl.: viral: encephalitis NOS (A86) meningitis NOS (A87.9) 	`,`	null	`],
	[`	A88.0	`,`	Enteroviral exanthematous fever [Boston exanthem] 	`,`	null	`],
	[`	A88.1	`,`	Epidemic vertigo 	`,`	null	`],
	[`	A88.8	`,`	Other specified viral infections of central nervous system 	`,`	null	`],
	[`	A89	`,`	Unspecified viral infection of central nervous system 	`,`	null	`],
	[`	A90	`,`	Dengue fever [classical dengue] Excl.: dengue haemorrhagic fever (A91) 	`,`	null	`],
	[`	A91	`,`	Dengue haemorrhagic fever 	`,`	null	`],
	[`	A92	`,`	Other mosquito-borne viral fevers Excl.: Ross River disease (B33.1) 	`,`	null	`],
	[`	A92.0	`,`	Chikungunya virus disease Chikungunya (haemorrhagic) fever 	`,`	null	`],
	[`	A92.1	`,`	O'nyong-nyong fever 	`,`	null	`],
	[`	A92.2	`,`	Venezuelan equine fever Venezuelan equine: encephalitis encephalomyelitis virus disease 	`,`	null	`],
	[`	A92.3	`,`	West Nile virus infection West Nile fever 	`,`	null	`],
	[`	A92.4	`,`	Rift Valley fever 	`,`	null	`],
	[`	A92.8	`,`	Other specified mosquito-borne viral fevers 	`,`	null	`],
	[`	A92.9	`,`	Mosquito-borne viral fever, unspecified 	`,`	null	`],
	[`	A93	`,`	Other arthropod-borne viral fevers, not elsewhere classified 	`,`	null	`],
	[`	A93.0	`,`	Oropouche virus disease Oropouche fever 	`,`	null	`],
	[`	A93.1	`,`	Sandfly fever Pappataci fever Phlebotomus fever 	`,`	null	`],
	[`	A93.2	`,`	Colorado tick fever 	`,`	null	`],
	[`	A93.8	`,`	Other specified arthropod-borne viral fevers Piry virus disease Vesicular stomatitis virus disease [Indiana fever] 	`,`	null	`],
	[`	A94	`,`	Unspecified arthropod-borne viral fever Incl.: Arboviral fever NOS Arbovirus infection NOS 	`,`	null	`],
	[`	A95	`,`	Yellow fever 	`,`	null	`],
	[`	A95.0	`,`	Sylvatic yellow fever Jungle yellow fever 	`,`	null	`],
	[`	A95.1	`,`	Urban yellow fever 	`,`	null	`],
	[`	A95.9	`,`	Yellow fever, unspecified 	`,`	null	`],
	[`	A96	`,`	Arenaviral haemorrhagic fever 	`,`	null	`],
	[`	A96.0	`,`	Junin haemorrhagic fever Argentinian haemorrhagic fever 	`,`	null	`],
	[`	A96.1	`,`	Machupo haemorrhagic fever Bolivian haemorrhagic fever 	`,`	null	`],
	[`	A96.2	`,`	Lassa fever 	`,`	null	`],
	[`	A96.8	`,`	Other arenaviral haemorrhagic fevers 	`,`	null	`],
	[`	A96.9	`,`	Arenaviral haemorrhagic fever, unspecified 	`,`	null	`],
	[`	A98	`,`	Other viral haemorrhagic fevers, not elsewhere classified Excl.: chikungunya haemorrhagic fever (A92.0) dengue haemorrhagic fever (A91) 	`,`	null	`],
	[`	A98.0	`,`	Crimean-Congo haemorrhagic fever Central Asian haemorrhagic fever 	`,`	null	`],
	[`	A98.1	`,`	Omsk haemorrhagic fever 	`,`	null	`],
	[`	A98.2	`,`	Kyasanur Forest disease 	`,`	null	`],
	[`	A98.3	`,`	Marburg virus disease 	`,`	null	`],
	[`	A98.4	`,`	Ebola virus disease 	`,`	null	`],
	[`	A98.5	`,`	Haemorrhagic fever with renal syndrome Haemorrhagic fever: epidemic Korean Russian Hantaan virus disease Hantanvirus disease with renal manifestations Nephropathia epidemica Excl.: hantavirus (cardio-)pulmonary syndrome (B33.4, J17.1*) 	`,`	null	`],
	[`	A98.8	`,`	Other specified viral haemorrhagic fevers 	`,`	null	`],
	[`	A99	`,`	Unspecified viral haemorrhagic fever 	`,`	null	`],
							
							
];								
							
							
							
					
							
				
	
let CodeRangeA ={
	f0:function(val1=(-1),val2=(0)){
		let Range1 = ACodes.slice(val1,val2);
		Range1.reverse();


		for(value1 in Range1){	
				document.getElementById('readout').innerHTML = `<br>Showing A Codes ${Range1.length} items(s)<br>
				Starts at: ${Range1[value1][0]}`;	    
				document.getElementById('acodesTR').outerHTML += `<tr><td style="background-color:navy;color:white;width:5%;padding:40px;border:2px solid white;font-weight:900;font-size:40px;text-align:center;">${Range1[value1][0]}</td><td style="background-color:black;color:white;width:90%;padding:20px;border:2px solid white;font-size:30px;">${Range1[value1][1]}</td><td style="background-color:navy;color:white;width:5%;padding:20px;border:2px solid white;font-weight:900;font-size:40px;text-align:center;">${Range1[value1][2]}</td></tr>`;	
		
		}

	},


};

	






	






