								
let BCodes = [								
								
	[`		`,`		`,`		`],
	[`	B00	`,`	Herpesviral [herpes simplex] infections Excl.: anogenital herpesviral infection (A60.-) congenital herpesviral infection (P35.2) gammaherpesviral mononucleosis (B27.0) herpangina (B08.5) 	`,`	null	`],
	[`	B00.0	`,`	Eczema herpeticum Kaposi varicelliform eruption 	`,`	null	`],
	[`	B00.1	`,`	Herpesviral vesicular dermatitis Herpes simplex: facialis labialis Vesicular dermatitis of: ear lip due to human (alpha) herpesvirus 2 	`,`	null	`],
	[`	B00.2	`,`	Herpesviral gingivostomatitis and pharyngotonsillitis Herpesviral pharyngitis 	`,`	null	`],
	[`	B00.3	`,`	Herpesviral meningitis (G02.0*) 	`,`	null	`],
	[`	B00.4	`,`	Herpesviral encephalitis (G05.1*) Herpesviral meningoencephalitis Simian B disease 	`,`	null	`],
	[`	B00.5	`,`	Herpesviral ocular disease Herpesviral: conjunctivitis (H13.1*) dermatitis of eyelid (H03.1*) iridocyclitis (H22.0*) iritis (H22.0*) keratitis (H19.1*) keratoconjunctivitis (H19.1*) uveitis, anterior (H22.0*) 	`,`	null	`],
	[`	B00.7	`,`	Disseminated herpesviral disease Herpesviral sepsis 	`,`	null	`],
	[`	B00.8	`,`	Other forms of herpesviral infection Herpesviral: hepatitis (K77.0*) whitlow (L99.8*) 	`,`	null	`],
	[`	B00.9	`,`	Herpesviral infection, unspecified Herpes simplex infection NOS 	`,`	null	`],
	[`	B01	`,`	Varicella [chickenpox] 	`,`	null	`],
	[`	B01.0	`,`	Varicella meningitis (G02.0*) 	`,`	null	`],
	[`	B01.1	`,`	Varicella encephalitis (G05.1*) Postchickenpox encephalitis Varicella encephalomyelitis 	`,`	null	`],
	[`	B01.2	`,`	Varicella pneumonia (J17.1*) 	`,`	null	`],
	[`	B01.8	`,`	Varicella with other complications 	`,`	null	`],
	[`	B01.9	`,`	Varicella without complication Varicella NOS 	`,`	null	`],
	[`	B02	`,`	Zoster [herpes zoster] Incl.: shingles zona 	`,`	null	`],
	[`	B02.0	`,`	Zoster encephalitis (G05.1*) Zoster meningoencephalitis 	`,`	null	`],
	[`	B02.1	`,`	Zoster meningitis (G02.0*) 	`,`	null	`],
	[`	B02.2	`,`	Zoster with other nervous system involvement Postherpetic: geniculate ganglionitis (G53.0*) polyneuropathy (G63.0*) trigeminal neuralgia (G53.0*) 	`,`	null	`],
	[`	B02.3	`,`	Zoster ocular disease Zoster: blepharitis (H03.1*) conjunctivitis (H13.1*) iridocyclitis (H22.0*) iritis (H22.0*) keratitis (H19.2*) keratoconjunctivitis (H19.2*) scleritis (H19.0*) 	`,`	null	`],
	[`	B02.7	`,`	Disseminated zoster 	`,`	null	`],
	[`	B02.8	`,`	Zoster with other complications 	`,`	null	`],
	[`	B02.9	`,`	Zoster without complication Zoster NOS 	`,`	null	`],
	[`	B03	`,`	Smallpox [Footnote: In 1980 the 33rd World Health Assembly declared that smallpox had been eradicated. The classification is maintained for surveillance purposes.] 	`,`	null	`],
	[`	B04	`,`	Monkeypox 	`,`	null	`],
	[`	B05	`,`	Measles Incl.: morbilli Excl.: subacute sclerosing panencephalitis (A81.1) 	`,`	null	`],
	[`	B05.0	`,`	Measles complicated by encephalitis (G05.1*) Postmeasles encephalitis 	`,`	null	`],
	[`	B05.1	`,`	Measles complicated by meningitis (G02.0*) Postmeasles meningitis 	`,`	null	`],
	[`	B05.2	`,`	Measles complicated by pneumonia (J17.1*) Postmeasles pneumonia 	`,`	null	`],
	[`	B05.3	`,`	Measles complicated by otitis media (H67.1*) Postmeasles otitis media 	`,`	null	`],
	[`	B05.4	`,`	Measles with intestinal complications 	`,`	null	`],
	[`	B05.8	`,`	Measles with other complications Measles keratitis and keratoconjunctivitis (H19.2*) 	`,`	null	`],
	[`	B05.9	`,`	Measles without complication Measles NOS 	`,`	null	`],
	[`	B06	`,`	Rubella [German measles] Excl.: congenital rubella (P35.0) 	`,`	null	`],
	[`	B06.0	`,`	Rubella with neurological complications Rubella: encephalitis (G05.1*) meningitis (G02.0*) meningoencephalitis (G05.1*) 	`,`	null	`],
	[`	B06.8	`,`	Rubella with other complications Rubella: arthritis (M01.4*) pneumonia (J17.1*) 	`,`	null	`],
	[`	B06.9	`,`	Rubella without complication Rubella NOS 	`,`	null	`],
	[`	B07	`,`	Viral warts Incl.: Verruca: simplex vulgaris Excl.: anogenital (venereal) warts (A63.0) papilloma of: bladder (D41.4) cervix (D26.0) larynx (D14.1) 	`,`	null	`],
	[`	B08	`,`	Other viral infections characterized by skin and mucous membrane lesions, not elsewhere classified Excl.: vesicular stomatitis virus disease (A93.8) 	`,`	null	`],
	[`	B08.0	`,`	Other orthopoxvirus infections Cowpox Orf virus disease Pseudocowpox [milker node] Vaccinia Excl.: monkeypox (B04) 	`,`	null	`],
	[`	B08.1	`,`	Molluscum contagiosum 	`,`	null	`],
	[`	B08.2	`,`	Exanthema subitum [sixth disease] 	`,`	null	`],
	[`	B08.3	`,`	Erythema infectiosum [fifth disease] 	`,`	null	`],
	[`	B08.4	`,`	Enteroviral vesicular stomatitis with exanthem Hand, foot and mouth disease 	`,`	null	`],
	[`	B08.5	`,`	Enteroviral vesicular pharyngitis Herpangina 	`,`	null	`],
	[`	B08.8	`,`	Other specified viral infections characterized by skin and mucous membrane lesions Enteroviral lymphonodular pharyngitis Foot-and-mouth disease Tanapox virus disease Yaba pox virus disease 	`,`	null	`],
	[`	B09	`,`	Unspecified viral infection characterized by skin and mucous membrane lesions Incl.: Viral: enanthema NOS exanthema NOS 	`,`	null	`],
	[`	B15	`,`	Acute hepatitis A 	`,`	null	`],
	[`	B15.0	`,`	Hepatitis A with hepatic coma 	`,`	null	`],
	[`	B15.9	`,`	Hepatitis A without hepatic coma Hepatitis A (acute)(viral) NOS 	`,`	null	`],
	[`	B16	`,`	Acute hepatitis B 	`,`	null	`],
	[`	B16.0	`,`	Acute hepatitis B with delta-agent (coinfection) with hepatic coma 	`,`	null	`],
	[`	B16.1	`,`	Acute hepatitis B with delta-agent (coinfection) without hepatic coma 	`,`	null	`],
	[`	B16.2	`,`	Acute hepatitis B without delta-agent with hepatic coma 	`,`	null	`],
	[`	B16.9	`,`	Acute hepatitis B without delta-agent and without hepatic coma Hepatitis B (acute)(viral) NOS 	`,`	null	`],
	[`	B17	`,`	Other acute viral hepatitis 	`,`	null	`],
	[`	B17.0	`,`	Acute delta-(super)infection of hepatitis B carrier 	`,`	null	`],
	[`	B17.1	`,`	Acute hepatitis C 	`,`	null	`],
	[`	B17.2	`,`	Acute hepatitis E 	`,`	null	`],
	[`	B17.8	`,`	Other specified acute viral hepatitis Hepatitis non-A non-B (acute)(viral) NEC 	`,`	null	`],
	[`	B17.9	`,`	Acute viral hepatitis, unspecified Acute hepatitis, NOS Acute infectious hepatitis NOS 	`,`	null	`],
	[`	B18	`,`	Chronic viral hepatitis 	`,`	null	`],
	[`	B18.0	`,`	Chronic viral hepatitis B with delta-agent 	`,`	null	`],
	[`	B18.1	`,`	Chronic viral hepatitis B without delta-agent Chronic (viral) hepatitis B 	`,`	null	`],
	[`	B18.2	`,`	Chronic viral hepatitis C 	`,`	null	`],
	[`	B18.8	`,`	Other chronic viral hepatitis 	`,`	null	`],
	[`	B18.9	`,`	Chronic viral hepatitis, unspecified 	`,`	null	`],
	[`	B19	`,`	Unspecified viral hepatitis 	`,`	null	`],
	[`	B19.0	`,`	Unspecified viral hepatitis with hepatic coma 	`,`	null	`],
	[`	B19.9	`,`	Unspecified viral hepatitis without hepatic coma Viral hepatitis NOS 	`,`	null	`],
	[`	B20	`,`	Human immunodeficiency virus [HIV] disease resulting in infectious and parasitic diseases Excl.: acute HIV infection syndrome (B23.0) 	`,`	null	`],
	[`	B20.0	`,`	HIV disease resulting in mycobacterial infection HIV disease resulting in tuberculosis 	`,`	null	`],
	[`	B20.1	`,`	HIV disease resulting in other bacterial infections 	`,`	null	`],
	[`	B20.2	`,`	HIV disease resulting in cytomegaloviral disease 	`,`	null	`],
	[`	B20.3	`,`	HIV disease resulting in other viral infections 	`,`	null	`],
	[`	B20.4	`,`	HIV disease resulting in candidiasis 	`,`	null	`],
	[`	B20.5	`,`	HIV disease resulting in other mycoses 	`,`	null	`],
	[`	B20.6	`,`	HIV disease resulting in Pneumocystis jirovecii pneumonia HIV disease resulting in Pneumocystis carinii pneumonia 	`,`	null	`],
	[`	B20.7	`,`	HIV disease resulting in multiple infections 	`,`	null	`],
	[`	B20.8	`,`	HIV disease resulting in other infectious and parasitic diseases 	`,`	null	`],
	[`	B20.9	`,`	HIV disease resulting in unspecified infectious or parasitic disease HIV disease resulting in infection NOS 	`,`	null	`],
	[`	B21	`,`	Human immunodeficiency virus [HIV] disease resulting in malignant neoplasms 	`,`	null	`],
	[`	B21.0	`,`	HIV disease resulting in Kaposi sarcoma 	`,`	null	`],
	[`	B21.1	`,`	HIV disease resulting in Burkitt lymphoma 	`,`	null	`],
	[`	B21.2	`,`	HIV disease resulting in other types of non-Hodgkin lymphoma 	`,`	null	`],
	[`	B21.3	`,`	HIV disease resulting in other malignant neoplasms of lymphoid, haematopoietic and related tissue 	`,`	null	`],
	[`	B21.7	`,`	HIV disease resulting in multiple malignant neoplasms 	`,`	null	`],
	[`	B21.8	`,`	HIV disease resulting in other malignant neoplasms 	`,`	null	`],
	[`	B21.9	`,`	HIV disease resulting in unspecified malignant neoplasm 	`,`	null	`],
	[`	B22	`,`	Human immunodeficiency virus [HIV] disease resulting in other specified diseases 	`,`	null	`],
	[`	B22.0	`,`	HIV disease resulting in encephalopathy HIV dementia 	`,`	null	`],
	[`	B22.1	`,`	HIV disease resulting in lymphoid interstitial pneumonitis 	`,`	null	`],
	[`	B22.2	`,`	HIV disease resulting in wasting syndrome HIV disease resulting in failure to thrive Slim disease 	`,`	null	`],
	[`	B22.7	`,`	HIV disease resulting in multiple diseases classified elsewhere Note: For use of this category, reference should be made to the morbidity or mortality coding rules and guidelines in Volume 2. 	`,`	null	`],
	[`	B23	`,`	Human immunodeficiency virus [HIV] disease resulting in other conditions 	`,`	null	`],
	[`	B23.0	`,`	Acute HIV infection syndrome 	`,`	null	`],
	[`	B23.1	`,`	HIV disease resulting in (persistent) generalized lymphadenopathy 	`,`	null	`],
	[`	B23.2	`,`	HIV disease resulting in haematological and immunological abnormalities, not elsewhere classified 	`,`	null	`],
	[`	B23.8	`,`	HIV disease resulting in other specified conditions 	`,`	null	`],
	[`	B24	`,`	Unspecified human immunodeficiency virus [HIV] disease Incl.: Acquired immunodeficiency syndrome [AIDS] NOS AIDS-related complex [ARC] NOS 	`,`	null	`],
	[`	B25	`,`	Cytomegaloviral disease Excl.: congenital cytomegalovirus infection (P35.1) cytomegaloviral mononucleosis (B27.1) 	`,`	null	`],
	[`	B25.0	`,`	Cytomegaloviral pneumonitis (J17.1*) 	`,`	null	`],
	[`	B25.1	`,`	Cytomegaloviral hepatitis (K77.0*) 	`,`	null	`],
	[`	B25.2	`,`	Cytomegaloviral pancreatitis (K87.1*) 	`,`	null	`],
	[`	B25.8	`,`	Other cytomegaloviral diseases 	`,`	null	`],
	[`	B25.9	`,`	Cytomegaloviral disease, unspecified 	`,`	null	`],
	[`	B26	`,`	Mumps Incl.: parotitis: epidemic infectious 	`,`	null	`],
	[`	B26.0	`,`	Mumps orchitis (N51.1*) 	`,`	null	`],
	[`	B26.1	`,`	Mumps meningitis (G02.0*) 	`,`	null	`],
	[`	B26.2	`,`	Mumps encephalitis (G05.1*) 	`,`	null	`],
	[`	B26.3	`,`	Mumps pancreatitis (K87.1*) 	`,`	null	`],
	[`	B26.8	`,`	Mumps with other complications Mumps: arthritis (M01.5*) myocarditis (I41.1*) nephritis (N08.0*) polyneuropathy (G63.0*) 	`,`	null	`],
	[`	B26.9	`,`	Mumps without complication Mumps: NOS parotitis NOS 	`,`	null	`],
	[`	B27	`,`	Infectious mononucleosis Incl.: glandular fever monocytic angina Pfeiffer disease 	`,`	null	`],
	[`	B27.0	`,`	Gammaherpesviral mononucleosis Mononucleosis due to Epstein-Barr virus 	`,`	null	`],
	[`	B27.1	`,`	Cytomegaloviral mononucleosis 	`,`	null	`],
	[`	B27.8	`,`	Other infectious mononucleosis 	`,`	null	`],
	[`	B27.9	`,`	Infectious mononucleosis, unspecified 	`,`	null	`],
	[`	B30	`,`	Viral conjunctivitis Excl.: ocular disease: herpesviral [herpes simplex] (B00.5) zoster (B02.3) 	`,`	null	`],
	[`	B30.0	`,`	Keratoconjunctivitis due to adenovirus (H19.2*) Epidemic keratoconjunctivitis Shipyard eye 	`,`	null	`],
	[`	B30.1	`,`	Conjunctivitis due to adenovirus (H13.1*) Acute adenoviral follicular conjunctivitis Swimming-pool conjunctivitis 	`,`	null	`],
	[`	B30.2	`,`	Viral pharyngoconjunctivitis 	`,`	null	`],
	[`	B30.3	`,`	Acute epidemic haemorrhagic conjunctivitis (enteroviral) (H13.1*) Conjunctivitis due to: coxsackievirus 24 enterovirus 70 Haemorrhagic conjunctivitis (acute)(epidemic) 	`,`	null	`],
	[`	B30.8	`,`	Other viral conjunctivitis (H13.1*) Newcastle conjunctivitis 	`,`	null	`],
	[`	B30.9	`,`	Viral conjunctivitis, unspecified 	`,`	null	`],
	[`	B33	`,`	Other viral diseases, not elsewhere classified 	`,`	null	`],
	[`	B33.0	`,`	Epidemic myalgia Bornholm disease 	`,`	null	`],
	[`	B33.1	`,`	Ross River disease Epidemic polyarthritis and exanthema Ross River fever 	`,`	null	`],
	[`	B33.2	`,`	Viral carditis 	`,`	null	`],
	[`	B33.3	`,`	Retrovirus infections, not elsewhere classified Retrovirus infection NOS 	`,`	null	`],
	[`	B33.4	`,`	Hantavirus (cardio-)pulmonary syndrome [HPS] [HCPS] (J17.1*) Hantavirus disease with pulmonary manifestations Sin Nombre virus disease Use additional code (N17.9), if desired, to identify any renal failure associated with HPS caused by the Andes, Bayou and Black Creek Canal hantavirus aetiologies. Excl.: haemorrhagic fever with renal manifestations (A98.5) 	`,`	null	`],
	[`	B33.8	`,`	Other specified viral diseases 	`,`	null	`],
	[`	B34	`,`	Viral infection of unspecified site Excl.: cytomegaloviral disease NOS (B25.9) herpesvirus [herpes simplex] infection NOS (B00.9) retrovirus infection NOS (B33.3) viral agents as the cause of diseases classified to other chapters (B97.-) 	`,`	null	`],
	[`	B34.0	`,`	Adenovirus infection, unspecified site 	`,`	null	`],
	[`	B34.1	`,`	Enterovirus infection, unspecified site Coxsackievirus infection NOS Echovirus infection NOS 	`,`	null	`],
	[`	B34.2	`,`	Coronavirus infection, unspecified site Excl.: severe acute respiratory syndrome [SARS] (U04.9) 	`,`	null	`],
	[`	B34.3	`,`	Parvovirus infection, unspecified site 	`,`	null	`],
	[`	B34.4	`,`	Papovavirus infection, unspecified site 	`,`	null	`],
	[`	B34.8	`,`	Other viral infections of unspecified site 	`,`	null	`],
	[`	B34.9	`,`	Viral infection, unspecified Viraemia NOS 	`,`	null	`],
	[`	B35	`,`	Dermatophytosis Incl.: favus infections due to species of Epidermophyton, Microsporum and Trichophyton tinea, any type except those in B36.- 	`,`	null	`],
	[`	B35.0	`,`	Tinea barbae and tinea capitis Beard ringworm Kerion Scalp ringworm Sycosis, mycotic 	`,`	null	`],
	[`	B35.1	`,`	Tinea unguium Dermatophytic onychia Dermatophytosis of nail Onychomycosis Ringworm of nails 	`,`	null	`],
	[`	B35.2	`,`	Tinea manuum Dermatophytosis of hand Hand ringworm 	`,`	null	`],
	[`	B35.3	`,`	Tinea pedis Athlete foot Dermatophytosis of foot Foot ringworm 	`,`	null	`],
	[`	B35.4	`,`	Tinea corporis Ringworm of the body 	`,`	null	`],
	[`	B35.5	`,`	Tinea imbricata Tokelau 	`,`	null	`],
	[`	B35.6	`,`	Tinea cruris Dhobi itch Groin ringworm Jock itch 	`,`	null	`],
	[`	B35.8	`,`	Other dermatophytoses Dermatophytosis: disseminated granulomatous 	`,`	null	`],
	[`	B35.9	`,`	Dermatophytosis, unspecified Ringworm NOS 	`,`	null	`],
	[`	B36	`,`	Other superficial mycoses 	`,`	null	`],
	[`	B36.0	`,`	Pityriasis versicolor Tinea: flava versicolor 	`,`	null	`],
	[`	B36.1	`,`	Tinea nigra Keratomycosis nigricans palmaris Microsporosis nigra Pityriasis nigra 	`,`	null	`],
	[`	B36.2	`,`	White piedra Tinea blanca 	`,`	null	`],
	[`	B36.3	`,`	Black piedra 	`,`	null	`],
	[`	B36.8	`,`	Other specified superficial mycoses 	`,`	null	`],
	[`	B36.9	`,`	Superficial mycosis, unspecified 	`,`	null	`],
	[`	B37	`,`	Candidiasis Incl.: candidosis moniliasis Excl.: neonatal candidiasis (P37.5) 	`,`	null	`],
	[`	B37.0	`,`	Candidal stomatitis Oral thrush 	`,`	null	`],
	[`	B37.1	`,`	Pulmonary candidiasis 	`,`	null	`],
	[`	B37.2	`,`	Candidiasis of skin and nail Candidal: onychia paronychia Excl.: diaper [napkin] dermatitis (L22) 	`,`	null	`],
	[`	B37.3	`,`	Candidiasis of vulva and vagina (N77.1*) Candidal vulvovaginitis Monilial vulvovaginitis Vaginal thrush 	`,`	null	`],
	[`	B37.4	`,`	Candidiasis of other urogenital sites Candidal: balanitis (N51.2*) urethritis (N37.0*) 	`,`	null	`],
	[`	B37.5	`,`	Candidal meningitis (G02.1*) 	`,`	null	`],
	[`	B37.6	`,`	Candidal endocarditis (I39.8*) 	`,`	null	`],
	[`	B37.7	`,`	Candidal sepsis 	`,`	null	`],
	[`	B37.8	`,`	Candidiasis of other sites Candidal: cheilitis enteritis 	`,`	null	`],
	[`	B37.9	`,`	Candidiasis, unspecified Thrush NOS 	`,`	null	`],
	[`	B38	`,`	Coccidioidomycosis 	`,`	null	`],
	[`	B38.0	`,`	Acute pulmonary coccidioidomycosis 	`,`	null	`],
	[`	B38.1	`,`	Chronic pulmonary coccidioidomycosis 	`,`	null	`],
	[`	B38.2	`,`	Pulmonary coccidioidomycosis, unspecified 	`,`	null	`],
	[`	B38.3	`,`	Cutaneous coccidioidomycosis 	`,`	null	`],
	[`	B38.4	`,`	Coccidioidomycosis meningitis (G02.1*) 	`,`	null	`],
	[`	B38.7	`,`	Disseminated coccidioidomycosis Generalized coccidioidomycosis 	`,`	null	`],
	[`	B38.8	`,`	Other forms of coccidioidomycosis 	`,`	null	`],
	[`	B38.9	`,`	Coccidioidomycosis, unspecified 	`,`	null	`],
	[`	B39	`,`	Histoplasmosis 	`,`	null	`],
	[`	B39.0	`,`	Acute pulmonary histoplasmosis capsulati 	`,`	null	`],
	[`	B39.1	`,`	Chronic pulmonary histoplasmosis capsulati 	`,`	null	`],
	[`	B39.2	`,`	Pulmonary histoplasmosis capsulati, unspecified 	`,`	null	`],
	[`	B39.3	`,`	Disseminated histoplasmosis capsulati Generalized histoplasmosis capsulati 	`,`	null	`],
	[`	B39.4	`,`	Histoplasmosis capsulati, unspecified American histoplasmosis 	`,`	null	`],
	[`	B39.5	`,`	Histoplasmosis duboisii African histoplasmosis 	`,`	null	`],
	[`	B39.9	`,`	Histoplasmosis, unspecified 	`,`	null	`],
	[`	B40	`,`	Blastomycosis Excl.: Brazilian blastomycosis (B41.-) keloidal blastomycosis (B48.0) 	`,`	null	`],
	[`	B40.0	`,`	Acute pulmonary blastomycosis 	`,`	null	`],
	[`	B40.1	`,`	Chronic pulmonary blastomycosis 	`,`	null	`],
	[`	B40.2	`,`	Pulmonary blastomycosis, unspecified 	`,`	null	`],
	[`	B40.3	`,`	Cutaneous blastomycosis 	`,`	null	`],
	[`	B40.7	`,`	Disseminated blastomycosis Generalized blastomycosis 	`,`	null	`],
	[`	B40.8	`,`	Other forms of blastomycosis 	`,`	null	`],
	[`	B40.9	`,`	Blastomycosis, unspecified 	`,`	null	`],
	[`	B41	`,`	Paracoccidioidomycosis Incl.: Brazilian blastomycosis Lutz disease 	`,`	null	`],
	[`	B41.0	`,`	Pulmonary paracoccidioidomycosis 	`,`	null	`],
	[`	B41.7	`,`	Disseminated paracoccidioidomycosis Generalized paracoccidioidomycosis 	`,`	null	`],
	[`	B41.8	`,`	Other forms of paracoccidioidomycosis 	`,`	null	`],
	[`	B41.9	`,`	Paracoccidioidomycosis, unspecified 	`,`	null	`],
	[`	B42	`,`	Sporotrichosis 	`,`	null	`],
	[`	B42.0	`,`	Pulmonary sporotrichosis (J99.8*) 	`,`	null	`],
	[`	B42.1	`,`	Lymphocutaneous sporotrichosis 	`,`	null	`],
	[`	B42.7	`,`	Disseminated sporotrichosis Generalized sporotrichosis 	`,`	null	`],
	[`	B42.8	`,`	Other forms of sporotrichosis 	`,`	null	`],
	[`	B42.9	`,`	Sporotrichosis, unspecified 	`,`	null	`],
	[`	B43	`,`	Chromomycosis and phaeomycotic abscess 	`,`	null	`],
	[`	B43.0	`,`	Cutaneous chromomycosis Dermatitis verrucosa 	`,`	null	`],
	[`	B43.1	`,`	Phaeomycotic brain abscess Cerebral chromomycosis 	`,`	null	`],
	[`	B43.2	`,`	Subcutaneous phaeomycotic abscess and cyst 	`,`	null	`],
	[`	B43.8	`,`	Other forms of chromomycosis 	`,`	null	`],
	[`	B43.9	`,`	Chromomycosis, unspecified 	`,`	null	`],
	[`	B44	`,`	Aspergillosis Incl.: aspergilloma 	`,`	null	`],
	[`	B44.0	`,`	Invasive pulmonary aspergillosis 	`,`	null	`],
	[`	B44.1	`,`	Other pulmonary aspergillosis 	`,`	null	`],
	[`	B44.2	`,`	Tonsillar aspergillosis 	`,`	null	`],
	[`	B44.7	`,`	Disseminated aspergillosis Generalized aspergillosis 	`,`	null	`],
	[`	B44.8	`,`	Other forms of aspergillosis 	`,`	null	`],
	[`	B44.9	`,`	Aspergillosis, unspecified 	`,`	null	`],
	[`	B45	`,`	Cryptococcosis 	`,`	null	`],
	[`	B45.0	`,`	Pulmonary cryptococcosis 	`,`	null	`],
	[`	B45.1	`,`	Cerebral cryptococcosis Cryptococcal meningitis (G02.1*) Cryptococcosis meningocerebralis 	`,`	null	`],
	[`	B45.2	`,`	Cutaneous cryptococcosis 	`,`	null	`],
	[`	B45.3	`,`	Osseous cryptococcosis 	`,`	null	`],
	[`	B45.7	`,`	Disseminated cryptococcosis Generalized cryptococcosis 	`,`	null	`],
	[`	B45.8	`,`	Other forms of cryptococcosis 	`,`	null	`],
	[`	B45.9	`,`	Cryptococcosis, unspecified 	`,`	null	`],
	[`	B46	`,`	Zygomycosis 	`,`	null	`],
	[`	B46.0	`,`	Pulmonary mucormycosis 	`,`	null	`],
	[`	B46.1	`,`	Rhinocerebral mucormycosis 	`,`	null	`],
	[`	B46.2	`,`	Gastrointestinal mucormycosis 	`,`	null	`],
	[`	B46.3	`,`	Cutaneous mucormycosis Subcutaneous mucormycosis 	`,`	null	`],
	[`	B46.4	`,`	Disseminated mucormycosis Generalized mucormycosis 	`,`	null	`],
	[`	B46.5	`,`	Mucormycosis, unspecified 	`,`	null	`],
	[`	B46.8	`,`	Other zygomycoses Entomophthoromycosis 	`,`	null	`],
	[`	B46.9	`,`	Zygomycosis, unspecified Phycomycosis NOS 	`,`	null	`],
	[`	B47	`,`	Mycetoma 	`,`	null	`],
	[`	B47.0	`,`	Eumycetoma Madura foot, mycotic Maduromycosis 	`,`	null	`],
	[`	B47.1	`,`	Actinomycetoma 	`,`	null	`],
	[`	B47.9	`,`	Mycetoma, unspecified Madura foot NOS 	`,`	null	`],
	[`	B48	`,`	Other mycoses, not elsewhere classified 	`,`	null	`],
	[`	B48.0	`,`	Lobomycosis Keloidal blastomycosis Lobo disease 	`,`	null	`],
	[`	B48.1	`,`	Rhinosporidiosis 	`,`	null	`],
	[`	B48.2	`,`	Allescheriasis Infection due to Pseudallescheria boydii Excl.: eumycetoma (B47.0) 	`,`	null	`],
	[`	B48.3	`,`	Geotrichosis Geotrichum stomatitis 	`,`	null	`],
	[`	B48.4	`,`	Penicillosis 	`,`	null	`],
	[`	B48.7	`,`	Opportunistic mycoses Mycoses caused by fungi of low virulence that can establish an infection only as a consequence of factors such as the presence of debilitating disease or the administration of immunosuppressive and other therapeutic agents or radiation therapy. Most of the causal fungi are normally saprophytic in soil and decaying vegetation. 	`,`	null	`],
	[`	B48.8	`,`	Other specified mycoses Adiaspiromycosis 	`,`	null	`],
	[`	B49	`,`	Unspecified mycosis Incl.: Fungaemia NOS 	`,`	nul	`],
	[`	B50	`,`	Plasmodium falciparum malaria Incl.: mixed infections of Plasmodium falciparum with any other Plasmodium species 	`,`	null	`],
	[`	B50.0	`,`	Plasmodium falciparum malaria with cerebral complications Cerebral malaria NOS 	`,`	null	`],
	[`	B50.8	`,`	Other severe and complicated Plasmodium falciparum malaria Severe or complicated Plasmodium falciparum malaria NOS 	`,`	null	`],
	[`	B50.9	`,`	Plasmodium falciparum malaria, unspecified 	`,`	null	`],
	[`	B51	`,`	Plasmodium vivax malaria Incl.: mixed infections of Plasmodium vivax with other Plasmodium species, except Plasmodium falciparum Excl.: when mixed with Plasmodium falciparum (B50.-) 	`,`	null	`],
	[`	B51.0	`,`	Plasmodium vivax malaria with rupture of spleen 	`,`	null	`],
	[`	B51.8	`,`	Plasmodium vivax malaria with other complications 	`,`	null	`],
	[`	B51.9	`,`	Plasmodium vivax malaria without complication Plasmodium vivax malaria NOS 	`,`	null	`],
	[`	B52	`,`	Plasmodium malariae malaria Incl.: mixed infections of Plasmodium malariae with other Plasmodium species, except Plasmodium falciparum and Plasmodium vivax Excl.: when mixed with Plasmodium: falciparum (B50.-) vivax (B51.-) 	`,`	null	`],
	[`	B52.0	`,`	Plasmodium malariae malaria with nephropathy 	`,`	null	`],
	[`	B52.8	`,`	Plasmodium malariae malaria with other complications 	`,`	null	`],
	[`	B52.9	`,`	Plasmodium malariae malaria without complication Plasmodium malariae malaria NOS 	`,`	null	`],
	[`	B53	`,`	Other parasitologically confirmed malaria 	`,`	null	`],
	[`	B53.0	`,`	Plasmodium ovale malaria Excl.: when mixed with Plasmodium: falciparum (B50.-) malariae (B52.-) vivax (B51.-) 	`,`	null	`],
	[`	B53.1	`,`	Malaria due to simian plasmodia Excl.: when mixed with Plasmodium: falciparum (B50.-) malariae (B52.-) ovale (B53.0) vivax (B51.-) 	`,`	null	`],
	[`	B53.8	`,`	Other parasitologically confirmed malaria, not elsewhere classified Parasitologically confirmed malaria NOS 	`,`	null	`],
	[`	B54	`,`	Unspecified malaria Incl.: Clinically diagnosed malaria without parasitological confirmation 	`,`	null	`],
	[`	B55	`,`	Leishmaniasis 	`,`	null	`],
	[`	B55.0	`,`	Visceral leishmaniasis Kala-azar Post-kala-azar dermal leishmaniasis 	`,`	null	`],
	[`	B55.1	`,`	Cutaneous leishmaniasis 	`,`	null	`],
	[`	B55.2	`,`	Mucocutaneous leishmaniasis 	`,`	null	`],
	[`	B55.9	`,`	Leishmaniasis, unspecified 	`,`	null	`],
	[`	B56	`,`	African trypanosomiasis 	`,`	null	`],
	[`	B56.0	`,`	Gambiense trypanosomiasis Infection due to Trypanosoma brucei gambiense West African sleeping sickness 	`,`	null	`],
	[`	B56.1	`,`	Rhodesiense trypanosomiasis East African sleeping sickness Infection due to Trypanosoma brucei rhodesiense 	`,`	null	`],
	[`	B56.9	`,`	African trypanosomiasis, unspecified Sleeping sickness NOS Trypanosomiasis NOS, in places where African trypanosomiasis is prevalent 	`,`	null	`],
	[`	B57	`,`	Chagas disease Incl.: American trypanosomiasis infection due to Trypanosoma cruzi 	`,`	null	`],
	[`	B57.0	`,`	Acute Chagas disease with heart involvement (I41.2*, I98.1*) Acute Chagas disease with: cardiovascular involvement NEC (I98.1*) myocarditis (I41.2*) 	`,`	null	`],
	[`	B57.1	`,`	Acute Chagas disease without heart involvement Acute Chagas disease NOS 	`,`	null	`],
	[`	B57.2	`,`	Chagas disease (chronic) with heart involvement American trypanosomiasis NOS Chagas disease (chronic) (with): NOS cardiovascular involvement NEC (I98.1*) myocarditis (I41.2*) Trypanosomiasis NOS, in places where Chagas disease is prevalent 	`,`	null	`],
	[`	B57.3	`,`	Chagas disease (chronic) with digestive system involvement 	`,`	null	`],
	[`	B57.4	`,`	Chagas disease (chronic) with nervous system involvement 	`,`	null	`],
	[`	B57.5	`,`	Chagas disease (chronic) with other organ involvement 	`,`	null	`],
	[`	B58	`,`	Toxoplasmosis Incl.: infection due to Toxoplasma gondii Excl.: congenital toxoplasmosis (P37.1) 	`,`	null	`],
	[`	B58.0	`,`	Toxoplasma oculopathy Toxoplasma chorioretinitis (H32.0*) 	`,`	null	`],
	[`	B58.1	`,`	Toxoplasma hepatitis (K77.0*) 	`,`	null	`],
	[`	B58.2	`,`	Toxoplasma meningoencephalitis (G05.2*) 	`,`	null	`],
	[`	B58.3	`,`	Pulmonary toxoplasmosis (J17.3*) 	`,`	null	`],
	[`	B58.8	`,`	Toxoplasmosis with other organ involvement Toxoplasma: myocarditis (I41.2*) myositis (M63.1*) 	`,`	null	`],
	[`	B58.9	`,`	Toxoplasmosis, unspecified 	`,`	null	`],
	[`	B59	`,`	Pneumocystosis (J17.3*) Incl.: Pneumonia due to: Pneumocystis carinii Pneumocystis jirovecii 	`,`	null	`],
	[`	B60	`,`	Other protozoal diseases, not elsewhere classified Excl.: cryptosporidiosis (A07.2) intestinal microsporidiosis (A07.8) isosporiasis (A07.3) 	`,`	null	`],
	[`	B60.0	`,`	Babesiosis Piroplasmosis 	`,`	null	`],
	[`	B60.1	`,`	Acanthamoebiasis Conjunctivitis due to Acanthamoeba (H13.1*) Keratoconjunctivitis due to Acanthamoeba (H19.2*) 	`,`	null	`],
	[`	B60.2	`,`	Naegleriasis Primary amoebic meningoencephalitis (G05.2*) 	`,`	null	`],
	[`	B60.8	`,`	Other specified protozoal diseases Microsporidiosis 	`,`	null	`],
	[`	B64	`,`	Unspecified protozoal disease 	`,`	null	`],
	[`	B65	`,`	Schistosomiasis [bilharziasis] Incl.: snail fever 	`,`	null	`],
	[`	B65.0	`,`	Schistosomiasis due to Schistosoma haematobium [urinary schistosomiasis] 	`,`	null	`],
	[`	B65.1	`,`	Schistosomiasis due to Schistosoma mansoni [intestinal schistosomiasis] 	`,`	null	`],
	[`	B65.2	`,`	Schistosomiasis due to Schistosoma japonicum Asiatic schistosomiasis 	`,`	null	`],
	[`	B65.3	`,`	Cercarial dermatitis Swimmer itch 	`,`	null	`],
	[`	B65.8	`,`	Other schistosomiases Infection due to Schistosoma: intercalatum mattheei mekongi 	`,`	null	`],
	[`	B65.9	`,`	Schistosomiasis, unspecified 	`,`	null	`],
	[`	B66	`,`	Other fluke infections 	`,`	null	`],
	[`	B66.0	`,`	Opisthorchiasis Infection due to: cat liver fluke Opisthorchis (felineus)(viverrini) 	`,`	null	`],
	[`	B66.1	`,`	Clonorchiasis Chinese liver fluke disease Infection due to Clonorchis sinensis Oriental liver fluke disease 	`,`	null	`],
	[`	B66.2	`,`	Dicrocoeliasis Infection due to Dicrocoelium dendriticum Lancet fluke infection 	`,`	null	`],
	[`	B66.3	`,`	Fascioliasis Infection due to Fasciola: gigantica hepatica indica Sheep liver fluke disease 	`,`	null	`],
	[`	B66.4	`,`	Paragonimiasis Infection due to Paragonimus species Lung fluke disease Pulmonary distomiasis 	`,`	null	`],
	[`	B66.5	`,`	Fasciolopsiasis Infection due to Fasciolopsis buski Intestinal distomiasis 	`,`	null	`],
	[`	B66.8	`,`	Other specified fluke infections Echinostomiasis Heterophyiasis Metagonimiasis Nanophyetiasis Watsoniasis 	`,`	null	`],
	[`	B66.9	`,`	Fluke infection, unspecified 	`,`	null	`],
	[`	B67	`,`	Echinococcosis Incl.: hydatidosis 	`,`	null	`],
	[`	B67.0	`,`	Echinococcus granulosus infection of liver 	`,`	null	`],
	[`	B67.1	`,`	Echinococcus granulosus infection of lung 	`,`	null	`],
	[`	B67.2	`,`	Echinococcus granulosus infection of bone 	`,`	null	`],
	[`	B67.3	`,`	Echinococcus granulosus infection, other and multiple sites 	`,`	null	`],
	[`	B67.4	`,`	Echinococcus granulosus infection, unspecified Dog tapeworm (infection) 	`,`	null	`],
	[`	B67.5	`,`	Echinococcus multilocularis infection of liver 	`,`	null	`],
	[`	B67.6	`,`	Echinococcus multilocularis infection, other and multiple sites 	`,`	null	`],
	[`	B67.7	`,`	Echinococcus multilocularis infection, unspecified 	`,`	null	`],
	[`	B67.8	`,`	Echinococcosis, unspecified, of liver 	`,`	null	`],
	[`	B67.9	`,`	Echinococcosis, other and unspecified Echinococcosis NOS 	`,`	null	`],
	[`	B68	`,`	Taeniasis Excl.: cysticercosis (B69.-) 	`,`	null	`],
	[`	B68.0	`,`	Taenia solium taeniasis Pork tapeworm (infection) 	`,`	null	`],
	[`	B68.1	`,`	Taenia saginata taeniasis Beef tapeworm (infection) Infection due to adult tapeworm Taenia saginata 	`,`	null	`],
	[`	B68.9	`,`	Taeniasis, unspecified 	`,`	null	`],
	[`	B69	`,`	Cysticercosis Incl.: cysticerciasis infection due to larval form of Taenia solium 	`,`	null	`],
	[`	B69.0	`,`	Cysticercosis of central nervous system 	`,`	null	`],
	[`	B69.1	`,`	Cysticercosis of eye 	`,`	null	`],
	[`	B69.8	`,`	Cysticercosis of other sites 	`,`	null	`],
	[`	B69.9	`,`	Cysticercosis, unspecified 	`,`	null	`],
	[`	B70	`,`	Diphyllobothriasis and sparganosis 	`,`	null	`],
	[`	B70.0	`,`	Diphyllobothriasis Diphyllobothrium (adult)(latum)(pacificum) infection Fish tapeworm (infection) Excl.: larval diphyllobothriasis (B70.1) 	`,`	null	`],
	[`	B70.1	`,`	Sparganosis Infection due to: Sparganum (mansoni)(proliferum) Spirometra larvae Larval diphyllobothriasis Spirometrosis 	`,`	null	`],
	[`	B71	`,`	Other cestode infections 	`,`	null	`],
	[`	B71.0	`,`	Hymenolepiasis Dwarf tapeworm (infection) Rat tapeworm (infection) 	`,`	null	`],
	[`	B71.1	`,`	Dipylidiasis 	`,`	null	`],
	[`	B71.8	`,`	Other specified cestode infections Coenurosis 	`,`	null	`],
	[`	B71.9	`,`	Cestode infection, unspecified Tapeworm (infection) NOS 	`,`	null	`],
	[`	B72	`,`	Dracunculiasis Incl.: Guinea worm infection Infection due to Dracunculus medinensis 	`,`	null	`],
	[`	B73	`,`	Onchocerciasis Incl.: Onchocerca volvulus infection Onchocercosis River blindness 	`,`	null	`],
	[`	B74	`,`	Filariasis Excl.: onchocerciasis (B73) tropical (pulmonary) eosinophilia NOS (J82) 	`,`	null	`],
	[`	B74.0	`,`	Filariasis due to Wuchereria bancrofti Bancroftian: elephantiasis filariasis 	`,`	null	`],
	[`	B74.1	`,`	Filariasis due to Brugia malayi 	`,`	null	`],
	[`	B74.2	`,`	Filariasis due to Brugia timori 	`,`	null	`],
	[`	B74.3	`,`	Loiasis Calabar swelling Eyeworm disease of Africa Loa loa infection 	`,`	null	`],
	[`	B74.4	`,`	Mansonelliasis Infection due to Mansonella: ozzardi perstans streptocerca 	`,`	null	`],
	[`	B74.8	`,`	Other filariases Dirofilariasis 	`,`	null	`],
	[`	B74.9	`,`	Filariasis, unspecified 	`,`	null	`],
	[`	B75	`,`	Trichinellosis Incl.: Infection due to Trichinella species Trichiniasis 	`,`	null	`],
	[`	B76	`,`	Hookworm diseases Incl.: uncinariasis 	`,`	null	`],
	[`	B76.0	`,`	Ancylostomiasis Infection due to Ancylostoma species 	`,`	null	`],
	[`	B76.1	`,`	Necatoriasis Infection due to Necator americanus 	`,`	null	`],
	[`	B76.8	`,`	Other hookworm diseases 	`,`	null	`],
	[`	B76.9	`,`	Hookworm disease, unspecified Cutaneous larva migrans NOS 	`,`	null	`],
	[`	B77	`,`	Ascariasis Incl.: ascaridiasis roundworm infection 	`,`	null	`],
	[`	B77.0	`,`	Ascariasis with intestinal complications 	`,`	null	`],
	[`	B77.8	`,`	Ascariasis with other complications 	`,`	null	`],
	[`	B77.9	`,`	Ascariasis, unspecified 	`,`	null	`],
	[`	B78	`,`	Strongyloidiasis Excl.: trichostrongyliasis (B81.2) 	`,`	null	`],
	[`	B78.0	`,`	Intestinal strongyloidiasis 	`,`	null	`],
	[`	B78.1	`,`	Cutaneous strongyloidiasis 	`,`	null	`],
	[`	B78.7	`,`	Disseminated strongyloidiasis 	`,`	null	`],
	[`	B78.9	`,`	Strongyloidiasis, unspecified 	`,`	null	`],
	[`	B79	`,`	Trichuriasis Incl.: Trichocephaliasis Whipworm (disease)(infection) 	`,`	null	`],
	[`	B80	`,`	Enterobiasis Incl.: Oxyuriasis Pinworm infection Threadworm infection 	`,`	null	`],
	[`	B81	`,`	Other intestinal helminthiases, not elsewhere classified Excl.: Angiostrongyliasis due to: Angiostrongylus cantonensis (B83.2) Parastrongylus cantonensis (B83.2) 	`,`	null	`],
	[`	B81.0	`,`	Anisakiasis Infection due to Anisakis larvae 	`,`	null	`],
	[`	B81.1	`,`	Intestinal capillariasis Capillariasis NOS Infection due to Capillaria philippinensis Excl.: hepatic capillariasis (B83.8) 	`,`	null	`],
	[`	B81.2	`,`	Trichostrongyliasis 	`,`	null	`],
	[`	B81.3	`,`	Intestinal angiostrongyliasis Angiostrongyliasis due to: Angiostrongylus cantonensis (B83.2) Parastrongylus cantonensis (B83.2) 	`,`	null	`],
	[`	B81.4	`,`	Mixed intestinal helminthiases Infection due to intestinal helminths classifiable to more than one of the categories B65.0-B81.3 and B81.8 Mixed helminthiasis NOS 	`,`	null	`],
	[`	B81.8	`,`	Other specified intestinal helminthiases Infection due to: Oesophagostomum species [oesophagostomiasis] Ternidens deminutus [ternidensiasis] Ternidens diminutus [ternidensiasis] 	`,`	null	`],
	[`	B82	`,`	Unspecified intestinal parasitism 	`,`	null	`],
	[`	B82.0	`,`	Intestinal helminthiasis, unspecified 	`,`	null	`],
	[`	B82.9	`,`	Intestinal parasitism, unspecified 	`,`	null	`],
	[`	B83	`,`	Other helminthiases Excl.: capillariasis: NOS (B81.1) intestinal (B81.1) 	`,`	null	`],
	[`	B83.0	`,`	Visceral larva migrans Toxocariasis 	`,`	null	`],
	[`	B83.1	`,`	Gnathostomiasis Wandering swelling 	`,`	null	`],
	[`	B83.2	`,`	Angiostrongyliasis due to Parastrongylus cantonensis Angiostrongyliasis due to Angiostrongylus cantonensis Eosinophilic meningoencephalitis (G05.2*) Excl.: intestinal angiostrongyliasis (B81.3) 	`,`	null	`],
	[`	B83.3	`,`	Syngamiasis Syngamosis 	`,`	null	`],
	[`	B83.4	`,`	Internal hirudiniasis Excl.: external hirudiniasis (B88.3) 	`,`	null	`],
	[`	B83.8	`,`	Other specified helminthiases Acanthocephaliasis Gongylonemiasis Hepatic capillariasis Metastrongyliasis Thelaziasis 	`,`	null	`],
	[`	B83.9	`,`	Helminthiasis, unspecified Worms NOS Excl.: intestinal helminthiasis NOS (B82.0) 	`,`	null	`],
	[`	B85	`,`	Pediculosis and phthiriasis 	`,`	null	`],
	[`	B85.0	`,`	Pediculosis due to Pediculus humanus capitis Head-louse infestation 	`,`	null	`],
	[`	B85.1	`,`	Pediculosis due to Pediculus humanus corporis Body-louse infestation 	`,`	null	`],
	[`	B85.2	`,`	Pediculosis, unspecified 	`,`	null	`],
	[`	B85.3	`,`	Phthiriasis Infestation by: crab-louse Phthirus pubis 	`,`	null	`],
	[`	B85.4	`,`	Mixed pediculosis and phthiriasis Infestation classifiable to more than one of the categories B85.0-B85.3 	`,`	null	`],
	[`	B86	`,`	Scabies Incl.: Sarcoptic itch 	`,`	null	`],
	[`	B87	`,`	Myiasis Incl.: infestation by larvae of flies 	`,`	null	`],
	[`	B87.0	`,`	Cutaneous myiasis Creeping myiasis 	`,`	null	`],
	[`	B87.1	`,`	Wound myiasis Traumatic myiasis 	`,`	null	`],
	[`	B87.2	`,`	Ocular myiasis 	`,`	null	`],
	[`	B87.3	`,`	Nasopharyngeal myiasis Laryngeal myiasis 	`,`	null	`],
	[`	B87.4	`,`	Aural myiasis 	`,`	null	`],
	[`	B87.8	`,`	Myiasis of other sites Genitourinary myiasis Intestinal myiasis 	`,`	null	`],
	[`	B87.9	`,`	Myiasis, unspecified 	`,`	null	`],
	[`	B88	`,`	Other infestations 	`,`	null	`],
	[`	B88.0	`,`	Other acariasis Acarine dermatitis Dermatitis due to: Demodex species Dermanyssus gallinae Liponyssoides sanguineus Trombiculosis Excl.: scabies (B86) 	`,`	null	`],
	[`	B88.1	`,`	Tungiasis [sandflea infestation] 	`,`	null	`],
	[`	B88.2	`,`	Other arthropod infestations Scarabiasis 	`,`	null	`],
	[`	B88.3	`,`	External hirudiniasis Leech infestation NOS Excl.: internal hirudiniasis (B83.4) 	`,`	null	`],
	[`	B88.8	`,`	Other specified infestations Ichthyoparasitism due to Vandellia cirrhosa Linguatulosis Porocephaliasis 	`,`	null	`],
	[`	B88.9	`,`	Infestation, unspecified Infestation (skin) NOS Infestation by mites NOS Skin parasites NOS 	`,`	null	`],
	[`	B89	`,`	Unspecified parasitic disease 	`,`	null	`],
	[`	B90	`,`	Sequelae of tuberculosis 	`,`	null	`],
	[`	B90.0	`,`	Sequelae of central nervous system tuberculosis 	`,`	null	`],
	[`	B90.1	`,`	Sequelae of genitourinary tuberculosis 	`,`	null	`],
	[`	B90.2	`,`	Sequelae of tuberculosis of bones and joints 	`,`	null	`],
	[`	B90.8	`,`	Sequelae of tuberculosis of other organs 	`,`	null	`],
	[`	B90.9	`,`	Sequelae of respiratory and unspecified tuberculosis Sequelae of tuberculosis NOS 	`,`	null	`],
	[`	B91	`,`	Sequelae of poliomyelitis Excl.: postpolio syndrome (G14) 	`,`	null	`],
	[`	B92	`,`	Sequelae of leprosy 	`,`	null	`],
	[`	B94	`,`	Sequelae of other and unspecified infectious and parasitic diseases 	`,`	null	`],
	[`	B94.0	`,`	Sequelae of trachoma 	`,`	null	`],
	[`	B94.1	`,`	Sequelae of viral encephalitis 	`,`	null	`],
	[`	B94.2	`,`	Sequelae of viral hepatitis 	`,`	null	`],
	[`	B94.8	`,`	Sequelae of other specified infectious and parasitic diseases 	`,`	null	`],
	[`	B94.9	`,`	Sequelae of unspecified infectious or parasitic disease 	`,`	null	`],
	[`	B95	`,`	Streptococcus and staphylococcus as the cause of diseases classified to other chapters 	`,`	null	`],
	[`	B95.0	`,`	Streptococcus, group A, as the cause of diseases classified to other chapters 	`,`	null	`],
	[`	B95.1	`,`	Streptococcus, group B, as the cause of diseases classified to other chapters 	`,`	null	`],
	[`	B95.2	`,`	Streptococcus, group D, as the cause of diseases classified to other chapters 	`,`	null	`],
	[`	B95.3	`,`	Streptococcus pneumoniae as the cause of diseases classified to other chapters 	`,`	null	`],
	[`	B95.4	`,`	Other streptococcus as the cause of diseases classified to other chapters 	`,`	null	`],
	[`	B95.5	`,`	Unspecified streptococcus as the cause of diseases classified to other chapters 	`,`	null	`],
	[`	B95.6	`,`	Staphylococcus aureus as the cause of diseases classified to other chapters 	`,`	null	`],
	[`	B95.7	`,`	Other staphylococcus as the cause of diseases classified to other chapters 	`,`	null	`],
	[`	B95.8	`,`	Unspecified staphylococcus as the cause of diseases classified to other chapters 	`,`	null	`],
	[`	B96	`,`	Other specified bacterial agents as the cause of diseases classified to other chapters 	`,`	null	`],
	[`	B96.0	`,`	Mycoplasma pneumoniae [M. pneumoniae] as the cause of diseases classified to other chapters Pleuro-pneumonia-like-organism [PPLO] 	`,`	null	`],
	[`	B96.1	`,`	Klebsiella pneumoniae [K. pneumoniae] as the cause of diseases classified to other chapters 	`,`	null	`],
	[`	B96.2	`,`	Escherichia coli [E. coli] as the cause of diseases classified to other chapters 	`,`	null	`],
	[`	B96.3	`,`	Haemophilus influenzae [H. influenzae] as the cause of diseases classified to other chapters 	`,`	null	`],
	[`	B96.4	`,`	Proteus (mirabilis)(morganii) as the cause of diseases classified to other chapters 	`,`	null	`],
	[`	B96.5	`,`	Pseudomonas (aeruginosa) as the cause of diseases classified to other chapters 	`,`	null	`],
	[`	B96.6	`,`	Bacillus fragilis [B. fragilis] as the cause of diseases classified to other chapters 	`,`	null	`],
	[`	B96.7	`,`	Clostridium perfringens [C. perfringens] as the cause of diseases classified to other chapters 	`,`	null	`],
	[`	B96.8	`,`	Other specified bacterial agents as the cause of diseases classified to other chapters 	`,`	null	`],
	[`	B97	`,`	Viral agents as the cause of diseases classified to other chapters 	`,`	null	`],
	[`	B97.0	`,`	Adenovirus as the cause of diseases classified to other chapters 	`,`	null	`],
	[`	B97.1	`,`	Enterovirus as the cause of diseases classified to other chapters Coxsackievirus Echovirus 	`,`	null	`],
	[`	B97.2	`,`	Coronavirus as the cause of diseases classified to other chapters 	`,`	null	`],
	[`	B97.3	`,`	Retrovirus as the cause of diseases classified to other chapters Lentivirus Oncovirus 	`,`	null	`],
	[`	B97.4	`,`	Respiratory syncytial virus as the cause of diseases classified to other chapters 	`,`	null	`],
	[`	B97.5	`,`	Reovirus as the cause of diseases classified to other chapters 	`,`	null	`],
	[`	B97.6	`,`	Parvovirus as the cause of diseases classified to other chapters 	`,`	null	`],
	[`	B97.7	`,`	Papillomavirus as the cause of diseases classified to other chapters 	`,`	null	`],
	[`	B97.8	`,`	Other viral agents as the cause of diseases classified to other chapters Human metapneumovirus 	`,`	null	`],
	[`	B98	`,`	Other specified infectious agents as the cause of diseases classified to other chapters 	`,`	null	`],
	[`	B98.0	`,`	Helicobacter pylori [H.pylori] as the cause of diseases classified to other chapters 	`,`	null	`],
	[`	B98.1	`,`	Vibrio vulnificus as the cause of diseases classified to other chapters 	`,`	null	`],
							
							
							
];								
			
							
							
				
	
let CodeRangeB ={
	f0:function(val1=(-1),val2=(0)){
		let Range1 = BCodes.slice(val1,val2);
		Range1.reverse();
		document.documentElement.innerHTML += `<br>Showing B Codes ${Range1.length} items(s)`;

		for(value1 in Range1){
			    document.documentElement.style.cssText += "background-color:tan;";
				document.getElementById('bcodesTR').outerHTML += `<tr><td style="background-color:navy;color:white;width:5%;padding:40px;border:2px solid white;font-weight:900;font-size:40px;text-align:center;">${Range1[value1][0]}</td><td style="background-color:black;color:white;width:90%;padding:20px;border:2px solid white;font-size:30px;">${Range1[value1][1]}</td><td style="background-color:navy;color:white;width:5%;padding:20px;border:2px solid white;font-weight:900;font-size:40px;text-align:center;">${Range1[value1][2]}</td></tr>`;			
		}

	},

};

	






	






