let CCodes =[								
								
								
	[`	ID	`,`	SYMPTOMS / PROBLEMS / ISSUES	`,`	SYSTEM	`],
	[`	C00	`,`	Malignant neoplasm of lip Excl.: skin of lip (C43.0, C44.0) 	`,`	null	`],
	[`	C00.0	`,`	External upper lip Upper lip: NOS lipstick area vermilion border 	`,`	null	`],
	[`	C00.1	`,`	External lower lip Lower lip: NOS lipstick area vermilion border 	`,`	null	`],
	[`	C00.2	`,`	External lip, unspecified Vermilion border NOS 	`,`	null	`],
	[`	C00.3	`,`	Upper lip, inner aspect Upper lip: buccal aspect frenulum mucosa oral aspect 	`,`	null	`],
	[`	C00.4	`,`	Lower lip, inner aspect Lower lip: buccal aspect frenulum mucosa oral aspect 	`,`	null	`],
	[`	C00.5	`,`	Lip, unspecified, inner aspect Lip, not specified whether upper or lower: buccal aspect frenulum mucosa oral aspect 	`,`	null	`],
	[`	C00.6	`,`	Commissure of lip 	`,`	null	`],
	[`	C00.8	`,`	Overlapping lesion of lip [See note 5 at the beginning of this chapter] 	`,`	null	`],
	[`	C00.9	`,`	Lip, unspecified 	`,`	null	`],
	[`	C01	`,`	Malignant neoplasm of base of tongue Incl.: Dorsal surface of base of tongue Fixed part of tongue NOS Posterior third of tongue 	`,`	null	`],
	[`	C02	`,`	Malignant neoplasm of other and unspecified parts of tongue 	`,`	null	`],
	[`	C02.0	`,`	Dorsal surface of tongue Anterior two-thirds of tongue, dorsal surface Excl.: dorsal surface of base of tongue (C01) 	`,`	null	`],
	[`	C02.1	`,`	Border of tongue Tip of tongue 	`,`	null	`],
	[`	C02.2	`,`	Ventral surface of tongue Anterior two-thirds of tongue, ventral surface Frenulum linguae 	`,`	null	`],
	[`	C02.3	`,`	Anterior two-thirds of tongue, part unspecified Middle third of tongue NOS Mobile part of tongue NOS 	`,`	null	`],
	[`	C02.4	`,`	Lingual tonsil Excl.: tonsil NOS (C09.9) 	`,`	null	`],
	[`	C02.8	`,`	Overlapping lesion of tongue [See note 5 at the beginning of this chapter] Malignant neoplasm of tongue whose point of origin cannot be classified to any one of the categories C01-C02.4 	`,`	null	`],
	[`	C02.9	`,`	Tongue, unspecified 	`,`	null	`],
	[`	C03	`,`	Malignant neoplasm of gum Incl.: alveolar (ridge) mucosa gingiva Excl.: malignant odontogenic neoplasms (C41.0-C41.1) 	`,`	null	`],
	[`	C03.0	`,`	Upper gum 	`,`	null	`],
	[`	C03.1	`,`	Lower gum 	`,`	null	`],
	[`	C03.9	`,`	Gum, unspecified 	`,`	null	`],
	[`	C04	`,`	Malignant neoplasm of floor of mouth 	`,`	null	`],
	[`	C04.0	`,`	Anterior floor of mouth Anterior to the premolar-canine junction 	`,`	null	`],
	[`	C04.1	`,`	Lateral floor of mouth 	`,`	null	`],
	[`	C04.8	`,`	Overlapping lesion of floor of mouth [See note 5 at the beginning of this chapter] 	`,`	null	`],
	[`	C04.9	`,`	Floor of mouth, unspecified 	`,`	null	`],
	[`	C05	`,`	Malignant neoplasm of palate 	`,`	null	`],
	[`	C05.0	`,`	Hard palate 	`,`	null	`],
	[`	C05.1	`,`	Soft palate Excl.: nasopharyngeal surface of soft palate (C11.3) 	`,`	null	`],
	[`	C05.2	`,`	Uvula 	`,`	null	`],
	[`	C05.8	`,`	Overlapping lesion of palate [See note 5 at the beginning of this chapter] 	`,`	null	`],
	[`	C05.9	`,`	Palate, unspecified Roof of mouth 	`,`	null	`],
	[`	C06	`,`	Malignant neoplasm of other and unspecified parts of mouth 	`,`	null	`],
	[`	C06.0	`,`	Cheek mucosa Buccal mucosa NOS Internal cheek 	`,`	null	`],
	[`	C06.1	`,`	Vestibule of mouth Buccal sulcus (upper)(lower) Labial sulcus (upper)(lower) 	`,`	null	`],
	[`	C06.2	`,`	Retromolar area 	`,`	null	`],
	[`	C06.8	`,`	Overlapping lesion of other and unspecified parts of mouth [See note 5 at the beginning of this chapter] 	`,`	null	`],
	[`	C06.9	`,`	Mouth, unspecified Minor salivary gland, unspecified site Oral cavity NOS 	`,`	null	`],
	[`	C07	`,`	Malignant neoplasm of parotid gland 	`,`	null	`],
	[`	C08	`,`	Malignant neoplasm of other and unspecified major salivary glands Excl.: malignant neoplasms of specified minor salivary glands which are classified according to their anatomical location malignant neoplasms of minor salivary glands NOS (C06.9) parotid gland (C07) 	`,`	null	`],
	[`	C08.0	`,`	Submandibular gland Submaxillary gland 	`,`	null	`],
	[`	C08.1	`,`	Sublingual gland 	`,`	null	`],
	[`	C08.8	`,`	Overlapping lesion of major salivary glands [See note 5 at the beginning of this chapter] Malignant neoplasm of major salivary glands whose point of origin cannot be classified to any one of the categories C07-C08.1 	`,`	null	`],
	[`	C08.9	`,`	Major salivary gland, unspecified Salivary gland (major) NOS 	`,`	null	`],
	[`	C09	`,`	Malignant neoplasm of tonsil Excl.: lingual tonsil (C02.4) pharyngeal tonsil (C11.1) 	`,`	null	`],
	[`	C09.0	`,`	Tonsillar fossa 	`,`	null	`],
	[`	C09.1	`,`	Tonsillar pillar (anterior)(posterior) 	`,`	null	`],
	[`	C09.8	`,`	Overlapping lesion of tonsil [See note 5 at the beginning of this chapter] 	`,`	null	`],
	[`	C09.9	`,`	Tonsil, unspecified Tonsil: NOS faucial palatine 	`,`	null	`],
	[`	C10	`,`	Malignant neoplasm of oropharynx Excl.: tonsil (C09.-) 	`,`	null	`],
	[`	C10.0	`,`	Vallecula 	`,`	null	`],
	[`	C10.1	`,`	Anterior surface of epiglottis Epiglottis, free border [margin] Glossoepiglottic fold(s) Excl.: epiglottis (suprahyoid portion) NOS (C32.1) 	`,`	null	`],
	[`	C10.2	`,`	Lateral wall of oropharynx 	`,`	null	`],
	[`	C10.3	`,`	Posterior wall of oropharynx 	`,`	null	`],
	[`	C10.4	`,`	Branchial cleft Branchial cyst [site of neoplasm] 	`,`	null	`],
	[`	C10.8	`,`	Overlapping lesion of oropharynx [See note 5 at the beginning of this chapter] Junctional region of oropharynx 	`,`	null	`],
	[`	C10.9	`,`	Oropharynx, unspecified 	`,`	null	`],
	[`	C11	`,`	Malignant neoplasm of nasopharynx 	`,`	null	`],
	[`	C11.0	`,`	Superior wall of nasopharynx Roof of nasopharynx 	`,`	null	`],
	[`	C11.1	`,`	Posterior wall of nasopharynx Adenoid Pharyngeal tonsil 	`,`	null	`],
	[`	C11.2	`,`	Lateral wall of nasopharynx Fossa of Rosenmuller Opening of auditory tube Pharyngeal recess 	`,`	null	`],
	[`	C11.3	`,`	Anterior wall of nasopharynx Floor of nasopharynx Nasopharyngeal (anterior)(posterior) surface of soft palate Posterior margin of nasal: choana septum 	`,`	null	`],
	[`	C11.8	`,`	Overlapping lesion of nasopharynx [See note 5 at the beginning of this chapter] 	`,`	null	`],
	[`	C11.9	`,`	Nasopharynx, unspecified Nasopharyngeal wall NOS 	`,`	null	`],
	[`	C12	`,`	Malignant neoplasm of piriform sinus Incl.: Piriform fossa 	`,`	null	`],
	[`	C13	`,`	Malignant neoplasm of hypopharynx Excl.: piriform sinus (C12) 	`,`	null	`],
	[`	C13.0	`,`	Postcricoid region 	`,`	null	`],
	[`	C13.1	`,`	Aryepiglottic fold, hypopharyngeal aspect Aryepiglottic fold: NOS marginal zone Excl.: aryepiglottic fold, laryngeal aspect (C32.1) 	`,`	null	`],
	[`	C13.2	`,`	Posterior wall of hypopharynx 	`,`	null	`],
	[`	C13.8	`,`	Overlapping lesion of hypopharynx [See note 5 at the beginning of this chapter] 	`,`	null	`],
	[`	C13.9	`,`	Hypopharynx, unspecified Hypopharyngeal wall NOS 	`,`	null	`],
	[`	C14	`,`	Malignant neoplasm of other and ill-defined sites in the lip, oral cavity and pharynx Excl.: oral cavity NOS (C06.9) 	`,`	null	`],
	[`	C14.0	`,`	Pharynx, unspecified 	`,`	null	`],
	[`	C14.2	`,`	Waldeyer ring 	`,`	null	`],
	[`	C14.8	`,`	Overlapping lesion of lip, oral cavity and pharynx 	`,`	null	`],
	[`	C00-C97 	`,`	Malignant neoplasms 	`,`	null	`],
	[`	C00-C75 	`,`	Malignant neoplasms, stated or presumed to be primary, of specified sites, except of lymphoid, haematopoietic and related tissue 	`,`	null	`],
	[`	C00-C14	`,`	Malignant neoplasms of lip, oral cavity and pharynx 	`,`	null	`],
	[`	C15-C26 	`,`	Malignant neoplasms of digestive organs 	`,`	null	`],
	[`	C30-C39	`,`	Malignant neoplasms of respiratory and intrathoracic organs 	`,`	null	`],
	[`	C40-C41	`,`	Malignant neoplasms of bone and articular cartilage 	`,`	null	`],
	[`	C43-C44	`,`	Melanoma and other malignant neoplasms of skin 	`,`	null	`],
	[`	C45-C49 	`,`	Malignant neoplasms of mesothelial and soft tissue 	`,`	null	`],
	[`	C50-C50 	`,`	Malignant neoplasm of breast 	`,`	null	`],
	[`	C51-C58 	`,`	Malignant neoplasms of female genital organs 	`,`	null	`],
	[`	C60-C63 	`,`	Malignant neoplasms of male genital organs 	`,`	null	`],
	[`	C64-C68 	`,`	Malignant neoplasms of urinary tract 	`,`	null	`],
	[`	C69-C72 	`,`	Malignant neoplasms of eye, brain and other parts of central nervous system 	`,`	null	`],
	[`	C73-C75 	`,`	Malignant neoplasms of thyroid and other endocrine glands 	`,`	null	`],
	[`	C76-C80 	`,`	Malignant neoplasms of ill-defined, secondary and unspecified sites 	`,`	null	`],
	[`	C76 	`,`	Malignant neoplasm of other and ill-defined sites 	`,`	null	`],
	[`	C77 	`,`	Secondary and unspecified malignant neoplasm of lymph nodes 	`,`	null	`],
	[`	C78 	`,`	Secondary malignant neoplasm of respiratory and digestive organs 	`,`	null	`],
	[`	C79	`,`	Secondary malignant neoplasm of other and unspecified sites 	`,`	null	`],
	[`	C80 	`,`	Malignant neoplasm, without specification of site 	`,`	null	`],
	[`	C81-C96 	`,`	Malignant neoplasms, stated or presumed to be primary, of lymphoid, haematopoietic and related tissue 	`,`	null	`],
	[`	C97-C97	`,`	Malignant neoplasms of independent (primary) multiple sites 	`,`	null	`],
	[`	D00-D09	`,`	In situ neoplasms 	`,`	null	`],
	[`	D10-D36	`,`	Benign neoplasms 	`,`	null	`],
	[`	D37-D48	`,`	Neoplasms of uncertain or unknown behaviour 	`,`	null	`],
	[`	E00-E07 	`,`	Disorders of thyroid gland 	`,`	null	`],
	[`	E10-E14 	`,`	Diabetes mellitus 	`,`	null	`],
	[`	E15-E16 	`,`	Other disorders of glucose regulation and pancreatic internal secretion 	`,`	null	`],
	[`	E20-E35 	`,`	Disorders of other endocrine glands 	`,`	null	`],
	[`	E40-E46 	`,`	Malnutrition 	`,`	null	`],
	[`	E50-E64 	`,`	Other nutritional deficiencies 	`,`	null	`],
	[`	E65-E68 	`,`	Obesity and other hyperalimentation 	`,`	null	`],
	[`	E70-E90 	`,`	Metabolic disorders 	`,`	null	`],
	[`	C15	`,`	Malignant neoplasm of oesophagus Note: Two alternative subclassifications are given: .0-.2 by anatomical description .3-.5 by thirds This departure from the principle that categories should be mutually exclusive is deliberate, since both forms of terminology are in use but the resulting anatomical divisions are not analogous. 	`,`	null	`],
	[`	C15.0	`,`	Cervical part of oesophagus 	`,`	null	`],
	[`	C15.1	`,`	Thoracic part of oesophagus 	`,`	null	`],
	[`	C15.2	`,`	Abdominal part of oesophagus 	`,`	null	`],
	[`	C15.3	`,`	Upper third of oesophagus 	`,`	null	`],
	[`	C15.4	`,`	Middle third of oesophagus 	`,`	null	`],
	[`	C15.5	`,`	Lower third of oesophagus 	`,`	null	`],
	[`	C15.8	`,`	Overlapping lesion of oesophagus [See note 5 at the beginning of this chapter] 	`,`	null	`],
	[`	C15.9	`,`	Oesophagus, unspecified 	`,`	null	`],
	[`	C16	`,`	Malignant neoplasm of stomach 	`,`	null	`],
	[`	C16.0	`,`	Cardia Cardiac orifice Cardio-oesophageal junction Gastro-oesophageal junction Oesophagus and stomach 	`,`	null	`],
	[`	C16.1	`,`	Fundus of stomach 	`,`	null	`],
	[`	C16.2	`,`	Body of stomach 	`,`	null	`],
	[`	C16.3	`,`	Pyloric antrum Gastric antrum 	`,`	null	`],
	[`	C16.4	`,`	Pylorus Prepylorus Pyloric canal 	`,`	null	`],
	[`	C16.5	`,`	Lesser curvature of stomach, unspecified Lesser curvature of stomach, not classifiable to C16.1-C16.4 	`,`	null	`],
	[`	C16.6	`,`	Greater curvature of stomach, unspecified Greater curvature of stomach, not classifiable to C16.0-C16.4 	`,`	null	`],
	[`	C16.8	`,`	Overlapping lesion of stomach [See note 5 at the beginning of this chapter] 	`,`	null	`],
	[`	C16.9	`,`	Stomach, unspecified Gastric cancer NOS 	`,`	null	`],
	[`	C17	`,`	Malignant neoplasm of small intestine 	`,`	null	`],
	[`	C17.0	`,`	Duodenum 	`,`	null	`],
	[`	C17.1	`,`	Jejunum 	`,`	null	`],
	[`	C17.2	`,`	Ileum Excl.: ileocaecal valve (C18.0) 	`,`	null	`],
	[`	C17.3	`,`	Meckel diverticulum 	`,`	null	`],
	[`	C17.8	`,`	Overlapping lesion of small intestine [See note 5 at the beginning of this chapter] 	`,`	null	`],
	[`	C17.9	`,`	Small intestine, unspecified 	`,`	null	`],
	[`	C18	`,`	Malignant neoplasm of colon 	`,`	null	`],
	[`	C18.0	`,`	Caecum Ileocaecal valve 	`,`	null	`],
	[`	C18.1	`,`	Appendix 	`,`	null	`],
	[`	C18.2	`,`	Ascending colon 	`,`	null	`],
	[`	C18.3	`,`	Hepatic flexure 	`,`	null	`],
	[`	C18.4	`,`	Transverse colon 	`,`	null	`],
	[`	C18.5	`,`	Splenic flexure 	`,`	null	`],
	[`	C18.6	`,`	Descending colon 	`,`	null	`],
	[`	C18.7	`,`	Sigmoid colon Sigmoid (flexure) Excl.: rectosigmoid junction (C19) 	`,`	null	`],
	[`	C18.8	`,`	Overlapping lesion of colon [See note 5 at the beginning of this chapter] 	`,`	null	`],
	[`	C18.9	`,`	Colon, unspecified Large intestine NOS 	`,`	null	`],
	[`	C19	`,`	Malignant neoplasm of rectosigmoid junction Incl.: Colon with rectum Rectosigmoid (colon) 	`,`	null	`],
	[`	C20	`,`	Malignant neoplasm of rectum Incl.: Rectal ampulla 	`,`	null	`],
	[`	C21	`,`	Malignant neoplasm of anus and anal canal 	`,`	null	`],
	[`	C21.0	`,`	Anus, unspecified Excl.: anal: margin (C43.5, C44.5) skin (C43.5, C44.5) perianal skin (C43.5, C44.5) 	`,`	null	`],
	[`	C21.1	`,`	Anal canal Anal sphincter 	`,`	null	`],
	[`	C21.2	`,`	Cloacogenic zone 	`,`	null	`],
	[`	C21.8	`,`	Overlapping lesion of rectum, anus and anal canal [See note 5 at the beginning of this chapter] Anorectal junction Anorectum Malignant neoplasm of rectum, anus and anal canal whose point of origin cannot be classified to any one of the categories C20-C21.2 	`,`	null	`],
	[`	C22	`,`	Malignant neoplasm of liver and intrahepatic bile ducts Excl.: biliary tract NOS (C24.9) secondary malignant neoplasm of liver (C78.7) 	`,`	null	`],
	[`	C22.0	`,`	Liver cell carcinoma Hepatocellular carcinoma Hepatoma 	`,`	null	`],
	[`	C22.1	`,`	Intrahepatic bile duct carcinoma Cholangiocarcinoma 	`,`	null	`],
	[`	C22.2	`,`	Hepatoblastoma 	`,`	null	`],
	[`	C22.3	`,`	Angiosarcoma of liver Kupffer cell sarcoma 	`,`	null	`],
	[`	C22.4	`,`	Other sarcomas of liver 	`,`	null	`],
	[`	C22.7	`,`	Other specified carcinomas of liver 	`,`	null	`],
	[`	C22.9	`,`	Liver, unspecified 	`,`	null	`],
	[`	C23	`,`	Malignant neoplasm of gallbladder 	`,`	null	`],
	[`	C24	`,`	Malignant neoplasm of other and unspecified parts of biliary tract Excl.: intrahepatic bile duct (C22.1) 	`,`	null	`],
	[`	C24.0	`,`	Extrahepatic bile duct Biliary duct or passage NOS Common bile duct Cystic duct Hepatic duct 	`,`	null	`],
	[`	C24.1	`,`	Ampulla of Vater 	`,`	null	`],
	[`	C24.8	`,`	Overlapping lesion of biliary tract [See note 5 at the beginning of this chapter] Malignant neoplasm involving both intrahepatic and extrahepatic bile ducts Malignant neoplasm of biliary tract whose point of origin cannot be classified to any one of the categories C22.0-C24.1 	`,`	null	`],
	[`	C24.9	`,`	Biliary tract, unspecified 	`,`	null	`],
	[`	C25	`,`	Malignant neoplasm of pancreas 	`,`	null	`],
	[`	C25.0	`,`	Head of pancreas 	`,`	null	`],
	[`	C25.1	`,`	Body of pancreas 	`,`	null	`],
	[`	C25.2	`,`	Tail of pancreas 	`,`	null	`],
	[`	C25.3	`,`	Pancreatic duct 	`,`	null	`],
	[`	C25.4	`,`	Endocrine pancreas Islets of Langerhans 	`,`	null	`],
	[`	C25.7	`,`	Other parts of pancreas Neck of pancreas 	`,`	null	`],
	[`	C25.8	`,`	Overlapping lesion of pancreas [See note 5 at the beginning of this chapter] 	`,`	null	`],
	[`	C25.9	`,`	Pancreas, unspecified 	`,`	null	`],
	[`	C26	`,`	Malignant neoplasm of other and ill-defined digestive organs Excl.: peritoneum and retroperitoneum (C48.-) 	`,`	null	`],
	[`	C26.0	`,`	Intestinal tract, part unspecified Intestine NOS 	`,`	null	`],
	[`	C26.1	`,`	Spleen Excl.: follicular lymphoma (C82.-) Hodgkin lymphoma (C81.-) mature T/NK-cell lymphomas (C84.-) non-follicular lymphoma (C83.-) non-Hodgkin lymphoma, other and unspecified types (C85.-) 	`,`	null	`],
	[`	C26.8	`,`	Overlapping lesion of digestive system [See note 5 at the beginning of this chapter] Malignant neoplasm of digestive organs whose point of origin cannot be classified to any one of the categories C15-C26.1 Excl.: cardio-oesophageal junction (C16.0) 	`,`	null	`],
	[`	C26.9	`,`	Ill-defined sites within the digestive system Alimentary canal or tract NOS Gastrointestinal tract NOS 	`,`	null	`],
	[`	C30	`,`	Malignant neoplasm of nasal cavity and middle ear 	`,`	null	`],
	[`	C30.0	`,`	Nasal cavity Cartilage of nose Concha, nasal Internal nose Septum of nose Vestibule of nose Excl.: nasal bone (C41.0) nose NOS (C76.0) olfactory bulb (C72.2) posterior margin of nasal septum and choana (C11.3) skin of nose (C43.3, C44.3) 	`,`	null	`],
	[`	C30.1	`,`	Middle ear Eustachian tube Inner ear Mastoid air cells Excl.: auricular canal (external) (C43.2, C44.2) bone of ear (meatus) (C41.0) cartilage of ear (C49.0) skin of (external) ear (C43.2, C44.2) 	`,`	null	`],
	[`	C31	`,`	Malignant neoplasm of accessory sinuses 	`,`	null	`],
	[`	C31.0	`,`	Maxillary sinus Antrum (Highmore)(maxillary) 	`,`	null	`],
	[`	C31.1	`,`	Ethmoidal sinus 	`,`	null	`],
	[`	C31.2	`,`	Frontal sinus 	`,`	null	`],
	[`	C31.3	`,`	Sphenoidal sinus 	`,`	null	`],
	[`	C31.8	`,`	Overlapping lesion of accessory sinuses [See note 5 at the beginning of this chapter] 	`,`	null	`],
	[`	C31.9	`,`	Accessory sinus, unspecified 	`,`	null	`],
	[`	C32	`,`	Malignant neoplasm of larynx 	`,`	null	`],
	[`	C32.0	`,`	Glottis Intrinsic larynx Vocal cord (true) NOS 	`,`	null	`],
	[`	C32.1	`,`	Supraglottis Aryepiglottic fold, laryngeal aspect Epiglottis (suprahyoid portion) NOS Extrinsic larynx False vocal cord Posterior (laryngeal) surface of epiglottis Ventricular bands Excl.: anterior surface of epiglottis (C10.1) aryepiglottic fold: NOS (C13.1) hypopharyngeal aspect (C13.1) marginal zone (C13.1) 	`,`	null	`],
	[`	C32.2	`,`	Subglottis 	`,`	null	`],
	[`	C32.3	`,`	Laryngeal cartilage 	`,`	null	`],
	[`	C32.8	`,`	Overlapping lesion of larynx [See note 5 at the beginning of this chapter] 	`,`	null	`],
	[`	C32.9	`,`	Larynx, unspecified 	`,`	null	`],
	[`	C33	`,`	Malignant neoplasm of trachea 	`,`	null	`],
	[`	C34	`,`	Malignant neoplasm of bronchus and lung 	`,`	null	`],
	[`	C34.0	`,`	Main bronchus Carina Hilus (of lung) 	`,`	null	`],
	[`	C34.1	`,`	Upper lobe, bronchus or lung 	`,`	null	`],
	[`	C34.2	`,`	Middle lobe, bronchus or lung 	`,`	null	`],
	[`	C34.3	`,`	Lower lobe, bronchus or lung 	`,`	null	`],
	[`	C34.8	`,`	Overlapping lesion of bronchus and lung [See note 5 at the beginning of this chapter] 	`,`	null	`],
	[`	C34.9	`,`	Bronchus or lung, unspecified 	`,`	null	`],
	[`	C37	`,`	Malignant neoplasm of thymus 	`,`	null	`],
	[`	C38	`,`	Malignant neoplasm of heart, mediastinum and pleura Excl.: mesothelioma (C45.-) 	`,`	null	`],
	[`	C38.0	`,`	Heart Pericardium Excl.: great vessels (C49.3) 	`,`	null	`],
	[`	C38.1	`,`	Anterior mediastinum 	`,`	null	`],
	[`	C38.2	`,`	Posterior mediastinum 	`,`	null	`],
	[`	C38.3	`,`	Mediastinum, part unspecified 	`,`	null	`],
	[`	C38.4	`,`	Pleura 	`,`	null	`],
	[`	C38.8	`,`	Overlapping lesion of heart, mediastinum and pleura [See note 5 at the beginning of this chapter] 	`,`	null	`],
	[`	C39	`,`	Malignant neoplasm of other and ill-defined sites in the respiratory system and intrathoracic organs Excl.: intrathoracic NOS (C76.1) thoracic NOS (C76.1) 	`,`	null	`],
	[`	C39.0	`,`	Upper respiratory tract, part unspecified 	`,`	null	`],
	[`	C39.8	`,`	Overlapping lesion of respiratory and intrathoracic organs [See note 5 at the beginning of this chapter] Malignant neoplasm of respiratory and intrathoracic organs whose point of origin cannot be classified to any one of the categories C30-C39.0 	`,`	null	`],
	[`	C39.9	`,`	Ill-defined sites within the respiratory system Respiratory tract NOS 	`,`	null	`],
	[`	C45	`,`	Mesothelioma Incl.: morphology code M905 with behaviour code /3 	`,`	null	`],
	[`	C45.0	`,`	Mesothelioma of pleura Excl.: other malignant neoplasms of pleura (C38.4) 	`,`	null	`],
	[`	C45.1	`,`	Mesothelioma of peritoneum Mesentery Mesocolon Omentum Peritoneum (parietal)(pelvic) Excl.: other malignant neoplasms of peritoneum (C48.-) 	`,`	null	`],
	[`	C45.2	`,`	Mesothelioma of pericardium Excl.: other malignant neoplasms of pericardium (C38.0) 	`,`	null	`],
	[`	C45.7	`,`	Mesothelioma of other sites 	`,`	null	`],
	[`	C45.9	`,`	Mesothelioma, unspecified 	`,`	null	`],
	[`	C46	`,`	Kaposi sarcoma Incl.: morphology code M9140 with behaviour code /3 	`,`	null	`],
	[`	C46.0	`,`	Kaposi sarcoma of skin 	`,`	null	`],
	[`	C46.1	`,`	Kaposi sarcoma of soft tissue 	`,`	null	`],
	[`	C46.2	`,`	Kaposi sarcoma of palate 	`,`	null	`],
	[`	C46.3	`,`	Kaposi sarcoma of lymph nodes 	`,`	null	`],
	[`	C46.7	`,`	Kaposi sarcoma of other sites 	`,`	null	`],
	[`	C46.8	`,`	Kaposi sarcoma of multiple organs 	`,`	null	`],
	[`	C46.9	`,`	Kaposi sarcoma, unspecified 	`,`	null	`],
	[`	C47	`,`	Malignant neoplasm of peripheral nerves and autonomic nervous system Incl.: sympathetic and parasympathetic nerves and ganglia 	`,`	null	`],
	[`	C47.0	`,`	Peripheral nerves of head, face and neck Excl.: peripheral nerves of orbit (C69.6) 	`,`	null	`],
	[`	C47.1	`,`	Peripheral nerves of upper limb, including shoulder 	`,`	null	`],
	[`	C47.2	`,`	Peripheral nerves of lower limb, including hip 	`,`	null	`],
	[`	C47.3	`,`	Peripheral nerves of thorax 	`,`	null	`],
	[`	C47.4	`,`	Peripheral nerves of abdomen 	`,`	null	`],
	[`	C47.5	`,`	Peripheral nerves of pelvis 	`,`	null	`],
	[`	C47.6	`,`	Peripheral nerves of trunk, unspecified 	`,`	null	`],
	[`	C47.8	`,`	Overlapping lesion of peripheral nerves and autonomic nervous system [See note 5 at the beginning of this chapter] 	`,`	null	`],
	[`	C47.9	`,`	Peripheral nerves and autonomic nervous system, unspecified 	`,`	null	`],
	[`	C48	`,`	Malignant neoplasm of retroperitoneum and peritoneum Excl.: Kaposi sarcoma (C46.1) mesothelioma (C45.-) 	`,`	null	`],
	[`	C48.0	`,`	Retroperitoneum 	`,`	null	`],
	[`	C48.1	`,`	Specified parts of peritoneum Mesentery Mesocolon Omentum Peritoneum: parietal pelvic 	`,`	null	`],
	[`	C48.2	`,`	Peritoneum, unspecified 	`,`	null	`],
	[`	C48.8	`,`	Overlapping lesion of retroperitoneum and peritoneum [See note 5 at the beginning of this chapter] 	`,`	null	`],
	[`	C49	`,`	Malignant neoplasm of other connective and soft tissue Incl.: blood vessel bursa cartilage fascia fat ligament, except uterine lymphatic vessel muscle synovia tendon (sheath) Excl.: cartilage (of): articular (C40-C41) larynx (C32.3) nose (C30.0) connective tissue of breast (C50.-) Kaposi sarcoma (C46.-) mesothelioma (C45.-) peripheral nerves and autonomic nervous system (C47.-) peritoneum (C48.-) retroperitoneum (C48.0) 	`,`	null	`],
	[`	C49.0	`,`	Connective and soft tissue of head, face and neck Connective tissue of: ear eyelid Excl.: connective tissue of orbit (C69.6) 	`,`	null	`],
	[`	C49.1	`,`	Connective and soft tissue of upper limb, including shoulder 	`,`	null	`],
	[`	C49.2	`,`	Connective and soft tissue of lower limb, including hip 	`,`	null	`],
	[`	C49.3	`,`	Connective and soft tissue of thorax Axilla Diaphragm Great vessels Excl.: breast (C50.-) heart (C38.0) mediastinum (C38.1-C38.3) thymus (C37) 	`,`	null	`],
	[`	C49.4	`,`	Connective and soft tissue of abdomen Abdominal wall Hypochondrium 	`,`	null	`],
	[`	C49.5	`,`	Connective and soft tissue of pelvis Buttock Groin Perineum 	`,`	null	`],
	[`	C49.6	`,`	Connective and soft tissue of trunk, unspecified Back NOS 	`,`	null	`],
	[`	C49.8	`,`	Overlapping lesion of connective and soft tissue [See note 5 at the beginning of this chapter] Malignant neoplasm of connective and soft tissue whose point of origin cannot be classified to any one of the categories C47-C49.6 	`,`	null	`],
	[`	C49.9	`,`	Connective and soft tissue, unspecified 	`,`	null	`],
	[`	C50	`,`	Malignant neoplasm of breast Incl.: connective tissue of breast Excl.: skin of breast (C43.5, C44.5) 	`,`	null	`],
	[`	C50.0	`,`	Nipple and areola 	`,`	null	`],
	[`	C50.1	`,`	Central portion of breast 	`,`	null	`],
	[`	C50.2	`,`	Upper-inner quadrant of breast 	`,`	null	`],
	[`	C50.3	`,`	Lower-inner quadrant of breast 	`,`	null	`],
	[`	C50.4	`,`	Upper-outer quadrant of breast 	`,`	null	`],
	[`	C50.5	`,`	Lower-outer quadrant of breast 	`,`	null	`],
	[`	C50.6	`,`	Axillary tail of breast 	`,`	null	`],
	[`	C50.8	`,`	Overlapping lesion of breast [See note 5 at the beginning of this chapter] 	`,`	null	`],
	[`	C50.9	`,`	Breast, unspecified 	`,`	null	`],
	[`	C51	`,`	Malignant neoplasm of vulva 	`,`	null	`],
	[`	C51.0	`,`	Labium majus Bartholin [greater vestibular] gland 	`,`	null	`],
	[`	C51.1	`,`	Labium minus 	`,`	null	`],
	[`	C51.2	`,`	Clitoris 	`,`	null	`],
	[`	C51.8	`,`	Overlapping lesion of vulva [See note 5 at the beginning of this chapter] 	`,`	null	`],
	[`	C51.9	`,`	Vulva, unspecified External female genitalia NOS Pudendum 	`,`	null	`],
	[`	C52	`,`	Malignant neoplasm of vagina 	`,`	null	`],
	[`	C53	`,`	Malignant neoplasm of cervix uteri 	`,`	null	`],
	[`	C53.0	`,`	Endocervix 	`,`	null	`],
	[`	C53.1	`,`	Exocervix 	`,`	null	`],
	[`	C53.8	`,`	Overlapping lesion of cervix uteri [See note 5 at the beginning of this chapter] 	`,`	null	`],
	[`	C53.9	`,`	Cervix uteri, unspecified 	`,`	null	`],
	[`	C54	`,`	Malignant neoplasm of corpus uteri 	`,`	null	`],
	[`	C54.0	`,`	Isthmus uteri Lower uterine segment 	`,`	null	`],
	[`	C54.1	`,`	Endometrium 	`,`	null	`],
	[`	C54.2	`,`	Myometrium 	`,`	null	`],
	[`	C54.3	`,`	Fundus uteri 	`,`	null	`],
	[`	C54.8	`,`	Overlapping lesion of corpus uteri [See note 5 at the beginning of this chapter] 	`,`	null	`],
	[`	C54.9	`,`	Corpus uteri, unspecified 	`,`	null	`],
	[`	C55	`,`	Malignant neoplasm of uterus, part unspecified 	`,`	null	`],
	[`	C56	`,`	Malignant neoplasm of ovary 	`,`	null	`],
	[`	C57	`,`	Malignant neoplasm of other and unspecified female genital organs 	`,`	null	`],
	[`	C57.0	`,`	Fallopian tube Oviduct Uterine tube 	`,`	null	`],
	[`	C57.1	`,`	Broad ligament 	`,`	null	`],
	[`	C57.2	`,`	Round ligament 	`,`	null	`],
	[`	C57.3	`,`	Parametrium Uterine ligament NOS 	`,`	null	`],
	[`	C57.4	`,`	Uterine adnexa, unspecified 	`,`	null	`],
	[`	C57.7	`,`	Other specified female genital organs Wolffian body or duct 	`,`	null	`],
	[`	C57.8	`,`	Overlapping lesion of female genital organs [See note 5 at the beginning of this chapter] Malignant neoplasm of female genital organs whose point of origin cannot be classified to any one of the categories C51-C57.7, C58 Tubo-ovarian Utero-ovarian 	`,`	null	`],
	[`	C57.9	`,`	Female genital organ, unspecified Female genitourinary tract NOS 	`,`	null	`],
	[`	C58	`,`	Malignant neoplasm of placenta Incl.: Choriocarcinoma NOS Chorionepithelioma NOS Excl.: chorioadenoma (destruens) (D39.2) hydatidiform mole: NOS (O01.9) invasive (D39.2) malignant (D39.2) 	`,`	null	`],
	[`	C60	`,`	Malignant neoplasm of penis 	`,`	null	`],
	[`	C60.0	`,`	Prepuce Foreskin 	`,`	null	`],
	[`	C60.1	`,`	Glans penis 	`,`	null	`],
	[`	C60.2	`,`	Body of penis Corpus cavernosum 	`,`	null	`],
	[`	C60.8	`,`	Overlapping lesion of penis [See note 5 at the beginning of this chapter] 	`,`	null	`],
	[`	C60.9	`,`	Penis, unspecified Skin of penis NOS 	`,`	null	`],
	[`	C61	`,`	Malignant neoplasm of prostate 	`,`	null	`],
	[`	C62	`,`	Malignant neoplasm of testis 	`,`	null	`],
	[`	C62.0	`,`	Undescended testis Ectopic testis [site of neoplasm] Retained testis [site of neoplasm] 	`,`	null	`],
	[`	C62.1	`,`	Descended testis Scrotal testis 	`,`	null	`],
	[`	C62.9	`,`	Testis, unspecified 	`,`	null	`],
	[`	C63	`,`	Malignant neoplasm of other and unspecified male genital organs 	`,`	null	`],
	[`	C63.0	`,`	Epididymis 	`,`	null	`],
	[`	C63.1	`,`	Spermatic cord 	`,`	null	`],
	[`	C63.2	`,`	Scrotum Skin of scrotum 	`,`	null	`],
	[`	C63.7	`,`	Other specified male genital organs Seminal vesicle Tunica vaginalis 	`,`	null	`],
	[`	C63.8	`,`	Overlapping lesion of male genital organs [See note 5 at the beginning of this chapter] Malignant neoplasm of male genital organs whose point of origin cannot be classified to any one of the categories C60-C63.7 	`,`	null	`],
	[`	C63.9	`,`	Male genital organ, unspecified Male genitourinary tract NOS 	`,`	null	`],
	[`	C64	`,`	Malignant neoplasm of kidney, except renal pelvis Excl.: renal: calyces (C65) pelvis (C65) 	`,`	null	`],
	[`	C65	`,`	Malignant neoplasm of renal pelvis Incl.: Pelviureteric junction Renal calyces 	`,`	null	`],
	[`	C66	`,`	Malignant neoplasm of ureter Excl.: ureteric orifice of bladder (C67.6) 	`,`	null	`],
	[`	C67	`,`	Malignant neoplasm of bladder 	`,`	null	`],
	[`	C67.0	`,`	Trigone of bladder 	`,`	null	`],
	[`	C67.1	`,`	Dome of bladder 	`,`	null	`],
	[`	C67.2	`,`	Lateral wall of bladder 	`,`	null	`],
	[`	C67.3	`,`	Anterior wall of bladder 	`,`	null	`],
	[`	C67.4	`,`	Posterior wall of bladder 	`,`	null	`],
	[`	C67.5	`,`	Bladder neck Internal urethral orifice 	`,`	null	`],
	[`	C67.6	`,`	Ureteric orifice 	`,`	null	`],
	[`	C67.7	`,`	Urachus 	`,`	null	`],
	[`	C67.8	`,`	Overlapping lesion of bladder [See note 5 at the beginning of this chapter] 	`,`	null	`],
	[`	C67.9	`,`	Bladder, unspecified 	`,`	null	`],
	[`	C68	`,`	Malignant neoplasm of other and unspecified urinary organs Excl.: genitourinary tract NOS: female (C57.9) male (C63.9) 	`,`	null	`],
	[`	C68.0	`,`	Urethra Excl.: urethral orifice of bladder (C67.5) 	`,`	null	`],
	[`	C68.1	`,`	Paraurethral gland 	`,`	null	`],
	[`	C68.8	`,`	Overlapping lesion of urinary organs [See note 5 at the beginning of this chapter] Malignant neoplasm of urinary organs whose point of origin cannot be classified to any one of the categories C64-C68.1 	`,`	null	`],
	[`	C68.9	`,`	Urinary organ, unspecified Urinary system NOS 	`,`	null	`],
	[`	C69	`,`	Malignant neoplasm of eye and adnexa Excl.: connective tissue of eyelid (C49.0) eyelid (skin) (C43.1, C44.1) optic nerve (C72.3) 	`,`	null	`],
	[`	C69.0	`,`	Conjunctiva 	`,`	null	`],
	[`	C69.1	`,`	Cornea 	`,`	null	`],
	[`	C69.2	`,`	Retina 	`,`	null	`],
	[`	C69.3	`,`	Choroid 	`,`	null	`],
	[`	C69.4	`,`	Ciliary body 	`,`	null	`],
	[`	C69.5	`,`	Lacrimal gland and duct Lacrimal sac Nasolacrimal duct 	`,`	null	`],
	[`	C69.6	`,`	Orbit Connective tissue of orbit Extraocular muscle Peripheral nerves of orbit Retrobulbar tissue Retro-ocular tissue Excl.: orbital bone (C41.0) 	`,`	null	`],
	[`	C69.8	`,`	Overlapping lesion of eye and adnexa [See note 5 at the beginning of this chapter] 	`,`	null	`],
	[`	C69.9	`,`	Eye, unspecified Eyeball 	`,`	null	`],
	[`	C70	`,`	Malignant neoplasm of meninges 	`,`	null	`],
	[`	C70.0	`,`	Cerebral meninges 	`,`	null	`],
	[`	C70.1	`,`	Spinal meninges 	`,`	null	`],
	[`	C70.9	`,`	Meninges, unspecified 	`,`	null	`],
	[`	C71	`,`	Malignant neoplasm of brain Excl.: cranial nerves (C72.2-C72.5) retrobulbar tissue (C69.6) 	`,`	null	`],
	[`	C71.0	`,`	Cerebrum, except lobes and ventricles Supratentorial NOS 	`,`	null	`],
	[`	C71.1	`,`	Frontal lobe 	`,`	null	`],
	[`	C71.2	`,`	Temporal lobe 	`,`	null	`],
	[`	C71.3	`,`	Parietal lobe 	`,`	null	`],
	[`	C71.4	`,`	Occipital lobe 	`,`	null	`],
	[`	C71.5	`,`	Cerebral ventricle Excl.: fourth ventricle (C71.7) 	`,`	null	`],
	[`	C71.6	`,`	Cerebellum 	`,`	null	`],
	[`	C71.7	`,`	Brain stem Fourth ventricle Infratentorial NOS 	`,`	null	`],
	[`	C71.8	`,`	Overlapping lesion of brain [See note 5 at the beginning of this chapter] 	`,`	null	`],
	[`	C71.9	`,`	Brain, unspecified 	`,`	null	`],
	[`	C72	`,`	Malignant neoplasm of spinal cord, cranial nerves and other parts of central nervous system Excl.: meninges (C70.-) peripheral nerves and autonomic nervous system (C47.-) 	`,`	null	`],
	[`	C72.0	`,`	Spinal cord 	`,`	null	`],
	[`	C72.1	`,`	Cauda equina 	`,`	null	`],
	[`	C72.2	`,`	Olfactory nerve Olfactory bulb 	`,`	null	`],
	[`	C72.3	`,`	Optic nerve 	`,`	null	`],
	[`	C72.4	`,`	Acoustic nerve 	`,`	null	`],
	[`	C72.5	`,`	Other and unspecified cranial nerves Cranial nerve NOS 	`,`	null	`],
	[`	C72.8	`,`	Overlapping lesion of brain and other parts of central nervous system [See note 5 at the beginning of this chapter] Malignant neoplasm of brain and other parts of central nervous system whose point of origin cannot be classified to any one of the categories C70-C72.5 	`,`	null	`],
	[`	C72.9	`,`	Central nervous system, unspecified 	`,`	null	`],
	[`	C73	`,`	Malignant neoplasm of thyroid gland 	`,`	null	`],
	[`	C74	`,`	Malignant neoplasm of adrenal gland 	`,`	null	`],
	[`	C74.0	`,`	Cortex of adrenal gland 	`,`	null	`],
	[`	C74.1	`,`	Medulla of adrenal gland 	`,`	null	`],
	[`	C74.9	`,`	Adrenal gland, unspecified 	`,`	null	`],
	[`	C75	`,`	Malignant neoplasm of other endocrine glands and related structures Excl.: adrenal gland (C74.-) endocrine pancreas (C25.4) ovary (C56) testis (C62.-) thymus (C37) thyroid gland (C73) 	`,`	null	`],
	[`	C75.0	`,`	Parathyroid gland 	`,`	null	`],
	[`	C75.1	`,`	Pituitary gland 	`,`	null	`],
	[`	C75.2	`,`	Craniopharyngeal duct 	`,`	null	`],
	[`	C75.3	`,`	Pineal gland 	`,`	null	`],
	[`	C75.4	`,`	Carotid body 	`,`	null	`],
	[`	C75.5	`,`	Aortic body and other paraganglia 	`,`	null	`],
	[`	C75.8	`,`	Pluriglandular involvement, unspecified Note: If the sites of multiple involvement are known, they should be coded separately. 	`,`	null	`],
	[`	C75.9	`,`	Endocrine gland, unspecified 	`,`	null	`],
	[`	C76	`,`	Malignant neoplasm of other and ill-defined sites Excl.: malignant neoplasm of: genitourinary tract NOS: female (C57.9) male (C63.9) lymphoid, haematopoietic and related tissue (C81-C96) unspecified site (C80.-) 	`,`	null	`],
	[`	C76.0	`,`	Head, face and neck Cheek NOS Nose NOS 	`,`	null	`],
	[`	C76.1	`,`	Thorax Axilla NOS Intrathoracic NOS Thoracic NOS 	`,`	null	`],
	[`	C76.2	`,`	Abdomen 	`,`	null	`],
	[`	C76.3	`,`	Pelvis Groin NOS Sites overlapping systems within the pelvis, such as: rectovaginal (septum) rectovesical (septum) 	`,`	null	`],
	[`	C76.4	`,`	Upper limb 	`,`	null	`],
	[`	C76.5	`,`	Lower limb 	`,`	null	`],
	[`	C76.7	`,`	Other ill-defined sites 	`,`	null	`],
	[`	C76.8	`,`	Overlapping lesion of other and ill-defined sites [See note 5 at the beginning of this chapter] 	`,`	null	`],
	[`	C77	`,`	Secondary and unspecified malignant neoplasm of lymph nodes Excl.: malignant neoplasm of lymph nodes, specified as primary (C81-C86, C96.-) 	`,`	null	`],
	[`	C77.0	`,`	Lymph nodes of head, face and neck Supraclavicular lymph nodes 	`,`	null	`],
	[`	C77.1	`,`	Intrathoracic lymph nodes 	`,`	null	`],
	[`	C77.2	`,`	Intra-abdominal lymph nodes 	`,`	null	`],
	[`	C77.3	`,`	Axillary and upper limb lymph nodes Pectoral lymph nodes 	`,`	null	`],
	[`	C77.4	`,`	Inguinal and lower limb lymph nodes 	`,`	null	`],
	[`	C77.5	`,`	Intrapelvic lymph nodes 	`,`	null	`],
	[`	C77.8	`,`	Lymph nodes of multiple regions 	`,`	null	`],
	[`	C77.9	`,`	Lymph node, unspecified 	`,`	null	`],
	[`	C78	`,`	Secondary malignant neoplasm of respiratory and digestive organs 	`,`	null	`],
	[`	C78.0	`,`	Secondary malignant neoplasm of lung 	`,`	null	`],
	[`	C78.1	`,`	Secondary malignant neoplasm of mediastinum 	`,`	null	`],
	[`	C78.2	`,`	Secondary malignant neoplasm of pleura Malignant pleural effusion NOS 	`,`	null	`],
	[`	C78.3	`,`	Secondary malignant neoplasm of other and unspecified respiratory organs 	`,`	null	`],
	[`	C78.4	`,`	Secondary malignant neoplasm of small intestine 	`,`	null	`],
	[`	C78.5	`,`	Secondary malignant neoplasm of large intestine and rectum 	`,`	null	`],
	[`	C78.6	`,`	Secondary malignant neoplasm of retroperitoneum and peritoneum Malignant ascites NOS 	`,`	null	`],
	[`	C78.7	`,`	Secondary malignant neoplasm of liver and intrahepatic bile duct 	`,`	null	`],
	[`	C78.8	`,`	Secondary malignant neoplasm of other and unspecified digestive organs 	`,`	null	`],
	[`	C79	`,`	Secondary malignant neoplasm of other and unspecified sites 	`,`	null	`],
	[`	C79.0	`,`	Secondary malignant neoplasm of kidney and renal pelvis 	`,`	null	`],
	[`	C79.1	`,`	Secondary malignant neoplasm of bladder and other and unspecified urinary organs 	`,`	null	`],
	[`	C79.2	`,`	Secondary malignant neoplasm of skin 	`,`	null	`],
	[`	C79.3	`,`	Secondary malignant neoplasm of brain and cerebral meninges 	`,`	null	`],
	[`	C79.4	`,`	Secondary malignant neoplasm of other and unspecified parts of nervous system 	`,`	null	`],
	[`	C79.5	`,`	Secondary malignant neoplasm of bone and bone marrow 	`,`	null	`],
	[`	C79.6	`,`	Secondary malignant neoplasm of ovary 	`,`	null	`],
	[`	C79.7	`,`	Secondary malignant neoplasm of adrenal gland 	`,`	null	`],
	[`	C79.8	`,`	Secondary malignant neoplasm of other specified sites 	`,`	null	`],
	[`	C79.9	`,`	Secondary malignant neoplasm, unspecified site Carcinomatosis (secondary) Disseminated (secondary): cancer NOS malignancy NOS Generalized (secondary): cancer NOS malignancy NOS Multiple secondary cancer NOS Sarcomatosis (secondary) 	`,`	null	`],
	[`	C80	`,`	Malignant neoplasm, without specification of site 	`,`	null	`],
	[`	C80.0	`,`	Malignant neoplasm, primary site unknown, so stated Primary site unknown 	`,`	null	`],
	[`	C80.9	`,`	Malignant neoplasm, primary site unspecified Cancer NOS Carcinoma NOS Malignancy NOS Malignant cachexia NOS Multiple cancer NOS Excl.: multiple secondary cancer NOS (C79.9) secondary malignant neoplasm, unspecified site (C79.9) 	`,`	null	`],
	[`	C81	`,`	Hodgkin lymphoma 	`,`	null	`],
	[`	C81.0	`,`	Nodular lymphocyte predominant Hodgkin lymphoma 	`,`	null	`],
	[`	C81.1	`,`	Nodular sclerosis (classical) Hodgkin lymphoma 	`,`	null	`],
	[`	C81.2	`,`	Mixed cellularity (classical) Hodgkin lymphoma 	`,`	null	`],
	[`	C81.3	`,`	Lymphocyte depleted (classical) Hodgkin lymphoma 	`,`	null	`],
	[`	C81.4	`,`	Lymphocyte-rich (classical) Hodgkin lymphoma Excl.: nodular lymphocyte predominant Hodgkin lymphoma (C81.0) 	`,`	null	`],
	[`	C81.7	`,`	Other (classical) Hodgkin lymphoma Classic Hodgkin lymphoma, type not specified 	`,`	null	`],
	[`	C81.9	`,`	Hodgkin lymphoma, unspecified 	`,`	null	`],
	[`	C82	`,`	Follicular lymphoma Incl.: follicular lymphoma with or without diffuse areas Excl.: mature T/NK-cell lymphoma (C84.-) 	`,`	null	`],
	[`	C82.0	`,`	Follicular lymphoma grade I 	`,`	null	`],
	[`	C82.1	`,`	Follicular lymphoma grade II 	`,`	null	`],
	[`	C82.2	`,`	Follicular lymphoma grade III, unspecified 	`,`	null	`],
	[`	C82.3	`,`	Follicular lymphoma grade IIIa 	`,`	null	`],
	[`	C82.4	`,`	Follicular lymphoma grade IIIb 	`,`	null	`],
	[`	C82.5	`,`	Diffuse follicle centre lymphoma 	`,`	null	`],
	[`	C82.6	`,`	Cutaneous follicle centre lymphoma 	`,`	null	`],
	[`	C82.7	`,`	Other types of follicular lymphoma 	`,`	null	`],
	[`	C82.9	`,`	Follicular lymphoma, unspecified Nodular lymphoma NOS 	`,`	null	`],
	[`	C83	`,`	Non-follicular lymphoma 	`,`	null	`],
	[`	C83.0	`,`	Small cell B-cell lymphoma Lymphoplasmacytic lymphoma Nodal marginal zone lymphoma Non-leukaemic variant of B-CLL Splenic marginal zone lymphoma Excl.: Chronic lymphocytic leukaemia (C91.1) Waldenstrom macroglobulinaemia (C88.0) mature T/NK-cell lymphomas (C84.-) 	`,`	null	`],
	[`	C83.1	`,`	Mantle cell lymphoma Centrocytic lymphoma Malignant lymphomatous polyposis 	`,`	null	`],
	[`	C83.3	`,`	Diffuse large B-cell lymphoma Anaplastic CD30-positive Centroblastic Plasmablastic Immunoblastic Subtype not specified T-cell rich diffuse large B-cell lymphoma Excl.: mediastinal (thymic) large B-cell lymphoma (C85.2) mature T/NK-cell lymphomas (C84.-) 	`,`	null	`],
	[`	C83.5	`,`	Lymphoblastic (diffuse) lymphoma B-cell precursor lymphoma Lymphoblastic B-cell lymphoma Lymphoblastic lymphoma NOS Lymphoblastic T-cell lymphoma T-cell precursor lymphoma 	`,`	null	`],
	[`	C83.7	`,`	Burkitt lymphoma Atypical Burkitt lymphoma Burkitt-like lymphoma Excl.: mature B-cell leukaemia Burkitt-type (C91.8) 	`,`	null	`],
	[`	C83.8	`,`	Other non-follicular lymphoma Primary effusion B-cell lymphoma Intravascular large B-cell lymphoma Lymphoid granulomatosis Excl.: mediastinal (thymic) large B-cell lymphoma (C85.2) T-cell rich B-cell lymphoma (C83.3) 	`,`	null	`],
	[`	C83.9	`,`	Non-follicular (diffuse) lymphoma, unspecified 	`,`	null	`],
	[`	C84	`,`	Mature T/NK-cell lymphomas 	`,`	null	`],
	[`	C84.0	`,`	Mycosis fungoides 	`,`	null	`],
	[`	C84.1	`,`	Sezary disease 	`,`	null	`],
	[`	C84.4	`,`	Peripheral T-cell lymphoma, not elsewhere classified Lennert s lymphoma Lymphoepithelioid lymphoma 	`,`	null	`],
	[`	C84.5	`,`	Other mature T/NK-cell lymphomas Note: If T-cell lineage or involvement is mentioned in conjunction with a specific lymphoma, code to the more specific description. Excl.: angioimmunoblastic T-cell lymphoma (C86.5) blastic NK-cell lymphoma (C86.4) enteropathy-type T-cell lymphoma (C86.2) extranodal NK-cell lymphoma, nasal type (C86.0) hepatosplenic T-cell lymphoma (C86.1) primary cutaneous CD30-positive T-cell proliferations (C86.6) subcutaneous panniculitis-like T-cell lymphoma (C86.3) T-cell leukaemia (C91.-) 	`,`	null	`],
	[`	C84.6	`,`	Anaplastic large cell lymphoma, ALK-positive Anaplastic large cell lymphoma, CD30-positive 	`,`	null	`],
	[`	C84.7	`,`	Anaplastic large cell lymphoma, ALK-negative Excl.: primary cutaneous CD30-positive T-cell proliferations (C86.6) 	`,`	null	`],
	[`	C84.8	`,`	Cutaneous T-cell lymphoma, unspecified 	`,`	null	`],
	[`	C84.9	`,`	Mature T/NK-cell lymphoma, unspecified NK/T cell lymphoma NOS Excl.: mature T-cell lymphoma, not elsewhere classified (C84.4) 	`,`	null	`],
	[`	C85	`,`	Other and unspecified types of non-Hodgkin lymphoma 	`,`	null	`],
	[`	C85.1	`,`	B-cell lymphoma, unspecified Note: If B-cell lineage or involvement is mentioned in conjunction with a specific lymphoma, code to the more specific description. 	`,`	null	`],
	[`	C85.2	`,`	Mediastinal (thymic) large B-cell lymphoma 	`,`	null	`],
	[`	C85.7	`,`	Other specified types of non-Hodgkin lymphoma 	`,`	null	`],
	[`	C85.9	`,`	Non-Hodgkin lymphoma, unspecified Lymphoma NOS Malignant lymphoma NOS Non-Hodgkin lymphoma NOS 	`,`	null	`],
	[`	C86	`,`	Other specified types of T/NK-cell lymphoma Excl.: anaplastic large cell lymphoma, ALK negative (C84.7) anaplastic large cell lymphoma, ALK positive (C84.6) 	`,`	null	`],
	[`	C86.0	`,`	Extranodal NK/T-cell lymphoma, nasal type 	`,`	null	`],
	[`	C86.1	`,`	Hepatosplenic T-cell lymphoma Alpha-beta and gamma-delta types 	`,`	null	`],
	[`	C86.2	`,`	Enteropathy-type (intestinal) T-cell lymphoma Enteropathy associated T-cell lymphoma 	`,`	null	`],
	[`	C86.3	`,`	Subcutaneous panniculitis-like T-cell lymphoma 	`,`	null	`],
	[`	C86.4	`,`	Blastic NK-cell lymphoma 	`,`	null	`],
	[`	C86.5	`,`	Angioimmunoblastic T-cell lymphoma Angioimmunoblastic lymphadenopathy with dysproteinaemia [AILD] 	`,`	null	`],
	[`	C86.6	`,`	Primary cutaneous CD30-positive T-cell proliferations Lymphomatoid papulosis Primary cutaneous anaplastic large-cell lymphoma Primary cutaneous CD30-positive large T-cell lymphoma 	`,`	null	`],
	[`	C88	`,`	Malignant immunoproliferative diseases 	`,`	null	`],
	[`	C88.0	`,`	Waldenstrom macroglobulinaemia Lymphoplasmacytic lymphoma with IgM-production Macroglobulinaemia (primary)(idiopathic) Excl.: small cell B-cell lymphoma (C83.0) 	`,`	null	`],
	[`	C88.2	`,`	Other heavy chain disease Franklin disease Gamma heavy chain disease Mu (u) heavy chain disease 	`,`	null	`],
	[`	C88.3	`,`	Immunoproliferative small intestinal disease Alpha heavy chain disease Mediterranean lymphoma 	`,`	null	`],
	[`	C88.4	`,`	Extranodal marginal zone B-cell lymphoma of mucosa-associated lymphoid tissue [MALT-lyphoma] Note: Use additional code (C83.3) if desired, to specify transition to high malignant (diffuse large cell) lymphoma Lymphoma of skin-associated lymphoid tissue (SALT-lymphoma) Lymphoma of bronchial-associated lymphoid tissue (BALT-lymphoma) 	`,`	null	`],
	[`	C88.7	`,`	Other malignant immunoproliferative diseases 	`,`	null	`],
	[`	C88.9	`,`	Malignant immunoproliferative disease, unspecified Immunoproliferative disease NOS 	`,`	null	`],
	[`	C90	`,`	Multiple myeloma and malignant plasma cell neoplasms 	`,`	null	`],
	[`	C90.0	`,`	Multiple myeloma Kahler disease Medullary plasmacytoma Myelomatosis Plasma cell myeloma Excl.: solitary plasmacytoma (C90.3) 	`,`	null	`],
	[`	C90.1	`,`	Plasma cell leukaemia Plasmacytic leukaemia 	`,`	null	`],
	[`	C90.2	`,`	Extramedullary plasmacytoma 	`,`	null	`],
	[`	C90.3	`,`	Solitary plasmacytoma Localized malignant plasma cell tumour NOS Plasmacytoma NOS Solitary myeloma 	`,`	null	`],
	[`	C91	`,`	Lymphoid leukaemia 	`,`	null	`],
	[`	C91.0	`,`	Acute lymphoblastic leukaemia [ALL] Note: This code should only be used for T-cell and B-cell precursor leukeamia 	`,`	null	`],
	[`	C91.1	`,`	Chronic lymphocytic leukaemia of B-cell type Lymphoplasmacytic leukaemia Richter syndrome Excl.: lymphoplasmacytic lymphoma (C83.0) 	`,`	null	`],
	[`	C91.3	`,`	Prolymphocytic leukaemia of B-cell type 	`,`	null	`],
	[`	C91.4	`,`	Hairy-cell leukaemia Leukaemic reticuloendotheliosis 	`,`	null	`],
	[`	C91.5	`,`	Adult T-cell lymphoma/leukaemia [HTLV-1-associated] Acute Chronic Lymphomatoid Smouldering variant 	`,`	null	`],
	[`	C91.6	`,`	Prolymphocytic leukaemia of T-cell type 	`,`	null	`],
	[`	C91.7	`,`	Other lymphoid leukaemia T-cell large granular lymphocytic leukaemia (associated with rheumatoid arthritis) 	`,`	null	`],
	[`	C91.8	`,`	Mature B-cell leukaemia Burkitt-type Excl.: Burkitt lymphoma with little or no bone marrow infiltration (C83.7) 	`,`	null	`],
	[`	C91.9	`,`	Lymphoid leukaemia, unspecified 	`,`	null	`],
	[`	C92	`,`	Myeloid leukaemia Incl.: leukaemia: granulocytic myelogenous 	`,`	null	`],
	[`	C92.0	`,`	Acute myeloblastic leukaemia [AML] Acute myeloblastic leukaemia, minimal differentiation Acute myeloblastic leukaemia (with maturation) AML1/ETO AML M0 AML M1 AML M2 AML with t(8;21) AML (without a FAB classification) NOS Refractory anaemia with excess blasts in transformation Excl.: acute exacerbation of chronic myeloid leukaemia (C92.1) 	`,`	null	`],
	[`	C92.1	`,`	Chronic myeloid leukaemia [CML], BCR/ABL-positive Chronic myelogenous leukaemia: Philadelphia chromosome (Ph1) positive t(9:22)(q34; q11) with crisis of blast cells Excl.: atypical chronic myeloid leukaemia, BCR/ABL-negative (C92.2) chronic myelomonocytic leukaemia (C93.1) unclassified myeloproliferative disease (D47.1) 	`,`	null	`],
	[`	C92.2	`,`	Atypical chronic myeloid leukaemia, BCR/ABL- negative 	`,`	null	`],
	[`	C92.3	`,`	Myeloid sarcoma Note: a tumour of immature myeloid cells Chloroma Granulocytic sarcoma 	`,`	null	`],
	[`	C92.4	`,`	Acute promyelocytic leukaemia [PML] AML M3 AML Me with t(15; 17) and variants 	`,`	null	`],
	[`	C92.5	`,`	Acute myelomonocytic leukaemia AML M4 AML M4 Eo with inv(16) or t(16;16) 	`,`	null	`],
	[`	C92.6	`,`	Acute myeloid leukaemia with 11q23-abnormality Acute myeloid leukaemia with variation of MLL-gene 	`,`	null	`],
	[`	C92.7	`,`	Other myeloid leukaemia Excl.: chronic eosinophilic leukaemia [hypereosinophilic syndrome] (D47.5) 	`,`	null	`],
	[`	C92.8	`,`	Acute myeloid leukaemia with multilineage dysplasia Note: Acute myeloid leukaemia with dysplasia of remaining haematopoesis and/or myelodysplastic disease in its history. 	`,`	null	`],
	[`	C92.9	`,`	Myeloid leukaemia, unspecified 	`,`	null	`],
	[`	C93	`,`	Monocytic leukaemia Incl.: monocytoid leukaemia 	`,`	null	`],
	[`	C93.0	`,`	Acute monoblastic/monocytic leukaemia AML M5a AML M5b AML M5 	`,`	null	`],
	[`	C93.1	`,`	Chronic myelomonocytic leukaemia Chronic monocytic leukaemia CMML-1 CMML-2 CMML with eosinophilia 	`,`	null	`],
	[`	C93.3	`,`	Juvenile myelomonocytic leukaemia 	`,`	null	`],
	[`	C93.7	`,`	Other monocytic leukaemia 	`,`	null	`],
	[`	C93.9	`,`	Monocytic leukaemia, unspecified 	`,`	null	`],
	[`	C94	`,`	Other leukaemias of specified cell type Excl.: leukaemic reticuloendotheliosis (C91.4) plasma cell leukaemia (C90.1) 	`,`	null	`],
	[`	C94.0	`,`	Acute erythroid leukaemia Acute myeloid leukaemia M6 (a)(b) Erythroleukaemia 	`,`	null	`],
	[`	C94.2	`,`	Acute megakaryoblastic leukaemia Acute myeloid leukaemia, M7 Acute megakaryocytic leukaemia 	`,`	null	`],
	[`	C94.3	`,`	Mast cell leukaemia 	`,`	null	`],
	[`	C94.4	`,`	Acute panmyelosis with myelofibrosis Acute myelofibrosis 	`,`	null	`],
	[`	C94.6	`,`	Myelodysplastic and myeloproliferative disease, not elsewhere classified 	`,`	null	`],
	[`	C94.7	`,`	Other specified leukaemias Aggressive NK-cell leukaemia Acute basophilic leukaemia 	`,`	null	`],
	[`	C95	`,`	Leukaemia of unspecified cell type 	`,`	null	`],
	[`	C95.0	`,`	Acute leukaemia of unspecified cell type Acute bilineal leukaemia Acute mixed lineage leukaemia Biphenotypic acute leukaemia Stem cell leukaemia of unclear lineage Excl.: acute exacerbation of unspecified chronic leukaemia (C95.1) 	`,`	null	`],
	[`	C95.1	`,`	Chronic leukaemia of unspecified cell type 	`,`	null	`],
	[`	C95.7	`,`	Other leukaemia of unspecified cell type 	`,`	null	`],
	[`	C95.9	`,`	Leukaemia, unspecified 	`,`	null	`],
	[`	C96	`,`	Other and unspecified malignant neoplasms of lymphoid, haematopoietic and related tissue 	`,`	null	`],
	[`	C96.0	`,`	Multifocal and multisystemic (disseminated) Langerhans-cell histiocytosis [Letterer-Siwe disease] Histiocytosis X, multisystemic 	`,`	null	`],
	[`	C96.2	`,`	Malignant mast cell tumour Aggressive systemic mastocytosis Mast cell sarcoma Excl.: indolent mastocytosis (D47.0) mast cell leukaemia (C94.3) mastocytosis (congenital) (cutaneous) (Q82.2) 	`,`	null	`],
	[`	C96.4	`,`	Sarcoma of dendritic cells (accessory cells) Interdigiting dendritic cell sarcoma Langerhans-cell sarcoma Sarcoma of follicular dendritic cells 	`,`	null	`],
	[`	C96.5	`,`	Multifocal and unisystemic Langerhans-cell histiocytosis Hand-Schuller-Christian disease Histiocytosis X, multifocal 	`,`	null	`],
	[`	C96.6	`,`	Unifocal Langerhans-cell histiocytosis Eosinophilic granuloma Histiocytosis X, unifocal Histiocytosis X NOS Langerhans-cell histiocytosis NOS 	`,`	null	`],
	[`	C96.7	`,`	Other specified malignant neoplasms of lymphoid, haematopoietic and related tissue 	`,`	null	`],
	[`	C96.8	`,`	Histiocytic sarcoma Malignant Histiocytosis 	`,`	null	`],
	[`	C96.9	`,`	Malignant neoplasm of lymphoid, haematopoietic and related tissue, unspecified 	`,`	null	`],
	[`	C97	`,`	Malignant neoplasms of independent (primary) multiple sites Note: For use of this category, reference should be made to the mortality coding rules and guidelines in Volume 2. 	`,`	null	`],
							
];								
			
							
							
				
	
let CodeRangeC = {
	f0:function(val1=(-1),val2=(0)){
		let Range1 = CCodes.slice(val1,val2);
		Range1.reverse();
		document.documentElement.innerHTML += `<br>Showing C Codes ${Range1.length} items(s)`;

		for(value1 in Range1){
			    document.documentElement.style.cssText += "background-color:tan;";
				document.getElementById('ccodesTR').outerHTML += `<tr><td style="background-color:navy;color:white;width:5%;padding:40px;border:2px solid white;font-weight:900;font-size:40px;text-align:center;">${Range1[value1][0]}</td><td style="background-color:black;color:white;width:90%;padding:20px;border:2px solid white;font-size:30px;">${Range1[value1][1]}</td><td style="background-color:navy;color:white;width:5%;padding:20px;border:2px solid white;font-weight:900;font-size:40px;text-align:center;">${Range1[value1][2]}</td></tr>`;			
		}

	},

};

	






	






