let DCodes = [								
								
	[`		`,`		`,`		`],
	[`	D00	`,`	Carcinoma in situ of oral cavity, oesophagus and stomach Excl.: melanoma in situ (D03.-) 	`,`	null	`],
	[`	D00.0	`,`	Lip, oral cavity and pharynx Aryepiglottic fold: NOS hypopharyngeal aspect marginal zone Vermilion border of lip Excl.: aryepiglottic fold, laryngeal aspect (D02.0) epiglottis: NOS (D02.0) suprahyoid portion (D02.0) skin of lip (D03.0, D04.0) 	`,`	null	`],
	[`	D00.1	`,`	Oesophagus 	`,`	null	`],
	[`	D00.2	`,`	Stomach 	`,`	null	`],
	[`	D01	`,`	Carcinoma in situ of other and unspecified digestive organs Excl.: melanoma in situ (D03.-) 	`,`	null	`],
	[`	D01.0	`,`	Colon Excl.: rectosigmoid junction (D01.1) 	`,`	null	`],
	[`	D01.1	`,`	Rectosigmoid junction 	`,`	null	`],
	[`	D01.2	`,`	Rectum 	`,`	null	`],
	[`	D01.3	`,`	Anus and anal canal Excl.: anal: margin (D03.5, D04.5) skin (D03.5, D04.5) perianal skin (D03.5, D04.5) 	`,`	null	`],
	[`	D01.4	`,`	Other and unspecified parts of intestine Excl.: ampulla of Vater (D01.5) 	`,`	null	`],
	[`	D01.5	`,`	Liver, gallbladder and bile ducts Ampulla of Vater 	`,`	null	`],
	[`	D01.7	`,`	Other specified digestive organs Pancreas 	`,`	null	`],
	[`	D01.9	`,`	Digestive organ, unspecified 	`,`	null	`],
	[`	D02	`,`	Carcinoma in situ of middle ear and respiratory system Excl.: melanoma in situ (D03.-) 	`,`	null	`],
	[`	D02.0	`,`	Larynx Aryepiglottic fold, laryngeal aspect Epiglottis (suprahyoid portion) Excl.: aryepiglottic fold: NOS (D00.0) hypopharyngeal aspect (D00.0) marginal zone (D00.0) 	`,`	null	`],
	[`	D02.1	`,`	Trachea 	`,`	null	`],
	[`	D02.2	`,`	Bronchus and lung 	`,`	null	`],
	[`	D02.3	`,`	Other parts of respiratory system Accessory sinuses Middle ear Nasal cavities Excl.: ear (external)(skin) (D03.2, D04.2) nose: NOS (D09.7) skin (D03.3, D04.3) 	`,`	null	`],
	[`	D02.4	`,`	Respiratory system, unspecified 	`,`	null	`],
	[`	D03	`,`	Melanoma in situ Incl.: morphology codes M872-M879 with behaviour code /2 	`,`	null	`],
	[`	D03.0	`,`	Melanoma in situ of lip 	`,`	null	`],
	[`	D03.1	`,`	Melanoma in situ of eyelid, including canthus 	`,`	null	`],
	[`	D03.2	`,`	Melanoma in situ of ear and external auricular canal 	`,`	null	`],
	[`	D03.3	`,`	Melanoma in situ of other and unspecified parts of face 	`,`	null	`],
	[`	D03.4	`,`	Melanoma in situ of scalp and neck 	`,`	null	`],
	[`	D03.5	`,`	Melanoma in situ of trunk Anal: margin skin Breast (skin)(soft tissue) Perianal skin 	`,`	null	`],
	[`	D03.6	`,`	Melanoma in situ of upper limb, including shoulder 	`,`	null	`],
	[`	D03.7	`,`	Melanoma in situ of lower limb, including hip 	`,`	null	`],
	[`	D03.8	`,`	Melanoma in situ of other sites 	`,`	null	`],
	[`	D03.9	`,`	Melanoma in situ, unspecified 	`,`	null	`],
	[`	D04	`,`	Carcinoma in situ of skin Excl.: erythroplasia of Queyrat (penis) NOS (D07.4) melanoma in situ (D03.-) 	`,`	null	`],
	[`	D04.0	`,`	Skin of lip Excl.: vermilion border of lip (D00.0) 	`,`	null	`],
	[`	D04.1	`,`	Skin of eyelid, including canthus 	`,`	null	`],
	[`	D04.2	`,`	Skin of ear and external auricular canal 	`,`	null	`],
	[`	D04.3	`,`	Skin of other and unspecified parts of face 	`,`	null	`],
	[`	D04.4	`,`	Skin of scalp and neck 	`,`	null	`],
	[`	D04.5	`,`	Skin of trunk Anal: margin skin Perianal skin Skin of breast Excl.: anus NOS (D01.3) skin of genital organs (D07.-) 	`,`	null	`],
	[`	D04.6	`,`	Skin of upper limb, including shoulder 	`,`	null	`],
	[`	D04.7	`,`	Skin of lower limb, including hip 	`,`	null	`],
	[`	D04.8	`,`	Skin of other sites 	`,`	null	`],
	[`	D04.9	`,`	Skin, unspecified 	`,`	null	`],
	[`	D05	`,`	Carcinoma in situ of breast Excl.: carcinoma in situ of skin of breast (D04.5) melanoma in situ of breast (skin) (D03.5) 	`,`	null	`],
	[`	D05.0	`,`	Lobular carcinoma in situ 	`,`	null	`],
	[`	D05.1	`,`	Intraductal carcinoma in situ 	`,`	null	`],
	[`	D05.7	`,`	Other carcinoma in situ of breast 	`,`	null	`],
	[`	D05.9	`,`	Carcinoma in situ of breast, unspecified 	`,`	null	`],
	[`	D06	`,`	Carcinoma in situ of cervix uteri Incl.: cervical intraepithelial neoplasia [CIN], grade III, with or without mention of severe dysplasia Excl.: melanoma in situ of cervix (D03.5) severe dysplasia of cervix NOS (N87.2) 	`,`	null	`],
	[`	D06.0	`,`	Endocervix 	`,`	null	`],
	[`	D06.1	`,`	Exocervix 	`,`	null	`],
	[`	D06.7	`,`	Other parts of cervix 	`,`	null	`],
	[`	D06.9	`,`	Cervix, unspecified 	`,`	null	`],
	[`	D07	`,`	Carcinoma in situ of other and unspecified genital organs Excl.: melanoma in situ (D03.5) 	`,`	null	`],
	[`	D07.0	`,`	Endometrium 	`,`	null	`],
	[`	D07.1	`,`	Vulva Vulvar intraepithelial neoplasia [VIN], grade III, with or without mention of severe dysplasia Excl.: severe dysplasia of vulva NOS (N90.2) 	`,`	null	`],
	[`	D07.2	`,`	Vagina Vaginal intraepithelial neoplasia [VAIN], grade III, with or without mention of severe dysplasia Excl.: severe dysplasia of vagina NOS (N89.2) 	`,`	null	`],
	[`	D07.3	`,`	Other and unspecified female genital organs 	`,`	null	`],
	[`	D07.4	`,`	Penis Erythroplasia of Queyrat NOS 	`,`	null	`],
	[`	D07.5	`,`	Prostate Excl.: low grade dysplasia of prostate (N42.3) 	`,`	null	`],
	[`	D07.6	`,`	Other and unspecified male genital organs 	`,`	null	`],
	[`	D09	`,`	Carcinoma in situ of other and unspecified sites Excl.: melanoma in situ (D03.-) 	`,`	null	`],
	[`	D09.0	`,`	Bladder 	`,`	null	`],
	[`	D09.1	`,`	Other and unspecified urinary organs 	`,`	null	`],
	[`	D09.2	`,`	Eye Excl.: skin of eyelid (D04.1) 	`,`	null	`],
	[`	D09.3	`,`	Thyroid and other endocrine glands Excl.: endocrine pancreas (D01.7) ovary (D07.3) testis (D07.6) 	`,`	null	`],
	[`	D09.7	`,`	Carcinoma in situ of other specified sites 	`,`	null	`],
	[`	D09.9	`,`	Carcinoma in situ, unspecified 	`,`	null	`],
	[`	D10	`,`	Benign neoplasm of mouth and pharynx 	`,`	null	`],
	[`	D10.0	`,`	Lip Lip (frenulum)(inner aspect)(mucosa)(vermilion border) Excl.: skin of lip (D22.0, D23.0) 	`,`	null	`],
	[`	D10.1	`,`	Tongue Lingual tonsil 	`,`	null	`],
	[`	D10.2	`,`	Floor of mouth 	`,`	null	`],
	[`	D10.3	`,`	Other and unspecified parts of mouth Minor salivary gland NOS Excl.: benign odontogenic neoplasms (D16.4-D16.5) mucosa of lip (D10.0) nasopharyngeal surface of soft palate (D10.6) 	`,`	null	`],
	[`	D10.4	`,`	Tonsil Tonsil (faucial)(palatine) Excl.: lingual tonsil (D10.1) pharyngeal tonsil (D10.6) tonsillar: fossa (D10.5) pillars (D10.5) 	`,`	null	`],
	[`	D10.5	`,`	Other parts of oropharynx Epiglottis, anterior aspect Tonsillar: fossa pillars Vallecula Excl.: epiglottis: NOS (D14.1) suprahyoid portion (D14.1) 	`,`	null	`],
	[`	D10.6	`,`	Nasopharynx Pharyngeal tonsil Posterior margin of septum and choanae 	`,`	null	`],
	[`	D10.7	`,`	Hypopharynx 	`,`	null	`],
	[`	D10.9	`,`	Pharynx, unspecified 	`,`	null	`],
	[`	D11	`,`	Benign neoplasm of major salivary glands Excl.: benign neoplasms of specified minor salivary glands which are classified according to their anatomical location benign neoplasms of minor salivary glands NOS (D10.3) 	`,`	null	`],
	[`	D11.0	`,`	Parotid gland 	`,`	null	`],
	[`	D11.7	`,`	Other major salivary glands Gland: sublingual submandibular 	`,`	null	`],
	[`	D11.9	`,`	Major salivary gland, unspecified 	`,`	null	`],
	[`	D12	`,`	Benign neoplasm of colon, rectum, anus and anal canal 	`,`	null	`],
	[`	D12.0	`,`	Caecum Ileocaecal valve 	`,`	null	`],
	[`	D12.1	`,`	Appendix 	`,`	null	`],
	[`	D12.2	`,`	Ascending colon 	`,`	null	`],
	[`	D12.3	`,`	Transverse colon Hepatic flexure Splenic flexure 	`,`	null	`],
	[`	D12.4	`,`	Descending colon 	`,`	null	`],
	[`	D12.5	`,`	Sigmoid colon 	`,`	null	`],
	[`	D12.6	`,`	Colon, unspecified Adenomatosis of colon Large intestine NOS Polyposis (hereditary) of colon 	`,`	null	`],
	[`	D12.7	`,`	Rectosigmoid junction 	`,`	null	`],
	[`	D12.8	`,`	Rectum 	`,`	null	`],
	[`	D12.9	`,`	Anus and anal canal Excl.: anal: margin (D22.5, D23.5) skin (D22.5, D23.5) perianal skin (D22.5, D23.5) 	`,`	null	`],
	[`	D13	`,`	Benign neoplasm of other and ill-defined parts of digestive system 	`,`	null	`],
	[`	D13.0	`,`	Oesophagus 	`,`	null	`],
	[`	D13.1	`,`	Stomach 	`,`	null	`],
	[`	D13.2	`,`	Duodenum 	`,`	null	`],
	[`	D13.3	`,`	Other and unspecified parts of small intestine 	`,`	null	`],
	[`	D13.4	`,`	Liver Intrahepatic bile ducts 	`,`	null	`],
	[`	D13.5	`,`	Extrahepatic bile ducts 	`,`	null	`],
	[`	D13.6	`,`	Pancreas Excl.: endocrine pancreas (D13.7) 	`,`	null	`],
	[`	D13.7	`,`	Endocrine pancreas Islet cell tumour Islets of Langerhans 	`,`	null	`],
	[`	D13.9	`,`	Ill-defined sites within the digestive system Digestive system NOS Intestine NOS Spleen 	`,`	null	`],
	[`	D14	`,`	Benign neoplasm of middle ear and respiratory system 	`,`	null	`],
	[`	D14.0	`,`	Middle ear, nasal cavity and accessory sinuses Cartilage of nose Excl.: auricular canal (external) (D22.2, D23.2) bone of: ear (D16.4) nose (D16.4) cartilage of ear (D21.0) ear (external)(skin) (D22.2, D23.2) nose: NOS (D36.7) skin (D22.3, D23.3) olfactory bulb (D33.3) polyp (of): accessory sinus (J33.8) ear (middle) (H74.4) nasal (cavity) (J33.-) posterior margin of septum and choanae (D10.6) 	`,`	null	`],
	[`	D14.1	`,`	Larynx Epiglottis (suprahyoid portion) Excl.: epiglottis, anterior aspect (D10.5) polyp of vocal cord and larynx (J38.1) 	`,`	null	`],
	[`	D14.2	`,`	Trachea 	`,`	null	`],
	[`	D14.3	`,`	Bronchus and lung 	`,`	null	`],
	[`	D14.4	`,`	Respiratory system, unspecified 	`,`	null	`],
	[`	D15	`,`	Benign neoplasm of other and unspecified intrathoracic organs Excl.: mesothelial tissue (D19.-) 	`,`	null	`],
	[`	D15.0	`,`	Thymus 	`,`	null	`],
	[`	D15.1	`,`	Heart Excl.: great vessels (D21.3) 	`,`	null	`],
	[`	D15.2	`,`	Mediastinum 	`,`	null	`],
	[`	D15.7	`,`	Other specified intrathoracic organs 	`,`	null	`],
	[`	D15.9	`,`	Intrathoracic organ, unspecified 	`,`	null	`],
	[`	D16	`,`	Benign neoplasm of bone and articular cartilage Excl.: connective tissue of: ear (D21.0) eyelid (D21.0) larynx (D14.1) nose (D14.0) synovia (D21.-) 	`,`	null	`],
	[`	D16.0	`,`	Scapula and long bones of upper limb 	`,`	null	`],
	[`	D16.1	`,`	Short bones of upper limb 	`,`	null	`],
	[`	D16.2	`,`	Long bones of lower limb 	`,`	null	`],
	[`	D16.3	`,`	Short bones of lower limb 	`,`	null	`],
	[`	D16.4	`,`	Bones of skull and face Maxilla (superior) Orbital bone Excl.: lower jaw bone (D16.5) 	`,`	null	`],
	[`	D16.5	`,`	Lower jaw bone 	`,`	null	`],
	[`	D16.6	`,`	Vertebral column Excl.: sacrum and coccyx (D16.8) 	`,`	null	`],
	[`	D16.7	`,`	Ribs, sternum and clavicle 	`,`	null	`],
	[`	D16.8	`,`	Pelvic bones, sacrum and coccyx 	`,`	null	`],
	[`	D16.9	`,`	Bone and articular cartilage, unspecified 	`,`	null	`],
	[`	D17	`,`	Benign lipomatous neoplasm Incl.: morphology codes M885-M888 with behaviour code /0 	`,`	null	`],
	[`	D17.0	`,`	Benign lipomatous neoplasm of skin and subcutaneous tissue of head, face and neck 	`,`	null	`],
	[`	D17.1	`,`	Benign lipomatous neoplasm of skin and subcutaneous tissue of trunk 	`,`	null	`],
	[`	D17.2	`,`	Benign lipomatous neoplasm of skin and subcutaneous tissue of limbs 	`,`	null	`],
	[`	D17.3	`,`	Benign lipomatous neoplasm of skin and subcutaneous tissue of other and unspecified sites 	`,`	null	`],
	[`	D17.4	`,`	Benign lipomatous neoplasm of intrathoracic organs 	`,`	null	`],
	[`	D17.5	`,`	Benign lipomatous neoplasm of intra-abdominal organs Excl.: peritoneum and retroperitoneum (D17.7) 	`,`	null	`],
	[`	D17.6	`,`	Benign lipomatous neoplasm of spermatic cord 	`,`	null	`],
	[`	D17.7	`,`	Benign lipomatous neoplasm of other sites Peritoneum Retroperitoneum 	`,`	null	`],
	[`	D17.9	`,`	Benign lipomatous neoplasm, unspecified Lipoma NOS 	`,`	null	`],
	[`	D18	`,`	Haemangioma and lymphangioma, any site Incl.: morphology codes M912-M917 with behaviour code /0 Excl.: blue or pigmented naevus (D22.-) 	`,`	null	`],
	[`	D18.0	`,`	Haemangioma, any site Angioma NOS 	`,`	null	`],
	[`	D18.1	`,`	Lymphangioma, any site 	`,`	null	`],
	[`	D19	`,`	Benign neoplasm of mesothelial tissue Incl.: morphology code M905 with behaviour code /0 	`,`	null	`],
	[`	D19.0	`,`	Mesothelial tissue of pleura 	`,`	null	`],
	[`	D19.1	`,`	Mesothelial tissue of peritoneum 	`,`	null	`],
	[`	D19.7	`,`	Mesothelial tissue of other sites 	`,`	null	`],
	[`	D19.9	`,`	Mesothelial tissue, unspecified Benign mesothelioma NOS 	`,`	null	`],
	[`	D20	`,`	Benign neoplasm of soft tissue of retroperitoneum and peritoneum Excl.: benign lipomatous neoplasm of peritoneum and retroperitoneum (D17.7) mesothelial tissue (D19.-) 	`,`	null	`],
	[`	D20.0	`,`	Retroperitoneum 	`,`	null	`],
	[`	D20.1	`,`	Peritoneum 	`,`	null	`],
	[`	D21	`,`	Other benign neoplasms of connective and other soft tissue Incl.: blood vessel bursa cartilage fascia fat ligament, except uterine lymphatic channel muscle synovia tendon (sheath) Excl.: cartilage: articular (D16.-) larynx (D14.1) nose (D14.0) connective tissue of breast (D24) haemangioma (D18.0) lipomatous neoplasm (D17.-) lymphangioma (D18.1) peripheral nerves and autonomic nervous system (D36.1) peritoneum (D20.1) retroperitoneum (D20.0) uterine: leiomyoma (D25.-) ligament, any (D28.2) vascular tissue (D18.-) 	`,`	null	`],
	[`	D21.0	`,`	Connective and other soft tissue of head, face and neck Connective tissue of: ear eyelid Excl.: connective tissue of orbit (D31.6) 	`,`	null	`],
	[`	D21.1	`,`	Connective and other soft tissue of upper limb, including shoulder 	`,`	null	`],
	[`	D21.2	`,`	Connective and other soft tissue of lower limb, including hip 	`,`	null	`],
	[`	D21.3	`,`	Connective and other soft tissue of thorax Axilla Diaphragm Great vessels Excl.: heart (D15.1) mediastinum (D15.2) thymus (D15.0) 	`,`	null	`],
	[`	D21.4	`,`	Connective and other soft tissue of abdomen 	`,`	null	`],
	[`	D21.5	`,`	Connective and other soft tissue of pelvis Excl.: uterine: leiomyoma (D25.-) ligament, any (D28.2) 	`,`	null	`],
	[`	D21.6	`,`	Connective and other soft tissue of trunk, unspecified Back NOS 	`,`	null	`],
	[`	D21.9	`,`	Connective and other soft tissue, unspecified 	`,`	null	`],
	[`	D22	`,`	Melanocytic naevi Incl.: morphology codes M872-M879 with behaviour code /0 naevus: NOS blue hairy pigmented 	`,`	null	`],
	[`	D22.0	`,`	Melanocytic naevi of lip 	`,`	null	`],
	[`	D22.1	`,`	Melanocytic naevi of eyelid, including canthus 	`,`	null	`],
	[`	D22.2	`,`	Melanocytic naevi of ear and external auricular canal 	`,`	null	`],
	[`	D22.3	`,`	Melanocytic naevi of other and unspecified parts of face 	`,`	null	`],
	[`	D22.4	`,`	Melanocytic naevi of scalp and neck 	`,`	null	`],
	[`	D22.5	`,`	Melanocytic naevi of trunk Anal: margin skin Perianal skin Skin of breast 	`,`	null	`],
	[`	D22.6	`,`	Melanocytic naevi of upper limb, including shoulder 	`,`	null	`],
	[`	D22.7	`,`	Melanocytic naevi of lower limb, including hip 	`,`	null	`],
	[`	D22.9	`,`	Melanocytic naevi, unspecified 	`,`	null	`],
	[`	D23	`,`	Other benign neoplasms of skin Incl.: benign neoplasm of: hair follicles sebaceous glands sweat glands Excl.: benign lipomatous neoplasms (D17.0-D17.3) melanocytic naevi (D22.-) 	`,`	null	`],
	[`	D23.0	`,`	Skin of lip Excl.: vermilion border of lip (D10.0) 	`,`	null	`],
	[`	D23.1	`,`	Skin of eyelid, including canthus 	`,`	null	`],
	[`	D23.2	`,`	Skin of ear and external auricular canal 	`,`	null	`],
	[`	D23.3	`,`	Skin of other and unspecified parts of face 	`,`	null	`],
	[`	D23.4	`,`	Skin of scalp and neck 	`,`	null	`],
	[`	D23.5	`,`	Skin of trunk Anal: margin skin Perianal skin Skin of breast Excl.: anus NOS (D12.9) skin of genital organs (D28-D29) 	`,`	null	`],
	[`	D23.6	`,`	Skin of upper limb, including shoulder 	`,`	null	`],
	[`	D23.7	`,`	Skin of lower limb, including hip 	`,`	null	`],
	[`	D23.9	`,`	Skin, unspecified 	`,`	null	`],
	[`	D24	`,`	Benign neoplasm of breast Incl.: Breast: connective tissue soft parts Excl.: benign mammary dysplasia (N60.-) skin of breast (D22.5, D23.5) 	`,`	null	`],
	[`	D25	`,`	Leiomyoma of uterus Incl.: benign neoplasms of uterus with morphology code M889 and behaviour code /0 fibromyoma of uterus 	`,`	null	`],
	[`	D25.0	`,`	Submucous leiomyoma of uterus 	`,`	null	`],
	[`	D25.1	`,`	Intramural leiomyoma of uterus 	`,`	null	`],
	[`	D25.2	`,`	Subserosal leiomyoma of uterus 	`,`	null	`],
	[`	D25.9	`,`	Leiomyoma of uterus, unspecified 	`,`	null	`],
	[`	D26	`,`	Other benign neoplasms of uterus 	`,`	null	`],
	[`	D26.0	`,`	Cervix uteri 	`,`	null	`],
	[`	D26.1	`,`	Corpus uteri 	`,`	null	`],
	[`	D26.7	`,`	Other parts of uterus 	`,`	null	`],
	[`	D26.9	`,`	Uterus, unspecified 	`,`	null	`],
	[`	D27	`,`	Benign neoplasm of ovary 	`,`	null	`],
	[`	D28	`,`	Benign neoplasm of other and unspecified female genital organs Incl.: adenomatous polyp skin of female genital organs 	`,`	null	`],
	[`	D28.0	`,`	Vulva 	`,`	null	`],
	[`	D28.1	`,`	Vagina 	`,`	null	`],
	[`	D28.2	`,`	Uterine tubes and ligaments Fallopian tube Uterine ligament (broad)(round) 	`,`	null	`],
	[`	D28.7	`,`	Other specified female genital organs 	`,`	null	`],
	[`	D28.9	`,`	Female genital organ, unspecified 	`,`	null	`],
	[`	D29	`,`	Benign neoplasm of male genital organs Incl.: skin of male genital organs 	`,`	null	`],
	[`	D29.0	`,`	Penis 	`,`	null	`],
	[`	D29.1	`,`	Prostate Excl.: hyperplasia of prostate (adenomatous) (N40) prostatic: enlargement (N40) hypertrophy (N40) 	`,`	null	`],
	[`	D29.2	`,`	Testis 	`,`	null	`],
	[`	D29.3	`,`	Epididymis 	`,`	null	`],
	[`	D29.4	`,`	Scrotum Skin of scrotum 	`,`	null	`],
	[`	D29.7	`,`	Other male genital organs Seminal vesicle Spermatic cord Tunica vaginalis 	`,`	null	`],
	[`	D29.9	`,`	Male genital organ, unspecified 	`,`	null	`],
	[`	D30	`,`	Benign neoplasm of urinary organs 	`,`	null	`],
	[`	D30.0	`,`	Kidney Excl.: renal: calyces (D30.1) pelvis (D30.1) 	`,`	null	`],
	[`	D30.1	`,`	Renal pelvis 	`,`	null	`],
	[`	D30.2	`,`	Ureter Excl.: ureteric orifice of bladder (D30.3) 	`,`	null	`],
	[`	D30.3	`,`	Bladder Orifice of bladder: urethral ureteric 	`,`	null	`],
	[`	D30.4	`,`	Urethra Excl.: urethral orifice of bladder (D30.3) 	`,`	null	`],
	[`	D30.7	`,`	Other urinary organs Paraurethral glands 	`,`	null	`],
	[`	D30.9	`,`	Urinary organ, unspecified Urinary system NOS 	`,`	null	`],
	[`	D31	`,`	Benign neoplasm of eye and adnexa Excl.: connective tissue of eyelid (D21.0) optic nerve (D33.3) skin of eyelid (D22.1, D23.1) 	`,`	null	`],
	[`	D31.0	`,`	Conjunctiva 	`,`	null	`],
	[`	D31.1	`,`	Cornea 	`,`	null	`],
	[`	D31.2	`,`	Retina 	`,`	null	`],
	[`	D31.3	`,`	Choroid 	`,`	null	`],
	[`	D31.4	`,`	Ciliary body 	`,`	null	`],
	[`	D31.5	`,`	Lacrimal gland and duct Lacrimal sac Nasolacrimal duct 	`,`	null	`],
	[`	D31.6	`,`	Orbit, unspecified Connective tissue of orbit Extraocular muscle Peripheral nerves of orbit Retrobulbar tissue Retro-ocular tissue Excl.: orbital bone (D16.4) 	`,`	null	`],
	[`	D31.9	`,`	Eye, unspecified Eyeball 	`,`	null	`],
	[`	D32	`,`	Benign neoplasm of meninges 	`,`	null	`],
	[`	D32.0	`,`	Cerebral meninges 	`,`	null	`],
	[`	D32.1	`,`	Spinal meninges 	`,`	null	`],
	[`	D32.9	`,`	Meninges, unspecified Meningioma NOS 	`,`	null	`],
	[`	D33	`,`	Benign neoplasm of brain and other parts of central nervous system Excl.: angioma (D18.0) meninges (D32.-) peripheral nerves and autonomic nervous system (D36.1) retro-ocular tissue (D31.6) 	`,`	null	`],
	[`	D33.0	`,`	Brain, supratentorial Cerebral ventricle Cerebrum Frontal Occipital Parietal Temporal lobe Excl.: fourth ventricle (D33.1) 	`,`	null	`],
	[`	D33.1	`,`	Brain, infratentorial Brain stem Cerebellum Fourth ventricle 	`,`	null	`],
	[`	D33.2	`,`	Brain, unspecified 	`,`	null	`],
	[`	D33.3	`,`	Cranial nerves Olfactory bulb 	`,`	null	`],
	[`	D33.4	`,`	Spinal cord 	`,`	null	`],
	[`	D33.7	`,`	Other specified parts of central nervous system 	`,`	null	`],
	[`	D33.9	`,`	Central nervous system, unspecified Nervous system (central) NOS 	`,`	null	`],
	[`	D34	`,`	Benign neoplasm of thyroid gland 	`,`	null	`],
	[`	D35	`,`	Benign neoplasm of other and unspecified endocrine glands Excl.: endocrine pancreas (D13.7) ovary (D27) testis (D29.2) thymus (D15.0) 	`,`	null	`],
	[`	D35.0	`,`	Adrenal gland 	`,`	null	`],
	[`	D35.1	`,`	Parathyroid gland 	`,`	null	`],
	[`	D35.2	`,`	Pituitary gland 	`,`	null	`],
	[`	D35.3	`,`	Craniopharyngeal duct 	`,`	null	`],
	[`	D35.4	`,`	Pineal gland 	`,`	null	`],
	[`	D35.5	`,`	Carotid body 	`,`	null	`],
	[`	D35.6	`,`	Aortic body and other paraganglia 	`,`	null	`],
	[`	D35.7	`,`	Other specified endocrine glands 	`,`	null	`],
	[`	D35.8	`,`	Pluriglandular involvement 	`,`	null	`],
	[`	D35.9	`,`	Endocrine gland, unspecified 	`,`	null	`],
	[`	D36	`,`	Benign neoplasm of other and unspecified sites 	`,`	null	`],
	[`	D36.0	`,`	Lymph nodes 	`,`	null	`],
	[`	D36.1	`,`	Peripheral nerves and autonomic nervous system Excl.: peripheral nerves of orbit (D31.6) 	`,`	null	`],
	[`	D36.7	`,`	Other specified sites Nose NOS 	`,`	null	`],
	[`	D36.9	`,`	Benign neoplasm of unspecified site 	`,`	null	`],
	[`	D37	`,`	Neoplasm of uncertain or unknown behaviour of oral cavity and digestive organs 	`,`	null	`],
	[`	D37.0	`,`	Lip, oral cavity and pharynx Aryepiglottic fold: NOS hypopharyngeal aspect marginal zone Major and minor salivary glands Vermilion border of lip Excl.: aryepiglottic fold, laryngeal aspect (D38.0) epiglottis: NOS (D38.0) suprahyoid portion (D38.0) skin of lip (D48.5) 	`,`	null	`],
	[`	D37.1	`,`	Stomach 	`,`	null	`],
	[`	D37.2	`,`	Small intestine 	`,`	null	`],
	[`	D37.3	`,`	Appendix 	`,`	null	`],
	[`	D37.4	`,`	Colon 	`,`	null	`],
	[`	D37.5	`,`	Rectum Rectosigmoid junction 	`,`	null	`],
	[`	D37.6	`,`	Liver, gallbladder and bile ducts Ampulla of Vater 	`,`	null	`],
	[`	D37.7	`,`	Other digestive organs Anal: canal sphincter Anus NOS Intestine NOS Oesophagus Pancreas Excl.: anal: margin (D48.5) skin (D48.5) perianal skin (D48.5) 	`,`	null	`],
	[`	D37.9	`,`	Digestive organ, unspecified 	`,`	null	`],
	[`	D38	`,`	Neoplasm of uncertain or unknown behaviour of middle ear and respiratory and intrathoracic organs Excl.: heart (D48.7) 	`,`	null	`],
	[`	D38.0	`,`	Larynx Aryepiglottic fold, laryngeal aspect Epiglottis (suprahyoid portion) Excl.: aryepiglottic fold: NOS (D37.0) hypopharyngeal aspect (D37.0) marginal zone (D37.0) 	`,`	null	`],
	[`	D38.1	`,`	Trachea, bronchus and lung 	`,`	null	`],
	[`	D38.2	`,`	Pleura 	`,`	null	`],
	[`	D38.3	`,`	Mediastinum 	`,`	null	`],
	[`	D38.4	`,`	Thymus 	`,`	null	`],
	[`	D38.5	`,`	Other respiratory organs Accessory sinuses Cartilage of nose Middle ear Nasal cavities Excl.: ear (external)(skin) (D48.5) nose: NOS (D48.7) skin (D48.5) 	`,`	null	`],
	[`	D38.6	`,`	Respiratory organ, unspecified 	`,`	null	`],
	[`	D39	`,`	Neoplasm of uncertain or unknown behaviour of female genital organs 	`,`	null	`],
	[`	D39.0	`,`	Uterus 	`,`	null	`],
	[`	D39.1	`,`	Ovary 	`,`	null	`],
	[`	D39.2	`,`	Placenta Chorioadenoma destruens Hydatidiform mole: invasive malignant Excl.: hydatidiform mole NOS (O01.9) 	`,`	null	`],
	[`	D39.7	`,`	Other female genital organs Skin of female genital organs 	`,`	null	`],
	[`	D39.9	`,`	Female genital organ, unspecified 	`,`	null	`],
	[`	D40	`,`	Neoplasm of uncertain or unknown behaviour of male genital organs 	`,`	null	`],
	[`	D40.0	`,`	Prostate 	`,`	null	`],
	[`	D40.1	`,`	Testis 	`,`	null	`],
	[`	D40.7	`,`	Other male genital organs Skin of male genital organs 	`,`	null	`],
	[`	D40.9	`,`	Male genital organ, unspecified 	`,`	null	`],
	[`	D41	`,`	Neoplasm of uncertain or unknown behaviour of urinary organs 	`,`	null	`],
	[`	D41.0	`,`	Kidney Excl.: renal pelvis (D41.1) 	`,`	null	`],
	[`	D41.1	`,`	Renal pelvis 	`,`	null	`],
	[`	D41.2	`,`	Ureter 	`,`	null	`],
	[`	D41.3	`,`	Urethra 	`,`	null	`],
	[`	D41.4	`,`	Bladder 	`,`	null	`],
	[`	D41.7	`,`	Other urinary organs 	`,`	null	`],
	[`	D41.9	`,`	Urinary organ, unspecified 	`,`	null	`],
	[`	D42	`,`	Neoplasm of uncertain or unknown behaviour of meninges 	`,`	null	`],
	[`	D42.0	`,`	Cerebral meninges 	`,`	null	`],
	[`	D42.1	`,`	Spinal meninges 	`,`	null	`],
	[`	D42.9	`,`	Meninges, unspecified 	`,`	null	`],
	[`	D43	`,`	Neoplasm of uncertain or unknown behaviour of brain and central nervous system Excl.: peripheral nerves and autonomic nervous system (D48.2) 	`,`	null	`],
	[`	D43.0	`,`	Brain, supratentorial Cerebral ventricle Cerebrum Frontal Occipital Parietal Temporal lobe Excl.: fourth ventricle (D43.1) 	`,`	null	`],
	[`	D43.1	`,`	Brain, infratentorial Brain stem Cerebellum Fourth ventricle 	`,`	null	`],
	[`	D43.2	`,`	Brain, unspecified 	`,`	null	`],
	[`	D43.3	`,`	Cranial nerves 	`,`	null	`],
	[`	D43.4	`,`	Spinal cord 	`,`	null	`],
	[`	D43.7	`,`	Other parts of central nervous system 	`,`	null	`],
	[`	D43.9	`,`	Central nervous system, unspecified Nervous system (central) NOS 	`,`	null	`],
	[`	D44	`,`	Neoplasm of uncertain or unknown behaviour of endocrine glands Excl.: endocrine pancreas (D37.7) ovary (D39.1) testis (D40.1) thymus (D38.4) 	`,`	null	`],
	[`	D44.0	`,`	Thyroid gland 	`,`	null	`],
	[`	D44.1	`,`	Adrenal gland 	`,`	null	`],
	[`	D44.2	`,`	Parathyroid gland 	`,`	null	`],
	[`	D44.3	`,`	Pituitary gland 	`,`	null	`],
	[`	D44.4	`,`	Craniopharyngeal duct 	`,`	null	`],
	[`	D44.5	`,`	Pineal gland 	`,`	null	`],
	[`	D44.6	`,`	Carotid body 	`,`	null	`],
	[`	D44.7	`,`	Aortic body and other paraganglia 	`,`	null	`],
	[`	D44.8	`,`	Pluriglandular involvement Multiple endocrine adenomatosis 	`,`	null	`],
	[`	D44.9	`,`	Endocrine gland, unspecified 	`,`	null	`],
	[`	D45	`,`	Polycythaemia vera Note: Polycythaemia vera has been reclassified in ICD-O Third Edition with a malignant code. The code D45 will continue to be used, although it is located in the chapter for Neoplasms of uncertain or unknown behaviour. The modification of its classification is reserved to the revision of ICD. 	`,`	null	`],
	[`	D46	`,`	Myelodysplastic syndromes Incl.: Alkylating agent related myelodysplastic syndrome Epipodophyllotoxin related myelodysplastic syndrome Therapy related myelodysplastic syndrome NOS Excl.: drug induced aplastic anaemia (D61.1) 	`,`	null	`],
	[`	D46.0	`,`	Refractory anaemia without ring sideroblasts, so stated Note: without sideroblasts, without excess of blasts 	`,`	null	`],
	[`	D46.1	`,`	Refractory anaemia with ring sideroblasts 	`,`	null	`],
	[`	D46.2	`,`	Refractory anaemia with excess of blasts [RAEB] Note: RAEB I RAEB II 	`,`	null	`],
	[`	D46.4	`,`	Refractory anaemia, unspecified 	`,`	null	`],
	[`	D46.5	`,`	Refractory anaemia with multi-lineage dysplasia 	`,`	null	`],
	[`	D46.6	`,`	Myelodysplastic syndrome with isolated del(5q) chromosomal abnormality 5 q-minus syndrome 	`,`	null	`],
	[`	D46.7	`,`	Other myelodysplastic syndromes Excl.: chronic myelomonocytic leukaemia (C93.1) 	`,`	null	`],
	[`	D46.9	`,`	Myelodysplastic syndrome, unspecified Myelodysplasia NOS Preleukaemia (syndrome) NOS 	`,`	null	`],
	[`	D47	`,`	Other neoplasms of uncertain or unknown behaviour of lymphoid, haematopoietic and related tissue 	`,`	null	`],
	[`	D47.0	`,`	Histiocytic and mast cell tumours of uncertain and unknown behaviour Indolent systemic mastocytosis Mast cell tumour NOS Mastocytoma NOS Systemic mastocytosis, associated with clonal haematopoietic non-mast-cell disease (SM-AHNMD) Excl.: mastocytosis (congenital) (cutaneous) (Q82.2) 	`,`	null	`],
	[`	D47.1	`,`	Chronic myeloproliferative disease Chronic neutrophilic leukaemia Myeloproliferative disease, unspecified Excl.: atypical chronic myeloid leukaemia, BCR/ABL-negative (C92.2) chronic myeloid leukaemia [CML] BCR/ABL-positive (C92.1) 	`,`	null	`],
	[`	D47.2	`,`	Monoclonal gammopathy of undetermined significance (MGUS) 	`,`	null	`],
	[`	D47.3	`,`	Essential (haemorrhagic) thrombocythaemia Idiopathic haemorrhagic thrombocythaemia 	`,`	null	`],
	[`	D47.4	`,`	Osteomyelofibrosis Chronic idiopathic myelofibrosis Myelofibrosis (idiopathic) (with myeloid metaplasia) Myelosclerosis (megakaryocytic) with myeloid metaplasia Secondary myelofibrosis in myeloproliferative disease Excl.: acute myelofibrosis (C94.4) 	`,`	null	`],
	[`	D47.5	`,`	Chronic eosinophilic leukaemia [hypereosinophilic syndrome] 	`,`	null	`],
	[`	D47.7	`,`	Other specified neoplasms of uncertain or unknown behaviour of lymphoid, haematopoietic and related tissue Histiocytic tumours of uncertain and unknown behaviour 	`,`	null	`],
	[`	D47.9	`,`	Neoplasm of uncertain or unknown behaviour of lymphoid, haematopoietic and related tissue, unspecified Lymphoproliferative disease NOS 	`,`	null	`],
	[`	D48	`,`	Neoplasm of uncertain or unknown behaviour of other and unspecified sites Excl.: neurofibromatosis (nonmalignant) (Q85.0) 	`,`	null	`],
	[`	D48.0	`,`	Bone and articular cartilage Excl.: cartilage of: ear (D48.1) larynx (D38.0) nose (D38.5) connective tissue of eyelid (D48.1) synovia (D48.1) 	`,`	null	`],
	[`	D48.1	`,`	Connective and other soft tissue Connective tissue of: ear eyelid Excl.: cartilage (of): articular (D48.0) larynx (D38.0) nose (D38.5) connective tissue of breast (D48.6) 	`,`	null	`],
	[`	D48.2	`,`	Peripheral nerves and autonomic nervous system Excl.: peripheral nerves of orbit (D48.7) 	`,`	null	`],
	[`	D48.3	`,`	Retroperitoneum 	`,`	null	`],
	[`	D48.4	`,`	Peritoneum 	`,`	null	`],
	[`	D48.5	`,`	Skin Anal: margin skin Perianal skin Skin of breast Excl.: anus NOS (D37.7) skin of genital organs (D39.7, D40.7) vermilion border of lip (D37.0) 	`,`	null	`],
	[`	D48.6	`,`	Breast Connective tissue of breast Cystosarcoma phyllodes Excl.: skin of breast (D48.5) 	`,`	null	`],
	[`	D48.7	`,`	Other specified sites Eye Heart Peripheral nerves of orbit Excl.: connective tissue (D48.1) skin of eyelid (D48.5) 	`,`	null	`],
	[`	D48.9	`,`	Neoplasm of uncertain or unknown behaviour, unspecified "Growth" NOS Neoplasm NOS New growth NOS Tumour NOS 	`,`	null	`],
	[`	D50	`,`	Iron deficiency anaemia Incl.: anaemia: asiderotic hypochromic 	`,`	null	`],
	[`	D50.0	`,`	Iron deficiency anaemia secondary to blood loss (chronic) Posthaemorrhagic anaemia (chronic) Excl.: acute posthaemorrhagic anaemia (D62) congenital anaemia from fetal blood loss (P61.3) 	`,`	null	`],
	[`	D50.1	`,`	Sideropenic dysphagia Kelly-Paterson syndrome Plummer-Vinson syndrome 	`,`	null	`],
	[`	D50.8	`,`	Other iron deficiency anaemias 	`,`	null	`],
	[`	D50.9	`,`	Iron deficiency anaemia, unspecified 	`,`	null	`],
	[`	D51	`,`	Vitamin B12 deficiency anaemia Excl.: Vitamin B12 deficiency (E53.8) 	`,`	null	`],
	[`	D51.0	`,`	Vitamin B12 deficiency anaemia due to intrinsic factor deficiency Anaemia: Addison Biermer pernicious (congenital) Congenital intrinsic factor deficiency 	`,`	null	`],
	[`	D51.1	`,`	Vitamin B12 deficiency anaemia due to selective vitamin B12 malabsorption with proteinuria Imerslund(-Grasbeck) syndrome Megaloblastic hereditary anaemia 	`,`	null	`],
	[`	D51.2	`,`	Transcobalamin II deficiency 	`,`	null	`],
	[`	D51.3	`,`	Other dietary vitamin B12 deficiency anaemia Vegan anaemia 	`,`	null	`],
	[`	D51.8	`,`	Other vitamin B12 deficiency anaemias 	`,`	null	`],
	[`	D51.9	`,`	Vitamin B12 deficiency anaemia, unspecified 	`,`	null	`],
	[`	D52	`,`	Folate deficiency anaemia 	`,`	null	`],
	[`	D52.0	`,`	Dietary folate deficiency anaemia Nutritional megaloblastic anaemia 	`,`	null	`],
	[`	D52.1	`,`	Drug-induced folate deficiency anaemia Use additional external cause code (Chapter XX), if desired, to identify drug. 	`,`	null	`],
	[`	D52.8	`,`	Other folate deficiency anaemias 	`,`	null	`],
	[`	D52.9	`,`	Folate deficiency anaemia, unspecified Folic acid deficiency anaemia NOS 	`,`	null	`],
	[`	D53	`,`	Other nutritional anaemias Incl.: megaloblastic anaemia unresponsive to vitamin B12 or folate therapy 	`,`	null	`],
	[`	D53.0	`,`	Protein deficiency anaemia Amino-acid deficiency anaemia Orotaciduric anaemia Excl.: Lesch-Nyhan syndrome (E79.1) 	`,`	null	`],
	[`	D53.1	`,`	Other megaloblastic anaemias, not elsewhere classified Megaloblastic anaemia NOS Excl.: Di Guglielmo disease (C94.0) 	`,`	null	`],
	[`	D53.2	`,`	Scorbutic anaemia Excl.: scurvy (E54) 	`,`	null	`],
	[`	D53.8	`,`	Other specified nutritional anaemias Anaemia associated with deficiency of: copper molybdenum zinc Excl.: nutritional deficiencies without mention of anaemia, such as: copper deficiency (E61.0) molybdenum deficiency (E61.5) zinc deficiency (E60) 	`,`	null	`],
	[`	D53.9	`,`	Nutritional anaemia, unspecified Simple chronic anaemia Excl.: anaemia NOS (D64.9) 	`,`	null	`],
	[`	D55	`,`	Anaemia due to enzyme disorders Excl.: drug-induced enzyme deficiency anaemia (D59.2) 	`,`	null	`],
	[`	D55.0	`,`	Anaemia due to glucose-6-phosphate dehydrogenase [G6PD] deficiency Favism G6PD deficiency anaemia 	`,`	null	`],
	[`	D55.1	`,`	Anaemia due to other disorders of glutathione metabolism Anaemia (due to): enzyme deficiencies, except G6PD, related to the hexose monophosphate [HMP] shunt pathway haemolytic nonspherocytic (hereditary), type I 	`,`	null	`],
	[`	D55.2	`,`	Anaemia due to disorders of glycolytic enzymes Anaemia: haemolytic nonspherocytic (hereditary), type II hexokinase deficiency pyruvate kinase [PK] deficiency triose-phosphate isomerase deficiency 	`,`	null	`],
	[`	D55.3	`,`	Anaemia due to disorders of nucleotide metabolism 	`,`	null	`],
	[`	D55.8	`,`	Other anaemias due to enzyme disorders 	`,`	null	`],
	[`	D55.9	`,`	Anaemia due to enzyme disorder, unspecified 	`,`	null	`],
	[`	D56	`,`	Thalassaemia 	`,`	null	`],
	[`	D56.0	`,`	Alpha thalassaemia Excl.: hydrops fetalis due to haemolytic disease (P56.-) 	`,`	null	`],
	[`	D56.1	`,`	Beta thalassaemia Cooley anaemia Severe beta thalassaemia Thalassaemia: intermedia major 	`,`	null	`],
	[`	D56.2	`,`	Delta-beta thalassaemia 	`,`	null	`],
	[`	D56.3	`,`	Thalassaemia trait 	`,`	null	`],
	[`	D56.4	`,`	Hereditary persistence of fetal haemoglobin [HPFH] 	`,`	null	`],
	[`	D56.8	`,`	Other thalassaemias 	`,`	null	`],
	[`	D56.9	`,`	Thalassaemia, unspecified Mediterranean anaemia (with other haemoglobinopathy) Thalassaemia (minor)(mixed)(with other haemoglobinopathy) 	`,`	null	`],
	[`	D57	`,`	Sickle-cell disorders Excl.: other haemoglobinopathies (D58.-) 	`,`	null	`],
	[`	D57.0	`,`	Sickle-cell anaemia with crisis Hb-SS disease with crisis 	`,`	null	`],
	[`	D57.1	`,`	Sickle-cell anaemia without crisis Sickle-cell: anaemia disease disorder NOS 	`,`	null	`],
	[`	D57.2	`,`	Double heterozygous sickling disorders Disease: Hb-SC Hb-SD Hb-SE sickle-cell thalassaemia 	`,`	null	`],
	[`	D57.3	`,`	Sickle-cell trait Hb-S trait Heterozygous haemoglobin S [HbAS] 	`,`	null	`],
	[`	D57.8	`,`	Other sickle-cell disorders 	`,`	null	`],
	[`	D58	`,`	Other hereditary haemolytic anaemias 	`,`	null	`],
	[`	D58.0	`,`	Hereditary spherocytosis Acholuric (familial) jaundice Congenital (spherocytic) haemolytic icterus Minkowski-Chauffard syndrome 	`,`	null	`],
	[`	D58.1	`,`	Hereditary elliptocytosis Elliptocytosis (congenital) Ovalocytosis (congenital)(hereditary) 	`,`	null	`],
	[`	D58.2	`,`	Other haemoglobinopathies Abnormal haemoglobin NOS Congenital Heinz body anaemia Disease: Hb-C Hb-D Hb-E Haemoglobinopathy NOS Unstable haemoglobin haemolytic disease Excl.: familial polycythaemia (D75.0) Hb-M disease (D74.0) hereditary persistence of fetal haemoglobin [HPFH] (D56.4) high-altitude polycythaemia (D75.1) methaemoglobinaemia (D74.-) 	`,`	null	`],
	[`	D58.8	`,`	Other specified hereditary haemolytic anaemias Stomatocytosis 	`,`	null	`],
	[`	D58.9	`,`	Hereditary haemolytic anaemia, unspecified 	`,`	null	`],
	[`	D59	`,`	Acquired haemolytic anaemia 	`,`	null	`],
	[`	D59.0	`,`	Drug-induced autoimmune haemolytic anaemia Use additional external cause code (Chapter XX), if desired, to identify drug. 	`,`	null	`],
	[`	D59.1	`,`	Other autoimmune haemolytic anaemias Autoimmune haemolytic disease (cold type)(warm type) Chronic cold haemagglutinin disease Cold agglutinin: disease haemoglobinuria Haemolytic anaemia: cold type (secondary)(symptomatic) warm type (secondary)(symptomatic) Excl.: Evans syndrome (D69.3) haemolytic disease of fetus and newborn (P55.-) paroxysmal cold haemoglobinuria (D59.6) 	`,`	null	`],
	[`	D59.2	`,`	Drug-induced nonautoimmune haemolytic anaemia Drug-induced enzyme deficiency anaemia Use additional external cause code (Chapter XX), if desired, to identify drug. 	`,`	null	`],
	[`	D59.3	`,`	Haemolytic-uraemic syndrome 	`,`	null	`],
	[`	D59.4	`,`	Other nonautoimmune haemolytic anaemias Haemolytic anaemia: mechanical microangiopathic toxic Use additional external cause code (Chapter XX), if desired, to identify cause. 	`,`	null	`],
	[`	D59.5	`,`	Paroxysmal nocturnal haemoglobinuria [Marchiafava-Micheli] Excl.: haemoglobinuria NOS (R82.3) 	`,`	null	`],
	[`	D59.6	`,`	Haemoglobinuria due to haemolysis from other external causes Haemoglobinuria: from exertion march paroxysmal cold Use additional external cause code (Chapter XX), if desired, to identify cause. Excl.: haemoglobinuria NOS (R82.3) 	`,`	null	`],
	[`	D59.8	`,`	Other acquired haemolytic anaemias 	`,`	null	`],
	[`	D59.9	`,`	Acquired haemolytic anaemia, unspecified Idiopathic haemolytic anaemia, chronic 	`,`	null	`],
	[`	D60	`,`	Acquired pure red cell aplasia [erythroblastopenia] Incl.: red cell aplasia (acquired)(adult)(with thymoma) 	`,`	null	`],
	[`	D60.0	`,`	Chronic acquired pure red cell aplasia 	`,`	null	`],
	[`	D60.1	`,`	Transient acquired pure red cell aplasia 	`,`	null	`],
	[`	D60.8	`,`	Other acquired pure red cell aplasias 	`,`	null	`],
	[`	D60.9	`,`	Acquired pure red cell aplasia, unspecified 	`,`	null	`],
	[`	D61	`,`	Other aplastic anaemias Excl.: agranulocytosis (D70) 	`,`	null	`],
	[`	D61.0	`,`	Constitutional aplastic anaemia Aplasia, (pure) red cell (of): congenital infants primary Blackfan-Diamond syndrome Familial hypoplastic anaemia Fanconi anaemia Pancytopenia with malformations 	`,`	null	`],
	[`	D61.1	`,`	Drug-induced aplastic anaemia Use additional external cause code (Chapter XX), if desired, to identify drug. 	`,`	null	`],
	[`	D61.2	`,`	Aplastic anaemia due to other external agents Use additional external cause code (Chapter XX), if desired, to identify cause. 	`,`	null	`],
	[`	D61.3	`,`	Idiopathic aplastic anaemia 	`,`	null	`],
	[`	D61.8	`,`	Other specified aplastic anaemias 	`,`	null	`],
	[`	D61.9	`,`	Aplastic anaemia, unspecified Hypoplastic anaemia NOS Medullary hypoplasia Panmyelophthisis 	`,`	null	`],
	[`	D62	`,`	Acute posthaemorrhagic anaemia Excl.: congenital anaemia from fetal blood loss (P61.3) 	`,`	null	`],
	[`	D63*	`,`	Anaemia in chronic diseases classified elsewhere 	`,`	null	`],
	[`	D63.0*	`,`	Anaemia in neoplastic disease (C00-D48) 	`,`	null	`],
	[`	D63.8*	`,`	Anaemia in other chronic diseases classified elsewhere Anaemia in chronic kidney disease stage 3 -- N18.3 to N18.9 	`,`	null	`],
	[`	D64	`,`	Other anaemias Excl.: refractory anaemia: NOS (D46.4) with excess of blasts (D46.2) with excess of blasts with transformation (C92.0) with sideroblasts (D46.1) without sideroblasts (D46.0) 	`,`	null	`],
	[`	D64.0	`,`	Hereditary sideroblastic anaemia Sex-linked hypochromic sideroblastic anaemia 	`,`	null	`],
	[`	D64.1	`,`	Secondary sideroblastic anaemia due to disease Use additional code, if desired, to identify disease. 	`,`	null	`],
	[`	D64.2	`,`	Secondary sideroblastic anaemia due to drugs and toxins Use additional external cause code (Chapter XX), if desired, to identify cause. 	`,`	null	`],
	[`	D64.3	`,`	Other sideroblastic anaemias Sideroblastic anaemia: NOS pyridoxine-responsive NEC 	`,`	null	`],
	[`	D64.4	`,`	Congenital dyserythropoietic anaemia Dyshaematopoietic anaemia (congenital) Excl.: Blackfan-Diamond syndrome (D61.0) Di Guglielmo disease (C94.0) 	`,`	null	`],
	[`	D64.8	`,`	Other specified anaemias Infantile pseudoleukaemia Leukoerythroblastic anaemia 	`,`	null	`],
	[`	D64.9	`,`	Anaemia, unspecified 	`,`	null	`],
	[`	D65	`,`	Disseminated intravascular coagulation [defibrination syndrome] Incl.: Afibrinogenaemia, acquired Consumption coagulopathy Diffuse or disseminated intravascular coagulation [DIC] Fibrinolytic haemorrhage, acquired Purpura: fibrinolytic fulminans Excl.: that (complicating): abortion or ectopic or molar pregnancy (O00-O07, O08.1) in newborn (P60) pregnancy, childbirth and the puerperium (O45.0, O46.0, O67.0, O72.3) 	`,`	null	`],
	[`	D66	`,`	Hereditary factor VIII deficiency Incl.: Deficiency factor VIII (with functional defect) Haemophilia: NOS A classical Excl.: factor VIII deficiency with vascular defect (D68.0) 	`,`	null	`],
	[`	D67	`,`	Hereditary factor IX deficiency Incl.: Christmas disease Deficiency: factor IX (with functional defect) plasma thromboplastin component [PTC] Haemophilia B 	`,`	null	`],
	[`	D68	`,`	Other coagulation defects Excl.: those complicating: abortion or ectopic or molar pregnancy (O00-O07, O08.1) pregnancy, childbirth and the puerperium (O45.0, O46.0, O67.0, O72.3) 	`,`	null	`],
	[`	D68.0	`,`	Von Willebrand disease Angiohaemophilia Factor VIII deficiency with vascular defect Vascular haemophilia Excl.: capillary fragility (hereditary) (D69.8) factor VIII deficiency: NOS (D66) with functional defect (D66) 	`,`	null	`],
	[`	D68.1	`,`	Hereditary factor XI deficiency Haemophilia C Plasma thromboplastin antecedent [PTA] deficiency 	`,`	null	`],
	[`	D68.2	`,`	Hereditary deficiency of other clotting factors Congenital afibrinogenaemia Deficiency: AC globulin proaccelerin Deficiency of factor: I [fibrinogen] II [prothrombin] V [labile] VII [stable] X [Stuart-Prower] XII [Hageman] XIII [fibrin-stabilizing] Dysfibrinogenaemia (congenital) Hypoproconvertinaemia Owren disease 	`,`	null	`],
	[`	D68.3	`,`	Haemorrhagic disorder due to circulating anticoagulants Haemorrhage during long-term use of anticoagulants Hyperheparinaemia Increase in: antithrombin anti-VIIIa anti-IXa anti-Xa anti-XIa Use additional external cause code (Chapter XX), if desired, to identify any administered anticoagulant. Excl.: long-term use of anticoagulants without haemorrhage (Z92.1) 	`,`	null	`],
	[`	D68.4	`,`	Acquired coagulation factor deficiency Deficiency of coagulation factor due to: liver disease vitamin K deficiency Excl.: vitamin K deficiency of newborn (P53) 	`,`	null	`],
	[`	D68.5	`,`	Primary Thrombophilia Activated protein C resistance [factor V Leiden mutation] Deficiency: antithrombin protein C protein S Prothrombin gene mutation 	`,`	null	`],
	[`	D68.6	`,`	Other Thrombophilia Anticardiolipin syndrome Antiphospholipid syndrome Presence of the lupus anticoagulant Excl.: disseminated intravascular coagulation (D65) hyperhomocysteinemia (E72.1) 	`,`	null	`],
	[`	D68.8	`,`	Other specified coagulation defects 	`,`	null	`],
	[`	D68.9	`,`	Coagulation defect, unspecified 	`,`	null	`],
	[`	D69	`,`	Purpura and other haemorrhagic conditions Excl.: benign hypergammaglobulinaemic purpura (D89.0) cryoglobulinaemic purpura (D89.1) essential (haemorrhagic) thrombocythaemia (D47.3) purpura fulminans (D65) thrombotic thrombocytopenic purpura (M31.1) 	`,`	null	`],
	[`	D69.0	`,`	Allergic purpura Purpura: anaphylactoid Henoch(-Schonlein) nonthrombocytopenic: haemorrhagic idiopathic vascular Vasculitis, allergic 	`,`	null	`],
	[`	D69.1	`,`	Qualitative platelet defects Bernard-Soulier [giant platelet] syndrome Glanzmann disease Grey platelet syndrome Thromboasthenia (haemorrhagic)(hereditary) Thrombocytopathy Excl.: von Willebrand disease (D68.0) 	`,`	null	`],
	[`	D69.2	`,`	Other nonthrombocytopenic purpura Purpura: NOS senile simplex 	`,`	null	`],
	[`	D69.3	`,`	Idiopathic thrombocytopenic purpura Evans syndrome 	`,`	null	`],
	[`	D69.4	`,`	Other primary thrombocytopenia Excl.: thrombocytopenia with absent radius (Q87.2) transient neonatal thrombocytopenia (P61.0) Wiskott-Aldrich syndrome (D82.0) 	`,`	null	`],
	[`	D69.5	`,`	Secondary thrombocytopenia Use additional external cause code (Chapter XX), if desired, to identify cause. 	`,`	null	`],
	[`	D69.6	`,`	Thrombocytopenia, unspecified 	`,`	null	`],
	[`	D69.8	`,`	Other specified haemorrhagic conditions Capillary fragility (hereditary) Vascular pseudohaemophilia 	`,`	null	`],
	[`	D69.9	`,`	Haemorrhagic condition, unspecified 	`,`	null	`],
	[`	D70	`,`	Agranulocytosis Incl.: Agranulocytic angina Infantile genetic agranulocytosis Kostmann disease Neutropenia: NOS congenital cyclic drug-induced periodic splenic (primary) toxic Neutropenic splenomegaly Werner-Schultz disease Use additional external cause code (Chapter XX), if desired, to identify drug, if drug-induced. Excl.: transient neonatal neutropenia (P61.5) 	`,`	null	`],
	[`	D71	`,`	Functional disorders of polymorphonuclear neutrophils Incl.: Cell membrane receptor complex [CR3] defect Chronic (childhood) granulomatous disease Congenital dysphagocytosis Progressive septic granulomatosis 	`,`	null	`],
	[`	D72	`,`	Other disorders of white blood cells Excl.: basophilia (D75.8) immunity disorders (D80-D89) neutropenia (D70) abnormal white blood cells (count) (R72) preleukaemia (syndrome) (D46.9) 	`,`	null	`],
	[`	D72.0	`,`	Genetic anomalies of leukocytes Anomaly (granulation)(granulocyte) or syndrome: Alder May-Hegglin Pelger-Huet Hereditary: leukocytic: hypersegmentation hyposegmentation leukomelanopathy Excl.: Chediak(-Steinbrinck)-Higashi syndrome (E70.3) 	`,`	null	`],
	[`	D72.1	`,`	Eosinophilia Eosinophilia: allergic hereditary 	`,`	null	`],
	[`	D72.8	`,`	Other specified disorders of white blood cells Leukaemoid reaction: lymphocytic monocytic myelocytic Leukocytosis Lymphocytosis (symptomatic) Lymphopenia Monocytosis (symptomatic) Plasmacytosis 	`,`	null	`],
	[`	D72.9	`,`	Disorder of white blood cells, unspecified 	`,`	null	`],
	[`	D73	`,`	Diseases of spleen 	`,`	null	`],
	[`	D73.0	`,`	Hyposplenism Asplenia, postsurgical Atrophy of spleen Excl.: asplenia (congenital) (Q89.0) 	`,`	null	`],
	[`	D73.1	`,`	Hypersplenism Excl.: splenomegaly: NOS (R16.1) congenital (Q89.0) 	`,`	null	`],
	[`	D73.2	`,`	Chronic congestive splenomegaly 	`,`	null	`],
	[`	D73.3	`,`	Abscess of spleen 	`,`	null	`],
	[`	D73.4	`,`	Cyst of spleen 	`,`	null	`],
	[`	D73.5	`,`	Infarction of spleen Splenic rupture, nontraumatic Torsion of spleen Excl.: traumatic rupture of spleen (S36.0) 	`,`	null	`],
	[`	D73.8	`,`	Other diseases of spleen Fibrosis of spleen NOS Perisplenitis Splenitis NOS 	`,`	null	`],
	[`	D73.9	`,`	Disease of spleen, unspecified 	`,`	null	`],
	[`	D74	`,`	Methaemoglobinaemia 	`,`	null	`],
	[`	D74.0	`,`	Congenital methaemoglobinaemia Congenital NADH-methaemoglobin reductase deficiency Haemoglobin-M [Hb-M] disease Methaemoglobinaemia, hereditary 	`,`	null	`],
	[`	D74.8	`,`	Other methaemoglobinaemias Acquired methaemoglobinaemia (with sulfhaemoglobinaemia) Toxic methaemoglobinaemia Use additional external cause code (Chapter XX), if desired, to identify cause. 	`,`	null	`],
	[`	D74.9	`,`	Methaemoglobinaemia, unspecified 	`,`	null	`],
	[`	D75	`,`	Other diseases of blood and blood-forming organs Excl.: enlarged lymph nodes (R59.-) hypergammaglobulinaemia NOS (D89.2) lymphadenitis: NOS (I88.9) acute (L04.-) chronic (I88.1) mesenteric (acute)(chronic) (I88.0) 	`,`	null	`],
	[`	D75.0	`,`	Familial erythrocytosis Polycythaemia: benign familial Excl.: hereditary ovalocytosis (D58.1) 	`,`	null	`],
	[`	D75.1	`,`	Secondary polycythaemia Erythrocytosis NOS Polycythaemia: NOS acquired due to: erythropoietin fall in plasma volume high altitude stress emotional hypoxaemic nephrogenous relative Excl.: polycythaemia: neonatorum (P61.1) vera (D45) 	`,`	null	`],
	[`	D75.8	`,`	Other specified diseases of blood and blood-forming organs Basophilia 	`,`	null	`],
	[`	D75.9	`,`	Disease of blood and blood-forming organs, unspecified 	`,`	null	`],
	[`	D76	`,`	Other specified diseases with participation of lymphoreticular and reticulohistiocytic tissue Excl.: (Abt-)Letterer-Siwe disease (C96.0) eosinophilic granuloma (C96.6) Hand-Schuller-Christian disease (C96.5) histiocytic sarcoma (C96.8) histiocytosis X, multifocal (C96.5) histiocytosis X, unifocal (C96.6) Langerhans-cell histiocytosis, multifocal (C96.5) Langerhans-cell histiocytosis, unifocal (C96.6) malignant histiocytosis (C96.8) reticuloendotheliosis: leukaemic (C91.4) nonlipid (C96.0) reticulosis: histiocytic medullary (C96.8) lipomelanotic (I89.8) malignant NOS (C86.0) 	`,`	null	`],
	[`	D76.1	`,`	Haemophagocytic lymphohistiocytosis Familial haemophagocytic reticulosis Histiocytoses of mononuclear phagocytes 	`,`	null	`],
	[`	D76.2	`,`	Haemophagocytic syndrome, infection-associated Use additional code, if desired, to identify infectious agent or disease. 	`,`	null	`],
	[`	D76.3	`,`	Other histiocytosis syndromes Reticulohistiocytoma (giant-cell) Sinus histiocytosis with massive lymphadenopathy Xanthogranuloma 	`,`	null	`],
	[`	D77*	`,`	Other disorders of blood and blood-forming organs in diseases classified elsewhere Incl.: Fibrosis of spleen in schistosomiasis [bilharziasis] (B65.-) 	`,`	null	`],
	[`	D80	`,`	Immunodeficiency with predominantly antibody defects 	`,`	null	`],
	[`	D80.0	`,`	Hereditary hypogammaglobulinaemia Autosomal recessive agammaglobulinaemia (Swiss type) X-linked agammaglobulinaemia [Bruton] (with growth hormone deficiency) 	`,`	null	`],
	[`	D80.1	`,`	Nonfamilial hypogammaglobulinaemia Agammaglobulinaemia with immunoglobulin-bearing B-lymphocytes Common variable agammaglobulinaemia [CVAgamma] Hypogammaglobulinaemia NOS 	`,`	null	`],
	[`	D80.2	`,`	Selective deficiency of immunoglobulin A [IgA] 	`,`	null	`],
	[`	D80.3	`,`	Selective deficiency of immunoglobulin G [IgG] subclasses 	`,`	null	`],
	[`	D80.4	`,`	Selective deficiency of immunoglobulin M [IgM] 	`,`	null	`],
	[`	D80.5	`,`	Immunodeficiency with increased immunoglobulin M [IgM] 	`,`	null	`],
	[`	D80.6	`,`	Antibody deficiency with near-normal immunoglobulins or with hyperimmunoglobulinaemia 	`,`	null	`],
	[`	D80.7	`,`	Transient hypogammaglobulinaemia of infancy 	`,`	null	`],
	[`	D80.8	`,`	Other immunodeficiencies with predominantly antibody defects Kappa light chain deficiency 	`,`	null	`],
	[`	D80.9	`,`	Immunodeficiency with predominantly antibody defects, unspecified 	`,`	null	`],
	[`	D81	`,`	Combined immunodeficiencies Excl.: autosomal recessive agammaglobulinaemia (Swiss type) (D80.0) 	`,`	null	`],
	[`	D81.0	`,`	Severe combined immunodeficiency [SCID] with reticular dysgenesis 	`,`	null	`],
	[`	D81.1	`,`	Severe combined immunodeficiency [SCID] with low T- and B-cell numbers 	`,`	null	`],
	[`	D81.2	`,`	Severe combined immunodeficiency [SCID] with low or normal B-cell numbers 	`,`	null	`],
	[`	D81.3	`,`	Adenosine deaminase [ADA] deficiency 	`,`	null	`],
	[`	D81.4	`,`	Nezelof syndrome 	`,`	null	`],
	[`	D81.5	`,`	Purine nucleoside phosphorylase [PNP] deficiency 	`,`	null	`],
	[`	D81.6	`,`	Major histocompatibility complex class I deficiency Bare lymphocyte syndrome 	`,`	null	`],
	[`	D81.7	`,`	Major histocompatibility complex class II deficiency 	`,`	null	`],
	[`	D81.8	`,`	Other combined immunodeficiencies Biotin-dependent carboxylase deficiency 	`,`	null	`],
	[`	D81.9	`,`	Combined immunodeficiency, unspecified Severe combined immunodeficiency disorder [SCID] NOS 	`,`	null	`],
	[`	D82	`,`	Immunodeficiency associated with other major defects Excl.: ataxia telangiectasia [Louis-Bar] (G11.3) 	`,`	null	`],
	[`	D82.0	`,`	Wiskott-Aldrich syndrome Immunodeficiency with thrombocytopenia and eczema 	`,`	null	`],
	[`	D82.1	`,`	Di George syndrome Pharyngeal pouch syndrome Thymic: alymphoplasia aplasia or hypoplasia with immunodeficiency 	`,`	null	`],
	[`	D82.2	`,`	Immunodeficiency with short-limbed stature 	`,`	null	`],
	[`	D82.3	`,`	Immunodeficiency following hereditary defective response to Epstein-Barr virus X-linked lymphoproliferative disease 	`,`	null	`],
	[`	D82.4	`,`	Hyperimmunoglobulin E [IgE] syndrome 	`,`	null	`],
	[`	D82.8	`,`	Immunodeficiency associated with other specified major defects 	`,`	null	`],
	[`	D82.9	`,`	Immunodeficiency associated with major defect, unspecified 	`,`	null	`],
	[`	D83	`,`	Common variable immunodeficiency 	`,`	null	`],
	[`	D83.0	`,`	Common variable immunodeficiency with predominant abnormalities of B-cell numbers and function 	`,`	null	`],
	[`	D83.1	`,`	Common variable immunodeficiency with predominant immunoregulatory T-cell disorders 	`,`	null	`],
	[`	D83.2	`,`	Common variable immunodeficiency with autoantibodies to B- or T-cells 	`,`	null	`],
	[`	D83.8	`,`	Other common variable immunodeficiencies 	`,`	null	`],
	[`	D83.9	`,`	Common variable immunodeficiency, unspecified 	`,`	null	`],
	[`	D84	`,`	Other immunodeficiencies 	`,`	null	`],
	[`	D84.0	`,`	Lymphocyte function antigen-1 [LFA-1] defect 	`,`	null	`],
	[`	D84.1	`,`	Defects in the complement system C1 esterase inhibitor [C1-INH] deficiency 	`,`	null	`],
	[`	D84.8	`,`	Other specified immunodeficiencies 	`,`	null	`],
	[`	D84.9	`,`	Immunodeficiency, unspecified 	`,`	null	`],
	[`	D86	`,`	Sarcoidosis 	`,`	null	`],
	[`	D86.0	`,`	Sarcoidosis of lung 	`,`	null	`],
	[`	D86.1	`,`	Sarcoidosis of lymph nodes 	`,`	null	`],
	[`	D86.2	`,`	Sarcoidosis of lung with sarcoidosis of lymph nodes 	`,`	null	`],
	[`	D86.3	`,`	Sarcoidosis of skin 	`,`	null	`],
	[`	D86.8	`,`	Sarcoidosis of other and combined sites Iridocyclitis in sarcoidosis (H22.1*) Multiple cranial nerve palsies in sarcoidosis (G53.2*) Sarcoid: arthropathy (M14.8*) myocarditis (I41.8*) myositis (M63.3*) Uveoparotid fever [Heerfordt] 	`,`	null	`],
	[`	D86.9	`,`	Sarcoidosis, unspecified 	`,`	null	`],
	[`	D89	`,`	Other disorders involving the immune mechanism, not elsewhere classified Excl.: hyperglobulinaemia NOS (R77.1) monoclonal gammopathy of undertermined significance [MGUS] (D47.2) transplant failure and rejection (T86.-) 	`,`	null	`],
	[`	D89.0	`,`	Polyclonal hypergammaglobulinaemia Benign hypergammaglobulinaemic purpura Polyclonal gammopathy NOS 	`,`	null	`],
	[`	D89.1	`,`	Cryoglobulinaemia Cryoglobulinaemia: essential idiopathic mixed primary secondary Cryoglobulinaemic: purpura vasculitis 	`,`	null	`],
	[`	D89.2	`,`	Hypergammaglobulinaemia, unspecified 	`,`	null	`],
	[`	D89.3	`,`	Immune reconstitution syndrome Immune reconstitution inflammatory syndrome [IRIS] Use additional external cause code (Chapter XX), if desired, to identify drug. 	`,`	null	`],
	[`	D89.8	`,`	Other specified disorders involving the immune mechanism, not elsewhere classified 	`,`	null	`],
	[`	D89.9	`,`	Disorder involving the immune mechanism, unspecified Immune disease NOS 	`,`	null	`],
							
							
];								
							
							
				
							
							
				
	
let CodeRangeD ={
	f0:function(val1=(-1),val2=(0)){
		let Range1 = DCodes.slice(val1,val2);
		Range1.reverse();
		document.documentElement.innerHTML += `<br>Showing D Codes ${Range1.length} items(s)`;

		for(value1 in Range1){
			    document.documentElement.style.cssText += "background-color:tan;";
				document.getElementById('dcodesTR').outerHTML += `<tr><td style="background-color:navy;color:white;width:5%;padding:40px;border:2px solid white;font-weight:900;font-size:40px;text-align:center;">${Range1[value1][0]}</td><td style="background-color:black;color:white;width:90%;padding:20px;border:2px solid white;font-size:30px;">${Range1[value1][1]}</td><td style="background-color:navy;color:white;width:5%;padding:20px;border:2px solid white;font-weight:900;font-size:40px;text-align:center;">${Range1[value1][2]}</td></tr>`;			
		}

	},

};

	






	






