								
let ECodes = [								
								
	[`		`,`		`,`		`],
	[`	E00	`,`	Congenital iodine-deficiency syndrome Incl.: endemic conditions associated with environmental iodine deficiency either directly or as a consequence of maternal iodine deficiency. Some of the conditions have no current hypothyroidism but are the consequence of inadequate thyroid hormone secretion in the developing fetus. Environmental goitrogens may be associated. Use additional code (F70-F79), if desired, to identify associated mental retardation. Excl.: subclinical iodine-deficiency hypothyroidism (E02) 	`,`	null	`],
	[`	E00.0	`,`	Congenital iodine-deficiency syndrome, neurological type Endemic cretinism, neurological type 	`,`	null	`],
	[`	E00.1	`,`	Congenital iodine-deficiency syndrome, myxoedematous type Endemic cretinism: hypothyroid myxoedematous type 	`,`	null	`],
	[`	E00.2	`,`	Congenital iodine-deficiency syndrome, mixed type Endemic cretinism, mixed type 	`,`	null	`],
	[`	E00.9	`,`	Congenital iodine-deficiency syndrome, unspecified Congenital iodine-deficiency hypothyroidism NOS Endemic cretinism NOS 	`,`	null	`],
	[`	E01	`,`	Iodine-deficiency-related thyroid disorders and allied conditions Excl.: congenital iodine-deficiency syndrome (E00.-) subclinical iodine-deficiency hypothyroidism (E02) 	`,`	null	`],
	[`	E01.0	`,`	Iodine-deficiency-related diffuse (endemic) goitre 	`,`	null	`],
	[`	E01.1	`,`	Iodine-deficiency-related multinodular (endemic) goitre Iodine-deficiency-related nodular goitre 	`,`	null	`],
	[`	E01.2	`,`	Iodine-deficiency-related (endemic) goitre, unspecified Endemic goitre NOS 	`,`	null	`],
	[`	E01.8	`,`	Other iodine-deficiency-related thyroid disorders and allied conditions Acquired iodine-deficiency hypothyroidism NOS 	`,`	null	`],
	[`	E02	`,`	Subclinical iodine-deficiency hypothyroidism 	`,`	null	`],
	[`	E03	`,`	Other hypothyroidism Excl.: iodine-deficiency-related hypothyroidism (E00-E02) postprocedural hypothyroidism (E89.0) 	`,`	null	`],
	[`	E03.0	`,`	Congenital hypothyroidism with diffuse goitre Goitre (nontoxic) congenital: NOS parenchymatous Excl.: transitory congenital goitre with normal function (P72.0) 	`,`	null	`],
	[`	E03.1	`,`	Congenital hypothyroidism without goitre Aplasia of thyroid (with myxoedema) Congenital: atrophy of thyroid hypothyroidism NOS 	`,`	null	`],
	[`	E03.2	`,`	Hypothyroidism due to medicaments and other exogenous substances Use additional external cause code (Chapter XX), if desired, to identify cause. 	`,`	null	`],
	[`	E03.3	`,`	Postinfectious hypothyroidism 	`,`	null	`],
	[`	E03.4	`,`	Atrophy of thyroid (acquired) Excl.: congenital atrophy of thyroid (E03.1) 	`,`	null	`],
	[`	E03.5	`,`	Myxoedema coma 	`,`	null	`],
	[`	E03.8	`,`	Other specified hypothyroidism 	`,`	null	`],
	[`	E03.9	`,`	Hypothyroidism, unspecified Myxoedema NOS 	`,`	null	`],
	[`	E04	`,`	Other nontoxic goitre Excl.: congenital goitre: NOS (E03.3) diffuse (E03.3) parenchymatous (E03.3) iodine-deficiency-related goitre (E00-E02) 	`,`	null	`],
	[`	E04.0	`,`	Nontoxic diffuse goitre Goitre, nontoxic: diffuse (colloid) simple 	`,`	null	`],
	[`	E04.1	`,`	Nontoxic single thyroid nodule Colloid nodule (cystic)(thyroid) Nontoxic uninodular goitre Thyroid (cystic) nodule NOS 	`,`	null	`],
	[`	E04.2	`,`	Nontoxic multinodular goitre Cystic goitre NOS Multinodular (cystic) goitre NOS 	`,`	null	`],
	[`	E04.8	`,`	Other specified nontoxic goitre 	`,`	null	`],
	[`	E04.9	`,`	Nontoxic goitre, unspecified Goitre NOS Nodular goitre (nontoxic) NOS 	`,`	null	`],
	[`	E05	`,`	Thyrotoxicosis [hyperthyroidism] Excl.: chronic thyroiditis with transient thyrotoxicosis (E06.2) neonatal thyrotoxicosis (P72.1) 	`,`	null	`],
	[`	E05.0	`,`	Thyrotoxicosis with diffuse goitre Exophthalmic or toxic goitre NOS Graves disease Toxic diffuse goitre 	`,`	null	`],
	[`	E05.1	`,`	Thyrotoxicosis with toxic single thyroid nodule Thyrotoxicosis with toxic uninodular goitre 	`,`	null	`],
	[`	E05.2	`,`	Thyrotoxicosis with toxic multinodular goitre Toxic nodular goitre NOS 	`,`	null	`],
	[`	E05.3	`,`	Thyrotoxicosis from ectopic thyroid tissue 	`,`	null	`],
	[`	E05.4	`,`	Thyrotoxicosis factitia 	`,`	null	`],
	[`	E05.5	`,`	Thyroid crisis or storm 	`,`	null	`],
	[`	E05.8	`,`	Other thyrotoxicosis Overproduction of thyroid-stimulating hormone Use additional external cause code (Chapter XX), if desired, to identify cause. 	`,`	null	`],
	[`	E05.9	`,`	Thyrotoxicosis, unspecified Hyperthyroidism NOS Thyrotoxic heart disease (I43.8*) 	`,`	null	`],
	[`	E06	`,`	Thyroiditis Excl.: postpartum thyroiditis (O90.5) 	`,`	null	`],
	[`	E06.0	`,`	Acute thyroiditis Abscess of thyroid Thyroiditis: pyogenic suppurative Use additional code (B95-B98), if desired, to identify infectious agent. 	`,`	null	`],
	[`	E06.1	`,`	Subacute thyroiditis Thyroiditis: de Quervain giant-cell granulomatous nonsuppurative Excl.: autoimmune thyroiditis (E06.3) 	`,`	null	`],
	[`	E06.2	`,`	Chronic thyroiditis with transient thyrotoxicosis Excl.: autoimmune thyroiditis (E06.3) 	`,`	null	`],
	[`	E06.3	`,`	Autoimmune thyroiditis Hashimoto thyroiditis Hashitoxicosis (transient) Lymphadenoid goitre Lymphocytic thyroiditis Struma lymphomatosa 	`,`	null	`],
	[`	E06.4	`,`	Drug-induced thyroiditis Use additional external cause code (Chapter XX), if desired, to identify drug. 	`,`	null	`],
	[`	E06.5	`,`	Other chronic thyroiditis Thyroiditis: chronic: NOS fibrous ligneous Riedel 	`,`	null	`],
	[`	E06.9	`,`	Thyroiditis, unspecified 	`,`	null	`],
	[`	E07	`,`	Other disorders of thyroid 	`,`	null	`],
	[`	E07.0	`,`	Hypersecretion of calcitonin C-cell hyperplasia of thyroid Hypersecretion of thyrocalcitonin 	`,`	null	`],
	[`	E07.1	`,`	Dyshormogenetic goitre Familial dyshormogenetic goitre Pendred syndrome Excl.: transitory congenital goitre with normal function (P72.0) 	`,`	null	`],
	[`	E07.8	`,`	Other specified disorders of thyroid Abnormality of thyroid-binding globulin Haemorrhage Infarction of thyroid Sick-euthyroid syndrome 	`,`	null	`],
	[`	E07.9	`,`	Disorder of thyroid, unspecified 	`,`	null	`],
	[`	0	`,`	With coma Diabetic: coma with or without ketoacidosis hyperosmolar coma hypoglycaemic coma Hyperglycaemic coma NOS 	`,`	null	`],
	[`	0.1	`,`	With ketoacidosis Diabetic: acidosis ketoacidosis without mention of coma 	`,`	null	`],
	[`	0.2	`,`	With renal complications Diabetic nephropathy (N08.3*) Intracapillary glomerulonephrosis (N08.3*) Kimmelstiel-Wilson syndrome (N08.3*) 	`,`	null	`],
	[`	0.3	`,`	With ophthalmic complications Diabetic: cataract (H28.0*) retinopathy (H36.0*) 	`,`	null	`],
	[`	0.4	`,`	With neurological complications Diabetic: amyotrophy (G73.0*) autonomic neuropathy (G99.0*) mononeuropathy (G59.0*) polyneuropathy (G63.2*) autonomic (G99.0*) 	`,`	null	`],
	[`	0.5	`,`	With peripheral circulatory complications Diabetic: gangrene peripheral angiopathy (I79.2*) ulcer 	`,`	null	`],
	[`	0.6	`,`	With other specified complications Diabetic arthropathy (M14.2*) Neuropathic diabetic arthropathy (M14.6*) 	`,`	null	`],
	[`	0.7	`,`	With multiple complications 	`,`	null	`],
	[`	0.8	`,`	With unspecified complications 	`,`	null	`],
	[`	0.9	`,`	Without complications 	`,`	null	`],
	[`	E10	`,`	Type 1 diabetes mellitus [See before E10 for subdivisions] Incl.: diabetes (mellitus): brittle juvenile-onset ketosis-prone Excl.: diabetes mellitus (in): malnutrition-related (E12.-) neonatal (P70.2) pregnancy, childbirth and the puerperium (O24.-) glycosuria: NOS (R81) renal (E74.8) impaired glucose tolerance (R73.0) postsurgical hypoinsulinaemia (E89.1) 	`,`	null	`],
	[`	E11	`,`	Type 2 diabetes mellitus [See before E10 for subdivisions] Incl.: diabetes (mellitus)(nonobese)(obese): adult-onset maturity-onset nonketotic stable non-insulin-dependent diabetes of the young Excl.: diabetes mellitus (in): malnutrition-related (E12.-) neonatal (P70.2) pregnancy, childbirth and the puerperium (O24.-) glycosuria: NOS (R81) renal (E74.8) impaired glucose tolerance (R73.0) postsurgical hypoinsulinaemia (E89.1) 	`,`	null	`],
	[`	E12	`,`	Malnutrition-related diabetes mellitus [See before E10 for subdivisions] Incl.: malnutrition-related diabetes mellitus: type 1 type 2 Excl.: diabetes mellitus in pregnancy, childbirth and the puerperium (O24.-) glycosuria: NOS (R81) renal (E74.8) impaired glucose tolerance (R73.0) neonatal diabetes mellitus (P70.2) postsurgical hypoinsulinaemia (E89.1) 	`,`	null	`],
	[`	E13	`,`	Other specified diabetes mellitus [See before E10 for subdivisions] Excl.: diabetes mellitus (in): malnutrition-related (E12.-) neonatal (P70.2) pregnancy, childbirth and the puerperium (O24.-) type 1 (E10.-) type 2 (E11.-) glycosuria: NOS (R81) renal (E74.8) impaired glucose tolerance (R73.0) postsurgical hypoinsulinaemia (E89.1) 	`,`	null	`],
	[`	E14	`,`	Unspecified diabetes mellitus [See before E10 for subdivisions] Incl.: diabetes NOS Excl.: diabetes mellitus (in): malnutrition-related (E12.-) neonatal (P70.2) pregnancy, childbirth and the puerperium (O24.-) Type 1 (E10.-) Type 2 (E11.-) glycosuria: NOS (R81) renal (E74.8) impaired glucose tolerance (R73.0) postsurgical hypoinsulinaemia (E89.1) 	`,`	null	`],
	[`	E15	`,`	Nondiabetic hypoglycaemic coma Incl.: Drug-induced insulin coma in nondiabetic Hyperinsulinism with hypoglycaemic coma Hypoglycaemic coma NOS Use additional external cause code (Chapter XX), if desired, to identify drug, if drug-induced. 	`,`	null	`],
	[`	E16	`,`	Other disorders of pancreatic internal secretion 	`,`	null	`],
	[`	E16.0	`,`	Drug-induced hypoglycaemia without coma Use additional external cause code (Chapter XX), if desired, to identify drug. 	`,`	null	`],
	[`	E16.1	`,`	Other hypoglycaemia Functional nonhyperinsulinaemic hypoglycaemia Hyperinsulinism: NOS functional Hyperplasia of pancreatic islet beta cells NOS Posthypoglycaemic coma encephalopathy 	`,`	null	`],
	[`	E16.2	`,`	Hypoglycaemia, unspecified 	`,`	null	`],
	[`	E16.3	`,`	Increased secretion of glucagon Hyperplasia of pancreatic endocrine cells with glucagon excess 	`,`	null	`],
	[`	E16.4	`,`	Abnormal secretion of gastrin Hypergastrinaemia Zollinger-Ellison syndrome 	`,`	null	`],
	[`	E16.8	`,`	Other specified disorders of pancreatic internal secretion Increased secretion from endocrine pancreas of: growth hormone-releasing hormone pancreatic polypeptide somatostatin vasoactive-intestinal polypeptide 	`,`	null	`],
	[`	E16.9	`,`	Disorder of pancreatic internal secretion, unspecified Islet-cell hyperplasia NOS Pancreatic endocrine cell hyperplasia NOS 	`,`	null	`],
	[`	E20	`,`	Hypoparathyroidism Excl.: Di George syndrome (D82.1) postprocedural hypoparathyroidism (E89.2) tetany NOS (R29.0) transitory neonatal hypoparathyroidism (P71.4) 	`,`	null	`],
	[`	E20.0	`,`	Idiopathic hypoparathyroidism 	`,`	null	`],
	[`	E20.1	`,`	Pseudohypoparathyroidism 	`,`	null	`],
	[`	E20.8	`,`	Other hypoparathyroidism 	`,`	null	`],
	[`	E20.9	`,`	Hypoparathyroidism, unspecified Parathyroid tetany 	`,`	null	`],
	[`	E21	`,`	Hyperparathyroidism and other disorders of parathyroid gland Excl.: osteomalacia: adult (M83.-) infantile and juvenile (E55.0) 	`,`	null	`],
	[`	E21.0	`,`	Primary hyperparathyroidism Hyperplasia of parathyroid Osteitis fibrosa cystica generalisata [von Recklinghausen disease of bone] 	`,`	null	`],
	[`	E21.1	`,`	Secondary hyperparathyroidism, not elsewhere classified Excl.: secondary hyperparathyroidism of renal origin (N25.8) 	`,`	null	`],
	[`	E21.2	`,`	Other hyperparathyroidism Tertiary hyperparathryoidism Excl.: familial hypocalciuric hypercalcaemia (E83.5) 	`,`	null	`],
	[`	E21.3	`,`	Hyperparathyroidism, unspecified 	`,`	null	`],
	[`	E21.4	`,`	Other specified disorders of parathyroid gland 	`,`	null	`],
	[`	E21.5	`,`	Disorder of parathyroid gland, unspecified 	`,`	null	`],
	[`	E22	`,`	Hyperfunction of pituitary gland Excl.: Cushing syndrome (E24.-) Nelson syndrome (E24.1) overproduction of: ACTH not associated with Cushing disease (E27.0) pituitary ACTH (E24.0) thyroid-stimulating hormone (E05.8) 	`,`	null	`],
	[`	E22.0	`,`	Acromegaly and pituitary gigantism Arthropathy associated with acromegaly (M14.5*) Overproduction of growth hormone Excl.: constitutional: gigantism (E34.4) tall stature (E34.4) increased secretion from endocrine pancreas of growth hormone-releasing hormone (E16.8) 	`,`	null	`],
	[`	E22.1	`,`	Hyperprolactinaemia Use additional external cause code (Chapter XX), if desired, to identify drug, if drug-induced. 	`,`	null	`],
	[`	E22.2	`,`	Syndrome of inappropriate secretion of antidiuretic hormone 	`,`	null	`],
	[`	E22.8	`,`	Other hyperfunction of pituitary gland Central precocious puberty 	`,`	null	`],
	[`	E22.9	`,`	Hyperfunction of pituitary gland, unspecified 	`,`	null	`],
	[`	E23	`,`	Hypofunction and other disorders of pituitary gland Incl.: the listed conditions whether the disorder is in the pituitary or the hypothalamus Excl.: postprocedural hypopituitarism (E89.3) 	`,`	null	`],
	[`	E23.0	`,`	Hypopituitarism Fertile eunuch syndrome Hypogonadotropic hypogonadism Idiopathic growth hormone deficiency Isolated deficiency of: gonadotropin growth hormone pituitary hormone Kallmann syndrome Lorain-Levi short stature Necrosis of pituitary gland (postpartum) Panhypopituitarism Pituitary: cachexia insufficiency NOS short stature Sheehan syndrome Simmonds disease 	`,`	null	`],
	[`	E23.1	`,`	Drug-induced hypopituitarism Use additional external cause code (Chapter XX), if desired, to identify drug. 	`,`	null	`],
	[`	E23.2	`,`	Diabetes insipidus Excl.: nephrogenic diabetes insipidus (N25.1) 	`,`	null	`],
	[`	E23.3	`,`	Hypothalamic dysfunction, not elsewhere classified Excl.: Prader-Willi syndrome (Q87.1) Russell-Silver syndrome (Q87.1) 	`,`	null	`],
	[`	E23.6	`,`	Other disorders of pituitary gland Abscess of pituitary Adiposogenital dystrophy 	`,`	null	`],
	[`	E23.7	`,`	Disorder of pituitary gland, unspecified 	`,`	null	`],
	[`	E24	`,`	Cushing syndrome 	`,`	null	`],
	[`	E24.0	`,`	Pituitary-dependent Cushing disease Overproduction of pituitary ACTH Pituitary-dependent hyperadrenocorticism 	`,`	null	`],
	[`	E24.1	`,`	Nelson syndrome 	`,`	null	`],
	[`	E24.2	`,`	Drug-induced Cushing syndrome Use additional external cause code (Chapter XX), if desired, to identify drug. 	`,`	null	`],
	[`	E24.3	`,`	Ectopic ACTH syndrome 	`,`	null	`],
	[`	E24.4	`,`	Alcohol-induced pseudo-Cushing syndrome 	`,`	null	`],
	[`	E24.8	`,`	Other Cushing syndrome 	`,`	null	`],
	[`	E24.9	`,`	Cushing syndrome, unspecified 	`,`	null	`],
	[`	E25	`,`	Adrenogenital disorders Incl.: adrenogenital syndromes, virilizing or feminizing, whether acquired or due to adrenal hyperplasia consequent on inborn enzyme defects in hormone synthesis female: adrenal pseudohermaphroditism heterosexual precocious pseudopuberty male: isosexual precocious pseudopuberty macrogenitosomia praecox sexual precocity with adrenal hyperplasia virilization (female) 	`,`	null	`],
	[`	E25.0	`,`	Congenital adrenogenital disorders associated with enzyme deficiency Congenital adrenal hyperplasia 21-Hydroxylase deficiency Salt-losing congenital adrenal hyperplasia 	`,`	null	`],
	[`	E25.8	`,`	Other adrenogenital disorders Idiopathic adrenogenital disorder Use additional external cause code (Chapter XX), if desired, to identify drug, if drug-induced. 	`,`	null	`],
	[`	E25.9	`,`	Adrenogenital disorder, unspecified Adrenogenital syndrome NOS 	`,`	null	`],
	[`	E26	`,`	Hyperaldosteronism 	`,`	null	`],
	[`	E26.0	`,`	Primary hyperaldosteronism Conn syndrome Primary aldosteronism due to adrenal hyperplasia (bilateral) 	`,`	null	`],
	[`	E26.1	`,`	Secondary hyperaldosteronism 	`,`	null	`],
	[`	E26.8	`,`	Other hyperaldosteronism Bartter syndrome 	`,`	null	`],
	[`	E26.9	`,`	Hyperaldosteronism, unspecified 	`,`	null	`],
	[`	E27	`,`	Other disorders of adrenal gland 	`,`	null	`],
	[`	E27.0	`,`	Other adrenocortical overactivity Overproduction of ACTH, not associated with Cushing disease Premature adrenarche Excl.: Cushing syndrome (E24.-) 	`,`	null	`],
	[`	E27.1	`,`	Primary adrenocortical insufficiency Addison disease Autoimmune adrenalitis Excl.: amyloidosis (E85.-) tuberculous Addison disease (A18.7) Waterhouse-Friderichsen syndrome (A39.1) 	`,`	null	`],
	[`	E27.2	`,`	Addisonian crisis Adrenal crisis Adrenocortical crisis 	`,`	null	`],
	[`	E27.3	`,`	Drug-induced adrenocortical insufficiency Use additional external cause code (Chapter XX), if desired, to identify drug. 	`,`	null	`],
	[`	E27.4	`,`	Other and unspecified adrenocortical insufficiency Adrenal: haemorrhage infarction Adrenocortical insufficiency NOS Hypoaldosteronism Excl.: adrenoleukodystrophy [Addison-Schilder] (E71.3) Waterhouse-Friderichsen syndrome (A39.1) 	`,`	null	`],
	[`	E27.5	`,`	Adrenomedullary hyperfunction Adrenomedullary hyperplasia Catecholamine hypersecretion 	`,`	null	`],
	[`	E27.8	`,`	Other specified disorders of adrenal gland Abnormality of cortisol-binding globulin 	`,`	null	`],
	[`	E27.9	`,`	Disorder of adrenal gland, unspecified 	`,`	null	`],
	[`	E28	`,`	Ovarian dysfunction Excl.: isolated gonadotropin deficiency (E23.0) postprocedural ovarian failure (E89.4) 	`,`	null	`],
	[`	E28.0	`,`	Estrogen excess Use additional external cause code (Chapter XX), if desired, to identify drug, if drug-induced. 	`,`	null	`],
	[`	E28.1	`,`	Androgen excess Hypersecretion of ovarian androgens Use additional external cause code (Chapter XX), if desired, to identify drug, if drug-induced. 	`,`	null	`],
	[`	E28.2	`,`	Polycystic ovarian syndrome Sclerocystic ovary syndrome Stein-Leventhal syndrome 	`,`	null	`],
	[`	E28.3	`,`	Primary ovarian failure Decreased estrogen Premature menopause NOS Resistant ovary syndrome Excl.: menopausal and female climacteric states (N95.1) pure gonadal dysgenesis (Q99.1) Turner syndrome (Q96.-) 	`,`	null	`],
	[`	E28.8	`,`	Other ovarian dysfunction Ovarian hyperfunction NOS 	`,`	null	`],
	[`	E28.9	`,`	Ovarian dysfunction, unspecified 	`,`	null	`],
	[`	E29	`,`	Testicular dysfunction Excl.: androgen resistance syndrome (E34.5) azoospermia or oligospermia NOS (N46) isolated gonadotropin deficiency (E23.0) Klinefelter syndrome (Q98.0-Q98.2, Q98.4) postprocedural testicular hypofunction (E89.5) testicular feminization (syndrome) (E34.5) 	`,`	null	`],
	[`	E29.0	`,`	Testicular hyperfunction Hypersecretion of testicular hormones 	`,`	null	`],
	[`	E29.1	`,`	Testicular hypofunction 5-Alpha-reductase deficiency (with male pseudohermaphroditism) Defective biosynthesis of testicular androgen NOS Testicular hypogonadism NOS Use additional external cause code (Chapter XX), if desired, to identify drug, if drug-induced. 	`,`	null	`],
	[`	E29.8	`,`	Other testicular dysfunction 	`,`	null	`],
	[`	E29.9	`,`	Testicular dysfunction, unspecified 	`,`	null	`],
	[`	E30	`,`	Disorders of puberty, not elsewhere classified 	`,`	null	`],
	[`	E30.0	`,`	Delayed puberty Constitutional delay of puberty Delayed sexual development 	`,`	null	`],
	[`	E30.1	`,`	Precocious puberty Precocious menstruation Excl.: Albright(-McCune)(-Sternberg) syndrome (Q78.1) central precocious puberty (E22.8) congenital adrenal hyperplasia (E25.0) female heterosexual precocious pseudopuberty (E25.-) male isosexual precocious pseudopuberty (E25.-) 	`,`	null	`],
	[`	E30.8	`,`	Other disorders of puberty Premature thelarche 	`,`	null	`],
	[`	E30.9	`,`	Disorder of puberty, unspecified 	`,`	null	`],
	[`	E31	`,`	Polyglandular dysfunction Excl.: ataxia telangiectasia [Louis-Bar] (G11.3) dystrophia myotonica [Steinert] (G71.1) pseudohypoparathyroidism (E20.1) 	`,`	null	`],
	[`	E31.0	`,`	Autoimmune polyglandular failure Schmidt syndrome 	`,`	null	`],
	[`	E31.1	`,`	Polyglandular hyperfunction Excl.: multiple endocrine adenomatosis (D44.8) 	`,`	null	`],
	[`	E31.8	`,`	Other polyglandular dysfunction 	`,`	null	`],
	[`	E31.9	`,`	Polyglandular dysfunction, unspecified 	`,`	null	`],
	[`	E32	`,`	Diseases of thymus Excl.: aplasia or hypoplasia with immunodeficiency (D82.1) myasthenia gravis (G70.0) 	`,`	null	`],
	[`	E32.0	`,`	Persistent hyperplasia of thymus Hypertrophy of thymus 	`,`	null	`],
	[`	E32.1	`,`	Abscess of thymus 	`,`	null	`],
	[`	E32.8	`,`	Other diseases of thymus 	`,`	null	`],
	[`	E32.9	`,`	Disease of thymus, unspecified 	`,`	null	`],
	[`	E34	`,`	Other endocrine disorders Excl.: pseudohypoparathyroidism (E20.1) 	`,`	null	`],
	[`	E34.0	`,`	Carcinoid syndrome Note: May be used as an additional code, if desired, to identify functional activity associated with a carcinoid tumour. 	`,`	null	`],
	[`	E34.1	`,`	Other hypersecretion of intestinal hormones 	`,`	null	`],
	[`	E34.2	`,`	Ectopic hormone secretion, not elsewhere classified 	`,`	null	`],
	[`	E34.3	`,`	Short stature, not elsewhere classified Short stature: NOS constitutional Laron-type psychosocial Excl.: progeria (E34.8) Russell-Silver syndrome (Q87.1) short-limbed stature with immunodeficiency (D82.2) short stature: achondroplastic (Q77.4) hypochondroplastic (Q77.4) in specific dysmorphic syndromes - code to syndrome - see Alphabetical Index nutritional (E45) pituitary (E23.0) renal (N25.0) 	`,`	null	`],
	[`	E34.4	`,`	Constitutional tall stature Constitutional gigantism 	`,`	null	`],
	[`	E34.5	`,`	Androgen resistance syndrome Male pseudohermaphroditism with androgen resistance Peripheral hormonal receptor disorder Reifenstein syndrome Testicular feminization (syndrome) 	`,`	null	`],
	[`	E34.8	`,`	Other specified endocrine disorders Pineal gland dysfunction Progeria 	`,`	null	`],
	[`	E34.9	`,`	Endocrine disorder, unspecified Disturbance: endocrine NOS hormone NOS 	`,`	null	`],
	[`	E35*	`,`	Disorders of endocrine glands in diseases classified elsewhere 	`,`	null	`],
	[`	E35.0*	`,`	Disorders of thyroid gland in diseases classified elsewhere Tuberculosis of thyroid gland (A18.8) 	`,`	null	`],
	[`	E35.1*	`,`	Disorders of adrenal glands in diseases classified elsewhere Tuberculous Addison disease (A18.7) Waterhouse-Friderichsen syndrome (meningococcal) (A39.1) 	`,`	null	`],
	[`	E35.8*	`,`	Disorders of other endocrine glands in diseases classified elsewhere 	`,`	null	`],
	[`	E40	`,`	Kwashiorkor Severe malnutrition with nutritional oedema with dyspigmentation of skin and hair. Excl.: marasmic kwashiorkor (E42) 	`,`	null	`],
	[`	E41	`,`	Nutritional marasmus Incl.: Severe malnutrition with marasmus Excl.: marasmic kwashiorkor (E42) 	`,`	null	`],
	[`	E42	`,`	Marasmic kwashiorkor Incl.: Severe protein-energy malnutrition [as in E43]: intermediate form with signs of both kwashiorkor and marasmus 	`,`	null	`],
	[`	E43	`,`	Unspecified severe protein-energy malnutrition Severe loss of weight [wasting] in children or adults, or lack of weight gain in children leading to an observed weight that is at least 3 standard deviations below the mean value for the reference population (or a similar loss expressed through other statistical approaches). When only one measurement is available, there is a high probability of severe wasting when the observed weight is 3 or more standard deviations below the mean of the reference population. Incl.: Starvation oedema 	`,`	null	`],
	[`	E44	`,`	Protein-energy malnutrition of moderate and mild degree 	`,`	null	`],
	[`	E44.0	`,`	Moderate protein-energy malnutrition Weight loss in children or adults, or lack of weight gain in children leading to an observed weight that is 2 or more but less than 3 standard deviations below the mean value for the reference population (or a similar loss expressed through other statistical approaches). When only one measurement is available, there is a high probability of moderate protein-energy malnutrition when the observed weight is 2 or more but less than 3 standard deviations below the mean of the reference population. 	`,`	null	`],
	[`	E44.1	`,`	Mild protein-energy malnutrition Weight loss in children or adults, or lack of weight gain in children leading to an observed weight that is 1 or more but less than 2 standard deviations below the mean value for the reference population (or a similar loss expresssed through other statistical approaches). When only one measurement is available, there is a high probability of mild protein-energy malnutrition when the observed weight is 1 or more but less than 2 standard deviations below the mean of the reference population. 	`,`	null	`],
	[`	E45	`,`	Retarded development following protein-energy malnutrition Incl.: Nutritional: short stature stunting Physical retardation due to malnutrition 	`,`	null	`],
	[`	E46	`,`	Unspecified protein-energy malnutrition Incl.: Malnutrition NOS Protein-energy imbalance NOS 	`,`	null	`],
	[`	E50	`,`	Vitamin A deficiency Excl.: sequelae of vitamin A deficiency (E64.1) 	`,`	null	`],
	[`	E50.0	`,`	Vitamin A deficiency with conjunctival xerosis 	`,`	null	`],
	[`	E50.1	`,`	Vitamin A deficiency with Bitot spot and conjunctival xerosis Bitot spot in the young child 	`,`	null	`],
	[`	E50.2	`,`	Vitamin A deficiency with corneal xerosis 	`,`	null	`],
	[`	E50.3	`,`	Vitamin A deficiency with corneal ulceration and xerosis 	`,`	null	`],
	[`	E50.4	`,`	Vitamin A deficiency with keratomalacia 	`,`	null	`],
	[`	E50.5	`,`	Vitamin A deficiency with night blindness 	`,`	null	`],
	[`	E50.6	`,`	Vitamin A deficiency with xerophthalmic scars of cornea 	`,`	null	`],
	[`	E50.7	`,`	Other ocular manifestations of vitamin A deficiency Xerophthalmia NOS 	`,`	null	`],
	[`	E50.8	`,`	Other manifestations of vitamin A deficiency Follicular keratosis Xeroderma due to vitamin A deficiency (L86*) 	`,`	null	`],
	[`	E50.9	`,`	Vitamin A deficiency, unspecified Hypovitaminosis A NOS 	`,`	null	`],
	[`	E51	`,`	Thiamine deficiency Excl.: sequelae of thiamine deficiency (E64.8) 	`,`	null	`],
	[`	E51.1	`,`	Beriberi Beriberi: dry wet (I98.8*) 	`,`	null	`],
	[`	E51.2	`,`	Wernicke encephalopathy 	`,`	null	`],
	[`	E51.8	`,`	Other manifestations of thiamine deficiency 	`,`	null	`],
	[`	E51.9	`,`	Thiamine deficiency, unspecified 	`,`	null	`],
	[`	E52	`,`	Niacin deficiency [pellagra] Incl.: Deficiency: niacin(-tryptophan) nicotinamide Pellagra (alcoholic) Excl.: sequelae of niacin deficiency (E64.8) 	`,`	null	`],
	[`	E53	`,`	Deficiency of other B group vitamins Excl.: sequelae of vitamin B deficiency (E64.8) vitamin B12 deficiency anaemia (D51.-) 	`,`	null	`],
	[`	E53.0	`,`	Riboflavin deficiency Ariboflavinosis 	`,`	null	`],
	[`	E53.1	`,`	Pyridoxine deficiency Vitamin B6 deficiency Excl.: pyridoxine-responsive sideroblastic anaemia (D64.3) 	`,`	null	`],
	[`	E53.8	`,`	Deficiency of other specified B group vitamins Deficiency: biotin cyanocobalamin folate folic acid pantothenic acid vitamin B12 	`,`	null	`],
	[`	E53.9	`,`	Vitamin B deficiency, unspecified 	`,`	null	`],
	[`	E54	`,`	Ascorbic acid deficiency Incl.: Deficiency of vitamin C Scurvy Excl.: scorbutic anaemia (D53.2) sequelae of vitamin C deficiency (E64.2) 	`,`	null	`],
	[`	E55	`,`	Vitamin D deficiency Excl.: adult osteomalacia (M83.-) osteoporosis (M80-M81) sequelae of rickets (E64.3) 	`,`	null	`],
	[`	E55.0	`,`	Rickets, active Osteomalacia: infantile juvenile Excl.: rickets: coeliac (K90.0) Crohn (K50.-) inactive (E64.3) renal (N25.0) vitamin-D-resistant (E83.3) 	`,`	null	`],
	[`	E55.9	`,`	Vitamin D deficiency, unspecified Avitaminosis D 	`,`	null	`],
	[`	E56	`,`	Other vitamin deficiencies Excl.: sequelae of other vitamin deficiencies (E64.8) 	`,`	null	`],
	[`	E56.0	`,`	Deficiency of vitamin E 	`,`	null	`],
	[`	E56.1	`,`	Deficiency of vitamin K Excl.: deficiency of coagulation factor due to vitamin K deficiency (D68.4) vitamin K deficiency of newborn (P53) 	`,`	null	`],
	[`	E56.8	`,`	Deficiency of other vitamins 	`,`	null	`],
	[`	E56.9	`,`	Vitamin deficiency, unspecified 	`,`	null	`],
	[`	E58	`,`	Dietary calcium deficiency Excl.: disorder of calcium metabolism (E83.5) sequelae of calcium deficiency (E64.8) 	`,`	null	`],
	[`	E59	`,`	Dietary selenium deficiency Incl.: Keshan disease Excl.: sequelae of selenium deficiency (E64.8) 	`,`	null	`],
	[`	E60	`,`	Dietary zinc deficiency 	`,`	null	`],
	[`	E61	`,`	Deficiency of other nutrient elements Use additional external cause code (Chapter XX), if desired, to identify drug, if drug-induced. Excl.: disorders of mineral metabolism (E83.-) iodine-deficiency-related thyroid disorders (E00-E02) sequelae of malnutrition and other nutritional deficiencies (E64.-) 	`,`	null	`],
	[`	E61.0	`,`	Copper deficiency 	`,`	null	`],
	[`	E61.1	`,`	Iron deficiency Excl.: iron deficiency anaemia (D50.-) 	`,`	null	`],
	[`	E61.2	`,`	Magnesium deficiency 	`,`	null	`],
	[`	E61.3	`,`	Manganese deficiency 	`,`	null	`],
	[`	E61.4	`,`	Chromium deficiency 	`,`	null	`],
	[`	E61.5	`,`	Molybdenum deficiency 	`,`	null	`],
	[`	E61.6	`,`	Vanadium deficiency 	`,`	null	`],
	[`	E61.7	`,`	Deficiency of multiple nutrient elements 	`,`	null	`],
	[`	E61.8	`,`	Deficiency of other specified nutrient elements 	`,`	null	`],
	[`	E61.9	`,`	Deficiency of nutrient element, unspecified 	`,`	null	`],
	[`	E63	`,`	Other nutritional deficiencies Excl.: dehydration (E86) failure to thrive (R62.8) feeding problems in newborn (P92.-) sequelae of malnutrition and other nutritional deficiencies (E64.-) 	`,`	null	`],
	[`	E63.0	`,`	Essential fatty acid [EFA] deficiency 	`,`	null	`],
	[`	E63.1	`,`	Imbalance of constituents of food intake 	`,`	null	`],
	[`	E63.8	`,`	Other specified nutritional deficiencies 	`,`	null	`],
	[`	E63.9	`,`	Nutritional deficiency, unspecified Nutritional cardiomyopathy NOS (I43.2*) 	`,`	null	`],
	[`	E64	`,`	Sequelae of malnutrition and other nutritional deficiencies Note: Not to be used for chronic malnutrition or nutritional deficiency. Code these to current malnutrition or nutritional deficiency. 	`,`	null	`],
	[`	E64.0	`,`	Sequelae of protein-energy malnutrition Excl.: retarded development following protein-energy malnutrition (E45) 	`,`	null	`],
	[`	E64.1	`,`	Sequelae of vitamin A deficiency 	`,`	null	`],
	[`	E64.2	`,`	Sequelae of vitamin C deficiency 	`,`	null	`],
	[`	E64.3	`,`	Sequelae of rickets Use additional code (M40.1, M41.5), if desired, to identify spinal deformity 	`,`	null	`],
	[`	E64.8	`,`	Sequelae of other nutritional deficiencies 	`,`	null	`],
	[`	E64.9	`,`	Sequelae of unspecified nutritional deficiency 	`,`	null	`],
	[`	E65	`,`	Localized adiposity Incl.: Fat pad 	`,`	null	`],
	[`	E66	`,`	Obesity Excl.: adiposogenital dystrophy (E23.6) lipomatosis: NOS (E88.2) dolorosa [Dercum] (E88.2) Prader-Willi syndrome (Q87.1) 	`,`	null	`],
	[`	E66.0	`,`	Obesity due to excess calories 	`,`	null	`],
	[`	E66.1	`,`	Drug-induced obesity Use additional external cause code (Chapter XX), if desired, to identify drug. 	`,`	null	`],
	[`	E66.2	`,`	Extreme obesity with alveolar hypoventilation Pickwickian syndrome 	`,`	null	`],
	[`	E66.8	`,`	Other obesity Morbid obesity 	`,`	null	`],
	[`	E66.9	`,`	Obesity, unspecified Simple obesity NOS 	`,`	null	`],
	[`	E67	`,`	Other hyperalimentation Excl.: hyperalimentation NOS (R63.2) sequelae of hyperalimentation (E68) 	`,`	null	`],
	[`	E67.0	`,`	Hypervitaminosis A 	`,`	null	`],
	[`	E67.1	`,`	Hypercarotenaemia 	`,`	null	`],
	[`	E67.2	`,`	Megavitamin-B6 syndrome 	`,`	null	`],
	[`	E67.3	`,`	Hypervitaminosis D 	`,`	null	`],
	[`	E67.8	`,`	Other specified hyperalimentation 	`,`	null	`],
	[`	E68	`,`	Sequelae of hyperalimentation Note: Not to be used for chronic hyperalimentation. Code these to current hyperalimentation. 	`,`	null	`],
	[`	E70	`,`	Disorders of aromatic amino-acid metabolism 	`,`	null	`],
	[`	E70.0	`,`	Classical phenylketonuria 	`,`	null	`],
	[`	E70.1	`,`	Other hyperphenylalaninaemias 	`,`	null	`],
	[`	E70.2	`,`	Disorders of tyrosine metabolism Alkaptonuria Hypertyrosinaemia Ochronosis Tyrosinaemia Tyrosinosis 	`,`	null	`],
	[`	E70.3	`,`	Albinism Albinism: ocular oculocutaneous Syndrome: Chediak(-Steinbrinck)-Higashi Cross Hermansky-Pudlak 	`,`	null	`],
	[`	E70.8	`,`	Other disorders of aromatic amino-acid metabolism Disorders of: histidine metabolism tryptophan metabolism 	`,`	null	`],
	[`	E70.9	`,`	Disorder of aromatic amino-acid metabolism, unspecified 	`,`	null	`],
	[`	E71	`,`	Disorders of branched-chain amino-acid metabolism and fatty-acid metabolism 	`,`	null	`],
	[`	E71.0	`,`	Maple-syrup-urine disease 	`,`	null	`],
	[`	E71.1	`,`	Other disorders of branched-chain amino-acid metabolism Hyperleucine-isoleucinaemia Hypervalinaemia Isovaleric acidaemia Methylmalonic acidaemia Propionic acidaemia 	`,`	null	`],
	[`	E71.2	`,`	Disorder of branched-chain amino-acid metabolism, unspecified 	`,`	null	`],
	[`	E71.3	`,`	Disorders of fatty-acid metabolism Adrenoleukodystrophy [Addison-Schilder] Muscle carnitine palmityltransferase deficiency Very long chain acyl-CoA dehydrogenase (VLCAD) deficiency Excl.: Schilder disease (G37.0) 	`,`	null	`],
	[`	E72	`,`	Other disorders of amino-acid metabolism Excl.: abnormal findings without manifest disease (R70-R89) disorders of: aromatic amino-acid metabolism (E70.-) branched-chain amino-acid metabolism (E71.0-E71.2) fatty-acid metabolism (E71.3) purine and pyrimidine metabolism (E79.-) gout (M10.-) 	`,`	null	`],
	[`	E72.0	`,`	Disorders of amino-acid transport Cystine storage disease (N29.8*) Cystinosis Cystinuria Fanconi(-de Toni)(-Debre) syndrome Hartnup disease Lowe syndrome Excl.: disorders of tryptophan metabolism (E70.8) 	`,`	null	`],
	[`	E72.1	`,`	Disorders of sulfur-bearing amino-acid metabolism Cystathioninuria Homocystinuria Methioninaemia Sulfite oxidase deficiency Excl.: transcobalamin II deficiency (D51.2) 	`,`	null	`],
	[`	E72.2	`,`	Disorders of urea cycle metabolism Argininaemia Argininosuccinic aciduria Citrullinaemia Hyperammonaemia Excl.: disorders of ornithine metabolism (E72.4) 	`,`	null	`],
	[`	E72.3	`,`	Disorders of lysine and hydroxylysine metabolism Glutaric aciduria Hydroxylysinaemia Hyperlysinaemia Excl.: Refsum disease (G60.1) Zellweger syndrome (Q87.8) 	`,`	null	`],
	[`	E72.4	`,`	Disorders of ornithine metabolism Ornithinaemia (types I, II) 	`,`	null	`],
	[`	E72.5	`,`	Disorders of glycine metabolism Hyperhydroxyprolinaemia Hyperprolinaemia (types I, II) Non-ketotic hyperglycinaemia Sarcosinaemia 	`,`	null	`],
	[`	E72.8	`,`	Other specified disorders of amino-acid metabolism Disorders of: Beta-amino-acid metabolism Gamma-glutamyl cycle 	`,`	null	`],
	[`	E72.9	`,`	Disorder of amino-acid metabolism, unspecified 	`,`	null	`],
	[`	E73	`,`	Lactose intolerance 	`,`	null	`],
	[`	E73.0	`,`	Congenital lactase deficiency 	`,`	null	`],
	[`	E73.1	`,`	Secondary lactase deficiency 	`,`	null	`],
	[`	E73.8	`,`	Other lactose intolerance 	`,`	null	`],
	[`	E73.9	`,`	Lactose intolerance, unspecified 	`,`	null	`],
	[`	E74	`,`	Other disorders of carbohydrate metabolism Excl.: increased secretion of glucagon (E16.3) diabetes mellitus (E10-E14) hypoglycaemia NOS (E16.2) mucopolysaccharidosis (E76.0-E76.3) 	`,`	null	`],
	[`	E74.0	`,`	Glycogen storage disease Cardiac glycogenosis Disease: Andersen Cori Forbes Hers McArdle Pompe Tarui Tauri von Gierke Liver phosphorylase deficiency 	`,`	null	`],
	[`	E74.1	`,`	Disorders of fructose metabolism Essential fructosuria Fructose-1,6-diphosphatase deficiency Hereditary fructose intolerance 	`,`	null	`],
	[`	E74.2	`,`	Disorders of galactose metabolism Galactokinase deficiency Galactosaemia 	`,`	null	`],
	[`	E74.3	`,`	Other disorders of intestinal carbohydrate absorption Glucose-galactose malabsorption Sucrase deficiency Excl.: lactose intolerance (E73.-) 	`,`	null	`],
	[`	E74.4	`,`	Disorders of pyruvate metabolism and gluconeogenesis Deficiency of: phosphoenolpyruvate carboxykinase pyruvate: carboxylase dehydrogenase Excl.: with anaemia (D55.-) 	`,`	null	`],
	[`	E74.8	`,`	Other specified disorders of carbohydrate metabolism Essential pentosuria Oxalosis Oxaluria Renal glycosuria 	`,`	null	`],
	[`	E74.9	`,`	Disorder of carbohydrate metabolism, unspecified 	`,`	null	`],
	[`	E75	`,`	Disorders of sphingolipid metabolism and other lipid storage disorders Excl.: mucolipidosis, types I-III (E77.0-E77.1) Refsum disease (G60.1) 	`,`	null	`],
	[`	E75.0	`,`	GM2 gangliosidosis Disease: Sandhoff Tay-Sachs GM2 gangliosidosis: NOS adult juvenile 	`,`	null	`],
	[`	E75.1	`,`	Other gangliosidosis Gangliosidosis: NOS GM1 GM3 Mucolipidosis IV 	`,`	null	`],
	[`	E75.2	`,`	Other sphingolipidosis Disease: Fabry(-Anderson) Gaucher Krabbe Niemann-Pick Farber syndrome Metachromatic leukodystrophy Sulfatase deficiency Excl.: adrenoleukodystrophy [Addison-Schilder] (E71.3) 	`,`	null	`],
	[`	E75.3	`,`	Sphingolipidosis, unspecified 	`,`	null	`],
	[`	E75.4	`,`	Neuronal ceroid lipofuscinosis Disease: Batten Bielschowsky-Jansky Kufs Spielmeyer-Vogt 	`,`	null	`],
	[`	E75.5	`,`	Other lipid storage disorders Cerebrotendinous cholesterosis [van Bogaert-Scherer-Epstein] Wolman disease 	`,`	null	`],
	[`	E75.6	`,`	Lipid storage disorder, unspecified 	`,`	null	`],
	[`	E76	`,`	Disorders of glycosaminoglycan metabolism 	`,`	null	`],
	[`	E76.0	`,`	Mucopolysaccharidosis, type I Syndrome: Hurler Hurler-Scheie Scheie 	`,`	null	`],
	[`	E76.1	`,`	Mucopolysaccharidosis, type II Hunter syndrome 	`,`	null	`],
	[`	E76.2	`,`	Other mucopolysaccharidoses Beta-glucuronidase deficiency Mucopolysaccharidosis, types III, IV, VI, VII Syndrome: Maroteaux-Lamy (mild)(severe) Morquio(-like)(classic) Sanfilippo (type B)(type C)(type D) 	`,`	null	`],
	[`	E76.3	`,`	Mucopolysaccharidosis, unspecified 	`,`	null	`],
	[`	E76.8	`,`	Other disorders of glucosaminoglycan metabolism 	`,`	null	`],
	[`	E76.9	`,`	Disorder of glucosaminoglycan metabolism, unspecified 	`,`	null	`],
	[`	E77	`,`	Disorders of glycoprotein metabolism 	`,`	null	`],
	[`	E77.0	`,`	Defects in post-translational modification of lysosomal enzymes Mucolipidosis II [I-cell disease] Mucolipidosis III [pseudo-Hurler polydystrophy] 	`,`	null	`],
	[`	E77.1	`,`	Defects in glycoprotein degradation Aspartylglucosaminuria Fucosidosis Mannosidosis Sialidosis [mucolipidosis I] 	`,`	null	`],
	[`	E77.8	`,`	Other disorders of glycoprotein metabolism 	`,`	null	`],
	[`	E77.9	`,`	Disorder of glycoprotein metabolism, unspecified 	`,`	null	`],
	[`	E78	`,`	Disorders of lipoprotein metabolism and other lipidaemias Excl.: sphingolipidosis (E75.0-E75.3) 	`,`	null	`],
	[`	E78.0	`,`	Pure hypercholesterolaemia Familial hypercholesterolaemia Fredrickson hyperlipoproteinaemia, type IIa Hyperbetalipoproteinaemia Hyperlipidaemia, group A Low-density-lipoprotein-type [LDL] hyperlipoproteinaemia 	`,`	null	`],
	[`	E78.1	`,`	Pure hyperglyceridaemia Endogenous hyperglyceridaemia Fredrickson hyperlipoproteinaemia, type IV Hyperlipidaemia, group B Hyperprebetalipoproteinaemia Very-low-density-lipoprotein-type [VLDL] hyperlipoproteinaemia 	`,`	null	`],
	[`	E78.2	`,`	Mixed hyperlipidaemia Broad- or floating-betalipoproteinaemia Fredrickson hyperlipoproteinaemia, type IIb or III Hyperbetalipoproteinaemia with prebetalipoproteinaemia Hypercholesterolaemia with endogenous hyperglyceridaemia Hyperlipidaemia, group C Tubero-eruptive xanthoma Xanthoma tuberosum Excl.: cerebrotendinous cholesterosis [van Bogaert-Scherer-Epstein] (E75.5) 	`,`	null	`],
	[`	E78.3	`,`	Hyperchylomicronaemia Fredrickson hyperlipoproteinaemia, type I or V Hyperlipidaemia, group D Mixed hyperglyceridaemia 	`,`	null	`],
	[`	E78.4	`,`	Other hyperlipidaemia Familial combined hyperlipidaemia 	`,`	null	`],
	[`	E78.5	`,`	Hyperlipidaemia, unspecified 	`,`	null	`],
	[`	E78.6	`,`	Lipoprotein deficiency Abetalipoproteinaemia High-density lipoprotein deficiency Hypoalphalipoproteinaemia Hypobetalipoproteinaemia (familial) Lecithin cholesterol acyltransferase deficiency Tangier disease 	`,`	null	`],
	[`	E78.8	`,`	Other disorders of lipoprotein metabolism 	`,`	null	`],
	[`	E78.9	`,`	Disorder of lipoprotein metabolism, unspecified 	`,`	null	`],
	[`	E79	`,`	Disorders of purine and pyrimidine metabolism Excl.: calculus of kidney (N20.0) combined immunodeficiency disorders (D81.-) gout (M10.-) orotaciduric anaemia (D53.0) xeroderma pigmentosum (Q82.1) 	`,`	null	`],
	[`	E79.0	`,`	Hyperuricaemia without signs of inflammatory arthritis and tophaceous disease Asymptomatic hyperuricaemia 	`,`	null	`],
	[`	E79.1	`,`	Lesch-Nyhan syndrome 	`,`	null	`],
	[`	E79.8	`,`	Other disorders of purine and pyrimidine metabolism Hereditary xanthinuria 	`,`	null	`],
	[`	E79.9	`,`	Disorder of purine and pyrimidine metabolism, unspecified 	`,`	null	`],
	[`	E80	`,`	Disorders of porphyrin and bilirubin metabolism Incl.: defects of catalase and peroxidase 	`,`	null	`],
	[`	E80.0	`,`	Hereditary erythropoietic porphyria Congenital erythropoietic porphyria Erythropoietic protoporphyria 	`,`	null	`],
	[`	E80.1	`,`	Porphyria cutanea tarda 	`,`	null	`],
	[`	E80.2	`,`	Other porphyria Hereditary coproporphyria Porphyria: NOS acute intermittent (hepatic) Use additional external cause code (Chapter XX), if desired, to identify cause. 	`,`	null	`],
	[`	E80.3	`,`	Defects of catalase and peroxidase Acatalasia [Takahara] 	`,`	null	`],
	[`	E80.4	`,`	Gilbert syndrome 	`,`	null	`],
	[`	E80.5	`,`	Crigler-Najjar syndrome 	`,`	null	`],
	[`	E80.6	`,`	Other disorders of bilirubin metabolism Dubin-Johnson syndrome Rotor syndrome 	`,`	null	`],
	[`	E80.7	`,`	Disorder of bilirubin metabolism, unspecified 	`,`	null	`],
	[`	E83	`,`	Disorders of mineral metabolism Excl.: dietary mineral deficiency (E58-E61) parathyroid disorders (E20-E21) vitamin D deficiency (E55.-) 	`,`	null	`],
	[`	E83.0	`,`	Disorders of copper metabolism Menkes (kinky hair)(steely hair) disease Wilson disease 	`,`	null	`],
	[`	E83.1	`,`	Disorders of iron metabolism Haemochromatosis Excl.: anaemia: iron deficiency (D50.-) sideroblastic (D64.0-D64.3) 	`,`	null	`],
	[`	E83.2	`,`	Disorders of zinc metabolism Acrodermatitis enteropathica 	`,`	null	`],
	[`	E83.3	`,`	Disorders of phosphorus metabolism and phosphatases Acid phosphatase deficiency Familial hypophosphataemia Hypophosphatasia Vitamin-D-resistant: osteomalacia rickets Excl.: adult osteomalacia (M83.-) osteoporosis (M80-M81) 	`,`	null	`],
	[`	E83.4	`,`	Disorders of magnesium metabolism Hypermagnesaemia Hypomagnesaemia 	`,`	null	`],
	[`	E83.5	`,`	Disorders of calcium metabolism Familial hypocalciuric hypercalcaemia Idiopathic hypercalciuria Excl.: chondrocalcinosis (M11.1-M11.2) hyperparathyroidism (E21.0-E21.3) 	`,`	null	`],
	[`	E83.8	`,`	Other disorders of mineral metabolism 	`,`	null	`],
	[`	E83.9	`,`	Disorder of mineral metabolism, unspecified 	`,`	null	`],
	[`	E84	`,`	Cystic fibrosis Incl.: mucoviscidosis 	`,`	null	`],
	[`	E84.0	`,`	Cystic fibrosis with pulmonary manifestations 	`,`	null	`],
	[`	E84.1	`,`	Cystic fibrosis with intestinal manifestations Distal intestinal obstruction syndrome Meconium ileus in cystic fibrosis (P75*) Excl.: meconium obstruction (ileus) in cases where cystic fibrosis is known not to be present (P76.0) 	`,`	null	`],
	[`	E84.8	`,`	Cystic fibrosis with other manifestations 	`,`	null	`],
	[`	E84.9	`,`	Cystic fibrosis, unspecified 	`,`	null	`],
	[`	E85	`,`	Amyloidosis Excl.: Alzheimer disease (G30.-) 	`,`	null	`],
	[`	E85.0	`,`	Non-neuropathic heredofamilial amyloidosis Familial Mediterranean fever Hereditary amyloid nephropathy 	`,`	null	`],
	[`	E85.1	`,`	Neuropathic heredofamilial amyloidosis Amyloid polyneuropathy (Portuguese) 	`,`	null	`],
	[`	E85.2	`,`	Heredofamilial amyloidosis, unspecified 	`,`	null	`],
	[`	E85.3	`,`	Secondary systemic amyloidosis Haemodialysis-associated amyloidosis 	`,`	null	`],
	[`	E85.4	`,`	Organ-limited amyloidosis Localized amyloidosis 	`,`	null	`],
	[`	E85.8	`,`	Other amyloidosis 	`,`	null	`],
	[`	E85.9	`,`	Amyloidosis, unspecified 	`,`	null	`],
	[`	E86	`,`	Volume depletion Incl.: Dehydration Depletion of volume of plasma or extracellular fluid Hypovolaemia Excl.: dehydration of newborn (P74.1) hypovolaemic shock: NOS (R57.1) postoperative (T81.1) traumatic (T79.4) 	`,`	null	`],
	[`	E87	`,`	Other disorders of fluid, electrolyte and acid-base balance 	`,`	null	`],
	[`	E87.0	`,`	Hyperosmolality and hypernatraemia Sodium [Na] excess Sodium [Na] overload 	`,`	null	`],
	[`	E87.1	`,`	Hypo-osmolality and hyponatraemia Sodium [Na] deficiency Excl.: Syndrome of inappropriate secretion of antidiuretic hormone (E22.2) 	`,`	null	`],
	[`	E87.2	`,`	Acidosis Acidosis: NOS lactic metabolic respiratory Excl.: diabetic acidosis (E10-E14 with common fourth character .1) 	`,`	null	`],
	[`	E87.3	`,`	Alkalosis Alkalosis: NOS metabolic respiratory 	`,`	null	`],
	[`	E87.4	`,`	Mixed disorder of acid-base balance 	`,`	null	`],
	[`	E87.5	`,`	Hyperkalaemia Potassium [K] excess Potassium [K] overload 	`,`	null	`],
	[`	E87.6	`,`	Hypokalaemia Potassium [K] deficiency 	`,`	null	`],
	[`	E87.7	`,`	Fluid overload Excl.: oedema (R60.-) 	`,`	null	`],
	[`	E87.8	`,`	Other disorders of electrolyte and fluid balance, not elsewhere classified Electrolyte imbalance NOS Hyperchloraemia Hypochloraemia 	`,`	null	`],
	[`	E88	`,`	Other metabolic disorders Use additional external cause code (Chapter XX), if desired, to identify drug, if drug-induced. Excl.: histiocytosis X (chronic) (C96.6) 	`,`	null	`],
	[`	E88.0	`,`	Disorders of plasma-protein metabolism, not elsewhere classified Alpha-1-antitrypsin deficiency Bisalbuminaemia Excl.: disorder of lipoprotein metabolism (E78.-) monoclonal gammopathy of undetermined significance (MGUS) (D47.2) polyclonal hypergammaglobulinaemia (D89.0) Waldenstrom macroglobulinaemia (C88.0) 	`,`	null	`],
	[`	E88.1	`,`	Lipodystrophy, not elsewhere classified Lipodystrophy NOS Excl.: Whipple disease (K90.8) 	`,`	null	`],
	[`	E88.2	`,`	Lipomatosis, not elsewhere classified Lipomatosis: NOS dolorosa [Dercum] 	`,`	null	`],
	[`	E88.3	`,`	Tumour lysis syndrome Tumour lysis (following antineoplastic drug therapy)(spontaneous) 	`,`	null	`],
	[`	E88.8	`,`	Other specified metabolic disorders Launois-Bensaude adenolipomatosis Trimethylaminuria 	`,`	null	`],
	[`	E88.9	`,`	Metabolic disorder, unspecified 	`,`	null	`],
	[`	E89	`,`	Postprocedural endocrine and metabolic disorders, not elsewhere classified 	`,`	null	`],
	[`	E89.0	`,`	Postprocedural hypothyroidism Postirradiation hypothyroidism Postsurgical hypothyroidism 	`,`	null	`],
	[`	E89.1	`,`	Postprocedural hypoinsulinaemia Postpancreatectomy hyperglycaemia Postsurgical hypoinsulinaemia 	`,`	null	`],
	[`	E89.2	`,`	Postprocedural hypoparathyroidism Parathyroprival tetany 	`,`	null	`],
	[`	E89.3	`,`	Postprocedural hypopituitarism Postirradiation hypopituitarism 	`,`	null	`],
	[`	E89.4	`,`	Postprocedural ovarian failure 	`,`	null	`],
	[`	E89.5	`,`	Postprocedural testicular hypofunction 	`,`	null	`],
	[`	E89.6	`,`	Postprocedural adrenocortical(-medullary) hypofunction 	`,`	null	`],
	[`	E89.8	`,`	Other postprocedural endocrine and metabolic disorders 	`,`	null	`],
	[`	E89.9	`,`	Postprocedural endocrine and metabolic disorder, unspecified 	`,`	null	`],
	[`	E90*	`,`	Nutritional and metabolic disorders in diseases classified elsewhere 	`,`	null	`],
							
							
							
];								
				
							
							
				
	
let CodeRangeE ={
	f0:function(val1=(-1),val2=(0)){
		let Range1 = ECodes.slice(val1,val2);
		Range1.reverse();
		document.documentElement.innerHTML += `<br>Showing E Codes ${Range1.length} items(s)`;

		for(value2 in Range1){
			    document.documentElement.style.cssText += "background-color:tan;";
				document.getElementById('ecodesTR').outerHTML += `<tr><td style="background-color:navy;color:white;width:5%;padding:40px;border:2px solid white;font-weight:900;font-size:40px;text-align:center;">${Range1[value2][0]}</td><td style="background-color:black;color:white;width:90%;padding:20px;border:2px solid white;font-size:30px;">${Range1[value2][1]}</td><td style="background-color:navy;color:white;width:5%;padding:20px;border:2px solid white;font-weight:900;font-size:40px;text-align:center;">${Range1[value2][2]}</td></tr>`;			
		}

	},

};

	






	






