								
								
let GCodes = [								
	[`		`,`		`,`		`],
	[`	G00	`,`	Bacterial meningitis, not elsewhere classified Incl.: arachnoiditis leptomeningitis meningitis pachymeningitis bacterial Excl.: bacterial: meningoencephalitis (G04.2) meningomyelitis (G04.2) 	`,`	null	`],
	[`	G00.0	`,`	Haemophilus meningitis Meningitis due to Haemophilus influenzae 	`,`	null	`],
	[`	G00.1	`,`	Pneumococcal meningitis 	`,`	null	`],
	[`	G00.2	`,`	Streptococcal meningitis 	`,`	null	`],
	[`	G00.3	`,`	Staphylococcal meningitis 	`,`	null	`],
	[`	G00.8	`,`	Other bacterial meningitis Meningitis due to: Escherichia coli Friedlander bacillus Klebsiella 	`,`	null	`],
	[`	G00.9	`,`	Bacterial meningitis, unspecified Meningitis: purulent NOS pyogenic NOS suppurative NOS 	`,`	null	`],
	[`	G01*	`,`	Meningitis in bacterial diseases classified elsewhere Incl.: Meningitis (in): anthrax (A22.8) gonococcal (A54.8) leptospirosis (A27.-) listerial (A32.1) Lyme disease (A69.2) meningococcal (A39.0) neurosyphilis (A52.1) salmonella infection (A02.2) syphilis: congenital (A50.4) secondary (A51.4) tuberculous (A17.0) typhoid fever (A01.0) Excl.: meningoencephalitis and meningomyelitis in bacterial diseases classified elsewhere (G05.0*) 	`,`	null	`],
	[`	G02*	`,`	Meningitis in other infectious and parasitic diseases classified elsewhere Excl.: meningoencephalitis and meningomyelitis in other infectious and parasitic diseases classified elsewhere (G05.1-G05.2*) 	`,`	null	`],
	[`	G02.0*	`,`	Meningitis in viral diseases classified elsewhere Meningitis (due to): adenoviral (A87.1) enteroviral (A87.0) herpesviral [herpes simplex] (B00.3) infectious mononucleosis (B27.-) measles (B05.1) mumps (B26.1) rubella (B06.0) varicella [chickenpox] (B01.0) zoster (B02.1) 	`,`	null	`],
	[`	G02.1*	`,`	Meningitis in mycoses Meningitis (in): candidal (B37.5) coccidioidomycosis (B38.4) cryptococcal (B45.1) 	`,`	null	`],
	[`	G02.8*	`,`	Meningitis in other specified infectious and parasitic diseases classified elsewhere Meningitis due to: African trypanosomiasis (B56.-) Chagas disease (chronic) (B57.4) 	`,`	null	`],
	[`	G03	`,`	Meningitis due to other and unspecified causes Incl.: arachnoiditis leptomeningitis meningitis pachymeningitis due to other and unspecified causes Excl.: meningoencephalitis (G04.-) meningomyelitis (G04.-) 	`,`	null	`],
	[`	G03.0	`,`	Nonpyogenic meningitis Nonbacterial meningitis 	`,`	null	`],
	[`	G03.1	`,`	Chronic meningitis 	`,`	null	`],
	[`	G03.2	`,`	Benign recurrent meningitis [Mollaret] 	`,`	null	`],
	[`	G03.8	`,`	Meningitis due to other specified causes 	`,`	null	`],
	[`	G03.9	`,`	Meningitis, unspecified Arachnoiditis (spinal) NOS 	`,`	null	`],
	[`	G04	`,`	Encephalitis, myelitis and encephalomyelitis Incl.: acute ascending myelitis meningoencephalitis meningomyelitis Excl.: benign myalgic encephalomyelitis (G93.3) encephalopathy: NOS (G93.4) alcoholic (G31.2) toxic (G92) multiple sclerosis (G35) myelitis: acute transverse (G37.3) subacute necrotizing (G37.4) 	`,`	null	`],
	[`	G04.0	`,`	Acute disseminated encephalitis Encephalitis Encephalomyelitis postimmunization Use additional external cause code (Chapter XX), if desired, to identify vaccine. 	`,`	null	`],
	[`	G04.1	`,`	Tropical spastic paraplegia 	`,`	null	`],
	[`	G04.2	`,`	Bacterial meningoencephalitis and meningomyelitis, not elsewhere classified 	`,`	null	`],
	[`	G04.8	`,`	Other encephalitis, myelitis and encephalomyelitis Postinfectious encephalitis and encephalomyelitis NOS Use additional code, if desired, to identify any associated epileptic seizures (G40.-). 	`,`	null	`],
	[`	G04.9	`,`	Encephalitis, myelitis and encephalomyelitis, unspecified Ventriculitis (cerebral) NOS 	`,`	null	`],
	[`	G05*	`,`	Encephalitis, myelitis and encephalomyelitis in diseases classified elsewhere Incl.: meningoencephalitis and meningomyelitis in diseases classified elsewhere 	`,`	null	`],
	[`	G05.0*	`,`	Encephalitis, myelitis and encephalomyelitis in bacterial diseases classified elsewhere Encephalitis, myelitis or encephalomyelitis (in): listerial (A32.1) meningococcal (A39.8) syphilis: congenital (A50.4) late (A52.1) tuberculous (A17.8) 	`,`	null	`],
	[`	G05.1*	`,`	Encephalitis, myelitis and encephalomyelitis in viral diseases classified elsewhere Encephalitis, myelitis or encephalomyelitis (in): adenoviral (A85.1) cytomegaloviral (B25.8) enteroviral (A85.0) herpesviral [herpes simplex] (B00.4) influenza (J09, J10.8, J11.8) measles (B05.0) mumps (B26.2) postchickenpox (B01.1) rubella (B06.0) zoster (B02.0) 	`,`	null	`],
	[`	G05.2*	`,`	Encephalitis, myelitis and encephalomyelitis in other infectious and parasitic diseases classified elsewhere Encephalitis, myelitis or encephalomyelitis in: African trypanosomiasis (B56.-) Chagas disease (chronic) (B57.4) naegleriasis (B60.2) toxoplasmosis (B58.2) Eosinophilic meningoencephalitis (B83.2) 	`,`	null	`],
	[`	G05.8*	`,`	Encephalitis, myelitis and encephalomyelitis in other diseases classified elsewhere Encephalitis in systemic lupus erythematosus (M32.1) 	`,`	null	`],
	[`	G06	`,`	Intracranial and intraspinal abscess and granuloma Use additional code (B95-B98), if desired, to identify infectious agent. 	`,`	null	`],
	[`	G06.0	`,`	Intracranial abscess and granuloma Abscess (embolic)(of): brain [any part] cerebellar cerebral otogenic Intracranial abscess or granuloma: epidural extradural subdural 	`,`	null	`],
	[`	G06.1	`,`	Intraspinal abscess and granuloma Abscess (embolic) of spinal cord [any part] Intraspinal abscess or granuloma: epidural extradural subdural 	`,`	null	`],
	[`	G06.2	`,`	Extradural and subdural abscess, unspecified 	`,`	null	`],
	[`	G07*	`,`	Intracranial and intraspinal abscess and granuloma in diseases classified elsewhere Incl.: Abscess of brain: amoebic (A06.6) gonococcal (A54.8) tuberculous (A17.8) Schistosomiasis granuloma of brain (B65.-) Tuberculoma of: brain (A17.8) meninges (A17.1) 	`,`	null	`],
	[`	G08	`,`	Intracranial and intraspinal phlebitis and thrombophlebitis Incl.: Septic: embolism endophlebitis phlebitis thrombophlebitis thrombosis of intracranial or intraspinal venous sinuses and veins Excl.: intracranial phlebitis and thrombophlebitis: complicating: abortion or ectopic or molar pregnancy (O00-O07, O08.7) pregnancy, childbirth and the puerperium (O22.5, O87.3) of nonpyogenic origin (I67.6) nonpyogenic intraspinal phlebitis and thrombophlebitis (G95.1) 	`,`	null	`],
	[`	G09	`,`	Sequelae of inflammatory diseases of central nervous system Note: Category G09 is to be used to indicate conditions whose primary classification is to G00-G08 (i.e. excluding those marked with an asterisk (*)) as the cause of sequelae, themselves classifiable elsewhere. The "sequelae" include conditions specified as such or as late effects, or those present one year or more after onset of the causal condition. For use of this category reference should be made to the relevant morbidity and mortality coding rules and guidelines in Volume 2. Not to be used for chronic inflammatory diseases of the central nervous system. Code these to current inflammatory diseases of the central nervous system. 	`,`	null	`],
	[`	G10	`,`	Huntington disease Incl.: Huntington chorea 	`,`	null	`],
	[`	G11	`,`	Hereditary ataxia Excl.: cerebral palsy (G80.-) hereditary and idiopathic neuropathy (G60.-) metabolic disorders (E70-E90) 	`,`	null	`],
	[`	G11.0	`,`	Congenital nonprogressive ataxia 	`,`	null	`],
	[`	G11.1	`,`	Early-onset cerebellar ataxia Note: Onset usually before the age of 20 Early-onset cerebellar ataxia with: essential tremor myoclonus [Hunt ataxia] retained tendon reflexes Friedreich ataxia (autosomal recessive) X-linked recessive spinocerebellar ataxia 	`,`	null	`],
	[`	G11.2	`,`	Late-onset cerebellar ataxia Note: Onset usually after the age of 20 	`,`	null	`],
	[`	G11.3	`,`	Cerebellar ataxia with defective DNA repair Ataxia telangiectasia [Louis-Bar] Excl.: Cockayne syndrome (Q87.1) xeroderma pigmentosum (Q82.1) 	`,`	null	`],
	[`	G11.4	`,`	Hereditary spastic paraplegia 	`,`	null	`],
	[`	G11.8	`,`	Other hereditary ataxias 	`,`	null	`],
	[`	G11.9	`,`	Hereditary ataxia, unspecified Hereditary cerebellar: ataxia NOS degeneration disease syndrome 	`,`	null	`],
	[`	G12	`,`	Spinal muscular atrophy and related syndromes 	`,`	null	`],
	[`	G12.0	`,`	Infantile spinal muscular atrophy, type I [Werdnig-Hoffman] 	`,`	null	`],
	[`	G12.1	`,`	Other inherited spinal muscular atrophy Progressive bulbar palsy of childhood [Fazio-Londe] Spinal muscular atrophy: adult form childhood form, type II distal juvenile form, type III [Kugelberg-Welander] scapuloperoneal form 	`,`	null	`],
	[`	G12.2	`,`	Motor neuron disease Familial motor neuron disease Lateral sclerosis: amyotrophic primary Progressive: bulbar palsy spinal muscular atrophy 	`,`	null	`],
	[`	G12.8	`,`	Other spinal muscular atrophies and related syndromes 	`,`	null	`],
	[`	G12.9	`,`	Spinal muscular atrophy, unspecified 	`,`	null	`],
	[`	G13*	`,`	Systemic atrophies primarily affecting central nervous system in diseases classified elsewhere 	`,`	null	`],
	[`	G13.0*	`,`	Paraneoplastic neuromyopathy and neuropathy Carcinomatous neuromyopathy (C00-C97) Sensorial paraneoplastic neuropathy [Denny Brown] (C00-D48) 	`,`	null	`],
	[`	G13.1*	`,`	Other systemic atrophy primarily affecting central nervous system in neoplastic disease Paraneoplastic limbic encephalopathy (C00-D48) 	`,`	null	`],
	[`	G13.2*	`,`	Systemic atrophy primarily affecting central nervous system in myxoedema (E00.1, E03.-) 	`,`	null	`],
	[`	G13.8*	`,`	Systemic atrophy primarily affecting central nervous system in other diseases classified elsewhere 	`,`	null	`],
	[`	G14	`,`	Postpolio syndrome Incl.: Postpolio myelitic syndrome Excl.: sequelae of poliomyelitis (B91) 	`,`	null	`],
	[`	G20	`,`	Parkinson disease Incl.: Hemiparkinsonism Paralysis agitans Parkinsonism or Parkinson disease: NOS idiopathic primary 	`,`	null	`],
	[`	G21	`,`	Secondary parkinsonism 	`,`	null	`],
	[`	G21.0	`,`	Malignant neuroleptic syndrome Use additional external cause code (Chapter XX), if desired, to identify drug. 	`,`	null	`],
	[`	G21.1	`,`	Other drug-induced secondary parkinsonism Use additional external cause code (Chapter XX), if desired, to identify drug. 	`,`	null	`],
	[`	G21.2	`,`	Secondary parkinsonism due to other external agents Use additional external cause code (Chapter XX), if desired, to identify external agent. 	`,`	null	`],
	[`	G21.3	`,`	Postencephalitic parkinsonism 	`,`	null	`],
	[`	G21.4	`,`	Vascular parkinsonism 	`,`	null	`],
	[`	G21.8	`,`	Other secondary parkinsonism 	`,`	null	`],
	[`	G21.9	`,`	Secondary parkinsonism, unspecified 	`,`	null	`],
	[`	G22*	`,`	Parkinsonism in diseases classified elsewhere Incl.: Syphilitic parkinsonism (A52.1) 	`,`	null	`],
	[`	G23	`,`	Other degenerative diseases of basal ganglia Excl.: multi-system degeneration (G90.3) 	`,`	null	`],
	[`	G23.0	`,`	Hallervorden-Spatz disease Pigmentary pallidal degeneration 	`,`	null	`],
	[`	G23.1	`,`	Progressive supranuclear ophthalmoplegia [Steele-Richardson-Olszewski] Progressive supranuclear palsy 	`,`	null	`],
	[`	G23.2	`,`	Striatonigral degeneration 	`,`	null	`],
	[`	G23.8	`,`	Other specified degenerative diseases of basal ganglia Calcification of basal ganglia 	`,`	null	`],
	[`	G23.9	`,`	Degenerative disease of basal ganglia, unspecified 	`,`	null	`],
	[`	G24	`,`	Dystonia Incl.: dyskinesia Excl.: athetoid cerebral palsy (G80.3) 	`,`	null	`],
	[`	G24.0	`,`	Drug-induced dystonia Use additional external cause code (Chapter XX), if desired, to identify drug. 	`,`	null	`],
	[`	G24.1	`,`	Idiopathic familial dystonia Idiopathic dystonia NOS 	`,`	null	`],
	[`	G24.2	`,`	Idiopathic nonfamilial dystonia 	`,`	null	`],
	[`	G24.3	`,`	Spasmodic torticollis Excl.: torticollis NOS (M43.6) 	`,`	null	`],
	[`	G24.4	`,`	Idiopathic orofacial dystonia Orofacial dyskinesia 	`,`	null	`],
	[`	G24.5	`,`	Blepharospasm 	`,`	null	`],
	[`	G24.8	`,`	Other dystonia 	`,`	null	`],
	[`	G24.9	`,`	Dystonia, unspecified Dyskinesia NOS 	`,`	null	`],
	[`	G25	`,`	Other extrapyramidal and movement disorders 	`,`	null	`],
	[`	G25.0	`,`	Essential tremor Familial tremor Excl.: tremor NOS (R25.1) 	`,`	null	`],
	[`	G25.1	`,`	Drug-induced tremor Use additional external cause code (Chapter XX), if desired, to identify drug. 	`,`	null	`],
	[`	G25.2	`,`	Other specified forms of tremor Intention tremor 	`,`	null	`],
	[`	G25.3	`,`	Myoclonus Drug-induced myoclonus Use additional external cause code (Chapter XX), if desired, to identify drug, if drug-induced. Excl.: facial myokymia (G51.4) myoclonic epilepsy (G40.-) 	`,`	null	`],
	[`	G25.4	`,`	Drug-induced chorea Use additional external cause code (Chapter XX), if desired, to identify drug. 	`,`	null	`],
	[`	G25.5	`,`	Other chorea Chorea NOS Excl.: chorea NOS with heart involvement (I02.0) Huntington chorea (G10) rheumatic chorea (I02.-) Sydenham chorea (I02.-) 	`,`	null	`],
	[`	G25.6	`,`	Drug-induced tics and other tics of organic origin Use additional external cause code (Chapter XX), if desired, to identify drug, if drug-induced. Excl.: de la Tourette syndrome (F95.2) tic NOS (F95.9) 	`,`	null	`],
	[`	G25.8	`,`	Other specified extrapyramidal and movement disorders Akathisia (drug-induced) (treatment-induced) Restless legs syndrome Stiff-man syndrome Use additional external cause code (Chapter XX), if desired, to identify drug, if drug-induced 	`,`	null	`],
	[`	G25.9	`,`	Extrapyramidal and movement disorder, unspecified 	`,`	null	`],
	[`	G26*	`,`	Extrapyramidal and movement disorders in diseases classified elsewhere 	`,`	null	`],
	[`	G30	`,`	Alzheimer disease Incl.: senile and presenile forms Excl.: senile: degeneration of brain NEC (G31.1) dementia NOS (F03) senility NOS (R54) 	`,`	null	`],
	[`	G30.0	`,`	Alzheimer disease with early onset Note: Onset usually before the age of 65 	`,`	null	`],
	[`	G30.1	`,`	Alzheimer disease with late onset Note: Onset usually after the age of 65 	`,`	null	`],
	[`	G30.8	`,`	Other Alzheimer disease 	`,`	null	`],
	[`	G30.9	`,`	Alzheimer disease, unspecified 	`,`	null	`],
	[`	G31	`,`	Other degenerative diseases of nervous system, not elsewhere classified Excl.: Reye syndrome (G93.7) 	`,`	null	`],
	[`	G31.0	`,`	Circumscribed brain atrophy Frontotemporal dementia (FTD) Pick disease Progressive isolated aphasia 	`,`	null	`],
	[`	G31.1	`,`	Senile degeneration of brain, not elsewhere classified Excl.: Alzheimer disease (G30.-) senility NOS (R54) 	`,`	null	`],
	[`	G31.2	`,`	Degeneration of nervous system due to alcohol Alcoholic: cerebellar: ataxia degeneration cerebral degeneration encephalopathy Dysfunction of autonomic nervous system due to alcohol 	`,`	null	`],
	[`	G31.8	`,`	Other specified degenerative diseases of nervous system Grey-matter degeneration [Alpers] Lewy body(ies)(dementia)(disease) (F02.8*) Subacute necrotizing encephalopathy [Leigh] 	`,`	null	`],
	[`	G31.9	`,`	Degenerative disease of nervous system, unspecified 	`,`	null	`],
	[`	G32*	`,`	Other degenerative disorders of nervous system in diseases classified elsewhere 	`,`	null	`],
	[`	G32.0*	`,`	Subacute combined degeneration of spinal cord in diseases classified elsewhere Excl.: Subacute combined degeneration of spinal cord in vitamin B12 deficiency (E53.8) 	`,`	null	`],
	[`	G32.8*	`,`	Other specified degenerative disorders of nervous system in diseases classified elsewhere 	`,`	null	`],
	[`	G35	`,`	Multiple sclerosis Incl.: Multiple sclerosis (of): NOS brain stem cord disseminated generalized 	`,`	null	`],
	[`	G36	`,`	Other acute disseminated demyelination Excl.: postinfectious encephalitis and encephalomyelitis NOS (G04.8) 	`,`	null	`],
	[`	G36.0	`,`	Neuromyelitis optica [Devic] Demyelination in optic neuritis Excl.: optic neuritis NOS (H46) 	`,`	null	`],
	[`	G36.1	`,`	Acute and subacute haemorrhagic leukoencephalitis [Hurst] 	`,`	null	`],
	[`	G36.8	`,`	Other specified acute disseminated demyelination 	`,`	null	`],
	[`	G36.9	`,`	Acute disseminated demyelination, unspecified 	`,`	null	`],
	[`	G37	`,`	Other demyelinating diseases of central nervous system 	`,`	null	`],
	[`	G37.0	`,`	Diffuse sclerosis Periaxial encephalitis Schilder disease Excl.: adrenoleukodystrophy [Addison-Schilder] (E71.3) 	`,`	null	`],
	[`	G37.1	`,`	Central demyelination of corpus callosum 	`,`	null	`],
	[`	G37.2	`,`	Central pontine myelinolysis 	`,`	null	`],
	[`	G37.3	`,`	Acute transverse myelitis in demyelinating disease of central nervous system Acute transverse myelitis NOS Excl.: multiple sclerosis (G35) neuromyelitis optica [Devic] (G36.0) 	`,`	null	`],
	[`	G37.4	`,`	Subacute necrotizing myelitis 	`,`	null	`],
	[`	G37.5	`,`	Concentric sclerosis [Balo] 	`,`	null	`],
	[`	G37.8	`,`	Other specified demyelinating diseases of central nervous system 	`,`	null	`],
	[`	G37.9	`,`	Demyelinating disease of central nervous system, unspecified 	`,`	null	`],
	[`	G40	`,`	Epilepsy Excl.: Landau-Kleffner syndrome (F80.3) seizure (convulsive) NOS (R56.8) status epilepticus (G41.-) Todd paralysis (G83.8) 	`,`	null	`],
	[`	G40.0	`,`	Localization-related (focal)(partial) idiopathic epilepsy and epileptic syndromes with seizures of localized onset Benign childhood epilepsy with centrotemporal EEG spikes Childhood epilepsy with occipital EEG paroxysms 	`,`	null	`],
	[`	G40.1	`,`	Localization-related (focal)(partial) symptomatic epilepsy and epileptic syndromes with simple partial seizures Attacks without alteration of consciousness Simple partial seizures developing into secondarily generalized seizures 	`,`	null	`],
	[`	G40.2	`,`	Localization-related (focal)(partial) symptomatic epilepsy and epileptic syndromes with complex partial seizures Attacks with alteration of consciousness, often with automatisms Complex partial seizures developing into secondarily generalized seizures 	`,`	null	`],
	[`	G40.3	`,`	Generalized idiopathic epilepsy and epileptic syndromes Benign: myoclonic epilepsy in infancy neonatal convulsions (familial) Childhood absence epilepsy [pyknolepsy] Epilepsy with grand mal seizures on awakening Juvenile: absence epilepsy myoclonic epilepsy [impulsive petit mal] Nonspecific epileptic seizures: atonic clonic myoclonic tonic tonic-clonic 	`,`	null	`],
	[`	G40.4	`,`	Other generalized epilepsy and epileptic syndromes Epilepsy with: myoclonic absences myoclonic-astatic seizures Infantile spasms Lennox-Gastaut syndrome Salaam attacks Symptomatic early myoclonic encephalopathy West syndrome 	`,`	null	`],
	[`	G40.5	`,`	Special epileptic syndromes Epilepsia partialis continua [Kozhevnikof] Epileptic seizures related to: alcohol drugs hormonal changes sleep deprivation stress Use additional external cause code (Chapter XX), if desired, to identify drug, if drug-induced. 	`,`	null	`],
	[`	G40.6	`,`	Grand mal seizures, unspecified (with or without petit mal) 	`,`	null	`],
	[`	G40.7	`,`	Petit mal, unspecified, without grand mal seizures 	`,`	null	`],
	[`	G40.8	`,`	Other epilepsy Epilepsies and epileptic syndromes undetermined as to whether they are focal or generalized 	`,`	null	`],
	[`	G40.9	`,`	Epilepsy, unspecified Epileptic: convulsions NOS fits NOS seizures NOS 	`,`	null	`],
	[`	G41	`,`	Status epilepticus 	`,`	null	`],
	[`	G41.0	`,`	Grand mal status epilepticus Tonic-clonic status epilepticus Excl.: epilepsia partialis continua [Kozhevnikof] (G40.5) 	`,`	null	`],
	[`	G41.1	`,`	Petit mal status epilepticus Epileptic absence status 	`,`	null	`],
	[`	G41.2	`,`	Complex partial status epilepticus 	`,`	null	`],
	[`	G41.8	`,`	Other status epilepticus 	`,`	null	`],
	[`	G41.9	`,`	Status epilepticus, unspecified 	`,`	null	`],
	[`	G43	`,`	Migraine Use additional external cause code (Chapter XX), if desired, to identify drug, if drug-induced. Excl.: headache NOS (R51) 	`,`	null	`],
	[`	G43.0	`,`	Migraine without aura [common migraine] 	`,`	null	`],
	[`	G43.1	`,`	Migraine with aura [classical migraine] Migraine: aura without headache basilar equivalents familial hemiplegic with: acute-onset aura prolonged aura typical aura 	`,`	null	`],
	[`	G43.2	`,`	Status migrainosus 	`,`	null	`],
	[`	G43.3	`,`	Complicated migraine 	`,`	null	`],
	[`	G43.8	`,`	Other migraine Ophthalmoplegic migraine Retinal migraine 	`,`	null	`],
	[`	G43.9	`,`	Migraine, unspecified 	`,`	null	`],
	[`	G44	`,`	Other headache syndromes Excl.: atypical facial pain (G50.1) headache NOS (R51) trigeminal neuralgia (G50.0) 	`,`	null	`],
	[`	G44.0	`,`	Cluster headache syndrome Chronic paroxysmal hemicrania Cluster headache: chronic episodic 	`,`	null	`],
	[`	G44.1	`,`	Vascular headache, not elsewhere classified Vascular headache NOS 	`,`	null	`],
	[`	G44.2	`,`	Tension-type headache Chronic tension-type headache Episodic tension headache Tension headache NOS 	`,`	null	`],
	[`	G44.3	`,`	Chronic post-traumatic headache 	`,`	null	`],
	[`	G44.4	`,`	Drug-induced headache, not elsewhere classified Use additional external cause code (Chapter XX), if desired, to identify drug. 	`,`	null	`],
	[`	G44.8	`,`	Other specified headache syndromes 	`,`	null	`],
	[`	G45	`,`	Transient cerebral ischaemic attacks and related syndromes Excl.: neonatal cerebral ischaemia (P91.0) 	`,`	null	`],
	[`	G45.0	`,`	Vertebro-basilar artery syndrome 	`,`	null	`],
	[`	G45.1	`,`	Carotid artery syndrome (hemispheric) 	`,`	null	`],
	[`	G45.2	`,`	Multiple and bilateral precerebral artery syndromes 	`,`	null	`],
	[`	G45.3	`,`	Amaurosis fugax 	`,`	null	`],
	[`	G45.4	`,`	Transient global amnesia Excl.: amnesia NOS (R41.3) 	`,`	null	`],
	[`	G45.8	`,`	Other transient cerebral ischaemic attacks and related syndromes 	`,`	null	`],
	[`	G45.9	`,`	Transient cerebral ischaemic attack, unspecified Spasm of cerebral artery Transient cerebral ischaemia NOS 	`,`	null	`],
	[`	G46*	`,`	Vascular syndromes of brain in cerebrovascular diseases (I60-I67) 	`,`	null	`],
	[`	G46.0*	`,`	Middle cerebral artery syndrome (I66.0) 	`,`	null	`],
	[`	G46.1*	`,`	Anterior cerebral artery syndrome (I66.1) 	`,`	null	`],
	[`	G46.2*	`,`	Posterior cerebral artery syndrome (I66.2) 	`,`	null	`],
	[`	G46.3*	`,`	Brain stem stroke syndrome (I60-I67) Syndrome: Benedikt Claude Foville Millard-Gubler Wallenberg Weber 	`,`	null	`],
	[`	G46.4*	`,`	Cerebellar stroke syndrome (I60-I67) 	`,`	null	`],
	[`	G46.5*	`,`	Pure motor lacunar syndrome (I60-I67) 	`,`	null	`],
	[`	G46.6*	`,`	Pure sensory lacunar syndrome (I60-I67) 	`,`	null	`],
	[`	G46.7*	`,`	Other lacunar syndromes (I60-I67) 	`,`	null	`],
	[`	G46.8*	`,`	Other vascular syndromes of brain in cerebrovascular diseases (I60-I67) 	`,`	null	`],
	[`	G47	`,`	Sleep disorders Excl.: nightmares (F51.5) nonorganic sleep disorders (F51.-) sleep terrors (F51.4) sleepwalking (F51.3) 	`,`	null	`],
	[`	G47.0	`,`	Disorders of initiating and maintaining sleep [insomnias] 	`,`	null	`],
	[`	G47.1	`,`	Disorders of excessive somnolence [hypersomnias] 	`,`	null	`],
	[`	G47.2	`,`	Disorders of the sleep-wake schedule Delayed sleep phase syndrome Irregular sleep-wake pattern 	`,`	null	`],
	[`	G47.3	`,`	Sleep apnoea Sleep apnoea: central obstructive Excl.: pickwickian syndrome (E66.2) sleep apnoea of newborn (P28.3) 	`,`	null	`],
	[`	G47.4	`,`	Narcolepsy and cataplexy 	`,`	null	`],
	[`	G47.8	`,`	Other sleep disorders Kleine-Levin syndrome 	`,`	null	`],
	[`	G47.9	`,`	Sleep disorder, unspecified 	`,`	null	`],
	[`	G50	`,`	Disorders of trigeminal nerve Incl.: disorders of 5th cranial nerve 	`,`	null	`],
	[`	G50.0	`,`	Trigeminal neuralgia Syndrome of paroxysmal facial pain Tic douloureux 	`,`	null	`],
	[`	G50.1	`,`	Atypical facial pain 	`,`	null	`],
	[`	G50.8	`,`	Other disorders of trigeminal nerve 	`,`	null	`],
	[`	G50.9	`,`	Disorder of trigeminal nerve, unspecified 	`,`	null	`],
	[`	G51	`,`	Facial nerve disorders Incl.: disorders of 7th cranial nerve 	`,`	null	`],
	[`	G51.0	`,`	Bell palsy Facial palsy 	`,`	null	`],
	[`	G51.1	`,`	Geniculate ganglionitis Excl.: postherpetic geniculate ganglionitis (B02.2) 	`,`	null	`],
	[`	G51.2	`,`	Melkersson syndrome Melkersson-Rosenthal syndrome 	`,`	null	`],
	[`	G51.3	`,`	Clonic hemifacial spasm 	`,`	null	`],
	[`	G51.4	`,`	Facial myokymia 	`,`	null	`],
	[`	G51.8	`,`	Other disorders of facial nerve 	`,`	null	`],
	[`	G51.9	`,`	Disorder of facial nerve, unspecified 	`,`	null	`],
	[`	G52	`,`	Disorders of other cranial nerves Excl.: disorders of: acoustic [8th] nerve (H93.3) optic [2nd] nerve (H46, H47.0) paralytic strabismus due to nerve palsy (H49.0-H49.2) 	`,`	null	`],
	[`	G52.0	`,`	Disorders of olfactory nerve Disorder of 1st cranial nerve 	`,`	null	`],
	[`	G52.1	`,`	Disorders of glossopharyngeal nerve Disorder of 9th cranial nerve Glossopharyngeal neuralgia 	`,`	null	`],
	[`	G52.2	`,`	Disorders of vagus nerve Disorder of pneumogastric [10th] nerve 	`,`	null	`],
	[`	G52.3	`,`	Disorders of hypoglossal nerve Disorder of 12th cranial nerve 	`,`	null	`],
	[`	G52.7	`,`	Disorders of multiple cranial nerves Polyneuritis cranialis 	`,`	null	`],
	[`	G52.8	`,`	Disorders of other specified cranial nerves 	`,`	null	`],
	[`	G52.9	`,`	Cranial nerve disorder, unspecified 	`,`	null	`],
	[`	G53*	`,`	Cranial nerve disorders in diseases classified elsewhere 	`,`	null	`],
	[`	G53.0*	`,`	Postzoster neuralgia (B02.2) Postherpetic: geniculate ganglionitis trigeminal neuralgia 	`,`	null	`],
	[`	G53.1*	`,`	Multiple cranial nerve palsies in infectious and parasitic diseases classified elsewhere (A00-B99) 	`,`	null	`],
	[`	G53.2*	`,`	Multiple cranial nerve palsies in sarcoidosis (D86.8) 	`,`	null	`],
	[`	G53.3*	`,`	Multiple cranial nerve palsies in neoplastic disease (C00-D48) 	`,`	null	`],
	[`	G53.8*	`,`	Other cranial nerve disorders in other diseases classified elsewhere 	`,`	null	`],
	[`	G54	`,`	Nerve root and plexus disorders Excl.: current traumatic nerve root and plexus disorders - see nerve injury by body region intervertebral disc disorders (M50-M51) neuralgia or neuritis NOS (M79.2) neuritis or radiculitis: brachial NOS (M54.1) lumbar NOS (M54.1) lumbosacral NOS (M54.1) thoracic NOS (M54.1) radiculitis NOS (M54.1) radiculopathy NOS (M54.1) spondylosis (M47.-) 	`,`	null	`],
	[`	G54.0	`,`	Brachial plexus disorders Thoracic outlet syndrome 	`,`	null	`],
	[`	G54.1	`,`	Lumbosacral plexus disorders 	`,`	null	`],
	[`	G54.2	`,`	Cervical root disorders, not elsewhere classified 	`,`	null	`],
	[`	G54.3	`,`	Thoracic root disorders, not elsewhere classified 	`,`	null	`],
	[`	G54.4	`,`	Lumbosacral root disorders, not elsewhere classified 	`,`	null	`],
	[`	G54.5	`,`	Neuralgic amyotrophy Parsonage-Aldren-Turner syndrome Shoulder-girdle neuritis 	`,`	null	`],
	[`	G54.6	`,`	Phantom limb syndrome with pain 	`,`	null	`],
	[`	G54.7	`,`	Phantom limb syndrome without pain Phantom limb syndrome NOS 	`,`	null	`],
	[`	G54.8	`,`	Other nerve root and plexus disorders 	`,`	null	`],
	[`	G54.9	`,`	Nerve root and plexus disorder, unspecified 	`,`	null	`],
	[`	G55*	`,`	Nerve root and plexus compressions in diseases classified elsewhere 	`,`	null	`],
	[`	G55.0*	`,`	Nerve root and plexus compressions in neoplastic disease (C00-D48) 	`,`	null	`],
	[`	G55.1*	`,`	Nerve root and plexus compressions in intervertebral disc disorders (M50-M51) 	`,`	null	`],
	[`	G55.2*	`,`	Nerve root and plexus compressions in spondylosis (M47.-) 	`,`	null	`],
	[`	G55.3*	`,`	Nerve root and plexus compressions in other dorsopathies (M45-M46, M48.-, M53-M54) 	`,`	null	`],
	[`	G55.8*	`,`	Nerve root and plexus compressions in other diseases classified elsewhere 	`,`	null	`],
	[`	G56	`,`	Mononeuropathies of upper limb Excl.: current traumatic nerve disorder - see nerve injury by body region 	`,`	null	`],
	[`	G56.0	`,`	Carpal tunnel syndrome 	`,`	null	`],
	[`	G56.1	`,`	Other lesions of median nerve 	`,`	null	`],
	[`	G56.2	`,`	Lesion of ulnar nerve Tardy ulnar nerve palsy 	`,`	null	`],
	[`	G56.3	`,`	Lesion of radial nerve 	`,`	null	`],
	[`	G56.4	`,`	Causalgia 	`,`	null	`],
	[`	G56.8	`,`	Other mononeuropathies of upper limb Interdigital neuroma of upper limb 	`,`	null	`],
	[`	G56.9	`,`	Mononeuropathy of upper limb, unspecified 	`,`	null	`],
	[`	G57	`,`	Mononeuropathies of lower limb Excl.: current traumatic nerve disorder - see nerve injury by body region 	`,`	null	`],
	[`	G57.0	`,`	Lesion of sciatic nerve Excl.: sciatica: NOS (M54.3) attributed to intervertebral disc disorder (M51.1) 	`,`	null	`],
	[`	G57.1	`,`	Meralgia paraesthetica Lateral cutaneous nerve of thigh syndrome 	`,`	null	`],
	[`	G57.2	`,`	Lesion of femoral nerve 	`,`	null	`],
	[`	G57.3	`,`	Lesion of lateral popliteal nerve Peroneal nerve palsy 	`,`	null	`],
	[`	G57.4	`,`	Lesion of medial popliteal nerve 	`,`	null	`],
	[`	G57.5	`,`	Tarsal tunnel syndrome 	`,`	null	`],
	[`	G57.6	`,`	Lesion of plantar nerve Morton metatarsalgia 	`,`	null	`],
	[`	G57.8	`,`	Other mononeuropathies of lower limb Interdigital neuroma of lower limb 	`,`	null	`],
	[`	G57.9	`,`	Mononeuropathy of lower limb, unspecified 	`,`	null	`],
	[`	G58	`,`	Other mononeuropathies 	`,`	null	`],
	[`	G58.0	`,`	Intercostal neuropathy 	`,`	null	`],
	[`	G58.7	`,`	Mononeuritis multiplex 	`,`	null	`],
	[`	G58.8	`,`	Other specified mononeuropathies 	`,`	null	`],
	[`	G58.9	`,`	Mononeuropathy, unspecified 	`,`	null	`],
	[`	G59*	`,`	Mononeuropathy in diseases classified elsewhere 	`,`	null	`],
	[`	G59.0*	`,`	Diabetic mononeuropathy (E10-E14 with common fourth character .4) 	`,`	null	`],
	[`	G59.8*	`,`	Other mononeuropathies in diseases classified elsewhere 	`,`	null	`],
	[`	G60	`,`	Hereditary and idiopathic neuropathy 	`,`	null	`],
	[`	G60.0	`,`	Hereditary motor and sensory neuropathy Disease: Charcot-Marie-Tooth Dejerine-Sottas Hereditary motor and sensory neuropathy, types I-IV Hypertrophic neuropathy of infancy Peroneal muscular atrophy (axonal type)(hypertrophic type) Roussy-Levy syndrome 	`,`	null	`],
	[`	G60.1	`,`	Refsum disease 	`,`	null	`],
	[`	G60.2	`,`	Neuropathy in association with hereditary ataxia 	`,`	null	`],
	[`	G60.3	`,`	Idiopathic progressive neuropathy 	`,`	null	`],
	[`	G60.8	`,`	Other hereditary and idiopathic neuropathies Morvan disease Nelaton syndrome Sensory neuropathy: dominantly inherited recessively inherited 	`,`	null	`],
	[`	G60.9	`,`	Hereditary and idiopathic neuropathy, unspecified 	`,`	null	`],
	[`	G61	`,`	Inflammatory polyneuropathy 	`,`	null	`],
	[`	G61.0	`,`	Guillain-Barre syndrome Acute (post-)infective polyneuritis Miller Fisher Syndrome 	`,`	null	`],
	[`	G61.1	`,`	Serum neuropathy Use additional external cause code (Chapter XX), if desired, to identify cause. 	`,`	null	`],
	[`	G61.8	`,`	Other inflammatory polyneuropathies 	`,`	null	`],
	[`	G61.9	`,`	Inflammatory polyneuropathy, unspecified 	`,`	null	`],
	[`	G62	`,`	Other polyneuropathies 	`,`	null	`],
	[`	62	`,`	Drug-induced polyneuropathy Use additional external cause code (Chapter XX), if desired, to identify drug. 	`,`	null	`],
	[`	G62.1	`,`	Alcoholic polyneuropathy 	`,`	null	`],
	[`	G62.2	`,`	Polyneuropathy due to other toxic agents Use additional external cause code (Chapter XX), if desired, to identify toxic agent. 	`,`	null	`],
	[`	G62.8	`,`	Other specified polyneuropathies Radiation-induced polyneuropathy Use additional external cause code (Chapter XX), if desired, to identify cause. 	`,`	null	`],
	[`	G62.9	`,`	Polyneuropathy, unspecified Neuropathy NOS 	`,`	null	`],
	[`	G63*	`,`	Polyneuropathy in diseases classified elsewhere 	`,`	null	`],
	[`	G63.0*	`,`	Polyneuropathy in infectious and parasitic diseases classified elsewhere Polyneuropathy (in): diphtheria (A36.8) infectious mononucleosis (B27.-) leprosy (A30.-) Lyme disease (A69.2) mumps (B26.8) postherpetic (B02.2) syphilis, late (A52.1) congenital syphilis, late (A50.4) tuberculous (A17.8) 	`,`	null	`],
	[`	G63.1*	`,`	Polyneuropathy in neoplastic disease (C00-D48) 	`,`	null	`],
	[`	G63.2*	`,`	Diabetic polyneuropathy (E10-E14 with common fourth character .4) 	`,`	null	`],
	[`	G63.3*	`,`	Polyneuropathy in other endocrine and metabolic diseases (E00-E07, E15-E16, E20-E34, E70-E89) 	`,`	null	`],
	[`	G63.4*	`,`	Polyneuropathy in nutritional deficiency (E40-E64) 	`,`	null	`],
	[`	G63.5*	`,`	Polyneuropathy in systemic connective tissue disorders (M30-M35) 	`,`	null	`],
	[`	G63.6*	`,`	Polyneuropathy in other musculoskeletal disorders (M00-M25, M40-M96) 	`,`	null	`],
	[`	G63.8*	`,`	Polyneuropathy in other diseases classified elsewhere Uraemic neuropathy (N18.5) 	`,`	null	`],
	[`	G64	`,`	Other disorders of peripheral nervous system Incl.: Disorder of peripheral nervous system NOS 	`,`	null	`],
	[`	G70	`,`	Myasthenia gravis and other myoneural disorders Excl.: botulism (A05.1) transient neonatal myasthenia gravis (P94.0) 	`,`	null	`],
	[`	G70.0	`,`	Myasthenia gravis Use additional external cause code (Chapter XX), if desired, to identify drug, if drug-induced. 	`,`	null	`],
	[`	G70.1	`,`	Toxic myoneural disorders Use additional external cause code (Chapter XX), if desired, to identify toxic agent. 	`,`	null	`],
	[`	G70.2	`,`	Congenital and developmental myasthenia 	`,`	null	`],
	[`	G70.8	`,`	Other specified myoneural disorders 	`,`	null	`],
	[`	G70.9	`,`	Myoneural disorder, unspecified 	`,`	null	`],
	[`	G71	`,`	Primary disorders of muscles Excl.: arthrogryposis multiplex congenita (Q74.3) metabolic disorders (E70-E90) myositis (M60.-) 	`,`	null	`],
	[`	G71.0	`,`	Muscular dystrophy Muscular dystrophy: autosomal recessive, childhood type, resembling Duchenne or Becker benign [Becker] benign scapuloperoneal with early contractures [Emery-Dreifuss] distal facioscapulohumeral limb-girdle ocular oculopharyngeal scapuloperoneal severe [Duchenne] Excl.: congenital muscular dystrophy: NOS (G71.2) with specific morphological abnormalities of the muscle fibre (G71.2) 	`,`	null	`],
	[`	G71.1	`,`	Myotonic disorders Dystrophia myotonica [Steinert] Myotonia: chondrodystrophic drug-induced symptomatic Myotonia congenita: NOS dominant [Thomsen] recessive [Becker] Neuromyotonia [Isaacs] Paramyotonia congenita Pseudomyotonia Use additional external cause code (Chapter XX), if desired, to identify drug, if drug-induced. 	`,`	null	`],
	[`	G71.2	`,`	Congenital myopathies Congenital muscular dystrophy: NOS with specific morphological abnormalities of the muscle fibre Disease: central core minicore multicore Fibre-type disproportion Myopathy: myotubular (centronuclear) nemaline 	`,`	null	`],
	[`	G71.3	`,`	Mitochondrial myopathy, not elsewhere classified 	`,`	null	`],
	[`	G71.8	`,`	Other primary disorders of muscles 	`,`	null	`],
	[`	G71.9	`,`	Primary disorder of muscle, unspecified Hereditary myopathy NOS 	`,`	null	`],
	[`	G72	`,`	Other myopathies Excl.: arthrogryposis multiplex congenita (Q74.3) dermatopolymyositis (M33.-) ischaemic infarction of muscle (M62.2) myositis (M60.-) polymyositis (M33.2) 	`,`	null	`],
	[`	G72.0	`,`	Drug-induced myopathy Use additional external cause code (Chapter XX), if desired, to identify drug. 	`,`	null	`],
	[`	G72.1	`,`	Alcoholic myopathy 	`,`	null	`],
	[`	G72.2	`,`	Myopathy due to other toxic agents Use additional external cause code (Chapter XX), if desired, to identify toxic agent. 	`,`	null	`],
	[`	G72.3	`,`	Periodic paralysis Periodic paralysis (familial): hyperkalaemic hypokalaemic myotonic normokalaemic 	`,`	null	`],
	[`	G72.4	`,`	Inflammatory myopathy, not elsewhere classified 	`,`	null	`],
	[`	G72.8	`,`	Other specified myopathies 	`,`	null	`],
	[`	G72.9	`,`	Myopathy, unspecified 	`,`	null	`],
	[`	G73*	`,`	Disorders of myoneural junction and muscle in diseases classified elsewhere 	`,`	null	`],
	[`	G73.0*	`,`	Myasthenic syndromes in endocrine diseases Myasthenic syndromes in: diabetic amyotrophy (E10-E14 with common fourth character .4) thyrotoxicosis [hyperthyroidism] (E05.-) 	`,`	null	`],
	[`	G73.1*	`,`	Lambert-Eaton syndrome (C00-D48) 	`,`	null	`],
	[`	G73.2*	`,`	Other myasthenic syndromes in neoplastic disease (C00-D48) 	`,`	null	`],
	[`	G73.3*	`,`	Myasthenic syndromes in other diseases classified elsewhere 	`,`	null	`],
	[`	G73.4*	`,`	Myopathy in infectious and parasitic diseases classified elsewhere 	`,`	null	`],
	[`	G73.5*	`,`	Myopathy in endocrine diseases Myopathy in: hyperparathyroidism (E21.0-E21.3) hypoparathyroidism (E20.-) Thyrotoxic myopathy (E05.-) 	`,`	null	`],
	[`	G73.6*	`,`	Myopathy in metabolic diseases Myopathy in: glycogen storage disease (E74.0) lipid storage disorders (E75.-) 	`,`	null	`],
	[`	G73.7*	`,`	Myopathy in other diseases classified elsewhere Myopathy in: rheumatoid arthritis (M05-M06) scleroderma (M34.8) sicca syndrome [Sjogren] (M35.0) systemic lupus erythematosus (M32.1) 	`,`	null	`],
	[`	G80	`,`	Cerebral palsy Excl.: hereditary spastic paraplegia (G11.4) 	`,`	null	`],
	[`	G80.0	`,`	Spastic quadriplegic cerebral palsy Spastic tetraplegic cerebral palsy 	`,`	null	`],
	[`	G80.1	`,`	Spastic diplegic cerebral palsy Congenital spastic paralysis (cerebral) Spastic cerebral palsy NOS 	`,`	null	`],
	[`	G80.2	`,`	Spastic hemiplegic cerebral palsy 	`,`	null	`],
	[`	G80.3	`,`	Dyskinetic cerebral palsy Athetoid cerebral palsy Dystonic cerebral palsy 	`,`	null	`],
	[`	G80.4	`,`	Ataxic cerebral palsy 	`,`	null	`],
	[`	G80.8	`,`	Other cerebral palsy Mixed cerebral palsy syndromes 	`,`	null	`],
	[`	G80.9	`,`	Cerebral palsy, unspecified Cerebral palsy NOS 	`,`	null	`],
	[`	G81	`,`	Hemiplegia Note: For primary coding, this category is to be used only when hemiplegia (complete) (incomplete) is reported without further specification, or is stated to be old or longstanding but of unspecified cause. The category is also for use in multiple coding to identify these types of hemiplegia resulting from any cause. Excl.: congenital cerebral palsy (G80.-) 	`,`	null	`],
	[`	G81.0	`,`	Flaccid hemiplegia 	`,`	null	`],
	[`	G81.1	`,`	Spastic hemiplegia 	`,`	null	`],
	[`	G81.9	`,`	Hemiplegia, unspecified 	`,`	null	`],
	[`	G82	`,`	Paraplegia and tetraplegia Note: For primary coding, this category is to be used only when the listed conditions are reported without further specification, or are stated to be old or longstanding but of unspecified cause. The category is also for use in multiple coding to identify these conditions resulting from any cause. Excl.: congenital cerebral palsy (G80.-) 	`,`	null	`],
	[`	G82.0	`,`	Flaccid paraplegia 	`,`	null	`],
	[`	G82.1	`,`	Spastic paraplegia 	`,`	null	`],
	[`	G82.2	`,`	Paraplegia, unspecified Paralysis of both lower limbs NOS Paraplegia (lower) NOS 	`,`	null	`],
	[`	G82.3	`,`	Flaccid tetraplegia 	`,`	null	`],
	[`	G82.4	`,`	Spastic tetraplegia 	`,`	null	`],
	[`	G82.5	`,`	Tetraplegia, unspecified Quadriplegia NOS 	`,`	null	`],
	[`	G83	`,`	Other paralytic syndromes Note: For primary coding, this category is to be used only when the listed conditions are reported without further specification, or are stated to be old or longstanding but of unspecified cause. The category is also for use in multiple coding to identify these conditions resulting from any cause. Incl.: paralysis (complete)(incomplete), except as in G80-G82 	`,`	null	`],
	[`	G83.0	`,`	Diplegia of upper limbs Diplegia (upper) Paralysis of both upper limbs 	`,`	null	`],
	[`	G83.1	`,`	Monoplegia of lower limb Paralysis of lower limb 	`,`	null	`],
	[`	G83.2	`,`	Monoplegia of upper limb Paralysis of upper limb 	`,`	null	`],
	[`	G83.3	`,`	Monoplegia, unspecified 	`,`	null	`],
	[`	G83.4	`,`	Cauda equina syndrome Neurogenic bladder due to cauda equina syndrome Excl.: cord bladder NOS (G95.8) 	`,`	null	`],
	[`	G83.8	`,`	Other specified paralytic syndromes Todd paralysis (postepileptic) 	`,`	null	`],
	[`	G83.9	`,`	Paralytic syndrome, unspecified 	`,`	null	`],
	[`	G90	`,`	Disorders of autonomic nervous system Excl.: dysfunction of autonomic nervous system due to alcohol (G31.2) 	`,`	null	`],
	[`	G90.0	`,`	Idiopathic peripheral autonomic neuropathy Carotid sinus syncope 	`,`	null	`],
	[`	G90.1	`,`	Familial dysautonomia [Riley-Day] 	`,`	null	`],
	[`	G90.2	`,`	Horner syndrome Bernard(-Horner) syndrome 	`,`	null	`],
	[`	G90.3	`,`	Multi-system degeneration Neurogenic orthostatic hypotension [Shy-Drager] Excl.: orthostatic hypotension NOS (I95.1) 	`,`	null	`],
	[`	G90.4	`,`	Autonomic dysreflexia 	`,`	null	`],
	[`	G90.8	`,`	Other disorders of autonomic nervous system 	`,`	null	`],
	[`	G90.9	`,`	Disorder of autonomic nervous system, unspecified 	`,`	null	`],
	[`	G91	`,`	Hydrocephalus Incl.: acquired hydrocephalus Excl.: hydrocephalus: congenital (Q03.-) due to congenital toxoplasmosis (P37.1) 	`,`	null	`],
	[`	G91.0	`,`	Communicating hydrocephalus 	`,`	null	`],
	[`	G91.1	`,`	Obstructive hydrocephalus 	`,`	null	`],
	[`	G91.2	`,`	Normal-pressure hydrocephalus 	`,`	null	`],
	[`	G91.3	`,`	Post-traumatic hydrocephalus, unspecified 	`,`	null	`],
	[`	G91.8	`,`	Other hydrocephalus 	`,`	null	`],
	[`	G91.9	`,`	Hydrocephalus, unspecified 	`,`	null	`],
	[`	G92	`,`	Toxic encephalopathy Use additional external cause code (Chapter XX), if desired, to identify toxic agent. 	`,`	null	`],
	[`	G93	`,`	Other disorders of brain 	`,`	null	`],
	[`	G93.0	`,`	Cerebral cysts Arachnoid cyst Porencephalic cyst, acquired Excl.: acquired periventricular cysts of newborn (P91.1) congenital cerebral cysts (Q04.6) 	`,`	null	`],
	[`	G93.1	`,`	Anoxic brain damage, not elsewhere classified Excl.: complicating: abortion or ectopic or molar pregnancy (O00-O07, O08.8) pregnancy, labour or delivery (O29.2, O74.3, O89.2) surgical and medical care (T80-T88) neonatal anoxia (P21.9) 	`,`	null	`],
	[`	G93.2	`,`	Benign intracranial hypertension Excl.: hypertensive encephalopathy (I67.4) 	`,`	null	`],
	[`	G93.3	`,`	Postviral fatigue syndrome Benign myalgic encephalomyelitis 	`,`	null	`],
	[`	G93.4	`,`	Encephalopathy, unspecified Excl.: encephalopathy: alcoholic (G31.2) toxic (G92) 	`,`	null	`],
	[`	G93.5	`,`	Compression of brain Compression Herniation of brain (stem) Excl.: traumatic compression of brain (diffuse) (S06.2) traumatic compression of brain (diffuse) focal (S06.3) 	`,`	null	`],
	[`	G93.6	`,`	Cerebral oedema Excl.: cerebral oedema: due to birth injury (P11.0) traumatic (S06.1) 	`,`	null	`],
	[`	G93.7	`,`	Reye syndrome Use additional external cause code (Chapter XX), if desired, to identify cause. 	`,`	null	`],
	[`	G93.8	`,`	Other specified disorders of brain Postradiation encephalopathy Use additional external cause code (Chapter XX), if desired, to identify cause. 	`,`	null	`],
	[`	G93.9	`,`	Disorder of brain, unspecified 	`,`	null	`],
	[`	G94*	`,`	Other disorders of brain in diseases classified elsewhere 	`,`	null	`],
	[`	G94.0*	`,`	Hydrocephalus in infectious and parasitic diseases classified elsewhere (A00-B99) 	`,`	null	`],
	[`	G94.1*	`,`	Hydrocephalus in neoplastic disease (C00-D48) 	`,`	null	`],
	[`	G94.2*	`,`	Hydrocephalus in other diseases classified elsewhere 	`,`	null	`],
	[`	G94.8*	`,`	Other specified disorders of brain in diseases classified elsewhere 	`,`	null	`],
	[`	G95	`,`	Other diseases of spinal cord Excl.: myelitis (G04.-) 	`,`	null	`],
	[`	G95.0	`,`	Syringomyelia and syringobulbia 	`,`	null	`],
	[`	G95.1	`,`	Vascular myelopathies Acute infarction of spinal cord (embolic)(nonembolic) Arterial thrombosis of spinal cord Haematomyelia Nonpyogenic intraspinal phlebitis and thrombophlebitis Oedema of spinal cord Subacute necrotic myelopathy Excl.: intraspinal phlebitis and thrombophlebitis, except non-pyogenic (G08) 	`,`	null	`],
	[`	G95.2	`,`	Cord compression, unspecified 	`,`	null	`],
	[`	G95.8	`,`	Other specified diseases of spinal cord Cord bladder NOS Myelopathy: drug-induced radiation-induced Use additional external cause code (Chapter XX), if desired, to identify external agent. Excl.: neurogenic bladder: NOS (N31.9) due to cauda equina syndrome (G83.4) neuromuscular dysfunction of bladder without mention of spinal cord lesion (N31.-) 	`,`	null	`],
	[`	G95.9	`,`	Disease of spinal cord, unspecified Myelopathy NOS 	`,`	null	`],
	[`	G96	`,`	Other disorders of central nervous system 	`,`	null	`],
	[`	G96.0	`,`	Cerebrospinal fluid leak Excl.: from spinal puncture (G97.0) 	`,`	null	`],
	[`	G96.1	`,`	Disorders of meninges, not elsewhere classified Meningeal adhesions (cerebral)(spinal) 	`,`	null	`],
	[`	G96.8	`,`	Other specified disorders of central nervous system 	`,`	null	`],
	[`	G96.9	`,`	Disorder of central nervous system, unspecified 	`,`	null	`],
	[`	G97	`,`	Postprocedural disorders of nervous system, not elsewhere classified 	`,`	null	`],
	[`	G97.0	`,`	Cerebrospinal fluid leak from spinal puncture 	`,`	null	`],
	[`	G97.1	`,`	Other reaction to spinal and lumbar puncture 	`,`	null	`],
	[`	G97.2	`,`	Intracranial hypotension following ventricular shunting 	`,`	null	`],
	[`	G97.8	`,`	Other postprocedural disorders of nervous system 	`,`	null	`],
	[`	G97.9	`,`	Postprocedural disorder of nervous system, unspecified 	`,`	null	`],
	[`	G98	`,`	Other disorders of nervous system, not elsewhere classified Incl.: Nervous system disorder NOS 	`,`	null	`],
	[`	G99*	`,`	Other disorders of nervous system in diseases classified elsewhere 	`,`	null	`],
	[`	G99.0*	`,`	Autonomic neuropathy in endocrine and metabolic diseases Amyloid autonomic neuropathy (E85.-) Diabetic autonomic neuropathy (E10-E14 with common fourth character .4) 	`,`	null	`],
	[`	G99.1*	`,`	Other disorders of autonomic nervous system in other diseases classified elsewhere 	`,`	null	`],
	[`	G99.2*	`,`	Myelopathy in diseases classified elsewhere Anterior spinal and vertebral artery compression syndromes (M47.0) Myelopathy in: intervertebral disc disorders (M50.0, M51.0) neoplastic disease (C00-D48) spondylosis (M47.-) 	`,`	null	`],
	[`	G99.8*	`,`	Other specified disorders of nervous system in diseases classified elsewhere Uraemic paralysis (N18.5) 	`,`	null	`],
							
							
];								
			
							
							
				
	
let CodeRangeG ={
	f0:function(val1=(-1),val2=(0)){
		let Range1 = GCodes.slice(val1,val2);
		Range1.reverse();
		document.documentElement.innerHTML += `<br>Showing G Codes ${Range1.length} items(s)`;

		for(value1 in Range1){
			    document.documentElement.style.cssText += "background-color:tan;";
				document.getElementById('gcodesTR').outerHTML += `<tr><td style="background-color:navy;color:white;width:5%;padding:40px;border:2px solid white;font-weight:900;font-size:40px;text-align:center;">${Range1[value1][0]}</td><td style="background-color:black;color:white;width:90%;padding:20px;border:2px solid white;font-size:30px;">${Range1[value1][1]}</td><td style="background-color:navy;color:white;width:5%;padding:20px;border:2px solid white;font-weight:900;font-size:40px;text-align:center;">${Range1[value1][2]}</td></tr>`;			
		}

	},

};

	






	






