								
let HCodes = [								
								
	[`		`,`		`,`		`],
	[`	H00	`,`	Hordeolum and chalazion 	`,`	null	`],
	[`	H00.0	`,`	Hordeolum and other deep inflammation of eyelid Abscess Furuncle Stye of eyelid 	`,`	null	`],
	[`	H00.1	`,`	Chalazion 	`,`	null	`],
	[`	H01	`,`	Other inflammation of eyelid 	`,`	null	`],
	[`	H01.0	`,`	Blepharitis Excl.: blepharoconjunctivitis (H10.5) 	`,`	null	`],
	[`	H01.1	`,`	Noninfectious dermatoses of eyelid Dermatitis: allergic contact eczematous Discoid lupus erythematosus Xeroderma of eyelid 	`,`	null	`],
	[`	H01.8	`,`	Other specified inflammation of eyelid 	`,`	null	`],
	[`	H01.9	`,`	Inflammation of eyelid, unspecified 	`,`	null	`],
	[`	H02	`,`	Other disorders of eyelid Excl.: congenital malformations of eyelid (Q10.0-Q10.3) 	`,`	null	`],
	[`	H02.0	`,`	Entropion and trichiasis of eyelid 	`,`	null	`],
	[`	H02.1	`,`	Ectropion of eyelid 	`,`	null	`],
	[`	H02.2	`,`	Lagophthalmos 	`,`	null	`],
	[`	H02.3	`,`	Blepharochalasis 	`,`	null	`],
	[`	H02.4	`,`	Ptosis of eyelid 	`,`	null	`],
	[`	H02.5	`,`	Other disorders affecting eyelid function Ankyloblepharon Blepharophimosis Lid retraction Excl.: blepharospasm (G24.5) tic (psychogenic) (F95.-) tic (psychogenic) organic (G25.6) 	`,`	null	`],
	[`	H02.6	`,`	Xanthelasma of eyelid 	`,`	null	`],
	[`	H02.7	`,`	Other degenerative disorders of eyelid and periocular area Chloasma Madarosis Vitiligo of eyelid 	`,`	null	`],
	[`	H02.8	`,`	Other specified disorders of eyelid Hypertrichosis of eyelid Retained foreign body in eyelid 	`,`	null	`],
	[`	H02.9	`,`	Disorder of eyelid, unspecified 	`,`	null	`],
	[`	H03*	`,`	Disorders of eyelid in diseases classified elsewhere 	`,`	null	`],
	[`	H03.0*	`,`	Parasitic infestation of eyelid in diseases classified elsewhere Dermatitis of eyelid due to Demodex species (B88.0) Parasitic infestation of eyelid in: leishmaniasis (B55.-) loiasis (B74.3) onchocerciasis (B73) phthiriasis (B85.3) 	`,`	null	`],
	[`	H03.1*	`,`	Involvement of eyelid in other infectious diseases classified elsewhere Involvement of eyelid in: herpesviral [herpes simplex] infection (B00.5) leprosy (A30.-) molluscum contagiosum (B08.1) tuberculosis (A18.4) yaws (A66.-) zoster (B02.3) 	`,`	null	`],
	[`	H03.8*	`,`	Involvement of eyelid in other diseases classified elsewhere Involvement of eyelid in impetigo (L01.0) 	`,`	null	`],
	[`	H04	`,`	Disorders of lacrimal system Excl.: congenital malformations of lacrimal system (Q10.4-Q10.6) 	`,`	null	`],
	[`	H04.0	`,`	Dacryoadenitis Chronic enlargement of lacrimal gland 	`,`	null	`],
	[`	H04.1	`,`	Other disorders of lacrimal gland Dacryops Dry eye syndrome Lacrimal: cyst gland atrophy 	`,`	null	`],
	[`	H04.2	`,`	Epiphora 	`,`	null	`],
	[`	H04.3	`,`	Acute and unspecified inflammation of lacrimal passages Dacryocystitis (phlegmonous) Dacryopericystitis Lacrimal canaliculitis acute, subacute or unspecified Excl.: neonatal dacryocystitis (P39.1) 	`,`	null	`],
	[`	H04.4	`,`	Chronic inflammation of lacrimal passages Dacryocystitis Lacrimal: canaliculitis mucocele chronic 	`,`	null	`],
	[`	H04.5	`,`	Stenosis and insufficiency of lacrimal passages Dacryolith Eversion of lacrimal punctum Stenosis of lacrimal: canaliculi duct sac 	`,`	null	`],
	[`	H04.6	`,`	Other changes in lacrimal passages Lacrimal fistula 	`,`	null	`],
	[`	H04.8	`,`	Other disorders of lacrimal system 	`,`	null	`],
	[`	H04.9	`,`	Disorder of lacrimal system, unspecified 	`,`	null	`],
	[`	H05	`,`	Disorders of orbit Excl.: congenital malformation of orbit (Q10.7) 	`,`	null	`],
	[`	H05.0	`,`	Acute inflammation of orbit Abscess Cellulitis Osteomyelitis Periostitis of orbit Tenonitis 	`,`	null	`],
	[`	H05.1	`,`	Chronic inflammatory disorders of orbit Granuloma of orbit 	`,`	null	`],
	[`	H05.2	`,`	Exophthalmic conditions Displacement of globe (lateral) NOS Haemorrhage Oedema of orbit 	`,`	null	`],
	[`	H05.3	`,`	Deformity of orbit Atrophy Exostosis of orbit 	`,`	null	`],
	[`	H05.4	`,`	Enophthalmos 	`,`	null	`],
	[`	H05.5	`,`	Retained (old) foreign body following penetrating wound of orbit Retrobulbar foreign body 	`,`	null	`],
	[`	H05.8	`,`	Other disorders of orbit Cyst of orbit 	`,`	null	`],
	[`	H05.9	`,`	Disorder of orbit, unspecified 	`,`	null	`],
	[`	H06*	`,`	Disorders of lacrimal system and orbit in diseases classified elsewhere 	`,`	null	`],
	[`	H06.0*	`,`	Disorders of lacrimal system in diseases classified elsewhere 	`,`	null	`],
	[`	H06.1*	`,`	Parasitic infestation of orbit in diseases classified elsewhere Echinococcus infection of orbit (B67.-) Myiasis of orbit (B87.2) 	`,`	null	`],
	[`	H06.2*	`,`	Dysthyroid exophthalmos (E05.-) 	`,`	null	`],
	[`	H06.3*	`,`	Other disorders of orbit in diseases classified elsewhere 	`,`	null	`],
	[`	H10	`,`	Conjunctivitis Excl.: keratoconjunctivitis (H16.2) 	`,`	null	`],
	[`	H10.0	`,`	Mucopurulent conjunctivitis 	`,`	null	`],
	[`	H10.1	`,`	Acute atopic conjunctivitis 	`,`	null	`],
	[`	H10.2	`,`	Other acute conjunctivitis 	`,`	null	`],
	[`	H10.3	`,`	Acute conjunctivitis, unspecified Excl.: ophthalmia neonatorum NOS (P39.1) 	`,`	null	`],
	[`	H10.4	`,`	Chronic conjunctivitis 	`,`	null	`],
	[`	H10.5	`,`	Blepharoconjunctivitis 	`,`	null	`],
	[`	H10.8	`,`	Other conjunctivitis 	`,`	null	`],
	[`	H10.9	`,`	Conjunctivitis, unspecified 	`,`	null	`],
	[`	H11	`,`	Other disorders of conjunctiva Excl.: keratoconjunctivitis (H16.2) 	`,`	null	`],
	[`	H11.0	`,`	Pterygium Excl.: pseudopterygium (H11.8) 	`,`	null	`],
	[`	H11.1	`,`	Conjunctival degenerations and deposits Conjunctival: argyrosis [argyria] concretions pigmentation xerosis NOS 	`,`	null	`],
	[`	H11.2	`,`	Conjunctival scars Symblepharon 	`,`	null	`],
	[`	H11.3	`,`	Conjunctival haemorrhage Subconjunctival haemorrhage 	`,`	null	`],
	[`	H11.4	`,`	Other conjunctival vascular disorders and cysts Conjunctival: aneurysm hyperaemia oedema 	`,`	null	`],
	[`	H11.8	`,`	Other specified disorders of conjunctiva Pseudopterygium 	`,`	null	`],
	[`	H11.9	`,`	Disorder of conjunctiva, unspecified 	`,`	null	`],
	[`	H13*	`,`	Disorders of conjunctiva in diseases classified elsewhere 	`,`	null	`],
	[`	H13.0*	`,`	Filarial infection of conjunctiva (B74.-) 	`,`	null	`],
	[`	H13.1*	`,`	Conjunctivitis in infectious and parasitic diseases classified elsewhere Conjunctivitis (due to): Acanthamoeba (B60.1) adenoviral follicular (acute) (B30.1) chlamydial (A74.0) diphtheritic (A36.8) gonococcal (A54.3) haemorrhagic (acute)(epidemic) (B30.3) herpesviral [herpes simplex] (B00.5) meningococcal (A39.8) Newcastle (B30.8) zoster (B02.3) 	`,`	null	`],
	[`	H13.2*	`,`	Conjunctivitis in other diseases classified elsewhere 	`,`	null	`],
	[`	H13.3*	`,`	Ocular pemphigoid (L12.-) 	`,`	null	`],
	[`	H13.8*	`,`	Other disorders of conjunctiva in diseases classified elsewhere 	`,`	null	`],
	[`	H15	`,`	Disorders of sclera 	`,`	null	`],
	[`	H15.0	`,`	Scleritis 	`,`	null	`],
	[`	H15.1	`,`	Episcleritis 	`,`	null	`],
	[`	H15.8	`,`	Other disorders of sclera Equatorial staphyloma Scleral ectasia Excl.: degenerative myopia (H44.2) 	`,`	null	`],
	[`	H15.9	`,`	Disorder of sclera, unspecified 	`,`	null	`],
	[`	H16	`,`	Keratitis 	`,`	null	`],
	[`	H16.0	`,`	Corneal ulcer Ulcer: corneal: NOS central marginal perforated ring with hypopyon Mooren 	`,`	null	`],
	[`	H16.1	`,`	Other superficial keratitis without conjunctivitis Keratitis: areolar filamentary nummular stellate striate superficial punctate Photokeratitis Snow blindness 	`,`	null	`],
	[`	H16.2	`,`	Keratoconjunctivitis Keratoconjunctivitis: NOS exposure neurotrophic phlyctenular Ophthalmia nodosa Superficial keratitis with conjunctivitis 	`,`	null	`],
	[`	H16.3	`,`	Interstitial and deep keratitis 	`,`	null	`],
	[`	H16.4	`,`	Corneal neovascularization Ghost vessels (corneal) Pannus (corneal) 	`,`	null	`],
	[`	H16.8	`,`	Other keratitis 	`,`	null	`],
	[`	H16.9	`,`	Keratitis, unspecified 	`,`	null	`],
	[`	H17	`,`	Corneal scars and opacities 	`,`	null	`],
	[`	H17.0	`,`	Adherent leukoma 	`,`	null	`],
	[`	H17.1	`,`	Other central corneal opacity 	`,`	null	`],
	[`	H17.8	`,`	Other corneal scars and opacities 	`,`	null	`],
	[`	H17.9	`,`	Corneal scar and opacity, unspecified 	`,`	null	`],
	[`	H18	`,`	Other disorders of cornea 	`,`	null	`],
	[`	H18.0	`,`	Corneal pigmentations and deposits Haematocornea Kayser-Fleischer ring Krukenberg spindle Staehli line Use additional external cause code (Chapter XX), if desired, to identify drug, if drug-induced. 	`,`	null	`],
	[`	H18.1	`,`	Bullous keratopathy 	`,`	null	`],
	[`	H18.2	`,`	Other corneal oedema 	`,`	null	`],
	[`	H18.3	`,`	Changes in corneal membranes Fold Rupture in Descemet membrane 	`,`	null	`],
	[`	H18.4	`,`	Corneal degeneration Arcus senilis Band keratopathy Excl.: Mooren ulcer (H16.0) 	`,`	null	`],
	[`	H18.5	`,`	Hereditary corneal dystrophies Dystrophy: corneal: epithelial granular lattice macular Fuchs 	`,`	null	`],
	[`	H18.6	`,`	Keratoconus 	`,`	null	`],
	[`	H18.7	`,`	Other corneal deformities Corneal: ectasia staphyloma Descemetocele Excl.: congenital malformations of cornea (Q13.3-Q13.4) 	`,`	null	`],
	[`	H18.8	`,`	Other specified disorders of cornea Anaesthesia Hypaesthesia Recurrent erosion of cornea 	`,`	null	`],
	[`	H18.9	`,`	Disorder of cornea, unspecified 	`,`	null	`],
	[`	H19*	`,`	Disorders of sclera and cornea in diseases classified elsewhere 	`,`	null	`],
	[`	H19.0*	`,`	Scleritis and episcleritis in diseases classified elsewhere Syphilitic episcleritis (A52.7) Tuberculous episcleritis (A18.5) Zoster scleritis (B02.3) 	`,`	null	`],
	[`	H19.1*	`,`	Herpesviral keratitis and keratoconjunctivitis (B00.5) Dendritic and disciform keratitis 	`,`	null	`],
	[`	H19.2*	`,`	Keratitis and keratoconjunctivitis in other infectious and parasitic diseases classified elsewhere Epidemic keratoconjunctivitis (B30.0) Keratitis and keratoconjunctivitis (interstitial) in: acanthamoebiasis (B60.1) measles (B05.8) syphilis (A50.3) tuberculosis (A18.5) zoster (B02.3) 	`,`	null	`],
	[`	H19.3*	`,`	Keratitis and keratoconjunctivitis in other diseases classified elsewhere Keratoconjunctivitis sicca (M35.0) 	`,`	null	`],
	[`	H19.8*	`,`	Other disorders of sclera and cornea in diseases classified elsewhere Keratoconus in Down syndrome (Q90.-) 	`,`	null	`],
	[`	H20	`,`	Iridocyclitis 	`,`	null	`],
	[`	H20.0	`,`	Acute and subacute iridocyclitis Anterior uveitis Cyclitis Iritis acute, recurrent or subacute 	`,`	null	`],
	[`	H20.1	`,`	Chronic iridocyclitis 	`,`	null	`],
	[`	H20.2	`,`	Lens-induced iridocyclitis 	`,`	null	`],
	[`	H20.8	`,`	Other iridocyclitis 	`,`	null	`],
	[`	H20.9	`,`	Iridocyclitis, unspecified 	`,`	null	`],
	[`	H21	`,`	Other disorders of iris and ciliary body Excl.: sympathetic uveitis (H44.1) 	`,`	null	`],
	[`	H21.0	`,`	Hyphaema Excl.: traumatic hyphaema (S05.1) 	`,`	null	`],
	[`	H21.1	`,`	Other vascular disorders of iris and ciliary body Neovascularization of iris or ciliary body Rubeosis of iris 	`,`	null	`],
	[`	H21.2	`,`	Degeneration of iris and ciliary body Degeneration of: iris (pigmentary) pupillary margin Iridoschisis Iris atrophy (essential)(progressive) Miotic pupillary cyst Translucency of iris 	`,`	null	`],
	[`	H21.3	`,`	Cyst of iris, ciliary body and anterior chamber Cyst of iris, ciliary body or anterior chamber: NOS exudative implantation parasitic Excl.: miotic pupillary cyst (H21.2) 	`,`	null	`],
	[`	H21.4	`,`	Pupillary membranes Iris bombe Pupillary: occlusion seclusion 	`,`	null	`],
	[`	H21.5	`,`	Other adhesions and disruptions of iris and ciliary body Goniosynechiae Iridodialysis Recession, chamber angle Synechiae (iris): NOS anterior posterior Excl.: corectopia (Q13.2) 	`,`	null	`],
	[`	H21.8	`,`	Other specified disorders of iris and ciliary body 	`,`	null	`],
	[`	H21.9	`,`	Disorder of iris and ciliary body, unspecified 	`,`	null	`],
	[`	H22*	`,`	Disorders of iris and ciliary body in diseases classified elsewhere 	`,`	null	`],
	[`	H22.0*	`,`	Iridocyclitis in infectious and parasitic diseases classified elsewhere Iridocyclitis in: gonococcal infection (A54.3) herpesviral [herpes simplex] infection (B00.5) syphilis (secondary) (A51.4) tuberculosis (A18.5) zoster (B02.3) 	`,`	null	`],
	[`	H22.1*	`,`	Iridocyclitis in other diseases classified elsewhere Iridocyclitis in: ankylosing spondylitis (M45) sarcoidosis (D86.8) 	`,`	null	`],
	[`	H22.8*	`,`	Other disorders of iris and ciliary body in diseases classified elsewhere 	`,`	null	`],
	[`	H25	`,`	Senile cataract Excl.: capsular glaucoma with pseudoexfoliation of lens (H40.1) 	`,`	null	`],
	[`	H25.0	`,`	Senile incipient cataract Senile cataract: coronary cortical punctate Subcapsular polar senile cataract (anterior)(posterior) Water clefts 	`,`	null	`],
	[`	H25.1	`,`	Senile nuclear cataract Cataracta brunescens Nuclear sclerosis cataract 	`,`	null	`],
	[`	H25.2	`,`	Senile cataract, morgagnian type Senile hypermature cataract 	`,`	null	`],
	[`	H25.8	`,`	Other senile cataract Combined forms of senile cataract 	`,`	null	`],
	[`	H25.9	`,`	Senile cataract, unspecified 	`,`	null	`],
	[`	H26	`,`	Other cataract Excl.: congenital cataract (Q12.0) 	`,`	null	`],
	[`	H26.0	`,`	Infantile, juvenile and presenile cataract 	`,`	null	`],
	[`	H26.1	`,`	Traumatic cataract Use additional external cause code (Chapter XX), if desired, to identify cause. 	`,`	null	`],
	[`	H26.2	`,`	Complicated cataract Cataract in chronic iridocyclitis Cataract secondary to ocular disorders Glaucomatous flecks (subcapsular) 	`,`	null	`],
	[`	H26.3	`,`	Drug-induced cataract Use additional external cause code (Chapter XX), if desired, to identify drug. 	`,`	null	`],
	[`	H26.4	`,`	After-cataract Secondary cataract Soemmerring ring 	`,`	null	`],
	[`	H26.8	`,`	Other specified cataract 	`,`	null	`],
	[`	H26.9	`,`	Cataract, unspecified 	`,`	null	`],
	[`	H27	`,`	Other disorders of lens Excl.: congenital lens malformations (Q12.-) mechanical complications of intraocular lens (T85.2) pseudophakia (Z96.1) 	`,`	null	`],
	[`	H27.0	`,`	Aphakia 	`,`	null	`],
	[`	H27.1	`,`	Dislocation of lens 	`,`	null	`],
	[`	H27.8	`,`	Other specified disorders of lens 	`,`	null	`],
	[`	H27.9	`,`	Disorder of lens, unspecified 	`,`	null	`],
	[`	H28*	`,`	Cataract and other disorders of lens in diseases classified elsewhere 	`,`	null	`],
	[`	H28.0*	`,`	Diabetic cataract (E10-E14 with common fourth character .3) 	`,`	null	`],
	[`	H28.1*	`,`	Cataract in other endocrine, nutritional and metabolic diseases Cataract in hypoparathyroidism (E20.-) Malnutrition-dehydration cataract (E40-E46) 	`,`	null	`],
	[`	H28.2*	`,`	Cataract in other diseases classified elsewhere Myotonic cataract (G71.1) 	`,`	null	`],
	[`	H28.8*	`,`	Other disorders of lens in diseases classified elsewhere 	`,`	null	`],
	[`	H30	`,`	Chorioretinal inflammation 	`,`	null	`],
	[`	H30.0	`,`	Focal chorioretinal inflammation Focal: chorioretinitis choroiditis retinitis retinochoroiditis 	`,`	null	`],
	[`	H30.1	`,`	Disseminated chorioretinal inflammation Disseminated: chorioretinitis choroiditis retinitis retinochoroiditis Excl.: exudative retinopathy (H35.0) 	`,`	null	`],
	[`	H30.2	`,`	Posterior cyclitis Pars planitis 	`,`	null	`],
	[`	H30.8	`,`	Other chorioretinal inflammations Harada disease 	`,`	null	`],
	[`	H30.9	`,`	Chorioretinal inflammation, unspecified Chorioretinitis Choroiditis Retinitis Retinochoroiditis NOS 	`,`	null	`],
	[`	H31	`,`	Other disorders of choroid 	`,`	null	`],
	[`	H31.0	`,`	Chorioretinal scars Macula scars of posterior pole (postinflammatory)(post-traumatic) Solar retinopathy 	`,`	null	`],
	[`	H31.1	`,`	Choroidal degeneration Atrophy Sclerosis of choroid Excl.: angioid streaks (H35.3) 	`,`	null	`],
	[`	H31.2	`,`	Hereditary choroidal dystrophy Choroideremia Dystrophy, choroidal (central areolar)(generalized)(peripapillary) Gyrate atrophy, choroid Excl.: ornithinaemia (E72.4) 	`,`	null	`],
	[`	H31.3	`,`	Choroidal haemorrhage and rupture Choroidal haemorrhage: NOS expulsive 	`,`	null	`],
	[`	H31.4	`,`	Choroidal detachment 	`,`	null	`],
	[`	H31.8	`,`	Other specified disorders of choroid 	`,`	null	`],
	[`	H31.9	`,`	Disorder of choroid, unspecified 	`,`	null	`],
	[`	H32*	`,`	Chorioretinal disorders in diseases classified elsewhere 	`,`	null	`],
	[`	H32.0*	`,`	Chorioretinal inflammation in infectious and parasitic diseases classified elsewhere Chorioretinitis: syphilitic, late (A52.7) toxoplasma (B58.0) tuberculous (A18.5) 	`,`	null	`],
	[`	H32.8*	`,`	Other chorioretinal disorders in diseases classified elsewhere Albuminuric retinitis (N18.5) Renal retinitis (N18.5) 	`,`	null	`],
	[`	H33	`,`	Retinal detachments and breaks Excl.: detachment of retinal pigment epithelium (H35.7) 	`,`	null	`],
	[`	H33.0	`,`	Retinal detachment with retinal break Rhegmatogenous retinal detachment 	`,`	null	`],
	[`	H33.1	`,`	Retinoschisis and retinal cysts Cyst of ora serrata Parasitic cyst of retina NOS Pseudocyst of retina Excl.: congenital retinoschisis (Q14.1) microcystoid degeneration of retina (H35.4) 	`,`	null	`],
	[`	H33.2	`,`	Serous retinal detachment Retinal detachment: NOS without retinal break Excl.: central serous chorioretinopathy (H35.7) 	`,`	null	`],
	[`	H33.3	`,`	Retinal breaks without detachment Horseshoe tear Round hole of retina, without detachment Operculum Retinal break NOS Excl.: chorioretinal scars after surgery for detachment (H59.8) peripheral retinal degeneration without break (H35.4) 	`,`	null	`],
	[`	H33.4	`,`	Traction detachment of retina Proliferative vitreo-retinopathy with retinal detachment 	`,`	null	`],
	[`	H33.5	`,`	Other retinal detachments 	`,`	null	`],
	[`	H34	`,`	Retinal vascular occlusions Excl.: amaurosis fugax (G45.3) 	`,`	null	`],
	[`	H34.0	`,`	Transient retinal artery occlusion 	`,`	null	`],
	[`	H34.1	`,`	Central retinal artery occlusion 	`,`	null	`],
	[`	H34.2	`,`	Other retinal artery occlusions Hollenhorst plaque Retinal: artery occlusion: branch partial microembolism 	`,`	null	`],
	[`	H34.8	`,`	Other retinal vascular occlusions Retinal vein occlusion: central incipient partial tributary 	`,`	null	`],
	[`	H34.9	`,`	Retinal vascular occlusion, unspecified 	`,`	null	`],
	[`	H35	`,`	Other retinal disorders 	`,`	null	`],
	[`	H35.0	`,`	Background retinopathy and retinal vascular changes Changes in retinal vascular appearance Retinal: micro-aneurysms neovascularization perivasculitis varices vascular sheathing vasculitis Retinopathy: NOS background NOS Coats exudative hypertensive 	`,`	null	`],
	[`	H35.1	`,`	Retinopathy of prematurity Retrolental fibroplasia 	`,`	null	`],
	[`	H35.2	`,`	Other proliferative retinopathy Proliferative vitreo-retinopathy Excl.: proliferative vitreo-retinopathy with retinal detachment (H33.4) 	`,`	null	`],
	[`	H35.3	`,`	Degeneration of macula and posterior pole Angioid streaks Cyst Drusen (degenerative) Hole Puckering of macula Kuhnt-Junius degeneration Senile macular degeneration (atrophic)(exudative) Toxic maculopathy Use additional external cause code (Chapter XX), if desired, to identify drug, if drug-induced. 	`,`	null	`],
	[`	H35.4	`,`	Peripheral retinal degeneration Degeneration, retina: NOS lattice microcystoid palisade paving stone reticular Excl.: with retinal break (H33.3) 	`,`	null	`],
	[`	H35.5	`,`	Hereditary retinal dystrophy Dystrophy: retinal (albipunctate)(pigmentary)(vitelliform) tapetoretinal vitreoretinal Retinitis pigmentosa Stargardt disease 	`,`	null	`],
	[`	H35.6	`,`	Retinal haemorrhage 	`,`	null	`],
	[`	H35.7	`,`	Separation of retinal layers Central serous chorioretinopathy Detachment of retinal pigment epithelium 	`,`	null	`],
	[`	H35.8	`,`	Other specified retinal disorders 	`,`	null	`],
	[`	H35.9	`,`	Retinal disorder, unspecified 	`,`	null	`],
	[`	H36*	`,`	Retinal disorders in diseases classified elsewhere 	`,`	null	`],
	[`	H36.0*	`,`	Diabetic retinopathy (E10-E14 with common fourth character .3) 	`,`	null	`],
	[`	H36.8*	`,`	Other retinal disorders in diseases classified elsewhere Atherosclerotic retinopathy (I70.8) Proliferative sickle-cell retinopathy (D57.-) Retinal dystrophy in lipid storage disorders (E75.-) 	`,`	null	`],
	[`	H40	`,`	Glaucoma Excl.: absolute glaucoma (H44.5) congenital glaucoma (Q15.0) traumatic glaucoma due to birth injury (P15.3) 	`,`	null	`],
	[`	H40.0	`,`	Glaucoma suspect Ocular hypertension 	`,`	null	`],
	[`	H40.1	`,`	Primary open-angle glaucoma Glaucoma (primary)(residual stage): capsular with pseudoexfoliation of lens chronic simple low-tension pigmentary 	`,`	null	`],
	[`	H40.2	`,`	Primary angle-closure glaucoma Angle-closure glaucoma (primary)(residual stage): acute chronic intermittent 	`,`	null	`],
	[`	H40.3	`,`	Glaucoma secondary to eye trauma Use additional code, if desired, to identify cause. 	`,`	null	`],
	[`	H40.4	`,`	Glaucoma secondary to eye inflammation Use additional code, if desired, to identify cause. 	`,`	null	`],
	[`	H40.5	`,`	Glaucoma secondary to other eye disorders Use additional code, if desired, to identify cause. 	`,`	null	`],
	[`	H40.6	`,`	Glaucoma secondary to drugs Use additional external cause code (Chapter XX), if desired, to identify drug. 	`,`	null	`],
	[`	H40.8	`,`	Other glaucoma 	`,`	null	`],
	[`	H40.9	`,`	Glaucoma, unspecified 	`,`	null	`],
	[`	H42*	`,`	Glaucoma in diseases classified elsewhere 	`,`	null	`],
	[`	H42.0*	`,`	Glaucoma in endocrine, nutritional and metabolic diseases Glaucoma in: amyloidosis (E85.-) Lowe syndrome (E72.0) 	`,`	null	`],
	[`	H42.8*	`,`	Glaucoma in other diseases classified elsewhere Glaucoma in onchocerciasis (B73) 	`,`	null	`],
	[`	H43	`,`	Disorders of vitreous body 	`,`	null	`],
	[`	H43.0	`,`	Vitreous prolapse Excl.: vitreous syndrome following cataract surgery (H59.0) 	`,`	null	`],
	[`	H43.1	`,`	Vitreous haemorrhage 	`,`	null	`],
	[`	H43.2	`,`	Crystalline deposits in vitreous body 	`,`	null	`],
	[`	H43.3	`,`	Other vitreous opacities Vitreous membranes and strands 	`,`	null	`],
	[`	H43.8	`,`	Other disorders of vitreous body Vitreous: degeneration detachment Excl.: proliferative vitreo-retinopathy with retinal detachment (H33.4) 	`,`	null	`],
	[`	H43.9	`,`	Disorder of vitreous body, unspecified 	`,`	null	`],
	[`	H44	`,`	Disorders of globe Incl.: disorders affecting multiple structures of eye 	`,`	null	`],
	[`	H44.0	`,`	Purulent endophthalmitis Panophthalmitis Vitreous abscess 	`,`	null	`],
	[`	H44.1	`,`	Other endophthalmitis Parasitic endophthalmitis NOS Sympathetic uveitis 	`,`	null	`],
	[`	H44.2	`,`	Degenerative myopia 	`,`	null	`],
	[`	H44.3	`,`	Other degenerative disorders of globe Chalcosis Siderosis of eye 	`,`	null	`],
	[`	H44.4	`,`	Hypotony of eye 	`,`	null	`],
	[`	H44.5	`,`	Degenerated conditions of globe Absolute glaucoma Atrophy of globe Phthisis bulbi 	`,`	null	`],
	[`	H44.6	`,`	Retained (old) intraocular foreign body, magnetic Retained (old) magnetic foreign body (in): anterior chamber ciliary body iris lens posterior wall of globe vitreous body 	`,`	null	`],
	[`	H44.7	`,`	Retained (old) intraocular foreign body, nonmagnetic Retained (nonmagnetic)(old) foreign body (in): anterior chamber ciliary body iris lens posterior wall of globe vitreous body 	`,`	null	`],
	[`	H44.8	`,`	Other disorders of globe Haemophthalmos Luxation of globe 	`,`	null	`],
	[`	H44.9	`,`	Disorder of globe, unspecified 	`,`	null	`],
	[`	H45*	`,`	Disorders of vitreous body and globe in diseases classified elsewhere 	`,`	null	`],
	[`	H45.0*	`,`	Vitreous haemorrhage in diseases classified elsewhere 	`,`	null	`],
	[`	H45.1*	`,`	Endophthalmitis in diseases classified elsewhere Endophthalmitis in: cysticercosis (B69.1) onchocerciasis (B73) toxocariasis (B83.0) 	`,`	null	`],
	[`	H45.8*	`,`	Other disorders of vitreous body and globe in diseases classified elsewhere 	`,`	null	`],
	[`	H49	`,`	Paralytic strabismus Excl.: ophthalmoplegia: internal (H52.5) internuclear (H51.2) progressive supranuclear (G23.1) 	`,`	null	`],
	[`	H49.0	`,`	Third [oculomotor] nerve palsy 	`,`	null	`],
	[`	H49.1	`,`	Fourth [trochlear] nerve palsy 	`,`	null	`],
	[`	H49.2	`,`	Sixth [abducent] nerve palsy 	`,`	null	`],
	[`	H49.3	`,`	Total (external) ophthalmoplegia 	`,`	null	`],
	[`	H49.4	`,`	Progressive external ophthalmoplegia 	`,`	null	`],
	[`	H49.8	`,`	Other paralytic strabismus External ophthalmoplegia NOS Kearns-Sayre syndrome 	`,`	null	`],
	[`	H49.9	`,`	Paralytic strabismus, unspecified 	`,`	null	`],
	[`	H50	`,`	Other strabismus 	`,`	null	`],
	[`	H50.0	`,`	Convergent concomitant strabismus Esotropia (alternating)(monocular), except intermittent 	`,`	null	`],
	[`	H50.1	`,`	Divergent concomitant strabismus Exotropia (alternating)(monocular), except intermittent 	`,`	null	`],
	[`	H50.2	`,`	Vertical strabismus Hypertropia Hypotropia 	`,`	null	`],
	[`	H50.3	`,`	Intermittent heterotropia Intermittent: esotropia exotropia (alternating)(monocular) 	`,`	null	`],
	[`	H50.4	`,`	Other and unspecified heterotropia Concomitant strabismus NOS Cyclotropia Microtropia Monofixation syndrome 	`,`	null	`],
	[`	H50.5	`,`	Heterophoria Alternating hyperphoria Esophoria Exophoria 	`,`	null	`],
	[`	H50.6	`,`	Mechanical strabismus Brown sheath syndrome Strabismus due to adhesions Traumatic limitation of duction of eye muscle 	`,`	null	`],
	[`	H50.8	`,`	Other specified strabismus Duane syndrome 	`,`	null	`],
	[`	H50.9	`,`	Strabismus, unspecified 	`,`	null	`],
	[`	H51	`,`	Other disorders of binocular movement 	`,`	null	`],
	[`	H51.0	`,`	Palsy of conjugate gaze 	`,`	null	`],
	[`	H51.1	`,`	Convergence insufficiency and excess 	`,`	null	`],
	[`	H51.2	`,`	Internuclear ophthalmoplegia 	`,`	null	`],
	[`	H51.8	`,`	Other specified disorders of binocular movement 	`,`	null	`],
	[`	H51.9	`,`	Disorder of binocular movement, unspecified 	`,`	null	`],
	[`	H52	`,`	Disorders of refraction and accommodation 	`,`	null	`],
	[`	H52.0	`,`	Hypermetropia 	`,`	null	`],
	[`	H52.1	`,`	Myopia Excl.: degenerative myopia (H44.2) 	`,`	null	`],
	[`	H52.2	`,`	Astigmatism 	`,`	null	`],
	[`	H52.3	`,`	Anisometropia and aniseikonia 	`,`	null	`],
	[`	H52.4	`,`	Presbyopia 	`,`	null	`],
	[`	H52.5	`,`	Disorders of accommodation Internal ophthalmoplegia (complete)(total) Paresis Spasm of accommodation 	`,`	null	`],
	[`	H52.6	`,`	Other disorders of refraction 	`,`	null	`],
	[`	H52.7	`,`	Disorder of refraction, unspecified 	`,`	null	`],
	[`	H55	`,`	Nystagmus and other irregular eye movements Incl.: Nystagmus: NOS congenital deprivation dissociated latent 	`,`	null	`],
	[`	H57	`,`	Other disorders of eye and adnexa 	`,`	null	`],
	[`	H57.0	`,`	Anomalies of pupillary function 	`,`	null	`],
	[`	H57.1	`,`	Ocular pain 	`,`	null	`],
	[`	H57.8	`,`	Other specified disorders of eye and adnexa 	`,`	null	`],
	[`	H57.9	`,`	Disorder of eye and adnexa, unspecified 	`,`	null	`],
	[`	H58*	`,`	Other disorders of eye and adnexa in diseases classified elsewhere 	`,`	null	`],
	[`	H58.0*	`,`	Anomalies of pupillary function in diseases classified elsewhere Argyll Robertson phenomenon or pupil, syphilitic (A52.1) 	`,`	null	`],
	[`	H58.1*	`,`	Visual disturbances in diseases classified elsewhere 	`,`	null	`],
	[`	H58.8*	`,`	Other specified disorders of eye and adnexa in diseases classified elsewhere Syphilitic oculopathy NEC: congenital: early (A50.0) late (A50.3) early (secondary) (A51.4) late (A52.7) 	`,`	null	`],
	[`	H59	`,`	Postprocedural disorders of eye and adnexa, not elsewhere classified Excl.: mechanical complication of: intraocular lens (T85.2) other ocular prosthetic devices, implants and grafts (T85.3) pseudophakia (Z96.1) 	`,`	null	`],
	[`	H59.0	`,`	Keratopathy (bullous aphakic) following cataract surgery Vitreous (touch) syndrome Vitreal corneal syndrome 	`,`	null	`],
	[`	H59.8	`,`	Other postprocedural disorders of eye and adnexa Bleb associated endophthalmitis Chorioretinal scars after surgery for detachment Inflammation (infection) of postprocedural bleb Postprocedural blebitis 	`,`	null	`],
	[`	H59.9	`,`	Postprocedural disorder of eye and adnexa, unspecified 	`,`	null	`],
	[`	H60	`,`	Otitis externa 	`,`	null	`],
	[`	H60.0	`,`	Abscess of external ear Boil Carbuncle Furuncle of auricle or external auditory canal 	`,`	null	`],
	[`	H60.1	`,`	Cellulitis of external ear Cellulitis of: auricle external auditory canal 	`,`	null	`],
	[`	H60.2	`,`	Malignant otitis externa 	`,`	null	`],
	[`	H60.3	`,`	Other infective otitis externa Otitis externa: diffuse haemorrhagic Swimmer ear 	`,`	null	`],
	[`	H60.4	`,`	Cholesteatoma of external ear Keratosis obturans of external ear (canal) 	`,`	null	`],
	[`	H60.5	`,`	Acute otitis externa, noninfective Acute otitis externa: NOS actinic chemical contact eczematoid reactive 	`,`	null	`],
	[`	H60.8	`,`	Other otitis externa Chronic otitis externa NOS 	`,`	null	`],
	[`	H60.9	`,`	Otitis externa, unspecified 	`,`	null	`],
	[`	H61	`,`	Other disorders of external ear 	`,`	null	`],
	[`	H61.0	`,`	Perichondritis of external ear Chondrodermatitis nodularis chronica helicis Perichondritis of: auricle pinna 	`,`	null	`],
	[`	H61.1	`,`	Noninfective disorders of pinna Acquired deformity of: auricle pinna Excl.: cauliflower ear (M95.1) 	`,`	null	`],
	[`	H61.2	`,`	Impacted cerumen Wax in ear 	`,`	null	`],
	[`	H61.3	`,`	Acquired stenosis of external ear canal Collapse of external ear canal 	`,`	null	`],
	[`	H61.8	`,`	Other specified disorders of external ear Exostosis of external canal 	`,`	null	`],
	[`	H61.9	`,`	Disorder of external ear, unspecified 	`,`	null	`],
	[`	H62*	`,`	Disorders of external ear in diseases classified elsewhere 	`,`	null	`],
	[`	H62.0*	`,`	Otitis externa in bacterial diseases classified elsewhere Otitis externa in erysipelas (A46) 	`,`	null	`],
	[`	H62.1*	`,`	Otitis externa in viral diseases classified elsewhere Otitis externa in: herpesviral [herpes simplex] infection (B00.1) zoster (B02.8) 	`,`	null	`],
	[`	H62.2*	`,`	Otitis externa in mycoses Otitis externa in: aspergillosis (B44.8) candidiasis (B37.2) Otomycosis NOS (B36.9) 	`,`	null	`],
	[`	H62.3*	`,`	Otitis externa in other infectious and parasitic diseases classified elsewhere 	`,`	null	`],
	[`	H62.4*	`,`	Otitis externa in other diseases classified elsewhere Otitis externa in impetigo (L01.-) 	`,`	null	`],
	[`	H62.8*	`,`	Other disorders of external ear in diseases classified elsewhere 	`,`	null	`],
	[`	H65	`,`	Nonsuppurative otitis media Incl.: with myringitis Use additional code (H72.-) , if desired, to identify presence of perforated tympanic membrane. 	`,`	null	`],
	[`	H65.0	`,`	Acute serous otitis media Acute and subacute secretory otitis media 	`,`	null	`],
	[`	H65.1	`,`	Other acute nonsuppurative otitis media Otitis media, acute and subacute: allergic (mucoid)(sanguinous)(serous) mucoid nonsuppurative NOS sanguinous seromucinous Excl.: otitic barotrauma (T70.0) otitis media (acute) NOS (H66.9) 	`,`	null	`],
	[`	H65.2	`,`	Chronic serous otitis media Chronic tubotympanal catarrh 	`,`	null	`],
	[`	H65.3	`,`	Chronic mucoid otitis media Glue ear Otitis media, chronic: mucinous secretory transudative Excl.: adhesive middle ear disease (H74.1) 	`,`	null	`],
	[`	H65.4	`,`	Other chronic nonsuppurative otitis media Otitis media, chronic: allergic exudative nonsuppurative NOS seromucinous with effusion (nonpurulent) 	`,`	null	`],
	[`	H65.9	`,`	Nonsuppurative otitis media, unspecified Otitis media: allergic catarrhal exudative mucoid secretory seromucinous serous transudative with effusion (nonpurulent) 	`,`	null	`],
	[`	H66	`,`	Suppurative and unspecified otitis media Incl.: with myringitis Use additional code (H72.-) , if desired, to identify presence of perforated tympanic membrane. 	`,`	null	`],
	[`	H66.0	`,`	Acute suppurative otitis media 	`,`	null	`],
	[`	H66.1	`,`	Chronic tubotympanic suppurative otitis media Benign chronic suppurative otitis media Chronic tubotympanic disease 	`,`	null	`],
	[`	H66.2	`,`	Chronic atticoantral suppurative otitis media Chronic atticoantral disease 	`,`	null	`],
	[`	H66.3	`,`	Other chronic suppurative otitis media Chronic suppurative otitis media NOS 	`,`	null	`],
	[`	H66.4	`,`	Suppurative otitis media, unspecified Purulent otitis media NOS 	`,`	null	`],
	[`	H66.9	`,`	Otitis media, unspecified Otitis media: NOS acute NOS chronic NOS 	`,`	null	`],
	[`	H67*	`,`	Otitis media in diseases classified elsewhere 	`,`	null	`],
	[`	H67.0*	`,`	Otitis media in bacterial diseases classified elsewhere Otitis media in: scarlet fever (A38) tuberculosis (A18.6) 	`,`	null	`],
	[`	H67.1*	`,`	Otitis media in viral diseases classified elsewhere Otitis media in: influenza (J09-J11) measles (B05.3) 	`,`	null	`],
	[`	H67.8*	`,`	Otitis media in other diseases classified elsewhere 	`,`	null	`],
	[`	H68	`,`	Eustachian salpingitis and obstruction 	`,`	null	`],
	[`	H68.0	`,`	Eustachian salpingitis 	`,`	null	`],
	[`	H68.1	`,`	Obstruction of Eustachian tube Compression Stenosis Stricture of Eustachian tube 	`,`	null	`],
	[`	H69	`,`	Other disorders of Eustachian tube 	`,`	null	`],
	[`	H69.0	`,`	Patulous Eustachian tube 	`,`	null	`],
	[`	H69.8	`,`	Other specified disorders of Eustachian tube 	`,`	null	`],
	[`	H69.9	`,`	Eustachian tube disorder, unspecified 	`,`	null	`],
	[`	H70	`,`	Mastoiditis and related conditions 	`,`	null	`],
	[`	H70.0	`,`	Acute mastoiditis Abscess Empyema of mastoid 	`,`	null	`],
	[`	H70.1	`,`	Chronic mastoiditis Caries Fistula of mastoid 	`,`	null	`],
	[`	H70.2	`,`	Petrositis Inflammation of petrous bone (acute)(chronic) 	`,`	null	`],
	[`	H70.8	`,`	Other mastoiditis and related conditions 	`,`	null	`],
	[`	H70.9	`,`	Mastoiditis, unspecified 	`,`	null	`],
	[`	H71	`,`	Cholesteatoma of middle ear Incl.: Cholesteatoma tympani Excl.: cholesteatoma of external ear (H60.4) recurrent cholesteatoma of postmastoidectomy cavity (H95.0) 	`,`	null	`],
	[`	H72	`,`	Perforation of tympanic membrane Incl.: perforation of ear drum: persistent post-traumatic postinflammatory Excl.: traumatic rupture of ear drum (S09.2) 	`,`	null	`],
	[`	H72.0	`,`	Central perforation of tympanic membrane 	`,`	null	`],
	[`	H72.1	`,`	Attic perforation of tympanic membrane Perforation of pars flaccida 	`,`	null	`],
	[`	H72.2	`,`	Other marginal perforations of tympanic membrane 	`,`	null	`],
	[`	H72.8	`,`	Other perforations of tympanic membrane Perforation(s): multiple total of tympanic membrane 	`,`	null	`],
	[`	H72.9	`,`	Perforation of tympanic membrane, unspecified 	`,`	null	`],
	[`	H73	`,`	Other disorders of tympanic membrane 	`,`	null	`],
	[`	H73.0	`,`	Acute myringitis Acute tympanitis Bullous myringitis Excl.: with otitis media (H65-H66) 	`,`	null	`],
	[`	H73.1	`,`	Chronic myringitis Chronic tympanitis Excl.: with otitis media (H65-H66) 	`,`	null	`],
	[`	H73.8	`,`	Other specified disorders of tympanic membrane 	`,`	null	`],
	[`	H73.9	`,`	Disorder of tympanic membrane, unspecified 	`,`	null	`],
	[`	H74	`,`	Other disorders of middle ear and mastoid 	`,`	null	`],
	[`	H74.0	`,`	Tympanosclerosis 	`,`	null	`],
	[`	H74.1	`,`	Adhesive middle ear disease Adhesive otitis Excl.: glue ear (H65.3) 	`,`	null	`],
	[`	H74.2	`,`	Discontinuity and dislocation of ear ossicles 	`,`	null	`],
	[`	H74.3	`,`	Other acquired abnormalities of ear ossicles Ankylosis Partial loss of ear ossicles 	`,`	null	`],
	[`	H74.4	`,`	Polyp of middle ear 	`,`	null	`],
	[`	H74.8	`,`	Other specified disorders of middle ear and mastoid 	`,`	null	`],
	[`	H74.9	`,`	Disorder of middle ear and mastoid, unspecified 	`,`	null	`],
	[`	H75*	`,`	Other disorders of middle ear and mastoid in diseases classified elsewhere 	`,`	null	`],
	[`	H75.0*	`,`	Mastoiditis in infectious and parasitic diseases classified elsewhere Tuberculous mastoiditis (A18.0) 	`,`	null	`],
	[`	H75.8*	`,`	Other specified disorders of middle ear and mastoid in diseases classified elsewhere 	`,`	null	`],
	[`	H80	`,`	Otosclerosis Incl.: otospongiosis 	`,`	null	`],
	[`	H80.0	`,`	Otosclerosis involving oval window, nonobliterative 	`,`	null	`],
	[`	H80.1	`,`	Otosclerosis involving oval window, obliterative 	`,`	null	`],
	[`	H80.2	`,`	Cochlear otosclerosis Otosclerosis involving: otic capsule round window 	`,`	null	`],
	[`	H80.8	`,`	Other otosclerosis 	`,`	null	`],
	[`	H80.9	`,`	Otosclerosis, unspecified 	`,`	null	`],
	[`	H81	`,`	Disorders of vestibular function Excl.: vertigo: NOS (R42) epidemic (A88.1) 	`,`	null	`],
	[`	H81.0	`,`	Meniere disease Labyrinthine hydrops Meniere syndrome or vertigo 	`,`	null	`],
	[`	H81.1	`,`	Benign paroxysmal vertigo 	`,`	null	`],
	[`	H81.2	`,`	Vestibular neuronitis 	`,`	null	`],
	[`	H81.3	`,`	Other peripheral vertigo Lermoyez syndrome Vertigo: aural otogenic peripheral NOS 	`,`	null	`],
	[`	H81.4	`,`	Vertigo of central origin Central positional nystagmus 	`,`	null	`],
	[`	H81.8	`,`	Other disorders of vestibular function 	`,`	null	`],
	[`	H81.9	`,`	Disorder of vestibular function, unspecified Vertiginous syndrome NOS 	`,`	null	`],
	[`	H82*	`,`	Vertiginous syndromes in diseases classified elsewhere 	`,`	null	`],
	[`	H83	`,`	Other diseases of inner ear 	`,`	null	`],
	[`	H83.0	`,`	Labyrinthitis 	`,`	null	`],
	[`	H83.1	`,`	Labyrinthine fistula 	`,`	null	`],
	[`	H83.2	`,`	Labyrinthine dysfunction Hypersensitivity Hypofunction Loss of function of labyrinth 	`,`	null	`],
	[`	H83.3	`,`	Noise effects on inner ear Acoustic trauma Noise-induced hearing loss 	`,`	null	`],
	[`	H83.8	`,`	Other specified diseases of inner ear 	`,`	null	`],
	[`	H83.9	`,`	Disease of inner ear, unspecified 	`,`	null	`],
	[`	H90	`,`	Conductive and sensorineural hearing loss Incl.: congenital deafness Excl.: deaf mutism NEC (H91.3) deafness NOS (H91.9) hearing loss: NOS (H91.9) noise-induced (H83.3) ototoxic (H91.0) sudden (idiopathic) (H91.2) 	`,`	null	`],
	[`	H90.0	`,`	Conductive hearing loss, bilateral 	`,`	null	`],
	[`	H90.1	`,`	Conductive hearing loss, unilateral with unrestricted hearing on the contralateral side 	`,`	null	`],
	[`	H90.2	`,`	Conductive hearing loss, unspecified Conductive deafness NOS 	`,`	null	`],
	[`	H90.3	`,`	Sensorineural hearing loss, bilateral 	`,`	null	`],
	[`	H90.4	`,`	Sensorineural hearing loss, unilateral with unrestricted hearing on the contralateral side 	`,`	null	`],
	[`	H90.5	`,`	Sensorineural hearing loss, unspecified Congenital deafness NOS Hearing loss: central neural perceptive sensory NOS Sensorineural deafness NOS 	`,`	null	`],
	[`	H90.6	`,`	Mixed conductive and sensorineural hearing loss, bilateral 	`,`	null	`],
	[`	H90.7	`,`	Mixed conductive and sensorineural hearing loss, unilateral with unrestricted hearing on the contralateral side 	`,`	null	`],
	[`	H90.8	`,`	Mixed conductive and sensorineural hearing loss, unspecified 	`,`	null	`],
	[`	H91	`,`	Other hearing loss Excl.: abnormal auditory perception (H93.2) hearing loss as classified in H90.- impacted cerumen (H61.2) noise-induced hearing loss (H83.3) psychogenic deafness (F44.6) transient ischaemic deafness (H93.0) 	`,`	null	`],
	[`	H91.0	`,`	Ototoxic hearing loss Use additional external cause code (Chapter XX), if desired, to identify toxic agent. 	`,`	null	`],
	[`	H91.1	`,`	Presbycusis Presbyacusia 	`,`	null	`],
	[`	H91.2	`,`	Sudden idiopathic hearing loss Sudden hearing loss NOS 	`,`	null	`],
	[`	H91.3	`,`	Deaf mutism, not elsewhere classified 	`,`	null	`],
	[`	H91.8	`,`	Other specified hearing loss 	`,`	null	`],
	[`	H91.9	`,`	Hearing loss, unspecified Deafness: NOS high frequency low frequency 	`,`	null	`],
	[`	H92	`,`	Otalgia and effusion of ear 	`,`	null	`],
	[`	H92.0	`,`	Otalgia 	`,`	null	`],
	[`	H92.1	`,`	Otorrhoea Excl.: leakage of cerebrospinal fluid through ear (G96.0) 	`,`	null	`],
	[`	H92.2	`,`	Otorrhagia Excl.: traumatic otorrhagia - code by type of injury. 	`,`	null	`],
	[`	H93	`,`	Other disorders of ear, not elsewhere classified 	`,`	null	`],
	[`	H93.0	`,`	Degenerative and vascular disorders of ear Transient ischaemic deafness Excl.: presbycusis (H91.1) 	`,`	null	`],
	[`	H93.1	`,`	Tinnitus 	`,`	null	`],
	[`	H93.2	`,`	Other abnormal auditory perceptions Auditory recruitment Diplacusis Hyperacusis Temporary auditory threshold shift Excl.: auditory hallucinations (R44.0) 	`,`	null	`],
	[`	H93.3	`,`	Disorders of acoustic nerve Disorder of 8th cranial nerve 	`,`	null	`],
	[`	H93.8	`,`	Other specified disorders of ear 	`,`	null	`],
	[`	H93.9	`,`	Disorder of ear, unspecified 	`,`	null	`],
	[`	H94*	`,`	Other disorders of ear in diseases classified elsewhere 	`,`	null	`],
	[`	H94.0*	`,`	Acoustic neuritis in infectious and parasitic diseases classified elsewhere Acoustic neuritis in syphilis (A52.1) 	`,`	null	`],
	[`	H94.8*	`,`	Other specified disorders of ear in diseases classified elsewhere 	`,`	null	`],
	[`	H95	`,`	Postprocedural disorders of ear and mastoid process, not elsewhere classified 	`,`	null	`],
	[`	H95.0	`,`	Recurrent cholesteatoma of postmastoidectomy cavity 	`,`	null	`],
	[`	H95.1	`,`	Other disorders following mastoidectomy Chronic inflammation Granulation Mucosal cyst of postmastoidectomy cavity 	`,`	null	`],
	[`	H95.8	`,`	Other postprocedural disorders of ear and mastoid process 	`,`	null	`],
	[`	H95.9	`,`	Postprocedural disorder of ear and mastoid process, unspecified 	`,`	null	`],
							
							
];								
					
							
				
	
let CodeRangeH ={
	f0:function(val1=(-1),val2=(0)){
		let Range1 = HCodes.slice(val1,val2);
		Range1.reverse();
		document.documentElement.innerHTML += `<br>Showing H Codes ${Range1.length} items(s)`;

		for(value2 in Range1){
			    document.documentElement.style.cssText += "background-color:tan;";
				document.getElementById('hcodesTR').outerHTML += `<tr><td style="background-color:navy;color:white;width:5%;padding:40px;border:2px solid white;font-weight:900;font-size:40px;text-align:center;">${Range1[value2][0]}</td><td style="background-color:black;color:white;width:90%;padding:20px;border:2px solid white;font-size:30px;">${Range1[value2][1]}</td><td style="background-color:navy;color:white;width:5%;padding:20px;border:2px solid white;font-weight:900;font-size:40px;text-align:center;">${Range1[value2][2]}</td></tr>`;			
		}

	},

};

	






	






