let ICodes = [								
	[`		`,`		`,`		`],
	[`	I00	`,`	Rheumatic fever without mention of heart involvement Incl.: Arthritis, rheumatic, acute or subacute 	`,`	null	`],
	[`	I01	`,`	Rheumatic fever with heart involvement Excl.: chronic diseases of rheumatic origin (I05-I09) unless rheumatic fever is also present or there is evidence of recrudescence or activity of the rheumatic process. In cases where there is doubt as to rheumatic activity at the time of death refer to the mortality coding rules and guidelines in Volume 2. 	`,`	null	`],
	[`	I01.0	`,`	Acute rheumatic pericarditis Any condition in I00 with pericarditis Rheumatic pericarditis (acute) Excl.: when not specified as rheumatic (I30.-) 	`,`	null	`],
	[`	I01.1	`,`	Acute rheumatic endocarditis Any condition in I00 with endocarditis or valvulitis Acute rheumatic valvulitis 	`,`	null	`],
	[`	I01.2	`,`	Acute rheumatic myocarditis Any condition in I00 with myocarditis 	`,`	null	`],
	[`	I01.8	`,`	Other acute rheumatic heart disease Any condition in I00 with other or multiple types of heart involvement Acute rheumatic pancarditis 	`,`	null	`],
	[`	I01.9	`,`	Acute rheumatic heart disease, unspecified Any condition in I00 with unspecified type of heart involvement Rheumatic: carditis, acute heart disease, active or acute 	`,`	null	`],
	[`	I02	`,`	Rheumatic chorea Incl.: Sydenham chorea Excl.: chorea: NOS (G25.5) Huntington (G10) 	`,`	null	`],
	[`	I02.0	`,`	Rheumatic chorea with heart involvement Chorea NOS with heart involvement Rheumatic chorea with heart involvement of any type classifiable under I01.- 	`,`	null	`],
	[`	I02.9	`,`	Rheumatic chorea without heart involvement Rheumatic chorea NOS 	`,`	null	`],
	[`	I05	`,`	Rheumatic mitral valve diseases Incl.: conditions classifiable to (I05.0) and (I05.2-I05.9) , whether specified as rheumatic or not Excl.: when specified as nonrheumatic (I34.-) 	`,`	null	`],
	[`	I05.0	`,`	Mitral stenosis Mitral (valve) obstruction (rheumatic) 	`,`	null	`],
	[`	I05.1	`,`	Rheumatic mitral insufficiency Rheumatic mitral: incompetence regurgitation 	`,`	null	`],
	[`	I05.2	`,`	Mitral stenosis with insufficiency Mitral stenosis with incompetence or regurgitation 	`,`	null	`],
	[`	I05.8	`,`	Other mitral valve diseases Mitral (valve) failure 	`,`	null	`],
	[`	I05.9	`,`	Mitral valve disease, unspecified Mitral (valve) disorder (chronic) NOS 	`,`	null	`],
	[`	I06	`,`	Rheumatic aortic valve diseases Excl.: when not specified as rheumatic (I35.-) 	`,`	null	`],
	[`	I06.0	`,`	Rheumatic aortic stenosis Rheumatic aortic (valve) obstruction 	`,`	null	`],
	[`	I06.1	`,`	Rheumatic aortic insufficiency Rheumatic aortic: incompetence regurgitation 	`,`	null	`],
	[`	I06.2	`,`	Rheumatic aortic stenosis with insufficiency Rheumatic aortic stenosis with incompetence or regurgitation 	`,`	null	`],
	[`	I06.8	`,`	Other rheumatic aortic valve diseases 	`,`	null	`],
	[`	I06.9	`,`	Rheumatic aortic valve disease, unspecified Rheumatic aortic (valve) disease NOS 	`,`	null	`],
	[`	I07	`,`	Rheumatic tricuspid valve diseases Incl.: whether specified as rheumatic or of unspecified origin Excl.: when specified as nonrheumatic (I36.-) 	`,`	null	`],
	[`	I07.0	`,`	Tricuspid stenosis Tricuspid (valve) stenosis (rheumatic) 	`,`	null	`],
	[`	I07.1	`,`	Tricuspid insufficiency Tricuspid (valve) insufficiency (rheumatic) 	`,`	null	`],
	[`	I07.2	`,`	Tricuspid stenosis with insufficiency 	`,`	null	`],
	[`	I07.8	`,`	Other tricuspid valve diseases 	`,`	null	`],
	[`	I07.9	`,`	Tricuspid valve disease, unspecified Tricuspid valve disorder NOS 	`,`	null	`],
	[`	I08	`,`	Multiple valve diseases Incl.: whether specified as rheumatic or of unspecified origin Excl.: endocarditis, valve unspecified (I38) multiple valve diseases of specified origin other than rheumatic heart disease; use appropriate codes in (I34-I38, Q22-Q23, Q24.8) rheumatic diseases of endocardium, valve unspecified (I09.1) 	`,`	null	`],
	[`	I08.0	`,`	Disorders of both mitral and aortic valves Involvement of both mitral and aortic valves whether specified as rheumatic or of unspecified origin 	`,`	null	`],
	[`	I08.1	`,`	Disorders of both mitral and tricuspid valves 	`,`	null	`],
	[`	I08.2	`,`	Disorders of both aortic and tricuspid valves 	`,`	null	`],
	[`	I08.3	`,`	Combined disorders of mitral, aortic and tricuspid valves 	`,`	null	`],
	[`	I08.8	`,`	Other multiple valve diseases 	`,`	null	`],
	[`	I08.9	`,`	Multiple valve disease, unspecified 	`,`	null	`],
	[`	I09	`,`	Other rheumatic heart diseases 	`,`	null	`],
	[`	I09.0	`,`	Rheumatic myocarditis Excl.: myocarditis not specified as rheumatic (I51.4) 	`,`	null	`],
	[`	I09.1	`,`	Rheumatic diseases of endocardium, valve unspecified Rheumatic: endocarditis (chronic) valvulitis (chronic) Excl.: endocarditis, valve unspecified (I38) 	`,`	null	`],
	[`	I09.2	`,`	Chronic rheumatic pericarditis Adherent pericardium, rheumatic Chronic rheumatic: mediastinopericarditis myopericarditis Excl.: when not specified as rheumatic (I31.-) 	`,`	null	`],
	[`	I09.8	`,`	Other specified rheumatic heart diseases Rheumatic disease of pulmonary valve 	`,`	null	`],
	[`	I09.9	`,`	Rheumatic heart disease, unspecified Rheumatic: carditis heart failure Excl.: rheumatoid carditis (M05.3) 	`,`	null	`],
	[`	I10	`,`	Essential (primary) hypertension Incl.: High blood pressure Hypertension (arterial)(benign)(essential)(malignant)(primary)(systemic) Excl.: involving vessels of: brain (I60-I69) eye (H35.0) 	`,`	null	`],
	[`	I11	`,`	Hypertensive heart disease Incl.: any condition in I50.-, I51.4-I51.9 due to hypertension 	`,`	null	`],
	[`	I11.0	`,`	Hypertensive heart disease with (congestive) heart failure Hypertensive heart failure 	`,`	null	`],
	[`	I11.9	`,`	Hypertensive heart disease without (congestive) heart failure Hypertensive heart disease NOS 	`,`	null	`],
	[`	I12	`,`	Hypertensive renal disease Incl.: any condition in N00-N07, N18.-, N19 or N26 due to hypertension arteriosclerosis of kidney arteriosclerotic nephritis (chronic)(interstitial) hypertensive nephropathy nephrosclerosis Excl.: secondary hypertension (I15.-) 	`,`	null	`],
	[`	I12.0	`,`	Hypertensive renal disease with renal failure Hypertensive renal failure 	`,`	null	`],
	[`	I12.9	`,`	Hypertensive renal disease without renal failure Hypertensive renal disease NOS 	`,`	null	`],
	[`	I13	`,`	Hypertensive heart and renal disease Incl.: any condition in I11.- with any condition in I12.- disease: cardiorenal cardiovascular renal 	`,`	null	`],
	[`	I13.0	`,`	Hypertensive heart and renal disease with (congestive) heart failure 	`,`	null	`],
	[`	I13.1	`,`	Hypertensive heart and renal disease with renal failure 	`,`	null	`],
	[`	I13.2	`,`	Hypertensive heart and renal disease with both (congestive) heart failure and renal failure 	`,`	null	`],
	[`	I13.9	`,`	Hypertensive heart and renal disease, unspecified 	`,`	null	`],
	[`	I15	`,`	Secondary hypertension Excl.: involving vessels of: brain (I60-I69) eye (H35.0) 	`,`	null	`],
	[`	I15.0	`,`	Renovascular hypertension 	`,`	null	`],
	[`	I15.1	`,`	Hypertension secondary to other renal disorders 	`,`	null	`],
	[`	I15.2	`,`	Hypertension secondary to endocrine disorders 	`,`	null	`],
	[`	I15.8	`,`	Other secondary hypertension 	`,`	null	`],
	[`	I15.9	`,`	Secondary hypertension, unspecified 	`,`	null	`],
	[`	I20	`,`	Angina pectoris I20.0 Unstable angina Angina: crescendo de novo effort worsening effort Intermediate coronary syndrome Preinfarction syndrome 	`,`	null	`],
	[`	I20.1	`,`	Angina pectoris with documented spasm Angina: angiospastic Prinzmetal spasm-induced variant 	`,`	null	`],
	[`	I20.8	`,`	Other forms of angina pectoris Angina of effort Coronary slow flow syndrome Stenocardia 	`,`	null	`],
	[`	I20.9	`,`	Angina pectoris, unspecified Angina: NOS cardiac Anginal syndrome Ischaemic chest pain 	`,`	null	`],
	[`	I21	`,`	Acute myocardial infarction Incl.: myocardial infarction specified as acute or with a stated duration of 4 weeks (28 days) or less from onset Excl.: certain current complications following acute myocardial infarction (I23.-) myocardial infarction: old (I25.2) specified as chronic or with a stated duration of more than 4 weeks (more than 28 days) from onset (I25.8) subsequent (I22.-) postmyocardial infarction syndrome (I24.1) 	`,`	null	`],
	[`	I21.0	`,`	Acute transmural myocardial infarction of anterior wall Transmural infarction (acute)(of): anterior (wall) NOS anteroapical anterolateral anteroseptal 	`,`	null	`],
	[`	I21.1	`,`	Acute transmural myocardial infarction of inferior wall Transmural infarction (acute)(of): diaphragmatic wall inferior (wall) NOS inferolateral inferoposterior 	`,`	null	`],
	[`	I21.2	`,`	Acute transmural myocardial infarction of other sites Transmural infarction (acute)(of): apical-lateral basal-lateral high lateral lateral (wall) NOS posterior (true) posterobasal posterolateral posteroseptal septal NOS 	`,`	null	`],
	[`	I21.3	`,`	Acute transmural myocardial infarction of unspecified site Transmural myocardial infarction NOS 	`,`	null	`],
	[`	I21.4	`,`	Acute subendocardial myocardial infarction Nontransmural myocardial infarction NOS 	`,`	null	`],
	[`	I21.9	`,`	Acute myocardial infarction, unspecified Myocardial infarction (acute) NOS 	`,`	null	`],
	[`	I22	`,`	Subsequent myocardial infarction Note: For morbidity coding, this category should be assigned for infarction of any myocardial site, occurring within 4 weeks (28 days) from onset of a previous infarction Incl.: myocardial infarction: extension recurrent reinfarction Excl.: specified as chronic or with a stated duration of more than 4 weeks (more than 28 days) from onset (I25.8) 	`,`	null	`],
	[`	I22.0	`,`	Subsequent myocardial infarction of anterior wall Subsequent infarction (acute)(of): anterior (wall) NOS anteroapical anterolateral anteroseptal 	`,`	null	`],
	[`	I22.1	`,`	Subsequent myocardial infarction of inferior wall Subsequent infarction (acute)(of): diaphragmatic wall inferior (wall) NOS inferolateral inferoposterior 	`,`	null	`],
	[`	I22.8	`,`	Subsequent myocardial infarction of other sites Subsequent myocardial infarction (acute)(of): apical-lateral basal-lateral high lateral lateral (wall) NOS posterior (true) posterobasal posterolateral posteroseptal septal NOS 	`,`	null	`],
	[`	I22.9	`,`	Subsequent myocardial infarction of unspecified site 	`,`	null	`],
	[`	I23	`,`	Certain current complications following acute myocardial infarction Excl.: the listed conditions, when: concurrent with acute myocardial infarction (I21-I22) not specified as current complications following acute myocardial infarction (I31.-, I51.-) 	`,`	null	`],
	[`	I23.0	`,`	Haemopericardium as current complication following acute myocardial infarction 	`,`	null	`],
	[`	I23.1	`,`	Atrial septal defect as current complication following acute myocardial infarction 	`,`	null	`],
	[`	I23.2	`,`	Ventricular septal defect as current complication following acute myocardial infarction 	`,`	null	`],
	[`	I23.3	`,`	Rupture of cardiac wall without haemopericardium as current complication following acute myocardial infarction Excl.: with haemopericardium (I23.0) 	`,`	null	`],
	[`	I23.4	`,`	Rupture of chordae tendineae as current complication following acute myocardial infarction 	`,`	null	`],
	[`	I23.5	`,`	Rupture of papillary muscle as current complication following acute myocardial infarction 	`,`	null	`],
	[`	I23.6	`,`	Thrombosis of atrium, auricular appendage, and ventricle as current complications following acute myocardial infarction 	`,`	null	`],
	[`	I23.8	`,`	Other current complications following acute myocardial infarction 	`,`	null	`],
	[`	I24	`,`	Other acute ischaemic heart diseases Excl.: angina pectoris (I20.-) transient myocardial ischaemia of newborn (P29.4) 	`,`	null	`],
	[`	I24.0	`,`	Coronary thrombosis not resulting in myocardial infarction Coronary (artery)(vein): embolism occlusion thromboembolism not resulting in myocardial infarction Excl.: specified as chronic or with a stated duration of more than 4 weeks (more than 28 days) from onset (I25.8) 	`,`	null	`],
	[`	I24.1	`,`	Dressler syndrome Postmyocardial infarction syndrome 	`,`	null	`],
	[`	I24.8	`,`	Other forms of acute ischaemic heart disease Coronary: failure insufficiency 	`,`	null	`],
	[`	I24.9	`,`	Acute ischaemic heart disease, unspecified Excl.: ischaemic heart disease (chronic) NOS (I25.9) 	`,`	null	`],
	[`	I25	`,`	Chronic ischaemic heart disease Excl.: cardiovascular disease NOS (I51.6) 	`,`	null	`],
	[`	I25.0	`,`	Atherosclerotic cardiovascular disease, so described 	`,`	null	`],
	[`	I25.1	`,`	Atherosclerotic heart disease Coronary (artery): atheroma atherosclerosis disease sclerosis 	`,`	null	`],
	[`	I25.2	`,`	Old myocardial infarction Healed myocardial infarction Past myocardial infarction diagnosed by ECG or other special investigation, but currently presenting no symptoms 	`,`	null	`],
	[`	I25.3	`,`	Aneurysm of heart Aneurysm: mural ventricular 	`,`	null	`],
	[`	I25.4	`,`	Coronary artery aneurysm Coronary arteriovenous fistula, acquired Excl.: congenital coronary (artery) aneurysm (Q24.5) 	`,`	null	`],
	[`	I25.5	`,`	Ischaemic cardiomyopathy 	`,`	null	`],
	[`	I25.6	`,`	Silent myocardial ischaemia 	`,`	null	`],
	[`	I25.8	`,`	Other forms of chronic ischaemic heart disease Any condition in I21-I22 and I24.- specified as chronic or with a stated duration of more than 4 weeks (more than 28 days) from onset 	`,`	null	`],
	[`	I25.9	`,`	Chronic ischaemic heart disease, unspecified Ischaemic heart disease (chronic) NOS 	`,`	null	`],
	[`	I26	`,`	Pulmonary embolism Incl.: pulmonary (artery)(vein): infarction thromboembolism thrombosis Excl.: complicating: abortion or ectopic or molar pregnancy (O00-O07, O08.2) pregnancy, childbirth and the puerperium (O88.-) 	`,`	null	`],
	[`	I26.0	`,`	Pulmonary embolism with mention of acute cor pulmonale Acute cor pulmonale NOS 	`,`	null	`],
	[`	I26.9	`,`	Pulmonary embolism without mention of acute cor pulmonale Pulmonary embolism NOS 	`,`	null	`],
	[`	I27	`,`	Other pulmonary heart diseases 	`,`	null	`],
	[`	I27.0	`,`	Primary pulmonary hypertension 	`,`	null	`],
	[`	I27.1	`,`	Kyphoscoliotic heart disease 	`,`	null	`],
	[`	I27.2	`,`	Other secondary pulmonary hypertension Use additional code, if desired, to identify the underlying disease. 	`,`	null	`],
	[`	I27.8	`,`	Other specified pulmonary heart diseases Excl.: Eisenmenger defect (Q21.8) 	`,`	null	`],
	[`	I27.9	`,`	Pulmonary heart disease, unspecified Chronic cardiopulmonary disease Cor pulmonale (chronic) NOS 	`,`	null	`],
	[`	I28	`,`	Other diseases of pulmonary vessels 	`,`	null	`],
	[`	I28.0	`,`	Arteriovenous fistula of pulmonary vessels 	`,`	null	`],
	[`	I28.1	`,`	Aneurysm of pulmonary artery 	`,`	null	`],
	[`	I28.8	`,`	Other specified diseases of pulmonary vessels Rupture Stenosis Stricture of pulmonary vessel 	`,`	null	`],
	[`	I28.9	`,`	Disease of pulmonary vessels, unspecified 	`,`	null	`],
	[`	I30	`,`	Acute pericarditis Incl.: acute pericardial effusion Excl.: rheumatic pericarditis (acute) (I01.0) 	`,`	null	`],
	[`	I30.0	`,`	Acute nonspecific idiopathic pericarditis 	`,`	null	`],
	[`	I30.1	`,`	Infective pericarditis Pericarditis: pneumococcal purulent staphylococcal streptococcal viral Pyopericarditis Use additional code (B95-B98), if desired, to identify infectious agent. 	`,`	null	`],
	[`	I30.8	`,`	Other forms of acute pericarditis 	`,`	null	`],
	[`	I30.9	`,`	Acute pericarditis, unspecified 	`,`	null	`],
	[`	I31	`,`	Other diseases of pericardium Excl.: current complications following acute myocardial infarction (I23.-) postcardiotomy syndrome (I97.0) trauma (S26.-) when specified as rheumatic (I09.2) 	`,`	null	`],
	[`	I31.0	`,`	Chronic adhesive pericarditis Accretio cordis Adherent pericardium Adhesive mediastinopericarditis 	`,`	null	`],
	[`	I31.1	`,`	Chronic constrictive pericarditis Concretio cordis Pericardial calcification 	`,`	null	`],
	[`	I31.2	`,`	Haemopericardium, not elsewhere classified 	`,`	null	`],
	[`	I31.3	`,`	Pericardial effusion (noninflammatory) Chylopericardium 	`,`	null	`],
	[`	I31.8	`,`	Other specified diseases of pericardium Epicardial plaques Focal pericardial adhesions 	`,`	null	`],
	[`	I31.9	`,`	Disease of pericardium, unspecified Cardiac tamponade Pericarditis (chronic) NOS 	`,`	null	`],
	[`	I32*	`,`	Pericarditis in diseases classified elsewhere 	`,`	null	`],
	[`	I32.0*	`,`	Pericarditis in bacterial diseases classified elsewhere Pericarditis: gonococcal (A54.8) meningococcal (A39.5) syphilitic (A52.0) tuberculous (A18.8) 	`,`	null	`],
	[`	I32.1*	`,`	Pericarditis in other infectious and parasitic diseases classified elsewhere 	`,`	null	`],
	[`	I32.8*	`,`	Pericarditis in other diseases classified elsewhere Pericarditis (in): rheumatoid (M05.3) systemic lupus erythematosus (M32.1) uraemic (N18.-) 	`,`	null	`],
	[`	I33	`,`	Acute and subacute endocarditis Excl.: acute rheumatic endocarditis (I01.1) endocarditis NOS (I38) 	`,`	null	`],
	[`	I33.0	`,`	Acute and subacute infective endocarditis Endocarditis (acute)(subacute): bacterial infective NOS lenta malignant septic ulcerative Use additional code (B95-B98), if desired, to identify infectious agent. 	`,`	null	`],
	[`	I33.9	`,`	Acute endocarditis, unspecified Endocarditis Myoendocarditis Periendocarditis acute or subacute 	`,`	null	`],
	[`	I34	`,`	Nonrheumatic mitral valve disorders Excl.: mitral (valve): disease (I05.9) failure (I05.8) stenosis (I05.0) when of unspecified cause but with mention of: diseases of aortic valve (I08.0) mitral stenosis or obstruction (I05.0) when specified as congenital (Q23.2, Q23.3) when specified as rheumatic (I05.-) 	`,`	null	`],
	[`	I34.0	`,`	Mitral (valve) insufficiency Mitral (valve): incompetence regurgitation NOS or of specified cause, except rheumatic 	`,`	null	`],
	[`	I34.1	`,`	Mitral (valve) prolapse Floppy mitral valve syndrome Excl.: Marfan syndrome (Q87.4) 	`,`	null	`],
	[`	I34.2	`,`	Nonrheumatic mitral (valve) stenosis 	`,`	null	`],
	[`	I34.8	`,`	Other nonrheumatic mitral valve disorders 	`,`	null	`],
	[`	I34.9	`,`	Nonrheumatic mitral valve disorder, unspecified 	`,`	null	`],
	[`	I35	`,`	Nonrheumatic aortic valve disorders Excl.: hypertrophic subaortic stenosis (I42.1) when of unspecified cause but with mention of diseases of mitral valve (I08.0) when specified as congenital (Q23.0, Q23.1) when specified as rheumatic (I06.-) 	`,`	null	`],
	[`	I35.0	`,`	Aortic (valve) stenosis 	`,`	null	`],
	[`	I35.1	`,`	Aortic (valve) insufficiency Aortic (valve): incompetence regurgitation NOS or of specified cause, except rheumatic 	`,`	null	`],
	[`	I35.2	`,`	Aortic (valve) stenosis with insufficiency 	`,`	null	`],
	[`	I35.8	`,`	Other aortic valve disorders 	`,`	null	`],
	[`	I35.9	`,`	Aortic valve disorder, unspecified 	`,`	null	`],
	[`	I36	`,`	Nonrheumatic tricuspid valve disorders Excl.: when of unspecified cause (I07.-) when specified as congenital (Q22.4, Q22.8, Q22.9) when specified as rheumatic (I07.-) 	`,`	null	`],
	[`	I36.0	`,`	Nonrheumatic tricuspid (valve) stenosis 	`,`	null	`],
	[`	I36.1	`,`	Nonrheumatic tricuspid (valve) insufficiency Tricuspid (valve): incompetence regurgitation of specified cause, except rheumatic 	`,`	null	`],
	[`	I36.2	`,`	Nonrheumatic tricuspid (valve) stenosis with insufficiency 	`,`	null	`],
	[`	I36.8	`,`	Other nonrheumatic tricuspid valve disorders 	`,`	null	`],
	[`	I36.9	`,`	Nonrheumatic tricuspid valve disorder, unspecified 	`,`	null	`],
	[`	I37	`,`	Pulmonary valve disorders Excl.: when specified as congenital (Q22.1, Q22.2, Q22.3) when specified as rheumatic (I09.8) 	`,`	null	`],
	[`	I37.0	`,`	Pulmonary valve stenosis 	`,`	null	`],
	[`	I37.1	`,`	Pulmonary valve insufficiency Pulmonary valve: incompetence regurgitation NOS or of specified cause, except rheumatic 	`,`	null	`],
	[`	I37.2	`,`	Pulmonary valve stenosis with insufficiency 	`,`	null	`],
	[`	I37.8	`,`	Other pulmonary valve disorders 	`,`	null	`],
	[`	I37.9	`,`	Pulmonary valve disorder, unspecified 	`,`	null	`],
	[`	I38	`,`	Endocarditis, valve unspecified Incl.: Endocarditis (chronic) NOS Valvular: incompetence insufficiency regurgitation stenosis Valvulitis (chronic) of unspecified valve NOS or of specified cause, except rheumatic or congenital Excl.: congenital insufficiency of cardiac valve NOS (Q24.8) congenital stenosis of cardiac valve NOS (Q24.8) endocardial fibroelastosis (I42.4) when specified as rheumatic (I09.1) 	`,`	null	`],
	[`	I39*	`,`	Endocarditis and heart valve disorders in diseases classified elsewhere Incl.: endocardial involvement in: candidal infection (B37.6) gonococcal infection (A54.8) Libman-Sacks disease (M32.1) meningococcal infection (A39.5) rheumatoid arthritis (M05.3) syphilis (A52.0) tuberculosis (A18.8) typhoid fever (A01.0) 	`,`	null	`],
	[`	I39.0*	`,`	Mitral valve disorders in diseases classified elsewhere 	`,`	null	`],
	[`	I39.1*	`,`	Aortic valve disorders in diseases classified elsewhere 	`,`	null	`],
	[`	I39.2*	`,`	Tricuspid valve disorders in diseases classified elsewhere 	`,`	null	`],
	[`	I39.3*	`,`	Pulmonary valve disorders in diseases classified elsewhere 	`,`	null	`],
	[`	I39.4*	`,`	Multiple valve disorders in diseases classified elsewhere 	`,`	null	`],
	[`	I39.8*	`,`	Endocarditis, valve unspecified, in diseases classified elsewhere 	`,`	null	`],
	[`	I40	`,`	Acute myocarditis 	`,`	null	`],
	[`	I40.0	`,`	Infective myocarditis Septic myocarditis Use additional code (B95-B98), if desired, to identify infectious agent. 	`,`	null	`],
	[`	I40.1	`,`	Isolated myocarditis 	`,`	null	`],
	[`	I40.8	`,`	Other acute myocarditis 	`,`	null	`],
	[`	I40.9	`,`	Acute myocarditis, unspecified 	`,`	null	`],
	[`	I41*	`,`	Myocarditis in diseases classified elsewhere 	`,`	null	`],
	[`	I41.0*	`,`	Myocarditis in bacterial diseases classified elsewhere Myocarditis: diphtheritic (A36.8) gonococcal (A54.8) meningococcal (A39.5) syphilitic (A52.0) tuberculous (A18.8) 	`,`	null	`],
	[`	I41.1*	`,`	Myocarditis in viral diseases classified elsewhere Influenzal myocarditis (acute) (J09, J10.8, J11.8) Mumps myocarditis (B26.8) 	`,`	null	`],
	[`	I41.2*	`,`	Myocarditis in other infectious and parasitic diseases classified elsewhere Myocarditis in: Chagas disease (chronic) (B57.2) acute (B57.0) toxoplasmosis (B58.8) 	`,`	null	`],
	[`	I41.8*	`,`	Myocarditis in other diseases classified elsewhere Rheumatoid myocarditis (M05.3) Sarcoid myocarditis (D86.8) 	`,`	null	`],
	[`	I42	`,`	Cardiomyopathy Excl.: cardiomyopathy complicating: pregnancy (O99.4) puerperium (O90.3) ischaemic cardiomyopathy (I25.5) 	`,`	null	`],
	[`	I42.0	`,`	Dilated cardiomyopathy Congestive cardiomyopathy 	`,`	null	`],
	[`	I42.1	`,`	Obstructive hypertrophic cardiomyopathy Hypertrophic subaortic stenosis 	`,`	null	`],
	[`	I42.2	`,`	Other hypertrophic cardiomyopathy Nonobstructive hypertrophic cardiomyopathy 	`,`	null	`],
	[`	I42.3	`,`	Endomyocardial (eosinophilic) disease Endomyocardial (tropical) fibrosis Loffler endocarditis 	`,`	null	`],
	[`	I42.4	`,`	Endocardial fibroelastosis Congenital cardiomyopathy 	`,`	null	`],
	[`	I42.5	`,`	Other restrictive cardiomyopathy Constrictive cardiomyopathy NOS 	`,`	null	`],
	[`	I42.6	`,`	Alcoholic cardiomyopathy 	`,`	null	`],
	[`	I42.7	`,`	Cardiomyopathy due to drugs and other external agents Use additional external cause code (Chapter XX), if desired, to identify cause. 	`,`	null	`],
	[`	I42.8	`,`	Other cardiomyopathies 	`,`	null	`],
	[`	I42.9	`,`	Cardiomyopathy, unspecified Cardiomyopathy (primary)(secondary) NOS 	`,`	null	`],
	[`	I43*	`,`	Cardiomyopathy in diseases classified elsewhere 	`,`	null	`],
	[`	I43.0*	`,`	Cardiomyopathy in infectious and parasitic diseases classified elsewhere Cardiomyopathy in diphtheria (A36.8) 	`,`	null	`],
	[`	I43.1*	`,`	Cardiomyopathy in metabolic diseases Cardiac amyloidosis (E85.-) 	`,`	null	`],
	[`	I43.2*	`,`	Cardiomyopathy in nutritional diseases Nutritional cardiomyopathy NOS (E63.9) 	`,`	null	`],
	[`	I43.8*	`,`	Cardiomyopathy in other diseases classified elsewhere Gouty tophi of heart (M10.0) Thyrotoxic heart disease (E05.9) 	`,`	null	`],
	[`	I44	`,`	Atrioventricular and left bundle-branch block 	`,`	null	`],
	[`	I44.0	`,`	Atrioventricular block, first degree 	`,`	null	`],
	[`	I44.1	`,`	Atrioventricular block, second degree Atrioventricular block, type I and II Mobitz block, type I and II Second-degree block, type I and II Wenckebach block 	`,`	null	`],
	[`	I44.2	`,`	Atrioventricular block, complete Complete heart block NOS Third-degree block 	`,`	null	`],
	[`	I44.3	`,`	Other and unspecified atrioventricular block Atrioventricular block NOS 	`,`	null	`],
	[`	I44.4	`,`	Left anterior fascicular block 	`,`	null	`],
	[`	I44.5	`,`	Left posterior fascicular block 	`,`	null	`],
	[`	I44.6	`,`	Other and unspecified fascicular block Left bundle-branch hemiblock NOS 	`,`	null	`],
	[`	I44.7	`,`	Left bundle-branch block, unspecified 	`,`	null	`],
	[`	I45	`,`	Other conduction disorders 	`,`	null	`],
	[`	I45.0	`,`	Right fascicular block 	`,`	null	`],
	[`	I45.1	`,`	Other and unspecified right bundle-branch block Right bundle-branch block NOS 	`,`	null	`],
	[`	I45.2	`,`	Bifascicular block 	`,`	null	`],
	[`	I45.3	`,`	Trifascicular block 	`,`	null	`],
	[`	I45.4	`,`	Nonspecific intraventricular block Bundle-branch block NOS 	`,`	null	`],
	[`	I45.5	`,`	Other specified heart block Sinoatrial block Sinoauricular block Excl.: heart block NOS (I45.9) 	`,`	null	`],
	[`	I45.6	`,`	Pre-excitation syndrome Anomalous atrioventricular excitation Atrioventricular conduction: accelerated accessory pre-excitation Lown-Ganong-Levine syndrome Wolff-Parkinson-White syndrome 	`,`	null	`],
	[`	I45.8	`,`	Other specified conduction disorders Atrioventricular [AV] dissociation Interference dissociation Long QT syndrome Excl.: prolongation of QT interval (R94.3) 	`,`	null	`],
	[`	I45.9	`,`	Conduction disorder, unspecified Heart block NOS Stokes-Adams syndrome 	`,`	null	`],
	[`	I46	`,`	Cardiac arrest Excl.: cardiogenic shock (R57.0) complicating: abortion or ectopic or molar pregnancy (O00-O07, O08.8) obstetric surgery and procedures (O75.4) 	`,`	null	`],
	[`	I46.0	`,`	Cardiac arrest with successful resuscitation 	`,`	null	`],
	[`	I46.1	`,`	Sudden cardiac death, so described Excl.: sudden death: NOS (R96.-) with: conduction disorder (I44-I45) myocardial infarction (I21-I22) 	`,`	null	`],
	[`	I46.9	`,`	Cardiac arrest, unspecified 	`,`	null	`],
	[`	I47	`,`	Paroxysmal tachycardia Excl.: complicating: abortion or ectopic or molar pregnancy (O00-O07, O08.8) obstetric surgery and procedures (O75.4) tachycardia: NOS (R00.0) sinoauricular NOS (R00.0) sinus [sinusal] NOS (R00.0) 	`,`	null	`],
	[`	I47.0	`,`	Re-entry ventricular arrhythmia 	`,`	null	`],
	[`	I47.1	`,`	Supraventricular tachycardia Tachycardia (paroxysmal): atrial atrioventricular [AV]: NOS re-entrant (nodal) [AVNRT] [AVRT] junctional nodal 	`,`	null	`],
	[`	I47.2	`,`	Ventricular tachycardia 	`,`	null	`],
	[`	I47.9	`,`	Paroxysmal tachycardia, unspecified Bouveret(-Hoffmann) syndrome 	`,`	null	`],
	[`	I48	`,`	Atrial fibrillation and flutter 	`,`	null	`],
	[`	I48.0	`,`	Paroxysmal atrial fibrillation 	`,`	null	`],
	[`	I48.1	`,`	Persistent atrial fibrillation 	`,`	null	`],
	[`	I48.2	`,`	Chronic atrial fibrillation 	`,`	null	`],
	[`	I48.3	`,`	Typical atrial flutter Type I atrial flutter 	`,`	null	`],
	[`	I48.4	`,`	Atypical atrial flutter Type II atrial flutter 	`,`	null	`],
	[`	I48.9	`,`	Atrial fibrillation and atrial flutter, unspecified 	`,`	null	`],
	[`	I49	`,`	Other cardiac arrhythmias Excl.: bradycardia: NOS (R00.1) sinoatrial (R00.1) sinus (R00.1) vagal (R00.1) complicating: abortion or ectopic or molar pregnancy (O00-O07, O08.8) obstetric surgery and procedures (O75.4) neonatal cardiac dysrhythmia (P29.1) 	`,`	null	`],
	[`	I49.0	`,`	Ventricular fibrillation and flutter 	`,`	null	`],
	[`	I49.1	`,`	Atrial premature depolarization Atrial premature beats 	`,`	null	`],
	[`	I49.2	`,`	Junctional premature depolarization 	`,`	null	`],
	[`	I49.3	`,`	Ventricular premature depolarization 	`,`	null	`],
	[`	I49.4	`,`	Other and unspecified premature depolarization Ectopic beats Extrasystoles Extrasystolic arrhythmias Premature: beats NOS contractions 	`,`	null	`],
	[`	I49.5	`,`	Sick sinus syndrome Tachycardia-bradycardia syndrome 	`,`	null	`],
	[`	I49.8	`,`	Other specified cardiac arrhythmias Rhythm disorder: coronary sinus ectopic nodal 	`,`	null	`],
	[`	I49.9	`,`	Cardiac arrhythmia, unspecified Arrhythmia (cardiac) NOS 	`,`	null	`],
	[`	I50	`,`	Heart failure Excl.: complicating: abortion or ectopic or molar pregnancy (O00-O07, O08.8) obstetric surgery and procedures (O75.4) due to hypertension (I11.0) with renal disease (I13.-) following cardiac surgery or due to presence of cardiac prosthesis (I97.1) neonatal cardiac failure (P29.0) 	`,`	null	`],
	[`	I50.0	`,`	Congestive heart failure Congestive heart disease Right ventricular failure (secondary to left heart failure) 	`,`	null	`],
	[`	I50.1	`,`	Left ventricular failure Cardiac asthma Left heart failure Oedema of lung Pulmonary oedema with mention of heart disease NOS or heart failure 	`,`	null	`],
	[`	I50.9	`,`	Heart failure, unspecified Cardiac, heart or myocardial failure NOS 	`,`	null	`],
	[`	I51	`,`	Complications and ill-defined descriptions of heart disease Excl.: any condition in I51.4-I51.9 due to hypertension (I11.-) any condition in I51.4-I51.9 due to hypertension with renal disease (I13.-) complications following acute myocardial infarction (I23.-) when specified as rheumatic (I00-I09) 	`,`	null	`],
	[`	I51.0	`,`	Cardiac septal defect, acquired Acquired septal defect (old): atrial auricular ventricular 	`,`	null	`],
	[`	I51.1	`,`	Rupture of chordae tendineae, not elsewhere classified 	`,`	null	`],
	[`	I51.2	`,`	Rupture of papillary muscle, not elsewhere classified 	`,`	null	`],
	[`	I51.3	`,`	Intracardiac thrombosis, not elsewhere classified Thrombosis (old): apical atrial auricular ventricular 	`,`	null	`],
	[`	I51.4	`,`	Myocarditis, unspecified Myocardial fibrosis Myocarditis: NOS chronic (interstitial) 	`,`	null	`],
	[`	I51.5	`,`	Myocardial degeneration Degeneration of heart or myocardium: fatty senile Myocardial disease 	`,`	null	`],
	[`	I51.6	`,`	Cardiovascular disease, unspecified Cardiovascular accident NOS Excl.: atherosclerotic cardiovascular disease, so described (I25.0) 	`,`	null	`],
	[`	I51.7	`,`	Cardiomegaly Cardiac: dilatation hypertrophy Ventricular dilatation 	`,`	null	`],
	[`	I51.8	`,`	Other ill-defined heart diseases Carditis (acute)(chronic) Pancarditis (acute)(chronic) 	`,`	null	`],
	[`	I51.9	`,`	Heart disease, unspecified 	`,`	null	`],
	[`	I52*	`,`	Other heart disorders in diseases classified elsewhere Excl.: cardiovascular disorders NOS in diseases classified elsewhere (I98.-*) 	`,`	null	`],
	[`	I52.0*	`,`	Other heart disorders in bacterial diseases classified elsewhere Meningococcal carditis NEC (A39.5) 	`,`	null	`],
	[`	I52.1*	`,`	Other heart disorders in other infectious and parasitic diseases classified elsewhere Pulmonary heart disease in schistosomiasis (B65.-) 	`,`	null	`],
	[`	I52.8*	`,`	Other heart disorders in other diseases classified elsewhere Rheumatoid carditis (M05.3) 	`,`	null	`],
	[`	I60	`,`	Subarachnoid haemorrhage Incl.: ruptured cerebral aneurysm Excl.: sequelae of subarachnoid haemorrhage (I69.0) 	`,`	null	`],
	[`	I60.0	`,`	Subarachnoid haemorrhage from carotid siphon and bifurcation 	`,`	null	`],
	[`	I60.1	`,`	Subarachnoid haemorrhage from middle cerebral artery 	`,`	null	`],
	[`	I60.2	`,`	Subarachnoid haemorrhage from anterior communicating artery 	`,`	null	`],
	[`	I60.3	`,`	Subarachnoid haemorrhage from posterior communicating artery 	`,`	null	`],
	[`	I60.4	`,`	Subarachnoid haemorrhage from basilar artery 	`,`	null	`],
	[`	I60.5	`,`	Subarachnoid haemorrhage from vertebral artery 	`,`	null	`],
	[`	I60.6	`,`	Subarachnoid haemorrhage from other intracranial arteries Multiple involvement of intracranial arteries 	`,`	null	`],
	[`	I60.7	`,`	Subarachnoid haemorrhage from intracranial artery, unspecified Ruptured (congenital) berry aneurysm NOS Subarachnoid haemorrhage from: cerebral communicating artery NOS 	`,`	null	`],
	[`	I60.8	`,`	Other subarachnoid haemorrhage Meningeal haemorrhage Rupture of cerebral arteriovenous malformation 	`,`	null	`],
	[`	I60.9	`,`	Subarachnoid haemorrhage, unspecified Ruptured (congenital) cerebral aneurysm NOS 	`,`	null	`],
	[`	I61	`,`	Intracerebral haemorrhage Excl.: sequelae of intracerebral haemorrhage (I69.1) 	`,`	null	`],
	[`	I61.0	`,`	Intracerebral haemorrhage in hemisphere, subcortical Deep intracerebral haemorrhage 	`,`	null	`],
	[`	I61.1	`,`	Intracerebral haemorrhage in hemisphere, cortical Cerebral lobe haemorrhage Superficial intracerebral haemorrhage 	`,`	null	`],
	[`	I61.2	`,`	Intracerebral haemorrhage in hemisphere, unspecified 	`,`	null	`],
	[`	I61.3	`,`	Intracerebral haemorrhage in brain stem 	`,`	null	`],
	[`	I61.4	`,`	Intracerebral haemorrhage in cerebellum 	`,`	null	`],
	[`	I61.5	`,`	Intracerebral haemorrhage, intraventricular 	`,`	null	`],
	[`	I61.6	`,`	Intracerebral haemorrhage, multiple localized 	`,`	null	`],
	[`	I61.8	`,`	Other intracerebral haemorrhage 	`,`	null	`],
	[`	I61.9	`,`	Intracerebral haemorrhage, unspecified 	`,`	null	`],
	[`	I62	`,`	Other nontraumatic intracranial haemorrhage Excl.: sequelae of intracranial haemorrhage (I69.2) 	`,`	null	`],
	[`	I62.0	`,`	Subdural haemorrhage (acute)(nontraumatic) 	`,`	null	`],
	[`	I62.1	`,`	Nontraumatic extradural haemorrhage Nontraumatic epidural haemorrhage 	`,`	null	`],
	[`	I62.9	`,`	Intracranial haemorrhage (nontraumatic), unspecified 	`,`	null	`],
	[`	I63	`,`	Cerebral infarction Incl.: occlusion and stenosis of cerebral and precerebral arteries, resulting in cerebral infarction Excl.: sequelae of cerebral infarction (I69.3) 	`,`	null	`],
	[`	I63.0	`,`	Cerebral infarction due to thrombosis of precerebral arteries 	`,`	null	`],
	[`	I63.1	`,`	Cerebral infarction due to embolism of precerebral arteries 	`,`	null	`],
	[`	I63.2	`,`	Cerebral infarction due to unspecified occlusion or stenosis of precerebral arteries 	`,`	null	`],
	[`	I63.3	`,`	Cerebral infarction due to thrombosis of cerebral arteries 	`,`	null	`],
	[`	I63.4	`,`	Cerebral infarction due to embolism of cerebral arteries 	`,`	null	`],
	[`	I63.5	`,`	Cerebral infarction due to unspecified occlusion or stenosis of cerebral arteries 	`,`	null	`],
	[`	I63.6	`,`	Cerebral infarction due to cerebral venous thrombosis, nonpyogenic 	`,`	null	`],
	[`	I63.8	`,`	Other cerebral infarction 	`,`	null	`],
	[`	I63.9	`,`	Cerebral infarction, unspecified 	`,`	null	`],
	[`	I64	`,`	Stroke, not specified as haemorrhage or infarction Incl.: Cerebrovascular accident NOS Excl.: sequelae of stroke (I69.4) 	`,`	null	`],
	[`	I65	`,`	Occlusion and stenosis of precerebral arteries, not resulting in cerebral infarction Incl.: embolism narrowing obstruction (complete)(partial) thrombosis of basilar, carotid or vertebral arteries, not resulting in cerebral infarction Excl.: when causing cerebral infarction (I63.-) 	`,`	null	`],
	[`	I65.0	`,`	Occlusion and stenosis of vertebral artery 	`,`	null	`],
	[`	I65.1	`,`	Occlusion and stenosis of basilar artery 	`,`	null	`],
	[`	I65.2	`,`	Occlusion and stenosis of carotid artery 	`,`	null	`],
	[`	I65.3	`,`	Occlusion and stenosis of multiple and bilateral precerebral arteries 	`,`	null	`],
	[`	I65.8	`,`	Occlusion and stenosis of other precerebral artery 	`,`	null	`],
	[`	I65.9	`,`	Occlusion and stenosis of unspecified precerebral artery Precerebral artery NOS 	`,`	null	`],
	[`	I66	`,`	Occlusion and stenosis of cerebral arteries, not resulting in cerebral infarction Incl.: embolism narrowing obstruction (complete)(partial) thrombosis of middle, anterior and posterior cerebral arteries, and cerebellar arteries, not resulting in cerebral infarction Excl.: when causing cerebral infarction (I63.-) 	`,`	null	`],
	[`	I66.0	`,`	Occlusion and stenosis of middle cerebral artery 	`,`	null	`],
	[`	I66.1	`,`	Occlusion and stenosis of anterior cerebral artery 	`,`	null	`],
	[`	I66.2	`,`	Occlusion and stenosis of posterior cerebral artery 	`,`	null	`],
	[`	I66.3	`,`	Occlusion and stenosis of cerebellar arteries 	`,`	null	`],
	[`	I66.4	`,`	Occlusion and stenosis of multiple and bilateral cerebral arteries I66.8 Occlusion and stenosis of other cerebral artery Occlusion and stenosis of perforating arteries 	`,`	null	`],
	[`	I66.9	`,`	Occlusion and stenosis of unspecified cerebral artery 	`,`	null	`],
	[`	I67	`,`	Other cerebrovascular diseases Excl.: sequelae of the listed conditions (I69.8) 	`,`	null	`],
	[`	I67.0	`,`	Dissection of cerebral arteries, nonruptured Excl.: ruptured cerebral arteries (I60.7) 	`,`	null	`],
	[`	I67.1	`,`	Cerebral aneurysm, nonruptured Cerebral: aneurysm NOS arteriovenous fistula, acquired Excl.: congenital cerebral aneurysm, nonruptured (Q28.-) ruptured cerebral aneurysm (I60.-) 	`,`	null	`],
	[`	I67.2	`,`	Cerebral atherosclerosis Atheroma of cerebral arteries 	`,`	null	`],
	[`	I67.3	`,`	Progressive vascular leukoencephalopathy Binswanger disease Excl.: subcortical vascular dementia (F01.2) 	`,`	null	`],
	[`	I67.4	`,`	Hypertensive encephalopathy 	`,`	null	`],
	[`	I67.5	`,`	Moyamoya disease 	`,`	null	`],
	[`	I67.6	`,`	Nonpyogenic thrombosis of intracranial venous system Nonpyogenic thrombosis of: cerebral vein intracranial venous sinus Excl.: when causing infarction (I63.6) 	`,`	null	`],
	[`	I67.7	`,`	Cerebral arteritis, not elsewhere classified 	`,`	null	`],
	[`	I67.8	`,`	Other specified cerebrovascular diseases Acute cerebrovascular insufficiency NOS Cerebral ischaemia (chronic) 	`,`	null	`],
	[`	I67.9	`,`	Cerebrovascular disease, unspecified 	`,`	null	`],
	[`	I68*	`,`	Cerebrovascular disorders in diseases classified elsewhere 	`,`	null	`],
	[`	I68.0*	`,`	Cerebral amyloid angiopathy (E85.-) 	`,`	null	`],
	[`	I68.1*	`,`	Cerebral arteritis in infectious and parasitic diseases classified elsewhere Cerebral arteritis: listerial (A32.8) syphilitic (A52.0) tuberculous (A18.8) 	`,`	null	`],
	[`	I68.2*	`,`	Cerebral arteritis in other diseases classified elsewhere Cerebral arteritis in systemic lupus erythematosus (M32.1) 	`,`	null	`],
	[`	I68.8*	`,`	Other cerebrovascular disorders in diseases classified elsewhere Uraemic apoplexia in chronic kidney disease (N18.5) 	`,`	null	`],
	[`	I69	`,`	Sequelae of cerebrovascular disease Note: Category I69 is to be used to indicate conditions in I60-I67.1 and I67.4-I67.9 as the cause of sequelae, themselves classified elsewhere. The "sequelae" include conditions specified as such or as late effects, or those present one year or more after onset of the causal condition. Not to be used for chronic cerebrovascular disease. Code these to I60-I67. 	`,`	null	`],
	[`	I69.0	`,`	Sequelae of subarachnoid haemorrhage 	`,`	null	`],
	[`	I69.1	`,`	Sequelae of intracerebral haemorrhage 	`,`	null	`],
	[`	I69.2	`,`	Sequelae of other nontraumatic intracranial haemorrhage 	`,`	null	`],
	[`	I69.3	`,`	Sequelae of cerebral infarction 	`,`	null	`],
	[`	I69.4	`,`	Sequelae of stroke, not specified as haemorrhage or infarction 	`,`	null	`],
	[`	I69.8	`,`	Sequelae of other and unspecified cerebrovascular diseases 	`,`	null	`],
	[`	I70	`,`	Atherosclerosis Incl.: arteriolosclerosis arteriosclerosis arteriosclerotic vascular disease atheroma degeneration: arterial arteriovascular vascular endarteritis deformans or obliterans senile: arteritis endarteritis Excl.: cerebral (I67.2) coronary (I25.1) mesenteric (K55.1) pulmonary (I27.0) The following supplementary classification to indicate the presence or absence of gangrene is provided for optional use with appropriate subcategories in I70. 	`,`	null	`],
	[`	0	`,`	without gangrene 	`,`	null	`],
	[`	1	`,`	with gangrene 	`,`	null	`],
	[`	I70.0	`,`	Atherosclerosis of aorta 	`,`	null	`],
	[`	I70.1	`,`	Atherosclerosis of renal artery Goldblatt kidney Excl.: atherosclerosis of renal arterioles (I12.-) 	`,`	null	`],
	[`	I70.2	`,`	Atherosclerosis of arteries of extremities Atherosclerotic gangrene Monckeberg (medial) sclerosis 	`,`	null	`],
	[`	I70.8	`,`	Atherosclerosis of other arteries 	`,`	null	`],
	[`	I70.9	`,`	Generalized and unspecified atherosclerosis 	`,`	null	`],
	[`	I71	`,`	Aortic aneurysm and dissection 	`,`	null	`],
	[`	I71.0	`,`	Dissection of aorta [any part] Dissecting aneurysm of aorta (ruptured) [any part] 	`,`	null	`],
	[`	I71.1	`,`	Thoracic aortic aneurysm, ruptured 	`,`	null	`],
	[`	I71.2	`,`	Thoracic aortic aneurysm, without mention of rupture 	`,`	null	`],
	[`	I71.3	`,`	Abdominal aortic aneurysm, ruptured 	`,`	null	`],
	[`	I71.4	`,`	Abdominal aortic aneurysm, without mention of rupture 	`,`	null	`],
	[`	I71.5	`,`	Thoracoabdominal aortic aneurysm, ruptured 	`,`	null	`],
	[`	I71.6	`,`	Thoracoabdominal aortic aneurysm, without mention of rupture 	`,`	null	`],
	[`	I71.8	`,`	Aortic aneurysm of unspecified site, ruptured Rupture of aorta NOS 	`,`	null	`],
	[`	I71.9	`,`	Aortic aneurysm of unspecified site, without mention of rupture Aneurysm Dilatation Hyaline necrosis of aorta 	`,`	null	`],
	[`	I72	`,`	Other aneurysm and dissection Incl.: aneurysm (cirsoid)(false)(ruptured) Excl.: aneurysm (of): aorta (I71.-) arteriovenous NOS (Q27.3) arteriovenous NOS acquired (I77.0) cerebral (nonruptured) (I67.1) cerebral (nonruptured) ruptured (I60.-) coronary (I25.4) heart (I25.3) pulmonary artery (I28.1) retinal (H35.0) varicose (I77.0) dissection of precerebral artery, congenital (nonruptured) (Q28.1) 	`,`	null	`],
	[`	I72.0	`,`	Aneurysm and dissection of carotid artery 	`,`	null	`],
	[`	I72.1	`,`	Aneurysm and dissection of artery of upper extremity 	`,`	null	`],
	[`	I72.2	`,`	Aneurysm and dissection of renal artery 	`,`	null	`],
	[`	I72.3	`,`	Aneurysm and dissection of iliac artery 	`,`	null	`],
	[`	I72.4	`,`	Aneurysm and dissection of artery of lower extremity 	`,`	null	`],
	[`	I72.5	`,`	Aneurysm and dissection of other precerebral arteries Aneurysm and dissection of basilar artery (trunk) Excl.: aneurysm and dissection of : carotid artery (I72.0) vertebral artery (I72.6) 	`,`	null	`],
	[`	I72.6	`,`	Aneurysm and dissection of vertebral artery 	`,`	null	`],
	[`	I72.8	`,`	Aneurysm and dissection of other specified arteries 	`,`	null	`],
	[`	I72.9	`,`	Aneurysm and dissection of unspecified site 	`,`	null	`],
	[`	I73	`,`	Other peripheral vascular diseases Excl.: chilblains (T69.1) frostbite (T33-T35) immersion hand or foot (T69.0) spasm of cerebral artery (G45.9) 	`,`	null	`],
	[`	I73.0	`,`	Raynaud syndrome Raynaud: disease gangrene phenomenon (secondary) 	`,`	null	`],
	[`	I73.1	`,`	Thromboangiitis obliterans [Buerger] I73.8 Other specified peripheral vascular diseases Acrocyanosis Acroparaesthesia: simple [Schultze type] vasomotor [Nothnagel type] Erythrocyanosis Erythromelalgia 	`,`	null	`],
	[`	I73.9	`,`	Peripheral vascular disease, unspecified Intermittent claudication Spasm of artery 	`,`	null	`],
	[`	I74	`,`	Arterial embolism and thrombosis Incl.: infarction: embolic thrombotic occlusion: embolic thrombotic Excl.: embolism and thrombosis: basilar (I63.0-I63.2, I65.1) carotid (I63.0-I63.2, I65.2) cerebral (I63.3-I63.5, I66.9) complicating: abortion or ectopic or molar pregnancy (O00-O07, O08.2) pregnancy, childbirth and the puerperium (O88.-) coronary (I21-I25) mesenteric (K55.0) precerebral (I63.0-I63.2, I65.9) pulmonary (I26.-) renal (N28.0) retinal (H34.-) vertebral (I63.0-I63.2, I65.0) 	`,`	null	`],
	[`	I74.0	`,`	Embolism and thrombosis of abdominal aorta Aortic bifurcation syndrome Leriche syndrome 	`,`	null	`],
	[`	I74.1	`,`	Embolism and thrombosis of other and unspecified parts of aorta 	`,`	null	`],
	[`	I74.2	`,`	Embolism and thrombosis of arteries of upper extremities 	`,`	null	`],
	[`	I74.3	`,`	Embolism and thrombosis of arteries of lower extremities 	`,`	null	`],
	[`	I74.4	`,`	Embolism and thrombosis of arteries of extremities, unspecified Peripheral arterial embolism 	`,`	null	`],
	[`	I74.5	`,`	Embolism and thrombosis of iliac artery 	`,`	null	`],
	[`	I74.8	`,`	Embolism and thrombosis of other arteries 	`,`	null	`],
	[`	I74.9	`,`	Embolism and thrombosis of unspecified artery 	`,`	null	`],
	[`	I77	`,`	Other disorders of arteries and arterioles Excl.: collagen (vascular) diseases (M30-M36) hypersensitivity angiitis (M31.0) pulmonary artery (I28.-) 	`,`	null	`],
	[`	I77.0	`,`	Arteriovenous fistula, acquired Aneurysmal varix Arteriovenous aneurysm, acquired Excl.: arteriovenous aneurysm NOS (Q27.3) cerebral (I67.1) coronary (I25.4) traumatic - see injury of blood vessel by body region. 	`,`	null	`],
	[`	I77.1	`,`	Stricture of artery 	`,`	null	`],
	[`	I77.2	`,`	Rupture of artery Fistula of artery Excl.: traumatic rupture of artery - see injury of blood vessel by body region. 	`,`	null	`],
	[`	I77.3	`,`	Arterial fibromuscular dysplasia 	`,`	null	`],
	[`	I77.4	`,`	Coeliac artery compression syndrome 	`,`	null	`],
	[`	I77.5	`,`	Necrosis of artery 	`,`	null	`],
	[`	I77.6	`,`	Arteritis, unspecified Aortitis NOS Endarteritis NOS Excl.: arteritis or endarteritis: aortic arch [Takayasu] (M31.4) cerebral NEC (I67.7) coronary (I25.8) deformans (I70.-) giant cell (M31.5-M31.6) obliterans (I70.-) senile (I70.-) 	`,`	null	`],
	[`	I77.8	`,`	Other specified disorders of arteries and arterioles Erosion Ulcer of artery 	`,`	null	`],
	[`	I77.9	`,`	Disorder of arteries and arterioles, unspecified 	`,`	null	`],
	[`	I78	`,`	Diseases of capillaries 	`,`	null	`],
	[`	I78.0	`,`	Hereditary haemorrhagic telangiectasia Rendu-Osler-Weber disease 	`,`	null	`],
	[`	I78.1	`,`	Naevus, non-neoplastic Naevus: araneus spider stellar Excl.: naevus: NOS (D22.-) blue (D22.-) flammeus (Q82.5) hairy (D22.-) melanocytic (D22.-) pigmented (D22.-) portwine (Q82.5) sanguineous (Q82.5) strawberry (Q82.5) vascular NOS (Q82.5) verrucous (Q82.5) 	`,`	null	`],
	[`	I78.8	`,`	Other diseases of capillaries 	`,`	null	`],
	[`	I78.9	`,`	Disease of capillaries, unspecified 	`,`	null	`],
	[`	I79*	`,`	Disorders of arteries, arterioles and capillaries in diseases classified elsewhere 	`,`	null	`],
	[`	I79.0*	`,`	Aneurysm of aorta in diseases classified elsewhere Syphilitic aneurysm of aorta (A52.0) 	`,`	null	`],
	[`	I79.1*	`,`	Aortitis in diseases classified elsewhere Syphilitic aortitis (A52.0) 	`,`	null	`],
	[`	I79.2*	`,`	Peripheral angiopathy in diseases classified elsewhere Diabetic peripheral angiopathy (E10-E14 with common fourth character .5) 	`,`	null	`],
	[`	I79.8*	`,`	Other disorders of arteries, arterioles and capillaries in diseases classified elsewhere 	`,`	null	`],
	[`	I80	`,`	Phlebitis and thrombophlebitis Incl.: endophlebitis inflammation, vein periphlebitis suppurative phlebitis Use additional external cause code (Chapter XX), if desired, to identify drug, if drug-induced. Excl.: phlebitis and thrombophlebitis (of): complicating: abortion or ectopic or molar pregnancy (O00-O07, O08.7) pregnancy, childbirth and the puerperium (O22.-, O87.-) intracranial and intraspinal, septic or NOS (G08) intracranial, nonpyogenic (I67.6) intraspinal, nonpyogenic (G95.1) portal (vein) (K75.1) postphlebitic syndrome (I87.0) thrombophlebitis migrans (I82.1) 	`,`	null	`],
	[`	I80.0	`,`	Phlebitis and thrombophlebitis of superficial vessels of lower extremities 	`,`	null	`],
	[`	I80.1	`,`	Phlebitis and thrombophlebitis of femoral vein 	`,`	null	`],
	[`	I80.2	`,`	Phlebitis and thrombophlebitis of other deep vessels of lower extremities Deep vein thrombosis NOS 	`,`	null	`],
	[`	I80.3	`,`	Phlebitis and thrombophlebitis of lower extremities, unspecified Embolism or thrombosis of lower extremity NOS 	`,`	null	`],
	[`	I80.8	`,`	Phlebitis and thrombophlebitis of other sites 	`,`	null	`],
	[`	I80.9	`,`	Phlebitis and thrombophlebitis of unspecified site 	`,`	null	`],
	[`	I81	`,`	Portal vein thrombosis Incl.: Portal (vein) obstruction Excl.: phlebitis of portal vein (K75.1) 	`,`	null	`],
	[`	I82	`,`	Other venous embolism and thrombosis Excl.: venous embolism and thrombosis (of): cerebral (I63.6, I67.6) complicating: abortion or ectopic or molar pregnancy (O00-O07, O08.7) pregnancy, childbirth and the puerperium (O22.-, O87.-) coronary (I21-I25) intracranial and intraspinal, septic or NOS (G08) intracranial, nonpyogenic (I67.6) intraspinal, nonpyogenic (G95.1) lower extremities (I80.-) mesenteric (K55.0) portal (I81) pulmonary (I26.-) 	`,`	null	`],
	[`	I82.0	`,`	Budd-Chiari syndrome 	`,`	null	`],
	[`	I82.1	`,`	Thrombophlebitis migrans 	`,`	null	`],
	[`	I82.2	`,`	Embolism and thrombosis of vena cava 	`,`	null	`],
	[`	I82.3	`,`	Embolism and thrombosis of renal vein 	`,`	null	`],
	[`	I82.8	`,`	Embolism and thrombosis of other specified veins 	`,`	null	`],
	[`	I82.9	`,`	Embolism and thrombosis of unspecified vein Embolism of vein NOS Thrombosis (vein) NOS 	`,`	null	`],
	[`	I83	`,`	Varicose veins of lower extremities Excl.: complicating: pregnancy (O22.0) puerperium (O87.8) 	`,`	null	`],
	[`	I83.0	`,`	Varicose veins of lower extremities with ulcer Any condition in I83.9 with ulcer or specified as ulcerated Varicose ulcer (lower extremity, any part) 	`,`	null	`],
	[`	I83.1	`,`	Varicose veins of lower extremities with inflammation Any condition in I83.9 with inflammation or specified as inflamed Stasis dermatitis NOS 	`,`	null	`],
	[`	I83.2	`,`	Varicose veins of lower extremities with both ulcer and inflammation Any condition in I83.9 with both ulcer and inflammation 	`,`	null	`],
	[`	I83.9	`,`	Varicose veins of lower extremities without ulcer or inflammation Phlebectasia Varicose veins Varix of lower extremity [any part] or of unspecified site 	`,`	null	`],
	[`	I85	`,`	Oesophageal varices 	`,`	null	`],
	[`	I85.0	`,`	Oesophageal varices with bleeding 	`,`	null	`],
	[`	I85.9	`,`	Oesophageal varices without bleeding Oesophageal varices NOS 	`,`	null	`],
	[`	I86	`,`	Varicose veins of other sites Excl.: retinal varices (H35.0) varicose veins of unspecified site (I83.9) 	`,`	null	`],
	[`	I86.0	`,`	Sublingual varices 	`,`	null	`],
	[`	I86.1	`,`	Scrotal varices Varicocele 	`,`	null	`],
	[`	I86.2	`,`	Pelvic varices 	`,`	null	`],
	[`	I86.3	`,`	Vulval varices Excl.: complicating: childbirth and the puerperium (O87.8) pregnancy (O22.1) 	`,`	null	`],
	[`	I86.4	`,`	Gastric varices 	`,`	null	`],
	[`	I86.8	`,`	Varicose veins of other specified sites Varicose ulcer of nasal septum 	`,`	null	`],
	[`	I87	`,`	Other disorders of veins 	`,`	null	`],
	[`	I87.0	`,`	Postthrombotic syndrome Postphlebitic syndrome 	`,`	null	`],
	[`	I87.1	`,`	Compression of vein Stricture of vein Vena cava syndrome (inferior)(superior) Excl.: pulmonary (I28.8) 	`,`	null	`],
	[`	I87.2	`,`	Venous insufficiency (chronic)(peripheral) 	`,`	null	`],
	[`	I87.8	`,`	Other specified disorders of veins 	`,`	null	`],
	[`	I87.9	`,`	Disorder of vein, unspecified 	`,`	null	`],
	[`	I88	`,`	Nonspecific lymphadenitis Excl.: acute lymphadenitis, except mesenteric (L04.-) enlarged lymph nodes NOS (R59.-) human immunodeficiency virus [HIV] disease resulting in generalized lymphadenopathy (B23.1) 	`,`	null	`],
	[`	I88.0	`,`	Nonspecific mesenteric lymphadenitis Mesenteric lymphadenitis (acute)(chronic) 	`,`	null	`],
	[`	I88.1	`,`	Chronic lymphadenitis, except mesenteric Adenitis Lymphadenitis chronic, any lymph node except mesenteric 	`,`	null	`],
	[`	I88.8	`,`	Other nonspecific lymphadenitis 	`,`	null	`],
	[`	I88.9	`,`	Nonspecific lymphadenitis, unspecified Lymphadenitis NOS 	`,`	null	`],
	[`	I89	`,`	Other noninfective disorders of lymphatic vessels and lymph nodes Excl.: chylocele: filarial (B74.-) tunica vaginalis (nonfilarial) NOS (N50.8) enlarged lymph nodes NOS (R59.-) hereditary lymphoedema (Q82.0) postmastectomy lymphoedema (I97.2) 	`,`	null	`],
	[`	I89.0	`,`	Lymphoedema, not elsewhere classified Lymphangiectasis 	`,`	null	`],
	[`	I89.1	`,`	Lymphangitis Lymphangitis: NOS chronic subacute Excl.: acute lymphangitis (L03.-) 	`,`	null	`],
	[`	I89.8	`,`	Other specified noninfective disorders of lymphatic vessels and lymph nodes Chylocele (nonfilarial) Lipomelanotic reticulosis 	`,`	null	`],
	[`	I89.9	`,`	Noninfective disorder of lymphatic vessels and lymph nodes, unspecified Disease of lymphatic vessels NOS 	`,`	null	`],
	[`	I95	`,`	Hypotension Excl.: cardiovascular collapse (R57.9) maternal hypotension syndrome (O26.5) nonspecific low blood pressure reading NOS (R03.1) 	`,`	null	`],
	[`	I95.0	`,`	Idiopathic hypotension 	`,`	null	`],
	[`	I95.1	`,`	Orthostatic hypotension Hypotension, postural Excl.: neurogenic orthostatic hypotension [Shy-Drager] (G90.3) 	`,`	null	`],
	[`	I95.2	`,`	Hypotension due to drugs Use additional external cause code (Chapter XX), if desired, to identify drug. 	`,`	null	`],
	[`	I95.8	`,`	Other hypotension Chronic hypotension 	`,`	null	`],
	[`	I95.9	`,`	Hypotension, unspecified 	`,`	null	`],
	[`	I97	`,`	Postprocedural disorders of circulatory system, not elsewhere classified Excl.: postoperative shock (T81.1) 	`,`	null	`],
	[`	I97.0	`,`	Postcardiotomy syndrome 	`,`	null	`],
	[`	I97.1	`,`	Other functional disturbances following cardiac surgery Cardiac insufficiency Heart failure following cardiac surgery or due to presence of cardiac prosthesis 	`,`	null	`],
	[`	I97.2	`,`	Postmastectomy lymphoedema syndrome Elephantiasis Obliteration of lymphatic vessels due to mastectomy 	`,`	null	`],
	[`	I97.8	`,`	Other postprocedural disorders of circulatory system, not elsewhere classified 	`,`	null	`],
	[`	I97.9	`,`	Postprocedural disorder of circulatory system, unspecified 	`,`	null	`],
	[`	I98*	`,`	Other disorders of circulatory system in diseases classified elsewhere Excl.: disorders classified to other asterisk categories within this chapter 	`,`	null	`],
	[`	I98.0*	`,`	Cardiovascular syphilis Cardiovascular syphilis: NOS (A52.0) congenital, late (A50.5) 	`,`	null	`],
	[`	I98.1*	`,`	Cardiovascular disorders in other infectious and parasitic diseases classified elsewhere Cardiovascular: involvement NEC, in Chagas disease (chronic) (B57.2) lesions of pinta [carate] (A67.2) 	`,`	null	`],
	[`	I98.2*	`,`	Oesophageal varices without bleeding in diseases classified elsewhere Oesophageal varices in: liver disorders (K70-K71, K74.-) schistosomiasis (B65.-) 	`,`	null	`],
	[`	I98.3*	`,`	Oesophageal varices with bleeding in diseases classified elsewhere Oesophageal varices in: liver disorders (K70-K71, K74.-) schistosomiasis (B65.-) 	`,`	null	`],
	[`	I98.8*	`,`	Other specified disorders of circulatory system in diseases classified elsewhere I99 Other and unspecified disorders of circulatory system 	`,`	null	`],
							
];								
				
							
				
	
let CodeRangeI ={
	f0:function(val1=(-1),val2=(0)){
		let Range1 = ICodes.slice(val1,val2);
		Range1.reverse();
		document.documentElement.innerHTML += `<br>Showing I Codes ${Range1.length} items(s)`;

		for(value1 in Range1){
			    document.documentElement.style.cssText += "background-color:tan;";
				document.getElementById('icodesTR').outerHTML += `<tr><td style="background-color:navy;color:white;width:5%;padding:40px;border:2px solid white;font-weight:900;font-size:40px;text-align:center;">${Range1[value1][0]}</td><td style="background-color:black;color:white;width:90%;padding:20px;border:2px solid white;font-size:30px;">${Range1[value1][1]}</td><td style="background-color:navy;color:white;width:5%;padding:20px;border:2px solid white;font-weight:900;font-size:40px;text-align:center;">${Range1[value1][2]}</td></tr>`;			
		}

	},

};

	






	






