let JCodes = [								
	[`		`,`		`,`		`],
	[`	J00	`,`	Acute nasopharyngitis [common cold] Incl.: Coryza (acute) Nasal catarrh, acute Nasopharyngitis: NOS infective NOS Rhinitis: acute infective Excl.: nasopharyngitis, chronic (J31.1) pharyngitis: NOS (J02.9) acute (J02.-) chronic (J31.2) rhinitis: NOS (J31.0) allergic (J30.1-J30.4) chronic (J31.0) vasomotor (J30.0) sore throat: NOS (J02.9) acute (J02.-) chronic (J31.2) 	`,`	null	`],
	[`	J01	`,`	Acute sinusitis Incl.: abscess empyema infection inflammation suppuration acute, of sinus (accessory)(nasal) Use additional code (B95-B98), if desired, to identify infectious agent. Excl.: sinusitis, chronic or NOS (J32.-) 	`,`	null	`],
	[`	J01.0	`,`	Acute maxillary sinusitis Acute antritis 	`,`	null	`],
	[`	J01.1	`,`	Acute frontal sinusitis 	`,`	null	`],
	[`	J01.2	`,`	Acute ethmoidal sinusitis 	`,`	null	`],
	[`	J01.3	`,`	Acute sphenoidal sinusitis 	`,`	null	`],
	[`	J01.4	`,`	Acute pansinusitis 	`,`	null	`],
	[`	J01.8	`,`	Other acute sinusitis Acute sinusitis involving more than one sinus but not pansinusitis 	`,`	null	`],
	[`	J01.9	`,`	Acute sinusitis, unspecified 	`,`	null	`],
	[`	J02	`,`	Acute pharyngitis Incl.: acute sore throat Excl.: abscess: peritonsillar (J36) pharyngeal (J39.1) retropharyngeal (J39.0) acute laryngopharyngitis (J06.0) chronic pharyngitis (J31.2) 	`,`	null	`],
	[`	J02.0	`,`	Streptococcal pharyngitis Streptococcal sore throat Excl.: scarlet fever (A38) 	`,`	null	`],
	[`	J02.8	`,`	Acute pharyngitis due to other specified organisms Use additional code (B95-B98), if desired, to identify infectious agent. Excl.: pharyngitis (due to): enteroviral vesicular (B08.5) herpesviral [herpes simplex] (B00.2) infectious mononucleosis (B27.-) influenza virus: identified (J09, J10.1) not identified (J11.1) 	`,`	null	`],
	[`	J02.9	`,`	Acute pharyngitis, unspecified Pharyngitis (acute): NOS gangrenous infective NOS suppurative ulcerative Sore throat (acute) NOS 	`,`	null	`],
	[`	J03	`,`	Acute tonsillitis Excl.: peritonsillar abscess (J36) sore throat: NOS (J02.9) acute (J02.-) streptococcal (J02.0) 	`,`	null	`],
	[`	J03.0	`,`	Streptococcal tonsillitis 	`,`	null	`],
	[`	J03.8	`,`	Acute tonsillitis due to other specified organisms Use additional code (B95-B98), if desired, to identify infectious agent. Excl.: herpesviral [herpes simplex] pharyngotonsillitis (B00.2) 	`,`	null	`],
	[`	J03.9	`,`	Acute tonsillitis, unspecified Tonsillitis (acute): NOS follicular gangrenous infective ulcerative 	`,`	null	`],
	[`	J04	`,`	Acute laryngitis and tracheitis Use additional code (B95-B98), if desired, to identify infectious agent. Excl.: acute obstructive laryngitis [croup] and epiglottitis (J05.-) laryngismus (stridulus) (J38.5) 	`,`	null	`],
	[`	J04.0	`,`	Acute laryngitis Laryngitis (acute): NOS oedematous subglottic suppurative ulcerative Excl.: chronic laryngitis (J37.0) influenzal laryngitis, influenza virus: identified (J09, J10.1) not identified (J11.1) 	`,`	null	`],
	[`	J04.1	`,`	Acute tracheitis Tracheitis (acute): NOS catarrhal Excl.: chronic tracheitis (J42) 	`,`	null	`],
	[`	J04.2	`,`	Acute laryngotracheitis Laryngotracheitis NOS Tracheitis (acute) with laryngitis (acute) Excl.: chronic laryngotracheitis (J37.1) J05 Acute obstructive laryngitis [croup] and epiglottitis Use additional code (B95-B98), if desired, to identify infectious agent. 	`,`	null	`],
	[`	J05.0	`,`	Acute obstructive laryngitis [croup] Obstructive laryngitis NOS 	`,`	null	`],
	[`	J05.1	`,`	Acute epiglottitis Epiglottitis NOS 	`,`	null	`],
	[`	J06	`,`	Acute upper respiratory infections of multiple and unspecified sites Excl.: acute respiratory infection NOS (J22) influenza virus: identified (J09, J10.1) not identified (J11.1) 	`,`	null	`],
	[`	J06.0	`,`	Acute laryngopharyngitis 	`,`	null	`],
	[`	J06.8	`,`	Other acute upper respiratory infections of multiple sites 	`,`	null	`],
	[`	J06.9	`,`	Acute upper respiratory infection, unspecified Upper respiratory: disease, acute infection NOS 	`,`	null	`],
	[`	J09	`,`	Influenza due to certain identified influenza virus Note: Additional virus strains may only be included upon recommendation by WHO. Influenza caused by influenza virus strains of special epidemiological importance with an animal-human or inter-human transmission limited to the inclusions. Incl.: Influenza A/H1N1 pandemic 2009 [swine flu] Influenza A/H5N1 epidemic [avian influenza] Use additional code, if desired, to identify pneumonia or other manifestations. Excl.: Haemophilus influenzae [H. influenzae]: infection NOS (A49.2) meningitis (G00.0) pneumonia (J14) 	`,`	null	`],
	[`	J10	`,`	Influenza due to other identified influenza virus Excl.: Haemophilus influenzae [H. influenzae]: infection NOS (A49.2) meningitis (G00.0) pneumonia (J14) 	`,`	null	`],
	[`	J10.0	`,`	Influenza with pneumonia, other influenza virus identified Influenzal (broncho)pneumonia, other influenza virus identified 	`,`	null	`],
	[`	J10.1	`,`	Influenza with other respiratory manifestations, other influenza virus identified Influenza Influenzal: acute upper respiratory infection laryngitis pharyngitis pleural effusion other influenza virus identified 	`,`	null	`],
	[`	J10.8	`,`	Influenza with other manifestations, other influenza virus identified Encephalopathy due to influenza Influenzal: gastroenteritis myocarditis (acute) other influenza virus identified 	`,`	null	`],
	[`	J11	`,`	Influenza, virus not identified Incl.: influenza viral influenza specific virus not stated to have been identified Excl.: Haemophilus influenzae [H. influenzae]: infection NOS (A49.2) meningitis (G00.0) pneumonia (J14) 	`,`	null	`],
	[`	J11.0	`,`	Influenza with pneumonia, virus not identified Influenzal (broncho)pneumonia, unspecified or specific virus not identified 	`,`	null	`],
	[`	J11.1	`,`	Influenza with other respiratory manifestations, virus not identified Influenza NOS Influenzal: acute upper respiratory infection laryngitis pharyngitis pleural effusion unspecified or specific virus not identified 	`,`	null	`],
	[`	J11.8	`,`	Influenza with other manifestations, virus not identified Encephalopathy due to influenza Influenzal: gastroenteritis myocarditis (acute) unspecified or specific virus not identified 	`,`	null	`],
	[`	J12	`,`	Viral pneumonia, not elsewhere classified Incl.: bronchopneumonia due to viruses other than influenza viruses Excl.: congenital rubella pneumonitis (P35.0) pneumonia: aspiration (due to): NOS (J69.0) anaesthesia during: labour and delivery (O74.0) pregnancy (O29.0) puerperium (O89.0) neonatal (P24.9) solids and liquids (J69.-) congenital (P23.0) in influenza (J09, J10.0, J11.0) interstitial NOS (J84.9) lipid (J69.1) severe acute respiratory syndrome [SARS] (U04.9) 	`,`	null	`],
	[`	J12.0	`,`	Adenoviral pneumonia 	`,`	null	`],
	[`	J12.1	`,`	Respiratory syncytial virus pneumonia 	`,`	null	`],
	[`	J12.2	`,`	Parainfluenza virus pneumonia 	`,`	null	`],
	[`	J12.3	`,`	Human metapneumovirus pneumonia 	`,`	null	`],
	[`	J12.8	`,`	Other viral pneumonia 	`,`	null	`],
	[`	J12.9	`,`	Viral pneumonia, unspecified 	`,`	null	`],
	[`	J13	`,`	Pneumonia due to Streptococcus pneumoniae Incl.: Bronchopneumonia due to S. pneumoniae Excl.: congenital pneumonia due to S. pneumoniae (P23.6) pneumonia due to other streptococci (J15.3-J15.4) 	`,`	null	`],
	[`	J14	`,`	Pneumonia due to Haemophilus influenzae Incl.: Bronchopneumonia due to H. influenzae Excl.: congenital pneumonia due to H. influenzae (P23.6) 	`,`	null	`],
	[`	J15	`,`	Bacterial pneumonia, not elsewhere classified Incl.: bronchopneumonia due to bacteria other than S. pneumoniae and H. influenzae Excl.: chlamydial pneumonia (J16.0) congenital pneumonia (P23.-) Legionnaires disease (A48.1) 	`,`	null	`],
	[`	J15.0	`,`	Pneumonia due to Klebsiella pneumoniae 	`,`	null	`],
	[`	J15.1	`,`	Pneumonia due to Pseudomonas 	`,`	null	`],
	[`	J15.2	`,`	Pneumonia due to staphylococcus 	`,`	null	`],
	[`	J15.3	`,`	Pneumonia due to streptococcus, group B 	`,`	null	`],
	[`	J15.4	`,`	Pneumonia due to other streptococci Excl.: pneumonia due to: streptococcus, group B (J15.3) Streptococcus pneumoniae (J13) 	`,`	null	`],
	[`	J15.5	`,`	Pneumonia due to Escherichia coli 	`,`	null	`],
	[`	J15.6	`,`	Pneumonia due to other aerobic Gram-negative bacteria Pneumonia due to Serratia marcescens 	`,`	null	`],
	[`	J15.7	`,`	Pneumonia due to Mycoplasma pneumoniae 	`,`	null	`],
	[`	J15.8	`,`	Other bacterial pneumonia 	`,`	null	`],
	[`	J15.9	`,`	Bacterial pneumonia, unspecified 	`,`	null	`],
	[`	J16	`,`	Pneumonia due to other infectious organisms, not elsewhere classified Excl.: ornithosis (A70) pneumocystosis (B59) pneumonia: NOS (J18.9) congenital (P23.-) 	`,`	null	`],
	[`	J16.0	`,`	Chlamydial pneumonia 	`,`	null	`],
	[`	J16.8	`,`	Pneumonia due to other specified infectious organisms 	`,`	null	`],
	[`	J17*	`,`	Pneumonia in diseases classified elsewhere 	`,`	null	`],
	[`	J17.0*	`,`	Pneumonia in bacterial diseases classified elsewhere Pneumonia (due to)(in): actinomycosis (A42.0) anthrax (A22.1) gonorrhoea (A54.8) nocardiosis (A43.0) salmonella infection (A02.2) tularaemia (A21.2) typhoid fever (A01.0) whooping cough (A37.-) 	`,`	null	`],
	[`	J17.1*	`,`	Pneumonia in viral diseases classified elsewhere Pneumonia in: cytomegalovirus disease (B25.0) measles (B05.2) rubella (B06.8) varicella (B01.2) 	`,`	null	`],
	[`	J17.2*	`,`	Pneumonia in mycoses Pneumonia in: aspergillosis (B44.0-B44.1) candidiasis (B37.1) coccidioidomycosis (B38.0-B38.2) histoplasmosis (B39.-) 	`,`	null	`],
	[`	J17.3*	`,`	Pneumonia in parasitic diseases Pneumonia in: ascariasis (B77.8) schistosomiasis (B65.-) toxoplasmosis (B58.3) 	`,`	null	`],
	[`	J17.8*	`,`	Pneumonia in other diseases classified elsewhere Pneumonia (in): ornithosis (A70) Q fever (A78) rheumatic fever (I00) spirochaetal, not elsewhere classified (A69.8) 	`,`	null	`],
	[`	J18	`,`	Pneumonia, organism unspecified Excl.: abscess of lung with pneumonia (J85.1) drug-induced interstitial lung disorders (J70.2-J70.4) pneumonia: aspiration (due to): NOS (J69.0) anaesthesia during: labour and delivery (O74.0) pregnancy (O29.0) puerperium (O89.0) neonatal (P24.9) solids and liquids (J69.-) congenital (P23.9) interstitial NOS (J84.9) lipid (J69.1) usual interstitial (J84.1) pneumonitis, due to external agents (J67-J70) 	`,`	null	`],
	[`	J18.0	`,`	Bronchopneumonia, unspecified Excl.: bronchiolitis (J21.-) 	`,`	null	`],
	[`	J18.1	`,`	Lobar pneumonia, unspecified 	`,`	null	`],
	[`	J18.2	`,`	Hypostatic pneumonia, unspecified 	`,`	null	`],
	[`	J18.8	`,`	Other pneumonia, organism unspecified 	`,`	null	`],
	[`	J18.9	`,`	Pneumonia, unspecified 	`,`	null	`],
	[`	J20	`,`	Acute bronchitis Incl.: bronchitis: NOS, in those under l5 years of age acute and subacute (with): bronchospasm fibrinous membranous purulent septic tracheitis tracheobronchitis, acute Excl.: bronchitis: NOS, in those 15 years of age and above (J40) allergic NOS (J45.0) chronic: NOS (J42) mucopurulent (J41.1) obstructive (J44.-) simple (J41.0) tracheobronchitis: NOS (J40) chronic (J42) chronic obstructive (J44.-) 	`,`	null	`],
	[`	J20.0	`,`	Acute bronchitis due to Mycoplasma pneumoniae 	`,`	null	`],
	[`	J20.1	`,`	Acute bronchitis due to Haemophilus influenzae 	`,`	null	`],
	[`	J20.2	`,`	Acute bronchitis due to streptococcus 	`,`	null	`],
	[`	J20.3	`,`	Acute bronchitis due to coxsackievirus 	`,`	null	`],
	[`	J20.4	`,`	Acute bronchitis due to parainfluenza virus 	`,`	null	`],
	[`	J20.5	`,`	Acute bronchitis due to respiratory syncytial virus 	`,`	null	`],
	[`	J20.6	`,`	Acute bronchitis due to rhinovirus 	`,`	null	`],
	[`	J20.7	`,`	Acute bronchitis due to echovirus 	`,`	null	`],
	[`	J20.8	`,`	Acute bronchitis due to other specified organisms 	`,`	null	`],
	[`	J20.9	`,`	Acute bronchitis, unspecified 	`,`	null	`],
	[`	J21	`,`	Acute bronchiolitis Incl.: with bronchospasm 	`,`	null	`],
	[`	J21.0	`,`	Acute bronchiolitis due to respiratory syncytial virus 	`,`	null	`],
	[`	J21.1	`,`	Acute bronchiolitis due to human metapneumovirus 	`,`	null	`],
	[`	J21.8	`,`	Acute bronchiolitis due to other specified organisms 	`,`	null	`],
	[`	J21.9	`,`	Acute bronchiolitis, unspecified Bronchiolitis (acute) 	`,`	null	`],
	[`	J22	`,`	Unspecified acute lower respiratory infection Incl.: Acute (lower) respiratory (tract) infection NOS Excl.: upper respiratory infection (acute) (J06.9) 	`,`	null	`],
	[`	J30	`,`	Vasomotor and allergic rhinitis Incl.: spasmodic rhinorrhoea Excl.: allergic rhinitis with asthma (J45.0) rhinitis NOS (J31.0) 	`,`	null	`],
	[`	J30.0	`,`	Vasomotor rhinitis 	`,`	null	`],
	[`	J30.1	`,`	Allergic rhinitis due to pollen Allergy NOS due to pollen Hay fever Pollinosis 	`,`	null	`],
	[`	J30.2	`,`	Other seasonal allergic rhinitis 	`,`	null	`],
	[`	J30.3	`,`	Other allergic rhinitis Perennial allergic rhinitis 	`,`	null	`],
	[`	J30.4	`,`	Allergic rhinitis, unspecified 	`,`	null	`],
	[`	J31	`,`	Chronic rhinitis, nasopharyngitis and pharyngitis 	`,`	null	`],
	[`	J31.0	`,`	Chronic rhinitis Ozena Rhinitis (chronic): NOS atrophic granulomatous hypertrophic obstructive purulent ulcerative Excl.: rhinitis: allergic (J30.1-J30.4) vasomotor (J30.0) 	`,`	null	`],
	[`	J31.1	`,`	Chronic nasopharyngitis Excl.: nasopharyngitis, acute or NOS (J00) 	`,`	null	`],
	[`	J31.2	`,`	Chronic pharyngitis Chronic sore throat Pharyngitis (chronic): atrophic granular hypertrophic Excl.: pharyngitis, acute or NOS (J02.9) 	`,`	null	`],
	[`	J32	`,`	Chronic sinusitis Incl.: abscess empyema infection suppuration (chronic) of sinus (accessory)(nasal) Use additional code (B95-B98), if desired, to identify infectious agent. Excl.: acute sinusitis (J01.-) 	`,`	null	`],
	[`	J32.0	`,`	Chronic maxillary sinusitis Antritis (chronic) Maxillary sinusitis NOS 	`,`	null	`],
	[`	J32.1	`,`	Chronic frontal sinusitis Frontal sinusitis NOS 	`,`	null	`],
	[`	J32.2	`,`	Chronic ethmoidal sinusitis Ethmoidal sinusitis NOS 	`,`	null	`],
	[`	J32.3	`,`	Chronic sphenoidal sinusitis Sphenoidal sinusitis NOS 	`,`	null	`],
	[`	J32.4	`,`	Chronic pansinusitis Pansinusitis NOS 	`,`	null	`],
	[`	J32.8	`,`	Other chronic sinusitis Sinusitis (chronic) involving more than one sinus but not pansinusitis 	`,`	null	`],
	[`	J32.9	`,`	Chronic sinusitis, unspecified Sinusitis (chronic) NOS 	`,`	null	`],
	[`	J33	`,`	Nasal polyp Excl.: adenomatous polyps (D14.0) 	`,`	null	`],
	[`	J33.0	`,`	Polyp of nasal cavity Polyp: choanal nasopharyngeal 	`,`	null	`],
	[`	J33.1	`,`	Polypoid sinus degeneration Woakes syndrome or ethmoiditis 	`,`	null	`],
	[`	J33.8	`,`	Other polyp of sinus Polyp of sinus: accessory ethmoidal maxillary sphenoidal 	`,`	null	`],
	[`	J33.9	`,`	Nasal polyp, unspecified 	`,`	null	`],
	[`	J34	`,`	Other disorders of nose and nasal sinuses Excl.: varicose ulcer of nasal septum (I86.8) 	`,`	null	`],
	[`	J34.0	`,`	Abscess, furuncle and carbuncle of nose Cellulitis Necrosis Ulceration of nose (septum) 	`,`	null	`],
	[`	J34.1	`,`	Cyst and mucocele of nose and nasal sinus 	`,`	null	`],
	[`	J34.2	`,`	Deviated nasal septum Deflection or deviation of septum (nasal)(acquired) 	`,`	null	`],
	[`	J34.3	`,`	Hypertrophy of nasal turbinates 	`,`	null	`],
	[`	J34.8	`,`	Other specified disorders of nose and nasal sinuses Perforation of nasal septum NOS Rhinolith 	`,`	null	`],
	[`	J35	`,`	Chronic diseases of tonsils and adenoids 	`,`	null	`],
	[`	J35.0	`,`	Chronic tonsillitis Excl.: tonsillitis: NOS (J03.9) acute (J03.-) 	`,`	null	`],
	[`	J35.1	`,`	Hypertrophy of tonsils Enlargement of tonsils 	`,`	null	`],
	[`	J35.2	`,`	Hypertrophy of adenoids Enlargement of adenoids 	`,`	null	`],
	[`	J35.3	`,`	Hypertrophy of tonsils with hypertrophy of adenoids 	`,`	null	`],
	[`	J35.8	`,`	Other chronic diseases of tonsils and adenoids Adenoid vegetations Amygdalolith Cicatrix of tonsil (and adenoid) Tonsillar tag Ulcer of tonsil 	`,`	null	`],
	[`	J35.9	`,`	Chronic disease of tonsils and adenoids, unspecified Disease (chronic) of tonsils and adenoids NOS 	`,`	null	`],
	[`	J36	`,`	Peritonsillar abscess Incl.: Abscess of tonsil Peritonsillar cellulitis Quinsy Use additional code (B95-B98), if desired, to identify infectious agent. Excl.: retropharyngeal abscess (J39.0) tonsillitis: NOS (J03.9) acute (J03.-) chronic (J35.0) 	`,`	null	`],
	[`	J37	`,`	Chronic laryngitis and laryngotracheitis Use additional code (B95-B98), if desired, to identify infectious agent. 	`,`	null	`],
	[`	J37.0	`,`	Chronic laryngitis Laryngitis: catarrhal hypertrophic sicca Excl.: laryngitis: NOS (J04.0) acute (J04.0) obstructive (acute) (J05.0) 	`,`	null	`],
	[`	J37.1	`,`	Chronic laryngotracheitis Laryngitis, chronic, with tracheitis (chronic) Tracheitis, chronic, with laryngitis Excl.: laryngotracheitis: NOS (J04.2) acute (J04.2) tracheitis: NOS (J04.1) acute (J04.1) chronic (J42) 	`,`	null	`],
	[`	J38	`,`	Diseases of vocal cords and larynx, not elsewhere classified Excl.: laryngitis: obstructive (acute) (J05.0) ulcerative (J04.0) postprocedural subglottic stenosis (J95.5) stridor: congenital laryngeal NOS (P28.8) NOS (R06.1) 	`,`	null	`],
	[`	J38.0	`,`	Paralysis of vocal cords and larynx Laryngoplegia Paralysis of glottis 	`,`	null	`],
	[`	J38.1	`,`	Polyp of vocal cord and larynx Excl.: adenomatous polyps (D14.1) 	`,`	null	`],
	[`	J38.2	`,`	Nodules of vocal cords Chorditis (fibrinous)(nodosa)(tuberosa) Singer nodes Teacher nodes 	`,`	null	`],
	[`	J38.3	`,`	Other diseases of vocal cords Abscess Cellulitis Granuloma Leukokeratosis Leukoplakia of vocal cord(s) 	`,`	null	`],
	[`	J38.4	`,`	Oedema of larynx Oedema (of): glottis subglottic supraglottic Excl.: laryngitis: acute obstructive [croup] (J05.0) oedematous (J04.0) 	`,`	null	`],
	[`	J38.5	`,`	Laryngeal spasm Laryngismus (stridulus) 	`,`	null	`],
	[`	J38.6	`,`	Stenosis of larynx 	`,`	null	`],
	[`	J38.7	`,`	Other diseases of larynx Abscess Cellulitis Disease NOS Necrosis Pachyderma Perichondritis Ulcer of larynx 	`,`	null	`],
	[`	J39	`,`	Other diseases of upper respiratory tract Excl.: acute respiratory infection NOS (J22) acute respiratory infection NOS upper (J06.9) upper respiratory inflammation due to chemicals, gases, fumes or vapours (J68.2) 	`,`	null	`],
	[`	J39.0	`,`	Retropharyngeal and parapharyngeal abscess Peripharyngeal abscess Excl.: peritonsillar abscess (J36) 	`,`	null	`],
	[`	J39.1	`,`	Other abscess of pharynx Cellulitis of pharynx Nasopharyngeal abscess 	`,`	null	`],
	[`	J39.2	`,`	Other diseases of pharynx Cyst Oedema of pharynx or nasopharynx Excl.: pharyngitis: chronic (J31.2) ulcerative (J02.9) 	`,`	null	`],
	[`	J39.3	`,`	Upper respiratory tract hypersensitivity reaction, site unspecified 	`,`	null	`],
	[`	J39.8	`,`	Other specified diseases of upper respiratory tract 	`,`	null	`],
	[`	J39.9	`,`	Disease of upper respiratory tract, unspecified 	`,`	null	`],
	[`	J80	`,`	Adult respiratory distress syndrome Incl.: Adult hyaline membrane disease 	`,`	null	`],
	[`	J81	`,`	Pulmonary oedema Incl.: Acute oedema of lung Pulmonary congestion (passive) Excl.: hypostatic pneumonia (J18.2) pulmonary oedema: chemical (acute) (J68.1) due to external agents (J60-J70) with mention of heart disease NOS or heart failure (I50.1) 	`,`	null	`],
	[`	J82	`,`	Pulmonary eosinophilia, not elsewhere classified Incl.: Eosinophilic asthma Loffler pneumonia Tropical (pulmonary) eosinophilia NOS Excl.: due to: aspergillosis (B44.-) drugs (J70.2-J70.4) specified parasitic infection (B50-B83) systemic connective tissue disorders (M30-M36) 	`,`	null	`],
	[`	J84	`,`	Other interstitial pulmonary diseases Excl.: drug-induced interstitial lung disorders (J70.2-J70.4) interstitial emphysema (J98.2) lung diseases due to external agents (J60-J70) lymphoid interstitial pneumonitis resulting from human immunodeficiency virus [HIV] disease (B22.1) 	`,`	null	`],
	[`	J84.0	`,`	Alveolar and parietoalveolar conditions Alveolar proteinosis Pulmonary alveolar microlithiasis 	`,`	null	`],
	[`	J84.1	`,`	Other interstitial pulmonary diseases with fibrosis Diffuse pulmonary fibrosis Fibrosing alveolitis (cryptogenic) Hamman-Rich syndrome Idiopathic pulmonary fibrosis Usual interstitial pneumonia Excl.: pulmonary fibrosis (chronic): due to inhalation of chemicals, gases, fumes or vapours (J68.4) following radiation (J70.1) 	`,`	null	`],
	[`	J84.8	`,`	Other specified interstitial pulmonary diseases 	`,`	null	`],
	[`	J84.9	`,`	Interstitial pulmonary disease, unspecified Interstitial pneumonia NOS 	`,`	null	`],
	[`	J85	`,`	Abscess of lung and mediastinum 	`,`	null	`],
	[`	J85.0	`,`	Gangrene and necrosis of lung 	`,`	null	`],
	[`	J85.1	`,`	Abscess of lung with pneumonia Excl.: with pneumonia due to specified organism (J09-J16) 	`,`	null	`],
	[`	J85.2	`,`	Abscess of lung without pneumonia Abscess of lung NOS 	`,`	null	`],
	[`	J85.3	`,`	Abscess of mediastinum 	`,`	null	`],
	[`	J86	`,`	Pyothorax Incl.: abscess of: pleura thorax empyema pyopneumothorax Use additional code (B95-B98), if desired, to identify infectious agent. Excl.: due to tuberculosis (A15-A16) 	`,`	null	`],
	[`	J86.0	`,`	Pyothorax with fistula 	`,`	null	`],
	[`	J86.9	`,`	Pyothorax without fistula 	`,`	null	`],
	[`	J90	`,`	Pleural effusion, not elsewhere classified Incl.: Pleurisy with effusion Excl.: chylous (pleural) effusion (J94.0) pleurisy NOS (R09.1) tuberculous (A15-A16) 	`,`	null	`],
	[`	J91*	`,`	Pleural effusion in conditions classified elsewhere 	`,`	null	`],
	[`	J92	`,`	Pleural plaque Incl.: pleural thickening 	`,`	null	`],
	[`	J92.0	`,`	Pleural plaque with presence of asbestos 	`,`	null	`],
	[`	J92.9	`,`	Pleural plaque without asbestos Pleural plaque NOS 	`,`	null	`],
	[`	J93	`,`	Pneumothorax Excl.: pneumothorax: congenital or perinatal (P25.1) traumatic (S27.0) tuberculous (current disease) (A15-A16) pyopneumothorax (J86.-) 	`,`	null	`],
	[`	J93.0	`,`	Spontaneous tension pneumothorax 	`,`	null	`],
	[`	J93.1	`,`	Other spontaneous pneumothorax 	`,`	null	`],
	[`	J93.8	`,`	Other pneumothorax 	`,`	null	`],
	[`	J93.9	`,`	Pneumothorax, unspecified 	`,`	null	`],
	[`	J94	`,`	Other pleural conditions Excl.: pleurisy NOS (R09.1) traumatic: haemopneumothorax (S27.2) haemothorax (S27.1) tuberculous pleural conditions (current disease) (A15-A16) 	`,`	null	`],
	[`	J94.0	`,`	Chylous effusion Chyliform effusion 	`,`	null	`],
	[`	J94.1	`,`	Fibrothorax 	`,`	null	`],
	[`	J94.2	`,`	Haemothorax Haemopneumothorax 	`,`	null	`],
	[`	J94.8	`,`	Other specified pleural conditions Hydrothorax 	`,`	null	`],
	[`	J94.9	`,`	Pleural condition, unspecified 	`,`	null	`],
							
];								
							
							
				
							
							
				
	
let CodeRangeJ ={
	f0:function(val1=(-1),val2=(0)){
		let Range1 = JCodes.slice(val1,val2);
		Range1.reverse();
		document.documentElement.innerHTML += `<br>Showing J Codes ${Range1.length} items(s)`;

		for(value2 in Range1){
			    document.documentElement.style.cssText += "background-color:tan;";
				document.getElementById('jcodesTR').outerHTML += `<tr><td style="background-color:navy;color:white;width:5%;padding:40px;border:2px solid white;font-weight:900;font-size:40px;text-align:center;">${Range1[value2][0]}</td><td style="background-color:black;color:white;width:90%;padding:20px;border:2px solid white;font-size:30px;">${Range1[value2][1]}</td><td style="background-color:navy;color:white;width:5%;padding:20px;border:2px solid white;font-weight:900;font-size:40px;text-align:center;">${Range1[value2][2]}</td></tr>`;			
		}

	},

};

	






	






