								
let KCodes =[								
								
	[`		`,`		`,`		`],
	[`	K00	`,`	Disorders of tooth development and eruption Excl.: embedded and impacted teeth (K01.-) 	`,`	null	`],
	[`	K00.0	`,`	Anodontia Hypodontia Oligodontia 	`,`	null	`],
	[`	K00.1	`,`	Supernumerary teeth Distomolar Fourth molar Mesiodens Paramolar Supplementary teeth 	`,`	null	`],
	[`	K00.2	`,`	Abnormalities of size and form of teeth Concrescence Fusion Gemination of teeth Dens: evaginatus in dente invaginatus Enamel pearls Macrodontia Microdontia Peg-shaped [conical] teeth Taurodontism Tuberculum paramolare Excl.: tuberculum Carabelli, which is regarded as a normal variation and should not be coded 	`,`	null	`],
	[`	K00.3	`,`	Mottled teeth Dental fluorosis Mottling of enamel Nonfluoride enamel opacities Excl.: deposits [accretions] on teeth (K03.6) 	`,`	null	`],
	[`	K00.4	`,`	Disturbances in tooth formation Aplasia and hypoplasia of cementum Dilaceration of tooth Enamel hypoplasia (neonatal)(postnatal)(prenatal) Regional odontodysplasia Turner tooth Excl.: Hutchinson teeth and mulberry molars in congenital syphilis (A50.5) mottled teeth (K00.3) 	`,`	null	`],
	[`	K00.5	`,`	Hereditary disturbances in tooth structure, not elsewhere classified Amelogenesis Dentinogenesis Odontogenesis imperfecta Dentinal dysplasia Shell teeth 	`,`	null	`],
	[`	K00.6	`,`	Disturbances in tooth eruption Dentia praecox Natal Neonatal tooth Premature: eruption of tooth shedding of primary [deciduous] tooth Retained [persistent] primary tooth 	`,`	null	`],
	[`	K00.7	`,`	Teething syndrome 	`,`	null	`],
	[`	K00.8	`,`	Other disorders of tooth development Colour changes during tooth formation Intrinsic staining of teeth NOS 	`,`	null	`],
	[`	K00.9	`,`	Disorder of tooth development, unspecified Disorder of odontogenesis NOS 	`,`	null	`],
	[`	K01	`,`	Embedded and impacted teeth Excl.: embedded and impacted teeth with abnormal position of such teeth or adjacent teeth (K07.3) 	`,`	null	`],
	[`	K01.0	`,`	Embedded teeth An embedded tooth is a tooth that has failed to erupt without obstruction by another tooth. 	`,`	null	`],
	[`	K01.1	`,`	Impacted teeth An impacted tooth is a tooth that has failed to erupt because of obstruction by another tooth. 	`,`	null	`],
	[`	K02	`,`	Dental caries 	`,`	null	`],
	[`	K02.0	`,`	Caries limited to enamel White spot lesions [initial caries] 	`,`	null	`],
	[`	K02.1	`,`	Caries of dentine 	`,`	null	`],
	[`	K02.2	`,`	Caries of cementum 	`,`	null	`],
	[`	K02.3	`,`	Arrested dental caries 	`,`	null	`],
	[`	K02.4	`,`	Odontoclasia Infantile melanodontia Melanodontoclasia 	`,`	null	`],
	[`	K02.5	`,`	Caries with pulp exposure 	`,`	null	`],
	[`	K02.8	`,`	Other dental caries 	`,`	null	`],
	[`	K02.9	`,`	Dental caries, unspecified 	`,`	null	`],
	[`	K03	`,`	Other diseases of hard tissues of teeth Excl.: bruxism (F45.8) dental caries (K02.-) teeth-grinding NOS (F45.8) 	`,`	null	`],
	[`	K03.0	`,`	Excessive attrition of teeth Wear: approximal occlusal of teeth 	`,`	null	`],
	[`	K03.1	`,`	Abrasion of teeth Abrasion: dentifrice habitual occupational ritual traditional Wedge defect NOS of teeth 	`,`	null	`],
	[`	K03.2	`,`	Erosion of teeth Erosion of teeth: NOS due to: diet drugs and medicaments persistent vomiting idiopathic occupational 	`,`	null	`],
	[`	K03.3	`,`	Pathological resorption of teeth Internal granuloma of pulp Resorption of teeth (external) 	`,`	null	`],
	[`	K03.4	`,`	Hypercementosis Cementation hyperplasia 	`,`	null	`],
	[`	K03.5	`,`	Ankylosis of teeth 	`,`	null	`],
	[`	K03.6	`,`	Deposits [accretions] on teeth Dental calculus: subgingival supragingival Deposits [accretions] on teeth: betel black green materia alba orange tobacco Staining of teeth: NOS extrinsic NOS 	`,`	null	`],
	[`	K03.7	`,`	Posteruptive colour changes of dental hard tissues Excl.: deposits [accretions] on teeth (K03.6) 	`,`	null	`],
	[`	K03.8	`,`	Other specified diseases of hard tissues of teeth Irradiated enamel Sensitive dentine Use additional external cause code (Chapter XX), if desired, to identify radiation, if radiation-induced. 	`,`	null	`],
	[`	K03.9	`,`	Disease of hard tissues of teeth, unspecified 	`,`	null	`],
	[`	K04	`,`	Diseases of pulp and periapical tissues 	`,`	null	`],
	[`	K04.0	`,`	Pulpitis Pulpitis: NOS acute chronic (hyperplastic)(ulcerative) irreversible reversible 	`,`	null	`],
	[`	K04.1	`,`	Necrosis of pulp Pulpal gangrene 	`,`	null	`],
	[`	K04.2	`,`	Pulp degeneration Denticles Pulpal: calcifications stones 	`,`	null	`],
	[`	K04.3	`,`	Abnormal hard tissue formation in pulp Secondary or irregular dentine 	`,`	null	`],
	[`	K04.4	`,`	Acute apical periodontitis of pulpal origin Acute apical periodontitis NOS 	`,`	null	`],
	[`	K04.5	`,`	Chronic apical periodontitis Apical or periapical granuloma Apical periodontitis NOS 	`,`	null	`],
	[`	K04.6	`,`	Periapical abscess with sinus Dental Dentoalveolar abscess with sinus 	`,`	null	`],
	[`	K04.7	`,`	Periapical abscess without sinus Dental Dentoalveolar Periapical abscess NOS 	`,`	null	`],
	[`	K04.8	`,`	Radicular cyst Cyst: apical (periodontal) periapical residual radicular Excl.: lateral periodontal cyst (K09.0) 	`,`	null	`],
	[`	K04.9	`,`	Other and unspecified diseases of pulp and periapical tissues 	`,`	null	`],
	[`	K05	`,`	Gingivitis and periodontal diseases 	`,`	null	`],
	[`	K05.0	`,`	Acute gingivitis Excl.: acute necrotizing ulcerative gingivitis (A69.1) herpesviral [herpes simplex] gingivostomatitis (B00.2) 	`,`	null	`],
	[`	K05.1	`,`	Chronic gingivitis Gingivitis (chronic): NOS desquamative hyperplastic simple marginal ulcerative 	`,`	null	`],
	[`	K05.2	`,`	Acute periodontitis Acute pericoronitis Parodontal abscess Periodontal abscess Excl.: acute apical periodontitis (K04.4) periapical abscess (K04.7) periapical abscess with sinus (K04.6) 	`,`	null	`],
	[`	K05.3	`,`	Chronic periodontitis Chronic pericoronitis Periodontitis: NOS complex simplex 	`,`	null	`],
	[`	K05.4	`,`	Periodontosis Juvenile periodontosis 	`,`	null	`],
	[`	K05.5	`,`	Other periodontal diseases 	`,`	null	`],
	[`	K05.6	`,`	Periodontal disease, unspecified 	`,`	null	`],
	[`	K06	`,`	Other disorders of gingiva and edentulous alveolar ridge Excl.: atrophy of edentulous alveolar ridge (K08.2) gingivitis: NOS (K05.1) acute (K05.0) chronic (K05.1) 	`,`	null	`],
	[`	K06.0	`,`	Gingival recession Gingival recession (generalized)(localized)(postinfective)(post-operative) 	`,`	null	`],
	[`	K06.1	`,`	Gingival enlargement Gingival fibromatosis 	`,`	null	`],
	[`	K06.2	`,`	Gingival and edentulous alveolar ridge lesions associated with trauma Irritative hyperplasia of edentulous ridge [denture hyperplasia] Use additional external cause code (Chapter XX), if desired, to identify cause. 	`,`	null	`],
	[`	K06.8	`,`	Other specified disorders of gingiva and edentulous alveolar ridge Fibrous epulis Flabby ridge Giant cell epulis Peripheral giant cell granuloma Pyogenic granuloma of gingiva 	`,`	null	`],
	[`	K06.9	`,`	Disorder of gingiva and edentulous alveolar ridge, unspecified 	`,`	null	`],
	[`	K07	`,`	Dentofacial anomalies [including malocclusion] Excl.: hemifacial atrophy or hypertrophy (Q67.4) unilateral condylar hyperplasia or hypoplasia (K10.8) 	`,`	null	`],
	[`	K07.0	`,`	Major anomalies of jaw size Hyperplasia, hypoplasia: mandibular maxillary Macrognathism (mandibular)(maxillary) Micrognathism (mandibular)(maxillary) Excl.: acromegaly (E22.0) Robin syndrome (Q87.0) 	`,`	null	`],
	[`	K07.1	`,`	Anomalies of jaw-cranial base relationship Asymmetry of jaw Prognathism (mandibular)(maxillary) Retrognathism (mandibular)(maxillary) 	`,`	null	`],
	[`	K07.2	`,`	Anomalies of dental arch relationship Crossbite (anterior)(posterior) Disto-occlusion Mesio-occlusion Midline deviation of dental arch Openbite (anterior)(posterior) Overbite (excessive): deep horizontal vertical Overjet Posterior lingual occlusion of mandibular teeth 	`,`	null	`],
	[`	K07.3	`,`	Anomalies of tooth position Crowding Diastema Displacement Rotation Spacing, abnormal Transposition of tooth or teeth Impacted or embedded teeth with abnormal position of such teeth or adjacent teeth Excl.: embedded and impacted teeth without abnormal position (K01.-) 	`,`	null	`],
	[`	K07.4	`,`	Malocclusion, unspecified 	`,`	null	`],
	[`	K07.5	`,`	Dentofacial functional abnormalities Abnormal jaw closure Malocclusion due to: abnormal swallowing mouth breathing tongue, lip or finger habits Excl.: bruxism (F45.8) teeth-grinding NOS (F45.8) 	`,`	null	`],
	[`	K07.6	`,`	Temporomandibular joint disorders Costen complex or syndrome Derangement of temporomandibular joint Snapping jaw Temporomandibular joint-pain-dysfunction syndrome Excl.: current temporomandibular joint: dislocation (S03.0) strain (S03.4) 	`,`	null	`],
	[`	K07.8	`,`	Other dentofacial anomalies 	`,`	null	`],
	[`	K07.9	`,`	Dentofacial anomaly, unspecified 	`,`	null	`],
	[`	K08	`,`	Other disorders of teeth and supporting structures 	`,`	null	`],
	[`	K08.0	`,`	Exfoliation of teeth due to systemic causes 	`,`	null	`],
	[`	K08.1	`,`	Loss of teeth due to accident, extraction or local periodontal disease 	`,`	null	`],
	[`	K08.2	`,`	Atrophy of edentulous alveolar ridge 	`,`	null	`],
	[`	K08.3	`,`	Retained dental root 	`,`	null	`],
	[`	K08.8	`,`	Other specified disorders of teeth and supporting structures Alveolar (process) cleft Enlargement of alveolar ridge NOS Irregular alveolar process Toothache NOS 	`,`	null	`],
	[`	K08.9	`,`	Disorder of teeth and supporting structures, unspecified 	`,`	null	`],
	[`	K09	`,`	Cysts of oral region, not elsewhere classified Incl.: lesions showing histological features both of aneurysmal cyst and of another fibro-osseous lesion Excl.: radicular cyst (K04.8) 	`,`	null	`],
	[`	K09.0	`,`	Developmental odontogenic cysts Cyst: dentigerous eruption follicular gingival lateral periodontal primordial 	`,`	null	`],
	[`	K09.1	`,`	Developmental (nonodontogenic) cysts of oral region Cyst (of): nasolabial [nasoalveolar] nasopalatine duct [incisive canal] 	`,`	null	`],
	[`	K09.2	`,`	Other cysts of jaw Cyst of jaw: NOS aneurysmal haemorrhagic traumatic Excl.: latent bone cyst of jaw (K10.0) Stafne cyst (K10.0) 	`,`	null	`],
	[`	K09.8	`,`	Other cysts of oral region, not elsewhere classified Dermoid cyst Epidermoid cyst Lymphoepithelial cyst of mouth Epstein pearl 	`,`	null	`],
	[`	K09.9	`,`	Cyst of oral region, unspecified 	`,`	null	`],
	[`	K10	`,`	Other diseases of jaws 	`,`	null	`],
	[`	K10.0	`,`	Developmental disorders of jaws Latent bone cyst of jaw Stafne cyst Torus: mandibularis palatinus 	`,`	null	`],
	[`	K10.1	`,`	Giant cell granuloma, central Giant cell granuloma NOS Excl.: peripheral giant cell granuloma (K06.8) 	`,`	null	`],
	[`	K10.2	`,`	Inflammatory conditions of jaws Osteitis Osteomyelitis (neonatal) Osteonecrosis (drug-induced)(radiation-induced) Periostitis of jaw (acute)(chronic)(suppurative) Sequestrum of jaw bone Use additional external cause code (Chapter XX), if desired, to identify radiation, if radiation-induced, or to identify drug, if drug-induced. 	`,`	null	`],
	[`	K10.3	`,`	Alveolitis of jaws Alveolar osteitis Dry socket 	`,`	null	`],
	[`	K10.8	`,`	Other specified diseases of jaws Cherubism Exostosis Fibrous dysplasia of jaw Unilateral condylar: hyperplasia hypoplasia 	`,`	null	`],
	[`	K10.9	`,`	Disease of jaws, unspecified 	`,`	null	`],
	[`	K11	`,`	Diseases of salivary glands 	`,`	null	`],
	[`	K11.0	`,`	Atrophy of salivary gland 	`,`	null	`],
	[`	K11.1	`,`	Hypertrophy of salivary gland 	`,`	null	`],
	[`	K11.2	`,`	Sialoadenitis Excl.: epidemic parotitis (B26.-) uveoparotid fever [Heerfordt] (D86.8) 	`,`	null	`],
	[`	K11.3	`,`	Abscess of salivary gland 	`,`	null	`],
	[`	K11.4	`,`	Fistula of salivary gland Excl.: congenital fistula of salivary gland (Q38.4) 	`,`	null	`],
	[`	K11.5	`,`	Sialolithiasis Calculus Stone of salivary gland or duct 	`,`	null	`],
	[`	K11.6	`,`	Mucocele of salivary gland Mucous: extravasation cyst retention cyst of salivary gland Ranula 	`,`	null	`],
	[`	K11.7	`,`	Disturbances of salivary secretion Hypoptyalism Ptyalism Xerostomia Excl.: dry mouth NOS (R68.2) 	`,`	null	`],
	[`	K11.8	`,`	Other diseases of salivary glands Benign lymphoepithelial lesion of salivary gland Mikulicz disease Necrotizing sialometaplasia Sialectasia Stenosis Stricture of salivary duct Excl.: sicca syndrome [Sjogren] (M35.0) 	`,`	null	`],
	[`	K11.9	`,`	Disease of salivary gland, unspecified Sialoadenopathy NOS 	`,`	null	`],
	[`	K12	`,`	Stomatitis and related lesions Excl.: cancrum oris (A69.0) cheilitis (K13.0) gangrenous stomatitis (A69.0) herpesviral [herpes simplex] gingivostomatitis (B00.2) noma (A69.0) 	`,`	null	`],
	[`	K12.0	`,`	Recurrent oral aphthae Aphthous stomatitis (major)(minor) Bednar aphthae Periadenitis mucosa necrotica recurrens Recurrent aphthous ulcer Stomatitis herpetiformis 	`,`	null	`],
	[`	K12.1	`,`	Other forms of stomatitis Stomatitis: NOS denture ulcerative vesicular 	`,`	null	`],
	[`	K12.2	`,`	Cellulitis and abscess of mouth Cellulitis of mouth (floor) Submandibular abscess Excl.: abscess (of): periapical (K04.6-K04.7) periodontal (K05.2) peritonsillar (J36) salivary gland (K11.3) tongue (K14.0) 	`,`	null	`],
	[`	K12.3	`,`	Oral mucositis (ulcerative) Mucositis(oral) (oropharyngeal): NOS drug-induced radiation induced viral Use additional external cause code (Chapter XX), if desired, to identify external agent Excl.: mucositis (ulcerative) of gastrointestinal tract (except oral cavity and oropharynx) (K92.8) 	`,`	null	`],
	[`	K13	`,`	Other diseases of lip and oral mucosa Incl.: epithelial disturbances of tongue Excl.: certain disorders of gingiva and edentulous alveolar ridge (K05-K06) cysts of oral region (K09.-) diseases of tongue (K14.-) stomatitis and related lesions (K12.-) 	`,`	null	`],
	[`	K13.0	`,`	Diseases of lips Cheilitis: NOS angular exfoliative glandular Cheilodynia Cheilosis Perleche NEC Excl.: ariboflavinosis (E53.0) cheilitis due to radiation-related disorders (L55-L59) perleche due to: candidiasis (B37.8) riboflavin deficiency (E53.0) 	`,`	null	`],
	[`	K13.1	`,`	Cheek and lip biting 	`,`	null	`],
	[`	K13.2	`,`	Leukoplakia and other disturbances of oral epithelium, including tongue Erythroplakia Leukoedema of oral epithelium, including tongue Leukokeratosis nicotina palati Smoker palate Excl.: hairy leukoplakia (K13.3) 	`,`	null	`],
	[`	K13.3	`,`	Hairy leukoplakia 	`,`	null	`],
	[`	K13.4	`,`	Granuloma and granuloma-like lesions of oral mucosa Eosinophilic granuloma Granuloma pyogenicum Verrucous xanthoma of oral mucosa 	`,`	null	`],
	[`	K13.5	`,`	Oral submucous fibrosis Submucous fibrosis of tongue 	`,`	null	`],
	[`	K13.6	`,`	Irritative hyperplasia of oral mucosa Excl.: irritative hyperplasia of edentulous ridge [denture hyperplasia] (K06.2) 	`,`	null	`],
	[`	K13.7	`,`	Other and unspecified lesions of oral mucosa Focal oral mucinosis 	`,`	null	`],
	[`	K14	`,`	Diseases of tongue Excl.: erythroplakia focal epithelial hyperplasia leukoedema leukoplakia of tongue (K13.2) hairy leukoplakia (K13.3) macroglossia (congenital) (Q38.2) submucous fibrosis of tongue (K13.5) 	`,`	null	`],
	[`	K14.0	`,`	Glossitis Abscess Ulceration (traumatic) of tongue Excl.: atrophic glossitis (K14.4) 	`,`	null	`],
	[`	K14.1	`,`	Geographic tongue Benign migratory glossitis Glossitis areata exfoliativa 	`,`	null	`],
	[`	K14.2	`,`	Median rhomboid glossitis 	`,`	null	`],
	[`	K14.3	`,`	Hypertrophy of tongue papillae Black hairy tongue Coated tongue Hypertrophy of foliate papillae Lingua villosa nigra 	`,`	null	`],
	[`	K14.4	`,`	Atrophy of tongue papillae Atrophic glossitis 	`,`	null	`],
	[`	K14.5	`,`	Plicated tongue Fissured Furrowed Scrotal tongue Excl.: fissured tongue, congenital (Q38.3) 	`,`	null	`],
	[`	K14.6	`,`	Glossodynia Glossopyrosis Painful tongue 	`,`	null	`],
	[`	K14.8	`,`	Other diseases of tongue Atrophy Crenated Enlargement Hypertrophy (of) tongue 	`,`	null	`],
	[`	K14.9	`,`	Disease of tongue, unspecified Glossopathy NOS 	`,`	null	`],
	[`	0	`,`	Acute with haemorrhage 	`,`	null	`],
	[`	0.1	`,`	Acute with perforation 	`,`	null	`],
	[`	0.2	`,`	Acute with both haemorrhage and perforation 	`,`	null	`],
	[`	0.3	`,`	Acute without haemorrhage or perforation 	`,`	null	`],
	[`	0.4	`,`	Chronic or unspecified with haemorrhage 	`,`	null	`],
	[`	0.5	`,`	Chronic or unspecified with perforation 	`,`	null	`],
	[`	0.6	`,`	Chronic or unspecified with both haemorrhage and perforation 	`,`	null	`],
	[`	0.7	`,`	Chronic without haemorrhage or perforation 	`,`	null	`],
	[`	0.9	`,`	Unspecified as acute or chronic, without haemorrhage or perforation 	`,`	null	`],
	[`	K20	`,`	Oesophagitis Incl.: Abscess of oesophagus Oesophagitis: NOS chemical peptic Use additional external cause code (Chapter XX), if desired, to identify cause. Excl.: erosion of oesophagus (K22.1) reflux oesophagitis (K21.0) with gastro-oesophageal reflux disease (K21.0) 	`,`	null	`],
	[`	K21	`,`	Gastro-oesophageal reflux disease 	`,`	null	`],
	[`	K21.0	`,`	Gastro-oesophageal reflux disease with oesophagitis Reflux oesophagitis 	`,`	null	`],
	[`	K21.9	`,`	Gastro-oesophageal reflux disease without oesophagitis Oesophageal reflux NOS 	`,`	null	`],
	[`	K22	`,`	Other diseases of oesophagus Excl.: oesophageal varices (I85.-) 	`,`	null	`],
	[`	K22.0	`,`	Achalasia of cardia Achalasia NOS Cardiospasm Excl.: congenital cardiospasm (Q39.5) 	`,`	null	`],
	[`	K22.1	`,`	Ulcer of oesophagus Erosion of oesophagus Ulcer of oesophagus: NOS due to ingestion of: chemicals drugs and medicaments fungal peptic Ulcerative oesophagitis Use additional external cause code (Chapter XX), if desired, to identify cause. 	`,`	null	`],
	[`	K22.2	`,`	Oesophageal obstruction Compression Constriction Stenosis Stricture of oesophagus Excl.: congenital stenosis or stricture of oesophagus (Q39.3) 	`,`	null	`],
	[`	K22.3	`,`	Perforation of oesophagus Rupture of oesophagus Excl.: traumatic perforation of (thoracic) oesophagus (S27.8) 	`,`	null	`],
	[`	K22.4	`,`	Dyskinesia of oesophagus Corkscrew oesophagus Diffuse oesophageal spasm Spasm of oesophagus Excl.: cardiospasm (K22.0) 	`,`	null	`],
	[`	K22.5	`,`	Diverticulum of oesophagus, acquired Oesophageal pouch, acquired Excl.: diverticulum of oesophagus (congenital) (Q39.6) 	`,`	null	`],
	[`	K22.6	`,`	Gastro-oesophageal laceration-haemorrhage syndrome Mallory-Weiss syndrome 	`,`	null	`],
	[`	K22.7	`,`	Barrett oesophagus Barrett: disease syndrome Excl.: Barrett ulcer (K22.1) 	`,`	null	`],
	[`	K22.8	`,`	Other specified diseases of oesophagus Haemorrhage of oesophagus NOS 	`,`	null	`],
	[`	K22.9	`,`	Disease of oesophagus, unspecified 	`,`	null	`],
	[`	K23*	`,`	Disorders of oesophagus in diseases classified elsewhere 	`,`	null	`],
	[`	K23.0*	`,`	Tuberculous oesophagitis (A18.8) 	`,`	null	`],
	[`	K23.1*	`,`	Megaoesophagus in Chagas disease (B57.3) 	`,`	null	`],
	[`	K23.8*	`,`	Disorders of oesophagus in other diseases classified elsewhere 	`,`	null	`],
	[`	K25	`,`	Gastric ulcer [See at the beginning of this block for subdivisions] Incl.: erosion (acute) of stomach ulcer (peptic): pylorus stomach Use additional external cause code (Chapter XX), if desired, to identify drug, if drug-induced. Excl.: acute haemorrhagic erosive gastritis (K29.0) peptic ulcer NOS (K27.-) 	`,`	null	`],
	[`	K26	`,`	Duodenal ulcer [See at the beginning of this block for subdivisions] Incl.: erosion (acute) of duodenum ulcer (peptic): duodenal postpyloric Use additional external cause code (Chapter XX), if desired, to identify drug, if drug-induced. Excl.: peptic ulcer NOS (K27.-) 	`,`	null	`],
	[`	K27	`,`	Peptic ulcer, site unspecified [See at the beginning of this block for subdivisions] Incl.: gastroduodenal ulcer NOS peptic ulcer NOS Excl.: peptic ulcer of newborn (P78.8) 	`,`	null	`],
	[`	K28	`,`	Gastrojejunal ulcer [See at the beginning of this block for subdivisions] Incl.: ulcer (peptic) or erosion: anastomotic gastrocolic gastrointestinal gastrojejunal jejunal marginal stomal Excl.: primary ulcer of small intestine (K63.3) 	`,`	null	`],
	[`	K29	`,`	Gastritis and duodenitis Excl.: eosinophilic gastritis or gastroenteritis (K52.8) Zollinger-Ellison syndrome (E16.4) 	`,`	null	`],
	[`	K29.0	`,`	Acute haemorrhagic gastritis Acute (erosive) gastritis with haemorrhage Excl.: erosion (acute) of stomach (K25.-) 	`,`	null	`],
	[`	K29.1	`,`	Other acute gastritis 	`,`	null	`],
	[`	K29.2	`,`	Alcoholic gastritis 	`,`	null	`],
	[`	K29.3	`,`	Chronic superficial gastritis 	`,`	null	`],
	[`	K29.4	`,`	Chronic atrophic gastritis Gastric atrophy 	`,`	null	`],
	[`	K29.5	`,`	Chronic gastritis, unspecified Chronic gastritis: antral fundal 	`,`	null	`],
	[`	K29.6	`,`	Other gastritis Giant hypertrophic gastritis Granulomatous gastritis Menetrier disease 	`,`	null	`],
	[`	K29.7	`,`	Gastritis, unspecified 	`,`	null	`],
	[`	K29.8	`,`	Duodenitis 	`,`	null	`],
	[`	K29.9	`,`	Gastroduodenitis, unspecified 	`,`	null	`],
	[`	K30	`,`	Functional dyspepsia Incl.: Indigestion Excl.: dyspepsia: nervous (F45.3) neurotic (F45.3) psychogenic (F45.3) heartburn (R12) 	`,`	null	`],
	[`	K31	`,`	Other diseases of stomach and duodenum Incl.: functional disorders of stomach Excl.: diverticulum of duodenum (K57.0-K57.1) gastrointestinal haemorrhage (K92.0-K92.2) 	`,`	null	`],
	[`	K31.0	`,`	Acute dilatation of stomach Acute distension of stomach 	`,`	null	`],
	[`	K31.1	`,`	Adult hypertrophic pyloric stenosis Pyloric stenosis NOS Excl.: congenital or infantile pyloric stenosis (Q40.0) 	`,`	null	`],
	[`	K31.2	`,`	Hourglass stricture and stenosis of stomach Excl.: congenital hourglass stomach (Q40.2) hourglass contraction of stomach (K31.8) 	`,`	null	`],
	[`	K31.3	`,`	Pylorospasm, not elsewhere classified Excl.: pylorospasm: congenital or infantile (Q40.0) neurotic (F45.3) psychogenic (F45.3) 	`,`	null	`],
	[`	K31.4	`,`	Gastric diverticulum Excl.: congenital diverticulum of stomach (Q40.2) 	`,`	null	`],
	[`	K31.5	`,`	Obstruction of duodenum Constriction Stenosis Stricture of duodenum Duodenal ileus (chronic) Excl.: congenital stenosis of duodenum (Q41.0) 	`,`	null	`],
	[`	K31.6	`,`	Fistula of stomach and duodenum Gastrocolic fistula Gastrojejunocolic fistula 	`,`	null	`],
	[`	K31.7	`,`	Polyp of stomach and duodenum Excl.: adenomatous polyp of stomach (D13.1) 	`,`	null	`],
	[`	K31.8	`,`	Other specified diseases of stomach and duodenum Achlorhydria Gastroptosis Hourglass contraction of stomach 	`,`	null	`],
	[`	K31.9	`,`	Disease of stomach and duodenum, unspecified 	`,`	null	`],
	[`	K35	`,`	Acute appendicitis 	`,`	null	`],
	[`	K35.2	`,`	Acute appendicitis with generalized peritonitis Appendicitis (acute) with generalized (diffuse) peritonitis following rupture or perforation 	`,`	null	`],
	[`	K35.3	`,`	Acute appendicitis with localized peritonitis Acute appendicitis (with or without perforation or rupture) with peritonitis: NOS localized Acute appendicitis with peritoneal abscess 	`,`	null	`],
	[`	K35.8	`,`	Acute appendicitis, other and unspecified Acute appendicitis without mention of localized or generalized peritonitis 	`,`	null	`],
	[`	K36	`,`	Other appendicitis Incl.: Appendicitis: chronic recurrent 	`,`	null	`],
	[`	K37	`,`	Unspecified appendicitis 	`,`	null	`],
	[`	K38	`,`	Other diseases of appendix 	`,`	null	`],
	[`	K38.0	`,`	Hyperplasia of appendix 	`,`	null	`],
	[`	K38.1	`,`	Appendicular concretions Faecalith Stercolith of appendix 	`,`	null	`],
	[`	K38.2	`,`	Diverticulum of appendix 	`,`	null	`],
	[`	K38.3	`,`	Fistula of appendix 	`,`	null	`],
	[`	K38.8	`,`	Other specified diseases of appendix Intussusception of appendix 	`,`	null	`],
	[`	K38.9	`,`	Disease of appendix, unspecified 	`,`	null	`],
	[`	K40	`,`	Inguinal hernia Incl.: bubonocele inguinal hernia: NOS direct double indirect oblique scrotal hernia 	`,`	null	`],
	[`	K40.0	`,`	Bilateral inguinal hernia, with obstruction, without gangrene 	`,`	null	`],
	[`	K40.1	`,`	Bilateral inguinal hernia, with gangrene 	`,`	null	`],
	[`	K40.2	`,`	Bilateral inguinal hernia, without obstruction or gangrene Bilateral inguinal hernia NOS 	`,`	null	`],
	[`	K40.3	`,`	Unilateral or unspecified inguinal hernia, with obstruction, without gangrene Inguinal hernia (unilateral): causing obstruction incarcerated irreducible strangulated without gangrene 	`,`	null	`],
	[`	K40.4	`,`	Unilateral or unspecified inguinal hernia, with gangrene Inguinal hernia NOS with gangrene 	`,`	null	`],
	[`	K40.9	`,`	Unilateral or unspecified inguinal hernia, without obstruction or gangrene Inguinal hernia (unilateral) NOS 	`,`	null	`],
	[`	K41	`,`	Femoral hernia 	`,`	null	`],
	[`	K41.0	`,`	Bilateral femoral hernia, with obstruction, without gangrene 	`,`	null	`],
	[`	K41.1	`,`	Bilateral femoral hernia, with gangrene 	`,`	null	`],
	[`	K41.2	`,`	Bilateral femoral hernia, without obstruction or gangrene Bilateral femoral hernia NOS 	`,`	null	`],
	[`	K41.3	`,`	Unilateral or unspecified femoral hernia, with obstruction, without gangrene Femoral hernia (unilateral): causing obstruction incarcerated irreducible strangulated without gangrene 	`,`	null	`],
	[`	K41.4	`,`	Unilateral or unspecified femoral hernia, with gangrene 	`,`	null	`],
	[`	K41.9	`,`	Unilateral or unspecified femoral hernia, without obstruction or gangrene Femoral hernia (unilateral) NOS 	`,`	null	`],
	[`	K42	`,`	Umbilical hernia Incl.: paraumbilical hernia Excl.: omphalocele (Q79.2) 	`,`	null	`],
	[`	K42.0	`,`	Umbilical hernia with obstruction, without gangrene Umbilical hernia: causing obstruction incarcerated irreducible strangulated without gangrene 	`,`	null	`],
	[`	K42.1	`,`	Umbilical hernia with gangrene Gangrenous umbilical hernia 	`,`	null	`],
	[`	K42.9	`,`	Umbilical hernia without obstruction or gangrene Umbilical hernia NOS 	`,`	null	`],
	[`	K43	`,`	Ventral hernia Incl.: hernia: epigastric incisional 	`,`	null	`],
	[`	K43.0	`,`	Incisional hernia with obstruction, without gangrene Incisional hernia: causing obstruction incarcerated irreducible strangulated without gangrene 	`,`	null	`],
	[`	K43.1	`,`	Incisional hernia with gangrene Gangrenous Incisional hernia 	`,`	null	`],
	[`	K43.2	`,`	Incisional hernia without obstruction or gangrene Incisional hernia NOS 	`,`	null	`],
	[`	K43.3	`,`	Parastomal hernia with obstruction, without gangrene Parastomal hernia: causing obstruction incarcerated irreducible strangulated without gangrene 	`,`	null	`],
	[`	K43.4	`,`	Parastomal hernia with gangrene Gangrenous parastomal hernia 	`,`	null	`],
	[`	K43.5	`,`	Parastomal hernia without obstruction or gangrene Parastomal hernia NOS 	`,`	null	`],
	[`	K43.6	`,`	Other and unspecified ventral hernia with gangrene Hernia: epigastric hypogastric midline spigelian subxiphoid Any condition listed under K43.6 causing obstruction incarcerated irreducible strangulated without gangrene 	`,`	null	`],
	[`	K43.7	`,`	Other and unspecified ventral hernia with gangrene Any condition listed under K43.6 specified as gangrenous 	`,`	null	`],
	[`	K43.9	`,`	Other and unspecified ventral hernia without obstruction or gangrene Ventral hernia NOS 	`,`	null	`],
	[`	K44	`,`	Diaphragmatic hernia Incl.: hiatus hernia (oesophageal)(sliding) paraoesophageal hernia Excl.: congenital hernia: diaphragmatic (Q79.0) hiatus (Q40.1) 	`,`	null	`],
	[`	K44.0	`,`	Diaphragmatic hernia with obstruction, without gangrene Diaphragmatic hernia: causing obstruction incarcerated irreducible strangulated without gangrene 	`,`	null	`],
	[`	K44.1	`,`	Diaphragmatic hernia with gangrene Gangrenous diaphragmatic hernia 	`,`	null	`],
	[`	K44.9	`,`	Diaphragmatic hernia without obstruction or gangrene Diaphragmatic hernia NOS 	`,`	null	`],
	[`	K45	`,`	Other abdominal hernia Incl.: hernia: abdominal, specified site NEC lumbar obturator pudendal retroperitoneal sciatic 	`,`	null	`],
	[`	K45.0	`,`	Other specified abdominal hernia with obstruction, without gangrene Any condition listed under K45: causing obstruction incarcerated irreducible strangulated without gangrene 	`,`	null	`],
	[`	K45.1	`,`	Other specified abdominal hernia with gangrene Any condition listed under K45 specified as gangrenous 	`,`	null	`],
	[`	K45.8	`,`	Other specified abdominal hernia without obstruction or gangrene 	`,`	null	`],
	[`	K46	`,`	Unspecified abdominal hernia Incl.: enterocele epiplocele hernia: NOS interstitial intestinal intra-abdominal Excl.: vaginal enterocele (N81.5) 	`,`	null	`],
	[`	K46.0	`,`	Unspecified abdominal hernia with obstruction, without gangrene Any condition listed under K46: causing obstruction incarcerated irreducible strangulated without gangrene 	`,`	null	`],
	[`	K46.1	`,`	Unspecified abdominal hernia with gangrene Any condition listed under K46 specified as gangrenous 	`,`	null	`],
	[`	K46.9	`,`	Unspecified abdominal hernia without obstruction or gangrene Abdominal hernia NOS 	`,`	null	`],
	[`	K50	`,`	Crohn disease [regional enteritis] Incl.: granulomatous enteritis Excl.: ulcerative colitis (K51.-) 	`,`	null	`],
	[`	K50.0	`,`	Crohn disease of small intestine Crohn disease [regional enteritis] of: duodenum ileum jejunum Ileitis: regional terminal Excl.: with Crohn disease of large intestine (K50.8) 	`,`	null	`],
	[`	K50.1	`,`	Crohn disease of large intestine Colitis: granulomatous regional Crohn disease [regional enteritis] of: colon large bowel rectum Excl.: with Crohn disease of small intestine (K50.8) 	`,`	null	`],
	[`	K50.8	`,`	Other Crohn disease Crohn disease of both small and large intestine 	`,`	null	`],
	[`	K50.9	`,`	Crohn disease, unspecified Regional enteritis NOS 	`,`	null	`],
	[`	K51	`,`	Ulcerative colitis 	`,`	null	`],
	[`	K51.0	`,`	Ulcerative (chronic) pancolitis backwash ileitis 	`,`	null	`],
	[`	K51.2	`,`	Ulcerative (chronic) proctitis 	`,`	null	`],
	[`	K51.3	`,`	Ulcerative (chronic) rectosigmoiditis 	`,`	null	`],
	[`	K51.4	`,`	Inflammatory polyps 	`,`	null	`],
	[`	K51.5	`,`	Left sided colitis left hemicolitis 	`,`	null	`],
	[`	K51.8	`,`	Other ulcerative colitis 	`,`	null	`],
	[`	K51.9	`,`	Ulcerative colitis, unspecified 	`,`	null	`],
	[`	K52	`,`	Other noninfective gastroenteritis and colitis 	`,`	null	`],
	[`	K52.0	`,`	Gastroenteritis and colitis due to radiation 	`,`	null	`],
	[`	K52.1	`,`	Toxic gastroenteritis and colitis Drug-induced gastroenteritis and colitis Use additional external cause code (Chapter XX), if desired, to identify drug, if drug-induced, or toxic agent. 	`,`	null	`],
	[`	K52.2	`,`	Allergic and dietetic gastroenteritis and colitis Food hypersensitivity gastroenteritis or colitis 	`,`	null	`],
	[`	K52.3	`,`	Indeterminate colitis 	`,`	null	`],
	[`	K52.8	`,`	Other specified noninfective gastroenteritis and colitis Collagenous colitis Eosinophilic gastritis or gastroenteritis Lymphocytic colitis Microscopic colitis (collagenous colitis or lymphocytic colitis) 	`,`	null	`],
	[`	K52.9	`,`	Noninfective gastroenteritis and colitis, unspecified Diarrhoea Enteritis Ileitis Jejunitis Sigmoiditis specified as noninfectious Excl.: colitis, diarrhoea, enteritis, gastroenteritis: infectious (A09.0) unspecified origin (A09.9) functional diarrhoea (K59.1) neonatal diarrhoea (noninfective) (P78.3) psychogenic diarrhoea (F45.3) 	`,`	null	`],
	[`	K55	`,`	Vascular disorders of intestine Excl.: necrotizing enterocolitis of fetus or newborn (P77) 	`,`	null	`],
	[`	K55.0	`,`	Acute vascular disorders of intestine Acute: fulminant ischaemic colitis intestinal infarction small intestine ischaemia Mesenteric (artery)(vein): embolism infarction thrombosis Subacute ischaemic colitis 	`,`	null	`],
	[`	K55.1	`,`	Chronic vascular disorders of intestine Chronic ischaemic: colitis enteritis enterocolitis Ischaemic stricture of intestine Mesenteric: atherosclerosis vascular insufficiency 	`,`	null	`],
	[`	K55.2	`,`	Angiodysplasia of colon 	`,`	null	`],
	[`	K55.8	`,`	Other vascular disorders of intestine 	`,`	null	`],
	[`	K55.9	`,`	Vascular disorder of intestine, unspecified Ischaemic: colitis enteritis enterocolitis NOS 	`,`	null	`],
	[`	K56	`,`	Paralytic ileus and intestinal obstruction without hernia Excl.: congenital stricture or stenosis of intestine (Q41-Q42) ischaemic stricture of intestine (K55.1) meconium ileus (E84.1) obstruction of duodenum (K31.5) postoperative intestinal obstruction (K91.3) stenosis of anus or rectum (K62.4) with hernia (K40-K46) 	`,`	null	`],
	[`	K56.0	`,`	Paralytic ileus Paralysis of: bowel colon intestine Excl.: gallstone ileus (K56.3) ileus NOS (K56.7) obstructive ileus NOS (K56.6) 	`,`	null	`],
	[`	K56.1	`,`	Intussusception Intussusception or invagination of: bowel colon intestine rectum Excl.: intussusception of appendix (K38.8) 	`,`	null	`],
	[`	K56.2	`,`	Volvulus Strangulation Torsion Twist of colon or intestine 	`,`	null	`],
	[`	K56.3	`,`	Gallstone ileus Obstruction of intestine by gallstone 	`,`	null	`],
	[`	K56.4	`,`	Other impaction of intestine Enterolith Impaction (of): colon faecal 	`,`	null	`],
	[`	K56.5	`,`	Intestinal adhesions [bands] with obstruction Peritoneal adhesions [bands] with intestinal obstruction 	`,`	null	`],
	[`	K56.6	`,`	Other and unspecified intestinal obstruction Enterostenosis Obstructive ileus NOS Occlusion Stenosis Stricture of colon or intestine Excl.: other and unspecified neonatal intestinal obstruction classifiable to P76.8, P76.9 	`,`	null	`],
	[`	K56.7	`,`	Ileus, unspecified 	`,`	null	`],
	[`	K57	`,`	Diverticular disease of intestine Incl.: diverticulitis diverticulosis diverticulum of (small)(large) intestine Excl.: congenital diverticulum of intestine (Q43.8) diverticulum of appendix (K38.2) Meckel diverticulum (Q43.0) 	`,`	null	`],
	[`	K57.0	`,`	Diverticular disease of small intestine with perforation and abscess Diverticular disease of small intestine with peritonitis Excl.: diverticular disease of both small and large intestine with perforation and abscess (K57.4) 	`,`	null	`],
	[`	K57.1	`,`	Diverticular disease of small intestine without perforation or abscess Diverticular disease of small intestine NOS Excl.: diverticular disease of both small and large intestine without perforation or abscess (K57.5) 	`,`	null	`],
	[`	K57.2	`,`	Diverticular disease of large intestine with perforation and abscess Diverticular disease of colon with peritonitis Excl.: diverticular disease of both small and large intestine with perforation and abscess (K57.4) 	`,`	null	`],
	[`	K57.3	`,`	Diverticular disease of large intestine without perforation or abscess Diverticular disease of colon NOS Excl.: diverticular disease of both small and large intestine without perforation or abscess (K57.5) 	`,`	null	`],
	[`	K57.4	`,`	Diverticular disease of both small and large intestine with perforation and abscess Diverticular disease of both small and large intestine with peritonitis 	`,`	null	`],
	[`	K57.5	`,`	Diverticular disease of both small and large intestine without perforation or abscess Diverticular disease of both small and large intestine NOS 	`,`	null	`],
	[`	K57.8	`,`	Diverticular disease of intestine, part unspecified, with perforation and abscess Diverticular disease of intestine NOS with peritonitis 	`,`	null	`],
	[`	K57.9	`,`	Diverticular disease of intestine, part unspecified, without perforation or abscess Diverticular disease of intestine NOS 	`,`	null	`],
	[`	K58	`,`	Irritable bowel syndrome Incl.: irritable colon 	`,`	null	`],
	[`	K58.0	`,`	Irritable bowel syndrome with diarrhoea 	`,`	null	`],
	[`	K58.9	`,`	Irritable bowel syndrome without diarrhoea Irritable bowel syndrome NOS 	`,`	null	`],
	[`	K59	`,`	Other functional intestinal disorders Excl.: change in bowel habit NOS (R19.4) functional disorders of stomach (K31.-) intestinal malabsorption (K90.-) psychogenic intestinal disorders (F45.3) 	`,`	null	`],
	[`	K59.0	`,`	Constipation 	`,`	null	`],
	[`	K59.1	`,`	Functional diarrhoea 	`,`	null	`],
	[`	K59.2	`,`	Neurogenic bowel, not elsewhere classified 	`,`	null	`],
	[`	K59.3	`,`	Megacolon, not elsewhere classified Dilatation of colon Toxic megacolon Use additional external cause code (Chapter XX), if desired, to identify toxic agent. Excl.: megacolon (due to) (in): Chagas disease (B57.3) Clostridium difficile (A04.7) congenital (aganglionic) (Q43.1) Hirschsprung disease (Q43.1) 	`,`	null	`],
	[`	K59.4	`,`	Anal spasm Proctalgia fugax 	`,`	null	`],
	[`	K59.8	`,`	Other specified functional intestinal disorders Atony of colon 	`,`	null	`],
	[`	K59.9	`,`	Functional intestinal disorder, unspecified 	`,`	null	`],
	[`	K60	`,`	Fissure and fistula of anal and rectal regions Excl.: with abscess or cellulitis (K61.-) 	`,`	null	`],
	[`	K60.0	`,`	Acute anal fissure 	`,`	null	`],
	[`	K60.1	`,`	Chronic anal fissure 	`,`	null	`],
	[`	K60.2	`,`	Anal fissure, unspecified 	`,`	null	`],
	[`	K60.3	`,`	Anal fistula 	`,`	null	`],
	[`	K60.4	`,`	Rectal fistula Fistula of rectum to skin Excl.: fistula: rectovaginal (N82.3) vesicorectal (N32.1) 	`,`	null	`],
	[`	K60.5	`,`	Anorectal fistula 	`,`	null	`],
	[`	K61	`,`	Abscess of anal and rectal regions Incl.: abscess cellulitis of anal and rectal regions with or without fistula 	`,`	null	`],
	[`	K61.0	`,`	Anal abscess Perianal abscess Excl.: intrasphincteric abscess (K61.4) 	`,`	null	`],
	[`	K61.1	`,`	Rectal abscess Perirectal abscess Excl.: ischiorectal abscess (K61.3) 	`,`	null	`],
	[`	K61.2	`,`	Anorectal abscess 	`,`	null	`],
	[`	K61.3	`,`	Ischiorectal abscess Abscess of ischiorectal fossa 	`,`	null	`],
	[`	K61.4	`,`	Intrasphincteric abscess 	`,`	null	`],
	[`	K62	`,`	Other diseases of anus and rectum Incl.: anal canal Excl.: colostomy and enterostomy malfunction (K91.4) faecal incontinence (R15) haemorrhoids (K64.-) ulcerative proctitis (K51.2) 	`,`	null	`],
	[`	K62.0	`,`	Anal polyp 	`,`	null	`],
	[`	K62.1	`,`	Rectal polyp Excl.: adenomatous polyp (D12.8) 	`,`	null	`],
	[`	K62.2	`,`	Anal prolapse Prolapse of anal canal 	`,`	null	`],
	[`	K62.3	`,`	Rectal prolapse Prolapse of rectal mucosa 	`,`	null	`],
	[`	K62.4	`,`	Stenosis of anus and rectum Stricture of anus (sphincter) K62.5 Haemorrhage of anus and rectum Excl.: neonatal rectal haemorrhage (P54.2) 	`,`	null	`],
	[`	K62.6	`,`	Ulcer of anus and rectum Ulcer: solitary stercoral Excl.: fissure and fistula of anus and rectum (K60.-) in ulcerative colitis (K51.-) 	`,`	null	`],
	[`	K62.7	`,`	Radiation proctitis 	`,`	null	`],
	[`	K62.8	`,`	Other specified diseases of anus and rectum Proctitis NOS 	`,`	null	`],
	[`	K62.9	`,`	Disease of anus and rectum, unspecified 	`,`	null	`],
	[`	K63	`,`	Other diseases of intestine 	`,`	null	`],
	[`	K63.0	`,`	Abscess of intestine Excl.: abscess of: anal and rectal regions (K61.-) appendix (K35.3) with diverticular disease (K57.-) 	`,`	null	`],
	[`	K63.1	`,`	Perforation of intestine (nontraumatic) Excl.: perforation (nontraumatic) of: appendix (K35.2, K35.3) duodenum (K26.-) with diverticular disease (K57.-) 	`,`	null	`],
	[`	K63.2	`,`	Fistula of intestine Excl.: fistula (of): anal and rectal regions (K60.-) appendix (K38.3) duodenum (K31.6) intestinal-genital, female (N82.2-N82.4) vesicointestinal (N32.1) 	`,`	null	`],
	[`	K63.3	`,`	Ulcer of intestine Primary ulcer of small intestine Excl.: ulcer (of): anus or rectum (K62.6) duodenal (K26.-) gastrointestinal (K28.-) gastrojejunal (K28.-) jejunal (K28.-) peptic, site unspecified (K27.-) ulcerative colitis (K51.-) 	`,`	null	`],
	[`	K63.4	`,`	Enteroptosis 	`,`	null	`],
	[`	K63.5	`,`	Polyp of colon Excl.: adenomatous polyp of colon (D12.6) polyposis of colon (D12.6) 	`,`	null	`],
	[`	K63.8	`,`	Other specified diseases of intestine 	`,`	null	`],
	[`	K63.9	`,`	Disease of intestine, unspecified 	`,`	null	`],
	[`	K64	`,`	Haemorrhoids and perianal venous thrombosis Incl.: piles Excl.: complicating: childbirth and the puerperium (O87.2) pregnancy (O22.4) 	`,`	null	`],
	[`	K64.0	`,`	First degree haemorrhoids Grade/stage I haemorrhoids Haemorrhoids (bleeding) without prolapse outside of anal canal 	`,`	null	`],
	[`	K64.1	`,`	Second degree haemorrhoids Grade/stage II haemorrhoids Haemorrhoids (bleeding) that prolapse with straining, but retract spontaneously 	`,`	null	`],
	[`	K64.2	`,`	Third degree haemorrhoids Grade/stage III haemorrhoids Haemorrhoids (bleeding) that prolapse with straining and require manual replacement back inside anal canal 	`,`	null	`],
	[`	K64.3	`,`	Fourth degree haemorrhoids Grade/stage IV haemorrhoids Haemorrhoids (bleeding) with prolapsed tissue that cannot be manually replaced 	`,`	null	`],
	[`	K64.4	`,`	Residual haemorrhoidal skin tags Skin tags of anus 	`,`	null	`],
	[`	K64.5	`,`	Perianal venous thrombosis Perianal haematoma 	`,`	null	`],
	[`	K64.8	`,`	Other specified haemorrhoids 	`,`	null	`],
	[`	K64.9	`,`	Haemorrhoids, unspecified Haemorrhoids (bleeding): NOS without mention of degree 	`,`	null	`],
	[`	K65	`,`	Peritonitis Excl.: peritonitis: aseptic (T81.6) benign paroxysmal (E85.0) chemical (T81.6) due to talc or other foreign substance (T81.6) neonatal (P78.0-P78.1) pelvic, female (N73.3-N73.5) periodic familial (E85.0) puerperal (O85) with or following: abortion or ectopic or molar pregnancy (O00-O07, O08.0) appendicitis (K35.-) diverticular disease of intestine (K57.-) 	`,`	null	`],
	[`	K65.0	`,`	Acute peritonitis Abscess (of): abdominopelvic mesenteric omentum peritoneum retrocaecal retroperitoneal subdiaphragmatic subhepatic subphrenic Peritonitis (acute): generalized pelvic, male subphrenic suppurative Use additional code (B95-B98), if desired, to identify infectious agent. 	`,`	null	`],
	[`	K65.8	`,`	Other peritonitis Chronic proliferative peritonitis Mesenteric: fat necrosis saponification Peritonitis due to: bile urine 	`,`	null	`],
	[`	K65.9	`,`	Peritonitis, unspecified 	`,`	null	`],
	[`	K66	`,`	Other disorders of peritoneum Excl.: ascites (R18) 	`,`	null	`],
	[`	K66.0	`,`	Peritoneal adhesions Adhesions (of): abdominal (wall) diaphragm intestine male pelvis mesenteric omentum stomach Adhesive bands Excl.: adhesions [bands] (of): female pelvis (N73.6) with intestinal obstruction (K56.5) 	`,`	null	`],
	[`	K66.1	`,`	Haemoperitoneum Excl.: traumatic haemoperitoneum (S36.8) 	`,`	null	`],
	[`	K66.8	`,`	Other specified disorders of peritoneum 	`,`	null	`],
	[`	K66.9	`,`	Disorder of peritoneum, unspecified 	`,`	null	`],
	[`	K67*	`,`	Disorders of peritoneum in infectious diseases classified elsewhere 	`,`	null	`],
	[`	K67.0*	`,`	Chlamydial peritonitis (A74.8) 	`,`	null	`],
	[`	K67.1*	`,`	Gonococcal peritonitis (A54.8) 	`,`	null	`],
	[`	K67.2*	`,`	Syphilitic peritonitis (A52.7) 	`,`	null	`],
	[`	K67.3*	`,`	Tuberculous peritonitis (A18.3) 	`,`	null	`],
	[`	K67.8*	`,`	Other disorders of peritoneum in infectious diseases classified elsewhere 	`,`	null	`],
	[`	K70	`,`	Alcoholic liver disease 	`,`	null	`],
	[`	K70.0	`,`	Alcoholic fatty liver 	`,`	null	`],
	[`	K70.1	`,`	Alcoholic hepatitis 	`,`	null	`],
	[`	K70.2	`,`	Alcoholic fibrosis and sclerosis of liver 	`,`	null	`],
	[`	K70.3	`,`	Alcoholic cirrhosis of liver Alcoholic cirrhosis NOS 	`,`	null	`],
	[`	K70.4	`,`	Alcoholic hepatic failure Alcoholic hepatic failure: NOS acute chronic subacute with or without hepatic coma 	`,`	null	`],
	[`	K70.9	`,`	Alcoholic liver disease, unspecified 	`,`	null	`],
	[`	K71	`,`	Toxic liver disease Incl.: drug-induced: idiosyncratic (unpredictable) liver disease toxic (predictable) liver disease Use additional external cause code (Chapter XX), if desired, to identify toxic agent. Excl.: alcoholic liver disease (K70.-) Budd-Chiari syndrome (I82.0) 	`,`	null	`],
	[`	K71.0	`,`	Toxic liver disease with cholestasis Cholestasis with hepatocyte injury "Pure" cholestasis 	`,`	null	`],
	[`	K71.1	`,`	Toxic liver disease with hepatic necrosis Hepatic failure (acute)(chronic) due to drugs 	`,`	null	`],
	[`	K71.2	`,`	Toxic liver disease with acute hepatitis 	`,`	null	`],
	[`	K71.3	`,`	Toxic liver disease with chronic persistent hepatitis 	`,`	null	`],
	[`	K71.4	`,`	Toxic liver disease with chronic lobular hepatitis 	`,`	null	`],
	[`	K71.5	`,`	Toxic liver disease with chronic active hepatitis Toxic liver disease with lupoid hepatitis 	`,`	null	`],
	[`	K71.6	`,`	Toxic liver disease with hepatitis, not elsewhere classified 	`,`	null	`],
	[`	K71.7	`,`	Toxic liver disease with fibrosis and cirrhosis of liver 	`,`	null	`],
	[`	K71.8	`,`	Toxic liver disease with other disorders of liver Toxic liver disease with: focal nodular hyperplasia hepatic granulomas peliosis hepatis veno-occlusive disease of liver 	`,`	null	`],
	[`	K71.9	`,`	Toxic liver disease, unspecified 	`,`	null	`],
	[`	K72	`,`	Hepatic failure, not elsewhere classified Incl.: hepatic: coma NOS encephalopathy NOS hepatitis: fulminant malignant NEC, with hepatic failure liver (cell) necrosis with hepatic failure yellow liver atrophy or dystrophy Excl.: alcoholic hepatic failure (K70.4) hepatic failure complicating: abortion or ectopic or molar pregnancy (O00-O07, O08.8) pregnancy, childbirth and the puerperium (O26.6) icterus of fetus and newborn (P55-P59) viral hepatitis (B15-B19) with toxic liver disease (K71.1) 	`,`	null	`],
	[`	K72.0	`,`	Acute and subacute hepatic failure Acute non-viral hepatitis NOS 	`,`	null	`],
	[`	K72.1	`,`	Chronic hepatic failure 	`,`	null	`],
	[`	K72.9	`,`	Hepatic failure, unspecified 	`,`	null	`],
	[`	K73	`,`	Chronic hepatitis, not elsewhere classified Excl.: hepatitis (chronic): alcoholic (K70.1) drug-induced (K71.-) granulomatous NEC (K75.3) reactive, nonspecific (K75.2) viral (B15-B19) 	`,`	null	`],
	[`	K73.0	`,`	Chronic persistent hepatitis, not elsewhere classified 	`,`	null	`],
	[`	K73.1	`,`	Chronic lobular hepatitis, not elsewhere classified 	`,`	null	`],
	[`	K73.2	`,`	Chronic active hepatitis, not elsewhere classified 	`,`	null	`],
	[`	K73.8	`,`	Other chronic hepatitis, not elsewhere classified 	`,`	null	`],
	[`	K73.9	`,`	Chronic hepatitis, unspecified 	`,`	null	`],
	[`	K74	`,`	Fibrosis and cirrhosis of liver Excl.: alcoholic fibrosis of liver (K70.2) cardiac sclerosis of liver (K76.1) cirrhosis (of liver): alcoholic (K70.3) congenital (P78.8) with toxic liver disease (K71.7) 	`,`	null	`],
	[`	K74.0	`,`	Hepatic fibrosis 	`,`	null	`],
	[`	K74.1	`,`	Hepatic sclerosis 	`,`	null	`],
	[`	K74.2	`,`	Hepatic fibrosis with hepatic sclerosis 	`,`	null	`],
	[`	K74.3	`,`	Primary biliary cirrhosis Chronic nonsuppurative destructive cholangitis 	`,`	null	`],
	[`	K74.4	`,`	Secondary biliary cirrhosis 	`,`	null	`],
	[`	K74.5	`,`	Biliary cirrhosis, unspecified 	`,`	null	`],
	[`	K74.6	`,`	Other and unspecified cirrhosis of liver Cirrhosis (of liver): NOS cryptogenic macronodular micronodular mixed type portal postnecrotic 	`,`	null	`],
	[`	K75	`,`	Other inflammatory liver diseases Excl.: chronic hepatitis NEC (K73.-) hepatitis: acute or subacute: NOS (B17.9) Non-viral (K72.0) viral (B15-B19) toxic liver disease (K71.-) 	`,`	null	`],
	[`	K75.0	`,`	Abscess of liver Hepatic abscess: NOS cholangitic haematogenic lymphogenic pylephlebitic Excl.: amoebic liver abscess (A06.4) cholangitis without liver abscess (K83.0) pylephlebitis without liver abscess (K75.1) 	`,`	null	`],
	[`	K75.1	`,`	Phlebitis of portal vein Pylephlebitis Excl.: pylephlebitic liver abscess (K75.0) 	`,`	null	`],
	[`	K75.2	`,`	Nonspecific reactive hepatitis 	`,`	null	`],
	[`	K75.3	`,`	Granulomatous hepatitis, not elsewhere classified 	`,`	null	`],
	[`	K75.4	`,`	Autoimmune hepatitis Lupoid hepatitis NEC 	`,`	null	`],
	[`	K75.8	`,`	Other specified inflammatory liver diseases Nonalcoholic steatohepatitis [NASH] 	`,`	null	`],
	[`	K75.9	`,`	Inflammatory liver disease, unspecified Hepatitis NOS 	`,`	null	`],
	[`	K76	`,`	Other diseases of liver Excl.: alcoholic liver disease (K70.-) amyloid degeneration of liver (E85.-) cystic disease of liver (congenital) (Q44.6) hepatic vein thrombosis (I82.0) hepatomegaly NOS (R16.0) portal vein thrombosis (I81) toxic liver disease (K71.-) 	`,`	null	`],
	[`	K76.0	`,`	Fatty (change of) liver, not elsewhere classified Nonalcoholic fatty liver disease [NAFLD] Excl.: nonalcoholic steatohepatitis (K75.8) 	`,`	null	`],
	[`	K76.1	`,`	Chronic passive congestion of liver Cardiac: cirrhosis (so-called) sclerosis of liver 	`,`	null	`],
	[`	K76.2	`,`	Central haemorrhagic necrosis of liver Excl.: liver necrosis with hepatic failure (K72.-) 	`,`	null	`],
	[`	K76.3	`,`	Infarction of liver 	`,`	null	`],
	[`	K76.4	`,`	Peliosis hepatis Hepatic angiomatosis 	`,`	null	`],
	[`	K76.5	`,`	Hepatic veno-occlusive disease Excl.: Budd-Chiari syndrome (I82.0) 	`,`	null	`],
	[`	K76.6	`,`	Portal hypertension 	`,`	null	`],
	[`	K76.7	`,`	Hepatorenal syndrome Excl.: following labour and delivery (O90.4) 	`,`	null	`],
	[`	K76.8	`,`	Other specified diseases of liver Simple cyst of liver Focal nodular hyperplasia of liver Hepatoptosis 	`,`	null	`],
	[`	K76.9	`,`	Liver disease, unspecified 	`,`	null	`],
	[`	K77*	`,`	Liver disorders in diseases classified elsewhere 	`,`	null	`],
	[`	K77.0*	`,`	Liver disorders in infectious and parasitic diseases classified elsewhere Hepatitis: cytomegaloviral (B25.1) herpesviral [herpes simplex] (B00.8) toxoplasma (B58.1) Hepatosplenic schistosomiasis (B65.-) Portal hypertension in schistosomiasis (B65.-) Syphilitic liver disease (A52.7) 	`,`	null	`],
	[`	K77.8*	`,`	Liver disorders in other diseases classified elsewhere Hepatic granulomas in: berylliosis (J63.2) sarcoidosis (D86.8) 	`,`	null	`],
	[`	K80	`,`	Cholelithiasis 	`,`	null	`],
	[`	K80.0	`,`	Calculus of gallbladder with acute cholecystitis Any condition listed in K80.2 with acute cholecystitis 	`,`	null	`],
	[`	K80.1	`,`	Calculus of gallbladder with other cholecystitis Any condition listed in K80.2 with cholecystitis (chronic) Cholecystitis with cholelithiasis NOS 	`,`	null	`],
	[`	K80.2	`,`	Calculus of gallbladder without cholecystitis Cholecystolithiasis Cholelithiasis Colic (recurrent) of gallbladder Gallstone (impacted) of: cystic duct gallbladder unspecified or without cholecystitis 	`,`	null	`],
	[`	K80.3	`,`	Calculus of bile duct with cholangitis Any condition listed in K80.5 with cholangitis 	`,`	null	`],
	[`	K80.4	`,`	Calculus of bile duct with cholecystitis Any condition listed in K80.5 with cholecystitis (with cholangitis) 	`,`	null	`],
	[`	K80.5	`,`	Calculus of bile duct without cholangitis or cholecystitis Choledocholithiasis Gallstone (impacted) of: bile duct NOS common duct hepatic duct Hepatic: cholelithiasis colic (recurrent) unspecified or without cholangitis or cholecystitis 	`,`	null	`],
	[`	K80.8	`,`	Other cholelithiasis 	`,`	null	`],
	[`	K81	`,`	Cholecystitis Excl.: with cholelithiasis (K80.-) 	`,`	null	`],
	[`	K81.0	`,`	Acute cholecystitis Abscess of gallbladder Angiocholecystitis Cholecystitis: emphysematous (acute) gangrenous suppurative Empyema of gallbladder Gangrene of gallbladder without calculus 	`,`	null	`],
	[`	K81.1	`,`	Chronic cholecystitis 	`,`	null	`],
	[`	K81.8	`,`	Other cholecystitis 	`,`	null	`],
	[`	K81.9	`,`	Cholecystitis, unspecified 	`,`	null	`],
	[`	K82	`,`	Other diseases of gallbladder Excl.: nonvisualization of gallbladder (R93.2) postcholecystectomy syndrome (K91.5) 	`,`	null	`],
	[`	K82.0	`,`	Obstruction of gallbladder Occlusion Stenosis Stricture of cystic duct or gallbladder without calculus Excl.: with cholelithiasis (K80.-) 	`,`	null	`],
	[`	K82.1	`,`	Hydrops of gallbladder Mucocele of gallbladder 	`,`	null	`],
	[`	K82.2	`,`	Perforation of gallbladder Rupture of cystic duct or gallbladder 	`,`	null	`],
	[`	K82.3	`,`	Fistula of gallbladder Cholecystocolic Cholecystoduodenal fistula 	`,`	null	`],
	[`	K82.4	`,`	Cholesterolosis of gallbladder Strawberry gallbladder 	`,`	null	`],
	[`	K82.8	`,`	Other specified diseases of gallbladder Adhesions Atrophy Cyst Dyskinesia Hypertrophy Nonfunctioning Ulcer of cystic duct or gallbladder 	`,`	null	`],
	[`	K82.9	`,`	Disease of gallbladder, unspecified K83 Other diseases of biliary tract Excl.: the listed conditions involving the: cystic duct (K81-K82) gallbladder (K81-K82) postcholecystectomy syndrome (K91.5) 	`,`	null	`],
	[`	K83.0	`,`	Cholangitis Cholangitis: NOS ascending primary recurrent sclerosing secondary stenosing suppurative Excl.: cholangitic liver abscess (K75.0) cholangitis with choledocholithiasis (K80.3-K80.4) chronic nonsuppurative destructive cholangitis (K74.3) 	`,`	null	`],
	[`	K83.1	`,`	Obstruction of bile duct Occlusion Stenosis Stricture of bile duct without calculus Excl.: with cholelithiasis (K80.-) 	`,`	null	`],
	[`	K83.2	`,`	Perforation of bile duct Rupture of bile duct 	`,`	null	`],
	[`	K83.3	`,`	Fistula of bile duct Choledochoduodenal fistula 	`,`	null	`],
	[`	K83.4	`,`	Spasm of sphincter of Oddi 	`,`	null	`],
	[`	K83.5	`,`	Biliary cyst 	`,`	null	`],
	[`	K83.8	`,`	Other specified diseases of biliary tract Adhesions Atrophy Hypertrophy Ulcer of bile duct 	`,`	null	`],
	[`	K83.9	`,`	Disease of biliary tract, unspecified 	`,`	null	`],
	[`	K85	`,`	Acute pancreatitis Incl.: Abscess of pancreas Necrosis of pancreas: acute infective Pancreatitis: NOS acute (recurrent) haemorrhagic subacute suppurative 	`,`	null	`],
	[`	K85.0	`,`	Idiopathic acute pancreatitis 	`,`	null	`],
	[`	K85.1	`,`	Biliary acute pancreatitis Gallstone pancreatitis 	`,`	null	`],
	[`	K85.2	`,`	Alcohol-induced acute pancreatitis 	`,`	null	`],
	[`	K85.3	`,`	Drug-induced acute pancreatitis Use additional external cause code (Chapter XX), if desired, to identify drug 	`,`	null	`],
	[`	K85.8	`,`	Other acute pancreatitis 	`,`	null	`],
	[`	K85.9	`,`	Acute pancreatitis, unspecified 	`,`	null	`],
	[`	K86	`,`	Other diseases of pancreas Excl.: fibrocystic disease of pancreas (E84.-) islet cell tumour (of pancreas) (D13.7) pancreatic steatorrhoea (K90.3) 	`,`	null	`],
	[`	K86.0	`,`	Alcohol-induced chronic pancreatitis 	`,`	null	`],
	[`	K86.1	`,`	Other chronic pancreatitis Chronic pancreatitis: NOS infectious recurrent relapsing 	`,`	null	`],
	[`	K86.2	`,`	Cyst of pancreas 	`,`	null	`],
	[`	K86.3	`,`	Pseudocyst of pancreas 	`,`	null	`],
	[`	K86.8	`,`	Other specified diseases of pancreas Atrophy Calculus Cirrhosis Fibrosis of pancreas Pancreatic: infantilism necrosis: NOS aseptic fat 	`,`	null	`],
	[`	K86.9	`,`	Disease of pancreas, unspecified 	`,`	null	`],
	[`	K87*	`,`	Disorders of gallbladder, biliary tract and pancreas in diseases classified elsewhere 	`,`	null	`],
	[`	K87.0*	`,`	Disorders of gallbladder and biliary tract in diseases classified elsewhere 	`,`	null	`],
	[`	K87.1*	`,`	Disorders of pancreas in diseases classified elsewhere Cytomegaloviral pancreatitis (B25.2) Mumps pancreatitis (B26.3) 	`,`	null	`],
	[`	K90	`,`	Intestinal malabsorption Excl.: following gastrointestinal surgery (K91.2) 	`,`	null	`],
	[`	K90.0	`,`	Coeliac disease Gluten-sensitive enteropathy Idiopathic steatorrhoea Nontropical sprue 	`,`	null	`],
	[`	K90.1	`,`	Tropical sprue Sprue NOS Tropical steatorrhoea 	`,`	null	`],
	[`	K90.2	`,`	Blind loop syndrome, not elsewhere classified Blind loop syndrome NOS Excl.: blind loop syndrome: congenital (Q43.8) postsurgical (K91.2) 	`,`	null	`],
	[`	K90.3	`,`	Pancreatic steatorrhoea 	`,`	null	`],
	[`	K90.4	`,`	Malabsorption due to intolerance, not elsewhere classified Malabsorption due to intolerance to: carbohydrate fat protein starch Excl.: gluten-sensitive enteropathy (K90.0) lactose intolerance (E73.-) 	`,`	null	`],
	[`	K90.8	`,`	Other intestinal malabsorption Whipple disease (M14.8*) 	`,`	null	`],
	[`	K90.9	`,`	Intestinal malabsorption, unspecified 	`,`	null	`],
	[`	K91	`,`	Postprocedural disorders of digestive system, not elsewhere classified Excl.: gastrojejunal ulcer (K28.-) radiation: colitis (K52.0) gastroenteritis (K52.0) proctitis (K62.7) 	`,`	null	`],
	[`	K91.0	`,`	Vomiting following gastrointestinal surgery 	`,`	null	`],
	[`	K91.1	`,`	Postgastric surgery syndromes Syndrome: dumping postgastrectomy postvagotomy 	`,`	null	`],
	[`	K91.2	`,`	Postsurgical malabsorption, not elsewhere classified Postsurgical blind loop syndrome Excl.: malabsorption: osteomalacia in adults (M83.2) osteoporosis, postsurgical (M81.3) 	`,`	null	`],
	[`	K91.3	`,`	Postoperative intestinal obstruction 	`,`	null	`],
	[`	K91.4	`,`	Colostomy and enterostomy malfunction 	`,`	null	`],
	[`	K91.5	`,`	Postcholecystectomy syndrome 	`,`	null	`],
	[`	K91.8	`,`	Other postprocedural disorders of digestive system, not elsewhere classified 	`,`	null	`],
	[`	K91.9	`,`	Postprocedural disorder of digestive system, unspecified 	`,`	null	`],
	[`	K92	`,`	Other diseases of digestive system Excl.: neonatal gastrointestinal haemorrhage (P54.0-P54.3) 	`,`	null	`],
	[`	K92.0	`,`	Haematemesis 	`,`	null	`],
	[`	K92.1	`,`	Melaena Excl.: occult blood in faeces (R19.5) 	`,`	null	`],
	[`	K92.2	`,`	Gastrointestinal haemorrhage, unspecified Haemorrhage: gastric NOS intestinal NOS Excl.: acute haemorrhagic gastritis (K29.0) haemorrhage of anus and rectum (K62.5) with peptic ulcer (K25-K28) 	`,`	null	`],
	[`	K92.8	`,`	Other specified diseases of digestive system 	`,`	null	`],
	[`	K92.9	`,`	Disease of digestive system, unspecified 	`,`	null	`],
	[`	K93*	`,`	Disorders of other digestive organs in diseases classified elsewhere 	`,`	null	`],
	[`	K93.0*	`,`	Tuberculous disorders of intestines, peritoneum and mesenteric glands (A18.3) Excl.: tuberculous peritonitis (K67.3*) 	`,`	null	`],
	[`	K93.1*	`,`	Megacolon in Chagas disease (B57.3) 	`,`	null	`],
	[`	K93.8*	`,`	Disorders of other specified digestive organs in diseases classified elsewhere 	`,`	null	`],
							
];								
				
							
							
				
	
let CodeRangeK ={
	f0:function(val1=(-1),val2=(0)){
		let Range1 = KCodes.slice(val1,val2);
		Range1.reverse();
		document.documentElement.innerHTML += `<br>Showing K Codes ${Range1.length} items(s)`;

		for(value1 in Range1){
			    document.documentElement.style.cssText += "background-color:tan;";
				document.getElementById('kcodesTR').outerHTML += `<tr><td style="background-color:navy;color:white;width:5%;padding:40px;border:2px solid white;font-weight:900;font-size:40px;text-align:center;">${Range1[value1][0]}</td><td style="background-color:black;color:white;width:90%;padding:20px;border:2px solid white;font-size:30px;">${Range1[value1][1]}</td><td style="background-color:navy;color:white;width:5%;padding:20px;border:2px solid white;font-weight:900;font-size:40px;text-align:center;">${Range1[value1][2]}</td></tr>`;			
		}

	},

};

	






	






