let LCodes = [								
								
	[`		`,`		`,`		`],
	[`	0	`,`	Staphylococcal scalded skin syndrome Incl.: Pemphigus neonatorum Ritter disease Excl.: toxic epidermal necrolysis [Lyell] (L51.2) 	`,`	null	`],
	[`	L01	`,`	Impetigo Excl.: impetigo herpetiformis (L40.1) pemphigus neonatorum (L00) 	`,`	null	`],
	[`	L01.0	`,`	Impetigo [any organism] [any site] Bockhart impetigo 	`,`	null	`],
	[`	L01.1	`,`	Impetiginization of other dermatoses 	`,`	null	`],
	[`	L02	`,`	Cutaneous abscess, furuncle and carbuncle Incl.: boil furunculosis Excl.: anal and rectal regions (K61.-) genital organs (external): female (N76.4) male (N48.2, N49.-) 	`,`	null	`],
	[`	L02.0	`,`	Cutaneous abscess, furuncle and carbuncle of face Excl.: ear, external (H60.0) eyelid (H00.0) head [any part, except face] (L02.8) lacrimal: gland (H04.0) passages (H04.3) mouth (K12.2) nose (J34.0) orbit (H05.0) submandibular (K12.2) 	`,`	null	`],
	[`	L02.1	`,`	Cutaneous abscess, furuncle and carbuncle of neck 	`,`	null	`],
	[`	L02.2	`,`	Cutaneous abscess, furuncle and carbuncle of trunk Abdominal wall Back [any part, except buttock] Chest wall Groin Perineum Umbilicus Excl.: breast (N61) hip (L02.4) omphalitis of newborn (P38) 	`,`	null	`],
	[`	L02.3	`,`	Cutaneous abscess, furuncle and carbuncle of buttock Gluteal region Excl.: pilonidal cyst with abscess (L05.0) 	`,`	null	`],
	[`	L02.4	`,`	Cutaneous abscess, furuncle and carbuncle of limb Axilla Hip Shoulder 	`,`	null	`],
	[`	L02.8	`,`	Cutaneous abscess, furuncle and carbuncle of other sites Head [any part, except face] Scalp 	`,`	null	`],
	[`	L02.9	`,`	Cutaneous abscess, furuncle and carbuncle, unspecified Furunculosis NOS 	`,`	null	`],
	[`	L03	`,`	Cellulitis Incl.: acute lymphangitis Excl.: cellulitis of: anal and rectal regions (K61.-) external auditory canal (H60.1) external genital organs: female (N76.4) male (N48.2, N49.-) eyelid (H00.0) lacrimal apparatus (H04.3) mouth (K12.2) nose (J34.0) eosinophilic cellulitis [Wells] (L98.3) febrile neutrophilic dermatosis [Sweet] (L98.2) lymphangitis (chronic)(subacute) (I89.1) 	`,`	null	`],
	[`	L03.0	`,`	Cellulitis of finger and toe Infection of nail Onychia Paronychia Perionychia 	`,`	null	`],
	[`	L03.1	`,`	Cellulitis of other parts of limb Axilla Hip Shoulder 	`,`	null	`],
	[`	L03.2	`,`	Cellulitis of face 	`,`	null	`],
	[`	L03.3	`,`	Cellulitis of trunk Abdominal wall Back [any part] Chest wall Groin Perineum Umbilicus Excl.: omphalitis of newborn (P38) 	`,`	null	`],
	[`	L03.8	`,`	Cellulitis of other sites Head [any part, except face] Scalp 	`,`	null	`],
	[`	L03.9	`,`	Cellulitis, unspecified 	`,`	null	`],
	[`	L04	`,`	Acute lymphadenitis Incl.: abscess (acute) lymphadenitis, acute any lymph node, except mesenteric Excl.: enlarged lymph nodes (R59.-) human immunodeficiency virus [HIV] disease resulting in generalized lymphadenopathy (B23.1) lymphadenitis: NOS (I88.9) chronic or subacute, except mesenteric (I88.1) mesenteric, nonspecific (I88.0) 	`,`	null	`],
	[`	L04.0	`,`	Acute lymphadenitis of face, head and neck 	`,`	null	`],
	[`	L04.1	`,`	Acute lymphadenitis of trunk 	`,`	null	`],
	[`	L04.2	`,`	Acute lymphadenitis of upper limb Axilla Shoulder 	`,`	null	`],
	[`	L04.3	`,`	Acute lymphadenitis of lower limb Hip 	`,`	null	`],
	[`	L04.8	`,`	Acute lymphadenitis of other sites 	`,`	null	`],
	[`	L04.9	`,`	Acute lymphadenitis, unspecified 	`,`	null	`],
	[`	L05	`,`	Pilonidal cyst Incl.: fistula sinus coccygeal or pilonidal 	`,`	null	`],
	[`	L05.0	`,`	Pilonidal cyst with abscess 	`,`	null	`],
	[`	L05.9	`,`	Pilonidal cyst without abscess Pilonidal cyst NOS 	`,`	null	`],
	[`	L08	`,`	Other local infections of skin and subcutaneous tissue 	`,`	null	`],
	[`	L08.0	`,`	Pyoderma Dermatitis: gangrenosa purulent septic suppurative Excl.: pyoderma gangrenosum (L88) 	`,`	null	`],
	[`	L08.1	`,`	Erythrasma 	`,`	null	`],
	[`	L08.8	`,`	Other specified local infections of skin and subcutaneous tissue 	`,`	null	`],
	[`	L08.9	`,`	Local infection of skin and subcutaneous tissue, unspecified 	`,`	null	`],
	[`	L10	`,`	Pemphigus Excl.: pemphigus neonatorum (L00) 	`,`	null	`],
	[`	L10.0	`,`	Pemphigus vulgaris 	`,`	null	`],
	[`	L10.1	`,`	Pemphigus vegetans 	`,`	null	`],
	[`	L10.2	`,`	Pemphigus foliaceus 	`,`	null	`],
	[`	L10.3	`,`	Brazilian pemphigus [fogo selvagem] 	`,`	null	`],
	[`	L10.4	`,`	Pemphigus erythematosus Senear-Usher syndrome 	`,`	null	`],
	[`	L10.5	`,`	Drug-induced pemphigus Use additional external cause code (Chapter XX), if desired, to identify drug. 	`,`	null	`],
	[`	L10.8	`,`	Other pemphigus 	`,`	null	`],
	[`	L10.9	`,`	Pemphigus, unspecified 	`,`	null	`],
	[`	L11	`,`	Other acantholytic disorders 	`,`	null	`],
	[`	L11.0	`,`	Acquired keratosis follicularis Excl.: keratosis follicularis (congenital) [Darier-White] (Q82.8) 	`,`	null	`],
	[`	L11.1	`,`	Transient acantholytic dermatosis [Grover] 	`,`	null	`],
	[`	L11.8	`,`	Other specified acantholytic disorders 	`,`	null	`],
	[`	L11.9	`,`	Acantholytic disorder, unspecified 	`,`	null	`],
	[`	L12	`,`	Pemphigoid Excl.: herpes gestationis (O26.4) impetigo herpetiformis (L40.1) 	`,`	null	`],
	[`	L12.0	`,`	Bullous pemphigoid 	`,`	null	`],
	[`	L12.1	`,`	Cicatricial pemphigoid Benign mucous membrane pemphigoid 	`,`	null	`],
	[`	L12.2	`,`	Chronic bullous disease of childhood Juvenile dermatitis herpetiformis 	`,`	null	`],
	[`	L12.3	`,`	Acquired epidermolysis bullosa Excl.: epidermolysis bullosa (congenital) (Q81.-) 	`,`	null	`],
	[`	L12.8	`,`	Other pemphigoid 	`,`	null	`],
	[`	L12.9	`,`	Pemphigoid, unspecified 	`,`	null	`],
	[`	L13	`,`	Other bullous disorders 	`,`	null	`],
	[`	L13.0	`,`	Dermatitis herpetiformis Duhring disease 	`,`	null	`],
	[`	L13.1	`,`	Subcorneal pustular dermatitis Sneddon-Wilkinson disease 	`,`	null	`],
	[`	L13.8	`,`	Other specified bullous disorders 	`,`	null	`],
	[`	L13.9	`,`	Bullous disorder, unspecified 	`,`	null	`],
	[`	L14*	`,`	Bullous disorders in diseases classified elsewhere 	`,`	null	`],
	[`	L40	`,`	Psoriasis 	`,`	null	`],
	[`	L40.0	`,`	Psoriasis vulgaris Nummular psoriasis Plaque psoriasis 	`,`	null	`],
	[`	L40.1	`,`	Generalized pustular psoriasis Impetigo herpetiformis Von Zumbusch disease 	`,`	null	`],
	[`	L40.2	`,`	Acrodermatitis continua 	`,`	null	`],
	[`	L40.3	`,`	Pustulosis palmaris et plantaris 	`,`	null	`],
	[`	L40.4	`,`	Guttate psoriasis 	`,`	null	`],
	[`	L40.5	`,`	Arthropathic psoriasis (M07.0-M07.3*, M09.0*) 	`,`	null	`],
	[`	L40.8	`,`	Other psoriasis Flexural psoriasis 	`,`	null	`],
	[`	L40.9	`,`	Psoriasis, unspecified 	`,`	null	`],
	[`	L41	`,`	Parapsoriasis Excl.: poikiloderma vasculare atrophicans (L94.5) 	`,`	null	`],
	[`	L41.0	`,`	Pityriasis lichenoides et varioliformis acuta Mucha-Habermann disease 	`,`	null	`],
	[`	L41.1	`,`	Pityriasis lichenoides chronica 	`,`	null	`],
	[`	L41.3	`,`	Small plaque parapsoriasis 	`,`	null	`],
	[`	L41.4	`,`	Large plaque parapsoriasis 	`,`	null	`],
	[`	L41.5	`,`	Retiform parapsoriasis 	`,`	null	`],
	[`	L41.8	`,`	Other parapsoriasis 	`,`	null	`],
	[`	L41.9	`,`	Parapsoriasis, unspecified 	`,`	null	`],
	[`	L42	`,`	Pityriasis rosea 	`,`	null	`],
	[`	L43	`,`	Lichen planus Excl.: lichen planopilaris (L66.1) 	`,`	null	`],
	[`	L43.0	`,`	Hypertrophic lichen planus 	`,`	null	`],
	[`	L43.1	`,`	Bullous lichen planus 	`,`	null	`],
	[`	L43.2	`,`	Lichenoid drug reaction Use additional external cause code (Chapter XX), if desired, to identify drug. 	`,`	null	`],
	[`	L43.3	`,`	Subacute (active) lichen planus Lichen planus tropicus 	`,`	null	`],
	[`	L43.8	`,`	Other lichen planus 	`,`	null	`],
	[`	L43.9	`,`	Lichen planus, unspecified 	`,`	null	`],
	[`	L44	`,`	Other papulosquamous disorders 	`,`	null	`],
	[`	L44.0	`,`	Pityriasis rubra pilaris 	`,`	null	`],
	[`	L44.1	`,`	Lichen nitidus 	`,`	null	`],
	[`	L44.2	`,`	Lichen striatus 	`,`	null	`],
	[`	L44.3	`,`	Lichen ruber moniliformis 	`,`	null	`],
	[`	L44.4	`,`	Infantile papular acrodermatitis [Giannotti-Crosti] 	`,`	null	`],
	[`	L44.8	`,`	Other specified papulosquamous disorders 	`,`	null	`],
	[`	L44.9	`,`	Papulosquamous disorder, unspecified 	`,`	null	`],
	[`	L45*	`,`	Papulosquamous disorders in diseases classified elsewhere 	`,`	null	`],
	[`	L50	`,`	Urticaria Excl.: allergic contact dermatitis (L23.-) angioneurotic oedema (T78.3) hereditary angio-oedema (D84.1) Quincke oedema (T78.3) urticaria: giant (T78.3) neonatorum (P83.8) papulosa (L28.2) pigmentosa (Q82.2) serum (T80.6) solar (L56.3) 	`,`	null	`],
	[`	L50.0	`,`	Allergic urticaria 	`,`	null	`],
	[`	L50.1	`,`	Idiopathic urticaria 	`,`	null	`],
	[`	L50.2	`,`	Urticaria due to cold and heat 	`,`	null	`],
	[`	L50.3	`,`	Dermatographic urticaria 	`,`	null	`],
	[`	L50.4	`,`	Vibratory urticaria 	`,`	null	`],
	[`	L50.5	`,`	Cholinergic urticaria 	`,`	null	`],
	[`	L50.6	`,`	Contact urticaria 	`,`	null	`],
	[`	L50.8	`,`	Other urticaria Urticaria: chronic recurrent periodic 	`,`	null	`],
	[`	L50.9	`,`	Urticaria, unspecified 	`,`	null	`],
	[`	L51	`,`	Erythema multiforme 	`,`	null	`],
	[`	L51.0	`,`	Nonbullous erythema multiforme 	`,`	null	`],
	[`	L51.1	`,`	Bullous erythema multiforme Stevens-Johnson syndrome 	`,`	null	`],
	[`	L51.2	`,`	Toxic epidermal necrolysis [Lyell] L51.8 Other erythema multiforme 	`,`	null	`],
	[`	L51.9	`,`	Erythema multiforme, unspecified 	`,`	null	`],
	[`	L52	`,`	Erythema nodosum 	`,`	null	`],
	[`	L53	`,`	Other erythematous conditions Excl.: erythema: ab igne (L59.0) due to external agents in contact with skin (L23-L25) intertrigo (L30.4) 	`,`	null	`],
	[`	L53.0	`,`	Toxic erythema Use additional external cause code (Chapter XX), if desired, to identify external agent. Excl.: neonatal erythema toxicum (P83.1) 	`,`	null	`],
	[`	L53.1	`,`	Erythema annulare centrifugum 	`,`	null	`],
	[`	L53.2	`,`	Erythema marginatum 	`,`	null	`],
	[`	L53.3	`,`	Other chronic figurate erythema 	`,`	null	`],
	[`	L53.8	`,`	Other specified erythematous conditions 	`,`	null	`],
	[`	L53.9	`,`	Erythematous condition, unspecified Erythema NOS Erythroderma NOS 	`,`	null	`],
	[`	L54*	`,`	Erythema in diseases classified elsewhere 	`,`	null	`],
	[`	L54.0*	`,`	Erythema marginatum in acute rheumatic fever (I00) 	`,`	null	`],
	[`	L54.8*	`,`	Erythema in other diseases classified elsewhere 	`,`	null	`],
	[`	L55	`,`	Sunburn 	`,`	null	`],
	[`	L55.0	`,`	Sunburn of first degree 	`,`	null	`],
	[`	L55.1	`,`	Sunburn of second degree 	`,`	null	`],
	[`	L55.2	`,`	Sunburn of third degree 	`,`	null	`],
	[`	L55.8	`,`	Other sunburn 	`,`	null	`],
	[`	L55.9	`,`	Sunburn, unspecified 	`,`	null	`],
	[`	L56	`,`	Other acute skin changes due to ultraviolet radiation 	`,`	null	`],
	[`	L56.0	`,`	Drug phototoxic response Use additional external cause code (Chapter XX), if desired, to identify drug. 	`,`	null	`],
	[`	L56.1	`,`	Drug photoallergic response Use additional external cause code (Chapter XX), if desired, to identify drug. 	`,`	null	`],
	[`	L56.2	`,`	Photocontact dermatitis [berloque dermatitis] 	`,`	null	`],
	[`	L56.3	`,`	Solar urticaria 	`,`	null	`],
	[`	L56.4	`,`	Polymorphous light eruption 	`,`	null	`],
	[`	L56.8	`,`	Other specified acute skin changes due to ultraviolet radiation 	`,`	null	`],
	[`	L56.9	`,`	Acute skin change due to ultraviolet radiation, unspecified 	`,`	null	`],
	[`	L57	`,`	Skin changes due to chronic exposure to nonionizing radiation 	`,`	null	`],
	[`	L57.0	`,`	Actinic keratosis Keratosis: NOS senile solar 	`,`	null	`],
	[`	L57.1	`,`	Actinic reticuloid 	`,`	null	`],
	[`	L57.2	`,`	Cutis rhomboidalis nuchae 	`,`	null	`],
	[`	L57.3	`,`	Poikiloderma of Civatte 	`,`	null	`],
	[`	L57.4	`,`	Cutis laxa senilis Elastosis senilis 	`,`	null	`],
	[`	L57.5	`,`	Actinic granuloma 	`,`	null	`],
	[`	L57.8	`,`	Other skin changes due to chronic exposure to nonionizing radiation Farmer skin Sailor skin Solar dermatitis 	`,`	null	`],
	[`	L57.9	`,`	Skin changes due to chronic exposure to nonionizing radiation, unspecified 	`,`	null	`],
	[`	L58	`,`	Radiodermatitis 	`,`	null	`],
	[`	L58.0	`,`	Acute radiodermatitis 	`,`	null	`],
	[`	L58.1	`,`	Chronic radiodermatitis 	`,`	null	`],
	[`	L58.9	`,`	Radiodermatitis, unspecified 	`,`	null	`],
	[`	L59	`,`	Other disorders of skin and subcutaneous tissue related to radiation 	`,`	null	`],
	[`	L59.0	`,`	Erythema ab igne [dermatitis ab igne] 	`,`	null	`],
	[`	L59.8	`,`	Other specified disorders of skin and subcutaneous tissue related to radiation 	`,`	null	`],
	[`	L59.9	`,`	Disorder of skin and subcutaneous tissue related to radiation, unspecified 	`,`	null	`],
	[`	L60	`,`	Nail disorders Excl.: clubbing of nails (R68.3) onychia and paronychia (L03.0) 	`,`	null	`],
	[`	L60.0	`,`	Ingrowing nail 	`,`	null	`],
	[`	L60.1	`,`	Onycholysis 	`,`	null	`],
	[`	L60.2	`,`	Onychogryphosis 	`,`	null	`],
	[`	L60.3	`,`	Nail dystrophy 	`,`	null	`],
	[`	L60.4	`,`	Beau lines 	`,`	null	`],
	[`	L60.5	`,`	Yellow nail syndrome 	`,`	null	`],
	[`	L60.8	`,`	Other nail disorders 	`,`	null	`],
	[`	L60.9	`,`	Nail disorder, unspecified 	`,`	null	`],
	[`	L62*	`,`	Nail disorders in diseases classified elsewhere 	`,`	null	`],
	[`	L62.0*	`,`	Clubbed nail pachydermoperiostosis (M89.4) 	`,`	null	`],
	[`	L62.8*	`,`	Nail disorders in other diseases classified elsewhere 	`,`	null	`],
	[`	L63	`,`	Alopecia areata 	`,`	null	`],
	[`	L63.0	`,`	Alopecia (capitis) totalis 	`,`	null	`],
	[`	L63.1	`,`	Alopecia universalis 	`,`	null	`],
	[`	L63.2	`,`	Ophiasis 	`,`	null	`],
	[`	L63.8	`,`	Other alopecia areata 	`,`	null	`],
	[`	L63.9	`,`	Alopecia areata, unspecified 	`,`	null	`],
	[`	L64	`,`	Androgenic alopecia Incl.: male-pattern baldness 	`,`	null	`],
	[`	L64.0	`,`	Drug-induced androgenic alopecia Use additional external cause code (Chapter XX), if desired, to identify drug. 	`,`	null	`],
	[`	L64.8	`,`	Other androgenic alopecia 	`,`	null	`],
	[`	L64.9	`,`	Androgenic alopecia, unspecified L65 Other nonscarring hair loss Use additional external cause code (Chapter XX), if desired, to identify drug, if drug-induced. Excl.: trichotillomania (F63.3) 	`,`	null	`],
	[`	L65.0	`,`	Telogen effluvium 	`,`	null	`],
	[`	L65.1	`,`	Anagen effluvium 	`,`	null	`],
	[`	L65.2	`,`	Alopecia mucinosa 	`,`	null	`],
	[`	L65.8	`,`	Other specified nonscarring hair loss 	`,`	null	`],
	[`	L65.9	`,`	Nonscarring hair loss, unspecified Alopecia NOS 	`,`	null	`],
	[`	L66	`,`	Cicatricial alopecia [scarring hair loss] 	`,`	null	`],
	[`	L66.0	`,`	Pseudopelade 	`,`	null	`],
	[`	L66.1	`,`	Lichen planopilaris Follicular lichen planus 	`,`	null	`],
	[`	L66.2	`,`	Folliculitis decalvans 	`,`	null	`],
	[`	L66.3	`,`	Perifolliculitis capitis abscedens 	`,`	null	`],
	[`	L66.4	`,`	Folliculitis ulerythematosa reticulata 	`,`	null	`],
	[`	L66.8	`,`	Other cicatricial alopecia 	`,`	null	`],
	[`	L66.9	`,`	Cicatricial alopecia, unspecified 	`,`	null	`],
	[`	L67	`,`	Hair colour and hair shaft abnormalities Excl.: monilethrix (Q84.1) pili annulati (Q84.1) telogen effluvium (L65.0) 	`,`	null	`],
	[`	L67.0	`,`	Trichorrhexis nodosa 	`,`	null	`],
	[`	L67.1	`,`	Variations in hair colour Canities Greyness, hair (premature) Heterochromia of hair Poliosis: NOS circumscripta, acquired 	`,`	null	`],
	[`	L67.8	`,`	Other hair colour and hair shaft abnormalities Fragilitas crinium 	`,`	null	`],
	[`	L67.9	`,`	Hair colour and hair shaft abnormality, unspecified 	`,`	null	`],
	[`	L68	`,`	Hypertrichosis Incl.: excess hair Excl.: congenital hypertrichosis (Q84.2) persistent lanugo (Q84.2) 	`,`	null	`],
	[`	L68.0	`,`	Hirsutism Use additional external cause code (Chapter XX), if desired, to identify drug, if drug-induced. 	`,`	null	`],
	[`	L68.1	`,`	Acquired hypertrichosis lanuginosa Use additional external cause code (Chapter XX), if desired, to identify drug, if drug-induced. 	`,`	null	`],
	[`	L68.2	`,`	Localized hypertrichosis 	`,`	null	`],
	[`	L68.3	`,`	Polytrichia 	`,`	null	`],
	[`	L68.8	`,`	Other hypertrichosis 	`,`	null	`],
	[`	L68.9	`,`	Hypertrichosis, unspecified 	`,`	null	`],
	[`	L70	`,`	Acne Excl.: acne keloid (L73.0) 	`,`	null	`],
	[`	L70.0	`,`	Acne vulgaris 	`,`	null	`],
	[`	L70.1	`,`	Acne conglobata 	`,`	null	`],
	[`	L70.2	`,`	Acne varioliformis Acne necrotica miliaris 	`,`	null	`],
	[`	L70.3	`,`	Acne tropica 	`,`	null	`],
	[`	L70.4	`,`	Infantile acne 	`,`	null	`],
	[`	L70.5	`,`	Acne excoriee des jeunes filles 	`,`	null	`],
	[`	L70.8	`,`	Other acne 	`,`	null	`],
	[`	L70.9	`,`	Acne, unspecified 	`,`	null	`],
	[`	L71	`,`	Rosacea 	`,`	null	`],
	[`	L71.0	`,`	Perioral dermatitis Use additional external cause code (Chapter XX), if desired, to identify drug, if drug-induced. 	`,`	null	`],
	[`	L71.1	`,`	Rhinophyma 	`,`	null	`],
	[`	L71.8	`,`	Other rosacea 	`,`	null	`],
	[`	L71.9	`,`	Rosacea, unspecified 	`,`	null	`],
	[`	L72	`,`	Follicular cysts of skin and subcutaneous tissue 	`,`	null	`],
	[`	L72.0	`,`	Epidermal cyst 	`,`	null	`],
	[`	L72.1	`,`	Trichilemmal cyst Pilar cyst Sebaceous cyst 	`,`	null	`],
	[`	L72.2	`,`	Steatocystoma multiplex 	`,`	null	`],
	[`	L72.8	`,`	Other follicular cysts of skin and subcutaneous tissue 	`,`	null	`],
	[`	L72.9	`,`	Follicular cyst of skin and subcutaneous tissue, unspecified 	`,`	null	`],
	[`	L73	`,`	Other follicular disorders 	`,`	null	`],
	[`	L73.0	`,`	Acne keloid 	`,`	null	`],
	[`	L73.1	`,`	Pseudofolliculitis barbae 	`,`	null	`],
	[`	L73.2	`,`	Hidradenitis suppurativa 	`,`	null	`],
	[`	L73.8	`,`	Other specified follicular disorders Sycosis barbae 	`,`	null	`],
	[`	L73.9	`,`	Follicular disorder, unspecified 	`,`	null	`],
	[`	L74	`,`	Eccrine sweat disorders Excl.: hyperhidrosis (R61.-) 	`,`	null	`],
	[`	L74.0	`,`	Miliaria rubra 	`,`	null	`],
	[`	L74.1	`,`	Miliaria crystallina 	`,`	null	`],
	[`	L74.2	`,`	Miliaria profunda Miliaria tropicalis 	`,`	null	`],
	[`	L74.3	`,`	Miliaria, unspecified 	`,`	null	`],
	[`	L74.4	`,`	Anhidrosis Hypohidrosis 	`,`	null	`],
	[`	L74.8	`,`	Other eccrine sweat disorders 	`,`	null	`],
	[`	L74.9	`,`	Eccrine sweat disorder, unspecified Sweat gland disorder NOS 	`,`	null	`],
	[`	L75	`,`	Apocrine sweat disorders Excl.: dyshidrosis [pompholyx] (L30.1) hidradenitis suppurativa (L73.2) 	`,`	null	`],
	[`	L75.0	`,`	Bromhidrosis 	`,`	null	`],
	[`	L75.1	`,`	Chromhidrosis 	`,`	null	`],
	[`	L75.2	`,`	Apocrine miliaria Fox-Fordyce disease 	`,`	null	`],
	[`	L75.8	`,`	Other apocrine sweat disorders 	`,`	null	`],
	[`	L75.9	`,`	Apocrine sweat disorder, unspecified 	`,`	null	`],
	[`	L80	`,`	Vitiligo 	`,`	null	`],
	[`	L81	`,`	Other disorders of pigmentation Excl.: birthmark NOS (Q82.5) naevus - see Alphabetical Index Peutz-Jeghers syndrome (Q85.8) 	`,`	null	`],
	[`	L81.0	`,`	Postinflammatory hyperpigmentation 	`,`	null	`],
	[`	L81.1	`,`	Chloasma 	`,`	null	`],
	[`	L81.2	`,`	Freckles 	`,`	null	`],
	[`	L81.3	`,`	Cafe au lait spots 	`,`	null	`],
	[`	L81.4	`,`	Other melanin hyperpigmentation Lentigo 	`,`	null	`],
	[`	L81.5	`,`	Leukoderma, not elsewhere classified 	`,`	null	`],
	[`	L81.6	`,`	Other disorders of diminished melanin formation 	`,`	null	`],
	[`	L81.7	`,`	Pigmented purpuric dermatosis Angioma serpiginosum 	`,`	null	`],
	[`	L81.8	`,`	Other specified disorders of pigmentation Iron pigmentation Tattoo pigmentation 	`,`	null	`],
	[`	L81.9	`,`	Disorder of pigmentation, unspecified 	`,`	null	`],
	[`	L82	`,`	Seborrhoeic keratosis Incl.: Dermatosis papulosa nigra Leser-Trelat disease 	`,`	null	`],
	[`	L83	`,`	Acanthosis nigricans Incl.: Confluent and reticulated papillomatosis 	`,`	null	`],
	[`	L84	`,`	Corns and callosities Incl.: Callus Clavus 	`,`	null	`],
	[`	L85	`,`	Other epidermal thickening Excl.: hypertrophic disorders of skin (L91.-) 	`,`	null	`],
	[`	L85.0	`,`	Acquired ichthyosis Excl.: congenital ichthyosis (Q80.-) 	`,`	null	`],
	[`	L85.1	`,`	Acquired keratosis [keratoderma] palmaris et plantaris Excl.: inherited keratosis palmaris et plantaris (Q82.8) 	`,`	null	`],
	[`	L85.2	`,`	Keratosis punctata (palmaris et plantaris) 	`,`	null	`],
	[`	L85.3	`,`	Xerosis cutis Dry skin dermatitis 	`,`	null	`],
	[`	L85.8	`,`	Other specified epidermal thickening Cutaneous horn 	`,`	null	`],
	[`	L85.9	`,`	Epidermal thickening, unspecified 	`,`	null	`],
	[`	L86*	`,`	Keratoderma in diseases classified elsewhere Incl.: Follicular keratosis Xeroderma due to a vitamin A deficiency (E50.8) 	`,`	null	`],
	[`	L87	`,`	Transepidermal elimination disorders Excl.: granuloma annulare (perforating) (L92.0) 	`,`	null	`],
	[`	L87.0	`,`	Keratosis follicularis et parafollicularis in cutem penetrans [Kyrle] Hyperkeratosis follicularis penetrans 	`,`	null	`],
	[`	L87.1	`,`	Reactive perforating collagenosis 	`,`	null	`],
	[`	L87.2	`,`	Elastosis perforans serpiginosa 	`,`	null	`],
	[`	L87.8	`,`	Other transepidermal elimination disorders 	`,`	null	`],
	[`	L87.9	`,`	Transepidermal elimination disorder, unspecified 	`,`	null	`],
	[`	L88	`,`	Pyoderma gangrenosum Incl.: Phagedenic pyoderma Excl.: dermatitis gangrenosa (L08.0) 	`,`	null	`],
	[`	L89	`,`	Decubitus ulcer and pressure area Note: For multiple sites of differing stages assign only one code indicating the highest stage Incl.: Bedsore Plaster ulcer Excl.: decubitus (trophic) ulcer of cervix (uteri) (N86) 	`,`	null	`],
	[`	L89.0	`,`	Stage I decubitus ulcer and pressure area The ulcer appears as a defined area of persistent redness (erythema) in lightly pigmented skin, whereas in darker skin tones, the ulcer may appear with persistent red, blue or purple hues, without skin loss Decubitus [pressure] ulcer limited to erythema only 	`,`	null	`],
	[`	L89.1	`,`	Stage II decubitus ulcer Decubitus [pressure] ulcer with: abrasion blister partial thickness skin loss involving epidermis and/or dermis skin loss NOS 	`,`	null	`],
	[`	L89.2	`,`	Stage III decubitus ulcer Decubitus [pressure] ulcer with full thickness skin loss involving damage or necrosis of subcutaneous tissue extending to underlying fascia 	`,`	null	`],
	[`	L89.3	`,`	Stage IV decubitus ulcer Decubitus [pressure] ulcer with necrosis of muscle, bone or supporting structures (ie tendon or joint capsule) 	`,`	null	`],
	[`	L89.9	`,`	Decubitus ulcer and pressure area, unspecified Decubitus [pressure] ulcer without mention of stage 	`,`	null	`],
	[`	L90	`,`	Atrophic disorders of skin 	`,`	null	`],
	[`	L90.0	`,`	Lichen sclerosus et atrophicus Excl.: lichen sclerosus of external genital organs: female (N90.4) male (N48.0) 	`,`	null	`],
	[`	L90.1	`,`	Anetoderma of Schweninger-Buzzi 	`,`	null	`],
	[`	L90.2	`,`	Anetoderma of Jadassohn-Pellizzari 	`,`	null	`],
	[`	L90.3	`,`	Atrophoderma of Pasini and Pierini 	`,`	null	`],
	[`	L90.4	`,`	Acrodermatitis chronica atrophicans 	`,`	null	`],
	[`	L90.5	`,`	Scar conditions and fibrosis of skin Adherent scar (skin) Cicatrix Disfigurement due to scar Scar NOS Excl.: hypertrophic scar (L91.0) keloid scar (L91.0) 	`,`	null	`],
	[`	L90.6	`,`	Striae atrophicae 	`,`	null	`],
	[`	L90.8	`,`	Other atrophic disorders of skin 	`,`	null	`],
	[`	L90.9	`,`	Atrophic disorder of skin, unspecified 	`,`	null	`],
	[`	L91	`,`	Hypertrophic disorders of skin 	`,`	null	`],
	[`	L91.0	`,`	Hypertrophic scar Keloid scar Keloid Excl.: acne keloid (L73.0) scar NOS (L90.5) 	`,`	null	`],
	[`	L91.8	`,`	Other hypertrophic disorders of skin 	`,`	null	`],
	[`	L91.9	`,`	Hypertrophic disorder of skin, unspecified 	`,`	null	`],
	[`	L92	`,`	Granulomatous disorders of skin and subcutaneous tissue Excl.: actinic granuloma (L57.5) 	`,`	null	`],
	[`	L92.0	`,`	Granuloma annulare Perforating granuloma annulare 	`,`	null	`],
	[`	L92.1	`,`	Necrobiosis lipoidica, not elsewhere classified Excl.: that associated with diabetes mellitus (E10-E14) 	`,`	null	`],
	[`	L92.2	`,`	Granuloma faciale [eosinophilic granuloma of skin] 	`,`	null	`],
	[`	L92.3	`,`	Foreign body granuloma of skin and subcutaneous tissue 	`,`	null	`],
	[`	L92.8	`,`	Other granulomatous disorders of skin and subcutaneous tissue 	`,`	null	`],
	[`	L92.9	`,`	Granulomatous disorder of skin and subcutaneous tissue, unspecified 	`,`	null	`],
	[`	L93	`,`	Lupus erythematosus Use additional external cause code (Chapter XX), if desired, to identify drug, if drug-induced. Excl.: lupus: exedens (A18.4) vulgaris (A18.4) scleroderma (M34.-) systemic lupus erythematosus (M32.-) 	`,`	null	`],
	[`	L93.0	`,`	Discoid lupus erythematosus Lupus erythematosus NOS 	`,`	null	`],
	[`	L93.1	`,`	Subacute cutaneous lupus erythematosus 	`,`	null	`],
	[`	L93.2	`,`	Other local lupus erythematosus Lupus: erythematosus profundus panniculitis 	`,`	null	`],
	[`	L94	`,`	Other localized connective tissue disorders Excl.: systemic connective tissue disorders (M30-M36) 	`,`	null	`],
	[`	L94.0	`,`	Localized scleroderma [morphea] Circumscribed scleroderma 	`,`	null	`],
	[`	L94.1	`,`	Linear scleroderma En coup de sabre lesion 	`,`	null	`],
	[`	L94.2	`,`	Calcinosis cutis 	`,`	null	`],
	[`	L94.3	`,`	Sclerodactyly 	`,`	null	`],
	[`	L94.4	`,`	Gottron papules 	`,`	null	`],
	[`	L94.5	`,`	Poikiloderma vasculare atrophicans 	`,`	null	`],
	[`	L94.6	`,`	Ainhum 	`,`	null	`],
	[`	L94.8	`,`	Other specified localized connective tissue disorders 	`,`	null	`],
	[`	L94.9	`,`	Localized connective tissue disorder, unspecified 	`,`	null	`],
	[`	L95	`,`	Vasculitis limited to skin, not elsewhere classified Excl.: angioma serpiginosum (L81.7) Henoch(-Schonlein) purpura (D69.0) hypersensitivity angiitis (M31.0) panniculitis (of): NOS (M79.3) lupus (L93.2) neck and back (M54.0) relapsing [Weber-Christian] (M35.6) polyarteritis nodosa (M30.0) rheumatoid vasculitis (M05.2) serum sickness (T80.6) urticaria (L50.-) Wegener granulomatosis (M31.3) 	`,`	null	`],
	[`	L95.0	`,`	Livedoid vasculitis Atrophie blanche (en plaque) 	`,`	null	`],
	[`	L95.1	`,`	Erythema elevatum diutinum 	`,`	null	`],
	[`	L95.8	`,`	Other vasculitis limited to skin 	`,`	null	`],
	[`	L95.9	`,`	Vasculitis limited to skin, unspecified 	`,`	null	`],
	[`	L97	`,`	Ulcer of lower limb, not elsewhere classified Excl.: decubitus [pressure] ulcer and pressure area (L89.-) gangrene (R02) skin infections (L00-L08) specific infections classified to A00-B99 varicose ulcer (I83.0, I83.2) 	`,`	null	`],
	[`	L98	`,`	Other disorders of skin and subcutaneous tissue, not elsewhere classified 	`,`	null	`],
	[`	L98.0	`,`	Pyogenic granuloma 	`,`	null	`],
	[`	L98.1	`,`	Factitial dermatitis Neurotic excoriation 	`,`	null	`],
	[`	L98.2	`,`	Febrile neutrophilic dermatosis [Sweet] 	`,`	null	`],
	[`	L98.3	`,`	Eosinophilic cellulitis [Wells] 	`,`	null	`],
	[`	L98.4	`,`	Chronic ulcer of skin, not elsewhere classified Chronic ulcer of skin NOS Tropical ulcer NOS Ulcer of skin NOS Excl.: decubitus [pressure] ulcer and pressure area (L89.-) gangrene (R02) skin infections (L00-L08) specific infections classified to A00-B99 ulcer of lower limb NEC (L97) varicose ulcer (I83.0, I83.2) 	`,`	null	`],
	[`	L98.5	`,`	Mucinosis of skin Focal mucinosis Lichen myxoedematosus Reticular erythematous mucinosis Excl.: focal oral mucinosis (K13.7) myxoedema (E03.9) 	`,`	null	`],
	[`	L98.6	`,`	Other infiltrative disorders of skin and subcutaneous tissue Excl.: hyalinosis cutis et mucosae (E78.8) 	`,`	null	`],
	[`	L98.8	`,`	Other specified disorders of skin and subcutaneous tissue 	`,`	null	`],
	[`	L98.9	`,`	Disorder of skin and subcutaneous tissue, unspecified 	`,`	null	`],
	[`	L99*	`,`	Other disorders of skin and subcutaneous tissue in diseases classified elsewhere 	`,`	null	`],
	[`	L99.0*	`,`	Amyloidosis of skin (E85.-) Lichen amyloidosis Macular amyloid 	`,`	null	`],
	[`	L99.8*	`,`	Other specified disorders of skin and subcutaneous tissue in diseases classified elsewhere Syphilitic: alopecia (A51.3) leukoderma (A51.3, A52.7) 	`,`	null	`],
							
];								
							
				
							
							
				
	
let CodeRangeL ={
	f0:function(val1=(-1),val2=(0)){
		let Range1 = LCodes.slice(val1,val2);
		Range1.reverse();
		document.documentElement.innerHTML += `<br>ShowingL Codes ${Range1.length} items(s)`;

		for(value1 in Range1){
			    document.documentElement.style.cssText += "background-color:tan;";
				document.getElementById('lcodesTR').outerHTML += `<tr><td style="background-color:navy;color:white;width:5%;padding:40px;border:2px solid white;font-weight:900;font-size:40px;text-align:center;">${Range1[value1][0]}</td><td style="background-color:black;color:white;width:90%;padding:20px;border:2px solid white;font-size:30px;">${Range1[value1][1]}</td><td style="background-color:navy;color:white;width:5%;padding:20px;border:2px solid white;font-weight:900;font-size:40px;text-align:center;">${Range1[value1][2]}</td></tr>`;			
		}

	},

};

	






	






