								
								
let MCodes = [								
	[`		`,`		`,`		`],
	[`	M00	`,`	Pyogenic arthritis [See site code at the beginning of this chapter] Excl.: infection and inflammatory reaction due to internal joint prosthesis (T84.5) 	`,`	null	`],
	[`	M00.0	`,`	Staphylococcal arthritis and polyarthritis 	`,`	null	`],
	[`	M00.1	`,`	Pneumococcal arthritis and polyarthritis 	`,`	null	`],
	[`	M00.2	`,`	Other streptococcal arthritis and polyarthritis 	`,`	null	`],
	[`	M00.8	`,`	Arthritis and polyarthritis due to other specified bacterial agents Use additional code (B95-B96), if desired, to identify bacterial agent. 	`,`	null	`],
	[`	M00.9	`,`	Pyogenic arthritis, unspecified Infective arthritis NOS 	`,`	null	`],
	[`	M01*	`,`	Direct infections of joint in infectious and parasitic diseases classified elsewhere [See site code at the beginning of this chapter] Excl.: arthropathy in sarcoidosis (M14.8*) postinfective and reactive arthropathy (M03.-*) 	`,`	null	`],
	[`	M01.0*	`,`	Meningococcal arthritis (A39.8) Excl.: postmeningococcal arthritis (M03.0*) 	`,`	null	`],
	[`	M01.1*	`,`	Tuberculous arthritis (A18.0) Excl.: of spine (M49.0*) 	`,`	null	`],
	[`	M01.2*	`,`	Arthritis in Lyme disease (A69.2) 	`,`	null	`],
	[`	M01.3*	`,`	Arthritis in other bacterial diseases classified elsewhere Arthritis in: leprosy [Hansen disease] (A30.-) localized salmonella infection (A02.2) typhoid or paratyphoid fever (A01.-) Gonococcal arthritis (A54.4) 	`,`	null	`],
	[`	M01.4*	`,`	Rubella arthritis (B06.8) 	`,`	null	`],
	[`	M01.5*	`,`	Arthritis in other viral diseases classified elsewhere Arthritis in: mumps (B26.8) O'nyong-nyong fever (A92.1) 	`,`	null	`],
	[`	M01.6*	`,`	Arthritis in mycoses (B35-B49) 	`,`	null	`],
	[`	M01.8*	`,`	Arthritis in other infectious and parasitic diseases classified elsewhere 	`,`	null	`],
	[`	M02	`,`	Reactive arthropathies [See site code at the beginning of this chapter] Excl.: Behcet disease (M35.2) rheumatic fever (I00) 	`,`	null	`],
	[`	M02.0	`,`	Arthropathy following intestinal bypass 	`,`	null	`],
	[`	M02.1	`,`	Postdysenteric arthropathy 	`,`	null	`],
	[`	M02.2	`,`	Postimmunization arthropathy 	`,`	null	`],
	[`	M02.3	`,`	Reiter disease 	`,`	null	`],
	[`	M02.8	`,`	Other reactive arthropathies 	`,`	null	`],
	[`	M02.9	`,`	Reactive arthropathy, unspecified 	`,`	null	`],
	[`	M03*	`,`	Postinfective and reactive arthropathies in diseases classified elsewhere [See site code at the beginning of this chapter] Excl.: direct infections of joint in infectious and parasitic diseases classified elsewhere (M01.-*) 	`,`	null	`],
	[`	M03.0*	`,`	Postmeningococcal arthritis (A39.8) Excl.: meningococcal arthritis (M01.0*) 	`,`	null	`],
	[`	M03.1*	`,`	Postinfective arthropathy in syphilis Clutton joints (A50.5) Excl.: Charcot or tabetic arthropathy (M14.6*) 	`,`	null	`],
	[`	M03.2*	`,`	Other postinfectious arthropathies in diseases classified elsewhere Postinfectious arthropathy in: enteritis due to Yersinia enterocolitica (A04.6) viral hepatitis (B15-B19) Excl.: viral arthropathies (M01.4-M01.5*) 	`,`	null	`],
	[`	M03.6*	`,`	Reactive arthropathy in other diseases classified elsewhere Arthropathy in infective endocarditis (I33.0) 	`,`	null	`],
	[`	M05	`,`	Seropositive rheumatoid arthritis [See site code at the beginning of this chapter] Excl.: rheumatic fever (I00) rheumatoid arthritis (of): juvenile (M08.-) spine (M45) 	`,`	null	`],
	[`	M05.0	`,`	Felty syndrome Rheumatoid arthritis with splenoadenomegaly and leukopenia 	`,`	null	`],
	[`	M05.1	`,`	Rheumatoid lung disease (J99.0*) 	`,`	null	`],
	[`	M05.2	`,`	Rheumatoid vasculitis 	`,`	null	`],
	[`	M05.3	`,`	Rheumatoid arthritis with involvement of other organs and systems Rheumatoid: carditis (I52.8*) endocarditis (I39.-*) myocarditis (I41.8*) myopathy (G73.7*) pericarditis (I32.8*) polyneuropathy (G63.6*) 	`,`	null	`],
	[`	M05.8	`,`	Other seropositive rheumatoid arthritis 	`,`	null	`],
	[`	M05.9	`,`	Seropositive rheumatoid arthritis, unspecified 	`,`	null	`],
	[`	M06	`,`	Other rheumatoid arthritis [See site code at the beginning of this chapter] 	`,`	null	`],
	[`	M06.0	`,`	Seronegative rheumatoid arthritis 	`,`	null	`],
	[`	M06.1	`,`	Adult-onset Still disease Excl.: Still disease NOS (M08.2) 	`,`	null	`],
	[`	M06.2	`,`	Rheumatoid bursitis 	`,`	null	`],
	[`	M06.3	`,`	Rheumatoid nodule 	`,`	null	`],
	[`	M06.4	`,`	Inflammatory polyarthropathy Excl.: polyarthritis NOS (M13.0) 	`,`	null	`],
	[`	M06.8	`,`	Other specified rheumatoid arthritis 	`,`	null	`],
	[`	M06.9	`,`	Rheumatoid arthritis, unspecified 	`,`	null	`],
	[`	M07*	`,`	Psoriatic and enteropathic arthropathies [See site code at the beginning of this chapter] Excl.: juvenile psoriatic and enteropathic arthropathies (M09.-*) 	`,`	null	`],
	[`	M07.0*	`,`	Distal interphalangeal psoriatic arthropathy (L40.5) 	`,`	null	`],
	[`	M07.1*	`,`	Arthritis mutilans (L40.5) 	`,`	null	`],
	[`	M07.2*	`,`	Psoriatic spondylitis (L40.5) 	`,`	null	`],
	[`	M07.3*	`,`	Other psoriatic arthropathies (L40.5) 	`,`	null	`],
	[`	M07.4*	`,`	Arthropathy in Crohn disease [regional enteritis] (K50.-) 	`,`	null	`],
	[`	M07.5*	`,`	Arthropathy in ulcerative colitis (K51.-) 	`,`	null	`],
	[`	M07.6*	`,`	Other enteropathic arthropathies 	`,`	null	`],
	[`	M08	`,`	Juvenile arthritis [See site code at the beginning of this chapter] Incl.: arthritis in children, with onset before 16th birthday and lasting longer than 3 months Excl.: Felty syndrome (M05.0) juvenile dermatomyositis (M33.0) 	`,`	null	`],
	[`	M08.0	`,`	Juvenile rheumatoid arthritis Juvenile rheumatoid arthritis with or without rheumatoid factor 	`,`	null	`],
	[`	M08.1	`,`	Juvenile ankylosing spondylitis Excl.: ankylosing spondylitis in adults (M45) 	`,`	null	`],
	[`	M08.2	`,`	Juvenile arthritis with systemic onset Still disease NOS Excl.: adult-onset Still disease (M06.1) 	`,`	null	`],
	[`	M08.3	`,`	Juvenile polyarthritis (seronegative) Chronic juvenile polyarthritis 	`,`	null	`],
	[`	M08.4	`,`	Pauciarticular juvenile arthritis 	`,`	null	`],
	[`	M08.8	`,`	Other juvenile arthritis 	`,`	null	`],
	[`	M08.9	`,`	Juvenile arthritis, unspecified 	`,`	null	`],
	[`	M09*	`,`	Juvenile arthritis in diseases classified elsewhere [See site code at the beginning of this chapter] Excl.: arthropathy in Whipple disease (M14.8*) 	`,`	null	`],
	[`	M09.0*	`,`	Juvenile arthritis in psoriasis (L40.5) 	`,`	null	`],
	[`	M09.1*	`,`	Juvenile arthritis in Crohn disease [regional enteritis] (K50.-) 	`,`	null	`],
	[`	M09.2*	`,`	Juvenile arthritis in ulcerative colitis (K51.-) 	`,`	null	`],
	[`	M09.8*	`,`	Juvenile arthritis in other diseases classified elsewhere 	`,`	null	`],
	[`	M10	`,`	Gout [See site code at the beginning of this chapter] 	`,`	null	`],
	[`	M10.0	`,`	Idiopathic gout Gouty bursitis Primary gout Urate tophus of heart (I43.8*) 	`,`	null	`],
	[`	M10.1	`,`	Lead-induced gout 	`,`	null	`],
	[`	M10.2	`,`	Drug-induced gout Use additional external cause code (Chapter XX), if desired, to identify drug. 	`,`	null	`],
	[`	M10.3	`,`	Gout due to impairment of renal function Use additional code, if desired, to identify impairment of kidney disease (N17-N19) 	`,`	null	`],
	[`	M10.4	`,`	Other secondary gout 	`,`	null	`],
	[`	M10.9	`,`	Gout, unspecified 	`,`	null	`],
	[`	M11	`,`	Other crystal arthropathies [See site code at the beginning of this chapter] 	`,`	null	`],
	[`	M11.0	`,`	Hydroxyapatite deposition disease 	`,`	null	`],
	[`	M11.1	`,`	Familial chondrocalcinosis 	`,`	null	`],
	[`	M11.2	`,`	Other chondrocalcinosis Chondrocalcinosis NOS 	`,`	null	`],
	[`	M11.8	`,`	Other specified crystal arthropathies 	`,`	null	`],
	[`	M11.9	`,`	Crystal arthropathy, unspecified 	`,`	null	`],
	[`	M12	`,`	Other specific arthropathies [See site code at the beginning of this chapter] Excl.: arthropathy NOS (M13.9) arthrosis (M15-M19) cricoarytenoid arthropathy (J38.7) 	`,`	null	`],
	[`	M12.0	`,`	Chronic postrheumatic arthropathy [Jaccoud] 	`,`	null	`],
	[`	M12.1	`,`	Kaschin-Beck disease 	`,`	null	`],
	[`	M12.2	`,`	Villonodular synovitis (pigmented) 	`,`	null	`],
	[`	M12.3	`,`	Palindromic rheumatism 	`,`	null	`],
	[`	M12.4	`,`	Intermittent hydrarthrosis 	`,`	null	`],
	[`	M12.5	`,`	Traumatic arthropathy Excl.: post-traumatic arthrosis (of): NOS (M19.1) first carpometacarpal joint (M18.2-M18.3) hip (M16.4-M16.5) knee (M17.2-M17.3) other single joints (M19.1) 	`,`	null	`],
	[`	M12.8	`,`	Other specific arthropathies, not elsewhere classified Transient arthropathy 	`,`	null	`],
	[`	M13	`,`	Other arthritis [See site code at the beginning of this chapter] Excl.: arthrosis (M15-M19) 	`,`	null	`],
	[`	M13.0	`,`	Polyarthritis, unspecified 	`,`	null	`],
	[`	M13.1	`,`	Monoarthritis, not elsewhere classified 	`,`	null	`],
	[`	M13.8	`,`	Other specified arthritis Allergic arthritis 	`,`	null	`],
	[`	M13.9	`,`	Arthritis, unspecified Arthropathy NOS 	`,`	null	`],
	[`	M14*	`,`	Arthropathies in other diseases classified elsewhere Excl.: arthropathy in: haematological disorders (M36.2-M36.3*) hypersensitivity reactions (M36.4*) neoplastic disease (M36.1*) neuropathic spondylopathy (M49.4*) psoriatic and enteropathic arthropathies (M07.-*) psoriatic and enteropathic arthropathies juvenile (M09.-*) 	`,`	null	`],
	[`	M14.0*	`,`	Gouty arthropathy due to enzyme defects and other inherited disorders Gouty arthropathy in: Lesch-Nyhan syndrome (E79.1) sickle-cell disorders (D57.-) 	`,`	null	`],
	[`	M14.1*	`,`	Crystal arthropathy in other metabolic disorders Crystal arthropathy in hyperparathyroidism (E21.-) 	`,`	null	`],
	[`	M14.2*	`,`	Diabetic arthropathy (E10-E14 with common fourth character .6) Excl.: diabetic neuropathic arthropathy (M14.6*) 	`,`	null	`],
	[`	M14.3*	`,`	Lipoid dermatoarthritis (E78.8) 	`,`	null	`],
	[`	M14.4*	`,`	Arthropathy in amyloidosis (E85.-) 	`,`	null	`],
	[`	M14.5*	`,`	Arthropathies in other endocrine, nutritional and metabolic disorders Arthropathy in: acromegaly and pituitary gigantism (E22.0) haemochromatosis (E83.1) hypothyroidism (E00-E03) thyrotoxicosis [hyperthyroidism] (E05.-) 	`,`	null	`],
	[`	M14.6*	`,`	Neuropathic arthropathy Charcot or tabetic arthropathy (A52.1) Diabetic neuropathic arthropathy (E10-E14 with common fourth character .6) 	`,`	null	`],
	[`	M14.8*	`,`	Arthropathies in other specified diseases classified elsewhere Arthropathy in: erythema: multiforme (L51.-) nodosum (L52) sarcoidosis (D86.8) Whipple disease (K90.8) 	`,`	null	`],
	[`	M15	`,`	Polyarthrosis Incl.: arthrosis with mention of more than one site Excl.: bilateral involvement of single joint (M16-M19) 	`,`	null	`],
	[`	M15.0	`,`	Primary generalized (osteo)arthrosis 	`,`	null	`],
	[`	M15.1	`,`	Heberden nodes (with arthropathy) 	`,`	null	`],
	[`	M15.2	`,`	Bouchard nodes (with arthropathy) 	`,`	null	`],
	[`	M15.3	`,`	Secondary multiple arthrosis Post-traumatic polyarthrosis 	`,`	null	`],
	[`	M15.4	`,`	Erosive (osteo)arthrosis 	`,`	null	`],
	[`	M15.8	`,`	Other polyarthrosis 	`,`	null	`],
	[`	M15.9	`,`	Polyarthrosis, unspecified Generalized osteoarthritis NOS 	`,`	null	`],
	[`	M16	`,`	Coxarthrosis [arthrosis of hip] 	`,`	null	`],
	[`	M16.0	`,`	Primary coxarthrosis, bilateral 	`,`	null	`],
	[`	M16.1	`,`	Other primary coxarthrosis Primary coxarthrosis: NOS unilateral 	`,`	null	`],
	[`	M16.2	`,`	Coxarthrosis resulting from dysplasia, bilateral 	`,`	null	`],
	[`	M16.3	`,`	Other dysplastic coxarthrosis Dysplastic coxarthrosis: NOS unilateral 	`,`	null	`],
	[`	M16.4	`,`	Post-traumatic coxarthrosis, bilateral 	`,`	null	`],
	[`	M16.5	`,`	Other post-traumatic coxarthrosis Post-traumatic coxarthrosis: NOS unilateral 	`,`	null	`],
	[`	M16.6	`,`	Other secondary coxarthrosis, bilateral 	`,`	null	`],
	[`	M16.7	`,`	Other secondary coxarthrosis Secondary coxarthrosis: NOS unilateral 	`,`	null	`],
	[`	M16.9	`,`	Coxarthrosis, unspecified 	`,`	null	`],
	[`	M17	`,`	Gonarthrosis [arthrosis of knee] 	`,`	null	`],
	[`	M17.0	`,`	Primary gonarthrosis, bilateral 	`,`	null	`],
	[`	M17.1	`,`	Other primary gonarthrosis Primary gonarthrosis: NOS unilateral 	`,`	null	`],
	[`	M17.2	`,`	Post-traumatic gonarthrosis, bilateral 	`,`	null	`],
	[`	M17.3	`,`	Other post-traumatic gonarthrosis Post-traumatic gonarthrosis: NOS unilateral 	`,`	null	`],
	[`	M17.4	`,`	Other secondary gonarthrosis, bilateral 	`,`	null	`],
	[`	M17.5	`,`	Other secondary gonarthrosis Secondary gonarthrosis: NOS unilateral 	`,`	null	`],
	[`	M17.9	`,`	Gonarthrosis, unspecified 	`,`	null	`],
	[`	M18	`,`	Arthrosis of first carpometacarpal joint 	`,`	null	`],
	[`	M18.0	`,`	Primary arthrosis of first carpometacarpal joints, bilateral 	`,`	null	`],
	[`	M18.1	`,`	Other primary arthrosis of first carpometacarpal joint Primary arthrosis of first carpometacarpal joint: NOS unilateral 	`,`	null	`],
	[`	M18.2	`,`	Post-traumatic arthrosis of first carpometacarpal joints, bilateral 	`,`	null	`],
	[`	M18.3	`,`	Other post-traumatic arthrosis of first carpometacarpal joint Post-traumatic arthrosis of first carpometacarpal joint: NOS unilateral 	`,`	null	`],
	[`	M18.4	`,`	Other secondary arthrosis of first carpometacarpal joints, bilateral 	`,`	null	`],
	[`	M18.5	`,`	Other secondary arthrosis of first carpometacarpal joint Secondary arthrosis of first carpometacarpal joint: NOS unilateral 	`,`	null	`],
	[`	M18.9	`,`	Arthrosis of first carpometacarpal joint, unspecified 	`,`	null	`],
	[`	M19	`,`	Other arthrosis [See site code at the beginning of this chapter] Excl.: arthrosis of spine (M47.-) hallux rigidus (M20.2) polyarthrosis (M15.-) 	`,`	null	`],
	[`	M19.0	`,`	Primary arthrosis of other joints Primary arthrosis NOS 	`,`	null	`],
	[`	M19.1	`,`	Post-traumatic arthrosis of other joints Post-traumatic arthrosis NOS 	`,`	null	`],
	[`	M19.2	`,`	Other secondary arthrosis Secondary arthrosis NOS 	`,`	null	`],
	[`	M19.8	`,`	Other specified arthrosis 	`,`	null	`],
	[`	M19.9	`,`	Arthrosis, unspecified 	`,`	null	`],
	[`	M20	`,`	Acquired deformities of fingers and toes Excl.: acquired absence of fingers and toes (Z89.-) congenital: absence of fingers and toes (Q71.3, Q72.3) deformities and malformations of fingers and toes (Q66.-, Q68-Q70, Q74.-) 	`,`	null	`],
	[`	M20.0	`,`	Deformity of finger(s) Boutonniere and swan-neck deformities Excl.: clubbing of fingers (R68.3) palmar fascial fibromatosis [Dupuytren] (M72.0) trigger finger (M65.3) 	`,`	null	`],
	[`	M20.1	`,`	Hallux valgus (acquired) Bunion 	`,`	null	`],
	[`	M20.2	`,`	Hallux rigidus 	`,`	null	`],
	[`	M20.3	`,`	Other deformity of hallux (acquired) Hallux varus 	`,`	null	`],
	[`	M20.4	`,`	Other hammer toe(s) (acquired) 	`,`	null	`],
	[`	M20.5	`,`	Other deformities of toe(s) (acquired) 	`,`	null	`],
	[`	M20.6	`,`	Acquired deformity of toe(s), unspecified 	`,`	null	`],
	[`	M21	`,`	Other acquired deformities of limbs [See site code at the beginning of this chapter] Excl.: acquired absence of limb (Z89.-) acquired deformities of fingers or toes (M20.-) congenital: absence of limbs (Q71-Q73) deformities and malformations of limbs (Q65-Q66, Q68-Q74) coxa plana (M91.2) 	`,`	null	`],
	[`	M21.0	`,`	Valgus deformity, not elsewhere classified Excl.: metatarsus valgus (Q66.6) talipes calcaneovalgus (Q66.4) 	`,`	null	`],
	[`	M21.1	`,`	Varus deformity, not elsewhere classified Excl.: metatarsus varus (Q66.2) tibia vara (M92.5) 	`,`	null	`],
	[`	M21.2	`,`	Flexion deformity 	`,`	null	`],
	[`	M21.3	`,`	Wrist or foot drop (acquired) 	`,`	null	`],
	[`	M21.4	`,`	Flat foot [pes planus] (acquired) Excl.: congenital pes planus (Q66.5) 	`,`	null	`],
	[`	M21.5	`,`	Acquired clawhand, clubhand, clawfoot and clubfoot Excl.: clubfoot, not specified as acquired (Q66.8) 	`,`	null	`],
	[`	M21.6	`,`	Other acquired deformities of ankle and foot Excl.: deformities of toe (acquired) (M20.1-M20.6) 	`,`	null	`],
	[`	M21.7	`,`	Unequal limb length (acquired) 	`,`	null	`],
	[`	M21.8	`,`	Other specified acquired deformities of limbs 	`,`	null	`],
	[`	M21.9	`,`	Acquired deformity of limb, unspecified 	`,`	null	`],
	[`	M22	`,`	Disorders of patella Excl.: dislocation of patella (S83.0) 	`,`	null	`],
	[`	M22.0	`,`	Recurrent dislocation of patella 	`,`	null	`],
	[`	M22.1	`,`	Recurrent subluxation of patella 	`,`	null	`],
	[`	M22.2	`,`	Patellofemoral disorders 	`,`	null	`],
	[`	M22.3	`,`	Other derangements of patella 	`,`	null	`],
	[`	M22.4	`,`	Chondromalacia patellae 	`,`	null	`],
	[`	M22.8	`,`	Other disorders of patella 	`,`	null	`],
	[`	M22.9	`,`	Disorder of patella, unspecified 	`,`	null	`],
	[`	M23	`,`	Internal derangement of knee Excl.: ankylosis (M24.6) current injury - see injury to the knee and lower leg (S80-S89) deformity of knee (M21.-) disorders of patella (M22.-) osteochondritis dissecans (M93.2) recurrent dislocation or subluxation (M24.4) recurrent dislocation or subluxation patella (M22.0-M22.1) The following supplementary subclassification to indicate the site of involvement is provided for optional use with appropriate subcategories in M23.-; see also note at the beginning of this chapter. 	`,`	null	`],
	[`	0	`,`	Multiple sites 	`,`	null	`],
	[`	1	`,`	Anterior cruciate ligament or Anterior horn of medial meniscus 	`,`	null	`],
	[`	2	`,`	Posterior cruciate ligament or Posterior horn of medial meniscus 	`,`	null	`],
	[`	3	`,`	Medial collateral ligament or Other and unspecified medial meniscus 	`,`	null	`],
	[`	4	`,`	Lateral collateral ligament or Anterior horn of lateral meniscus 	`,`	null	`],
	[`	5	`,`	Posterior horn of lateral meniscus 	`,`	null	`],
	[`	6	`,`	Other and unspecified lateral meniscus 	`,`	null	`],
	[`	7	`,`	Capsular ligament 	`,`	null	`],
	[`	9	`,`	Unspecified ligament or Unspecified meniscus 	`,`	null	`],
	[`	M23.0	`,`	Cystic meniscus 	`,`	null	`],
	[`	M23.1	`,`	Discoid meniscus (congenital) 	`,`	null	`],
	[`	M23.2	`,`	Derangement of meniscus due to old tear or injury Old bucket-handle tear 	`,`	null	`],
	[`	M23.3	`,`	Other meniscus derangements Degenerate Detached Retained meniscus 	`,`	null	`],
	[`	M23.4	`,`	Loose body in knee 	`,`	null	`],
	[`	M23.5	`,`	Chronic instability of knee 	`,`	null	`],
	[`	M23.6	`,`	Other spontaneous disruption of ligament(s) of knee 	`,`	null	`],
	[`	M23.8	`,`	Other internal derangements of knee Laxity of ligament of knee Snapping knee 	`,`	null	`],
	[`	M23.9	`,`	Internal derangement of knee, unspecified 	`,`	null	`],
	[`	M24	`,`	Other specific joint derangements [See site code at the beginning of this chapter] Excl.: current injury - see injury of joint by body region ganglion (M67.4) snapping knee (M23.8) temporomandibular joint disorders (K07.6) 	`,`	null	`],
	[`	M24.0	`,`	Loose body in joint Excl.: loose body in knee (M23.4) 	`,`	null	`],
	[`	M24.1	`,`	Other articular cartilage disorders Excl.: chondrocalcinosis (M11.1-M11.2) internal derangement of knee (M23.-) metastatic calcification (E83.5) ochronosis (E70.2) 	`,`	null	`],
	[`	M24.2	`,`	Disorder of ligament Instability secondary to old ligament injury Ligamentous laxity NOS Excl.: familial ligamentous laxity (M35.7) knee (M23.5-M23.8) 	`,`	null	`],
	[`	M24.3	`,`	Pathological dislocation and subluxation of joint, not elsewhere classified Excl.: dislocation or displacement of joint: congenital - see congenital malformations and deformations of the musculoskeletal system (Q65-Q79) current injury - see injury of joints and ligaments by body region recurrent (M24.4) 	`,`	null	`],
	[`	M24.4	`,`	Recurrent dislocation and subluxation of joint Excl.: patella (M22.0-M22.1) vertebral subluxation (M43.3-M43.5) 	`,`	null	`],
	[`	M24.5	`,`	Contracture of joint Excl.: acquired deformities of limbs (M20-M21) contracture of tendon (sheath) without contracture of joint (M67.1) Dupuytren contracture (M72.0) 	`,`	null	`],
	[`	M24.6	`,`	Ankylosis of joint Excl.: spine (M43.2) stiffness of joint without ankylosis (M25.6) 	`,`	null	`],
	[`	M24.7	`,`	Protrusio acetabuli M24.8 Other specific joint derangements, not elsewhere classified Excl.: that involving iliotibial band syndrome (M76.3) 	`,`	null	`],
	[`	M24.9	`,`	Joint derangement, unspecified 	`,`	null	`],
	[`	M25	`,`	Other joint disorders, not elsewhere classified [See site code at the beginning of this chapter] Excl.: abnormality of gait and mobility (R26.-) calcification of: bursa (M71.4) shoulder (joint) (M75.3) tendon (M65.2) deformities classified to M20-M21 difficulty in walking (R26.2) 	`,`	null	`],
	[`	M25.0	`,`	Haemarthrosis Excl.: current injury - see injury of joint by body region 	`,`	null	`],
	[`	M25.1	`,`	Fistula of joint 	`,`	null	`],
	[`	M25.2	`,`	Flail joint 	`,`	null	`],
	[`	M25.3	`,`	Other instability of joint Excl.: instability of joint secondary to: old ligament injury (M24.2) removal of joint prosthesis (M96.8) 	`,`	null	`],
	[`	M25.4	`,`	Effusion of joint Excl.: hydrarthrosis of yaws (A66.6) 	`,`	null	`],
	[`	M25.5	`,`	Pain in joint 	`,`	null	`],
	[`	M25.6	`,`	Stiffness of joint, not elsewhere classified 	`,`	null	`],
	[`	M25.7	`,`	Osteophyte 	`,`	null	`],
	[`	M25.8	`,`	Other specified joint disorders 	`,`	null	`],
	[`	M25.9	`,`	Joint disorder, unspecified 	`,`	null	`],
	[`	M30	`,`	Polyarteritis nodosa and related conditions 	`,`	null	`],
	[`	M30.0	`,`	Polyarteritis nodosa 	`,`	null	`],
	[`	M30.1	`,`	Polyarteritis with lung involvement [Churg-Strauss] Allergic granulomatous angiitis 	`,`	null	`],
	[`	M30.2	`,`	Juvenile polyarteritis 	`,`	null	`],
	[`	M30.3	`,`	Mucocutaneous lymph node syndrome [Kawasaki] 	`,`	null	`],
	[`	M30.8	`,`	Other conditions related to polyarteritis nodosa Polyangiitis overlap syndrome 	`,`	null	`],
	[`	M31	`,`	Other necrotizing vasculopathies 	`,`	null	`],
	[`	M31.0	`,`	Hypersensitivity angiitis Goodpasture syndrome 	`,`	null	`],
	[`	M31.1	`,`	Thrombotic microangiopathy Thrombotic thrombocytopenic purpura 	`,`	null	`],
	[`	M31.2	`,`	Lethal midline granuloma 	`,`	null	`],
	[`	M31.3	`,`	Wegener granulomatosis Necrotizing respiratory granulomatosis 	`,`	null	`],
	[`	M31.4	`,`	Aortic arch syndrome [Takayasu] 	`,`	null	`],
	[`	M31.5	`,`	Giant cell arteritis with polymyalgia rheumatica 	`,`	null	`],
	[`	M31.6	`,`	Other giant cell arteritis 	`,`	null	`],
	[`	M31.7	`,`	Microscopic polyangiitis Microscopic polyarteritis Excl.: polyarteritis nodosa (M30.0) 	`,`	null	`],
	[`	M31.8	`,`	Other specified necrotizing vasculopathies Hypocomplementaemic vasculitis 	`,`	null	`],
	[`	M31.9	`,`	Necrotizing vasculopathy, unspecified 	`,`	null	`],
	[`	M32	`,`	Systemic lupus erythematosus Excl.: lupus erythematosus (discoid)(NOS) (L93.0) 	`,`	null	`],
	[`	M32.0	`,`	Drug-induced systemic lupus erythematosus Use additional external cause code (Chapter XX), if desired, to identify drug. 	`,`	null	`],
	[`	M32.1	`,`	Systemic lupus erythematosus with organ or system involvement Libman-Sacks disease (I39.-*) Lupus pericarditis (I32.8*) Systemic lupus erythematosus with: kidney involvement (N08.5*, N16.4*) lung involvement (J99.1*) 	`,`	null	`],
	[`	M32.8	`,`	Other forms of systemic lupus erythematosus 	`,`	null	`],
	[`	M32.9	`,`	Systemic lupus erythematosus, unspecified 	`,`	null	`],
	[`	M33	`,`	Dermatopolymyositis 	`,`	null	`],
	[`	M33.0	`,`	Juvenile dermatomyositis 	`,`	null	`],
	[`	M33.1	`,`	Other dermatomyositis 	`,`	null	`],
	[`	M33.2	`,`	Polymyositis 	`,`	null	`],
	[`	M33.9	`,`	Dermatopolymyositis, unspecified 	`,`	null	`],
	[`	M34	`,`	Systemic sclerosis Incl.: scleroderma Excl.: scleroderma: circumscribed (L94.0) neonatal (P83.8) 	`,`	null	`],
	[`	M34.0	`,`	Progressive systemic sclerosis 	`,`	null	`],
	[`	M34.1	`,`	CR(E)ST syndrome Combination of calcinosis, Raynaud phenomenon, (o)esophageal dysfunction, sclerodactyly, telangiectasia. 	`,`	null	`],
	[`	M34.2	`,`	Systemic sclerosis induced by drugs and chemicals Use additional external cause code (Chapter XX), if desired, to identify cause. 	`,`	null	`],
	[`	M34.8	`,`	Other forms of systemic sclerosis Systemic sclerosis with: lung involvement (J99.1*) myopathy (G73.7*) 	`,`	null	`],
	[`	M34.9	`,`	Systemic sclerosis, unspecified 	`,`	null	`],
	[`	M35	`,`	Other systemic involvement of connective tissue Excl.: reactive perforating collagenosis (L87.1) 	`,`	null	`],
	[`	M35.0	`,`	Sicca syndrome [Sjogren] Sjogren syndrome with: keratoconjunctivitis (H19.3*) lung involvement (J99.1*) myopathy (G73.7*) renal tubulo-interstitial disorders (N16.4*) 	`,`	null	`],
	[`	M35.1	`,`	Other overlap syndromes Mixed connective tissue disease Excl.: polyangiitis overlap syndrome (M30.8) 	`,`	null	`],
	[`	M35.2	`,`	Behcet disease 	`,`	null	`],
	[`	M35.3	`,`	Polymyalgia rheumatica Excl.: polymyalgia rheumatica with giant cell arteritis (M31.5) 	`,`	null	`],
	[`	M35.4	`,`	Diffuse (eosinophilic) fasciitis 	`,`	null	`],
	[`	M35.5	`,`	Multifocal fibrosclerosis 	`,`	null	`],
	[`	M35.6	`,`	Relapsing panniculitis [Weber-Christian] Excl.: panniculitis: NOS (M79.3) lupus (L93.2) 	`,`	null	`],
	[`	M35.7	`,`	Hypermobility syndrome Familial ligamentous laxity Excl.: Ehlers-Danlos syndrome (Q79.6) ligamentous laxity NOS (M24.2) 	`,`	null	`],
	[`	M35.8	`,`	Other specified systemic involvement of connective tissue 	`,`	null	`],
	[`	M35.9	`,`	Systemic involvement of connective tissue, unspecified Autoimmune disease (systemic) NOS Collagen (vascular) disease NOS 	`,`	null	`],
	[`	M36*	`,`	Systemic disorders of connective tissue in diseases classified elsewhere Excl.: arthropathies in diseases classified elsewhere (M14.-*) 	`,`	null	`],
	[`	M36.0*	`,`	Dermato(poly)myositis in neoplastic disease (C00-D48) 	`,`	null	`],
	[`	M36.1*	`,`	Arthropathy in neoplastic disease (C00-D48) Arthropathy in: leukaemia (C91-C95) malignant histiocytosis (C96.8) multiple myeloma (C90.0) 	`,`	null	`],
	[`	M36.2*	`,`	Haemophilic arthropathy (D66-D68) 	`,`	null	`],
	[`	M36.3*	`,`	Arthropathy in other blood disorders (D50-D76) Excl.: arthropathy in Henoch(-Schonlein) purpura (M36.4*) 	`,`	null	`],
	[`	M36.4*	`,`	Arthropathy in hypersensitivity reactions classified elsewhere Arthropathy in Henoch(-Schonlein) purpura (D69.0) 	`,`	null	`],
	[`	M36.8*	`,`	Systemic disorders of connective tissue in other diseases classified elsewhere Systemic disorders of connective tissue in: hypogammaglobulinaemia (D80.-) ochronosis (E70.2) 	`,`	null	`],
	[`	0	`,`	Multiple sites in spine 	`,`	null	`],
	[`	1	`,`	Occipito-atlanto-axial region 	`,`	null	`],
	[`	2	`,`	Cervical region 	`,`	null	`],
	[`	3	`,`	Cervicothoracic region 	`,`	null	`],
	[`	4	`,`	Thoracic region 	`,`	null	`],
	[`	5	`,`	Thoracolumbar region 	`,`	null	`],
	[`	6	`,`	Lumbar region 	`,`	null	`],
	[`	7	`,`	Lumbosacral region 	`,`	null	`],
	[`	8	`,`	Sacral and sacrococcygeal region 	`,`	null	`],
	[`	9	`,`	Site unspecified 	`,`	null	`],
	[`	M40	`,`	Kyphosis and lordosis [See site code before M40] Excl.: kyphoscoliosis (M41.-) kyphosis and lordosis: congenital (Q76.4) postprocedural (M96.-) 	`,`	null	`],
	[`	M40.0	`,`	Postural kyphosis Excl.: osteochondrosis of spine (M42.-) 	`,`	null	`],
	[`	M40.1	`,`	Other secondary kyphosis 	`,`	null	`],
	[`	M40.2	`,`	Other and unspecified kyphosis 	`,`	null	`],
	[`	M40.3	`,`	Flatback syndrome 	`,`	null	`],
	[`	M40.4	`,`	Other lordosis Lordosis: acquired postural 	`,`	null	`],
	[`	M40.5	`,`	Lordosis, unspecified 	`,`	null	`],
	[`	M41	`,`	Scoliosis [See site code before M40] Incl.: kyphoscoliosis Excl.: congenital scoliosis: NOS (Q67.5) due to bony malformation (Q76.3) postural (Q67.5) kyphoscoliotic heart disease (I27.1) postprocedural (M96.-) 	`,`	null	`],
	[`	M41.0	`,`	Infantile idiopathic scoliosis 	`,`	null	`],
	[`	M41.1	`,`	Juvenile idiopathic scoliosis Adolescent scoliosis 	`,`	null	`],
	[`	M41.2	`,`	Other idiopathic scoliosis 	`,`	null	`],
	[`	M41.3	`,`	Thoracogenic scoliosis 	`,`	null	`],
	[`	M41.4	`,`	Neuromuscular scoliosis Scoliosis secondary to cerebral palsy, Friedreich ataxia, poliomyelitis, and other neuromuscular disorders. 	`,`	null	`],
	[`	M41.5	`,`	Other secondary scoliosis 	`,`	null	`],
	[`	M41.8	`,`	Other forms of scoliosis 	`,`	null	`],
	[`	M41.9	`,`	Scoliosis, unspecified 	`,`	null	`],
	[`	M42	`,`	Spinal osteochondrosis [See site code before M40] Excl.: postural kyphosis (M40.0) 	`,`	null	`],
	[`	M42.0	`,`	Juvenile osteochondrosis of spine Calve disease Scheuermann disease Excl.: postural kyphosis (M40.0) 	`,`	null	`],
	[`	M42.1	`,`	Adult osteochondrosis of spine 	`,`	null	`],
	[`	M42.9	`,`	Spinal osteochondrosis, unspecified 	`,`	null	`],
	[`	M43	`,`	Other deforming dorsopathies [See site code before M40] Excl.: congenital spondylolysis and spondylolisthesis (Q76.2) hemivertebra (Q76.3-Q76.4) Klippel-Feil syndrome (Q76.1) lumbarization and sacralization (Q76.4) platyspondylisis (Q76.4) spina bifida occulta (Q76.0) spinal curvature in: osteoporosis (M80-M81) Paget disease of bone [osteitis deformans] (M88.-) 	`,`	null	`],
	[`	M43.0	`,`	Spondylolysis 	`,`	null	`],
	[`	M43.1	`,`	Spondylolisthesis 	`,`	null	`],
	[`	M43.2	`,`	Other fusion of spine Ankylosis of spinal joint Excl.: ankylosing spondylitis (M45) arthrodesis status (Z98.1) pseudoarthrosis after fusion or arthrodesis (M96.0) 	`,`	null	`],
	[`	M43.3	`,`	Recurrent atlantoaxial subluxation with myelopathy 	`,`	null	`],
	[`	M43.4	`,`	Other recurrent atlantoaxial subluxation 	`,`	null	`],
	[`	M43.5	`,`	Other recurrent vertebral subluxation Excl.: biomechanical lesions NEC (M99.-) 	`,`	null	`],
	[`	M43.6	`,`	Torticollis Excl.: torticollis: congenital (sternomastoid) (Q68.0) current injury - see injury of spine by body region due to birth injury (P15.2) psychogenic (F45.8) spasmodic (G24.3) 	`,`	null	`],
	[`	M43.8	`,`	Other specified deforming dorsopathies Excl.: kyphosis and lordosis (M40.-) scoliosis (M41.-) 	`,`	null	`],
	[`	M43.9	`,`	Deforming dorsopathy, unspecified Curvature of spine NOS 	`,`	null	`],
	[`	M60	`,`	Myositis [See site code at the beginning of this chapter] 	`,`	null	`],
	[`	M60.0	`,`	Infective myositis Tropical pyomyositis Use additional code (B95-B98), if desired, to identify infectious agent. 	`,`	null	`],
	[`	M60.1	`,`	Interstitial myositis 	`,`	null	`],
	[`	M60.2	`,`	Foreign body granuloma of soft tissue, not elsewhere classified Excl.: foreign body granuloma of skin and subcutaneous tissue (L92.3) 	`,`	null	`],
	[`	M60.8	`,`	Other myositis 	`,`	null	`],
	[`	M60.9	`,`	Myositis, unspecified 	`,`	null	`],
	[`	M61	`,`	Calcification and ossification of muscle [See site code at the beginning of this chapter] 	`,`	null	`],
	[`	M61.0	`,`	Myositis ossificans traumatica 	`,`	null	`],
	[`	M61.1	`,`	Myositis ossificans progressiva Fibrodysplasia ossificans progressiva 	`,`	null	`],
	[`	M61.2	`,`	Paralytic calcification and ossification of muscle Myositis ossificans associated with quadriplegia or paraplegia 	`,`	null	`],
	[`	M61.3	`,`	Calcification and ossification of muscles associated with burns Myositis ossificans associated with burns 	`,`	null	`],
	[`	M61.4	`,`	Other calcification of muscle Excl.: calcific tendinitis (M65.2) calcific tendinitis of shoulder (M75.3) 	`,`	null	`],
	[`	M61.5	`,`	Other ossification of muscle 	`,`	null	`],
	[`	M61.9	`,`	Calcification and ossification of muscle, unspecified 	`,`	null	`],
	[`	M62	`,`	Other disorders of muscle [See site code at the beginning of this chapter] Excl.: cramp and spasm (R25.2) myalgia (M79.1) myopathy: alcoholic (G72.1) drug-induced (G72.0) stiff-man syndrome (G25.8) 	`,`	null	`],
	[`	M62.0	`,`	Diastasis of muscle 	`,`	null	`],
	[`	M62.1	`,`	Other rupture of muscle (nontraumatic) Excl.: rupture of tendon (M66.-) traumatic rupture of muscle - see injury of muscle by body region 	`,`	null	`],
	[`	M62.2	`,`	Ischaemic infarction of muscle Compartment syndrome, non-traumatic Excl.: compartment syndrome, traumatic (T79.6) traumatic ischaemia of muscle (T79.6) Volkmann ischaemic contracture (T79.6) 	`,`	null	`],
	[`	M62.3	`,`	Immobility syndrome (paraplegic) 	`,`	null	`],
	[`	M62.4	`,`	Contracture of muscle Excl.: contracture of joint (M24.5) 	`,`	null	`],
	[`	M62.5	`,`	Muscle wasting and atrophy, not elsewhere classified Disuse atrophy NEC 	`,`	null	`],
	[`	M62.6	`,`	Muscle strain Excl.: current injury - see injury of muscle by body region 	`,`	null	`],
	[`	M62.8	`,`	Other specified disorders of muscle Muscle (sheath) hernia 	`,`	null	`],
	[`	M62.9	`,`	Disorder of muscle, unspecified 	`,`	null	`],
	[`	M63*	`,`	Disorders of muscle in diseases classified elsewhere Excl.: myopathy in: endocrine diseases (G73.5*) metabolic diseases (G73.6*) 	`,`	null	`],
	[`	M63.0*	`,`	Myositis in bacterial diseases classified elsewhere Myositis in: leprosy [Hansen disease] (A30.-) syphilis (A51.4, A52.7) 	`,`	null	`],
	[`	M63.1*	`,`	Myositis in protozoal and parasitic infections classified elsewhere Myositis in: cysticercosis (B69.8) schistosomiasis [bilharziasis] (B65.-) toxoplasmosis (B58.8) trichinellosis (B75) 	`,`	null	`],
	[`	M63.2*	`,`	Myositis in other infectious diseases classified elsewhere Myositis in mycosis (B35-B49) 	`,`	null	`],
	[`	M63.3*	`,`	Myositis in sarcoidosis (D86.8) 	`,`	null	`],
	[`	M63.8*	`,`	Other disorders of muscle in diseases classified elsewhere 	`,`	null	`],
	[`	M65	`,`	Synovitis and tenosynovitis [See site code at the beginning of this chapter] Excl.: chronic crepitant synovitis of hand and wrist (M70.0) current injury - see injury of ligament or tendon by body region soft tissue disorders related to use, overuse and pressure (M70.-) 	`,`	null	`],
	[`	M65.0	`,`	Abscess of tendon sheath Use additional code (B95-B96), if desired, to identify bacterial agent. 	`,`	null	`],
	[`	M65.1	`,`	Other infective (teno)synovitis 	`,`	null	`],
	[`	M65.2	`,`	Calcific tendinitis Excl.: of shoulder (M75.3) specified tendinitis (M75-M77) 	`,`	null	`],
	[`	M65.3	`,`	Trigger finger Nodular tendinous disease 	`,`	null	`],
	[`	M65.4	`,`	Radial styloid tenosynovitis [de Quervain] 	`,`	null	`],
	[`	M65.8	`,`	Other synovitis and tenosynovitis Irritable hip 	`,`	null	`],
	[`	M65.9	`,`	Synovitis and tenosynovitis, unspecified 	`,`	null	`],
	[`	M66	`,`	Spontaneous rupture of synovium and tendon [See site code at the beginning of this chapter] Incl.: rupture that occurs when a normal force is applied to tissues that are inferred to have less than normal strength Excl.: rotator cuff syndrome (M75.1) rupture where an abnormal force is applied to normal tissue - see injury of tendon by body region 	`,`	null	`],
	[`	M66.0	`,`	Rupture of popliteal cyst 	`,`	null	`],
	[`	M66.1	`,`	Rupture of synovium Rupture of synovial cyst Excl.: rupture of popliteal cyst (M66.0) 	`,`	null	`],
	[`	M66.2	`,`	Spontaneous rupture of extensor tendons 	`,`	null	`],
	[`	M66.3	`,`	Spontaneous rupture of flexor tendons 	`,`	null	`],
	[`	M66.4	`,`	Spontaneous rupture of other tendons 	`,`	null	`],
	[`	M66.5	`,`	Spontaneous rupture of unspecified tendon Rupture at musculotendinous junction, nontraumatic 	`,`	null	`],
	[`	M67	`,`	Other disorders of synovium and tendon Excl.: palmar fascial fibromatosis [Dupuytren] (M72.0) tendinitis NOS (M77.9) xanthomatosis localized to tendons (E78.2) 	`,`	null	`],
	[`	M67.0	`,`	Short Achilles tendon (acquired) 	`,`	null	`],
	[`	M67.1	`,`	Other contracture of tendon (sheath) Excl.: with contracture of joint (M24.5) 	`,`	null	`],
	[`	M67.2	`,`	Synovial hypertrophy, not elsewhere classified Excl.: villonodular synovitis (pigmented) (M12.2) 	`,`	null	`],
	[`	M67.3	`,`	Transient synovitis Toxic synovitis Excl.: palindromic rheumatism (M12.3) 	`,`	null	`],
	[`	M67.4	`,`	Ganglion Ganglion of joint or tendon (sheath) Excl.: cyst of: bursa (M71.2-M71.3) synovium (M71.2-M71.3) ganglion in yaws (A66.6) 	`,`	null	`],
	[`	M67.8	`,`	Other specified disorders of synovium and tendon 	`,`	null	`],
	[`	M67.9	`,`	Disorder of synovium and tendon, unspecified 	`,`	null	`],
	[`	M68*	`,`	Disorders of synovium and tendon in diseases classified elsewhere 	`,`	null	`],
	[`	M68.0*	`,`	Synovitis and tenosynovitis in bacterial diseases classified elsewhere Synovitis or tenosynovitis in: gonorrhoea (A54.4) syphilis (A52.7) tuberculosis (A18.0) 	`,`	null	`],
	[`	M68.8*	`,`	Other disorders of synovium and tendon in diseases classified elsewhere 	`,`	null	`],
	[`	M70	`,`	Soft tissue disorders related to use, overuse and pressure [See site code at the beginning of this chapter] Incl.: soft tissue disorders of occupational origin Excl.: bursitis (of): NOS (M71.9) shoulder (M75.5) decubitus ulcer and pressure area (L89.-) enthesopathies (M76-M77) 	`,`	null	`],
	[`	M70.0	`,`	Chronic crepitant synovitis of hand and wrist 	`,`	null	`],
	[`	M70.1	`,`	Bursitis of hand 	`,`	null	`],
	[`	M70.2	`,`	Olecranon bursitis 	`,`	null	`],
	[`	M70.3	`,`	Other bursitis of elbow 	`,`	null	`],
	[`	M70.4	`,`	Prepatellar bursitis 	`,`	null	`],
	[`	M70.5	`,`	Other bursitis of knee 	`,`	null	`],
	[`	M70.6	`,`	Trochanteric bursitis Trochanteric tendinitis 	`,`	null	`],
	[`	M70.7	`,`	Other bursitis of hip Ischial bursitis 	`,`	null	`],
	[`	M70.8	`,`	Other soft tissue disorders related to use, overuse and pressure 	`,`	null	`],
	[`	M70.9	`,`	Unspecified soft tissue disorder related to use, overuse and pressure 	`,`	null	`],
	[`	M71	`,`	Other bursopathies [See site code at the beginning of this chapter] Excl.: bunion (M20.1) bursitis related to use, overuse and pressure (M70.-) enthesopathies (M76-M77) 	`,`	null	`],
	[`	M71.0	`,`	Abscess of bursa 	`,`	null	`],
	[`	M71.1	`,`	Other infective bursitis 	`,`	null	`],
	[`	M71.2	`,`	Synovial cyst of popliteal space [Baker] Excl.: with rupture (M66.0) 	`,`	null	`],
	[`	M71.3	`,`	Other bursal cyst Synovial cyst NOS Excl.: synovial cyst with rupture (M66.1) 	`,`	null	`],
	[`	M71.4	`,`	Calcium deposit in bursa Excl.: of shoulder (M75.3) 	`,`	null	`],
	[`	M71.5	`,`	Other bursitis, not elsewhere classified Excl.: bursitis (of): NOS (M71.9) shoulder (M75.5) tibial collateral [Pellegrini-Stieda] (M76.4) 	`,`	null	`],
	[`	M71.8	`,`	Other specified bursopathies 	`,`	null	`],
	[`	M71.9	`,`	Bursopathy, unspecified Bursitis NOS 	`,`	null	`],
	[`	M72	`,`	Fibroblastic disorders [See site code at the beginning of this chapter] Excl.: retroperitoneal fibromatosis (D48.3) 	`,`	null	`],
	[`	M72.0	`,`	Palmar fascial fibromatosis [Dupuytren] 	`,`	null	`],
	[`	M72.1	`,`	Knuckle pads 	`,`	null	`],
	[`	M72.2	`,`	Plantar fascial fibromatosis Plantar fasciitis 	`,`	null	`],
	[`	M72.4	`,`	Pseudosarcomatous fibromatosis Nodular fasciitis 	`,`	null	`],
	[`	M72.6	`,`	Necrotizing fasciitis Use additional code, if desired, to identify infectious agent 	`,`	null	`],
	[`	M72.8	`,`	Other fibroblastic disorders Abscess of fascia Excl.: fasciitis: diffuse (eosinophilic) (M35.4) necrotizing (M72.6) nodular (M72.4) perirenal: NOS (N13.5) with infection (N13.6) plantar (M72.2) 	`,`	null	`],
	[`	M72.9	`,`	Fibroblastic disorder, unspecified Fasciitis NOS Fibromatosis NOS 	`,`	null	`],
	[`	M73*	`,`	Soft tissue disorders in diseases classified elsewhere [See site code at the beginning of this chapter] 	`,`	null	`],
	[`	M73.0*	`,`	Gonococcal bursitis (A54.4) 	`,`	null	`],
	[`	M73.1*	`,`	Syphilitic bursitis (A52.7) 	`,`	null	`],
	[`	M73.8*	`,`	Other soft tissue disorders in diseases classified elsewhere 	`,`	null	`],
	[`	M75	`,`	Shoulder lesions Excl.: shoulder-hand syndrome (M89.0) 	`,`	null	`],
	[`	M75.0	`,`	Adhesive capsulitis of shoulder Frozen shoulder Periarthritis of shoulder 	`,`	null	`],
	[`	M75.1	`,`	Rotator cuff syndrome Rotator cuff or supraspinatus tear or rupture (complete)(incomplete), not specified as traumatic Supraspinatus syndrome 	`,`	null	`],
	[`	M75.2	`,`	Bicipital tendinitis 	`,`	null	`],
	[`	M75.3	`,`	Calcific tendinitis of shoulder Calcified bursa of shoulder 	`,`	null	`],
	[`	M75.4	`,`	Impingement syndrome of shoulder 	`,`	null	`],
	[`	M75.5	`,`	Bursitis of shoulder 	`,`	null	`],
	[`	M75.8	`,`	Other shoulder lesions 	`,`	null	`],
	[`	M75.9	`,`	Shoulder lesion, unspecified 	`,`	null	`],
	[`	M76	`,`	Enthesopathies of lower limb, excluding foot [See site code at the beginning of this chapter] Note: The superficially specific terms bursitis, capsulitis and tendinitis tend to be used indiscriminately for various disorders of peripheral ligamentous or muscular attachments; most of these conditions have been brought together as enthesopathies which is the generic term for lesions at these sites. Excl.: bursitis due to use, overuse and pressure (M70.-) 	`,`	null	`],
	[`	M76.0	`,`	Gluteal tendinitis 	`,`	null	`],
	[`	M76.1	`,`	Psoas tendinitis 	`,`	null	`],
	[`	M76.2	`,`	Iliac crest spur 	`,`	null	`],
	[`	M76.3	`,`	Iliotibial band syndrome 	`,`	null	`],
	[`	M76.4	`,`	Tibial collateral bursitis [Pellegrini-Stieda] 	`,`	null	`],
	[`	M76.5	`,`	Patellar tendinitis 	`,`	null	`],
	[`	M76.6	`,`	Achilles tendinitis Achilles bursitis 	`,`	null	`],
	[`	M76.7	`,`	Peroneal tendinitis 	`,`	null	`],
	[`	M76.8	`,`	Other enthesopathies of lower limb, excluding foot Anterior tibial syndrome Posterior tibial tendinitis 	`,`	null	`],
	[`	M76.9	`,`	Enthesopathy of lower limb, unspecified 	`,`	null	`],
	[`	M77	`,`	Other enthesopathies [See site code at the beginning of this chapter] Excl.: bursitis: NOS (M71.9) due to use, overuse and pressure (M70.-) osteophyte (M25.7) spinal enthesopathy (M46.0) 	`,`	null	`],
	[`	M77.0	`,`	Medial epicondylitis 	`,`	null	`],
	[`	M77.1	`,`	Lateral epicondylitis Tennis elbow 	`,`	null	`],
	[`	M77.2	`,`	Periarthritis of wrist 	`,`	null	`],
	[`	M77.3	`,`	Calcaneal spur 	`,`	null	`],
	[`	M77.4	`,`	Metatarsalgia Excl.: Morton metatarsalgia (G57.6) 	`,`	null	`],
	[`	M77.5	`,`	Other enthesopathy of foot 	`,`	null	`],
	[`	M77.8	`,`	Other enthesopathies, not elsewhere classified 	`,`	null	`],
	[`	M77.9	`,`	Enthesopathy, unspecified Bone spur NOS Capsulitis NOS Periarthritis NOS Tendinitis NOS 	`,`	null	`],
	[`	M79	`,`	Other soft tissue disorders, not elsewhere classified [See site code at the beginning of this chapter] Excl.: soft tissue pain, psychogenic (F45.4) 	`,`	null	`],
	[`	M79.0	`,`	Rheumatism, unspecified Excl.: fibromyalgia (M79.7) palindromic rheumatism (M12.3) 	`,`	null	`],
	[`	M79.1	`,`	Myalgia Excl.: myositis (M60.-) 	`,`	null	`],
	[`	M79.2	`,`	Neuralgia and neuritis, unspecified Excl.: mononeuropathies (G56-G58) radiculitis: NOS (M54.1) brachial NOS (M54.1) lumbosacral NOS (M54.1) sciatica (M54.3-M54.4) 	`,`	null	`],
	[`	M79.3	`,`	Panniculitis, unspecified Excl.: panniculitis: lupus (L93.2) neck and back (M54.0) relapsing [Weber-Christian] (M35.6) 	`,`	null	`],
	[`	M79.4	`,`	Hypertrophy of (infrapatellar) fat pad 	`,`	null	`],
	[`	M79.5	`,`	Residual foreign body in soft tissue Excl.: foreign body granuloma of: skin and subcutaneous tissue (L92.3) soft tissue (M60.2) 	`,`	null	`],
	[`	M79.6	`,`	Pain in limb 	`,`	null	`],
	[`	M79.7	`,`	Fibromyalgia Fibromyositis Fibrositis Myofibrositis 	`,`	null	`],
	[`	M79.8	`,`	Other specified soft tissue disorders 	`,`	null	`],
	[`	M79.9	`,`	Soft tissue disorder, unspecified 	`,`	null	`],
	[`	M80	`,`	Osteoporosis with pathological fracture [See site code at the beginning of this chapter] Incl.: osteoporotic vertebral collapse and wedging Excl.: collapsed vertebra NOS (M48.5) pathological fracture NOS (M84.4) wedging of vertebra NOS (M48.5) 	`,`	null	`],
	[`	M80.0	`,`	Postmenopausal osteoporosis with pathological fracture 	`,`	null	`],
	[`	M80.1	`,`	Postoophorectomy osteoporosis with pathological fracture 	`,`	null	`],
	[`	M80.2	`,`	Osteoporosis of disuse with pathological fracture 	`,`	null	`],
	[`	M80.3	`,`	Postsurgical malabsorption osteoporosis with pathological fracture 	`,`	null	`],
	[`	M80.4	`,`	Drug-induced osteoporosis with pathological fracture Use additional external cause code (Chapter XX), if desired, to identify drug. 	`,`	null	`],
	[`	M80.5	`,`	Idiopathic osteoporosis with pathological fracture 	`,`	null	`],
	[`	M80.8	`,`	Other osteoporosis with pathological fracture 	`,`	null	`],
	[`	M80.9	`,`	Unspecified osteoporosis with pathological fracture 	`,`	null	`],
	[`	M81	`,`	Osteoporosis without pathological fracture [See site code at the beginning of this chapter] Excl.: osteoporosis with pathological fracture (M80.-) 	`,`	null	`],
	[`	M81.0	`,`	Postmenopausal osteoporosis 	`,`	null	`],
	[`	M81.1	`,`	Postoophorectomy osteoporosis 	`,`	null	`],
	[`	M81.2	`,`	Osteoporosis of disuse Excl.: Sudeck atrophy (M89.0) 	`,`	null	`],
	[`	M81.3	`,`	Postsurgical malabsorption osteoporosis 	`,`	null	`],
	[`	M81.4	`,`	Drug-induced osteoporosis Use additional external cause code (Chapter XX), if desired, to identify drug. 	`,`	null	`],
	[`	M81.5	`,`	Idiopathic osteoporosis 	`,`	null	`],
	[`	M81.6	`,`	Localized osteoporosis [Lequesne] Excl.: Sudeck atrophy (M89.0) 	`,`	null	`],
	[`	M81.8	`,`	Other osteoporosis Senile osteoporosis 	`,`	null	`],
	[`	M81.9	`,`	Osteoporosis, unspecified 	`,`	null	`],
	[`	M82*	`,`	Osteoporosis in diseases classified elsewhere [See site code at the beginning of this chapter] 	`,`	null	`],
	[`	M82.0*	`,`	Osteoporosis in multiple myelomatosis (C90.0) 	`,`	null	`],
	[`	M82.1*	`,`	Osteoporosis in endocrine disorders (E00-E34) 	`,`	null	`],
	[`	M82.8*	`,`	Osteoporosis in other diseases classified elsewhere 	`,`	null	`],
	[`	M83	`,`	Adult osteomalacia [See site code at the beginning of this chapter] Excl.: osteomalacia: infantile and juvenile (E55.0) vitamin-D-resistant (E83.3) renal osteodystrophy (N25.0) rickets (active) (E55.0) rickets (active) sequelae (E64.3) vitamin-D-resistant (E83.3) 	`,`	null	`],
	[`	M83.0	`,`	Puerperal osteomalacia 	`,`	null	`],
	[`	M83.1	`,`	Senile osteomalacia 	`,`	null	`],
	[`	M83.2	`,`	Adult osteomalacia due to malabsorption Postsurgical malabsorption osteomalacia in adults 	`,`	null	`],
	[`	M83.3	`,`	Adult osteomalacia due to malnutrition 	`,`	null	`],
	[`	M83.4	`,`	Aluminium bone disease 	`,`	null	`],
	[`	M83.5	`,`	Other drug-induced osteomalacia in adults Use additional external cause code (Chapter XX), if desired, to identify drug. 	`,`	null	`],
	[`	M83.8	`,`	Other adult osteomalacia 	`,`	null	`],
	[`	M83.9	`,`	Adult osteomalacia, unspecified 	`,`	null	`],
	[`	M84	`,`	Disorders of continuity of bone [See site code at the beginning of this chapter] 	`,`	null	`],
	[`	M84.0	`,`	Malunion of fracture 	`,`	null	`],
	[`	M84.1	`,`	Nonunion of fracture [pseudarthrosis] Excl.: pseudarthrosis after fusion or arthrodesis (M96.0) 	`,`	null	`],
	[`	M84.2	`,`	Delayed union of fracture 	`,`	null	`],
	[`	M84.3	`,`	Stress fracture, not elsewhere classified Stress fracture NOS Excl.: stress fracture of vertebra (M48.4) 	`,`	null	`],
	[`	M84.4	`,`	Pathological fracture, not elsewhere classified Pathological fracture NOS Excl.: collapsed vertebra NEC (M48.5) pathological fracture in osteoporosis (M80.-) 	`,`	null	`],
	[`	M84.8	`,`	Other disorders of continuity of bone 	`,`	null	`],
	[`	M84.9	`,`	Disorder of continuity of bone, unspecified 	`,`	null	`],
	[`	M85	`,`	Other disorders of bone density and structure [See site code at the beginning of this chapter] Excl.: osteogenesis imperfecta (Q78.0) osteopetrosis (Q78.2) osteopoikilosis (Q78.8) polyostotic fibrous dysplasia (Q78.1) 	`,`	null	`],
	[`	M85.0	`,`	Fibrous dysplasia (monostotic) Excl.: fibrous dysplasia of jaw (K10.8) 	`,`	null	`],
	[`	M85.1	`,`	Skeletal fluorosis 	`,`	null	`],
	[`	M85.2	`,`	Hyperostosis of skull 	`,`	null	`],
	[`	M85.3	`,`	Osteitis condensans 	`,`	null	`],
	[`	M85.4	`,`	Solitary bone cyst Excl.: solitary cyst of jaw (K09.1-K09.2) 	`,`	null	`],
	[`	M85.5	`,`	Aneurysmal bone cyst Excl.: aneurysmal cyst of jaw (K09.2) 	`,`	null	`],
	[`	M85.6	`,`	Other cyst of bone Excl.: cyst of jaw NEC (K09.1-K09.2) osteitis fibrosa cystica generalisata [von Recklinghausen disease of bone] (E21.0) 	`,`	null	`],
	[`	M85.8	`,`	Other specified disorders of bone density and structure Hyperostosis of bones, except skull Osteosclerosis, acquired Excl.: diffuse idiopathic skeletal hyperostosis [DISH] (M48.1) osteosclerosis: congenita (Q77.4) myelofibrosis (D75.8) 	`,`	null	`],
	[`	M85.9	`,`	Disorder of bone density and structure, unspecified 	`,`	null	`],
	[`	M86	`,`	Osteomyelitis [See site code at the beginning of this chapter] Use additional code (B95-B98), if desired, to identify infectious agent. Excl.: osteomyelitis (of): due to salmonella (A01-A02) jaw (K10.2) vertebra (M46.2) 	`,`	null	`],
	[`	M86.0	`,`	Acute haematogenous osteomyelitis 	`,`	null	`],
	[`	M86.1	`,`	Other acute osteomyelitis 	`,`	null	`],
	[`	M86.2	`,`	Subacute osteomyelitis 	`,`	null	`],
	[`	M86.3	`,`	Chronic multifocal osteomyelitis 	`,`	null	`],
	[`	M86.4	`,`	Chronic osteomyelitis with draining sinus 	`,`	null	`],
	[`	M86.5	`,`	Other chronic haematogenous osteomyelitis 	`,`	null	`],
	[`	M86.6	`,`	Other chronic osteomyelitis 	`,`	null	`],
	[`	M86.8	`,`	Other osteomyelitis Brodie abscess 	`,`	null	`],
	[`	M86.9	`,`	Osteomyelitis, unspecified Infection of bone NOS Periostitis without mention of osteomyelitis 	`,`	null	`],
	[`	M87	`,`	Osteonecrosis [See site code at the beginning of this chapter] Incl.: avascular necrosis of bone Excl.: osteochondropathies (M91-M93) osteonecrosis of jaw (drug-induced) (radiation-induced) (K10.2) 	`,`	null	`],
	[`	M87.0	`,`	Idiopathic aseptic necrosis of bone 	`,`	null	`],
	[`	M87.1	`,`	Osteonecrosis due to drugs Use additional external cause code (Chapter XX), if desired, to identify drug. 	`,`	null	`],
	[`	M87.2	`,`	Osteonecrosis due to previous trauma 	`,`	null	`],
	[`	M87.3	`,`	Other secondary osteonecrosis 	`,`	null	`],
	[`	M87.8	`,`	Other osteonecrosis 	`,`	null	`],
	[`	M87.9	`,`	Osteonecrosis, unspecified 	`,`	null	`],
	[`	M88	`,`	Paget disease of bone [osteitis deformans] [See site code at the beginning of this chapter] 	`,`	null	`],
	[`	M88.0	`,`	Paget disease of skull 	`,`	null	`],
	[`	M88.8	`,`	Paget disease of other bones 	`,`	null	`],
	[`	M88.9	`,`	Paget disease of bone, unspecified 	`,`	null	`],
	[`	M89	`,`	Other disorders of bone [See site code at the beginning of this chapter] 	`,`	null	`],
	[`	M89.0	`,`	Algoneurodystrophy Shoulder-hand syndrome Sudeck atrophy Sympathetic reflex dystrophy 	`,`	null	`],
	[`	M89.1	`,`	Epiphyseal arrest 	`,`	null	`],
	[`	M89.2	`,`	Other disorders of bone development and growth 	`,`	null	`],
	[`	M89.3	`,`	Hypertrophy of bone 	`,`	null	`],
	[`	M89.4	`,`	Other hypertrophic osteoarthropathy Marie-Bamberger disease Pachydermoperiostosis 	`,`	null	`],
	[`	M89.5	`,`	Osteolysis 	`,`	null	`],
	[`	M89.6	`,`	Osteopathy after poliomyelitis Use additional code (B91) , if desired, to identify previous poliomyelitis. Excl.: postpolio syndrome (G14) 	`,`	null	`],
	[`	M89.8	`,`	Other specified disorders of bone Infantile cortical hyperostoses Post-traumatic subperiosteal ossification 	`,`	null	`],
	[`	M89.9	`,`	Disorder of bone, unspecified 	`,`	null	`],
	[`	M90*	`,`	Osteopathies in diseases classified elsewhere [See site code at the beginning of this chapter] 	`,`	null	`],
	[`	M90.0*	`,`	Tuberculosis of bone (A18.0) Excl.: tuberculosis of spine (M49.0*) 	`,`	null	`],
	[`	M90.1*	`,`	Periostitis in other infectious diseases classified elsewhere Secondary syphilitic periostitis (A51.4) 	`,`	null	`],
	[`	M90.2*	`,`	Osteopathy in other infectious diseases classified elsewhere Osteomyelitis: echinococcal (B67.2) gonococcal (A54.4) salmonella (A02.2) Syphilitic osteopathy or osteochondropathy (A50.5, A52.7) 	`,`	null	`],
	[`	M90.3*	`,`	Osteonecrosis in caisson disease (T70.3) 	`,`	null	`],
	[`	M90.4*	`,`	Osteonecrosis due to haemoglobinopathy (D50-D64) 	`,`	null	`],
	[`	M90.5*	`,`	Osteonecrosis in other diseases classified elsewhere 	`,`	null	`],
	[`	M90.6*	`,`	Osteitis deformans in neoplastic disease (C00-D48) Osteitis deformans in malignant neoplasm of bone (C40-C41) 	`,`	null	`],
	[`	M90.7*	`,`	Fracture of bone in neoplastic disease (C00-D48) Excl.: collapse of vertebra in neoplastic disease (M49.5*) 	`,`	null	`],
	[`	M90.8*	`,`	Osteopathy in other diseases classified elsewhere Osteopathy in renal osteodystrophy (N25.0) 	`,`	null	`],
	[`	M91	`,`	Juvenile osteochondrosis of hip and pelvis [See site code at the beginning of this chapter] Excl.: slipped upper femoral epiphysis (nontraumatic) (M93.0) 	`,`	null	`],
	[`	M91.0	`,`	Juvenile osteochondrosis of pelvis Osteochondrosis (juvenile) of: acetabulum iliac crest [Buchanan] ischiopubic synchondrosis [van Neck] symphisis pubis [Pierson] 	`,`	null	`],
	[`	M91.1	`,`	Juvenile osteochondrosis of head of femur [Legg-Calve-Perthes] 	`,`	null	`],
	[`	M91.2	`,`	Coxa plana Hip deformity due to previous juvenile osteochondrosis 	`,`	null	`],
	[`	M91.3	`,`	Pseudocoxalgia 	`,`	null	`],
	[`	M91.8	`,`	Other juvenile osteochondrosis of hip and pelvis Juvenile osteochondrosis after reduction of congenital dislocation of hip 	`,`	null	`],
	[`	M91.9	`,`	Juvenile osteochondrosis of hip and pelvis, unspecified 	`,`	null	`],
	[`	M92	`,`	Other juvenile osteochondrosis 	`,`	null	`],
	[`	M92.0	`,`	Juvenile osteochondrosis of humerus Osteochondrosis (juvenile) of: capitulum of humerus [Panner] head of humerus [Haas] 	`,`	null	`],
	[`	M92.1	`,`	Juvenile osteochondrosis of radius and ulna Osteochondrosis (juvenile) of: lower ulna [Burns] radial head [Brailsford] 	`,`	null	`],
	[`	M92.2	`,`	Juvenile osteochondrosis of hand Osteochondrosis (juvenile) of: carpal lunate [Kienbock] metacarpal heads [Mauclaire] 	`,`	null	`],
	[`	M92.3	`,`	Other juvenile osteochondrosis of upper limb 	`,`	null	`],
	[`	M92.4	`,`	Juvenile osteochondrosis of patella Osteochondrosis (juvenile) of: primary patellar centre [Kohler] secondary patellar centre [Sinding-Larsen] 	`,`	null	`],
	[`	M92.5	`,`	Juvenile osteochondrosis of tibia and fibula Osteochondrosis (juvenile) of: proximal tibia [Blount] tibial tubercle [Osgood-Schlatter] Tibia vara 	`,`	null	`],
	[`	M92.6	`,`	Juvenile osteochondrosis of tarsus Osteochondrosis (juvenile) of: calcaneum [Sever] os tibiale externum [Haglund] talus [Diaz] tarsal navicular [Kohler] 	`,`	null	`],
	[`	M92.7	`,`	Juvenile osteochondrosis of metatarsus Osteochondrosis (juvenile) of: fifth metatarsus [Iselin] second metatarsus [Freiberg] 	`,`	null	`],
	[`	M92.8	`,`	Other specified juvenile osteochondrosis Calcaneal apophysitis 	`,`	null	`],
	[`	M92.9	`,`	Juvenile osteochondrosis, unspecified Apophysitis Epiphysitis Osteochondritis Osteochondrosis specified as juvenile, of unspecified site 	`,`	null	`],
	[`	M93	`,`	Other osteochondropathies Excl.: osteochondrosis of spine (M42.-) 	`,`	null	`],
	[`	M93.0	`,`	Slipped upper femoral epiphysis (nontraumatic) 	`,`	null	`],
	[`	M93.1	`,`	Kienbock disease of adults Adult osteochondrosis of carpal lunate 	`,`	null	`],
	[`	M93.2	`,`	Osteochondritis dissecans 	`,`	null	`],
	[`	M93.8	`,`	Other specified osteochondropathies 	`,`	null	`],
	[`	M93.9	`,`	Osteochondropathy, unspecified Apophysitis Epiphysitis Osteochondritis Osteochondrosis not specified as adult or juvenile, of unspecified site 	`,`	null	`],
	[`	M94	`,`	Other disorders of cartilage [See site code at the beginning of this chapter] 	`,`	null	`],
	[`	M94.0	`,`	Chondrocostal junction syndrome [Tietze] Costochondritis 	`,`	null	`],
	[`	M94.1	`,`	Relapsing polychondritis 	`,`	null	`],
	[`	M94.2	`,`	Chondromalacia Excl.: chondromalacia patellae (M22.4) 	`,`	null	`],
	[`	M94.3	`,`	Chondrolysis 	`,`	null	`],
	[`	M94.8	`,`	Other specified disorders of cartilage 	`,`	null	`],
	[`	M94.9	`,`	Disorder of cartilage, unspecified 	`,`	null	`],
	[`	M95	`,`	Other acquired deformities of musculoskeletal system and connective tissue Excl.: acquired: absence of limbs and organs (Z89-Z90) deformities of limbs (M20-M21) congenital malformations and deformations of the musculoskeletal system (Q65-Q79) deforming dorsopathies (M40-M43) dentofacial anomalies [including malocclusion] (K07.-) postprocedural musculoskeletal disorders (M96.-) 	`,`	null	`],
	[`	M95.0	`,`	Acquired deformity of nose Excl.: deviated nasal septum (J34.2) 	`,`	null	`],
	[`	M95.1	`,`	Cauliflower ear Excl.: other acquired deformities of ear (H61.1) 	`,`	null	`],
	[`	M95.2	`,`	Other acquired deformity of head 	`,`	null	`],
	[`	M95.3	`,`	Acquired deformity of neck 	`,`	null	`],
	[`	M95.4	`,`	Acquired deformity of chest and rib 	`,`	null	`],
	[`	M95.5	`,`	Acquired deformity of pelvis Excl.: maternal care for known or suspected disproportion (O33.-) 	`,`	null	`],
	[`	M95.8	`,`	Other specified acquired deformities of musculoskeletal system 	`,`	null	`],
	[`	M95.9	`,`	Acquired deformity of musculoskeletal system, unspecified 	`,`	null	`],
	[`	M96	`,`	Postprocedural musculoskeletal disorders, not elsewhere classified Excl.: arthropathy following intestinal bypass (M02.0) disorders associated with osteoporosis (M80-M81) presence of functional implants and other devices (Z95-Z97) 	`,`	null	`],
	[`	M96.0	`,`	Pseudarthrosis after fusion or arthrodesis 	`,`	null	`],
	[`	M96.1	`,`	Postlaminectomy syndrome, not elsewhere classified 	`,`	null	`],
	[`	M96.2	`,`	Postradiation kyphosis 	`,`	null	`],
	[`	M96.3	`,`	Postlaminectomy kyphosis 	`,`	null	`],
	[`	M96.4	`,`	Postsurgical lordosis 	`,`	null	`],
	[`	M96.5	`,`	Postradiation scoliosis 	`,`	null	`],
	[`	M96.6	`,`	Fracture of bone following insertion of orthopaedic implant, joint prosthesis, or bone plate Excl.: complication of internal orthopaedic devices, implants or grafts (T84.-) 	`,`	null	`],
	[`	M96.8	`,`	Other postprocedural musculoskeletal disorders Instability of joint secondary to removal of joint prosthesis 	`,`	null	`],
	[`	M96.9	`,`	Postprocedural musculoskeletal disorder, unspecified 	`,`	null	`],
	[`	M99	`,`	Biomechanical lesions, not elsewhere classified Note: This category should not be used if the condition can be classified elsewhere. The following supplementary subclassification to indicate the site of lesions is provided for optional use with appropriate subcategories in M99.-; see also note at the beginning of this chapter. 	`,`	null	`],
	[`	0	`,`	Head region occipitocervical 	`,`	null	`],
	[`	1	`,`	Cervical region cervicothoracic 	`,`	null	`],
	[`	2	`,`	Thoracic region thoracolumbar 	`,`	null	`],
	[`	3	`,`	Lumbar region lumbosacral 	`,`	null	`],
	[`	4	`,`	Sacral region sacrococcygeal sacroiliac 	`,`	null	`],
	[`	5	`,`	Pelvic region hip pubic 	`,`	null	`],
	[`	6	`,`	Lower extremity 	`,`	null	`],
	[`	7	`,`	Upper extremity acromioclavicular sternoclavicular 	`,`	null	`],
	[`	8	`,`	Rib cage costochondral costovertebral sternochondral 	`,`	null	`],
	[`	9	`,`	Abdomen and other 	`,`	null	`],
	[`	M99.0	`,`	Segmental and somatic dysfunction 	`,`	null	`],
	[`	M99.1	`,`	Subluxation complex (vertebral) 	`,`	null	`],
	[`	M99.2	`,`	Subluxation stenosis of neural canal 	`,`	null	`],
	[`	M99.3	`,`	Osseous stenosis of neural canal 	`,`	null	`],
	[`	M99.4	`,`	Connective tissue stenosis of neural canal 	`,`	null	`],
	[`	M99.5	`,`	Intervertebral disc stenosis of neural canal 	`,`	null	`],
	[`	M99.6	`,`	Osseous and subluxation stenosis of intervertebral foramina 	`,`	null	`],
	[`	M99.7	`,`	Connective tissue and disc stenosis of intervertebral foramina 	`,`	null	`],
	[`	M99.8	`,`	Other biomechanical lesions 	`,`	null	`],
	[`	M99.9	`,`	Biomechanical lesion, unspecified 	`,`	null	`],
							
];								
				
							
							
				
	
let CodeRangeM ={
	f0:function(val1=(-1),val2=(0)){
		let Range1 = MCodes.slice(val1,val2);
		Range1.reverse();
		document.documentElement.innerHTML += `<br>Showing M Codes ${Range1.length} items(s)`;

		for(value1 in Range1){
			    document.documentElement.style.cssText += "background-color:tan;";
				document.getElementById('mcodesTR').outerHTML += `<tr><td style="background-color:navy;color:white;width:5%;padding:40px;border:2px solid white;font-weight:900;font-size:40px;text-align:center;">${Range1[value1][0]}</td><td style="background-color:black;color:white;width:90%;padding:20px;border:2px solid white;font-size:30px;">${Range1[value1][1]}</td><td style="background-color:navy;color:white;width:5%;padding:20px;border:2px solid white;font-weight:900;font-size:40px;text-align:center;">${Range1[value1][2]}</td></tr>`;			
		}

	},

};

	






	






