							
							
let NCodes = [							
	[`		`,`		`,`		`],
	[`	0	`,`	Minor glomerular abnormality Minimal change lesion 	`,`	null	`],
	[`	0.1	`,`	Focal and segmental glomerular lesions Focal and segmental: hyalinosis sclerosis Focal glomerulonephritis 	`,`	null	`],
	[`	0.2	`,`	Diffuse membranous glomerulonephritis 	`,`	null	`],
	[`	0.3	`,`	Diffuse mesangial proliferative glomerulonephritis 	`,`	null	`],
	[`	0.4	`,`	Diffuse endocapillary proliferative glomerulonephritis 	`,`	null	`],
	[`	0.5	`,`	Diffuse mesangiocapillary glomerulonephritis Membranoproliferative glomerulonephritis, types 1 and 3, or NOS 	`,`	null	`],
	[`	0.6	`,`	Dense deposit disease Membranoproliferative glomerulonephritis, type 2 	`,`	null	`],
	[`	0.7	`,`	Diffuse crescentic glomerulonephritis Extracapillary glomerulonephritis 	`,`	null	`],
	[`	0.8	`,`	Other Proliferative glomerulonephritis NOS 	`,`	null	`],
	[`	0.9	`,`	Unspecified 	`,`	null	`],
	[`	N00	`,`	Acute nephritic syndrome [See before N00 for subdivisions] Incl.: acute: glomerular disease glomerulonephritis nephritis renal disease NOS Excl.: acute infectious tubulo-interstitial nephritis (N10) nephritic syndrome NOS (N05.-) 	`,`	null	`],
	[`	N01	`,`	Rapidly progressive nephritic syndrome [See before N00 for subdivisions] Incl.: rapidly progressive: glomerular disease glomerulonephritis nephritis Excl.: nephritic syndrome NOS (N05.-) 	`,`	null	`],
	[`	N02	`,`	Recurrent and persistent haematuria [See before N00 for subdivisions] Incl.: haematuria: benign (familial)(of childhood) with morphological lesion specified in .0-.8 before N00.- Excl.: haematuria NOS (R31) 	`,`	null	`],
	[`	N03	`,`	Chronic nephritic syndrome [See before N00 for subdivisions] Incl.: chronic: glomerular disease glomerulonephritis nephritis Excl.: chronic tubulo-interstitial nephritis (N11.-) diffuse sclerosing glomerulonephritis (N18.-) nephritic syndrome NOS (N05.-) 	`,`	null	`],
	[`	N04	`,`	Nephrotic syndrome [See before N00 for subdivisions] Incl.: congenital nephrotic syndrome lipoid nephrosis 	`,`	null	`],
	[`	N05	`,`	Unspecified nephritic syndrome [See before N00 for subdivisions] Incl.: glomerular disease glomerulonephritis nephritis NOS nephropathy NOS and renal disease NOS with morphological lesion specified in .0-.8 before N00.- Excl.: nephropathy NOS with no stated morphological lesion (N28.9) renal disease NOS with no stated morphological lesion (N28.9) tubulo-interstitial nephritis NOS (N12) 	`,`	null	`],
	[`	N06	`,`	Isolated proteinuria with specified morphological lesion [See before N00 for subdivisions] Incl.: proteinuria (isolated)(orthostatic)(persistent) with morphological lesion specified in .0-.8 before N00.- Excl.: proteinuria: NOS (R80) Bence Jones (R80) gestational (O12.1) isolated NOS (R80) orthostatic NOS (N39.2) persistent NOS (N39.1) 	`,`	null	`],
	[`	N07	`,`	Hereditary nephropathy, not elsewhere classified [See before N00 for subdivisions] Excl.: Alport syndrome (Q87.8) hereditary amyloid nephropathy (E85.0) nail patella syndrome (Q87.2) non-neuropathic heredofamilial amyloidosis (E85.0) 	`,`	null	`],
	[`	N08*	`,`	Glomerular disorders in diseases classified elsewhere Incl.: nephropathy in diseases classified elsewhere Excl.: renal tubulo-interstitial disorders in diseases classified elsewhere (N16.-*) 	`,`	null	`],
	[`	N08.0*	`,`	Glomerular disorders in infectious and parasitic diseases classified elsewhere Glomerular disorders in: Plasmodium malariae malaria (B52.0) mumps (B26.8) schistosomiasis [bilharziasis] (B65.-) sepsis (A40-A41) strongyloidiasis (B78.-) syphilis (A52.7) 	`,`	null	`],
	[`	N08.1*	`,`	Glomerular disorders in neoplastic diseases Glomerular disorders in: multiple myeloma (C90.0) Waldenstrom macroglobulinaemia (C88.0) 	`,`	null	`],
	[`	N08.2*	`,`	Glomerular disorders in blood diseases and disorders involving the immune mechanism Glomerular disorders in: cryoglobulinaemia (D89.1) disseminated intravascular coagulation [defibrination syndrome] (D65) haemolytic-uraemic syndrome (D59.3) Henoch(-Schonlein) purpura (D69.0) sickle-cell disorders (D57.-) 	`,`	null	`],
	[`	N08.3*	`,`	Glomerular disorders in diabetes mellitus (E10-E14 with common fourth character .2) N08.4* Glomerular disorders in other endocrine, nutritional and metabolic diseases Glomerular disorders in: amyloidosis (E85.-) Fabry(-Anderson) disease (E75.2) lecithin cholesterol acyltransferase deficiency (E78.6) 	`,`	null	`],
	[`	N08.5*	`,`	Glomerular disorders in systemic connective tissue disorders Glomerular disorders in: Goodpasture syndrome (M31.0) microscopic polyangiitis (M31.7) systemic lupus erythematosus (M32.1) thrombotic thrombocytopenic purpura (M31.1) Wegener granulomatosis (M31.3) 	`,`	null	`],
	[`	N08.8*	`,`	Glomerular disorders in other diseases classified elsewhere Glomerular disorders in subacute bacterial endocarditis (I33.0) 	`,`	null	`],
	[`	N10	`,`	Acute tubulo-interstitial nephritis Incl.: Acute: infectious interstitial nephritis pyelitis pyelonephritis Use additional code (B95-B98), if desired, to identify infectious agent. 	`,`	null	`],
	[`	N11	`,`	Chronic tubulo-interstitial nephritis Incl.: chronic: infectious interstitial nephritis pyelitis pyelonephritis Use additional code (B95-B98), if desired, to identify infectious agent. 	`,`	null	`],
	[`	N11.0	`,`	Nonobstructive reflux-associated chronic pyelonephritis Pyelonephritis (chronic) associated with (vesicoureteral) reflux Excl.: vesicoureteral reflux NOS (N13.7) 	`,`	null	`],
	[`	N11.1	`,`	Chronic obstructive pyelonephritis Pyelonephritis (chronic) associated with: anomaly kinking obstruction stricture of pelviureteric junction pyeloureteric junction ureter Excl.: calculous pyelonephritis (N20.9) obstructive uropathy (N13.-) 	`,`	null	`],
	[`	N11.8	`,`	Other chronic tubulo-interstitial nephritis Nonobstructive chronic pyelonephritis NOS 	`,`	null	`],
	[`	N11.9	`,`	Chronic tubulo-interstitial nephritis, unspecified Chronic: interstitial nephritis NOS pyelitis NOS pyelonephritis NOS 	`,`	null	`],
	[`	N12	`,`	Tubulo-interstitial nephritis, not specified as acute or chronic Incl.: Interstitial nephritis NOS Pyelitis NOS Pyelonephritis NOS Excl.: calculous pyelonephritis (N20.9) 	`,`	null	`],
	[`	N13	`,`	Obstructive and reflux uropathy Excl.: calculus of kidney and ureter without hydronephrosis (N20.-) congenital obstructive defects of renal pelvis and ureter (Q62.0-Q62.3) obstructive pyelonephritis (N11.1) 	`,`	null	`],
	[`	N13.0	`,`	Hydronephrosis with ureteropelvic junction obstruction Excl.: with infection (N13.6) 	`,`	null	`],
	[`	N13.1	`,`	Hydronephrosis with ureteral stricture, not elsewhere classified Excl.: with infection (N13.6) 	`,`	null	`],
	[`	N13.2	`,`	Hydronephrosis with renal and ureteral calculous obstruction Excl.: with infection (N13.6) 	`,`	null	`],
	[`	N13.3	`,`	Other and unspecified hydronephrosis Excl.: with infection (N13.6) 	`,`	null	`],
	[`	N13.4	`,`	Hydroureter Excl.: with infection (N13.6) 	`,`	null	`],
	[`	N13.5	`,`	Kinking and stricture of ureter without hydronephrosis Excl.: with infection (N13.6) 	`,`	null	`],
	[`	N13.6	`,`	Pyonephrosis Conditions in N13.0-N13.5 with infection Obstructive uropathy with infection Use additional code (B95-B98), if desired, to identify infectious agent. 	`,`	null	`],
	[`	N13.7	`,`	Vesicoureteral-reflux-associated uropathy Vesicoureteral reflux: NOS with scarring Excl.: reflux-associated pyelonephritis (N11.0) 	`,`	null	`],
	[`	N13.8	`,`	Other obstructive and reflux uropathy 	`,`	null	`],
	[`	N13.9	`,`	Obstructive and reflux uropathy, unspecified Urinary tract obstruction NOS 	`,`	null	`],
	[`	N14	`,`	Drug- and heavy-metal-induced tubulo-interstitial and tubular conditions Use additional external cause code (Chapter XX), if desired, to identify toxic agent. 	`,`	null	`],
	[`	N14.0	`,`	Analgesic nephropathy 	`,`	null	`],
	[`	N14.1	`,`	Nephropathy induced by other drugs, medicaments and biological substances 	`,`	null	`],
	[`	N14.2	`,`	Nephropathy induced by unspecified drug, medicament or biological substance 	`,`	null	`],
	[`	N14.3	`,`	Nephropathy induced by heavy metals 	`,`	null	`],
	[`	N14.4	`,`	Toxic nephropathy, not elsewhere classified 	`,`	null	`],
	[`	N15	`,`	Other renal tubulo-interstitial diseases 	`,`	null	`],
	[`	N15.0	`,`	Balkan nephropathy Balkan endemic nephropathy 	`,`	null	`],
	[`	N15.1	`,`	Renal and perinephric abscess 	`,`	null	`],
	[`	N15.8	`,`	Other specified renal tubulo-interstitial diseases 	`,`	null	`],
	[`	N15.9	`,`	Renal tubulo-interstitial disease, unspecified Infection of kidney NOS Excl.: urinary tract infection NOS (N39.0) 	`,`	null	`],
	[`	N16*	`,`	Renal tubulo-interstitial disorders in diseases classified elsewhere 	`,`	null	`],
	[`	N16.0*	`,`	Renal tubulo-interstitial disorders in infectious and parasitic diseases classified elsewhere Renal tubulo-interstitial disorders (due to)(in): brucellosis (A23.-) diphtheria (A36.8) salmonella infection (A02.2) sepsis (A40-A41) toxoplasmosis (B58.8) 	`,`	null	`],
	[`	N16.1*	`,`	Renal tubulo-interstitial disorders in neoplastic diseases Renal tubulo-interstitial disorders in: leukaemia (C91-C95) lymphoma (C81-C85, C96.-) multiple myeloma (C90.0) 	`,`	null	`],
	[`	N16.2*	`,`	Renal tubulo-interstitial disorders in blood diseases and disorders involving the immune mechanism Renal tubulo-interstitial disorders in: mixed cryoglobulinaemia (D89.1) sarcoidosis (D86.-) 	`,`	null	`],
	[`	N16.3*	`,`	Renal tubulo-interstitial disorders in metabolic diseases Renal tubulo-interstitial disorders in: cystinosis (E72.0) glycogen storage disease (E74.0) Wilson disease (E83.0) 	`,`	null	`],
	[`	N16.4*	`,`	Renal tubulo-interstitial disorders in systemic connective tissue disorders Renal tubulo-interstitial disorders in: sicca syndrome [Sjogren] (M35.0) systemic lupus erythematosus (M32.1) 	`,`	null	`],
	[`	N16.5*	`,`	Renal tubulo-interstitial disorders in transplant rejection (T86.-) 	`,`	null	`],
	[`	N16.8*	`,`	Renal tubulo-interstitial disorders in other diseases classified elsewhere 	`,`	null	`],
	[`	N17	`,`	Acute renal failure Incl.: acute renal impairment 	`,`	null	`],
	[`	N17.0	`,`	Acute renal failure with tubular necrosis Tubular necrosis: NOS acute renal 	`,`	null	`],
	[`	N17.1	`,`	Acute renal failure with acute cortical necrosis Cortical necrosis: NOS acute renal 	`,`	null	`],
	[`	N17.2	`,`	Acute renal failure with medullary necrosis Medullary [papillary] necrosis: NOS acute renal 	`,`	null	`],
	[`	N17.8	`,`	Other acute renal failure 	`,`	null	`],
	[`	N17.9	`,`	Acute renal failure, unspecified 	`,`	null	`],
	[`	N18	`,`	Chronic kidney disease Use additional code, if desired, to identify underlying disease. Use additional code, if desired, to identify presence of hypertension. 	`,`	null	`],
	[`	N18.1	`,`	Chronic kidney disease, stage 1 Kidney damage with normal or increased GFR (= 90 mL/min) 	`,`	null	`],
	[`	N18.2	`,`	Chronic kidney disease, stage 2 Kidney damage with mild decreased GFR (60-89 mL/min) 	`,`	null	`],
	[`	N18.3	`,`	Chronic kidney disease, stage 3 Kidney damage with moderately decreased GFR (30-59 mL/min) 	`,`	null	`],
	[`	N18.4	`,`	Chronic kidney disease, stage 4 Kidney damage with severely decreased GFR (15-29 mL/min) 	`,`	null	`],
	[`	N18.5	`,`	Chronic kidney disease, stage 5 Chronic uraemia End stage kidney disease: in allograft failure NOS on dialysis without dialysis or transplant Renal retinitis (H32.8*) Uraemic: apoplexia (I68.8*) dementia (F02.8*) neuropathy (G63.8*) paralysis (G99.8*) pericarditis (I32.8*) 	`,`	null	`],
	[`	N18.9	`,`	Chronic kidney disease, unspecified 	`,`	null	`],
	[`	N19	`,`	Unspecified kidney failure Incl.: Renal insufficiency NOS Uraemia NOS Excl.: kidney failure due to hypertension (I12.0) uraemia of newborn (P96.0) 	`,`	null	`],
	[`	N20	`,`	Calculus of kidney and ureter Incl.: calculous pyelonephritis Excl.: with hydronephrosis (N13.2) 	`,`	null	`],
	[`	N20.0	`,`	Calculus of kidney Nephrolithiasis NOS Renal calculus or stone Staghorn calculus Stone in kidney 	`,`	null	`],
	[`	N20.1	`,`	Calculus of ureter Ureteric stone 	`,`	null	`],
	[`	N20.2	`,`	Calculus of kidney with calculus of ureter 	`,`	null	`],
	[`	N20.9	`,`	Urinary calculus, unspecified 	`,`	null	`],
	[`	N21	`,`	Calculus of lower urinary tract Incl.: with cystitis and urethritis 	`,`	null	`],
	[`	N21.0	`,`	Calculus in bladder Calculus in diverticulum of bladder Urinary bladder stone Excl.: staghorn calculus (N20.0) 	`,`	null	`],
	[`	N21.1	`,`	Calculus in urethra 	`,`	null	`],
	[`	N21.8	`,`	Other lower urinary tract calculus 	`,`	null	`],
	[`	N21.9	`,`	Calculus of lower urinary tract, unspecified 	`,`	null	`],
	[`	N22*	`,`	Calculus of urinary tract in diseases classified elsewhere 	`,`	null	`],
	[`	N22.0*	`,`	Urinary calculus in schistosomiasis [bilharziasis] (B65.-) 	`,`	null	`],
	[`	N22.8*	`,`	Calculus of urinary tract in other diseases classified elsewhere 	`,`	null	`],
	[`	N23	`,`	Unspecified renal colic 	`,`	null	`],
	[`	N25	`,`	Disorders resulting from impaired renal tubular function Excl.: metabolic disorders classifiable to E70-E90 	`,`	null	`],
	[`	N25.0	`,`	Renal osteodystrophy Azotaemic osteodystrophy Phosphate-losing tubular disorders Renal: rickets short stature 	`,`	null	`],
	[`	N25.1	`,`	Nephrogenic diabetes insipidus 	`,`	null	`],
	[`	N25.8	`,`	Other disorders resulting from impaired renal tubular function Lightwood-Albright syndrome Renal tubular acidosis NOS Secondary hyperparathyroidism of renal origin 	`,`	null	`],
	[`	N25.9	`,`	Disorder resulting from impaired renal tubular function, unspecified 	`,`	null	`],
	[`	N26	`,`	Unspecified contracted kidney Incl.: Atrophy of kidney (terminal) Renal sclerosis NOS Excl.: contracted kidney due to hypertension (I12.-) diffuse sclerosing glomerulonephritis (N18.-) hypertensive nephrosclerosis (arteriolar)(arteriosclerotic) (I12.-) small kidney of unknown cause (N27.-) 	`,`	null	`],
	[`	N27	`,`	Small kidney of unknown cause 	`,`	null	`],
	[`	N27.0	`,`	Small kidney, unilateral 	`,`	null	`],
	[`	N27.1	`,`	Small kidney, bilateral 	`,`	null	`],
	[`	N27.9	`,`	Small kidney, unspecified 	`,`	null	`],
	[`	N28	`,`	Other disorders of kidney and ureter, not elsewhere classified Excl.: hydroureter (N13.4) renal disease: acute NOS (N00.9) chronic NOS (N03.9) ureteric kinking and stricture: with hydronephrosis (N13.1) without hydronephrosis (N13.5) 	`,`	null	`],
	[`	N28.0	`,`	Ischaemia and infarction of kidney Renal artery: embolism obstruction occlusion thrombosis Renal infarct Excl.: Goldblatt kidney (I70.1) renal artery (extrarenal part): atherosclerosis (I70.1) congenital stenosis (Q27.1) 	`,`	null	`],
	[`	N28.1	`,`	Cyst of kidney, acquired Cyst (multiple)(solitary) of kidney, acquired Excl.: cystic kidney disease (congenital) (Q61.-) 	`,`	null	`],
	[`	N28.8	`,`	Other specified disorders of kidney and ureter Hypertrophy of kidney Megaloureter Nephroptosis Pyelitis Pyeloureteritis Ureteritis cystica Ureterocele 	`,`	null	`],
	[`	N28.9	`,`	Disorder of kidney and ureter, unspecified Nephropathy NOS Renal disease NOS Excl.: nephropathy NOS and renal disease NOS with morphological lesion specified in .0-.8 before N00.- (N05.-) 	`,`	null	`],
	[`	N29*	`,`	Other disorders of kidney and ureter in diseases classified elsewhere 	`,`	null	`],
	[`	N29.0*	`,`	Late syphilis of kidney (A52.7) 	`,`	null	`],
	[`	N29.1*	`,`	Other disorders of kidney and ureter in infectious and parasitic diseases classified elsewhere Disorders of kidney and ureter in: schistosomiasis [bilharziasis] (B65.-) tuberculosis (A18.1) 	`,`	null	`],
	[`	N29.8*	`,`	Other disorders of kidney and ureter in other diseases classified elsewhere Cystine storage disease (E72.0) 	`,`	null	`],
	[`	N30	`,`	Cystitis Use additional code, if desired, to identify infectious agent (B95-B98) or responsible external agent (Chapter XX). Excl.: prostatocystitis (N41.3) 	`,`	null	`],
	[`	N30.0	`,`	Acute cystitis Excl.: irradiation cystitis (N30.4) trigonitis (N30.3) 	`,`	null	`],
	[`	N30.1	`,`	Interstitial cystitis (chronic) 	`,`	null	`],
	[`	N30.2	`,`	Other chronic cystitis 	`,`	null	`],
	[`	N30.3	`,`	Trigonitis Urethrotrigonitis 	`,`	null	`],
	[`	N30.4	`,`	Irradiation cystitis 	`,`	null	`],
	[`	N30.8	`,`	Other cystitis Abscess of bladder 	`,`	null	`],
	[`	N30.9	`,`	Cystitis, unspecified 	`,`	null	`],
	[`	N31	`,`	Neuromuscular dysfunction of bladder, not elsewhere classified Excl.: cord bladder NOS (G95.8) due to spinal cord lesion (G95.8) neurogenic bladder due to cauda equina syndrome (G83.4) urinary incontinence: NOS (R32) specified (N39.3-N39.4) 	`,`	null	`],
	[`	N31.0	`,`	Uninhibited neuropathic bladder, not elsewhere classified 	`,`	null	`],
	[`	N31.1	`,`	Reflex neuropathic bladder, not elsewhere classified 	`,`	null	`],
	[`	N31.2	`,`	Flaccid neuropathic bladder, not elsewhere classified Neuropathic bladder: atonic (motor)(sensory) autonomous nonreflex 	`,`	null	`],
	[`	N31.8	`,`	Other neuromuscular dysfunction of bladder 	`,`	null	`],
	[`	N31.9	`,`	Neuromuscular dysfunction of bladder, unspecified Neurogenic bladder dysfunction NOS 	`,`	null	`],
	[`	N32	`,`	Other disorders of bladder Excl.: calculus in bladder (N21.0) cystocele (N81.1) hernia or prolapse of bladder, female (N81.1) 	`,`	null	`],
	[`	N32.0	`,`	Bladder-neck obstruction Bladder-neck stenosis (acquired) 	`,`	null	`],
	[`	N32.1	`,`	Vesicointestinal fistula Vesicorectal fistula 	`,`	null	`],
	[`	N32.2	`,`	Vesical fistula, not elsewhere classified Excl.: fistula between bladder and female genital tract (N82.0-N82.1) 	`,`	null	`],
	[`	N32.3	`,`	Diverticulum of bladder Diverticulitis of bladder Excl.: calculus in diverticulum of bladder (N21.0) 	`,`	null	`],
	[`	N32.4	`,`	Rupture of bladder, nontraumatic 	`,`	null	`],
	[`	N32.8	`,`	Other specified disorders of bladder Bladder: calcified contracted overactive 	`,`	null	`],
	[`	N32.9	`,`	Bladder disorder, unspecified 	`,`	null	`],
	[`	N33*	`,`	Bladder disorders in diseases classified elsewhere 	`,`	null	`],
	[`	N33.0*	`,`	Tuberculous cystitis (A18.1) 	`,`	null	`],
	[`	N33.8*	`,`	Bladder disorders in other diseases classified elsewhere Bladder disorder in schistosomiasis [bilharziasis] (B65.-) 	`,`	null	`],
	[`	N34	`,`	Urethritis and urethral syndrome Use additional code (B95-B98), if desired, to identify infectious agent. Excl.: Reiter disease (M02.3) urethritis in diseases with a predominantly sexual mode of transmission (A50-A64) urethrotrigonitis (N30.3) 	`,`	null	`],
	[`	N34.0	`,`	Urethral abscess Abscess (of): Cowper gland Littre gland periurethral urethral (gland) Excl.: urethral caruncle (N36.2) 	`,`	null	`],
	[`	N34.1	`,`	Nonspecific urethritis Urethritis: nongonococcal nonvenereal 	`,`	null	`],
	[`	N34.2	`,`	Other urethritis Meatitis, urethral Ulcer of urethra (meatus) Urethritis: NOS postmenopausal 	`,`	null	`],
	[`	N34.3	`,`	Urethral syndrome, unspecified 	`,`	null	`],
	[`	N35	`,`	Urethral stricture Excl.: postprocedural urethral stricture (N99.1) 	`,`	null	`],
	[`	N35.0	`,`	Post-traumatic urethral stricture Stricture of urethra as a sequela of: childbirth injury 	`,`	null	`],
	[`	N35.1	`,`	Postinfective urethral stricture, not elsewhere classified 	`,`	null	`],
	[`	N35.8	`,`	Other urethral stricture 	`,`	null	`],
	[`	N35.9	`,`	Urethral stricture, unspecified Pinhole meatus NOS 	`,`	null	`],
	[`	N36	`,`	Other disorders of urethra 	`,`	null	`],
	[`	N36.0	`,`	Urethral fistula False urethral passage Fistula: urethroperineal urethrorectal urinary NOS Excl.: fistula: urethroscrotal (N50.8) urethrovaginal (N82.1) 	`,`	null	`],
	[`	N36.1	`,`	Urethral diverticulum 	`,`	null	`],
	[`	N36.2	`,`	Urethral caruncle 	`,`	null	`],
	[`	N36.3	`,`	Prolapsed urethral mucosa Prolapse of urethra Urethrocele, male Excl.: urethrocele: congenital (Q64.7) female (N81.0) 	`,`	null	`],
	[`	N36.8	`,`	Other specified disorders of urethra 	`,`	null	`],
	[`	N36.9	`,`	Urethral disorder, unspecified 	`,`	null	`],
	[`	N37*	`,`	Urethral disorders in diseases classified elsewhere 	`,`	null	`],
	[`	N37.0*	`,`	Urethritis in diseases classified elsewhere Candidal urethritis (B37.4) 	`,`	null	`],
	[`	N37.8*	`,`	Other urethral disorders in diseases classified elsewhere 	`,`	null	`],
	[`	N39	`,`	Other disorders of urinary system Excl.: haematuria: NOS (R31) recurrent and persistent (N02.-) with specified morphological lesion (N02.-) proteinuria NOS (R80) 	`,`	null	`],
	[`	N39.0	`,`	Urinary tract infection, site not specified Use additional code (B95-B98), if desired, to identify infectious agent. 	`,`	null	`],
	[`	N39.1	`,`	Persistent proteinuria, unspecified Excl.: complicating pregnancy, childbirth and the puerperium (O11-O15) with specified morphological lesion (N06.-) 	`,`	null	`],
	[`	N39.2	`,`	Orthostatic proteinuria, unspecified Excl.: with specified morphological lesion (N06.-) 	`,`	null	`],
	[`	N39.3	`,`	Stress incontinence Use additional code (N32.8), if desired, to identify overactive bladder or detrusor muscle hyperactivity. 	`,`	null	`],
	[`	N39.4	`,`	Other specified urinary incontinence Overflow Reflex Urge incontinence Use additional code (N32.8), if desired, to identify overactive bladder or detrusor muscle hyperactivity. Excl.: enuresis NOS (R32) urinary incontinence (of): NOS (R32) nonorganic origin (F98.0) 	`,`	null	`],
	[`	N39.8	`,`	Other specified disorders of urinary system 	`,`	null	`],
	[`	N39.9	`,`	Disorder of urinary system, unspecified 	`,`	null	`],
	[`	N40	`,`	Hyperplasia of prostate Incl.: Adenofibromatous hypertrophy Enlargement (benign) Hypertrophy (benign) of prostate Median bar (prostate) Prostatic obstruction NOS Excl.: benign neoplasms of prostate (D29.1) 	`,`	null	`],
	[`	N41	`,`	Inflammatory diseases of prostate Use additional code (B95-B98), if desired, to identify infectious agent. 	`,`	null	`],
	[`	N41.0	`,`	Acute prostatitis 	`,`	null	`],
	[`	N41.1	`,`	Chronic prostatitis 	`,`	null	`],
	[`	N41.2	`,`	Abscess of prostate 	`,`	null	`],
	[`	N41.3	`,`	Prostatocystitis 	`,`	null	`],
	[`	N41.8	`,`	Other inflammatory diseases of prostate 	`,`	null	`],
	[`	N41.9	`,`	Inflammatory disease of prostate, unspecified Prostatitis NOS 	`,`	null	`],
	[`	N42	`,`	Other disorders of prostate 	`,`	null	`],
	[`	N42.0	`,`	Calculus of prostate Prostatic stone 	`,`	null	`],
	[`	N42.1	`,`	Congestion and haemorrhage of prostate 	`,`	null	`],
	[`	N42.2	`,`	Atrophy of prostate 	`,`	null	`],
	[`	N42.3	`,`	Dysplasia of prostate Low grade dysplasia Excl.: high grade dysplasia of prostate (D07.5) 	`,`	null	`],
	[`	N42.8	`,`	Other specified disorders of prostate 	`,`	null	`],
	[`	N42.9	`,`	Disorder of prostate, unspecified 	`,`	null	`],
	[`	N43	`,`	Hydrocele and spermatocele Incl.: hydrocele of spermatic cord, testis or tunica vaginalis Excl.: congenital hydrocele (P83.5) 	`,`	null	`],
	[`	N43.0	`,`	Encysted hydrocele 	`,`	null	`],
	[`	N43.1	`,`	Infected hydrocele Use additional code (B95-B98), if desired, to identify infectious agent. 	`,`	null	`],
	[`	N43.2	`,`	Other hydrocele 	`,`	null	`],
	[`	N43.3	`,`	Hydrocele, unspecified 	`,`	null	`],
	[`	N43.4	`,`	Spermatocele 	`,`	null	`],
	[`	N44	`,`	Torsion of testis Incl.: Torsion of: epididymis spermatic cord testicle 	`,`	null	`],
	[`	N45	`,`	Orchitis and epididymitis Use additional code (B95-B98), if desired, to identify infectious agent. 	`,`	null	`],
	[`	N45.0	`,`	Orchitis, epididymitis and epididymo-orchitis with abscess Abscess of epididymis or testis 	`,`	null	`],
	[`	N45.9	`,`	Orchitis, epididymitis and epididymo-orchitis without abscess Epididymitis NOS Orchitis NOS 	`,`	null	`],
	[`	N46	`,`	Male infertility Incl.: Azoospermia NOS Oligospermia NOS 	`,`	null	`],
	[`	N47	`,`	Redundant prepuce, phimosis and paraphimosis Incl.: Adherent prepuce Tight foreskin 	`,`	null	`],
	[`	N48	`,`	Other disorders of penis 	`,`	null	`],
	[`	N48.0	`,`	Leukoplakia of penis Balanitis xerotica obliterans Kraurosis of penis Excl.: carcinoma in situ of penis (D07.4) 	`,`	null	`],
	[`	N48.1	`,`	Balanoposthitis Balanitis Use additional code (B95-B98), if desired, to identify infectious agent. 	`,`	null	`],
	[`	N48.2	`,`	Other inflammatory disorders of penis Abscess Boil Carbuncle Cellulitis of corpus cavernosum and penis Cavernitis (penis) Use additional code (B95-B98), if desired, to identify infectious agent. 	`,`	null	`],
	[`	N48.3	`,`	Priapism Painful erection 	`,`	null	`],
	[`	N48.4	`,`	Impotence of organic origin Use additional code, if desired, to identify cause. Excl.: psychogenic impotence (F52.2) 	`,`	null	`],
	[`	N48.5	`,`	Ulcer of penis 	`,`	null	`],
	[`	N48.6	`,`	Induratio penis plastica Peyronie disease Plastic induration of penis 	`,`	null	`],
	[`	N48.8	`,`	Other specified disorders of penis Atrophy Hypertrophy Thrombosis of corpus cavernosum and penis 	`,`	null	`],
	[`	N48.9	`,`	Disorder of penis, unspecified 	`,`	null	`],
	[`	N49	`,`	Inflammatory disorders of male genital organs, not elsewhere classified Use additional code (B95-B98), if desired, to identify infectious agent. Excl.: inflammation of penis (N48.1-N48.2) orchitis and epididymitis (N45.-) 	`,`	null	`],
	[`	N49.0	`,`	Inflammatory disorders of seminal vesicle Vesiculitis NOS 	`,`	null	`],
	[`	N49.1	`,`	Inflammatory disorders of spermatic cord, tunica vaginalis and vas deferens Vasitis 	`,`	null	`],
	[`	N49.2	`,`	Inflammatory disorders of scrotum 	`,`	null	`],
	[`	N49.8	`,`	Inflammatory disorders of other specified male genital organs Inflammation of multiple sites in male genital organs 	`,`	null	`],
	[`	N49.9	`,`	Inflammatory disorder of unspecified male genital organ Abscess Boil Carbuncle Cellulitis of unspecified male genital organ 	`,`	null	`],
	[`	N50	`,`	Other disorders of male genital organs Excl.: torsion of testis (N44) 	`,`	null	`],
	[`	N50.0	`,`	Atrophy of testis 	`,`	null	`],
	[`	N50.1	`,`	Vascular disorders of male genital organs Haematocele NOS Haemorrhage Thrombosis of male genital organs 	`,`	null	`],
	[`	N50.8	`,`	Other specified disorders of male genital organs Atrophy Hypertrophy Oedema Ulcer of scrotum, seminal vesicle, spermatic cord, testis [except atrophy], tunica vaginalis and vas deferens Chylocele, tunica vaginalis (nonfilarial) NOS Fistula, urethroscrotal Stricture of: spermatic cord tunica vaginalis vas deferens 	`,`	null	`],
	[`	N50.9	`,`	Disorder of male genital organs, unspecified 	`,`	null	`],
	[`	N51*	`,`	Disorders of male genital organs in diseases classified elsewhere 	`,`	null	`],
	[`	N51.0*	`,`	Disorders of prostate in diseases classified elsewhere Prostatitis: gonococcal (A54.2) trichomonal (A59.0) tuberculous (A18.1) 	`,`	null	`],
	[`	N51.1*	`,`	Disorders of testis and epididymis in diseases classified elsewhere Chlamydial: epididymitis (A56.1) orchitis (A56.1) Gonococcal: epididymitis (A54.2) orchitis (A54.2) Mumps orchitis (B26.0) Tuberculosis of: epididymis (A18.1) testis (A18.1) 	`,`	null	`],
	[`	N51.2*	`,`	Balanitis in diseases classified elsewhere Balanitis: amoebic (A06.8) candidal (B37.4) 	`,`	null	`],
	[`	N51.8*	`,`	Other disorders of male genital organs in diseases classified elsewhere Filarial chylocele, tunica vaginalis (B74.-) Herpesviral [herpes simplex] infection of male genital tract (A60.0) Tuberculosis of seminal vesicle (A18.1) 	`,`	null	`],
	[`	N60	`,`	Benign mammary dysplasia Incl.: fibrocystic mastopathy 	`,`	null	`],
	[`	N60.0	`,`	Solitary cyst of breast Cyst of breast 	`,`	null	`],
	[`	N60.1	`,`	Diffuse cystic mastopathy Cystic breast Excl.: with epithelial proliferation (N60.3) 	`,`	null	`],
	[`	N60.2	`,`	Fibroadenosis of breast Excl.: fibroadenoma of breast (D24) 	`,`	null	`],
	[`	N60.3	`,`	Fibrosclerosis of breast Cystic mastopathy with epithelial proliferation 	`,`	null	`],
	[`	N60.4	`,`	Mammary duct ectasia 	`,`	null	`],
	[`	N60.8	`,`	Other benign mammary dysplasias 	`,`	null	`],
	[`	N60.9	`,`	Benign mammary dysplasia, unspecified 	`,`	null	`],
	[`	N61	`,`	Inflammatory disorders of breast Incl.: Abscess (acute)(chronic)(nonpuerperal) of: areola breast Carbuncle of breast Mastitis (acute)(subacute)(nonpuerperal): NOS infective Excl.: neonatal infective mastitis (P39.0) 	`,`	null	`],
	[`	N62	`,`	Hypertrophy of breast Incl.: Gynaecomastia Hypertrophy of breast: NOS massive pubertal 	`,`	null	`],
	[`	N63	`,`	Unspecified lump in breast Incl.: Nodule(s) NOS in breast 	`,`	null	`],
	[`	N64	`,`	Other disorders of breast 	`,`	null	`],
	[`	N64.0	`,`	Fissure and fistula of nipple 	`,`	null	`],
	[`	N64.1	`,`	Fat necrosis of breast Fat necrosis (segmental) of breast 	`,`	null	`],
	[`	N64.2	`,`	Atrophy of breast 	`,`	null	`],
	[`	N64.3	`,`	Galactorrhoea not associated with childbirth 	`,`	null	`],
	[`	N64.4	`,`	Mastodynia 	`,`	null	`],
	[`	N64.5	`,`	Other signs and symptoms in breast Induration of breast Nipple discharge Retraction of nipple 	`,`	null	`],
	[`	N64.8	`,`	Other specified disorders of breast Galactocele Subinvolution of breast (postlactational) 	`,`	null	`],
	[`	N64.9	`,`	Disorder of breast, unspecified 	`,`	null	`],
	[`	N70	`,`	Salpingitis and oophoritis Incl.: abscess (of): fallopian tube ovary tubo-ovarian pyosalpinx salpingo-oophoritis tubo-ovarian inflammatory disease Use additional code (B95-B98), if desired, to identify infectious agent. 	`,`	null	`],
	[`	N70.0	`,`	Acute salpingitis and oophoritis 	`,`	null	`],
	[`	N70.1	`,`	Chronic salpingitis and oophoritis Hydrosalpinx 	`,`	null	`],
	[`	N70.9	`,`	Salpingitis and oophoritis, unspecified 	`,`	null	`],
	[`	N71	`,`	Inflammatory disease of uterus, except cervix Incl.: endo(myo)metritis metritis myometritis pyometra uterine abscess Use additional code (B95-B98), if desired, to identify infectious agent. 	`,`	null	`],
	[`	N71.0	`,`	Acute inflammatory disease of uterus 	`,`	null	`],
	[`	N71.1	`,`	Chronic inflammatory disease of uterus 	`,`	null	`],
	[`	N71.9	`,`	Inflammatory disease of uterus, unspecified 	`,`	null	`],
	[`	N72	`,`	Inflammatory disease of cervix uteri Incl.: Cervicitis Endocervicitis Exocervicitis with or without erosion or ectropion Use additional code (B95-B98), if desired, to identify infectious agent. Excl.: erosion and ectropion of cervix without cervicitis (N86) 	`,`	null	`],
	[`	N73	`,`	Other female pelvic inflammatory diseases Use additional code (B95-B98), if desired, to identify infectious agent. 	`,`	null	`],
	[`	N73.0	`,`	Acute parametritis and pelvic cellulitis Abscess of: broad ligament parametrium Pelvic cellulitis, female specified as acute 	`,`	null	`],
	[`	N73.1	`,`	Chronic parametritis and pelvic cellulitis Any condition in N73.0 specified as chronic 	`,`	null	`],
	[`	N73.2	`,`	Unspecified parametritis and pelvic cellulitis Any condition in N73.0 unspecified whether acute or chronic 	`,`	null	`],
	[`	N73.3	`,`	Female acute pelvic peritonitis 	`,`	null	`],
	[`	N73.4	`,`	Female chronic pelvic peritonitis 	`,`	null	`],
	[`	N73.5	`,`	Female pelvic peritonitis, unspecified 	`,`	null	`],
	[`	N73.6	`,`	Female pelvic peritoneal adhesions Excl.: postprocedural pelvic peritoneal adhesions (N99.4) 	`,`	null	`],
	[`	N73.8	`,`	Other specified female pelvic inflammatory diseases 	`,`	null	`],
	[`	N73.9	`,`	Female pelvic inflammatory disease, unspecified Female pelvic infection or inflammation NOS 	`,`	null	`],
	[`	N74*	`,`	Female pelvic inflammatory disorders in diseases classified elsewhere 	`,`	null	`],
	[`	N74.0*	`,`	Tuberculous infection of cervix uteri (A18.1) 	`,`	null	`],
	[`	N74.1*	`,`	Female tuberculous pelvic inflammatory disease (A18.1) Tuberculous endometritis 	`,`	null	`],
	[`	N74.2*	`,`	Female syphilitic pelvic inflammatory disease (A51.4, A52.7) 	`,`	null	`],
	[`	N74.3*	`,`	Female gonococcal pelvic inflammatory disease (A54.2) 	`,`	null	`],
	[`	N74.4*	`,`	Female chlamydial pelvic inflammatory disease (A56.1) 	`,`	null	`],
	[`	N74.8*	`,`	Female pelvic inflammatory disorders in other diseases classified elsewhere 	`,`	null	`],
	[`	N75	`,`	Diseases of Bartholin gland 	`,`	null	`],
	[`	N75.0	`,`	Cyst of Bartholin gland 	`,`	null	`],
	[`	N75.1	`,`	Abscess of Bartholin gland 	`,`	null	`],
	[`	N75.8	`,`	Other diseases of Bartholin gland Bartholinitis 	`,`	null	`],
	[`	N75.9	`,`	Disease of Bartholin gland, unspecified 	`,`	null	`],
	[`	N76	`,`	Other inflammation of vagina and vulva Use additional code (B95-B98), if desired, to identify infectious agent. Excl.: senile (atrophic) vaginitis (N95.2) 	`,`	null	`],
	[`	N76.0	`,`	Acute vaginitis Vaginitis NOS Vulvovaginitis: NOS acute 	`,`	null	`],
	[`	N76.1	`,`	Subacute and chronic vaginitis Vulvovaginitis: chronic subacute 	`,`	null	`],
	[`	N76.2	`,`	Acute vulvitis Vulvitis NOS 	`,`	null	`],
	[`	N76.3	`,`	Subacute and chronic vulvitis 	`,`	null	`],
	[`	N76.4	`,`	Abscess of vulva Furuncle of vulva 	`,`	null	`],
	[`	N76.5	`,`	Ulceration of vagina 	`,`	null	`],
	[`	N76.6	`,`	Ulceration of vulva 	`,`	null	`],
	[`	N76.8	`,`	Other specified inflammation of vagina and vulva 	`,`	null	`],
	[`	N77*	`,`	Vulvovaginal ulceration and inflammation in diseases classified elsewhere 	`,`	null	`],
	[`	N77.0*	`,`	Ulceration of vulva in infectious and parasitic diseases classified elsewhere Ulceration of vulva in: herpesviral [herpes simplex] infection (A60.0) tuberculosis (A18.1) 	`,`	null	`],
	[`	N77.1*	`,`	Vaginitis, vulvitis and vulvovaginitis in infectious and parasitic diseases classified elsewhere Vaginitis, vulvitis and vulvovaginitis in: candidiasis (B37.3) herpesviral [herpes simplex] infection (A60.0) pinworm infection (B80) 	`,`	null	`],
	[`	N77.8*	`,`	Vulvovaginal ulceration and inflammation in other diseases classified elsewhere Ulceration of vulva in Behcet disease (M35.2) 	`,`	null	`],
	[`	N99	`,`	Postprocedural disorders of genitourinary system, not elsewhere classified Excl.: irradiation cystitis (N30.4) postoophorectomy osteoporosis (M81.1) postoophorectomy osteoporosis with pathological fracture (M80.1) states associated with artificial menopause (N95.3) 	`,`	null	`],
	[`	N99.0	`,`	Postprocedural renal failure 	`,`	null	`],
	[`	N99.1	`,`	Postprocedural urethral stricture Postcatheterization urethral stricture 	`,`	null	`],
	[`	N99.2	`,`	Postoperative adhesions of vagina 	`,`	null	`],
	[`	N99.3	`,`	Prolapse of vaginal vault after hysterectomy 	`,`	null	`],
	[`	N99.4	`,`	Postprocedural pelvic peritoneal adhesions 	`,`	null	`],
	[`	N99.5	`,`	Malfunction of external stoma of urinary tract 	`,`	null	`],
	[`	N99.8	`,`	Other postprocedural disorders of genitourinary system Residual ovary syndrome 	`,`	null	`],
	[`	N99.9	`,`	Postprocedural disorder of genitourinary system, unspecified 	`,`	null	`],
							
];							
					
							
							
				
	
let CodeRangeN ={
	f0:function(val1=(-1),val2=(0)){
		let Range1 = NCodes.slice(val1,val2);
		Range1.reverse();
		document.documentElement.innerHTML += `<br>Showing N Codes ${Range1.length} items(s)`;

		for(value2 in Range1){
			    document.documentElement.style.cssText += "background-color:tan;";
				document.getElementById('ncodesTR').outerHTML += `<tr><td style="background-color:navy;color:white;width:5%;padding:40px;border:2px solid white;font-weight:900;font-size:40px;text-align:center;">${Range1[value2][0]}</td><td style="background-color:black;color:white;width:90%;padding:20px;border:2px solid white;font-size:30px;">${Range1[value2][1]}</td><td style="background-color:navy;color:white;width:5%;padding:20px;border:2px solid white;font-weight:900;font-size:40px;text-align:center;">${Range1[value2][2]}</td></tr>`;			
		}

	},

};

	






	






