let OCodes = [							
	[`		`,`		`,`		`],
	[`	0	`,`	Incomplete, complicated by genital tract and pelvic infection With conditions in O08.0 	`,`	null	`],
	[`	0.1	`,`	Incomplete, complicated by delayed or excessive haemorrhage With conditions in O08.1 	`,`	null	`],
	[`	0.2	`,`	Incomplete, complicated by embolism With conditions in O08.2 	`,`	null	`],
	[`	0.3	`,`	Incomplete, with other and unspecified complications With conditions in O08.3-O08.9 	`,`	null	`],
	[`	0.4	`,`	Incomplete, without complication 	`,`	null	`],
	[`	0.5	`,`	Complete or unspecified, complicated by genital tract and pelvic infection With conditions in O08.0 	`,`	null	`],
	[`	0.6	`,`	Complete or unspecified, complicated by delayed or excessive haemorrhage With conditions in O08.1 	`,`	null	`],
	[`	0.7	`,`	Complete or unspecified, complicated by embolism With conditions in O08.2 	`,`	null	`],
	[`	0.8	`,`	Complete or unspecified, with other and unspecified complications With conditions in O08.3-O08.9 	`,`	null	`],
	[`	0.9	`,`	Complete or unspecified, without complication 	`,`	null	`],
	[`	O00	`,`	Ectopic pregnancy Incl.: ruptured ectopic pregnancy Use additional code from category O08.-, if desired, to identify any associated complication. 	`,`	null	`],
	[`	O00.0	`,`	Abdominal pregnancy Excl.: delivery of viable fetus in abdominal pregnancy (O83.3) maternal care for viable fetus in abdominal pregnancy (O36.7) 	`,`	null	`],
	[`	O00.1	`,`	Tubal pregnancy Fallopian pregnancy Rupture of (fallopian) tube due to pregnancy Tubal abortion 	`,`	null	`],
	[`	O00.2	`,`	Ovarian pregnancy 	`,`	null	`],
	[`	O00.8	`,`	Other ectopic pregnancy Pregnancy: cervical cornual intraligamentous mural 	`,`	null	`],
	[`	O00.9	`,`	Ectopic pregnancy, unspecified 	`,`	null	`],
	[`	O01	`,`	Hydatidiform mole Use additional code from category O08.-, if desired, to identify any associated complication. Excl.: malignant hydatidiform mole (D39.2) 	`,`	null	`],
	[`	O01.0	`,`	Classical hydatidiform mole Complete hydatidiform mole 	`,`	null	`],
	[`	O01.1	`,`	Incomplete and partial hydatidiform mole 	`,`	null	`],
	[`	O01.9	`,`	Hydatidiform mole, unspecified Trophoblastic disease NOS Vesicular mole NOS 	`,`	null	`],
	[`	O02	`,`	Other abnormal products of conception Use additional code from category O08.-, if desired, to identify any associated complication. Excl.: papyraceous fetus (O31.0) 	`,`	null	`],
	[`	O02.0	`,`	Blighted ovum and nonhydatidiform mole Mole: carneous fleshy intrauterine NOS Pathological ovum 	`,`	null	`],
	[`	O02.1	`,`	Missed abortion Early fetal death with retention of dead fetus Excl.: missed abortion with: blighted ovum (O02.0) mole: hydatidiform (O01.-) nonhydatidiform (O02.0) 	`,`	null	`],
	[`	O02.8	`,`	Other specified abnormal products of conception Excl.: those with: blighted ovum (O02.0) mole: hydatidiform (O01.-) nonhydatidiform (O02.0) 	`,`	null	`],
	[`	O02.9	`,`	Abnormal product of conception, unspecified 	`,`	null	`],
	[`	O03	`,`	Spontaneous abortion [See before O03 for subdivisions] Incl.: miscarriage 	`,`	null	`],
	[`	O04	`,`	Medical abortion [See before O03 for subdivisions] Incl.: termination of pregnancy: legal therapeutic therapeutic abortion 	`,`	null	`],
	[`	O05	`,`	Other abortion [See before O03 for subdivisions] 	`,`	null	`],
	[`	O06	`,`	Unspecified abortion [See before O03 for subdivisions] Incl.: induced abortion NOS 	`,`	null	`],
	[`	O07	`,`	Failed attempted abortion Incl.: failure of attempted induction of abortion Excl.: incomplete abortion (O03-O06) 	`,`	null	`],
	[`	O07.0	`,`	Failed medical abortion, complicated by genital tract and pelvic infection With conditions in O08.0 	`,`	null	`],
	[`	O07.1	`,`	Failed medical abortion, complicated by delayed or excessive haemorrhage With conditions in O08.1 	`,`	null	`],
	[`	O07.2	`,`	Failed medical abortion, complicated by embolism With conditions in O08.2 	`,`	null	`],
	[`	O07.3	`,`	Failed medical abortion, with other and unspecified complications With conditions in O08.3-O08.9 	`,`	null	`],
	[`	O07.4	`,`	Failed medical abortion, without complication Failed medical abortion NOS 	`,`	null	`],
	[`	O07.5	`,`	Other and unspecified failed attempted abortion, complicated by genital tract and pelvic infection With conditions in O08.0 	`,`	null	`],
	[`	O07.6	`,`	Other and unspecified failed attempted abortion, complicated by delayed or excessive haemorrhage With conditions in O08.1 	`,`	null	`],
	[`	O07.7	`,`	Other and unspecified failed attempted abortion, complicated by embolism With conditions in O08.2 	`,`	null	`],
	[`	O07.8	`,`	Other and unspecified failed attempted abortion, with other and unspecified complications With conditions in O08.3-O08.9 	`,`	null	`],
	[`	O07.9	`,`	Other and unspecified failed attempted abortion, without complication Failed attempted abortion NOS 	`,`	null	`],
	[`	O08	`,`	Complications following abortion and ectopic and molar pregnancy Note: This code is provided primarily for morbidity coding. For use of this category reference should be made to the morbidity coding rules and guidelines in Volume 2. 	`,`	null	`],
	[`	O08.0	`,`	Genital tract and pelvic infection following abortion and ectopic and molar pregnancy Endometritis Oophoritis Parametritis Pelvic peritonitis Salpingitis Salpingo-oophoritis Sepsis following conditions classifiable to O00-O07 Use additional code (R57.2) , if desired, to identify septic shock. Excl.: septic or septicopyaemic embolism (O08.2) urinary tract infection (O08.8) 	`,`	null	`],
	[`	O08.1	`,`	Delayed or excessive haemorrhage following abortion and ectopic and molar pregnancy Afibrinogenaemia Defibrination syndrome Intravascular coagulation following conditions classifiable to O00-O07 	`,`	null	`],
	[`	O08.2	`,`	Embolism following abortion and ectopic and molar pregnancy Embolism: NOS air amniotic fluid blood-clot pulmonary pyaemic septic or septicopyaemic soap following conditions classifiable to O00-O07 	`,`	null	`],
	[`	O08.3	`,`	Shock following abortion and ectopic and molar pregnancy Circulatory collapse Shock (postoperative) following conditions classifiable to O00-O07 Excl.: septic shock (R57.2) 	`,`	null	`],
	[`	O08.4	`,`	Renal failure following abortion and ectopic and molar pregnancy Oliguria Renal: failure (acute) shutdown tubular necrosis Uraemia following conditions classifiable to O00-O07 	`,`	null	`],
	[`	O08.5	`,`	Metabolic disorders following abortion and ectopic and molar pregnancy Electrolyte imbalance following conditions classifiable to O00-O07 	`,`	null	`],
	[`	O08.6	`,`	Damage to pelvic organs and tissues following abortion and ectopic and molar pregnancy Laceration, perforation, tear or chemical damage of: bladder bowel broad ligament cervix periurethral tissue uterus following conditions classifiable to O00-O07 	`,`	null	`],
	[`	O08.7	`,`	Other venous complications following abortion and ectopic and molar pregnancy 	`,`	null	`],
	[`	O08.8	`,`	Other complications following abortion and ectopic and molar pregnancy Cardiac arrest Urinary tract infection following conditions classifiable to O00-O07 	`,`	null	`],
	[`	O08.9	`,`	Complication following abortion and ectopic and molar pregnancy, unspecified Unspecified complication following conditions classifiable to O00-O07 	`,`	null	`],
	[`	O10 	`,`	Pre-existing hypertension complicating pregnancy, childbirth and the puerperium Incl.: the listed conditions with pre-existing proteinuria Excl.: that with superimposed pre-eclampsia (O11) 	`,`	null	`],
	[`	O10.0 	`,`	Pre-existing essential hypertension complicating pregnancy, childbirth and the puerperium Any condition in I10 specified as a reason for obstetric care during pregnancy, childbirth or the puerperium 	`,`	null	`],
	[`	O10.1 	`,`	Pre-existing hypertensive heart disease complicating pregnancy, childbirth and the puerperium Any condition in I11.- specified as a reason for obstetric care during pregnancy, childbirth or the puerperium 	`,`	null	`],
	[`	O10.2 	`,`	Pre-existing hypertensive renal disease complicating pregnancy, childbirth and the puerperium Any condition in I12.- specified as a reason for obstetric care during pregnancy, childbirth or the puerperium 	`,`	null	`],
	[`	O10.3 	`,`	Pre-existing hypertensive heart and renal disease complicating pregnancy, childbirth and the puerperium Any condition in I13.- specified as a reason for obstetric care during pregnancy, childbirth or the puerperium 	`,`	null	`],
	[`	O10.4 	`,`	Pre-existing secondary hypertension complicating pregnancy, childbirth and the puerperium Any condition in I15.- specified as a reason for obstetric care during pregnancy, childbirth or the puerperium 	`,`	null	`],
	[`	O10.9 	`,`	Unspecified pre-existing hypertension complicating pregnancy, childbirth and the puerperium 	`,`	null	`],
	[`	O11 	`,`	Pre-eclampsia superimposed on chronic hypertension Incl.: Conditions in O10.- complicated by pre-eclampsia Pre-eclampsia superimposed on: hypertension NOS pre-existing hypertension 	`,`	null	`],
	[`	O12 	`,`	Gestational [pregnancy-induced] oedema and proteinuria without hypertension 	`,`	null	`],
	[`	O12.0 	`,`	Gestational oedema 	`,`	null	`],
	[`	O12.1 	`,`	Gestational proteinuria 	`,`	null	`],
	[`	O12.2 	`,`	Gestational oedema with proteinuria 	`,`	null	`],
	[`	O13 	`,`	Gestational [pregnancy-induced] hypertension Incl.: Gestational Pregnancy-induced hypertension NOS Transient hypertension of pregnancy 	`,`	null	`],
	[`	O14 	`,`	Pre-eclampsia Excl.: superimposed pre-eclampsia (O11) 	`,`	null	`],
	[`	O14.0 	`,`	Mild to moderate pre-eclampsia 	`,`	null	`],
	[`	O14.1 	`,`	Severe pre-eclampsia 	`,`	null	`],
	[`	O14.2 	`,`	HELLP syndrome Combination of hemolysis, elevated liver enzymes and low platelet count 	`,`	null	`],
	[`	O14.9 	`,`	Pre-eclampsia, unspecified 	`,`	null	`],
	[`	O15 	`,`	Eclampsia Incl.: convulsions following conditions in O10-O14 and O16 eclampsia with pregnancy-induced or pre-existing hypertension 	`,`	null	`],
	[`	O15.0 	`,`	Eclampsia in pregnancy 	`,`	null	`],
	[`	O15.1 	`,`	Eclampsia in labour 	`,`	null	`],
	[`	O15.2 	`,`	Eclampsia in the puerperium 	`,`	null	`],
	[`	O15.9 	`,`	Eclampsia, unspecified as to time period Eclampsia NOS 	`,`	null	`],
	[`	O16 	`,`	Unspecified maternal hypertension 	`,`	null	`],
	[`	O20 	`,`	Haemorrhage in early pregnancy Excl.: pregnancy with abortive outcome (O00-O08) 	`,`	null	`],
	[`	O20.0	`,`	Threatened abortion Haemorrhage specified as due to threatened abortion 	`,`	null	`],
	[`	O20.8	`,`	Other haemorrhage in early pregnancy 	`,`	null	`],
	[`	O20.9	`,`	Haemorrhage in early pregnancy, unspecified 	`,`	null	`],
	[`	O21	`,`	Excessive vomiting in pregnancy 	`,`	null	`],
	[`	O21.0	`,`	Mild hyperemesis gravidarum Hyperemesis gravidarum, mild or unspecified, starting before the end of the 22nd week of gestation 	`,`	null	`],
	[`	O21.1	`,`	Hyperemesis gravidarum with metabolic disturbance Hyperemesis gravidarum, starting before the end of the 22nd week of gestation, with metabolic disturbance such as: carbohydrate depletion dehydration electrolyte imbalance 	`,`	null	`],
	[`	O21.2	`,`	Late vomiting of pregnancy Excessive vomiting starting after 22 completed weeks of gestation 	`,`	null	`],
	[`	O21.8	`,`	Other vomiting complicating pregnancy Vomiting due to diseases classified elsewhere, complicating pregnancy Use additional code, if desired, to identify cause. 	`,`	null	`],
	[`	O21.9	`,`	Vomiting of pregnancy, unspecified 	`,`	null	`],
	[`	O22	`,`	Venous complications and haemorrhoids in pregnancy Excl.: obstetric pulmonary embolism (O88.-) the listed conditions as complications of: abortion or ectopic or molar pregnancy (O00-O07, O08.7) childbirth and the puerperium (O87.-) 	`,`	null	`],
	[`	O22.0	`,`	Varicose veins of lower extremity in pregnancy Varicose veins NOS in pregnancy 	`,`	null	`],
	[`	O22.1	`,`	Genital varices in pregnancy Perineal Vaginal Vulval varices in pregnancy 	`,`	null	`],
	[`	O22.2	`,`	Superficial thrombophlebitis in pregnancy Thrombophlebitis of legs in pregnancy 	`,`	null	`],
	[`	O22.3	`,`	Deep phlebothrombosis in pregnancy Deep-vein thrombosis, antepartum 	`,`	null	`],
	[`	O22.4	`,`	Haemorrhoids in pregnancy 	`,`	null	`],
	[`	O22.5	`,`	Cerebral venous thrombosis in pregnancy Cerebrovenous sinus thrombosis in pregnancy 	`,`	null	`],
	[`	O22.8	`,`	Other venous complications in pregnancy 	`,`	null	`],
	[`	O22.9	`,`	Venous complication in pregnancy, unspecified Gestational: phlebitis NOS phlebopathy NOS thrombosis NOS 	`,`	null	`],
	[`	O23	`,`	Infections of genitourinary tract in pregnancy Excl.: gonococcal infections (O98.2) infections with a predominantly sexual mode of transmission NOS (O98.3) syphilis (O98.1) tuberculosis of genitourinary system (O98.0) venereal disease NOS (O98.3) 	`,`	null	`],
	[`	O23.0	`,`	Infections of kidney in pregnancy 	`,`	null	`],
	[`	O23.1	`,`	Infections of bladder in pregnancy 	`,`	null	`],
	[`	O23.2	`,`	Infections of urethra in pregnancy 	`,`	null	`],
	[`	O23.3	`,`	Infections of other parts of urinary tract in pregnancy 	`,`	null	`],
	[`	O23.4	`,`	Unspecified infection of urinary tract in pregnancy 	`,`	null	`],
	[`	O23.5	`,`	Infections of the genital tract in pregnancy 	`,`	null	`],
	[`	O23.9	`,`	Other and unspecified genitourinary tract infection in pregnancy Genitourinary tract infection in pregnancy NOS 	`,`	null	`],
	[`	O24	`,`	Diabetes mellitus in pregnancy Incl.: in childbirth and the puerperium 	`,`	null	`],
	[`	O24.0	`,`	Pre-existing type 1 diabetes mellitus 	`,`	null	`],
	[`	O24.1	`,`	Pre-existing type 2 diabetes mellitus 	`,`	null	`],
	[`	O24.2	`,`	Pre-existing malnutrition-related diabetes mellitus 	`,`	null	`],
	[`	O24.3	`,`	Pre-existing diabetes mellitus, unspecified 	`,`	null	`],
	[`	O24.4	`,`	Diabetes mellitus arising in pregnancy Gestational diabetes mellitus NOS 	`,`	null	`],
	[`	O24.9	`,`	Diabetes mellitus in pregnancy, unspecified 	`,`	null	`],
	[`	O25	`,`	Malnutrition in pregnancy Incl.: Malnutrition in childbirth and the puerperium 	`,`	null	`],
	[`	O26	`,`	Maternal care for other conditions predominantly related to pregnancy 	`,`	null	`],
	[`	O26.0	`,`	Excessive weight gain in pregnancy Excl.: gestational oedema (O12.0, O12.2) 	`,`	null	`],
	[`	O26.	`,`	Low weight gain in pregnancy 	`,`	null	`],
	[`	O26.2	`,`	Pregnancy care of habitual aborter Excl.: habitual aborter: with current abortion (O03-O06) without current pregnancy (N96) 	`,`	null	`],
	[`	O26.3	`,`	Retained intrauterine contraceptive device in pregnancy 	`,`	null	`],
	[`	O26.4	`,`	Herpes gestationis 	`,`	null	`],
	[`	O26.5	`,`	Maternal hypotension syndrome Supine hypotensive syndrome 	`,`	null	`],
	[`	O26.6	`,`	Liver disorders in pregnancy, childbirth and the puerperium Cholestasis (intrahepatic) in pregnancy Obstetric cholestasis Excl.: hepatorenal syndrome following labour and delivery (O90.4) 	`,`	null	`],
	[`	O26.7	`,`	Subluxation of symphysis (pubis) in pregnancy, childbirth and the puerperium Excl.: traumatic separation of symphysis (pubis) during childbirth (O71.6) 	`,`	null	`],
	[`	O26.8	`,`	Other specified pregnancy-related conditions Exhaustion and fatigue Peripheral neuritis Renal disease pregnancy-related 	`,`	null	`],
	[`	O26.9	`,`	Pregnancy-related condition, unspecified 	`,`	null	`],
	[`	O28	`,`	Abnormal findings on antenatal screening of mother Excl.: diagnostic findings classified elsewhere - see Alphabetical Index maternal care related to the fetus and amniotic cavity and possible delivery problems (O30-O48) 	`,`	null	`],
	[`	O28.0	`,`	Abnormal haematological finding on antenatal screening of mother 	`,`	null	`],
	[`	O28.1	`,`	Abnormal biochemical finding on antenatal screening of mother 	`,`	null	`],
	[`	O28.2	`,`	Abnormal cytological finding on antenatal screening of mother 	`,`	null	`],
	[`	O28.3	`,`	Abnormal ultrasonic finding on antenatal screening of mother 	`,`	null	`],
	[`	O28.4	`,`	Abnormal radiological finding on antenatal screening of mother 	`,`	null	`],
	[`	O28.5	`,`	Abnormal chromosomal and genetic finding on antenatal screening of mother 	`,`	null	`],
	[`	O28.8	`,`	Other abnormal findings on antenatal screening of mother 	`,`	null	`],
	[`	O28.9	`,`	Abnormal finding on antenatal screening of mother, unspecified 	`,`	null	`],
	[`	O29	`,`	Complications of anaesthesia during pregnancy Incl.: maternal complications arising from the administration of a general or local anaesthetic, analgesic or other sedation during pregnancy Excl.: complications of anaesthesia during: abortion or ectopic or molar pregnancy (O00-O08) labour and delivery (O74.-) puerperium (O89.-) 	`,`	null	`],
	[`	O29.0	`,`	Pulmonary complications of anaesthesia during pregnancy Aspiration pneumonitis Inhalation of stomach contents or secretions NOS Mendelson syndrome Pressure collapse of lung due to anaesthesia during pregnancy 	`,`	null	`],
	[`	O29.1	`,`	Cardiac complications of anaesthesia during pregnancy Cardiac: arrest failure due to anaesthesia during pregnancy 	`,`	null	`],
	[`	O29.2	`,`	Central nervous system complications of anaesthesia during pregnancy Cerebral anoxia due to anaesthesia during pregnancy 	`,`	null	`],
	[`	O29.3	`,`	Toxic reaction to local anaesthesia during pregnancy 	`,`	null	`],
	[`	O29.4	`,`	Spinal and epidural anaesthesia-induced headache during pregnancy 	`,`	null	`],
	[`	O29.5	`,`	Other complications of spinal and epidural anaesthesia during pregnancy 	`,`	null	`],
	[`	O29.6	`,`	Failed or difficult intubation during pregnancy 	`,`	null	`],
	[`	O29.8	`,`	Other complications of anaesthesia during pregnancy 	`,`	null	`],
	[`	O29.9	`,`	Complication of anaesthesia during pregnancy, unspecified 	`,`	null	`],
	[`	O30	`,`	Multiple gestation Excl.: complications specific to multiple gestation (O31.-) 	`,`	null	`],
	[`	O30.0	`,`	Twin pregnancy 	`,`	null	`],
	[`	O30.1	`,`	Triplet pregnancy 	`,`	null	`],
	[`	O30.2	`,`	Quadruplet pregnancy 	`,`	null	`],
	[`	O30.8	`,`	Other multiple gestation 	`,`	null	`],
	[`	O30.9	`,`	Multiple gestation, unspecified Multiple pregnancy NOS 	`,`	null	`],
	[`	O31	`,`	Complications specific to multiple gestation Excl.: conjoined twins causing disproportion (O33.7) delayed delivery of second twin, triplet, etc. (O63.2) malpresentation of one fetus or more (O32.5) with obstructed labour (O64-O66) 	`,`	null	`],
	[`	O31.0	`,`	Papyraceous fetus Fetus compressus 	`,`	null	`],
	[`	O31.1	`,`	Continuing pregnancy after abortion of one fetus or more 	`,`	null	`],
	[`	O31.2	`,`	Continuing pregnancy after intrauterine death of one fetus or more 	`,`	null	`],
	[`	O31.8	`,`	Other complications specific to multiple gestation 	`,`	null	`],
	[`	O32	`,`	Maternal care for known or suspected malpresentation of fetus Incl.: the listed conditions as a reason for observation, hospitalization or other obstetric care of the mother, or for caesarean section before onset of labour Excl.: the listed conditions with obstructed labour (O64.-) 	`,`	null	`],
	[`	O32.0	`,`	Maternal care for unstable lie 	`,`	null	`],
	[`	O32.1	`,`	Maternal care for breech presentation 	`,`	null	`],
	[`	O32.2	`,`	Maternal care for transverse and oblique lie Presentation: oblique transverse 	`,`	null	`],
	[`	O32.3	`,`	Maternal care for face, brow and chin presentation 	`,`	null	`],
	[`	O32.4	`,`	Maternal care for high head at term Failure of head to enter pelvic brim 	`,`	null	`],
	[`	O32.5	`,`	Maternal care for multiple gestation with malpresentation of one fetus or more 	`,`	null	`],
	[`	O32.6	`,`	Maternal care for compound presentation 	`,`	null	`],
	[`	O32.8	`,`	Maternal care for other malpresentation of fetus 	`,`	null	`],
	[`	O32.9	`,`	Maternal care for malpresentation of fetus, unspecified 	`,`	null	`],
	[`	O33	`,`	Maternal care for known or suspected disproportion Incl.: the listed conditions as a reason for observation, hospitalization or other obstetric care of the mother, or for caesarean section before onset of labour Excl.: the listed conditions with obstructed labour (O65-O66) 	`,`	null	`],
	[`	O33.0	`,`	Maternal care for disproportion due to deformity of maternal pelvic bones Pelvic deformity causing disproportion NOS 	`,`	null	`],
	[`	O33.1	`,`	Maternal care for disproportion due to generally contracted pelvis Contracted pelvis NOS causing disproportion 	`,`	null	`],
	[`	O33.2	`,`	Maternal care for disproportion due to inlet contraction of pelvis Inlet contraction (pelvis) causing disproportion 	`,`	null	`],
	[`	O33.3	`,`	Maternal care for disproportion due to outlet contraction of pelvis Mid-cavity contraction (pelvis) Outlet contraction (pelvis) causing disproportion 	`,`	null	`],
	[`	O33.4	`,`	Maternal care for disproportion of mixed maternal and fetal origin 	`,`	null	`],
	[`	O33.5	`,`	Maternal care for disproportion due to unusually large fetus Disproportion of fetal origin with normally formed fetus Fetal disproportion NOS 	`,`	null	`],
	[`	O33.6	`,`	Maternal care for disproportion due to hydrocephalic fetus 	`,`	null	`],
	[`	O33.7	`,`	Maternal care for disproportion due to other fetal deformities Conjoined twins Fetal: ascites hydrops meningomyelocele sacral teratoma tumour causing disproportion 	`,`	null	`],
	[`	O33.8	`,`	Maternal care for disproportion of other origin 	`,`	null	`],
	[`	O33.9	`,`	Maternal care for disproportion, unspecified Cephalopelvic disproportion NOS Fetopelvic disproportion NOS 	`,`	null	`],
	[`	O34	`,`	Maternal care for known or suspected abnormality of pelvic organs Incl.: the listed conditions as a reason for observation, hospitalization or other obstetric care of the mother, or for caesarean section before onset of labour Excl.: the listed conditions with obstructed labour (O65.5) 	`,`	null	`],
	[`	O34.0	`,`	Maternal care for congenital malformation of uterus Maternal care for: double uterus uterus bicornis 	`,`	null	`],
	[`	O34.1	`,`	Maternal care for tumour of corpus uteri Maternal care for: polyp of corpus uteri uterine fibroid Excl.: maternal care for tumour of cervix (O34.4) 	`,`	null	`],
	[`	O34.2	`,`	Maternal care due to uterine scar from previous surgery Maternal care for scar from previous caesarean section Excl.: vaginal delivery following previous caesarean section NOS (O75.7) 	`,`	null	`],
	[`	O34.3	`,`	Maternal care for cervical incompetence Maternal care for: cerclage Shirodkar suture with or without mention of cervical incompetence 	`,`	null	`],
	[`	O34.4	`,`	Maternal care for other abnormalities of cervix Maternal care for: polyp of cervix previous surgery to cervix stricture or stenosis of cervix tumour of cervix 	`,`	null	`],
	[`	O34.5	`,`	Maternal care for other abnormalities of gravid uterus Maternal care for: incarceration prolapse retroversion of gravid uterus 	`,`	null	`],
	[`	O34.6	`,`	Maternal care for abnormality of vagina Maternal care for: previous surgery to vagina septate vagina stenosis of vagina (acquired)(congenital) stricture of vagina tumour of vagina Excl.: maternal care for vaginal varices in pregnancy (O22.1) 	`,`	null	`],
	[`	O34.7	`,`	Maternal care for abnormality of vulva and perineum Maternal care for: fibrosis of perineum previous surgery to perineum or vulva rigid perineum tumour of vulva Excl.: maternal care for perineal and vulval varices in pregnancy (O22.1) 	`,`	null	`],
	[`	O34.8	`,`	Maternal care for other abnormalities of pelvic organs Maternal care for: cystocele pelvic floor repair (previous) pendulous abdomen rectocele rigid pelvic floor 	`,`	null	`],
	[`	O34.9	`,`	Maternal care for abnormality of pelvic organ, unspecified 	`,`	null	`],
	[`	O35	`,`	Maternal care for known or suspected fetal abnormality and damage Incl.: the listed conditions in the fetus as a reason for observation, hospitalization or other obstetric care of the mother, or for termination of pregnancy Excl.: maternal care for known or suspected disproportion (O33.-) 	`,`	null	`],
	[`	O35.0	`,`	Maternal care for (suspected) central nervous system malformation in fetus Maternal care for (suspected) fetal: anencephaly spina bifida Excl.: chromosomal abnormality in fetus (O35.1) 	`,`	null	`],
	[`	O35.1	`,`	Maternal care for (suspected) chromosomal abnormality in fetus 	`,`	null	`],
	[`	O35.2	`,`	Maternal care for (suspected) hereditary disease in fetus Excl.: chromosomal abnormality in fetus (O35.1) 	`,`	null	`],
	[`	O35.3	`,`	Maternal care for (suspected) damage to fetus from viral disease in mother Maternal care for (suspected) damage to fetus from maternal: cytomegalovirus infection rubella 	`,`	null	`],
	[`	O35.4	`,`	Maternal care for (suspected) damage to fetus from alcohol 	`,`	null	`],
	[`	O35.5	`,`	Maternal care for (suspected) damage to fetus by drugs Maternal care for (suspected) damage to fetus from drug addiction Excl.: fetal distress in labour and delivery due to drug administration (O68.-) 	`,`	null	`],
	[`	O35.6	`,`	Maternal care for (suspected) damage to fetus by radiation 	`,`	null	`],
	[`	O35.7	`,`	Maternal care for (suspected) damage to fetus by other medical procedures Maternal care for (suspected) damage to fetus by: amniocentesis biopsy procedures haematological investigation intrauterine contraceptive device intrauterine surgery 	`,`	null	`],
	[`	O35.8	`,`	Maternal care for other (suspected) fetal abnormality and damage Maternal care for (suspected) damage to fetus from maternal: listeriosis toxoplasmosis 	`,`	null	`],
	[`	O35.9	`,`	Maternal care for (suspected) fetal abnormality and damage, unspecified 	`,`	null	`],
	[`	O36	`,`	Maternal care for other known or suspected fetal problems Incl.: the listed conditions in the fetus as a reason for observation, hospitalization or other obstetric care of the mother, or for termination of pregnancy Excl.: labour and delivery complicated by fetal stress [distress] (O68.-) placental transfusion syndromes (O43.0) 	`,`	null	`],
	[`	O36.0	`,`	Maternal care for rhesus isoimmunization Anti-D [Rh] antibodies Rh incompatibility (with hydrops fetalis) 	`,`	null	`],
	[`	O36.1	`,`	Maternal care for other isoimmunization ABO isoimmunization Isoimmunization NOS (with hydrops fetalis) 	`,`	null	`],
	[`	O36.2	`,`	Maternal care for hydrops fetalis Hydrops fetalis: NOS not associated with isoimmunization 	`,`	null	`],
	[`	O36.3	`,`	Maternal care for signs of fetal hypoxia 	`,`	null	`],
	[`	O36.4	`,`	Maternal care for intrauterine death Excl.: missed abortion (O02.1) 	`,`	null	`],
	[`	O36.5	`,`	Maternal care for poor fetal growth Maternal care for known or suspected: light-for-dates placental insufficiency small-for-dates 	`,`	null	`],
	[`	O36.6	`,`	Maternal care for excessive fetal growth Maternal care for known or suspected large-for-dates 	`,`	null	`],
	[`	O36.7	`,`	Maternal care for viable fetus in abdominal pregnancy 	`,`	null	`],
	[`	O36.8	`,`	Maternal care for other specified fetal problems 	`,`	null	`],
	[`	O36.9	`,`	Maternal care for fetal problem, unspecified 	`,`	null	`],
	[`	O40	`,`	Polyhydramnios Incl.: Hydramnios 	`,`	null	`],
	[`	O41	`,`	Other disorders of amniotic fluid and membranes Excl.: premature rupture of membranes (O42.-) 	`,`	null	`],
	[`	O41.0	`,`	Oligohydramnios Oligohydramnios without mention of rupture of membranes 	`,`	null	`],
	[`	O41.1	`,`	Infection of amniotic sac and membranes Amnionitis Chorioamnionitis Membranitis Placentitis 	`,`	null	`],
	[`	O41.8	`,`	Other specified disorders of amniotic fluid and membranes 	`,`	null	`],
	[`	O41.9	`,`	Disorder of amniotic fluid and membranes, unspecified 	`,`	null	`],
	[`	O42	`,`	Premature rupture of membranes 	`,`	null	`],
	[`	O42.0	`,`	Premature rupture of membranes, onset of labour within 24 hours 	`,`	null	`],
	[`	O42.1	`,`	Premature rupture of membranes, onset of labour after 24 hours Excl.: with labour delayed by therapy (O42.2) 	`,`	null	`],
	[`	O42.2	`,`	Premature rupture of membranes, labour delayed by therapy 	`,`	null	`],
	[`	O42.9	`,`	Premature rupture of membranes, unspecified 	`,`	null	`],
	[`	O43	`,`	Placental disorders Excl.: maternal care for poor fetal growth due to placental insufficiency (O36.5) placenta praevia (O44.-) premature separation of placenta [abruptio placentae] (O45.-) 	`,`	null	`],
	[`	O43.0	`,`	Placental transfusion syndromes Transfusion: fetomaternal maternofetal twin-to-twin 	`,`	null	`],
	[`	O43.1	`,`	Malformation of placenta Abnormal placenta NOS Circumvallate placenta 	`,`	null	`],
	[`	O43.2	`,`	Morbidly adherent placenta Placenta: accreta increta percreta Use additional code, if desired, to identify any: postpartum haemmorrhage, third stage (O72.0) retained placenta without hemorrhage (O73.0) 	`,`	null	`],
	[`	O43.8	`,`	Other placental disorders Placental: dysfunction infarction 	`,`	null	`],
	[`	O43.9	`,`	Placental disorder, unspecified 	`,`	null	`],
	[`	O44	`,`	Placenta praevia 	`,`	null	`],
	[`	O44.0	`,`	Placenta praevia specified as without haemorrhage Low implantation of placenta specified as without haemorrhage 	`,`	null	`],
	[`	O44.1	`,`	Placenta praevia with haemorrhage Low implantation of placenta, NOS or with haemorrhage Placenta praevia: marginal partial total NOS or with haemorrhage Excl.: labour and delivery complicated by haemorrhage from vasa praevia (O69.4) 	`,`	null	`],
	[`	O45	`,`	Premature separation of placenta [abruptio placentae] 	`,`	null	`],
	[`	O45.0	`,`	Premature separation of placenta with coagulation defect Abruptio placentae with (excessive) haemorrhage associated with: afibrinogenaemia disseminated intravascular coagulation hyperfibrinolysis hypofibrinogenaemia 	`,`	null	`],
	[`	O45.8	`,`	Other premature separation of placenta 	`,`	null	`],
	[`	O45.9	`,`	Premature separation of placenta, unspecified Abruptio placentae NOS 	`,`	null	`],
	[`	O46	`,`	Antepartum haemorrhage, not elsewhere classified Excl.: haemorrhage in early pregnancy (O20.-) intrapartum haemorrhage NEC (O67.-) placenta praevia (O44.-) premature separation of placenta [abruptio placentae] (O45.-) 	`,`	null	`],
	[`	O46.0	`,`	Antepartum haemorrhage with coagulation defect Antepartum haemorrhage (excessive) associated with: afibrinogenaemia disseminated intravascular coagulation hyperfibrinolysis hypofibrinogenaemia 	`,`	null	`],
	[`	O46.8	`,`	Other antepartum haemorrhage 	`,`	null	`],
	[`	O46.9	`,`	Antepartum haemorrhage, unspecified 	`,`	null	`],
	[`	O47	`,`	False labour 	`,`	null	`],
	[`	O47.0	`,`	False labour before 37 completed weeks of gestation 	`,`	null	`],
	[`	O47.1	`,`	False labour at or after 37 completed weeks of gestation 	`,`	null	`],
	[`	O47.9	`,`	False labour, unspecified 	`,`	null	`],
	[`	O48	`,`	Prolonged pregnancy Incl.: Post-dates Post-term 	`,`	null	`],
	[`	O60	`,`	Preterm labour and delivery Incl.: Onset (spontaneous) of labour before 37 completed weeks of gestation 	`,`	null	`],
	[`	O60.0	`,`	Preterm labour without delivery Preterm labour: induced spontaneous 	`,`	null	`],
	[`	O60.1	`,`	Preterm spontaneous labour with preterm delivery Preterm labour with delivery NOS Preterm spontaneous labour with preterm delivery by caesarean section 	`,`	null	`],
	[`	O60.2	`,`	Preterm spontaneous labour with term delivery Preterm spontaneous labour with term delivery by caesarean section 	`,`	null	`],
	[`	O60.3	`,`	Preterm delivery without spontaneous labour Preterm delivery by: caesarean section, without spontaneous labour induction 	`,`	null	`],
	[`	O61	`,`	Failed induction of labour 	`,`	null	`],
	[`	O61.0	`,`	Failed medical induction of labour Failed induction (of labour) by: oxytocin prostaglandins 	`,`	null	`],
	[`	O61.1	`,`	Failed instrumental induction of labour Failed induction (of labour): mechanical surgical 	`,`	null	`],
	[`	O61.8	`,`	Other failed induction of labour 	`,`	null	`],
	[`	O61.9	`,`	Failed induction of labour, unspecified 	`,`	null	`],
	[`	O62	`,`	Abnormalities of forces of labour 	`,`	null	`],
	[`	O62.0	`,`	Primary inadequate contractions Failure of cervical dilatation Primary hypotonic uterine dysfunction Uterine inertia during latent phase of labour 	`,`	null	`],
	[`	O62.1	`,`	Secondary uterine inertia Arrested active phase of labour Secondary hypotonic uterine dysfunction 	`,`	null	`],
	[`	O62.2	`,`	Other uterine inertia Atony of uterus Desultory labour Hypotonic uterine dysfunction NOS Irregular labour Poor contractions Uterine inertia NOS 	`,`	null	`],
	[`	O62.3	`,`	Precipitate labour 	`,`	null	`],
	[`	O62.4	`,`	Hypertonic, incoordinate, and prolonged uterine contractions Contraction ring dystocia Dyscoordinate labour Hour-glass contraction of uterus Hypertonic uterine dysfunction Incoordinate uterine action Tetanic contractions Uterine dystocia NOS Excl.: dystocia (fetal)(maternal) NOS (O66.9) 	`,`	null	`],
	[`	O62.8	`,`	Other abnormalities of forces of labour 	`,`	null	`],
	[`	O62.9	`,`	Abnormality of forces of labour, unspecified 	`,`	null	`],
	[`	O63	`,`	Long labour 	`,`	null	`],
	[`	O63.0	`,`	Prolonged first stage (of labour) 	`,`	null	`],
	[`	O63.1	`,`	Prolonged second stage (of labour) 	`,`	null	`],
	[`	O63.2	`,`	Delayed delivery of second twin, triplet, etc. 	`,`	null	`],
	[`	O63.9	`,`	Long labour, unspecified Prolonged labour NOS 	`,`	null	`],
	[`	O64	`,`	Obstructed labour due to malposition and malpresentation of fetus 	`,`	null	`],
	[`	O64.0	`,`	Obstructed labour due to incomplete rotation of fetal head Deep transverse arrest Obstructed labour due to persistent (position): occipitoiliac occipitoposterior occipitosacral occipitotransverse 	`,`	null	`],
	[`	O64.1	`,`	Obstructed labour due to breech presentation 	`,`	null	`],
	[`	O64.2	`,`	Obstructed labour due to face presentation Obstructed labour due to chin presentation 	`,`	null	`],
	[`	O64.3	`,`	Obstructed labour due to brow presentation 	`,`	null	`],
	[`	O64.4	`,`	Obstructed labour due to shoulder presentation Prolapsed arm Excl.: impacted shoulders (O66.0) shoulder dystocia (O66.0) 	`,`	null	`],
	[`	O64.5	`,`	Obstructed labour due to compound presentation 	`,`	null	`],
	[`	O64.8	`,`	Obstructed labour due to other malposition and malpresentation 	`,`	null	`],
	[`	O64.9	`,`	Obstructed labour due to malposition and malpresentation, unspecified 	`,`	null	`],
	[`	O65	`,`	Obstructed labour due to maternal pelvic abnormality 	`,`	null	`],
	[`	O65.0	`,`	Obstructed labour due to deformed pelvis 	`,`	null	`],
	[`	O65.1	`,`	Obstructed labour due to generally contracted pelvis 	`,`	null	`],
	[`	O65.2	`,`	Obstructed labour due to pelvic inlet contraction 	`,`	null	`],
	[`	O65.3	`,`	Obstructed labour due to pelvic outlet and mid-cavity contraction 	`,`	null	`],
	[`	O65.4	`,`	Obstructed labour due to fetopelvic disproportion, unspecified Excl.: dystocia due to abnormality of fetus (O66.2-O66.3) 	`,`	null	`],
	[`	O65.5	`,`	Obstructed labour due to abnormality of maternal pelvic organs Obstructed labour due to conditions listed in O34.- 	`,`	null	`],
	[`	O65.8	`,`	Obstructed labour due to other maternal pelvic abnormalities 	`,`	null	`],
	[`	O65.9	`,`	Obstructed labour due to maternal pelvic abnormality, unspecified 	`,`	null	`],
	[`	O66	`,`	Other obstructed labour 	`,`	null	`],
	[`	O66.0	`,`	Obstructed labour due to shoulder dystocia Impacted shoulders 	`,`	null	`],
	[`	O66.1	`,`	Obstructed labour due to locked twins 	`,`	null	`],
	[`	O66.2	`,`	Obstructed labour due to unusually large fetus 	`,`	null	`],
	[`	O66.3	`,`	Obstructed labour due to other abnormalities of fetus Dystocia due to: conjoined twins fetal: ascites hydrops meningomyelocele sacral teratoma tumour hydrocephalic fetus 	`,`	null	`],
	[`	O66.4	`,`	Failed trial of labour, unspecified Failed trial of labour with subsequent delivery by caesarean section 	`,`	null	`],
	[`	O66.5	`,`	Failed application of vacuum extractor and forceps, unspecified Failed application of ventouse or forceps, with subsequent delivery by forceps or caesarean section respectively 	`,`	null	`],
	[`	O66.8	`,`	Other specified obstructed labour 	`,`	null	`],
	[`	O66.9	`,`	Obstructed labour, unspecified Dystocia: NOS fetal NOS maternal NOS 	`,`	null	`],
	[`	O67	`,`	Labour and delivery complicated by intrapartum haemorrhage, not elsewhere classified Excl.: antepartum haemorrhage NEC (O46.-) placenta praevia (O44.-) postpartum haemorrhage (O72.-) premature separation of placenta [abruptio placentae] (O45.-) 	`,`	null	`],
	[`	O67.0	`,`	Intrapartum haemorrhage with coagulation defect Intrapartum haemorrhage (excessive) associated with: afibrinogenaemia disseminated intravascular coagulation hyperfibrinolysis hypofibrinogenaemia 	`,`	null	`],
	[`	O67.8	`,`	Other intrapartum haemorrhage Excessive intrapartum haemorrhage 	`,`	null	`],
	[`	O67.9	`,`	Intrapartum haemorrhage, unspecified 	`,`	null	`],
	[`	O68	`,`	Labour and delivery complicated by fetal stress [distress] Incl.: fetal distress in labour or delivery due to drug administration 	`,`	null	`],
	[`	O68.0	`,`	Labour and delivery complicated by fetal heart rate anomaly Fetal: bradycardia heart rate irregularity tachycardia Excl.: with meconium in amniotic fluid (O68.2) 	`,`	null	`],
	[`	O68.1	`,`	Labour and delivery complicated by meconium in amniotic fluid Excl.: with fetal heart rate anomaly (O68.2) 	`,`	null	`],
	[`	O68.2	`,`	Labour and delivery complicated by fetal heart rate anomaly with meconium in amniotic fluid 	`,`	null	`],
	[`	O68.3	`,`	Labour and delivery complicated by biochemical evidence of fetal stress Abnormal fetal: acidaemia acid-base balance 	`,`	null	`],
	[`	O68.8	`,`	Labour and delivery complicated by other evidence of fetal stress Evidence of fetal distress: electrocardiographic ultrasonic 	`,`	null	`],
	[`	O68.9	`,`	Labour and delivery complicated by fetal stress, unspecified 	`,`	null	`],
	[`	O69	`,`	Labour and delivery complicated by umbilical cord complications 	`,`	null	`],
	[`	O69.0	`,`	Labour and delivery complicated by prolapse of cord 	`,`	null	`],
	[`	O69.1	`,`	Labour and delivery complicated by cord around neck, with compression 	`,`	null	`],
	[`	O69.2	`,`	Labour and delivery complicated by other cord entanglement, with compression Compression of cord NOS Entanglement of cords of twins in monoamniotic sac Knot in cord 	`,`	null	`],
	[`	O69.3	`,`	Labour and delivery complicated by short cord 	`,`	null	`],
	[`	O69.4	`,`	Labour and delivery complicated by vasa praevia Haemorrhage from vasa praevia 	`,`	null	`],
	[`	O69.5	`,`	Labour and delivery complicated by vascular lesion of cord Cord: bruising haematoma Thrombosis of umbilical vessels 	`,`	null	`],
	[`	O69.8	`,`	Labour and delivery complicated by other cord complications Cord around neck without compression 	`,`	null	`],
	[`	O69.9	`,`	Labour and delivery complicated by cord complication, unspecified 	`,`	null	`],
	[`	O70	`,`	Perineal laceration during delivery Incl.: episiotomy extended by laceration Excl.: obstetric high vaginal laceration (O71.4) vaginal sulcus laceration (O71.4) 	`,`	null	`],
	[`	O70.0	`,`	First degree perineal laceration during delivery Perineal laceration, rupture or tear (involving): fourchette labia periurethral tissue skin slight vagina, low vulva during delivery Excl.: periurethral laceration involving urethra (O71.5) that with laceration of: high vaginal wall (middle)(upper third of vaginal wall) (O71.4) vaginal sulcus (O71.4) 	`,`	null	`],
	[`	O70.1	`,`	Second degree perineal laceration during delivery Perineal laceration, rupture or tear as in O70.0, also involving: pelvic floor perineal muscles vaginal muscles during delivery Excl.: that involving anal sphincter (O70.2) 	`,`	null	`],
	[`	O70.2	`,`	Third degree perineal laceration during delivery Perineal laceration, rupture or tear as in O70.1, also involving: anal sphincter rectovaginal septum sphincter NOS during delivery Excl.: that involving anal or rectal mucosa (O70.3) 	`,`	null	`],
	[`	O70.3	`,`	Fourth degree perineal laceration during delivery Perineal laceration, rupture or tear as in O70.2, also involving: anal mucosa rectal mucosa during delivery 	`,`	null	`],
	[`	O70.9	`,`	Perineal laceration during delivery, unspecified 	`,`	null	`],
	[`	O71	`,`	Other obstetric trauma Incl.: damage from instruments 	`,`	null	`],
	[`	O71.0	`,`	Rupture of uterus before onset of labour 	`,`	null	`],
	[`	O71.1	`,`	Rupture of uterus during labour Rupture of uterus not stated as occurring before onset of labour 	`,`	null	`],
	[`	O71.2	`,`	Postpartum inversion of uterus 	`,`	null	`],
	[`	O71.3	`,`	Obstetric laceration of cervix Annular detachment of cervix 	`,`	null	`],
	[`	O71.4	`,`	Obstetric high vaginal laceration Laceration of: middle or upper third of vaginal wall vaginal sulcus Excl.: that of the lower vagina (O70.-) 	`,`	null	`],
	[`	O71.5	`,`	Other obstetric injury to pelvic organs Obstetric injury to: bladder urethra Excl.: (minor) laceration involving periurethral tissue only (O70.0) 	`,`	null	`],
	[`	O71.6	`,`	Obstetric damage to pelvic joints and ligaments Avulsion of inner symphyseal cartilage Damage to coccyx Traumatic separation of symphysis (pubis) obstetric 	`,`	null	`],
	[`	O71.7	`,`	Obstetric haematoma of pelvis Obstetric haematoma of: perineum vagina vulva 	`,`	null	`],
	[`	O71.8	`,`	Other specified obstetric trauma 	`,`	null	`],
	[`	O71.9	`,`	Obstetric trauma, unspecified 	`,`	null	`],
	[`	O72	`,`	Postpartum haemorrhage Incl.: haemorrhage after delivery of fetus or infant 	`,`	null	`],
	[`	O72.0	`,`	Third-stage haemorrhage Haemorrhage associated with retained, trapped or adherent placenta Retained placenta NOS Use additional code, if desired, to identify any morbidly adherent placenta (O43.2) 	`,`	null	`],
	[`	O72.1	`,`	Other immediate postpartum haemorrhage Haemorrhage following delivery of placenta Postpartum haemorrhage (atonic) NOS 	`,`	null	`],
	[`	O72.2	`,`	Delayed and secondary postpartum haemorrhage Haemorrhage associated with retained portions of placenta or membranes Retained products of conception NOS, following delivery 	`,`	null	`],
	[`	O72.3	`,`	Postpartum coagulation defects Postpartum: afibrinogenaemia fibrinolysis 	`,`	null	`],
	[`	O73	`,`	Retained placenta and membranes, without haemorrhage 	`,`	null	`],
	[`	O73.0	`,`	Retained placenta without haemorrhage Use additional code, if desired, to identify any morbidly adherent placenta (O43.2) 	`,`	null	`],
	[`	O73.1	`,`	Retained portions of placenta and membranes, without haemorrhage Retained products of conception following delivery, without haemorrhage 	`,`	null	`],
	[`	O74	`,`	Complications of anaesthesia during labour and delivery Incl.: maternal complications arising from the administration of a general or local anaesthetic, analgesic or other sedation during labour and delivery 	`,`	null	`],
	[`	O74.0	`,`	Aspiration pneumonitis due to anaesthesia during labour and delivery Inhalation of stomach contents or secretions NOS Mendelson syndrome due to anaesthesia during labour and delivery 	`,`	null	`],
	[`	O74.1	`,`	Other pulmonary complications of anaesthesia during labour and delivery Pressure collapse of lung due to anaesthesia during labour and delivery 	`,`	null	`],
	[`	O74.2	`,`	Cardiac complications of anaesthesia during labour and delivery Cardiac: arrest failure due to anaesthesia during labour and delivery 	`,`	null	`],
	[`	O74.3	`,`	Central nervous system complications of anaesthesia during labour and delivery Cerebral anoxia due to anaesthesia during labour and delivery 	`,`	null	`],
	[`	O74.4	`,`	Toxic reaction to local anaesthesia during labour and delivery 	`,`	null	`],
	[`	O74.5	`,`	Spinal and epidural anaesthesia-induced headache during labour and delivery 	`,`	null	`],
	[`	O74.6	`,`	Other complications of spinal and epidural anaesthesia during labour and delivery 	`,`	null	`],
	[`	O74.7	`,`	Failed or difficult intubation during labour and delivery 	`,`	null	`],
	[`	O74.8	`,`	Other complications of anaesthesia during labour and delivery 	`,`	null	`],
	[`	O74.9	`,`	Complication of anaesthesia during labour and delivery, unspecified 	`,`	null	`],
	[`	O75	`,`	Other complications of labour and delivery, not elsewhere classified Excl.: puerperal: infection (O86.-) sepsis (O85) 	`,`	null	`],
	[`	O75.0	`,`	Maternal distress during labour and delivery 	`,`	null	`],
	[`	O75.1	`,`	Shock during or following labour and delivery Obstetric shock 	`,`	null	`],
	[`	O75.2	`,`	Pyrexia during labour, not elsewhere classified 	`,`	null	`],
	[`	O75.3	`,`	Other infection during labour Sepsis during labour 	`,`	null	`],
	[`	O75.4	`,`	Other complications of obstetric surgery and procedures Cardiac: arrest failure Cerebral anoxia following caesarean or other obstetric surgery or procedures, including delivery NOS Excl.: complications of anaesthesia during labour and delivery (O74.-) obstetric (surgical) wound: disruption (O90.0-O90.1) haematoma (O90.2) infection (O86.0) 	`,`	null	`],
	[`	O75.5	`,`	Delayed delivery after artificial rupture of membranes 	`,`	null	`],
	[`	O75.6	`,`	Delayed delivery after spontaneous or unspecified rupture of membranes Excl.: spontaneous premature rupture of membranes (O42.-) 	`,`	null	`],
	[`	O75.7	`,`	Vaginal delivery following previous caesarean section 	`,`	null	`],
	[`	O75.8	`,`	Other specified complications of labour and delivery 	`,`	null	`],
	[`	O75.9	`,`	Complication of labour and delivery, unspecified 	`,`	null	`],
	[`	O80	`,`	Single spontaneous delivery Incl.: cases with minimal or no assistance, with or without episiotomy delivery in a completely normal case 	`,`	null	`],
	[`	O80.0	`,`	Spontaneous vertex delivery 	`,`	null	`],
	[`	O80.1	`,`	Spontaneous breech delivery 	`,`	null	`],
	[`	O80.8	`,`	Other single spontaneous delivery 	`,`	null	`],
	[`	O80.9	`,`	Single spontaneous delivery, unspecified Spontaneous delivery NOS 	`,`	null	`],
	[`	O81	`,`	Single delivery by forceps and vacuum extractor Excl.: failed application of vacuum extractor or forceps (O66.5) 	`,`	null	`],
	[`	O81.0	`,`	Low forceps delivery 	`,`	null	`],
	[`	O81.1	`,`	Mid-cavity forceps delivery 	`,`	null	`],
	[`	O81.2	`,`	Mid-cavity forceps with rotation 	`,`	null	`],
	[`	O81.3	`,`	Other and unspecified forceps delivery 	`,`	null	`],
	[`	O81.4	`,`	Vacuum extractor delivery Ventouse delivery 	`,`	null	`],
	[`	O81.5	`,`	Delivery by combination of forceps and vacuum extractor Forceps and ventouse delivery 	`,`	null	`],
	[`	O82	`,`	Single delivery by caesarean section 	`,`	null	`],
	[`	O82.0	`,`	Delivery by elective caesarean section Repeat caesarean section NOS 	`,`	null	`],
	[`	O82.1	`,`	Delivery by emergency caesarean section 	`,`	null	`],
	[`	O82.2	`,`	Delivery by caesarean hysterectomy 	`,`	null	`],
	[`	O82.8	`,`	Other single delivery by caesarean section 	`,`	null	`],
	[`	O82.9	`,`	Delivery by caesarean section, unspecified 	`,`	null	`],
	[`	O83	`,`	Other assisted single delivery 	`,`	null	`],
	[`	O83.0	`,`	Breech extraction 	`,`	null	`],
	[`	O83.1	`,`	Other assisted breech delivery Breech delivery NOS 	`,`	null	`],
	[`	O83.2	`,`	Other manipulation-assisted delivery Version with extraction 	`,`	null	`],
	[`	O83.3	`,`	Delivery of viable fetus in abdominal pregnancy 	`,`	null	`],
	[`	O83.4	`,`	Destructive operation for delivery Cleidotomy Craniotomy Embryotomy to facilitate delivery 	`,`	null	`],
	[`	O83.8	`,`	Other specified assisted single delivery 	`,`	null	`],
	[`	O83.9	`,`	Assisted single delivery, unspecified Assisted delivery NOS 	`,`	null	`],
	[`	O84	`,`	Multiple delivery Use additional code (O80-O83), if desired, to indicate the method of delivery of each fetus or infant. 	`,`	null	`],
	[`	O84.0	`,`	Multiple delivery, all spontaneous 	`,`	null	`],
	[`	O84.1	`,`	Multiple delivery, all by forceps and vacuum extractor 	`,`	null	`],
	[`	O84.2	`,`	Multiple delivery, all by caesarean section 	`,`	null	`],
	[`	O84.8	`,`	Other multiple delivery Multiple delivery by combination of methods 	`,`	null	`],
	[`	O84.9	`,`	Multiple delivery, unspecified 	`,`	null	`],
	[`	O85	`,`	Puerperal sepsis Incl.: Puerperal: endometritis fever peritonitis sepsis Use additional code (B95-B98) , if desired, to identify infectious agent. Excl.: obstetric pyaemic and septic embolism (O88.3) sepsis during labour (O75.3) 	`,`	null	`],
	[`	O86	`,`	Other puerperal infections Use additional code (B95-B98) , if desired, to identify infectious agent. Excl.: infection during labour (O75.3) 	`,`	null	`],
	[`	O86.0	`,`	Infection of obstetric surgical wound Infected: caesarean section wound perineal repair following delivery 	`,`	null	`],
	[`	O86.1	`,`	Other infection of genital tract following delivery Cervicitis Vaginitis following delivery 	`,`	null	`],
	[`	O86.2	`,`	Urinary tract infection following delivery Conditions in N10-N12, N15.-, N30.-, N34.-, N39.0 following delivery 	`,`	null	`],
	[`	O86.3	`,`	Other genitourinary tract infections following delivery Puerperal genitourinary tract infection NOS 	`,`	null	`],
	[`	O86.4	`,`	Pyrexia of unknown origin following delivery Puerperal: infection NOS pyrexia NOS Excl.: puerperal fever (O85) pyrexia during labour (O75.2) 	`,`	null	`],
	[`	O86.8	`,`	Other specified puerperal infections 	`,`	null	`],
	[`	O87	`,`	Venous complications and haemorrhoids in the puerperium Incl.: in labour, delivery and the puerperium Excl.: obstetric embolism (O88.-) venous complications in pregnancy (O22.-) 	`,`	null	`],
	[`	O87.0	`,`	Superficial thrombophlebitis in the puerperium 	`,`	null	`],
	[`	O87.1	`,`	Deep phlebothrombosis in the puerperium Deep-vein thrombosis, postpartum Pelvic thrombophlebitis, postpartum 	`,`	null	`],
	[`	O87.2	`,`	Haemorrhoids in the puerperium 	`,`	null	`],
	[`	O87.3	`,`	Cerebral venous thrombosis in the puerperium Cerebrovenous sinus thrombosis in the puerperium 	`,`	null	`],
	[`	O87.8	`,`	Other venous complications in the puerperium Genital varices in the puerperium 	`,`	null	`],
	[`	O87.9	`,`	Venous complication in the puerperium, unspecified Puerperal: phlebitis NOS phlebopathy NOS thrombosis NOS 	`,`	null	`],
	[`	O88	`,`	Obstetric embolism Incl.: pulmonary emboli in pregnancy, childbirth or the puerperium Excl.: embolism complicating abortion or ectopic or molar pregnancy (O00-O07, O08.2) 	`,`	null	`],
	[`	O88.0	`,`	Obstetric air embolism 	`,`	null	`],
	[`	O88.1	`,`	Amniotic fluid embolism Anaphylactoid syndrome of pregnancy 	`,`	null	`],
	[`	O88.2	`,`	Obstetric blood-clot embolism Obstetric (pulmonary) embolism NOS Puerperal (pulmonary) embolism NOS 	`,`	null	`],
	[`	O88.3	`,`	Obstetric pyaemic and septic embolism 	`,`	null	`],
	[`	O88.8	`,`	Other obstetric embolism Obstetric fat embolism 	`,`	null	`],
	[`	O89	`,`	Complications of anaesthesia during the puerperium Incl.: maternal complications arising from the administration of a general or local anaesthetic, analgesic or other sedation during the puerperium 	`,`	null	`],
	[`	O89.0	`,`	Pulmonary complications of anaesthesia during the puerperium Aspiration pneumonitis Inhalation of stomach contents or secretions NOS Mendelson syndrome Pressure collapse of lung due to anaesthesia during the puerperium 	`,`	null	`],
	[`	O89.1	`,`	Cardiac complications of anaesthesia during the puerperium Cardiac: arrest failure due to anaesthesia during the puerperium 	`,`	null	`],
	[`	O89.2	`,`	Central nervous system complications of anaesthesia during the puerperium Cerebral anoxia due to anaesthesia during the puerperium 	`,`	null	`],
	[`	O89.3	`,`	Toxic reaction to local anaesthesia during the puerperium 	`,`	null	`],
	[`	O89.4	`,`	Spinal and epidural anaesthesia-induced headache during the puerperium 	`,`	null	`],
	[`	O89.5	`,`	Other complications of spinal and epidural anaesthesia during the puerperium 	`,`	null	`],
	[`	O89.6	`,`	Failed or difficult intubation during the puerperium 	`,`	null	`],
	[`	O89.8	`,`	Other complications of anaesthesia during the puerperium 	`,`	null	`],
	[`	O89.9	`,`	Complication of anaesthesia during the puerperium, unspecified 	`,`	null	`],
	[`	O90	`,`	Complications of the puerperium, not elsewhere classified 	`,`	null	`],
	[`	O90.0	`,`	Disruption of caesarean section wound 	`,`	null	`],
	[`	O90.1	`,`	Disruption of perineal obstetric wound Disruption of wound of: episiotomy perineal laceration Secondary perineal tear 	`,`	null	`],
	[`	O90.2	`,`	Haematoma of obstetric wound 	`,`	null	`],
	[`	O90.3	`,`	Cardiomyopathy in the puerperium Conditions in I42.- 	`,`	null	`],
	[`	O90.4	`,`	Postpartum acute renal failure Hepatorenal syndrome following labour and delivery 	`,`	null	`],
	[`	O90.5	`,`	Postpartum thyroiditis 	`,`	null	`],
	[`	O90.8	`,`	Other complications of the puerperium, not elsewhere classified Placental polyp 	`,`	null	`],
	[`	O90.9	`,`	Complication of the puerperium, unspecified 	`,`	null	`],
	[`	O91	`,`	Infections of breast associated with childbirth Incl.: the listed conditions during pregnancy, the puerperium or lactation 	`,`	null	`],
	[`	O91.0	`,`	Infection of nipple associated with childbirth Abscess of nipple: gestational puerperal 	`,`	null	`],
	[`	O91.1	`,`	Abscess of breast associated with childbirth Mammary abscess Purulent mastitis Subareolar abscess gestational or puerperal 	`,`	null	`],
	[`	O91.2	`,`	Nonpurulent mastitis associated with childbirth Lymphangitis of breast Mastitis: NOS interstitial parenchymatous gestational or puerperal 	`,`	null	`],
	[`	O92	`,`	Other disorders of breast and lactation associated with childbirth Incl.: the listed conditions during pregnancy, the puerperium or lactation 	`,`	null	`],
	[`	O92.0	`,`	Retracted nipple associated with childbirth 	`,`	null	`],
	[`	O92.1	`,`	Cracked nipple associated with childbirth Fissure of nipple, gestational or puerperal 	`,`	null	`],
	[`	O92.2	`,`	Other and unspecified disorders of breast associated with childbirth 	`,`	null	`],
	[`	O92.3	`,`	Agalactia Primary agalactia 	`,`	null	`],
	[`	O92.4	`,`	Hypogalactia 	`,`	null	`],
	[`	O92.5	`,`	Suppressed lactation Agalactia: elective secondary therapeutic 	`,`	null	`],
	[`	O92.6	`,`	Galactorrhoea Excl.: galactorrhoea not associated with childbirth (N64.3) 	`,`	null	`],
	[`	O92.7	`,`	Other and unspecified disorders of lactation Puerperal galactocele 	`,`	null	`],
	[`	94	`,`	Sequelae of complication of pregnancy, childbirth and the puerperium Note: This category is to be used for morbidity coding only to indicate conditions in categories O00-O75 and O85-O92 as the cause of sequelae, which are themselves classified elsewhere. The 'sequelae' include conditions specified as such or as late effects, or those present one year or more after the onset of the causal condition. Not to be used for chronic complications of pregnancy, childbirth and the puerperium. Code these to O00-O75 and O85-O92 . Excl.: that resulting in death (O96.-, O97.-) 	`,`	null	`],
	[`	O95	`,`	Obstetric death of unspecified cause Incl.: Maternal death from unspecified cause occurring during pregnancy, labour and delivery, or the puerperium 	`,`	null	`],
	[`	O96	`,`	Death from any obstetric cause occurring more than 42 days but less than one year after delivery Use additional code, if desired, to identify obstetric cause (direct or indirect) of death. 	`,`	null	`],
	[`	O96.0	`,`	Death from direct obstetric cause 	`,`	null	`],
	[`	O96.1	`,`	Death from indirect obstetric cause 	`,`	null	`],
	[`	O96.9	`,`	Death from unspecified obstetric cause 	`,`	null	`],
	[`	O97	`,`	Death from sequelae of obstetric causes Death from any obstetric cause (direct or indirect) occurring one year or more after delivery Use additional code, if desired, to identify the obstetric cause (direct or indirect) 	`,`	null	`],
	[`	O97.0	`,`	Death from sequelae of direct obstetric cause 	`,`	null	`],
	[`	O97.1	`,`	Death from sequelae of indirect obstetric cause 	`,`	null	`],
	[`	O97.9	`,`	Death from sequelae of obstetric cause, unspecified 	`,`	null	`],
	[`	O98	`,`	Maternal infectious and parasitic diseases classifiable elsewhere but complicating pregnancy, childbirth and the puerperium Incl.: the listed conditions when complicating the pregnant state, when aggravated by the pregnancy, or as a reason for obstetric care Use additional code (Chapter I), if desired, to identify specific condition. Excl.: asymptomatic human immunodeficiency virus [HIV] infection status (Z21) laboratory evidence of human immunodeficiency virus [HIV] (R75) obstetrical tetanus (A34) puerperal: infection (O86.-) sepsis (O85) when the reason for maternal care is that the disease is known or suspected to have affected the fetus (O35-O36) 	`,`	null	`],
	[`	O98.0	`,`	Tuberculosis complicating pregnancy, childbirth and the puerperium Conditions in A15-A19 	`,`	null	`],
	[`	O98.1	`,`	Syphilis complicating pregnancy, childbirth and the puerperium Conditions in A50-A53 	`,`	null	`],
	[`	O98.2	`,`	Gonorrhoea complicating pregnancy, childbirth and the puerperium Conditions in A54.- 	`,`	null	`],
	[`	O98.3	`,`	Other infections with a predominantly sexual mode of transmission complicating pregnancy, childbirth and the puerperium Conditions in A55-A64 	`,`	null	`],
	[`	O98.4	`,`	Viral hepatitis complicating pregnancy, childbirth and the puerperium Conditions in B15-B19 	`,`	null	`],
	[`	O98.5	`,`	Other viral diseases complicating pregnancy, childbirth and the puerperium Conditions in A80-B09, B25-B34 	`,`	null	`],
	[`	O98.6	`,`	Protozoal diseases complicating pregnancy, childbirth and the puerperium Conditions in B50-B64 	`,`	null	`],
	[`	O98.7	`,`	Human immunodeficiency virus [HIV] disease complicating pregnancy, childbirth and the puerperium Conditions in (B20-B24) 	`,`	null	`],
	[`	O98.8	`,`	Other maternal infectious and parasitic diseases complicating pregnancy, childbirth and the puerperium 	`,`	null	`],
	[`	O98.9	`,`	Unspecified maternal infectious or parasitic disease complicating pregnancy, childbirth and the puerperium 	`,`	null	`],
	[`	O99	`,`	Other maternal diseases classifiable elsewhere but complicating pregnancy, childbirth and the puerperium Note: This category includes conditions which complicate the pregnant state, are aggravated by the pregnancy or are a main reason for obstetric care and for which the Alphabetical Index does not indicate a specific rubric in Chapter XV. Use additional code, if desired, to identify specific condition. Excl.: infectious and parasitic diseases (O98.-) injury, poisoning and certain other consequences of external causes (S00-T98) when the reason for maternal care is that the condition is known or suspected to have affected the fetus (O35-O36) 	`,`	null	`],
	[`	O99.0	`,`	Anaemia complicating pregnancy, childbirth and the puerperium Conditions in D50-D64 	`,`	null	`],
	[`	O99.1	`,`	Other diseases of the blood and blood-forming organs and certain disorders involving the immune mechanism complicating pregnancy, childbirth and the puerperium Conditions in D65-D89 Excl.: haemorrhage with coagulation defects (O46.0, O67.0, O72.3) 	`,`	null	`],
	[`	O99.2	`,`	Endocrine, nutritional and metabolic diseases complicating pregnancy, childbirth and the puerperium Conditions in E00-E90 Excl.: diabetes mellitus (O24.-) malnutrition (O25) postpartum thyroiditis (O90.5) 	`,`	null	`],
	[`	O99.3	`,`	Mental disorders and diseases of the nervous system complicating pregnancy, childbirth and the puerperium Conditions in F00-F99 and G00-G99 Excl.: postnatal depression (F53.0) pregnancy-related peripheral neuritis (O26.8) puerperal psychosis (F53.1) 	`,`	null	`],
	[`	O99.4	`,`	Diseases of the circulatory system complicating pregnancy, childbirth and the puerperium Conditions in I00-I99 Excl.: cardiomyopathy in the puerperium (O90.3) hypertensive disorders (O10-O16) obstetric embolism (O88.-) venous complications and cerebrovenous sinus thrombosis in: labour, childbirth and the puerperium (O87.-) pregnancy (O22.-) 	`,`	null	`],
	[`	O99.5	`,`	Diseases of the respiratory system complicating pregnancy, childbirth and the puerperium Conditions in J00-J99 	`,`	null	`],
	[`	O99.6	`,`	Diseases of the digestive system complicating pregnancy, childbirth and the puerperium Conditions in K00-K93 Excl.: haemorrhoids in pregnancy (O22.4) liver disorders in pregnancy, childbirth and the puerperium (O26.6) 	`,`	null	`],
	[`	O99.7	`,`	Diseases of the skin and subcutaneous tissue complicating pregnancy, childbirth and the puerperium Conditions in L00-L99 Excl.: herpes gestationis (O26.4) 	`,`	null	`],
	[`	O99.8	`,`	Other specified diseases and conditions complicating pregnancy, childbirth and the puerperium Combination of conditions classifiable to O99.0-O99.7 Conditions in C00-D48, H00-H95, M00-M99, N00-N99, and Q00-Q99 not elsewhere classified Excl.: genitourinary infections in pregnancy (O23.-) infection of genitourinary tract following delivery (O86.0-O86.3) maternal care for known or suspected abnormality of maternal pelvic organs (O34.-) postpartum acute renal failure (O90.4) postpartum nephritis (O90.8) 	`,`	null	`],
];							
					
							
							
				
	
let CodeRangeO ={
	f0:function(val1=(-1),val2=(0)){
		let Range1 = OCodes.slice(val1,val2);
		Range1.reverse();
		document.documentElement.innerHTML += `<br>Showing O Codes ${Range1.length} items(s)`;

		for(value1 in Range1){
			    document.documentElement.style.cssText += "background-color:tan;";
				document.getElementById('ocodesTR').outerHTML += `<tr><td style="background-color:navy;color:white;width:5%;padding:40px;border:2px solid white;font-weight:900;font-size:40px;text-align:center;">${Range1[value1][0]}</td><td style="background-color:black;color:white;width:90%;padding:20px;border:2px solid white;font-size:30px;">${Range1[value1][1]}</td><td style="background-color:navy;color:white;width:5%;padding:20px;border:2px solid white;font-weight:900;font-size:40px;text-align:center;">${Range1[value1][2]}</td></tr>`;			
		}

	},

};

	






	






