							
let PCodes = [							
	[`		`,`		`,`		`],
	[`	P00	`,`	Fetus and newborn affected by maternal conditions that may be unrelated to present pregnancy Excl.: fetus and newborn affected by: maternal complications of pregnancy (P01.-) maternal endocrine and metabolic disorders (P70-P74) noxious influences transmitted via placenta or breast milk (P04.-) 	`,`	null	`],
	[`	P00.0	`,`	Fetus and newborn affected by maternal hypertensive disorders Fetus or newborn affected by maternal conditions classifiable to O10-O11, O13-O16 	`,`	null	`],
	[`	P00.1	`,`	Fetus and newborn affected by maternal renal and urinary tract diseases Fetus or newborn affected by maternal conditions classifiable to N00-N39 	`,`	null	`],
	[`	P00.2	`,`	Fetus and newborn affected by maternal infectious and parasitic diseases Fetus or newborn affected by maternal infectious disease classifiable to A00-B99 and J09-J11, but not itself manifesting that disease Excl.: infections specific to the perinatal period (P35-P39) maternal genital tract and other localized infections (P00.8) 	`,`	null	`],
	[`	P00.3	`,`	Fetus and newborn affected by other maternal circulatory and respiratory diseases Fetus or newborn affected by maternal conditions classifiable to I00-I99, J00-J99, Q20-Q34 and not included in P00.0, P00.2 	`,`	null	`],
	[`	P00.4	`,`	Fetus and newborn affected by maternal nutritional disorders Fetus or newborn affected by maternal disorders classifiable to E40-E64 Maternal malnutrition NOS 	`,`	null	`],
	[`	P00.5	`,`	Fetus and newborn affected by maternal injury Fetus or newborn affected by maternal conditions classifiable to S00-T79 	`,`	null	`],
	[`	P00.6	`,`	Fetus and newborn affected by surgical procedure on mother Excl.: caesarean section for present delivery (P03.4) damage to placenta from amniocentesis, caesarean section or surgical induction (P02.1) previous surgery to uterus or pelvic organs (P03.8) termination of pregnancy, fetus (P96.4) 	`,`	null	`],
	[`	P00.7	`,`	Fetus and newborn affected by other medical procedures on mother, not elsewhere classified Fetus or newborn affected by radiology on mother Excl.: damage to placenta from amniocentesis, caesarean section or surgical induction (P02.1) fetus or newborn affected by other complications of labour and delivery (P03.-) 	`,`	null	`],
	[`	P00.8	`,`	Fetus and newborn affected by other maternal conditions Fetus or newborn affected by: conditions classifiable to T80-T88 maternal genital tract and other localized infections maternal systemic lupus erythematosus Excl.: transitory neonatal endocrine and metabolic disorders (P70-P74) 	`,`	null	`],
	[`	P00.9	`,`	Fetus and newborn affected by unspecified maternal condition 	`,`	null	`],
	[`	P01	`,`	Fetus and newborn affected by maternal complications of pregnancy 	`,`	null	`],
	[`	P01.0	`,`	Fetus and newborn affected by incompetent cervix 	`,`	null	`],
	[`	P01.1	`,`	Fetus and newborn affected by premature rupture of membranes 	`,`	null	`],
	[`	P01.2	`,`	Fetus and newborn affected by oligohydramnios Excl.: when due to premature rupture of membranes (P01.1) 	`,`	null	`],
	[`	P01.3	`,`	Fetus and newborn affected by polyhydramnios Hydramnios 	`,`	null	`],
	[`	P01.4	`,`	Fetus and newborn affected by ectopic pregnancy Abdominal pregnancy 	`,`	null	`],
	[`	P01.5	`,`	Fetus and newborn affected by multiple pregnancy Triplet (pregnancy) Twin (pregnancy) 	`,`	null	`],
	[`	P01.6	`,`	Fetus and newborn affected by maternal death 	`,`	null	`],
	[`	P01.7	`,`	Fetus and newborn affected by malpresentation before labour Breech presentation External version Face presentation Transverse lie Unstable lie before labour 	`,`	null	`],
	[`	P01.8	`,`	Fetus and newborn affected by other maternal complications of pregnancy Spontaneous abortion, fetus 	`,`	null	`],
	[`	P01.9	`,`	Fetus and newborn affected by maternal complication of pregnancy, unspecified 	`,`	null	`],
	[`	P02	`,`	Fetus and newborn affected by complications of placenta, cord and membranes 	`,`	null	`],
	[`	P02.0	`,`	Fetus and newborn affected by placenta praevia 	`,`	null	`],
	[`	P02.1	`,`	Fetus and newborn affected by other forms of placental separation and haemorrhage Abruptio placentae Accidental haemorrhage Antepartum haemorrhage Damage to placenta from amniocentesis, caesarean section or surgical induction Maternal blood loss Premature separation of placenta 	`,`	null	`],
	[`	P02.2	`,`	Fetus and newborn affected by other and unspecified morphological and functional abnormalities of placenta Placental: dysfunction infarction insufficiency 	`,`	null	`],
	[`	P02.3	`,`	Fetus and newborn affected by placental transfusion syndromes Placental and cord abnormalities resulting in twin-to-twin or other transplacental transfusion Use additional code, if desired, to indicate resultant condition in the fetus or newborn. 	`,`	null	`],
	[`	P02.4	`,`	Fetus and newborn affected by prolapsed cord 	`,`	null	`],
	[`	P02.5	`,`	Fetus and newborn affected by other compression of umbilical cord Cord (tightly) around neck Entanglement of cord Knot in cord 	`,`	null	`],
	[`	P02.6	`,`	Fetus and newborn affected by other and unspecified conditions of umbilical cord Short cord Vasa praevia Excl.: single umbilical artery (Q27.0) 	`,`	null	`],
	[`	P02.7	`,`	Fetus and newborn affected by chorioamnionitis Amnionitis Membranitis Placentitis 	`,`	null	`],
	[`	P02.8	`,`	Fetus and newborn affected by other abnormalities of membranes 	`,`	null	`],
	[`	P02.9	`,`	Fetus and newborn affected by abnormality of membranes, unspecified 	`,`	null	`],
	[`	P03	`,`	Fetus and newborn affected by other complications of labour and delivery 	`,`	null	`],
	[`	P03.0	`,`	Fetus and newborn affected by breech delivery and extraction 	`,`	null	`],
	[`	P03.1	`,`	Fetus and newborn affected by other malpresentation, malposition and disproportion during labour and delivery Contracted pelvis Fetus or newborn affected by conditions classifiable to O64-O66 Persistent occipitoposterior Transverse lie 	`,`	null	`],
	[`	P03.2	`,`	Fetus and newborn affected by forceps delivery 	`,`	null	`],
	[`	P03.3	`,`	Fetus and newborn affected by delivery by vacuum extractor [ventouse] 	`,`	null	`],
	[`	P03.4	`,`	Fetus and newborn affected by caesarean delivery 	`,`	null	`],
	[`	P03.5	`,`	Fetus and newborn affected by precipitate delivery Rapid second stage 	`,`	null	`],
	[`	P03.6	`,`	Fetus and newborn affected by abnormal uterine contractions Fetus or newborn affected by conditions classifiable to O62.-, except O62.3 Hypertonic labour Uterine inertia 	`,`	null	`],
	[`	P03.8	`,`	Fetus and newborn affected by other specified complications of labour and delivery Abnormality of maternal soft tissues Destructive operation to facilitate delivery Fetus or newborn affected by conditions classifiable to O60-O75 and by procedures used in labour and delivery not included in P02.- and P03.0-P03.6 Induction of labour 	`,`	null	`],
	[`	P03.9	`,`	Fetus and newborn affected by complication of labour and delivery, unspecified 	`,`	null	`],
	[`	P04	`,`	Fetus and newborn affected by noxious influences transmitted via placenta or breast milk Incl.: nonteratogenic effects of substances transmitted via placenta Excl.: congenital malformations (Q00-Q99) neonatal jaundice due to drugs or toxins transmitted from mother (P58.4) 	`,`	null	`],
	[`	P04.0	`,`	Fetus and newborn affected by maternal anaesthesia and analgesia in pregnancy, labour and delivery Reactions and intoxications from maternal opiates and tranquillizers administered during labour and delivery 	`,`	null	`],
	[`	P04.1	`,`	Fetus and newborn affected by other maternal medication Cancer chemotherapy Cytotoxic drugs Excl.: dysmorphism due to warfarin (Q86.2) fetal hydantoin syndrome (Q86.1) maternal use of drugs of addiction (P04.4) 	`,`	null	`],
	[`	P04.2	`,`	Fetus and newborn affected by maternal use of tobacco 	`,`	null	`],
	[`	P04.3	`,`	Fetus and newborn affected by maternal use of alcohol Excl.: fetal alcohol syndrome (Q86.0) 	`,`	null	`],
	[`	P04.4	`,`	Fetus and newborn affected by maternal use of drugs of addiction Excl.: maternal anaesthesia and analgesia (P04.0) withdrawal symptoms from maternal use of drugs of addiction (P96.1) 	`,`	null	`],
	[`	P04.5	`,`	Fetus and newborn affected by maternal use of nutritional chemical substances 	`,`	null	`],
	[`	P04.6	`,`	Fetus and newborn affected by maternal exposure to environmental chemical substances 	`,`	null	`],
	[`	P04.8	`,`	Fetus and newborn affected by other maternal noxious influences 	`,`	null	`],
	[`	P04.9	`,`	Fetus and newborn affected by maternal noxious influence, unspecified 	`,`	null	`],
	[`	P05	`,`	Slow fetal growth and fetal malnutrition 	`,`	null	`],
	[`	P05.0	`,`	Light for gestational age Usually referred to as weight below but length above 10th centile for gestational age. Light-for-dates 	`,`	null	`],
	[`	P05.1	`,`	Small for gestational age Usually referred to as weight and length below 10th centile for gestational age. Small-for-dates Small-and-light-for-dates 	`,`	null	`],
	[`	P05.2	`,`	Fetal malnutrition without mention of light or small for gestational age Infant, not light or small for gestational age, showing signs of fetal malnutrition, such as dry, peeling skin and loss of subcutaneous tissue. Excl.: fetal malnutrition with mention of: light for gestational age (P05.0) small for gestational age (P05.1) 	`,`	null	`],
	[`	P05.9	`,`	Slow fetal growth, unspecified Fetal growth retardation NOS 	`,`	null	`],
	[`	P07	`,`	Disorders related to short gestation and low birth weight, not elsewhere classified Note: When both birth weight and gestational age are available, priority of assignment should be given to birth weight. Incl.: the listed conditions, without further specification, as the cause of mortality, morbidity or additional care, in newborn Excl.: low birth weight due to slow fetal growth and fetal malnutrition (P05.-) 	`,`	null	`],
	[`	P07.0	`,`	Extremely low birth weight Birth weight 999 g or less. 	`,`	null	`],
	[`	P07.1	`,`	Other low birth weight Birth weight 1000-2499 g. 	`,`	null	`],
	[`	P07.2	`,`	Extreme immaturity Less than 28 completed weeks (less than 196 completed days) of gestation. 	`,`	null	`],
	[`	P07.3	`,`	Other preterm infants 28 completed weeks or more but less than 37 completed weeks (196 completed days but less than 259 completed days) of gestation. Prematurity NOS 	`,`	null	`],
	[`	P08	`,`	Disorders related to long gestation and high birth weight Note: When both birth weight and gestational age are available, priority of assignment should be given to birth weight. Incl.: the listed conditions, without further specification, as causes of mortality, morbidity or additional care, in fetus or newborn 	`,`	null	`],
	[`	P08.0	`,`	Exceptionally large baby Usually implies a birth weight of 4500 g or more. Excl.: syndrome of: infant of diabetic mother (P70.1) infant of mother with gestational diabetes (P70.0) 	`,`	null	`],
	[`	P08.1	`,`	Other heavy for gestational age infants Usually implies a birth weight >90th percentile for gestational age or 4000 g or more at term Other fetus or infant heavy- or large-for-dates regardless of period of gestation. Excl.: syndrome of infant of: diabetic mother (P70.1) mother with gestational diabetes (P70.0) Birth weight of 4500 g or more (P08.0) 	`,`	null	`],
	[`	P08.2	`,`	Post-term infant, not heavy for gestational age Fetus or infant with gestation period of 42 completed weeks or more (294 days or more), not heavy- or large-for-dates. Postmaturity NOS 	`,`	null	`],
	[`	P10	`,`	Intracranial laceration and haemorrhage due to birth injury Excl.: intracranial haemorrhage of fetus or newborn: NOS (P52.9) due to anoxia or hypoxia (P52.-) 	`,`	null	`],
	[`	P10.0	`,`	Subdural haemorrhage due to birth injury Subdural haematoma (localized) due to birth injury Excl.: subdural haemorrhage accompanying tentorial tear (P10.4) 	`,`	null	`],
	[`	P10.1	`,`	Cerebral haemorrhage due to birth injury 	`,`	null	`],
	[`	P10.2	`,`	Intraventricular haemorrhage due to birth injury 	`,`	null	`],
	[`	P10.3	`,`	Subarachnoid haemorrhage due to birth injury 	`,`	null	`],
	[`	P10.4	`,`	Tentorial tear due to birth injury 	`,`	null	`],
	[`	P10.8	`,`	Other intracranial lacerations and haemorrhages due to birth injury 	`,`	null	`],
	[`	P10.9	`,`	Unspecified intracranial laceration and haemorrhage due to birth injury 	`,`	null	`],
	[`	P11	`,`	Other birth injuries to central nervous system 	`,`	null	`],
	[`	P11.0	`,`	Cerebral oedema due to birth injury 	`,`	null	`],
	[`	P11.1	`,`	Other specified brain damage due to birth injury 	`,`	null	`],
	[`	P11.2	`,`	Unspecified brain damage due to birth injury 	`,`	null	`],
	[`	P11.3	`,`	Birth injury to facial nerve Facial palsy due to birth injury 	`,`	null	`],
	[`	P11.4	`,`	Birth injury to other cranial nerves 	`,`	null	`],
	[`	P11.5	`,`	Birth injury to spine and spinal cord Fracture of spine due to birth injury 	`,`	null	`],
	[`	P11.9	`,`	Birth injury to central nervous system, unspecified 	`,`	null	`],
	[`	P12	`,`	Birth injury to scalp 	`,`	null	`],
	[`	P12.0	`,`	Cephalhaematoma due to birth injury 	`,`	null	`],
	[`	P12.1	`,`	Chignon due to birth injury 	`,`	null	`],
	[`	P12.2	`,`	Epicranial subaponeurotic haemorrhage due to birth injury 	`,`	null	`],
	[`	P12.3	`,`	Bruising of scalp due to birth injury 	`,`	null	`],
	[`	P12.4	`,`	Monitoring injury of scalp of newborn Sampling incision Scalp clip (electrode) injury 	`,`	null	`],
	[`	P12.8	`,`	Other birth injuries to scalp 	`,`	null	`],
	[`	P12.9	`,`	Birth injury to scalp, unspecified 	`,`	null	`],
	[`	P13	`,`	Birth injury to skeleton Excl.: birth injury to spine (P11.5) 	`,`	null	`],
	[`	P13.0	`,`	Fracture of skull due to birth injury 	`,`	null	`],
	[`	P13.1	`,`	Other birth injuries to skull Excl.: cephalhaematoma (P12.0) 	`,`	null	`],
	[`	P13.2	`,`	Birth injury to femur 	`,`	null	`],
	[`	P13.3	`,`	Birth injury to other long bones 	`,`	null	`],
	[`	P13.4	`,`	Fracture of clavicle due to birth injury 	`,`	null	`],
	[`	P13.8	`,`	Birth injuries to other parts of skeleton 	`,`	null	`],
	[`	P13.9	`,`	Birth injury to skeleton, unspecified 	`,`	null	`],
	[`	P14	`,`	Birth injury to peripheral nervous system 	`,`	null	`],
	[`	P14.0	`,`	Erb paralysis due to birth injury 	`,`	null	`],
	[`	P14.1	`,`	Klumpke paralysis due to birth injury 	`,`	null	`],
	[`	P14.2	`,`	Phrenic nerve paralysis due to birth injury 	`,`	null	`],
	[`	P14.3	`,`	Other brachial plexus birth injuries 	`,`	null	`],
	[`	P14.8	`,`	Birth injuries to other parts of peripheral nervous system 	`,`	null	`],
	[`	P14.9	`,`	Birth injury to peripheral nervous system, unspecified 	`,`	null	`],
	[`	P15	`,`	Other birth injuries 	`,`	null	`],
	[`	P15.0	`,`	Birth injury to liver Rupture of liver due to birth injury 	`,`	null	`],
	[`	P15.1	`,`	Birth injury to spleen Rupture of spleen due to birth injury 	`,`	null	`],
	[`	P15.2	`,`	Sternomastoid injury due to birth injury 	`,`	null	`],
	[`	P15.3	`,`	Birth injury to eye Subconjunctival haemorrhage Traumatic glaucoma due to birth injury 	`,`	null	`],
	[`	P15.4	`,`	Birth injury to face Facial congestion due to birth injury 	`,`	null	`],
	[`	P15.5	`,`	Birth injury to external genitalia 	`,`	null	`],
	[`	P15.6	`,`	Subcutaneous fat necrosis due to birth injury 	`,`	null	`],
	[`	P15.8	`,`	Other specified birth injuries 	`,`	null	`],
	[`	P15.9	`,`	Birth injury, unspecified 	`,`	null	`],
	[`	P20	`,`	Intrauterine hypoxia Incl.: abnormal fetal heart rate fetal or intrauterine: acidosis anoxia asphyxia distress hypoxia meconium in liquor passage of meconium Excl.: intracranial haemorrhage due to anoxia or hypoxia (P52.-) 	`,`	null	`],
	[`	P20.0	`,`	Intrauterine hypoxia first noted before onset of labour 	`,`	null	`],
	[`	P20.1	`,`	Intrauterine hypoxia first noted during labour and delivery 	`,`	null	`],
	[`	P20.9	`,`	Intrauterine hypoxia, unspecified 	`,`	null	`],
	[`	P21	`,`	Birth asphyxia Note: This category is not to be used for low Apgar score without mention of asphyxia or other respiratory problems. Excl.: intrauterine hypoxia or asphyxia (P20.-) 	`,`	null	`],
	[`	P21.0	`,`	Severe birth asphyxia Pulse less than 100 per minute at birth and falling or steady, respiration absent or gasping, colour poor, tone absent. Asphyxia with 1-minute Apgar score 0-3 White asphyxia 	`,`	null	`],
	[`	P21.1	`,`	Mild and moderate birth asphyxia Normal respiration not established within one minute, but heart rate 100 or above, some muscle tone present, some response to stimulation. Asphyxia with 1-minute Apgar score 4-7 Blue asphyxia 	`,`	null	`],
	[`	P21.9	`,`	Birth asphyxia, unspecified Anoxia Asphyxia Hypoxia NOS 	`,`	null	`],
	[`	P22	`,`	Respiratory distress of newborn Excl.: respiratory failure of newborn (P28.5) 	`,`	null	`],
	[`	P22.0	`,`	Respiratory distress syndrome of newborn Hyaline membrane disease 	`,`	null	`],
	[`	P22.1	`,`	Transient tachypnoea of newborn 	`,`	null	`],
	[`	P22.8	`,`	Other respiratory distress of newborn 	`,`	null	`],
	[`	P22.9	`,`	Respiratory distress of newborn, unspecified 	`,`	null	`],
	[`	P23	`,`	Congenital pneumonia Incl.: infective pneumonia acquired in utero or during birth Excl.: neonatal pneumonia resulting from aspiration (P24.-) 	`,`	null	`],
	[`	P23.0	`,`	Congenital pneumonia due to viral agent Excl.: congenital rubella pneumonitis (P35.0) 	`,`	null	`],
	[`	P23.1	`,`	Congenital pneumonia due to Chlamydia 	`,`	null	`],
	[`	P23.2	`,`	Congenital pneumonia due to staphylococcus 	`,`	null	`],
	[`	P23.3	`,`	Congenital pneumonia due to streptococcus, group B 	`,`	null	`],
	[`	P23.4	`,`	Congenital pneumonia due to Escherichia coli 	`,`	null	`],
	[`	P23.5	`,`	Congenital pneumonia due to Pseudomonas 	`,`	null	`],
	[`	P23.6	`,`	Congenital pneumonia due to other bacterial agents Haemophilus influenzae Klebsiella pneumoniae Mycoplasma Streptococcus, except group B 	`,`	null	`],
	[`	P23.8	`,`	Congenital pneumonia due to other organisms 	`,`	null	`],
	[`	P23.9	`,`	Congenital pneumonia, unspecified 	`,`	null	`],
	[`	P24	`,`	Neonatal aspiration syndromes Incl.: neonatal pneumonia resulting from aspiration 	`,`	null	`],
	[`	P24.0	`,`	Neonatal aspiration of meconium 	`,`	null	`],
	[`	P24.1	`,`	Neonatal aspiration of amniotic fluid and mucus Aspiration of liquor (amnii) 	`,`	null	`],
	[`	P24.2	`,`	Neonatal aspiration of blood 	`,`	null	`],
	[`	P24.3	`,`	Neonatal aspiration of milk and regurgitated food 	`,`	null	`],
	[`	P24.8	`,`	Other neonatal aspiration syndromes 	`,`	null	`],
	[`	P24.9	`,`	Neonatal aspiration syndrome, unspecified Neonatal aspiration pneumonia NOS 	`,`	null	`],
	[`	P25	`,`	Interstitial emphysema and related conditions originating in the perinatal period 	`,`	null	`],
	[`	P25.0	`,`	Interstitial emphysema originating in the perinatal period 	`,`	null	`],
	[`	P25.1	`,`	Pneumothorax originating in the perinatal period 	`,`	null	`],
	[`	P25.2	`,`	Pneumomediastinum originating in the perinatal period 	`,`	null	`],
	[`	P25.3	`,`	Pneumopericardium originating in the perinatal period 	`,`	null	`],
	[`	P25.8	`,`	Other conditions related to interstitial emphysema originating in the perinatal period 	`,`	null	`],
	[`	P26	`,`	Pulmonary haemorrhage originating in the perinatal period 	`,`	null	`],
	[`	P26.0	`,`	Tracheobronchial haemorrhage originating in the perinatal period 	`,`	null	`],
	[`	P26.1	`,`	Massive pulmonary haemorrhage originating in the perinatal period 	`,`	null	`],
	[`	P26.8	`,`	Other pulmonary haemorrhages originating in the perinatal period 	`,`	null	`],
	[`	P26.9	`,`	Unspecified pulmonary haemorrhage originating in the perinatal period 	`,`	null	`],
	[`	P27	`,`	Chronic respiratory disease originating in the perinatal period 	`,`	null	`],
	[`	P27.0	`,`	Wilson-Mikity syndrome Pulmonary dysmaturity 	`,`	null	`],
	[`	P27.1	`,`	Bronchopulmonary dysplasia originating in the perinatal period 	`,`	null	`],
	[`	P27.8	`,`	Other chronic respiratory diseases originating in the perinatal period Congenital pulmonary fibrosis Ventilator lung in newborn 	`,`	null	`],
	[`	P27.9	`,`	Unspecified chronic respiratory disease originating in the perinatal period 	`,`	null	`],
	[`	P28	`,`	Other respiratory conditions originating in the perinatal period Excl.: congenital malformations of the respiratory system (Q30-Q34) 	`,`	null	`],
	[`	P28.0	`,`	Primary atelectasis of newborn Primary failure to expand terminal respiratory units Pulmonary: hypoplasia associated with short gestation immaturity NOS 	`,`	null	`],
	[`	P28.1	`,`	Other and unspecified atelectasis of newborn Atelectasis: NOS partial secondary Resorption atelectasis without respiratory distress syndrome 	`,`	null	`],
	[`	P28.2	`,`	Cyanotic attacks of newborn Excl.: apnoea of newborn (P28.3-P28.4) 	`,`	null	`],
	[`	P28.3	`,`	Primary sleep apnoea of newborn Sleep apnoea of newborn: central NOS obstructive 	`,`	null	`],
	[`	P28.4	`,`	Other apnoea of newborn Apnoea (of): newborn, obstructive prematurity Excl.: obstructive sleep apnoea of newborn (P28.3) 	`,`	null	`],
	[`	P28.5	`,`	Respiratory failure of newborn 	`,`	null	`],
	[`	P28.8	`,`	Other specified respiratory conditions of newborn Congenital (laryngeal) stridor NOS Snuffles in newborn Excl.: early congenital syphilitic rhinitis (A50.0) 	`,`	null	`],
	[`	P28.9	`,`	Respiratory condition of newborn, unspecified 	`,`	null	`],
	[`	P29	`,`	Cardiovascular disorders originating in the perinatal period Excl.: congenital malformations of the circulatory system (Q20-Q28) 	`,`	null	`],
	[`	P29.0	`,`	Neonatal cardiac failure 	`,`	null	`],
	[`	P29.1	`,`	Neonatal cardiac dysrhythmia 	`,`	null	`],
	[`	P29.2	`,`	Neonatal hypertension 	`,`	null	`],
	[`	P29.3	`,`	Persistent fetal circulation Delayed closure of ductus arteriosus Pulmonary hypertension of newborn (persistent) 	`,`	null	`],
	[`	P29.4	`,`	Transient myocardial ischaemia of newborn 	`,`	null	`],
	[`	P29.8	`,`	Other cardiovascular disorders originating in the perinatal period 	`,`	null	`],
	[`	P29.9	`,`	Cardiovascular disorder originating in the perinatal period, unspecified 	`,`	null	`],
	[`	P35	`,`	Congenital viral diseases 	`,`	null	`],
	[`	P35.0	`,`	Congenital rubella syndrome Congenital rubella pneumonitis 	`,`	null	`],
	[`	P35.1	`,`	Congenital cytomegalovirus infection 	`,`	null	`],
	[`	P35.2	`,`	Congenital herpesviral [herpes simplex] infection 	`,`	null	`],
	[`	P35.3	`,`	Congenital viral hepatitis 	`,`	null	`],
	[`	P35.8	`,`	Other congenital viral diseases Congenital varicella [chickenpox] 	`,`	null	`],
	[`	P35.9	`,`	Congenital viral disease, unspecified 	`,`	null	`],
	[`	P36	`,`	Bacterial sepsis of newborn Incl.: congenital septicaemia 	`,`	null	`],
	[`	P36.0	`,`	Sepsis of newborn due to streptococcus, group B 	`,`	null	`],
	[`	P36.1	`,`	Sepsis of newborn due to other and unspecified streptococci 	`,`	null	`],
	[`	P36.2	`,`	Sepsis of newborn due to Staphylococcus aureus 	`,`	null	`],
	[`	P36.3	`,`	Sepsis of newborn due to other and unspecified staphylococci 	`,`	null	`],
	[`	P36.4	`,`	Sepsis of newborn due to Escherichia coli 	`,`	null	`],
	[`	P36.5	`,`	Sepsis of newborn due to anaerobes 	`,`	null	`],
	[`	P36.8	`,`	Other bacterial sepsis of newborn 	`,`	null	`],
	[`	P36.9	`,`	Bacterial sepsis of newborn, unspecified 	`,`	null	`],
	[`	P37	`,`	Other congenital infectious and parasitic diseases Excl.: congenital syphilis (A50.-) necrotizing enterocolitis of fetus or newborn (P77) neonatal diarrhoea: infectious (A00-A09) noninfective (P78.3) ophthalmia neonatorum due to gonococcus (A54.3) tetanus neonatorum (A33) 	`,`	null	`],
	[`	P37.0	`,`	Congenital tuberculosis 	`,`	null	`],
	[`	P37.1	`,`	Congenital toxoplasmosis Hydrocephalus due to congenital toxoplasmosis 	`,`	null	`],
	[`	P37.2	`,`	Neonatal (disseminated) listeriosis 	`,`	null	`],
	[`	P37.3	`,`	Congenital falciparum malaria 	`,`	null	`],
	[`	P37.4	`,`	Other congenital malaria 	`,`	null	`],
	[`	P37.5	`,`	Neonatal candidiasis 	`,`	null	`],
	[`	P37.8	`,`	Other specified congenital infectious and parasitic diseases 	`,`	null	`],
	[`	P37.9	`,`	Congenital infectious and parasitic disease, unspecified 	`,`	null	`],
	[`	P38	`,`	Omphalitis of newborn with or without mild haemorrhage 	`,`	null	`],
	[`	P39	`,`	Other infections specific to the perinatal period 	`,`	null	`],
	[`	P39.0	`,`	Neonatal infective mastitis Excl.: breast engorgement of newborn (P83.4) noninfective mastitis of newborn (P83.4) 	`,`	null	`],
	[`	P39.1	`,`	Neonatal conjunctivitis and dacryocystitis Neonatal chlamydial conjunctivitis Ophthalmia neonatorum NOS Excl.: gonococcal conjunctivitis (A54.3) 	`,`	null	`],
	[`	P39.2	`,`	Intra-amniotic infection of fetus, not elsewhere classified 	`,`	null	`],
	[`	P39.3	`,`	Neonatal urinary tract infection 	`,`	null	`],
	[`	P39.4	`,`	Neonatal skin infection Neonatal pyoderma Excl.: pemphigus neonatorum (L00) staphylococcal scalded skin syndrome (L00) 	`,`	null	`],
	[`	P39.8	`,`	Other specified infections specific to the perinatal period 	`,`	null	`],
	[`	P39.9	`,`	Infection specific to the perinatal period, unspecified 	`,`	null	`],
	[`	P50	`,`	Fetal blood loss Excl.: congenital anaemia from fetal blood loss (P61.3) 	`,`	null	`],
	[`	P50.0	`,`	Fetal blood loss from vasa praevia 	`,`	null	`],
	[`	P50.1	`,`	Fetal blood loss from ruptured cord P50.2 Fetal blood loss from placenta 	`,`	null	`],
	[`	P50.3	`,`	Haemorrhage into co-twin 	`,`	null	`],
	[`	P50.4	`,`	Haemorrhage into maternal circulation 	`,`	null	`],
	[`	P50.5	`,`	Fetal blood loss from cut end of co-twin's cord 	`,`	null	`],
	[`	P50.8	`,`	Other fetal blood loss 	`,`	null	`],
	[`	P50.9	`,`	Fetal blood loss, unspecified Fetal haemorrhage NOS 	`,`	null	`],
	[`	P51	`,`	Umbilical haemorrhage of newborn Excl.: omphalitis with mild haemorrhage (P38) 	`,`	null	`],
	[`	P51.0	`,`	Massive umbilical haemorrhage of newborn 	`,`	null	`],
	[`	P51.8	`,`	Other umbilical haemorrhages of newborn Slipped umbilical ligature NOS 	`,`	null	`],
	[`	P51.9	`,`	Umbilical haemorrhage of newborn, unspecified 	`,`	null	`],
	[`	P52	`,`	Intracranial nontraumatic haemorrhage of fetus and newborn Incl.: intracranial haemorrhage due to anoxia or hypoxia Excl.: intracranial haemorrhage due to injury: birth (P10.-) maternal (P00.5) other (S06.-) 	`,`	null	`],
	[`	P52.0	`,`	Intraventricular (nontraumatic) haemorrhage, grade 1, of fetus and newborn Subependymal haemorrhage (without intraventricular extension) 	`,`	null	`],
	[`	P52.1	`,`	Intraventricular (nontraumatic) haemorrhage, grade 2, of fetus and newborn Subependymal haemorrhage with intraventricular extension 	`,`	null	`],
	[`	P52.2	`,`	Intraventricular (nontraumatic) haemorrhage, grade 3, and grade 4 of fetus and newborn Subependymal haemorrhage with both intraventricular and intracerebral extension 	`,`	null	`],
	[`	P52.3	`,`	Unspecified intraventricular (nontraumatic) haemorrhage of fetus and newborn 	`,`	null	`],
	[`	P52.4	`,`	Intracerebral (nontraumatic) haemorrhage of fetus and newborn 	`,`	null	`],
	[`	P52.5	`,`	Subarachnoid (nontraumatic) haemorrhage of fetus and newborn 	`,`	null	`],
	[`	P52.6	`,`	Cerebellar (nontraumatic) and posterior fossa haemorrhage of fetus and newborn 	`,`	null	`],
	[`	P52.8	`,`	Other intracranial (nontraumatic) haemorrhages of fetus and newborn 	`,`	null	`],
	[`	P52.9	`,`	Intracranial (nontraumatic) haemorrhage of fetus and newborn, unspecified 	`,`	null	`],
	[`	P53	`,`	Haemorrhagic disease of fetus and newborn Incl.: Vitamin K deficiency of newborn 	`,`	null	`],
	[`	P54	`,`	Other neonatal haemorrhages Excl.: fetal blood loss (P50.-) pulmonary haemorrhage originating in the perinatal period (P26.-) 	`,`	null	`],
	[`	P54.0	`,`	Neonatal haematemesis Excl.: that due to swallowed maternal blood (P78.2) 	`,`	null	`],
	[`	P54.1	`,`	Neonatal melaena Excl.: that due to swallowed maternal blood (P78.2) 	`,`	null	`],
	[`	P54.2	`,`	Neonatal rectal haemorrhage 	`,`	null	`],
	[`	P54.3	`,`	Other neonatal gastrointestinal haemorrhage 	`,`	null	`],
	[`	P54.4	`,`	Neonatal adrenal haemorrhage 	`,`	null	`],
	[`	P54.5	`,`	Neonatal cutaneous haemorrhage Bruising Ecchymoses Petechiae Superficial haematomata in fetus or newborn Excl.: bruising of scalp due to birth injury (P12.3) cephalhaematoma due to birth injury (P12.0) 	`,`	null	`],
	[`	P54.6	`,`	Neonatal vaginal haemorrhage Pseudomenses 	`,`	null	`],
	[`	P54.8	`,`	Other specified neonatal haemorrhages 	`,`	null	`],
	[`	P54.9	`,`	Neonatal haemorrhage, unspecified 	`,`	null	`],
	[`	P55	`,`	Haemolytic disease of fetus and newborn 	`,`	null	`],
	[`	P55.0	`,`	Rh isoimmunization of fetus and newborn 	`,`	null	`],
	[`	P55.1	`,`	ABO isoimmunization of fetus and newborn 	`,`	null	`],
	[`	P55.8	`,`	Other haemolytic diseases of fetus and newborn 	`,`	null	`],
	[`	P55.9	`,`	Haemolytic disease of fetus and newborn, unspecified 	`,`	null	`],
	[`	P56	`,`	Hydrops fetalis due to haemolytic disease Excl.: hydrops fetalis NOS (P83.2) hydrops fetalis NOS not due to haemolytic disease (P83.2) 	`,`	null	`],
	[`	P56.0	`,`	Hydrops fetalis due to isoimmunization 	`,`	null	`],
	[`	P56.9	`,`	Hydrops fetalis due to other and unspecified haemolytic disease 	`,`	null	`],
	[`	P57	`,`	Kernicterus 	`,`	null	`],
	[`	P57.0	`,`	Kernicterus due to isoimmunization 	`,`	null	`],
	[`	P57.8	`,`	Other specified kernicterus Excl.: Crigler-Najjar syndrome (E80.5) 	`,`	null	`],
	[`	P57.9	`,`	Kernicterus, unspecified 	`,`	null	`],
	[`	P58	`,`	Neonatal jaundice due to other excessive haemolysis Excl.: jaundice due to isoimmunization (P55-P57) 	`,`	null	`],
	[`	P58.0	`,`	Neonatal jaundice due to bruising 	`,`	null	`],
	[`	P58.1	`,`	Neonatal jaundice due to bleeding 	`,`	null	`],
	[`	P58.2	`,`	Neonatal jaundice due to infection 	`,`	null	`],
	[`	P58.3	`,`	Neonatal jaundice due to polycythaemia 	`,`	null	`],
	[`	P58.4	`,`	Neonatal jaundice due to drugs or toxins transmitted from mother or given to newborn Use additional external cause code (Chapter XX), if desired, to identify drug, if drug-induced. 	`,`	null	`],
	[`	P58.5	`,`	Neonatal jaundice due to swallowed maternal blood 	`,`	null	`],
	[`	P58.8	`,`	Neonatal jaundice due to other specified excessive haemolysis 	`,`	null	`],
	[`	P58.9	`,`	Neonatal jaundice due to excessive haemolysis, unspecified 	`,`	null	`],
	[`	P59	`,`	Neonatal jaundice from other and unspecified causes Excl.: due to inborn errors of metabolism (E70-E90) kernicterus (P57.-) 	`,`	null	`],
	[`	P59.0	`,`	Neonatal jaundice associated with preterm delivery Hyperbilirubinaemia of prematurity Jaundice due to delayed conjugation associated with preterm delivery 	`,`	null	`],
	[`	P59.1	`,`	Inspissated bile syndrome 	`,`	null	`],
	[`	P59.2	`,`	Neonatal jaundice from other and unspecified hepatocellular damage Fetal or neonatal giant cell hepatitis Fetal or neonatal (idiopathic) hepatitis Excl.: congenital viral hepatitis (P35.3) 	`,`	null	`],
	[`	P59.3	`,`	Neonatal jaundice from breast milk inhibitor 	`,`	null	`],
	[`	P59.8	`,`	Neonatal jaundice from other specified causes 	`,`	null	`],
	[`	P59.9	`,`	Neonatal jaundice, unspecified Physiological jaundice (intense)(prolonged) NOS 	`,`	null	`],
	[`	P60	`,`	Disseminated intravascular coagulation of fetus and newborn Incl.: Defibrination syndrome of fetus or newborn 	`,`	null	`],
	[`	P61	`,`	Other perinatal haematological disorders Excl.: transient hypogammaglobulinaemia of infancy (D80.7) 	`,`	null	`],
	[`	P61.0	`,`	Transient neonatal thrombocytopenia Neonatal thrombocytopenia due to: exchange transfusion idiopathic maternal thrombocytopenia isoimmunization 	`,`	null	`],
	[`	P61.1	`,`	Polycythaemia neonatorum 	`,`	null	`],
	[`	P61.2	`,`	Anaemia of prematurity 	`,`	null	`],
	[`	P61.3	`,`	Congenital anaemia from fetal blood loss 	`,`	null	`],
	[`	P61.4	`,`	Other congenital anaemias, not elsewhere classified Congenital anaemia NOS 	`,`	null	`],
	[`	P61.5	`,`	Transient neonatal neutropenia 	`,`	null	`],
	[`	P61.6	`,`	Other transient neonatal disorders of coagulation 	`,`	null	`],
	[`	P61.8	`,`	Other specified perinatal haematological disorders 	`,`	null	`],
	[`	P61.9	`,`	Perinatal haematological disorder, unspecified 	`,`	null	`],
	[`	P70	`,`	Transitory disorders of carbohydrate metabolism specific to fetus and newborn 	`,`	null	`],
	[`	P70.0	`,`	Syndrome of infant of mother with gestational diabetes Fetus or newborn (with hypoglycaemia) affected by maternal gestational diabetes 	`,`	null	`],
	[`	P70.1	`,`	Syndrome of infant of a diabetic mother Fetus or newborn (with hypoglycaemia) affected by maternal diabetes mellitus (pre-existing) 	`,`	null	`],
	[`	P70.2	`,`	Neonatal diabetes mellitus 	`,`	null	`],
	[`	P70.3	`,`	Iatrogenic neonatal hypoglycaemia 	`,`	null	`],
	[`	P70.4	`,`	Other neonatal hypoglycaemia Transitory neonatal hypoglycaemia 	`,`	null	`],
	[`	P70.8	`,`	Other transitory disorders of carbohydrate metabolism of fetus and newborn 	`,`	null	`],
	[`	P70.9	`,`	Transitory disorder of carbohydrate metabolism of fetus and newborn, unspecified 	`,`	null	`],
	[`	P71	`,`	Transitory neonatal disorders of calcium and magnesium metabolism 	`,`	null	`],
	[`	P71.0	`,`	Cow milk hypocalcaemia in newborn 	`,`	null	`],
	[`	P71.1	`,`	Other neonatal hypocalcaemia Excl.: neonatal hypoparathyroidism (P71.4) 	`,`	null	`],
	[`	P71.2	`,`	Neonatal hypomagnesaemia 	`,`	null	`],
	[`	P71.3	`,`	Neonatal tetany without calcium or magnesium deficiency Neonatal tetany NOS 	`,`	null	`],
	[`	P71.4	`,`	Transitory neonatal hypoparathyroidism 	`,`	null	`],
	[`	P71.8	`,`	Other transitory neonatal disorders of calcium and magnesium metabolism 	`,`	null	`],
	[`	P71.9	`,`	Transitory neonatal disorder of calcium and magnesium metabolism, unspecified 	`,`	null	`],
	[`	P72	`,`	Other transitory neonatal endocrine disorders Excl.: congenital hypothyroidism with or without goitre (E03.0-E03.1) dyshormogenetic goitre (E07.1) Pendred syndrome (E07.1) 	`,`	null	`],
	[`	P72.0	`,`	Neonatal goitre, not elsewhere classified Transitory congenital goitre with normal function 	`,`	null	`],
	[`	P72.1	`,`	Transitory neonatal hyperthyroidism Neonatal thyrotoxicosis 	`,`	null	`],
	[`	P72.2	`,`	Other transitory neonatal disorders of thyroid function, not elsewhere classified Transitory neonatal hypothyroidism 	`,`	null	`],
	[`	P72.8	`,`	Other specified transitory neonatal endocrine disorders 	`,`	null	`],
	[`	P72.9	`,`	Transitory neonatal endocrine disorder, unspecified 	`,`	null	`],
	[`	P74	`,`	Other transitory neonatal electrolyte and metabolic disturbances 	`,`	null	`],
	[`	P74.0	`,`	Late metabolic acidosis of newborn 	`,`	null	`],
	[`	P74.1	`,`	Dehydration of newborn 	`,`	null	`],
	[`	P74.2	`,`	Disturbances of sodium balance of newborn 	`,`	null	`],
	[`	P74.3	`,`	Disturbances of potassium balance of newborn 	`,`	null	`],
	[`	P74.4	`,`	Other transitory electrolyte disturbances of newborn 	`,`	null	`],
	[`	P74.5	`,`	Transitory tyrosinaemia of newborn 	`,`	null	`],
	[`	P74.8	`,`	Other transitory metabolic disturbances of newborn 	`,`	null	`],
	[`	P74.9	`,`	Transitory metabolic disturbance of newborn, unspecified 	`,`	null	`],
	[`	P75*	`,`	Meconium ileus in cystic fibrosis (E84.1) 	`,`	null	`],
	[`	P76	`,`	Other intestinal obstruction of newborn 	`,`	null	`],
	[`	P76.0	`,`	Meconium plug syndrome Meconium ileus in cases where cystic fibrosis is known not to be present. 	`,`	null	`],
	[`	P76.1	`,`	Transitory ileus of newborn Excl.: Hirschsprung disease (Q43.1) 	`,`	null	`],
	[`	P76.2	`,`	Intestinal obstruction due to inspissated milk 	`,`	null	`],
	[`	P76.8	`,`	Other specified intestinal obstruction of newborn Excl.: intestinal obstruction classifiable to K56.0-K56.5 	`,`	null	`],
	[`	P76.9	`,`	Intestinal obstruction of newborn, unspecified 	`,`	null	`],
	[`	P77	`,`	Necrotizing enterocolitis of fetus and newborn 	`,`	null	`],
	[`	P78	`,`	Other perinatal digestive system disorders Excl.: neonatal gastrointestinal haemorrhages (P54.0-P54.3) 	`,`	null	`],
	[`	P78.0	`,`	Perinatal intestinal perforation Meconium peritonitis 	`,`	null	`],
	[`	P78.1	`,`	Other neonatal peritonitis Neonatal peritonitis NOS 	`,`	null	`],
	[`	P78.2	`,`	Neonatal haematemesis and melaena due to swallowed maternal blood 	`,`	null	`],
	[`	P78.3	`,`	Noninfective neonatal diarrhoea Neonatal diarrhoea NOS Excl.: neonatal diarrhoea NOS in countries where the condition can be presumed to be of infectious origin (A09.-) 	`,`	null	`],
	[`	P78.8	`,`	Other specified perinatal digestive system disorders Congenital cirrhosis (of liver) Neonatal oesophageal reflux Peptic ulcer of newborn 	`,`	null	`],
	[`	P78.9	`,`	Perinatal digestive system disorder, unspecified 	`,`	null	`],
	[`	P80	`,`	Hypothermia of newborn 	`,`	null	`],
	[`	P80.0	`,`	Cold injury syndrome Severe and usually chronic hypothermia associated with a pink flushed appearance, oedema and neurological and biochemical abnormalities. Excl.: mild hypothermia of newborn (P80.8) 	`,`	null	`],
	[`	P80.8	`,`	Other hypothermia of newborn Mild hypothermia of newborn 	`,`	null	`],
	[`	P80.9	`,`	Hypothermia of newborn, unspecified 	`,`	null	`],
	[`	P81	`,`	Other disturbances of temperature regulation of newborn 	`,`	null	`],
	[`	P81.0	`,`	Environmental hyperthermia of newborn 	`,`	null	`],
	[`	P81.8	`,`	Other specified disturbances of temperature regulation of newborn 	`,`	null	`],
	[`	P81.9	`,`	Disturbance of temperature regulation of newborn, unspecified Fever of newborn NOS 	`,`	null	`],
	[`	P83	`,`	Other conditions of integument specific to fetus and newborn Excl.: congenital malformations of skin and integument (Q80-Q84) cradle cap (L21.0) diaper [napkin] dermatitis (L22) hydrops fetalis due to haemolytic disease (P56.-) neonatal skin infection (P39.4) staphylococcal scalded skin syndrome (L00) 	`,`	null	`],
	[`	P83.0	`,`	Sclerema neonatorum 	`,`	null	`],
	[`	P83.1	`,`	Neonatal erythema toxicum 	`,`	null	`],
	[`	P83.2	`,`	Hydrops fetalis not due to haemolytic disease Hydrops fetalis NOS 	`,`	null	`],
	[`	P83.3	`,`	Other and unspecified oedema specific to fetus and newborn 	`,`	null	`],
	[`	P83.4	`,`	Breast engorgement of newborn Noninfective mastitis of newborn 	`,`	null	`],
	[`	P83.5	`,`	Congenital hydrocele 	`,`	null	`],
	[`	P83.6	`,`	Umbilical polyp of newborn 	`,`	null	`],
	[`	P83.8	`,`	Other specified conditions of integument specific to fetus and newborn Bronze baby syndrome Neonatal scleroderma Urticaria neonatorum 	`,`	null	`],
	[`	P83.9	`,`	Condition of integument specific to fetus and newborn, unspecified 	`,`	null	`],
							
];							
							
						
							
							
				
	
let CodeRangeP ={
	f0:function(val1=(-1),val2=(0)){
		let Range1 = PCodes.slice(val1,val2);
		Range1.reverse();
		document.documentElement.innerHTML += `<br>Showing P Codes ${Range1.length} items(s)`;

		for(value1 in Range1){
			    document.documentElement.style.cssText += "background-color:tan;";
				document.getElementById('pcodesTR').outerHTML += `<tr><td style="background-color:navy;color:white;width:5%;padding:40px;border:2px solid white;font-weight:900;font-size:40px;text-align:center;">${Range1[value1][0]}</td><td style="background-color:black;color:white;width:90%;padding:20px;border:2px solid white;font-size:30px;">${Range1[value1][1]}</td><td style="background-color:navy;color:white;width:5%;padding:20px;border:2px solid white;font-weight:900;font-size:40px;text-align:center;">${Range1[value1][2]}</td></tr>`;			
		}

	},

};

	






	






