							
let QCodes = [							
	[`		`,`		`,`		`],
	[`	Q00	`,`	Anencephaly and similar malformations 	`,`	null	`],
	[`	Q00.0	`,`	Anencephaly Acephaly Acrania Amyelencephaly Hemianencephaly Hemicephaly 	`,`	null	`],
	[`	Q00.1	`,`	Craniorachischisis 	`,`	null	`],
	[`	Q00.2	`,`	Iniencephaly 	`,`	null	`],
	[`	Q01	`,`	Encephalocele Incl.: encephalomyelocele hydroencephalocele hydromeningocele, cranial meningocele, cerebral meningoencephalocele Excl.: Meckel-Gruber syndrome (Q61.9) 	`,`	null	`],
	[`	Q01.0	`,`	Frontal encephalocele 	`,`	null	`],
	[`	Q01.1	`,`	Nasofrontal encephalocele 	`,`	null	`],
	[`	Q01.2	`,`	Occipital encephalocele 	`,`	null	`],
	[`	Q01.8	`,`	Encephalocele of other sites 	`,`	null	`],
	[`	Q01.9	`,`	Encephalocele, unspecified 	`,`	null	`],
	[`	Q02	`,`	Microcephaly Incl.: Hydromicrocephaly Micrencephalon Excl.: Meckel-Gruber syndrome (Q61.9) 	`,`	null	`],
	[`	Q03	`,`	Congenital hydrocephalus Incl.: hydrocephalus in newborn Excl.: Arnold-Chiari syndrome (Q07.0) hydrocephalus: acquired (G91.-) due to congenital toxoplasmosis (P37.1) with spina bifida (Q05.0-Q05.4) 	`,`	null	`],
	[`	Q03.0	`,`	Malformations of aqueduct of Sylvius Aqueduct of Sylvius: anomaly obstruction, congenital stenosis 	`,`	null	`],
	[`	Q03.1	`,`	Atresia of foramina of Magendie and Luschka Dandy-Walker syndrome 	`,`	null	`],
	[`	Q03.8	`,`	Other congenital hydrocephalus 	`,`	null	`],
	[`	Q03.9	`,`	Congenital hydrocephalus, unspecified 	`,`	null	`],
	[`	Q04	`,`	Other congenital malformations of brain Excl.: cyclopia (Q87.0) macrocephaly (Q75.3) 	`,`	null	`],
	[`	Q04.0	`,`	Congenital malformations of corpus callosum Agenesis of corpus callosum 	`,`	null	`],
	[`	Q04.1	`,`	Arhinencephaly 	`,`	null	`],
	[`	Q04.2	`,`	Holoprosencephaly 	`,`	null	`],
	[`	Q04.3	`,`	Other reduction deformities of brain Absence Agenesis Aplasia Hypoplasia of part of brain Agyria Hydranencephaly Lissencephaly Microgyria Pachygyria Excl.: congenital malformations of corpus callosum (Q04.0) 	`,`	null	`],
	[`	Q04.4	`,`	Septo-optic dysplasia 	`,`	null	`],
	[`	Q04.5	`,`	Megalencephaly 	`,`	null	`],
	[`	Q04.6	`,`	Congenital cerebral cysts Porencephaly Schizencephaly Excl.: acquired porencephalic cyst (G93.0) 	`,`	null	`],
	[`	Q04.8	`,`	Other specified congenital malformations of brain Macrogyria 	`,`	null	`],
	[`	Q04.9	`,`	Congenital malformation of brain, unspecified Congenital: anomaly deformity disease or lesion multiple anomalies NOS of brain 	`,`	null	`],
	[`	Q05	`,`	Spina bifida Incl.: hydromeningocele (spinal) meningocele (spinal) meningomyelocele myelocele myelomeningocele rachischisis spina bifida (aperta)(cystica) syringomyelocele Excl.: Arnold-Chiari syndrome (Q07.0) spina bifida occulta (Q76.0) 	`,`	null	`],
	[`	Q05.0	`,`	Cervical spina bifida with hydrocephalus 	`,`	null	`],
	[`	Q05.1	`,`	Thoracic spina bifida with hydrocephalus Spina bifida: dorsal thoracolumbar with hydrocephalus 	`,`	null	`],
	[`	Q05.2	`,`	Lumbar spina bifida with hydrocephalus Lumbosacral spina bifida with hydrocephalus 	`,`	null	`],
	[`	Q05.3	`,`	Sacral spina bifida with hydrocephalus 	`,`	null	`],
	[`	Q05.4	`,`	Unspecified spina bifida with hydrocephalus 	`,`	null	`],
	[`	Q05.5	`,`	Cervical spina bifida without hydrocephalus 	`,`	null	`],
	[`	Q05.6	`,`	Thoracic spina bifida without hydrocephalus Spina bifida: dorsal NOS thoracolumbar NOS 	`,`	null	`],
	[`	Q05.7	`,`	Lumbar spina bifida without hydrocephalus Lumbosacral spina bifida NOS 	`,`	null	`],
	[`	Q05.8	`,`	Sacral spina bifida without hydrocephalus 	`,`	null	`],
	[`	Q05.9	`,`	Spina bifida, unspecified 	`,`	null	`],
	[`	Q06	`,`	Other congenital malformations of spinal cord 	`,`	null	`],
	[`	Q06.0	`,`	Amyelia 	`,`	null	`],
	[`	Q06.1	`,`	Hypoplasia and dysplasia of spinal cord Atelomyelia Myelatelia Myelodysplasia of spinal cord 	`,`	null	`],
	[`	Q06.2	`,`	Diastematomyelia 	`,`	null	`],
	[`	Q06.3	`,`	Other congenital cauda equina malformations 	`,`	null	`],
	[`	Q06.4	`,`	Hydromyelia Hydrorachis 	`,`	null	`],
	[`	Q06.8	`,`	Other specified congenital malformations of spinal cord 	`,`	null	`],
	[`	Q06.9	`,`	Congenital malformation of spinal cord, unspecified Congenital: anomaly deformity disease or lesion NOS of spinal cord or meninges 	`,`	null	`],
	[`	Q07	`,`	Other congenital malformations of nervous system Excl.: familial dysautonomia [Riley-Day] (G90.1) neurofibromatosis (nonmalignant) (Q85.0) 	`,`	null	`],
	[`	Q07.0	`,`	Arnold-Chiari syndrome 	`,`	null	`],
	[`	Q07.8	`,`	Other specified congenital malformations of nervous system Agenesis of nerve Displacement of brachial plexus Jaw-winking syndrome Marcus Gunn syndrome 	`,`	null	`],
	[`	Q07.9	`,`	Congenital malformation of nervous system, unspecified Congenital: anomaly deformity disease or lesion NOS of nervous system 	`,`	null	`],
	[`	Q10	`,`	Congenital malformations of eyelid, lacrimal apparatus and orbit Excl.: cryptophthalmos: NOS (Q11.2) syndrome (Q87.0) 	`,`	null	`],
	[`	Q10.0	`,`	Congenital ptosis 	`,`	null	`],
	[`	Q10.1	`,`	Congenital ectropion 	`,`	null	`],
	[`	Q10.2	`,`	Congenital entropion 	`,`	null	`],
	[`	Q10.3	`,`	Other congenital malformations of eyelid Ablepharon Absence or agenesis of: cilia eyelid Accessory: eye muscle Blepharophimosis, congenital Coloboma of eyelid Congenital malformation of eyelid NOS 	`,`	null	`],
	[`	Q10.4	`,`	Absence and agenesis of lacrimal apparatus Absence of punctum lacrimale 	`,`	null	`],
	[`	Q10.5 	`,`	Congenital stenosis and stricture of lacrimal duct 	`,`	null	`],
	[`	Q10.6	`,`	Other congenital malformations of lacrimal apparatus Congenital malformation of lacrimal apparatus NOS 	`,`	null	`],
	[`	Q10.7	`,`	Congenital malformation of orbit 	`,`	null	`],
	[`	Q11	`,`	Anophthalmos, microphthalmos and macrophthalmos 	`,`	null	`],
	[`	Q11.0	`,`	Cystic eyeball 	`,`	null	`],
	[`	Q11.1	`,`	Other anophthalmos Agenesis Aplasia of eye 	`,`	null	`],
	[`	Q11.2	`,`	Microphthalmos Cryptophthalmos NOS Dysplasia of eye Hypoplasia of eye Rudimentary eye Excl.: cryptophthalmos syndrome (Q87.0) 	`,`	null	`],
	[`	Q11.3	`,`	Macrophthalmos Excl.: macrophthalmos in congenital glaucoma (Q15.0) 	`,`	null	`],
	[`	Q12	`,`	Congenital lens malformations 	`,`	null	`],
	[`	Q12.0	`,`	Congenital cataract 	`,`	null	`],
	[`	Q12.1	`,`	Congenital displaced lens 	`,`	null	`],
	[`	Q12.2	`,`	Coloboma of lens 	`,`	null	`],
	[`	Q12.3	`,`	Congenital aphakia 	`,`	null	`],
	[`	Q12.4	`,`	Spherophakia 	`,`	null	`],
	[`	Q12.8	`,`	Other congenital lens malformations 	`,`	null	`],
	[`	Q12.9	`,`	Congenital lens malformation, unspecified 	`,`	null	`],
	[`	Q13	`,`	Congenital malformations of anterior segment of eye Q13.0 Coloboma of iris Coloboma NOS 	`,`	null	`],
	[`	Q13.1	`,`	Absence of iris Aniridia 	`,`	null	`],
	[`	Q13.2	`,`	Other congenital malformations of iris Anisocoria, congenital Atresia of pupil Congenital malformation of iris NOS Corectopia 	`,`	null	`],
	[`	Q13.3	`,`	Congenital corneal opacity 	`,`	null	`],
	[`	Q13.4	`,`	Other congenital corneal malformations Congenital malformation of cornea NOS Microcornea Peter anomaly 	`,`	null	`],
	[`	Q13.5	`,`	Blue sclera 	`,`	null	`],
	[`	Q13.8	`,`	Other congenital malformations of anterior segment of eye Rieger anomaly 	`,`	null	`],
	[`	Q13.9	`,`	Congenital malformation of anterior segment of eye, unspecified 	`,`	null	`],
	[`	Q14	`,`	Congenital malformations of posterior segment of eye 	`,`	null	`],
	[`	Q14.0	`,`	Congenital malformation of vitreous humour Congenital vitreous opacity 	`,`	null	`],
	[`	Q14.1	`,`	Congenital malformation of retina Congenital retinal aneurysm 	`,`	null	`],
	[`	Q14.2	`,`	Congenital malformation of optic disc Coloboma of optic disc 	`,`	null	`],
	[`	Q14.3	`,`	Congenital malformation of choroid 	`,`	null	`],
	[`	Q14.8	`,`	Other congenital malformations of posterior segment of eye Coloboma of the fundus 	`,`	null	`],
	[`	Q14.9	`,`	Congenital malformation of posterior segment of eye, unspecified 	`,`	null	`],
	[`	Q15	`,`	Other congenital malformations of eye Excl.: congenital nystagmus (H55) ocular albinism (E70.3) retinitis pigmentosa (H35.5) 	`,`	null	`],
	[`	Q15.0	`,`	Congenital glaucoma Buphthalmos Glaucoma of newborn Hydrophthalmos Keratoglobus, congenital, with glaucoma Macrocornea with glaucoma Macrophthalmos in congenital glaucoma Megalocornea with glaucoma 	`,`	null	`],
	[`	Q15.8	`,`	Other specified congenital malformations of eye 	`,`	null	`],
	[`	Q15.9	`,`	Congenital malformation of eye, unspecified Congenital: anomaly deformity NOS of eye 	`,`	null	`],
	[`	Q16	`,`	Congenital malformations of ear causing impairment of hearing Excl.: congenital deafness (H90.-) 	`,`	null	`],
	[`	Q16.0	`,`	Congenital absence of (ear) auricle 	`,`	null	`],
	[`	Q16.1	`,`	Congenital absence, atresia and stricture of auditory canal (external) Atresia or stricture of osseous meatus 	`,`	null	`],
	[`	Q16.2	`,`	Absence of eustachian tube 	`,`	null	`],
	[`	Q16.3	`,`	Congenital malformation of ear ossicles Fusion of ear ossicles 	`,`	null	`],
	[`	Q16.4	`,`	Other congenital malformations of middle ear Congenital malformation of middle ear NOS 	`,`	null	`],
	[`	Q16.5	`,`	Congenital malformation of inner ear Anomaly: membranous labyrinth organ of Corti 	`,`	null	`],
	[`	Q16.9	`,`	Congenital malformation of ear causing impairment of hearing, unspecified Congenital absence of ear NOS 	`,`	null	`],
	[`	Q17	`,`	Other congenital malformations of ear Excl.: preauricular sinus (Q18.1) 	`,`	null	`],
	[`	Q17.0	`,`	Accessory auricle Accessory tragus Polyotia Preauricular appendage or tag Supernumerary: ear lobule 	`,`	null	`],
	[`	Q17.1	`,`	Macrotia 	`,`	null	`],
	[`	Q17.2	`,`	Microtia 	`,`	null	`],
	[`	Q17.3	`,`	Other misshapen ear Pointed ear 	`,`	null	`],
	[`	Q17.4	`,`	Misplaced ear Low-set ears Excl.: cervical auricle (Q18.2) 	`,`	null	`],
	[`	Q17.5	`,`	Prominent ear Bat ear 	`,`	null	`],
	[`	Q17.8	`,`	Other specified congenital malformations of ear Congenital absence of lobe of ear 	`,`	null	`],
	[`	Q17.9	`,`	Congenital malformation of ear, unspecified Congenital anomaly of ear NOS 	`,`	null	`],
	[`	Q18	`,`	Other congenital malformations of face and neck Excl.: cleft lip and cleft palate (Q35-Q37) conditions classified to Q67.0-Q67.4 congenital malformations of skull and face bones (Q75.-) cyclopia (Q87.0) dentofacial anomalies [including malocclusion] (K07.-) malformation syndromes affecting facial appearance (Q87.0) persistent thyroglossal duct (Q89.2) 	`,`	null	`],
	[`	Q18.0	`,`	Sinus, fistula and cyst of branchial cleft Branchial vestige 	`,`	null	`],
	[`	Q18.1	`,`	Preauricular sinus and cyst Fistula (of): auricle, congenital cervicoaural Pretragal sinus and cyst 	`,`	null	`],
	[`	Q18.2	`,`	Other branchial cleft malformations Branchial cleft malformation NOS Cervical auricle Otocephaly 	`,`	null	`],
	[`	Q18.3	`,`	Webbing of neck Pterygium colli 	`,`	null	`],
	[`	Q18.4	`,`	Macrostomia 	`,`	null	`],
	[`	Q18.5	`,`	Microstomia 	`,`	null	`],
	[`	Q18.6	`,`	Macrocheilia Hypertrophy of lip, congenital 	`,`	null	`],
	[`	Q18.7	`,`	Microcheilia 	`,`	null	`],
	[`	Q18.8	`,`	Other specified congenital malformations of face and neck Medial: cyst fistula sinus of face and neck 	`,`	null	`],
	[`	Q18.9	`,`	Congenital malformation of face and neck, unspecified Congenital anomaly NOS of face and neck 	`,`	null	`],
	[`	Q20.0	`,`	Common arterial trunk Persistent truncus arteriosus 111 	`,`	null	`],
	[`	Q20.1	`,`	Double outlet right ventricle Taussig-Bing syndrome 	`,`	null	`],
	[`	Q20.2	`,`	Double outlet left ventricle 	`,`	null	`],
	[`	Q20.3	`,`	Discordant ventriculoarterial connection Dextrotransposition of aorta Transposition of great vessels (complete) 	`,`	null	`],
	[`	Q20.4	`,`	Double inlet ventricle Common ventricle Cor triloculare biatriatum Single ventricle 	`,`	null	`],
	[`	Q20.5	`,`	Discordant atrioventricular connection Corrected transposition Laevotransposition Ventricular inversion 	`,`	null	`],
	[`	Q20.6	`,`	Isomerism of atrial appendages Isomerism of atrial appendages with asplenia or polysplenia 	`,`	null	`],
	[`	Q20.8	`,`	Other congenital malformations of cardiac chambers and connections 	`,`	null	`],
	[`	Q20.9	`,`	Congenital malformation of cardiac chambers and connections, unspecified 	`,`	null	`],
	[`	Q21	`,`	Congenital malformations of cardiac septa Excl.: acquired cardiac septal defect (I51.0) 	`,`	null	`],
	[`	Q21.0	`,`	Ventricular septal defect 	`,`	null	`],
	[`	Q21.1	`,`	Atrial septal defect Coronary sinus defect Patent or persistent: foramen ovale ostium secundum defect (type II) Sinus venosus defect 	`,`	null	`],
	[`	Q21.2	`,`	Atrioventricular septal defect Common atrioventricular canal Endocardial cushion defect Ostium primum atrial septal defect (type I) 	`,`	null	`],
	[`	Q21.3	`,`	Tetralogy of Fallot Ventricular septal defect with pulmonary stenosis or atresia, dextroposition of aorta and hypertrophy of right ventricle. 	`,`	null	`],
	[`	Q21.4	`,`	Aortopulmonary septal defect Aortic septal defect Aortopulmonary window 	`,`	null	`],
	[`	Q21.8	`,`	Other congenital malformations of cardiac septa Eisenmenger defect Pentalogy of Fallot Excl.: Eisenmenger complex (I27.8) syndrome (I27.8) 	`,`	null	`],
	[`	Q21.9	`,`	Congenital malformation of cardiac septum, unspecified Septal (heart) defect NOS 	`,`	null	`],
	[`	Q22	`,`	Congenital malformations of pulmonary and tricuspid valves 	`,`	null	`],
	[`	Q22.0	`,`	Pulmonary valve atresia 	`,`	null	`],
	[`	Q22.1	`,`	Congenital pulmonary valve stenosis 	`,`	null	`],
	[`	Q22.2	`,`	Congenital pulmonary valve insufficiency Congenital pulmonary valve regurgitation 	`,`	null	`],
	[`	Q22.3	`,`	Other congenital malformations of pulmonary valve Congenital malformation of pulmonary valve NOS 	`,`	null	`],
	[`	Q22.4	`,`	Congenital tricuspid stenosis Tricuspid atresia 	`,`	null	`],
	[`	Q22.5	`,`	Ebstein anomaly 	`,`	null	`],
	[`	Q22.6	`,`	Hypoplastic right heart syndrome 	`,`	null	`],
	[`	Q22.8	`,`	Other congenital malformations of tricuspid valve 	`,`	null	`],
	[`	Q22.9	`,`	Congenital malformation of tricuspid valve, unspecified 	`,`	null	`],
	[`	Q23	`,`	Congenital malformations of aortic and mitral valves 	`,`	null	`],
	[`	Q23.0	`,`	Congenital stenosis of aortic valve Congenital aortic: atresia stenosis Excl.: congenital subaortic stenosis (Q24.4) that in hypoplastic left heart syndrome (Q23.4) 	`,`	null	`],
	[`	Q23.1	`,`	Congenital insufficiency of aortic valve Bicuspid aortic valve Congenital aortic insufficiency 	`,`	null	`],
	[`	Q23.2	`,`	Congenital mitral stenosis Congenital mitral atresia 	`,`	null	`],
	[`	Q23.3	`,`	Congenital mitral insufficiency 	`,`	null	`],
	[`	Q23.4	`,`	Hypoplastic left heart syndrome Atresia, or marked hypoplasia of aortic orifice or valve, with hypoplasia of ascending aorta and defective development of left ventricle (with mitral valve stenosis or atresia). 	`,`	null	`],
	[`	Q23.8	`,`	Other congenital malformations of aortic and mitral valves 	`,`	null	`],
	[`	Q23.9	`,`	Congenital malformation of aortic and mitral valves, unspecified 	`,`	null	`],
	[`	Q24	`,`	Other congenital malformations of heart Excl.: endocardial fibroelastosis (I42.4) 	`,`	null	`],
	[`	Q24.0	`,`	Dextrocardia Excl.: dextrocardia with situs inversus (Q89.3) isomerism of atrial appendages (with asplenia or polysplenia) (Q20.6) mirror-image atrial arrangement with situs inversus (Q89.3) 	`,`	null	`],
	[`	Q24.1	`,`	Laevocardia Location of heart in left hemithorax with apex pointing to the left, but with situs inversus of other viscera and defects of the heart, or corrected transposition of great vessels. 	`,`	null	`],
	[`	Q24.2	`,`	Cor triatriatum 	`,`	null	`],
	[`	Q24.3	`,`	Pulmonary infundibular stenosis 	`,`	null	`],
	[`	Q24.4	`,`	Congenital subaortic stenosis 	`,`	null	`],
	[`	Q24.5	`,`	Malformation of coronary vessels Congenital coronary (artery) aneurysm 	`,`	null	`],
	[`	Q24.6	`,`	Congenital heart block 	`,`	null	`],
	[`	Q24.8	`,`	Other specified congenital malformations of heart Congenital: diverticulum of left ventricle malformation of: myocardium pericardium Malposition of heart Uhl disease 	`,`	null	`],
	[`	Q24.9	`,`	Congenital malformation of heart, unspecified Congenital: anomaly disease NOS of heart 	`,`	null	`],
	[`	Q25	`,`	Congenital malformations of great arteries 	`,`	null	`],
	[`	Q25.0	`,`	Patent ductus arteriosus Patent ductus Botallo Persistent ductus arteriosus 	`,`	null	`],
	[`	Q25.1	`,`	Coarctation of aorta Coarctation of aorta (preductal)(postductal) 	`,`	null	`],
	[`	Q25.2	`,`	Atresia of aorta 	`,`	null	`],
	[`	Q25.3	`,`	Stenosis of aorta Supravalvular aortic stenosis Excl.: congenital stenosis of aortic valve (Q23.0) 	`,`	null	`],
	[`	Q25.4	`,`	Other congenital malformations of aorta Absence Aplasia Congenital: aneurysm dilatation of aorta Aneurysm of sinus of Valsalva (ruptured) Double aortic arch [vascular ring of aorta] Hypoplasia of aorta Persistent: convolutions of aortic arch right aortic arch Excl.: hypoplasia of aorta in hypoplastic left heart syndrome (Q23.4) 	`,`	null	`],
	[`	Q25.5	`,`	Atresia of pulmonary artery 	`,`	null	`],
	[`	Q25.6	`,`	Stenosis of pulmonary artery Supravalvular pulmonary stenosis 	`,`	null	`],
	[`	Q25.7	`,`	Other congenital malformations of pulmonary artery Aberrant pulmonary artery Agenesis Aneurysm, congenital Anomaly Hypoplasia of pulmonary artery Pulmonary arteriovenous aneurysm 	`,`	null	`],
	[`	Q25.8	`,`	Other congenital malformations of great arteries 	`,`	null	`],
	[`	Q25.9	`,`	Congenital malformation of great arteries, unspecified 	`,`	null	`],
	[`	Q26	`,`	Congenital malformations of great veins 	`,`	null	`],
	[`	Q26.0	`,`	Congenital stenosis of vena cava Congenital stenosis of vena cava (inferior)(superior) 	`,`	null	`],
	[`	Q26.1	`,`	Persistent left superior vena cava 	`,`	null	`],
	[`	Q26.2	`,`	Total anomalous pulmonary venous connection 	`,`	null	`],
	[`	Q26.3	`,`	Partial anomalous pulmonary venous connection 	`,`	null	`],
	[`	Q26.4	`,`	Anomalous pulmonary venous connection, unspecified 	`,`	null	`],
	[`	Q26.5	`,`	Anomalous portal venous connection 	`,`	null	`],
	[`	Q26.6	`,`	Portal vein-hepatic artery fistula 	`,`	null	`],
	[`	Q26.8	`,`	Other congenital malformations of great veins Absence of vena cava (inferior)(superior) Azygos continuation of inferior vena cava Persistent left posterior cardinal vein Scimitar syndrome 	`,`	null	`],
	[`	Q26.9	`,`	Congenital malformation of great vein, unspecified Anomaly of vena cava (inferior)(superior) NOS 	`,`	null	`],
	[`	Q27	`,`	Other congenital malformations of peripheral vascular system Excl.: anomalies of: cerebral and precerebral vessels (Q28.0-Q28.3) coronary vessels (Q24.5) pulmonary artery (Q25.5-Q25.7) congenital retinal aneurysm (Q14.1) haemangioma and lymphangioma (D18.-) 	`,`	null	`],
	[`	Q27.0	`,`	Congenital absence and hypoplasia of umbilical artery Single umbilical artery 	`,`	null	`],
	[`	Q27.1	`,`	Congenital renal artery stenosis 	`,`	null	`],
	[`	Q27.2	`,`	Other congenital malformations of renal artery Congenital malformation of renal artery NOS Multiple renal arteries 	`,`	null	`],
	[`	Q27.3	`,`	Peripheral arteriovenous malformation Arteriovenous aneurysm Excl.: acquired arteriovenous aneurysm (I77.0) 	`,`	null	`],
	[`	Q27.4	`,`	Congenital phlebectasia 	`,`	null	`],
	[`	Q27.8	`,`	Other specified congenital malformations of peripheral vascular system Aberrant subclavian artery Absence Atresia of artery or vein NEC Congenital: aneurysm (peripheral) stricture, artery varix 	`,`	null	`],
	[`	Q27.9	`,`	Congenital malformation of peripheral vascular system, unspecified Anomaly of artery or vein NOS 	`,`	null	`],
	[`	Q28	`,`	Other congenital malformations of circulatory system Excl.: congenital aneurysm: NOS (Q27.8) coronary (Q24.5) peripheral (Q27.8) pulmonary (Q25.7) retinal (Q14.1) ruptured: cerebral arteriovenous malformation (I60.8) malformation of precerebral vessels (I72.-) 	`,`	null	`],
	[`	Q28.0	`,`	Arteriovenous malformation of precerebral vessels Congenital arteriovenous precerebral aneurysm (nonruptured) 	`,`	null	`],
	[`	Q28.1	`,`	Other malformations of precerebral vessels Congenital: malformation of precerebral vessels NOS precerebral aneurysm (nonruptured) 	`,`	null	`],
	[`	Q28.2	`,`	Arteriovenous malformation of cerebral vessels Arteriovenous malformation of brain NOS Congenital arteriovenous cerebral aneurysm (nonruptured) 	`,`	null	`],
	[`	Q28.3	`,`	Other malformations of cerebral vessels Congenital: cerebral aneurysm (nonruptured) malformation of cerebral vessels NOS 	`,`	null	`],
	[`	Q28.8	`,`	Other specified congenital malformations of circulatory system Congenital aneurysm, specified site NEC 	`,`	null	`],
	[`	Q28.9	`,`	Congenital malformation of circulatory system, unspecified 	`,`	null	`],
	[`	Q30.0	`,`	Choanal atresia Atresia Congenital stenosis of nares (anterior)(posterior) 	`,`	null	`],
	[`	Q30.1	`,`	Agenesis and underdevelopment of nose Congenital absence of nose 	`,`	null	`],
	[`	Q30.2	`,`	Fissured, notched and cleft nose 	`,`	null	`],
	[`	Q30.3	`,`	Congenital perforated nasal septum 	`,`	null	`],
	[`	Q30.8	`,`	Other congenital malformations of nose Accessory nose Congenital anomaly of nasal sinus wall 	`,`	null	`],
	[`	Q30.9	`,`	Congenital malformation of nose, unspecified 	`,`	null	`],
	[`	Q31	`,`	Congenital malformations of larynx Excl.: congenital (laryngeal) stridor NOS (P28.8) 	`,`	null	`],
	[`	Q31.0	`,`	Web of larynx Web of larynx: NOS glottic subglottic 	`,`	null	`],
	[`	Q31.1	`,`	Congenital subglottic stenosis 	`,`	null	`],
	[`	Q31.2	`,`	Laryngeal hypoplasia 	`,`	null	`],
	[`	Q31.3	`,`	Laryngocele 	`,`	null	`],
	[`	Q31.5	`,`	Congenital laryngomalacia 	`,`	null	`],
	[`	Q31.8	`,`	Other congenital malformations of larynx Absence Agenesis Atresia of cricoid cartilage, epiglottis, glottis, larynx or thyroid cartilage Cleft thyroid cartilage Congenital stenosis of larynx NEC Fissure of epiglottis Posterior cleft of cricoid cartilage 	`,`	null	`],
	[`	Q31.9	`,`	Congenital malformation of larynx, unspecified 	`,`	null	`],
	[`	Q32	`,`	Congenital malformations of trachea and bronchus Excl.: congenital bronchiectasis (Q33.4) 	`,`	null	`],
	[`	Q32.0	`,`	Congenital tracheomalacia 	`,`	null	`],
	[`	Q32.1	`,`	Other congenital malformations of trachea Anomaly of tracheal cartilage Atresia of trachea Congenital: dilatation malformation stenosis of trachea Congenital tracheocele 	`,`	null	`],
	[`	Q32.2	`,`	Congenital bronchomalacia 	`,`	null	`],
	[`	Q32.3	`,`	Congenital stenosis of bronchus 	`,`	null	`],
	[`	Q32.4	`,`	Other congenital malformations of bronchus Absence Agenesis Atresia Congenital malformation NOS Diverticulum of bronchus 	`,`	null	`],
	[`	Q33	`,`	Congenital malformations of lung 	`,`	null	`],
	[`	Q33.0	`,`	Congenital cystic lung Congenital: honeycomb lung lung disease: cystic polycystic Excl.: cystic lung disease, acquired or unspecified (J98.4) 	`,`	null	`],
	[`	Q33.1	`,`	Accessory lobe of lung 	`,`	null	`],
	[`	Q33.2	`,`	Sequestration of lung 	`,`	null	`],
	[`	Q33.3	`,`	Agenesis of lung Absence of lung (lobe) 	`,`	null	`],
	[`	Q33.4	`,`	Congenital bronchiectasis 	`,`	null	`],
	[`	Q33.5	`,`	Ectopic tissue in lung 	`,`	null	`],
	[`	Q33.6	`,`	Hypoplasia and dysplasia of lung Excl.: pulmonary hypoplasia associated with short gestation (P28.0) 	`,`	null	`],
	[`	Q33.8	`,`	Other congenital malformations of lung 	`,`	null	`],
	[`	Q33.9	`,`	Congenital malformation of lung, unspecified 	`,`	null	`],
	[`	Q34	`,`	Other congenital malformations of respiratory system 	`,`	null	`],
	[`	Q34.0	`,`	Anomaly of pleura 	`,`	null	`],
	[`	Q34.1	`,`	Congenital cyst of mediastinum 	`,`	null	`],
	[`	Q34.8	`,`	Other specified congenital malformations of respiratory system Atresia of nasopharynx 	`,`	null	`],
	[`	Q34.9	`,`	Congenital malformation of respiratory system, unspecified Congenital: absence anomaly NOS of respiratory organ 	`,`	null	`],
	[`	Q35	`,`	Cleft palate Incl.: fissure of palate palatoschisis Excl.: cleft palate with cleft lip (Q37.-) 	`,`	null	`],
	[`	Q35.1	`,`	Cleft hard palate 	`,`	null	`],
	[`	Q35.3	`,`	Cleft soft palate 	`,`	null	`],
	[`	Q35.5	`,`	Cleft hard palate with cleft soft palate 	`,`	null	`],
	[`	Q35.7	`,`	Cleft uvula 	`,`	null	`],
	[`	Q35.9	`,`	Cleft palate, unspecified 	`,`	null	`],
	[`	Q36	`,`	Cleft lip Incl.: cheiloschisis congenital fissure of lip harelip labium leporinum Excl.: cleft lip with cleft palate (Q37.-) 	`,`	null	`],
	[`	Q36.0	`,`	Cleft lip, bilateral 	`,`	null	`],
	[`	Q36.1	`,`	Cleft lip, median 	`,`	null	`],
	[`	Q36.9	`,`	Cleft lip, unilateral Cleft lip NOS 	`,`	null	`],
	[`	Q37	`,`	Cleft palate with cleft lip 	`,`	null	`],
	[`	Q37.0	`,`	Cleft hard palate with bilateral cleft lip 	`,`	null	`],
	[`	Q37.1	`,`	Cleft hard palate with unilateral cleft lip Cleft hard palate with cleft lip NOS 	`,`	null	`],
	[`	Q37.2	`,`	Cleft soft palate with bilateral cleft lip 	`,`	null	`],
	[`	Q37.3	`,`	Cleft soft palate with unilateral cleft lip Cleft soft palate with cleft lip NOS 	`,`	null	`],
	[`	Q37.4	`,`	Cleft hard and soft palate with bilateral cleft lip 	`,`	null	`],
	[`	Q37.5	`,`	Cleft hard and soft palate with unilateral cleft lip Cleft hard and soft palate with cleft lip NOS 	`,`	null	`],
	[`	Q37.8	`,`	Unspecified cleft palate with bilateral cleft lip 	`,`	null	`],
	[`	Q37.9	`,`	Unspecified cleft palate with unilateral cleft lip Cleft palate with cleft lip NOS 	`,`	null	`],
	[`	Q38	`,`	Other congenital malformations of tongue, mouth and pharynx Excl.: macrostomia (Q18.4) microstomia (Q18.5) 	`,`	null	`],
	[`	Q38.0	`,`	Congenital malformations of lips, not elsewhere classified Congenital: fistula of lip malformation of lip NOS Van der Woude syndrome Excl.: cleft lip (Q36.-) cleft lip with cleft palate (Q37.-) macrocheilia (Q18.6) microcheilia (Q18.7) 	`,`	null	`],
	[`	Q38.1	`,`	Ankyloglossia Tongue tie 	`,`	null	`],
	[`	Q38.2	`,`	Macroglossia 	`,`	null	`],
	[`	Q38.3	`,`	Other congenital malformations of tongue Aglossia Bifid tongue Congenital: adhesion fissure malformation NOS of tongue Hypoglossia Hypoplasia of tongue Microglossia 	`,`	null	`],
	[`	Q38.4	`,`	Congenital malformations of salivary glands and ducts Absence Accessory Atresia (of) salivary gland or duct Congenital fistula of salivary gland 	`,`	null	`],
	[`	Q38.5	`,`	Congenital malformations of palate, not elsewhere classified Absence of uvula Congenital malformation of palate NOS High arched palate Excl.: cleft palate (Q35.-) cleft palate with cleft lip (Q37.-) 	`,`	null	`],
	[`	Q38.6	`,`	Other congenital malformations of mouth Congenital malformation of mouth NOS 	`,`	null	`],
	[`	Q38.7	`,`	Pharyngeal pouch Diverticulum of pharynx Excl.: pharyngeal pouch syndrome (D82.1) 	`,`	null	`],
	[`	Q38.8	`,`	Other congenital malformations of pharynx Congenital malformation of pharynx NOS 	`,`	null	`],
	[`	Q39	`,`	Congenital malformations of oesophagus 	`,`	null	`],
	[`	Q39.0	`,`	Atresia of oesophagus without fistula Atresia of oesophagus NOS 	`,`	null	`],
	[`	Q39.1	`,`	Atresia of oesophagus with tracheo-oesophageal fistula Atresia of oesophagus with broncho-oesophageal fistula 	`,`	null	`],
	[`	Q39.2	`,`	Congenital tracheo-oesophageal fistula without atresia Congenital tracheo-oesophageal fistula NOS 	`,`	null	`],
	[`	Q39.3	`,`	Congenital stenosis and stricture of oesophagus 	`,`	null	`],
	[`	Q39.4	`,`	Oesophageal web 	`,`	null	`],
	[`	Q39.5	`,`	Congenital dilatation of oesophagus 	`,`	null	`],
	[`	Q39.6	`,`	Diverticulum of oesophagus Oesophageal pouch 	`,`	null	`],
	[`	Q39.8	`,`	Other congenital malformations of oesophagus Absent Congenital displacement Duplication (of) oesophagus 	`,`	null	`],
	[`	Q39.9	`,`	Congenital malformation of oesophagus, unspecified 	`,`	null	`],
	[`	Q40	`,`	Other congenital malformations of upper alimentary tract 	`,`	null	`],
	[`	Q40.0	`,`	Congenital hypertrophic pyloric stenosis Congenital or infantile: constriction hypertrophy spasm stenosis stricture of pylorus 	`,`	null	`],
	[`	Q40.1	`,`	Congenital hiatus hernia Displacement of cardia through oesophageal hiatus Excl.: congenital diaphragmatic hernia (Q79.0) 	`,`	null	`],
	[`	Q40.2	`,`	Other specified congenital malformations of stomach Congenital: displacement of stomach diverticulum of stomach hourglass stomach Duplication of stomach Megalogastria Microgastria 	`,`	null	`],
	[`	Q40.3	`,`	Congenital malformation of stomach, unspecified 	`,`	null	`],
	[`	Q40.8	`,`	Other specified congenital malformations of upper alimentary tract 	`,`	null	`],
	[`	Q40.9	`,`	Congenital malformation of upper alimentary tract, unspecified Congenital: anomaly deformity NOS of upper alimentary tract 	`,`	null	`],
	[`	Q41	`,`	Congenital absence, atresia and stenosis of small intestine Incl.: congenital obstruction, occlusion and stricture of small intestine or intestine NOS Excl.: meconium ileus (E84.1) 	`,`	null	`],
	[`	Q41.0	`,`	Congenital absence, atresia and stenosis of duodenum 	`,`	null	`],
	[`	Q41.1	`,`	Congenital absence, atresia and stenosis of jejunum Apple peel syndrome Imperforate jejunum 	`,`	null	`],
	[`	Q41.2	`,`	Congenital absence, atresia and stenosis of ileum 	`,`	null	`],
	[`	Q41.8	`,`	Congenital absence, atresia and stenosis of other specified parts of small intestine 	`,`	null	`],
	[`	Q41.9	`,`	Congenital absence, atresia and stenosis of small intestine, part unspecified Congenital absence, atresia and stenosis of intestine NOS 	`,`	null	`],
	[`	Q42	`,`	Congenital absence, atresia and stenosis of large intestine Incl.: congenital obstruction, occlusion and stricture of large intestine 	`,`	null	`],
	[`	Q42.0	`,`	Congenital absence, atresia and stenosis of rectum with fistula 	`,`	null	`],
	[`	Q42.1	`,`	Congenital absence, atresia and stenosis of rectum without fistula Imperforate rectum 	`,`	null	`],
	[`	Q42.2	`,`	Congenital absence, atresia and stenosis of anus with fistula 	`,`	null	`],
	[`	Q42.3	`,`	Congenital absence, atresia and stenosis of anus without fistula Imperforate anus 	`,`	null	`],
	[`	Q42.8	`,`	Congenital absence, atresia and stenosis of other parts of large intestine 	`,`	null	`],
	[`	Q42.9	`,`	Congenital absence, atresia and stenosis of large intestine, part unspecified 	`,`	null	`],
	[`	Q43	`,`	Other congenital malformations of intestine 	`,`	null	`],
	[`	Q43.0	`,`	Meckel diverticulum Persistent: omphalomesenteric duct vitelline duct 	`,`	null	`],
	[`	Q43.1	`,`	Hirschsprung disease Aganglionosis Congenital (aganglionic) megacolon 	`,`	null	`],
	[`	Q43.2	`,`	Other congenital functional disorders of colon Congenital dilatation of colon 	`,`	null	`],
	[`	Q43.3	`,`	Congenital malformations of intestinal fixation Congenital adhesions [bands]: omental, anomalous peritoneal Jackson membrane Malrotation of colon Rotation: failure of incomplete insufficient of caecum and colon Universal mesentery 	`,`	null	`],
	[`	Q43.4	`,`	Duplication of intestine 	`,`	null	`],
	[`	Q43.5	`,`	Ectopic anus 	`,`	null	`],
	[`	Q43.6	`,`	Congenital fistula of rectum and anus Excl.: congenital fistula: rectovaginal (Q52.2) urethrorectal (Q64.7) pilonidal fistula or sinus (L05.-) with absence, atresia and stenosis (Q42.0, Q42.2) 	`,`	null	`],
	[`	Q43.7	`,`	Persistent cloaca Cloaca NOS 	`,`	null	`],
	[`	Q43.8	`,`	Other specified congenital malformations of intestine Congenital: blind loop syndrome diverticulitis, colon diverticulum, intestine Dolichocolon Megaloappendix Megaloduodenum Microcolon Transposition of: appendix colon intestine 	`,`	null	`],
	[`	Q43.9	`,`	Congenital malformation of intestine, unspecified 	`,`	null	`],
	[`	Q44	`,`	Congenital malformations of gallbladder, bile ducts and liver 	`,`	null	`],
	[`	Q44.0	`,`	Agenesis, aplasia and hypoplasia of gallbladder Congenital absence of gallbladder 	`,`	null	`],
	[`	Q44.1	`,`	Other congenital malformations of gallbladder Congenital malformation of gallbladder NOS Intrahepatic gallbladder 	`,`	null	`],
	[`	Q44.2	`,`	Atresia of bile ducts 	`,`	null	`],
	[`	Q44.3	`,`	Congenital stenosis and stricture of bile ducts 	`,`	null	`],
	[`	Q44.4	`,`	Choledochal cyst 	`,`	null	`],
	[`	Q44.5	`,`	Other congenital malformations of bile ducts Accessory hepatic duct Congenital malformation of bile duct NOS Duplication: biliary duct cystic duct 	`,`	null	`],
	[`	Q44.6	`,`	Cystic disease of liver Fibrocystic disease of liver 	`,`	null	`],
	[`	Q44.7	`,`	Other congenital malformations of liver Accessory liver Alagille syndrome Congenital: absence of liver hepatomegaly malformation of liver NOS 	`,`	null	`],
	[`	Q45	`,`	Other congenital malformations of digestive system Excl.: congenital: diaphragmatic hernia (Q79.0) hiatus hernia (Q40.1) 	`,`	null	`],
	[`	Q45.0	`,`	Agenesis, aplasia and hypoplasia of pancreas Congenital absence of pancreas 	`,`	null	`],
	[`	Q45.1	`,`	Annular pancreas 	`,`	null	`],
	[`	Q45.2	`,`	Congenital pancreatic cyst 	`,`	null	`],
	[`	Q45.3	`,`	Other congenital malformations of pancreas and pancreatic duct Accessory pancreas Congenital malformation of pancreas or pancreatic duct NOS Excl.: diabetes mellitus: congenital (E10.-) neonatal (P70.2) fibrocystic disease of pancreas (E84.-) 	`,`	null	`],
	[`	Q45.8	`,`	Other specified congenital malformations of digestive system Absence (complete)(partial) of alimentary tract NOS Duplication Malposition, congenital of digestive organs NOS 	`,`	null	`],
	[`	Q45.9	`,`	Congenital malformation of digestive system, unspecified Congenital: anomaly deformity NOS of digestive system 	`,`	null	`],
	[`	Q50	`,`	Congenital malformations of ovaries, fallopian tubes and broad ligaments 	`,`	null	`],
	[`	Q50.0	`,`	Congenital absence of ovary Excl.: Turner syndrome (Q96.-) 	`,`	null	`],
	[`	Q50.1	`,`	Developmental ovarian cyst 	`,`	null	`],
	[`	Q50.2	`,`	Congenital torsion of ovary 	`,`	null	`],
	[`	Q50.3	`,`	Other congenital malformations of ovary Accessory ovary Congenital malformation of ovary NOS Ovarian streak 	`,`	null	`],
	[`	Q50.4	`,`	Embryonic cyst of fallopian tube Fimbrial cyst 	`,`	null	`],
	[`	Q50.5	`,`	Embryonic cyst of broad ligament Cyst: epoophoron Gartner duct parovarian 	`,`	null	`],
	[`	Q50.6	`,`	Other congenital malformations of fallopian tube and broad ligament Absence Accessory Atresia (of) fallopian tube or broad ligament Congenital malformation of fallopian tube or broad ligament NOS 	`,`	null	`],
	[`	Q51	`,`	Congenital malformations of uterus and cervix 	`,`	null	`],
	[`	Q51.0	`,`	Agenesis and aplasia of uterus Congenital absence of uterus 	`,`	null	`],
	[`	Q51.1	`,`	Doubling of uterus with doubling of cervix and vagina 	`,`	null	`],
	[`	Q51.2	`,`	Other doubling of uterus Doubling of uterus NOS 	`,`	null	`],
	[`	Q51.3	`,`	Bicornate uterus 	`,`	null	`],
	[`	Q51.4	`,`	Unicornate uterus 	`,`	null	`],
	[`	Q51.5	`,`	Agenesis and aplasia of cervix Congenital absence of cervix 	`,`	null	`],
	[`	Q51.6	`,`	Embryonic cyst of cervix 	`,`	null	`],
	[`	Q51.7	`,`	Congenital fistulae between uterus and digestive and urinary tracts 	`,`	null	`],
	[`	Q51.8	`,`	Other congenital malformations of uterus and cervix Hypoplasia of uterus and cervix 	`,`	null	`],
	[`	Q51.9	`,`	Congenital malformation of uterus and cervix, unspecified 	`,`	null	`],
	[`	Q52	`,`	Other congenital malformations of female genitalia 	`,`	null	`],
	[`	Q52.0	`,`	Congenital absence of vagina 	`,`	null	`],
	[`	Q52.1	`,`	Doubling of vagina Septate vagina Excl.: doubling of vagina with doubling of uterus and cervix (Q51.1) 	`,`	null	`],
	[`	Q52.2	`,`	Congenital rectovaginal fistula Excl.: cloaca (Q43.7) 	`,`	null	`],
	[`	Q52.3	`,`	Imperforate hymen 	`,`	null	`],
	[`	Q52.4	`,`	Other congenital malformations of vagina Congenital malformation of vagina NOS Cyst: canal of Nuck, congenital embryonic vaginal 	`,`	null	`],
	[`	Q52.5	`,`	Fusion of labia 	`,`	null	`],
	[`	Q52.6	`,`	Congenital malformation of clitoris 	`,`	null	`],
	[`	Q52.7	`,`	Other congenital malformations of vulva Congenital: absence cyst malformation NOS of vulva 	`,`	null	`],
	[`	Q52.8	`,`	Other specified congenital malformations of female genitalia 	`,`	null	`],
	[`	Q52.9	`,`	Congenital malformation of female genitalia, unspecified 	`,`	null	`],
	[`	Q53	`,`	Undescended testicle 	`,`	null	`],
	[`	Q53.0	`,`	Ectopic testis Unilateral or bilateral ectopic testes 	`,`	null	`],
	[`	Q53.1	`,`	Undescended testicle, unilateral 	`,`	null	`],
	[`	Q53.2	`,`	Undescended testicle, bilateral 	`,`	null	`],
	[`	Q53.9	`,`	Undescended testicle, unspecified Cryptorchism NOS 	`,`	null	`],
	[`	Q54	`,`	Hypospadias Excl.: epispadias (Q64.0) 	`,`	null	`],
	[`	Q54.0	`,`	Hypospadias, balanic Hypospadias: coronal glandular 	`,`	null	`],
	[`	Q54.1	`,`	Hypospadias, penile 	`,`	null	`],
	[`	Q54.2	`,`	Hypospadias, penoscrotal 	`,`	null	`],
	[`	Q54.3	`,`	Hypospadias, perineal 	`,`	null	`],
	[`	Q54.4	`,`	Congenital chordee 	`,`	null	`],
	[`	Q54.8	`,`	Other hypospadias 	`,`	null	`],
	[`	Q54.9	`,`	Hypospadias, unspecified 	`,`	null	`],
	[`	Q55	`,`	Other congenital malformations of male genital organs Excl.: congenital hydrocele (P83.5) hypospadias (Q54.-) 	`,`	null	`],
	[`	Q55.0	`,`	Absence and aplasia of testis Monorchism 	`,`	null	`],
	[`	Q55.1	`,`	Hypoplasia of testis and scrotum Fusion of testes 	`,`	null	`],
	[`	Q55.2	`,`	Other congenital malformations of testis and scrotum Congenital malformation of testis or scrotum NOS Polyorchism Retractile testis Testis migrans 	`,`	null	`],
	[`	Q55.3	`,`	Atresia of vas deferens 	`,`	null	`],
	[`	Q55.4	`,`	Other congenital malformations of vas deferens, epididymis, seminal vesicles and prostate Absence or aplasia of: prostate spermatic cord Congenital malformation of vas deferens, epididymis, seminal vesicles or prostate NOS 	`,`	null	`],
	[`	Q55.5	`,`	Congenital absence and aplasia of penis 	`,`	null	`],
	[`	Q55.6	`,`	Other congenital malformations of penis Congenital malformation of penis NOS Curvature of penis (lateral) Hypoplasia of penis 	`,`	null	`],
	[`	Q55.8	`,`	Other specified congenital malformations of male genital organs 	`,`	null	`],
	[`	Q55.9	`,`	Congenital malformation of male genital organ, unspecified Congenital: anomaly deformity NOS of male genital organ 	`,`	null	`],
	[`	Q56	`,`	Indeterminate sex and pseudohermaphroditism Excl.: pseudohermaphroditism: female, with adrenocortical disorder (E25.-) male, with androgen resistance (E34.5) with specified chromosomal anomaly (Q96-Q99) 	`,`	null	`],
	[`	Q56.0	`,`	Hermaphroditism, not elsewhere classified Ovotestis 	`,`	null	`],
	[`	Q56.1	`,`	Male pseudohermaphroditism, not elsewhere classified Male pseudohermaphroditism NOS 	`,`	null	`],
	[`	Q56.2	`,`	Female pseudohermaphroditism, not elsewhere classified Female pseudohermaphroditism NOS 	`,`	null	`],
	[`	Q56.3	`,`	Pseudohermaphroditism, unspecified 	`,`	null	`],
	[`	Q56.4	`,`	Indeterminate sex, unspecified Ambiguous genitalia 	`,`	null	`],
	[`	Q60	`,`	Renal agenesis and other reduction defects of kidney Incl.: atrophy of kidney: congenital infantile congenital absence of kidney 	`,`	null	`],
	[`	Q60.0	`,`	Renal agenesis, unilateral 	`,`	null	`],
	[`	Q60.1	`,`	Renal agenesis, bilateral 	`,`	null	`],
	[`	Q60.2	`,`	Renal agenesis, unspecified 	`,`	null	`],
	[`	Q60.3	`,`	Renal hypoplasia, unilateral 	`,`	null	`],
	[`	Q60.4	`,`	Renal hypoplasia, bilateral 	`,`	null	`],
	[`	Q60.5	`,`	Renal hypoplasia, unspecified 	`,`	null	`],
	[`	Q60.6	`,`	Potter syndrome 	`,`	null	`],
	[`	Q61	`,`	Cystic kidney disease Excl.: cyst of kidney (acquired) (N28.1) Potter syndrome (Q60.6) 	`,`	null	`],
	[`	Q61.0	`,`	Congenital single renal cyst Congenital cyst of kidney (single) 	`,`	null	`],
	[`	Q61.1	`,`	Polycystic kidney, autosomal recessive Polycystic kidney, infantile type 	`,`	null	`],
	[`	Q61.2	`,`	Polycystic kidney, autosomal dominant Polycystic kidney, adult type 	`,`	null	`],
	[`	Q61.3	`,`	Polycystic kidney, unspecified Q61.4 Renal dysplasia Multicystic: dyplastic kidney kidney (developmental) kidney disease renal dysplasia Excl.: polycystic kidney disease (Q61.1-Q61.3) 	`,`	null	`],
	[`	Q61.5	`,`	Medullary cystic kidney Sponge kidney NOS 	`,`	null	`],
	[`	Q61.8	`,`	Other cystic kidney diseases Fibrocystic: kidney renal degeneration or disease 	`,`	null	`],
	[`	Q61.9	`,`	Cystic kidney disease, unspecified Meckel-Gruber syndrome 	`,`	null	`],
	[`	Q62	`,`	Congenital obstructive defects of renal pelvis and congenital malformations of ureter 	`,`	null	`],
	[`	Q62.0	`,`	Congenital hydronephrosis 	`,`	null	`],
	[`	Q62.1	`,`	Atresia and stenosis of ureter Congenital occlusion of: ureter ureteropelvic junction ureterovesical orifice Impervious ureter 	`,`	null	`],
	[`	Q62.2	`,`	Congenital megaloureter Congenital dilatation of ureter 	`,`	null	`],
	[`	Q62.3	`,`	Other obstructive defects of renal pelvis and ureter Congenital ureterocele 	`,`	null	`],
	[`	Q62.4	`,`	Agenesis of ureter Absent ureter 	`,`	null	`],
	[`	Q62.5	`,`	Duplication of ureter Accessory Double ureter 	`,`	null	`],
	[`	Q62.6	`,`	Malposition of ureter Deviation Displacement Ectopic Implantation, anomalous (of) ureter or ureteric orifice 	`,`	null	`],
	[`	Q62.7	`,`	Congenital vesico-uretero-renal reflux 	`,`	null	`],
	[`	Q62.8	`,`	Other congenital malformations of ureter Anomaly of ureter NOS 	`,`	null	`],
	[`	Q63	`,`	Other congenital malformations of kidney Excl.: congenital nephrotic syndrome (N04.-) 	`,`	null	`],
	[`	Q63.0	`,`	Accessory kidney 	`,`	null	`],
	[`	Q63.1	`,`	Lobulated, fused and horseshoe kidney 	`,`	null	`],
	[`	Q63.2	`,`	Ectopic kidney Congenital displaced kidney Malrotation of kidney 	`,`	null	`],
	[`	Q63.3	`,`	Hyperplastic and giant kidney 	`,`	null	`],
	[`	Q63.8	`,`	Other specified congenital malformations of kidney Congenital renal calculi 	`,`	null	`],
	[`	Q63.9	`,`	Congenital malformation of kidney, unspecified 	`,`	null	`],
	[`	Q64	`,`	Other congenital malformations of urinary system 	`,`	null	`],
	[`	Q64.0	`,`	Epispadias Excl.: hypospadias (Q54.-) 	`,`	null	`],
	[`	Q64.1	`,`	Exstrophy of urinary bladder Ectopia vesicae Extroversion of bladder 	`,`	null	`],
	[`	Q64.2	`,`	Congenital posterior urethral valves 	`,`	null	`],
	[`	Q64.3	`,`	Other atresia and stenosis of urethra and bladder neck Congenital: bladder neck obstruction stricture of: urethra urinary meatus vesicourethral orifice Impervious urethra 	`,`	null	`],
	[`	Q64.4	`,`	Malformation of urachus Cyst of urachus Patent urachus Prolapse of urachus 	`,`	null	`],
	[`	Q64.5	`,`	Congenital absence of bladder and urethra 	`,`	null	`],
	[`	Q64.6	`,`	Congenital diverticulum of bladder 	`,`	null	`],
	[`	Q64.7	`,`	Other congenital malformations of bladder and urethra Accessory: bladder urethra Congenital: hernia of bladder malformation of bladder or urethra NOS prolapse of: bladder (mucosa) urethra urinary meatus urethrorectal fistula Double: urethra urinary meatus 	`,`	null	`],
	[`	Q64.8	`,`	Other specified congenital malformations of urinary system 	`,`	null	`],
	[`	Q64.9	`,`	Congenital malformation of urinary system, unspecified Congenital: anomaly deformity NOS of urinary system 	`,`	null	`],
	[`	Q65	`,`	Congenital deformities of hip Excl.: clicking hip (R29.4) 	`,`	null	`],
	[`	Q65.0	`,`	Congenital dislocation of hip, unilateral 	`,`	null	`],
	[`	Q65.1	`,`	Congenital dislocation of hip, bilateral 	`,`	null	`],
	[`	Q65.2	`,`	Congenital dislocation of hip, unspecified 	`,`	null	`],
	[`	Q65.3	`,`	Congenital subluxation of hip, unilateral 	`,`	null	`],
	[`	Q65.4	`,`	Congenital subluxation of hip, bilateral 	`,`	null	`],
	[`	Q65.5	`,`	Congenital subluxation of hip, unspecified 	`,`	null	`],
	[`	Q65.6	`,`	Unstable hip Dislocatable hip Subluxatable hip 	`,`	null	`],
	[`	Q65.8	`,`	Other congenital deformities of hip Anteversion of femoral neck Congenital acetabular dysplasia Congenital coxa: valga vara 	`,`	null	`],
	[`	Q65.9	`,`	Congenital deformity of hip, unspecified 	`,`	null	`],
	[`	Q66	`,`	Congenital deformities of feet Excl.: reduction defects of feet (Q72.-) valgus deformities (acquired) (M21.0) varus deformities (acquired) (M21.1) 	`,`	null	`],
	[`	Q66.0	`,`	Talipes equinovarus 	`,`	null	`],
	[`	Q66.1	`,`	Talipes calcaneovarus 	`,`	null	`],
	[`	Q66.2	`,`	Metatarsus varus 	`,`	null	`],
	[`	Q66.3	`,`	Other congenital varus deformities of feet Hallux varus, congenital 	`,`	null	`],
	[`	Q66.4	`,`	Talipes calcaneovalgus 	`,`	null	`],
	[`	Q66.5	`,`	Congenital pes planus Flat foot: congenital rigid spastic (everted) 	`,`	null	`],
	[`	Q66.6	`,`	Other congenital valgus deformities of feet Metatarsus valgus 	`,`	null	`],
	[`	Q66.7	`,`	Pes cavus 	`,`	null	`],
	[`	Q66.8	`,`	Other congenital deformities of feet Clubfoot NOS Hammer toe, congenital Talipes: NOS asymmetric Tarsal coalition Vertical talus 	`,`	null	`],
	[`	Q66.9	`,`	Congenital deformity of feet, unspecified 	`,`	null	`],
	[`	Q67	`,`	Congenital musculoskeletal deformities of head, face, spine and chest Excl.: congenital malformation syndromes classified to Q87.- Potter syndrome (Q60.6) 	`,`	null	`],
	[`	Q67.0	`,`	Facial asymmetry 	`,`	null	`],
	[`	Q67.1	`,`	Compression facies 	`,`	null	`],
	[`	Q67.2	`,`	Dolichocephaly 	`,`	null	`],
	[`	Q67.3	`,`	Plagiocephaly 	`,`	null	`],
	[`	Q67.4	`,`	Other congenital deformities of skull, face and jaw Depressions in skull Deviation of nasal septum, congenital Hemifacial atrophy or hypertrophy Squashed or bent nose, congenital Excl.: dentofacial anomalies [including malocclusion] (K07.-) syphilitic saddle nose (A50.5) 	`,`	null	`],
	[`	Q67.5	`,`	Congenital deformity of spine Congenital scoliosis: NOS postural Excl.: infantile idiopathic scoliosis (M41.0) scoliosis due to congenital bony malformation (Q76.3) 	`,`	null	`],
	[`	Q67.6	`,`	Pectus excavatum Congenital funnel chest 	`,`	null	`],
	[`	Q67.7	`,`	Pectus carinatum Congenital pigeon chest 	`,`	null	`],
	[`	Q67.8	`,`	Other congenital deformities of chest Congenital deformity of chest wall NOS 	`,`	null	`],
	[`	Q68	`,`	Other congenital musculoskeletal deformities Excl.: reduction defects of limb(s) (Q71-Q73) 	`,`	null	`],
	[`	Q68.0	`,`	Congenital deformity of sternocleidomastoid muscle Congenital (sternomastoid) torticollis Contracture of sternocleidomastoid (muscle) Sternomastoid tumour (congenital) 	`,`	null	`],
	[`	Q68.1	`,`	Congenital deformity of hand Congenital clubfinger Spade-like hand (congenital) 	`,`	null	`],
	[`	Q68.2	`,`	Congenital deformity of knee Congenital: dislocation of knee genu recurvatum 	`,`	null	`],
	[`	Q68.3	`,`	Congenital bowing of femur Excl.: anteversion of femur (neck) (Q65.8) 	`,`	null	`],
	[`	Q68.4	`,`	Congenital bowing of tibia and fibula 	`,`	null	`],
	[`	Q68.5	`,`	Congenital bowing of long bones of leg, unspecified 	`,`	null	`],
	[`	Q68.8	`,`	Other specified congenital musculoskeletal deformities Congenital: deformity of: clavicle elbow forearm scapula dislocation of: elbow shoulder 	`,`	null	`],
	[`	Q69	`,`	Polydactyly 	`,`	null	`],
	[`	Q69.0	`,`	Accessory finger(s) 	`,`	null	`],
	[`	Q69.1	`,`	Accessory thumb(s) 	`,`	null	`],
	[`	Q69.2	`,`	Accessory toe(s) Accessory hallux 	`,`	null	`],
	[`	Q69.9	`,`	Polydactyly, unspecified Supernumerary digit(s) NOS 	`,`	null	`],
	[`	Q70	`,`	Syndactyly 	`,`	null	`],
	[`	Q70.0	`,`	Fused fingers Complex syndactyly of fingers with synostosis 	`,`	null	`],
	[`	Q70.1	`,`	Webbed fingers Simple syndactyly of fingers without synostosis 	`,`	null	`],
	[`	Q70.2	`,`	Fused toes Complex syndactyly of toes with synostosis 	`,`	null	`],
	[`	Q70.3	`,`	Webbed toes Simple syndactyly of toes without synostosis 	`,`	null	`],
	[`	Q70.4	`,`	Polysyndactyly 	`,`	null	`],
	[`	Q70.9	`,`	Syndactyly, unspecified Symphalangy NOS 	`,`	null	`],
	[`	Q71	`,`	Reduction defects of upper limb 	`,`	null	`],
	[`	Q71.0	`,`	Congenital complete absence of upper limb(s) 	`,`	null	`],
	[`	Q71.1	`,`	Congenital absence of upper arm and forearm with hand present 	`,`	null	`],
	[`	Q71.2	`,`	Congenital absence of both forearm and hand 	`,`	null	`],
	[`	Q71.3	`,`	Congenital absence of hand and finger(s) 	`,`	null	`],
	[`	Q71.4	`,`	Longitudinal reduction defect of radius Clubhand (congenital) Radial clubhand 	`,`	null	`],
	[`	Q71.5	`,`	Longitudinal reduction defect of ulna 	`,`	null	`],
	[`	Q71.6	`,`	Lobster-claw hand 	`,`	null	`],
	[`	Q71.8	`,`	Other reduction defects of upper limb(s) Congenital shortening of upper limb(s) 	`,`	null	`],
	[`	Q71.9	`,`	Reduction defect of upper limb, unspecified 	`,`	null	`],
	[`	Q72	`,`	Reduction defects of lower limb 	`,`	null	`],
	[`	Q72.0	`,`	Congenital complete absence of lower limb(s) 	`,`	null	`],
	[`	Q72.1	`,`	Congenital absence of thigh and lower leg with foot present 	`,`	null	`],
	[`	Q72.2	`,`	Congenital absence of both lower leg and foot 	`,`	null	`],
	[`	Q72.3	`,`	Congenital absence of foot and toe(s) 	`,`	null	`],
	[`	Q72.4	`,`	Longitudinal reduction defect of femur Proximal femoral focal deficiency 	`,`	null	`],
	[`	Q72.5	`,`	Longitudinal reduction defect of tibia 	`,`	null	`],
	[`	Q72.6	`,`	Longitudinal reduction defect of fibula 	`,`	null	`],
	[`	Q72.7	`,`	Split foot 	`,`	null	`],
	[`	Q72.8	`,`	Other reduction defects of lower limb(s) Congenital shortening of lower limb(s) 	`,`	null	`],
	[`	Q72.9	`,`	Reduction defect of lower limb, unspecified 	`,`	null	`],
	[`	Q73	`,`	Reduction defects of unspecified limb 	`,`	null	`],
	[`	Q73.0	`,`	Congenital absence of unspecified limb(s) Amelia NOS 	`,`	null	`],
	[`	Q73.1	`,`	Phocomelia, unspecified limb(s) Phocomelia NOS 	`,`	null	`],
	[`	Q73.8	`,`	Other reduction defects of unspecified limb(s) Longitudinal reduction deformity of unspecified limb(s) Ectromelia NOS Hemimelia NOS Reduction defect of limb(s) NOS 	`,`	null	`],
	[`	Q74	`,`	Other congenital malformations of limb(s) Excl.: polydactyly (Q69.-) reduction defect of limb (Q71-Q73) syndactyly (Q70.-) 	`,`	null	`],
	[`	Q74.0	`,`	Other congenital malformations of upper limb(s), including shoulder girdle Accessory carpal bones Cleidocranial dysostosis Congenital pseudarthrosis of clavicle Macrodactylia (fingers) Madelung deformity Radioulnar synostosis Sprengel deformity Triphalangeal thumb 	`,`	null	`],
	[`	Q74.1	`,`	Congenital malformation of knee Congenital: absence of patella dislocation of patella genu: valgum varum Rudimentary patella Excl.: congenital: dislocation of knee (Q68.2) genu recurvatum (Q68.2) nail patella syndrome (Q87.2) 	`,`	null	`],
	[`	Q74.2	`,`	Other congenital malformations of lower limb(s), including pelvic girdle Congenital: fusion of sacroiliac joint malformation (of): ankle (joint) sacroiliac (joint) Excl.: anteversion of femur (neck) (Q65.8) 	`,`	null	`],
	[`	Q74.3	`,`	Arthrogryposis multiplex congenita 	`,`	null	`],
	[`	Q74.8	`,`	Other specified congenital malformations of limb(s) 	`,`	null	`],
	[`	Q74.9	`,`	Unspecified congenital malformation of limb(s) Congenital anomaly of limb(s) NOS 	`,`	null	`],
	[`	Q75	`,`	Other congenital malformations of skull and face bones Excl.: congenital malformation of face NOS (Q18.-) congenital malformation syndromes classified to Q87.- dentofacial anomalies [including malocclusion] (K07.-) musculoskeletal deformities of head and face (Q67.0-Q67.4) skull defects associated with congenital anomalies of brain such as: anencephaly (Q00.0) encephalocele (Q01.-) hydrocephalus (Q03.-) microcephaly (Q02) 	`,`	null	`],
	[`	Q75.0	`,`	Craniosynostosis Acrocephaly Imperfect fusion of skull Oxycephaly Trigonocephaly 	`,`	null	`],
	[`	Q75.1	`,`	Craniofacial dysostosis Crouzon disease 	`,`	null	`],
	[`	Q75.2	`,`	Hypertelorism 	`,`	null	`],
	[`	Q75.3	`,`	Macrocephaly 	`,`	null	`],
	[`	Q75.4	`,`	Mandibulofacial dysostosis Syndrome: Franceschetti Treacher-Collins 	`,`	null	`],
	[`	Q75.5	`,`	Oculomandibular dysostosis 	`,`	null	`],
	[`	Q75.8	`,`	Other specified congenital malformations of skull and face bones Absence of skull bone, congenital Congenital deformity of forehead Platybasia 	`,`	null	`],
	[`	Q75.9	`,`	Congenital malformation of skull and face bones, unspecified Congenital anomaly of: face bones NOS skull NOS 	`,`	null	`],
	[`	Q76	`,`	Congenital malformations of spine and bony thorax Excl.: congenital musculoskeletal deformities of spine and chest (Q67.5-Q67.8) 	`,`	null	`],
	[`	Q76.0	`,`	Spina bifida occulta Excl.: meningocele (spinal) (Q05.-) spina bifida (aperta)(cystica) (Q05.-) 	`,`	null	`],
	[`	Q76.1	`,`	Klippel-Feil syndrome Cervical fusion syndrome 	`,`	null	`],
	[`	Q76.2	`,`	Congenital spondylolisthesis Congenital spondylolysis Excl.: spondylolisthesis (acquired) (M43.1) spondylolysis (acquired) (M43.0) 	`,`	null	`],
	[`	Q76.3	`,`	Congenital scoliosis due to congenital bony malformation Hemivertebra fusion or failure of segmentation with scoliosis 	`,`	null	`],
	[`	Q76.4	`,`	Other congenital malformations of spine, not associated with scoliosis Congenital: absence of vertebra fusion of spine kyphosis lordosis malformation of lumbosacral (joint) (region) Hemivertebra Malformation of spine Platyspondylisis Supernumerary vertebra unspecified or not associated with scoliosis 	`,`	null	`],
	[`	Q76.5	`,`	Cervical rib Supernumerary rib in cervical region 	`,`	null	`],
	[`	Q76.6	`,`	Other congenital malformations of ribs Accessory rib Congenital: absence of rib fusion of ribs malformation of ribs NOS Excl.: short rib syndrome (Q77.2) 	`,`	null	`],
	[`	Q76.7	`,`	Congenital malformation of sternum Congenital absence of sternum Sternum bifidum 	`,`	null	`],
	[`	Q76.8	`,`	Other congenital malformations of bony thorax 	`,`	null	`],
	[`	Q76.9	`,`	Congenital malformation of bony thorax, unspecified 	`,`	null	`],
	[`	Q77	`,`	Osteochondrodysplasia with defects of growth of tubular bones and spine Excl.: mucopolysaccharidosis (E76.0-E76.3) 	`,`	null	`],
	[`	Q77.0	`,`	Achondrogenesis Hypochondrogenesis 	`,`	null	`],
	[`	Q77.1	`,`	Thanatophoric short stature 	`,`	null	`],
	[`	Q77.2	`,`	Short rib syndrome Asphyxiating thoracic dysplasia [Jeune] 	`,`	null	`],
	[`	Q77.3	`,`	Chondrodysplasia punctata 	`,`	null	`],
	[`	Q77.4	`,`	Achondroplasia Hypochondroplasia Osteosclerosis congenita 	`,`	null	`],
	[`	Q77.5	`,`	Dystrophic dysplasia 	`,`	null	`],
	[`	Q77.6	`,`	Chondroectodermal dysplasia Ellis-van Creveld syndrome 	`,`	null	`],
	[`	Q77.7	`,`	Spondyloepiphyseal dysplasia 	`,`	null	`],
	[`	Q77.8	`,`	Other osteochondrodysplasia with defects of growth of tubular bones and spine 	`,`	null	`],
	[`	Q77.9	`,`	Osteochondrodysplasia with defects of growth of tubular bones and spine, unspecified 	`,`	null	`],
	[`	Q78	`,`	Other osteochondrodysplasias 	`,`	null	`],
	[`	Q78.0	`,`	Osteogenesis imperfecta Fragilitas ossium Osteopsathyrosis 	`,`	null	`],
	[`	Q78.1	`,`	Polyostotic fibrous dysplasia Albright(-McCune)(-Sternberg) syndrome 	`,`	null	`],
	[`	Q78.2	`,`	Osteopetrosis Albers-Sch...nberg syndrome 	`,`	null	`],
	[`	Q78.3	`,`	Progressive diaphyseal dysplasia Camurati-Engelmann syndrome 	`,`	null	`],
	[`	Q78.4	`,`	Enchondromatosis Maffucci syndrome Ollier disease 	`,`	null	`],
	[`	Q78.5	`,`	Metaphyseal dysplasia Pyle syndrome 	`,`	null	`],
	[`	Q78.6	`,`	Multiple congenital exostoses Diaphyseal aclasis 	`,`	null	`],
	[`	Q78.8	`,`	Other specified osteochondrodysplasias Osteopoikilosis 	`,`	null	`],
	[`	Q78.9	`,`	Osteochondrodysplasia, unspecified Chondrodystrophy NOS Osteodystrophy NOS 	`,`	null	`],
	[`	Q79	`,`	Congenital malformations of the musculoskeletal system, not elsewhere classified Excl.: congenital (sternomastoid) torticollis (Q68.0) 	`,`	null	`],
	[`	Q79.0	`,`	Congenital diaphragmatic hernia Excl.: congenital hiatus hernia (Q40.1) 	`,`	null	`],
	[`	Q79.1	`,`	Other congenital malformations of diaphragm Absence of diaphragm Congenital malformation of diaphragm NOS Eventration of diaphragm 	`,`	null	`],
	[`	Q79.2	`,`	Exomphalos Omphalocele Excl.: umbilical hernia (K42.-) 	`,`	null	`],
	[`	Q79.3	`,`	Gastroschisis 	`,`	null	`],
	[`	Q79.4	`,`	Prune belly syndrome 	`,`	null	`],
	[`	Q79.5	`,`	Other congenital malformations of abdominal wall Excl.: umbilical hernia (K42.-) 	`,`	null	`],
	[`	Q79.6	`,`	Ehlers-Danlos syndrome 	`,`	null	`],
	[`	Q79.8	`,`	Other congenital malformations of musculoskeletal system Absence of: muscle tendon Accessory muscle Amyotrophia congenita Congenital: constricting bands shortening of tendon Poland syndrome 	`,`	null	`],
	[`	Q79.9	`,`	Congenital malformation of musculoskeletal system, unspecified Congenital: anomaly NOS deformity NOS of musculoskeletal system NOS 	`,`	null	`],
	[`	Q80	`,`	Congenital ichthyosis Excl.: Refsum disease (G60.1) 	`,`	null	`],
	[`	Q80.0	`,`	Ichthyosis vulgaris 	`,`	null	`],
	[`	Q80.1	`,`	X-linked ichthyosis 	`,`	null	`],
	[`	Q80.2	`,`	Lamellar ichthyosis Collodion baby 	`,`	null	`],
	[`	Q80.3	`,`	Congenital bullous ichthyosiform erythroderma 	`,`	null	`],
	[`	Q80.4	`,`	Harlequin fetus 	`,`	null	`],
	[`	Q80.8	`,`	Other congenital ichthyosis 	`,`	null	`],
	[`	Q80.9	`,`	Congenital ichthyosis, unspecified 	`,`	null	`],
	[`	Q81	`,`	Epidermolysis bullosa 	`,`	null	`],
	[`	Q81.0	`,`	Epidermolysis bullosa simplex Excl.: Cockayne syndrome (Q87.1) 	`,`	null	`],
	[`	Q81.1	`,`	Epidermolysis bullosa letalis Herlitz syndrome 	`,`	null	`],
	[`	Q81.2	`,`	Epidermolysis bullosa dystrophica 	`,`	null	`],
	[`	Q81.8	`,`	Other epidermolysis bullosa 	`,`	null	`],
	[`	Q81.9	`,`	Epidermolysis bullosa, unspecified 	`,`	null	`],
	[`	Q82	`,`	Other congenital malformations of skin Excl.: acrodermatitis enteropathica (E83.2) congenital erythropoietic porphyria (E80.0) pilonidal cyst or sinus (L05.-) Sturge-Weber(-Dimitri) syndrome (Q85.8) 	`,`	null	`],
	[`	Q82.0	`,`	Hereditary lymphoedema 	`,`	null	`],
	[`	Q82.1	`,`	Xeroderma pigmentosum 	`,`	null	`],
	[`	Q82.2	`,`	Mastocytosis Urticaria pigmentosa Excl.: malignant mastocytosis (C96.2) 	`,`	null	`],
	[`	Q82.3	`,`	Incontinentia pigmenti 	`,`	null	`],
	[`	Q82.4	`,`	Ectodermal dysplasia (anhidrotic) Excl.: Ellis-van Creveld syndrome (Q77.6) 	`,`	null	`],
	[`	Q82.5	`,`	Congenital non-neoplastic naevus Birthmark NOS Naevus: flammeus portwine sanguineous strawberry vascular NOS verrucous Excl.: caf... au lait spots (L81.3) lentigo (L81.4) naevus: NOS (D22.-) araneus (I78.1) melanocytic (D22.-) pigmented (D22.-) spider (I78.1) stellar (I78.1) 	`,`	null	`],
	[`	Q82.8	`,`	Other specified congenital malformations of skin Abnormal palmar creases Accessory skin tags Benign familial pemphigus [Hailey-Hailey] Cutis laxa (hyperelastica) Dermatoglyphic anomalies Inherited keratosis palmaris et plantaris Keratosis follicularis [Darier-White] Excl.: Ehlers-Danlos syndrome (Q79.6) 	`,`	null	`],
	[`	Q82.9	`,`	Congenital malformation of skin, unspecified 	`,`	null	`],
	[`	Q83	`,`	Congenital malformations of breast Excl.: absence of pectoral muscle (Q79.8) 	`,`	null	`],
	[`	Q83.0	`,`	Congenital absence of breast with absent nipple 	`,`	null	`],
	[`	Q83.1	`,`	Accessory breast Supernumerary breast 	`,`	null	`],
	[`	Q83.2	`,`	Absent nipple 	`,`	null	`],
	[`	Q83.3	`,`	Accessory nipple Supernumerary nipple 	`,`	null	`],
	[`	Q83.8	`,`	Other congenital malformations of breast Hypoplasia of breast 	`,`	null	`],
	[`	Q83.9	`,`	Congenital malformation of breast, unspecified 	`,`	null	`],
	[`	Q84	`,`	Other congenital malformations of integument 	`,`	null	`],
	[`	Q84.0	`,`	Congenital alopecia Congenital atrichosis 	`,`	null	`],
	[`	Q84.1	`,`	Congenital morphological disturbances of hair, not elsewhere classified Beaded hair Monilethrix Pili annulati Excl.: Menkes kinky hair syndrome (E83.0) 	`,`	null	`],
	[`	Q84.2	`,`	Other congenital malformations of hair Congenital: hypertrichosis malformation of hair NOS Persistent lanugo 	`,`	null	`],
	[`	Q84.3	`,`	Anonychia Excl.: nail patella syndrome (Q87.2) 	`,`	null	`],
	[`	Q84.4	`,`	Congenital leukonychia 	`,`	null	`],
	[`	Q84.5	`,`	Enlarged and hypertrophic nails Congenital onychauxis Pachyonychia 	`,`	null	`],
	[`	Q84.6	`,`	Other congenital malformations of nails Congenital: clubnail koilonychia malformation of nail NOS 	`,`	null	`],
	[`	Q84.8	`,`	Other specified congenital malformations of integument Aplasia cutis congenita 	`,`	null	`],
	[`	Q84.9	`,`	Congenital malformation of integument, unspecified Congenital: anomaly NOS deformity NOS of integument NOS 	`,`	null	`],
	[`	Q85	`,`	Phakomatoses, not elsewhere classified Excl.: ataxia telangiectasia [Louis-Bar] (G11.3) familial dysautonomia [Riley-Day] (G90.1) 	`,`	null	`],
	[`	Q85.0	`,`	Neurofibromatosis (nonmalignant) Von Recklinghausen disease 	`,`	null	`],
	[`	Q85.1	`,`	Tuberous sclerosis Bourneville disease Epiloia 	`,`	null	`],
	[`	Q85.8	`,`	Other phakomatoses, not elsewhere classified Syndrome: Peutz-Jeghers Sturge-Weber(-Dimitri) von Hippel-Lindau Excl.: Meckel-Gruber syndrome (Q61.9) 	`,`	null	`],
	[`	Q85.9	`,`	Phakomatosis, unspecified Hamartosis NOS 	`,`	null	`],
	[`	Q86	`,`	Congenital malformation syndromes due to known exogenous causes, not elsewhere classified Excl.: iodine-deficiency-related hypothyroidism (E00-E02) nonteratogenic effects of substances transmitted via placenta or breast milk (P04.-) 	`,`	null	`],
	[`	Q86.0	`,`	Fetal alcohol syndrome (dysmorphic) 	`,`	null	`],
	[`	Q86.1	`,`	Fetal hydantoin syndrome Meadow syndrome 	`,`	null	`],
	[`	Q86.2	`,`	Dysmorphism due to warfarin 	`,`	null	`],
	[`	Q86.8	`,`	Other congenital malformation syndromes due to known exogenous causes 	`,`	null	`],
	[`	Q87	`,`	Other specified congenital malformation syndromes affecting multiple systems 	`,`	null	`],
	[`	Q87.0	`,`	Congenital malformation syndromes predominantly affecting facial appearance Acrocephalopolysyndactyly Acrocephalosyndactyly [Apert] Cryptophthalmos syndrome Cyclopia Syndrome: Goldenhar Moebius oro-facial-digital Robin Whistling face 	`,`	null	`],
	[`	Q87.1	`,`	Congenital malformation syndromes predominantly associated with short stature Syndrome: Aarskog Cockayne De Lange Dubowitz Noonan Prader-Willi Robinow-Silverman-Smith Russell-Silver Seckel Smith-Lemli-Opitz Excl.: Ellis-van Creveld syndrome (Q77.6) 	`,`	null	`],
	[`	Q87.2	`,`	Congenital malformation syndromes predominantly involving limbs Syndrome: Holt-Oram Klippel-Tr...naunay-Weber nail patella Rubinstein-Taybi sirenomelia thrombocytopenia with absent radius [TAR] VATER 	`,`	null	`],
	[`	Q87.3	`,`	Congenital malformation syndromes involving early overgrowth Syndrome: Beckwith-Wiedemann Sotos Weaver 	`,`	null	`],
	[`	Q87.4	`,`	Marfan syndrome 	`,`	null	`],
	[`	Q87.5	`,`	Other congenital malformation syndromes with other skeletal changes 	`,`	null	`],
	[`	Q87.8	`,`	Other specified congenital malformation syndromes, not elsewhere classified Syndrome: Alport Laurence-Moon(-Bardet)-Biedl Zellweger 	`,`	null	`],
	[`	Q89	`,`	Other congenital malformations, not elsewhere classified 	`,`	null	`],
	[`	Q89.0	`,`	Congenital malformations of spleen Asplenia (congenital) Congenital splenomegaly Excl.: isomerism of atrial appendages (with asplenia or polysplenia) (Q20.6) 	`,`	null	`],
	[`	Q89.1	`,`	Congenital malformations of adrenal gland Excl.: congenital adrenal hyperplasia (E25.0) 	`,`	null	`],
	[`	Q89.2	`,`	Congenital malformations of other endocrine glands Congenital malformation of parathyroid or thyroid gland Persistent thyroglossal duct Thyroglossal cyst 	`,`	null	`],
	[`	Q89.3	`,`	Situs inversus Dextrocardia with situs inversus Mirror-image atrial arrangement with situs inversus Situs inversus or transversus: abdominalis thoracis Transposition of viscera: abdominal thoracic Excl.: dextrocardia NOS (Q24.0) laevocardia (Q24.1) 	`,`	null	`],
	[`	Q89.4	`,`	Conjoined twins Craniopagus Dicephaly Double monster Pygopagus Thoracopagus 	`,`	null	`],
	[`	Q89.7	`,`	Multiple congenital malformations, not elsewhere classified Monster NOS Multiple congenital: anomalies NOS deformities NOS Excl.: congenital malformation syndromes affecting multiple systems (Q87.-) 	`,`	null	`],
	[`	Q89.8	`,`	Other specified congenital malformations 	`,`	null	`],
	[`	Q89.9	`,`	Congenital malformation, unspecified Congenital: anomaly NOS deformity NOS 	`,`	null	`],
	[`	Q90	`,`	Down syndrome 	`,`	null	`],
	[`	Q90.0	`,`	Trisomy 21, meiotic nondisjunction 	`,`	null	`],
	[`	Q90.1	`,`	Trisomy 21, mosaicism (mitotic nondisjunction) 	`,`	null	`],
	[`	Q90.2	`,`	Trisomy 21, translocation 	`,`	null	`],
	[`	Q90.9	`,`	Down syndrome, unspecified Trisomy 21 NOS 	`,`	null	`],
	[`	Q91	`,`	Edwards syndrome and Patau syndrome 	`,`	null	`],
	[`	Q91.0	`,`	Trisomy 18, meiotic nondisjunction 	`,`	null	`],
	[`	Q91.1	`,`	Trisomy 18, mosaicism (mitotic nondisjunction) 	`,`	null	`],
	[`	Q91.2	`,`	Trisomy 18, translocation 	`,`	null	`],
	[`	Q91.3	`,`	Edwards syndrome, unspecified 	`,`	null	`],
	[`	Q91.4	`,`	Trisomy 13, meiotic nondisjunction 	`,`	null	`],
	[`	Q91.5	`,`	Trisomy 13, mosaicism (mitotic nondisjunction) 	`,`	null	`],
	[`	Q91.6	`,`	Trisomy 13, translocation 	`,`	null	`],
	[`	Q91.7	`,`	Patau syndrome, unspecified 	`,`	null	`],
	[`	Q92	`,`	Other trisomies and partial trisomies of the autosomes, not elsewhere classified Incl.: unbalanced translocations and insertions Excl.: trisomies of chromosomes 13, 18, 21 (Q90-Q91) 	`,`	null	`],
	[`	Q92.0	`,`	Whole chromosome trisomy, meiotic nondisjunction 	`,`	null	`],
	[`	Q92.1	`,`	Whole chromosome trisomy, mosaicism (mitotic nondisjunction) 	`,`	null	`],
	[`	Q92.2	`,`	Major partial trisomy Whole arm or more duplicated. 	`,`	null	`],
	[`	Q92.3	`,`	Minor partial trisomy Less than whole arm duplicated. 	`,`	null	`],
	[`	Q92.4	`,`	Duplications seen only at prometaphase 	`,`	null	`],
	[`	Q92.5	`,`	Duplications with other complex rearrangements 	`,`	null	`],
	[`	Q92.6	`,`	Extra marker chromosomes 	`,`	null	`],
	[`	Q92.7	`,`	Triploidy and polyploidy 	`,`	null	`],
	[`	Q92.8	`,`	Other specified trisomies and partial trisomies of autosomes 	`,`	null	`],
	[`	Q92.9	`,`	Trisomy and partial trisomy of autosomes, unspecified 	`,`	null	`],
	[`	Q93	`,`	Monosomies and deletions from the autosomes, not elsewhere classified 	`,`	null	`],
	[`	Q93.0	`,`	Whole chromosome monosomy, meiotic nondisjunction 	`,`	null	`],
	[`	Q93.1	`,`	Whole chromosome monosomy, mosaicism (mitotic nondisjunction) 	`,`	null	`],
	[`	Q93.2	`,`	Chromosome replaced with ring or dicentric 	`,`	null	`],
	[`	Q93.3	`,`	Deletion of short arm of chromosome 4 Wolff-Hirschorn syndrome 	`,`	null	`],
	[`	Q93.4	`,`	Deletion of short arm of chromosome 5 Cri-du-chat syndrome 	`,`	null	`],
	[`	Q93.5	`,`	Other deletions of part of a chromosome Angelman syndrome 	`,`	null	`],
	[`	Q93.6	`,`	Deletions seen only at prometaphase 	`,`	null	`],
	[`	Q93.7	`,`	Deletions with other complex rearrangements 	`,`	null	`],
	[`	Q93.8	`,`	Other deletions from the autosomes 	`,`	null	`],
	[`	Q93.9	`,`	Deletion from autosomes, unspecified 	`,`	null	`],
	[`	Q95	`,`	Balanced rearrangements and structural markers, not elsewhere classified Incl.: Robertsonian and balanced reciprocal translocations and insertions 	`,`	null	`],
	[`	Q95.0	`,`	Balanced translocation and insertion in normal individual 	`,`	null	`],
	[`	Q95.1	`,`	Chromosome inversion in normal individual 	`,`	null	`],
	[`	Q95.2	`,`	Balanced autosomal rearrangement in abnormal individual 	`,`	null	`],
	[`	Q95.3	`,`	Balanced sex/autosomal rearrangement in abnormal individual 	`,`	null	`],
	[`	Q95.4	`,`	Individuals with marker heterochromatin 	`,`	null	`],
	[`	Q95.5	`,`	Individuals with autosomal fragile site 	`,`	null	`],
	[`	Q95.8	`,`	Other balanced rearrangements and structural markers 	`,`	null	`],
	[`	Q95.9	`,`	Balanced rearrangement and structural marker, unspecified 	`,`	null	`],
	[`	Q96	`,`	Turner syndrome Excl.: Noonan syndrome (Q87.1) 	`,`	null	`],
	[`	Q96.0	`,`	Karyotype 45,X 	`,`	null	`],
	[`	Q96.1	`,`	Karyotype 46,X iso (Xq) 	`,`	null	`],
	[`	Q96.2	`,`	Karyotype 46,X with abnormal sex chromosome, except iso (Xq) 	`,`	null	`],
	[`	Q96.3	`,`	Mosaicism, 45,X/46,XX or XY 	`,`	null	`],
	[`	Q96.4	`,`	Mosaicism, 45,X/other cell line(s) with abnormal sex chromosome 	`,`	null	`],
	[`	Q96.8	`,`	Other variants of Turner syndrome 	`,`	null	`],
	[`	Q96.9	`,`	Turner syndrome, unspecified 	`,`	null	`],
	[`	Q97	`,`	Other sex chromosome abnormalities, female phenotype, not elsewhere classified Excl.: Turner syndrome (Q96.-) 	`,`	null	`],
	[`	Q97.0	`,`	Karyotype 47,XXX 	`,`	null	`],
	[`	Q97.1	`,`	Female with more than three X chromosomes 	`,`	null	`],
	[`	Q97.2	`,`	Mosaicism, lines with various numbers of X chromosomes 	`,`	null	`],
	[`	Q97.3	`,`	Female with 46,XY karyotype 	`,`	null	`],
	[`	Q97.8	`,`	Other specified sex chromosome abnormalities, female phenotype 	`,`	null	`],
	[`	Q97.9	`,`	Sex chromosome abnormality, female phenotype, unspecified 	`,`	null	`],
	[`	Q98	`,`	Other sex chromosome abnormalities, male phenotype, not elsewhere classified 	`,`	null	`],
	[`	Q98.0	`,`	Klinefelter syndrome karyotype 47,XXY 	`,`	null	`],
	[`	Q98.1	`,`	Klinefelter syndrome, male with more than two X chromosomes 	`,`	null	`],
	[`	Q98.2	`,`	Klinefelter syndrome, male with 46,XX karyotype 	`,`	null	`],
	[`	Q98.3	`,`	Other male with 46,XX karyotype 	`,`	null	`],
	[`	Q98.4	`,`	Klinefelter syndrome, unspecified 	`,`	null	`],
	[`	Q98.5	`,`	Karyotype 47,XYY 	`,`	null	`],
	[`	Q98.6	`,`	Male with structurally abnormal sex chromosome 	`,`	null	`],
	[`	Q98.7	`,`	Male with sex chromosome mosaicism 	`,`	null	`],
	[`	Q98.8	`,`	Other specified sex chromosome abnormalities, male phenotype 	`,`	null	`],
	[`	Q98.9	`,`	Sex chromosome abnormality, male phenotype, unspecified 	`,`	null	`],
	[`	Q99	`,`	Other chromosome abnormalities, not elsewhere classified 	`,`	null	`],
	[`	Q99.0	`,`	Chimera 46,XX/46,XY Chimera 46,XX/46,XY true hermaphrodite 	`,`	null	`],
	[`	Q99.1	`,`	46,XX true hermaphrodite 46,XX with streak gonads 46,XY with streak gonads Pure gonadal dysgenesis 	`,`	null	`],
	[`	Q99.2	`,`	Fragile X chromosome Fragile X syndrome 	`,`	null	`],
	[`	Q99.8	`,`	Other specified chromosome abnormalities 	`,`	null	`],
	[`	Q99.9	`,`	Chromosomal abnormality, unspecified 	`,`	null	`],
];							
							
					
							
							
				
	
let CodeRangeQ ={
	f0:function(val1=(-1),val2=(0)){
		let Range1 = QCodes.slice(val1,val2);
		Range1.reverse();
		document.documentElement.innerHTML += `<br>Showing Q Codes ${Range1.length} items(s)`;

		for(value1 in Range1){
			    document.documentElement.style.cssText += "background-color:tan;";
				document.getElementById('qcodesTR').outerHTML += `<tr><td style="background-color:navy;color:white;width:5%;padding:40px;border:2px solid white;font-weight:900;font-size:40px;text-align:center;">${Range1[value1][0]}</td><td style="background-color:black;color:white;width:90%;padding:20px;border:2px solid white;font-size:30px;">${Range1[value1][1]}</td><td style="background-color:navy;color:white;width:5%;padding:20px;border:2px solid white;font-weight:900;font-size:40px;text-align:center;">${Range1[value1][2]}</td></tr>`;			
		}

	},

};

	






	






