							
let RCodes = [							
	[`	ID	`,`	 SYMPTOMS / PROBLEMS / ISSUES 	`,`	 SYSTEMS	`],
	[`	R00	`,`	Abnormalities of heart beat Excl.: abnormalities originating in the perinatal period (P29.1) specified arrhythmias (I47-I49) 	`,`	null	`],
	[`	R00.0	`,`	Tachycardia, unspecified Rapid heart beat Tachycardia: sinoauricular NOS sinus [sinusal] NOS 	`,`	null	`],
	[`	R00.1	`,`	Bradycardia, unspecified Bradycardia: sinoatrial sinus vagal Slow heart beat Use additional external cause code (Chapter XX), if desired, to identify drug, if drug-induced. 	`,`	null	`],
	[`	R00.2	`,`	Palpitations Awareness of heart beat 	`,`	null	`],
	[`	R00.8	`,`	Other and unspecified abnormalities of heart beat 	`,`	null	`],
	[`	R01	`,`	Cardiac murmurs and other cardiac sounds Excl.: those originating in the perinatal period (P29.8) 	`,`	null	`],
	[`	R01.0	`,`	Benign and innocent cardiac murmurs Functional cardiac murmur 	`,`	null	`],
	[`	R01.1	`,`	Cardiac murmur, unspecified Cardiac bruit NOS 	`,`	null	`],
	[`	R01.2	`,`	Other cardiac sounds Cardiac dullness, increased or decreased Precordial friction 	`,`	null	`],
	[`	R02	`,`	Gangrene, not elsewhere classified Excl.: gangrene in: atherosclerosis (I70.2) diabetes mellitus (E10-E14 with common fourth character .5) other peripheral vascular diseases (I73.-) gangrene of certain specified sites - see Alphabetical Index gas gangrene (A48.0) pyoderma gangrenosum (L88) 	`,`	null	`],
	[`	R03	`,`	Abnormal blood-pressure reading, without diagnosis 	`,`	null	`],
	[`	R03.0	`,`	Elevated blood-pressure reading, without diagnosis of hypertension Note: This category is to be used to record an episode of elevated blood pressure in a patient in whom no formal diagnosis of hypertension has been made, or as an isolated incidental finding. 	`,`	null	`],
	[`	R03.1	`,`	Nonspecific low blood-pressure reading Excl.: hypotension (I95.-) hypotension neurogenic orthostatic (G90.3) maternal hypotension syndrome (O26.5) 	`,`	null	`],
	[`	R04	`,`	Haemorrhage from respiratory passages 	`,`	null	`],
	[`	R04.0	`,`	Epistaxis Haemorrhage from nose Nosebleed 	`,`	null	`],
	[`	R04.1	`,`	Haemorrhage from throat Excl.: haemoptysis (R04.2) 	`,`	null	`],
	[`	R04.2	`,`	Haemoptysis Blood-stained sputum Cough with haemorrhage 	`,`	null	`],
	[`	R04.8	`,`	Haemorrhage from other sites in respiratory passages Pulmonary haemorrhage NOS Excl.: perinatal pulmonary haemorrhage (P26.-) 	`,`	null	`],
	[`	R04.9	`,`	Haemorrhage from respiratory passages, unspecified 	`,`	null	`],
	[`	R05	`,`	Cough Excl.: cough with haemorrhage (R04.2) psychogenic cough (F45.3) 	`,`	null	`],
	[`	R06	`,`	Abnormalities of breathing Excl.: respiratory: arrest (R09.2) distress: syndrome of adult (J80) in newborn (P22.-) failure (J96.-) failure of newborn (P28.5) 	`,`	null	`],
	[`	R06.0	`,`	Dyspnoea Orthopnoea Shortness of breath Excl.: transient tachypnoea of newborn (P22.1) 	`,`	null	`],
	[`	R06.1	`,`	Stridor Excl.: congenital laryngeal stridor (P28.8) laryngismus (stridulus) (J38.5) 	`,`	null	`],
	[`	R06.2	`,`	Wheezing 	`,`	null	`],
	[`	R06.3	`,`	Periodic breathing Cheyne-Stokes breathing 	`,`	null	`],
	[`	R06.4	`,`	Hyperventilation Excl.: psychogenic hyperventilation (F45.3) 	`,`	null	`],
	[`	R06.5	`,`	Mouth breathing Snoring Excl.: dry mouth NOS (R68.2) 	`,`	null	`],
	[`	R06.6	`,`	Hiccough Excl.: psychogenic hiccough (F45.3) 	`,`	null	`],
	[`	R06.7	`,`	Sneezing 	`,`	null	`],
	[`	R06.8	`,`	Other and unspecified abnormalities of breathing Apnoea NOS Breath-holding (spells) Choking sensation Sighing Excl.: apnoea (of): newborn (P28.4) sleep (G47.3) sleep newborn (primary) (P28.3) 	`,`	null	`],
	[`	R07	`,`	Pain in throat and chest Excl.: dysphagia (R13) epidemic myalgia (B33.0) pain in: breast (N64.4) neck (M54.2) sore throat (acute) NOS (J02.9) 	`,`	null	`],
	[`	R07.0	`,`	Pain in throat 	`,`	null	`],
	[`	R07.1	`,`	Chest pain on breathing Painful respiration 	`,`	null	`],
	[`	R07.2	`,`	Precordial pain 	`,`	null	`],
	[`	R07.3	`,`	Other chest pain Anterior chest-wall pain NOS 	`,`	null	`],
	[`	R07.4	`,`	Chest pain, unspecified 	`,`	null	`],
	[`	R09	`,`	Other symptoms and signs involving the circulatory and respiratory systems Excl.: respiratory: distress (syndrome)(of): adult (J80) newborn (P22.-) failure (J96.-) failure newborn (P28.5) 	`,`	null	`],
	[`	R09.0	`,`	Asphyxia Excl.: asphyxia (due to): birth (P21.-) carbon monoxide (T58) foreign body in respiratory tract (T17.-) intrauterine (P20.-) traumatic (T71) 	`,`	null	`],
	[`	R09.1	`,`	Pleurisy Excl.: pleurisy with effusion (J90) 	`,`	null	`],
	[`	R09.2	`,`	Respiratory arrest Cardiorespiratory failure 	`,`	null	`],
	[`	R09.3	`,`	Abnormal sputum Abnormal: amount colour odour Excessive (of) sputum Excl.: blood-stained sputum (R04.2) 	`,`	null	`],
	[`	R09.8	`,`	Other specified symptoms and signs involving the circulatory and respiratory systems Bruit (arterial) Chest: abnormal percussion friction sounds tympany Rales Weak pulse 	`,`	null	`],
	[`	R10	`,`	Abdominal and pelvic pain Excl.: dorsalgia (M54.-) flatulence and related conditions (R14) renal colic (N23) 	`,`	null	`],
	[`	R10.0	`,`	Acute abdomen Severe abdominal pain (generalized)(localized)(with abdominal rigidity) 	`,`	null	`],
	[`	R10.1	`,`	Pain localized to upper abdomen Dyspepsia NOS Epigastric pain Excl.: functional dyspepsia (K30) 	`,`	null	`],
	[`	R10.2	`,`	Pelvic and perineal pain 	`,`	null	`],
	[`	R10.3	`,`	Pain localized to other parts of lower abdomen 	`,`	null	`],
	[`	R10.4	`,`	Other and unspecified abdominal pain Abdominal tenderness NOS Colic: NOS infantile 	`,`	null	`],
	[`	R11	`,`	Nausea and vomiting Excl.: haematemesis (K92.0) haematemesis neonatal (P54.0) vomiting (of): excessive, in pregnancy (O21.-) following gastrointestinal surgery (K91.0) newborn (P92.0) psychogenic (F50.5) 	`,`	null	`],
	[`	R12	`,`	Heartburn Excl.: dyspepsia: NOS (R10.1) functional (K30) 	`,`	null	`],
	[`	R13	`,`	Dysphagia Incl.: Difficulty in swallowing 	`,`	null	`],
	[`	R14	`,`	Flatulence and related conditions Incl.: Abdominal distension (gaseous) Bloating Eructation Gas pain Tympanites (abdominal)(intestinal) Excl.: psychogenic aerophagy (F45.3) 	`,`	null	`],
	[`	R15	`,`	Faecal incontinence Incl.: Encopresis NOS Excl.: that of nonorganic origin (F98.1) 	`,`	null	`],
	[`	R16	`,`	Hepatomegaly and splenomegaly, not elsewhere classified 	`,`	null	`],
	[`	R16.0	`,`	Hepatomegaly, not elsewhere classified Hepatomegaly NOS 	`,`	null	`],
	[`	R16.1	`,`	Splenomegaly, not elsewhere classified Splenomegaly NOS 	`,`	null	`],
	[`	R16.2	`,`	Hepatomegaly with splenomegaly, not elsewhere classified Hepatosplenomegaly NOS 	`,`	null	`],
	[`	R17	`,`	Unspecified jaundice Excl.: neonatal jaundice (P55.-, P57-P59) 	`,`	null	`],
	[`	R18	`,`	Ascites Incl.: Fluid in peritoneal cavity 	`,`	null	`],
	[`	R19	`,`	Other symptoms and signs involving the digestive system and abdomen Excl.: acute abdomen (R10.0) 	`,`	null	`],
	[`	R19.0	`,`	Intra-abdominal and pelvic swelling, mass and lump Diffuse or generalized swelling or mass: intra-abdominal NOS pelvic NOS umbilical Excl.: abdominal distension (gaseous) (R14) ascites (R18) 	`,`	null	`],
	[`	R19.1	`,`	Abnormal bowel sounds Absent bowel sounds Hyperactive bowel sounds 	`,`	null	`],
	[`	R19.2	`,`	Visible peristalsis Hyperperistalsis 	`,`	null	`],
	[`	R19.3	`,`	Abdominal rigidity Excl.: that with severe abdominal pain (R10.0) 	`,`	null	`],
	[`	R19.4	`,`	Change in bowel habit Excl.: constipation (K59.0) functional diarrhoea (K59.1) 	`,`	null	`],
	[`	R19.5	`,`	Other faecal abnormalities Abnormal stool colour Bulky stools Mucus in stools Occult blood in stools Excl.: melaena (K92.1) melaena neonatal (P54.1) 	`,`	null	`],
	[`	R19.6	`,`	Halitosis 	`,`	null	`],
	[`	R19.8	`,`	Other specified symptoms and signs involving the digestive system and abdomen 	`,`	null	`],
	[`	R20	`,`	Disturbances of skin sensation Excl.: dissociative anaesthesia and sensory loss (F44.6) psychogenic disturbances (F45.8) 	`,`	null	`],
	[`	R20.0	`,`	Anaesthesia of skin 	`,`	null	`],
	[`	R20.1	`,`	Hypoaesthesia of skin 	`,`	null	`],
	[`	R20.2	`,`	Paraesthesia of skin Formication Pins and needles Tingling skin Excl.: acroparaesthesia (I73.8) 	`,`	null	`],
	[`	R20.3	`,`	Hyperaesthesia 	`,`	null	`],
	[`	R20.8	`,`	Other and unspecified disturbances of skin sensation 	`,`	null	`],
	[`	R21	`,`	Rash and other nonspecific skin eruption 	`,`	null	`],
	[`	R22	`,`	Localized swelling, mass and lump of skin and subcutaneous tissue Incl.: subcutaneous nodules (localized)(superficial) Excl.: abnormal findings on diagnostic imaging (R90-R93) enlarged lymph nodes (R59.-) localized adiposity (E65) mass and lump: breast (N63) intra-abdominal or pelvic (R19.0) oedema (R60.-) swelling (of): intra-abdominal or pelvic (R19.0) joint (M25.4) 	`,`	null	`],
	[`	R22.0	`,`	Localized swelling, mass and lump, head 	`,`	null	`],
	[`	R22.1	`,`	Localized swelling, mass and lump, neck 	`,`	null	`],
	[`	R22.2	`,`	Localized swelling, mass and lump, trunk 	`,`	null	`],
	[`	R22.3	`,`	Localized swelling, mass and lump, upper limb 	`,`	null	`],
	[`	R22.4	`,`	Localized swelling, mass and lump, lower limb 	`,`	null	`],
	[`	R22.7	`,`	Localized swelling, mass and lump, multiple sites 	`,`	null	`],
	[`	R22.9	`,`	Localized swelling, mass and lump, unspecified 	`,`	null	`],
	[`	R23	`,`	Other skin changes 	`,`	null	`],
	[`	R23.0	`,`	Cyanosis Excl.: acrocyanosis (I73.8) cyanotic attacks of newborn (P28.2) 	`,`	null	`],
	[`	R23.1	`,`	Pallor Clammy skin 	`,`	null	`],
	[`	R23.2	`,`	Flushing Excessive blushing Excl.: menopausal and female climacteric states (N95.1) 	`,`	null	`],
	[`	R23.3	`,`	Spontaneous ecchymoses Petechiae Excl.: ecchymoses in fetus and newborn (P54.5) purpura (D69.-) 	`,`	null	`],
	[`	R23.4	`,`	Changes in skin texture Desquamation Induration Scaling of skin Excl.: epidermal thickening NOS (L85.9) 	`,`	null	`],
	[`	R23.8	`,`	Other and unspecified skin changes 	`,`	null	`],
	[`	R25	`,`	Abnormal involuntary movements Excl.: specific movement disorders (G20-G26) stereotyped movement disorders (F98.4) tic disorders (F95.-) 	`,`	null	`],
	[`	R25.0	`,`	Abnormal head movements 	`,`	null	`],
	[`	R25.1	`,`	Tremor, unspecified Excl.: chorea NOS (G25.5) tremor: essential (G25.0) hysterical (F44.4) intention (G25.2) 	`,`	null	`],
	[`	R25.2	`,`	Cramp and spasm Excl.: carpopedal spasm (R29.0) infantile spasms (G40.4) 	`,`	null	`],
	[`	R25.3	`,`	Fasciculation Twitching NOS 	`,`	null	`],
	[`	R25.8	`,`	Other and unspecified abnormal involuntary movements 	`,`	null	`],
	[`	R26	`,`	Abnormalities of gait and mobility Excl.: ataxia: NOS (R27.0) hereditary (G11.-) locomotor (syphilitic) (A52.1) immobility syndrome (paraplegic) (M62.3) 	`,`	null	`],
	[`	R26.0	`,`	Ataxic gait Staggering gait 	`,`	null	`],
	[`	R26.1	`,`	Paralytic gait Spastic gait 	`,`	null	`],
	[`	R26.2	`,`	Difficulty in walking, not elsewhere classified 	`,`	null	`],
	[`	R26.3	`,`	Immobility Bedfast Chairfast 	`,`	null	`],
	[`	R26.8	`,`	Other and unspecified abnormalities of gait and mobility Unsteadiness on feet NOS 	`,`	null	`],
	[`	R27	`,`	Other lack of coordination Excl.: ataxic gait (R26.0) hereditary ataxia (G11.-) vertigo NOS (R42) 	`,`	null	`],
	[`	R27.0	`,`	Ataxia, unspecified 	`,`	null	`],
	[`	R27.8	`,`	Other and unspecified lack of coordination 	`,`	null	`],
	[`	R29	`,`	Other symptoms and signs involving the nervous and musculoskeletal systems 	`,`	null	`],
	[`	R29.0	`,`	Tetany Carpopedal spasm Excl.: tetany: hysterical (F44.5) neonatal (P71.3) parathyroid (E20.9) post-thyroidectomy (E89.2) 	`,`	null	`],
	[`	R29.1	`,`	Meningismus 	`,`	null	`],
	[`	R29.2	`,`	Abnormal reflex Excl.: abnormal pupillary reflex (H57.0) hyperactive gag reflex (J39.2) vasovagal reaction or syncope (R55) 	`,`	null	`],
	[`	R29.3	`,`	Abnormal posture 	`,`	null	`],
	[`	R29.4	`,`	Clicking hip Excl.: congenital deformities of hip (Q65.-) 	`,`	null	`],
	[`	R29.6	`,`	Tendency to fall, not elsewhere classified Tendency to fall because of old age or other unclear health problems Excl.: accidents (X59.-) difficulty in walking (R26.2) dizziness and giddiness (R42) falls causing injury (W00-W19) falls due to diseases classified elsewhere syncope and collapse (R55) 	`,`	null	`],
	[`	R29.8	`,`	Other and unspecified symptoms and signs involving the nervous and musculoskeletal systems 	`,`	null	`],
	[`	R30	`,`	Pain associated with micturition Excl.: psychogenic pain (F45.3) 	`,`	null	`],
	[`	R30.0	`,`	Dysuria Strangury 	`,`	null	`],
	[`	R30.1	`,`	Vesical tenesmus 	`,`	null	`],
	[`	R30.9	`,`	Painful micturition, unspecified Painful urination NOS 	`,`	null	`],
	[`	R31	`,`	Unspecified haematuria Excl.: recurrent or persistent haematuria (N02.-) 	`,`	null	`],
	[`	R32	`,`	Unspecified urinary incontinence Incl.: Enuresis NOS Excl.: nonorganic enuresis (F98.0) stress incontinence and other specified urinary incontinence (N39.3-N39.4) 	`,`	null	`],
	[`	R33	`,`	Retention of urine 	`,`	null	`],
	[`	R34	`,`	Anuria and oliguria Excl.: that complicating: abortion or ectopic or molar pregnancy (O00-O07, O08.4) pregnancy, childbirth and the puerperium (O26.8, O90.4) 	`,`	null	`],
	[`	R35	`,`	Polyuria Incl.: Frequency of micturition Nocturia Excl.: psychogenic polyuria (F45.3) 	`,`	null	`],
	[`	R36	`,`	Urethral discharge Incl.: Penile discharge Urethrorrhoea 	`,`	null	`],
	[`	R39	`,`	Other symptoms and signs involving the urinary system 	`,`	null	`],
	[`	R39.0	`,`	Extravasation of urine 	`,`	null	`],
	[`	R39.1	`,`	Other difficulties with micturition Hesitancy of micturition Poor urinary stream Splitting of urinary stream 	`,`	null	`],
	[`	R39.2	`,`	Extrarenal uraemia Prerenal uraemia 	`,`	null	`],
	[`	R39.8	`,`	Other and unspecified symptoms and signs involving the urinary system 	`,`	null	`],
	[`	R40	`,`	Somnolence, stupor and coma Excl.: coma: diabetic (E10-E14 with common fourth character .0) hepatic (K72.-) hypoglycaemic (nondiabetic) (E15) neonatal (P91.5) uraemic (N19) 	`,`	null	`],
	[`	R40.0	`,`	Somnolence Drowsiness 	`,`	null	`],
	[`	R40.1	`,`	Stupor Semicoma Excl.: stupor: catatonic (F20.2) depressive (F31-F33) dissociative (F44.2) manic (F30.2) 	`,`	null	`],
	[`	R40.2	`,`	Coma, unspecified Unconsciousness NOS 	`,`	null	`],
	[`	R41	`,`	Other symptoms and signs involving cognitive functions and awareness Excl.: dissociative [conversion] disorders (F44.-) 	`,`	null	`],
	[`	R41.0	`,`	Disorientation, unspecified Confusion NOS Excl.: psychogenic disorientation (F44.8) 	`,`	null	`],
	[`	R41.1	`,`	Anterograde amnesia 	`,`	null	`],
	[`	R41.2	`,`	Retrograde amnesia 	`,`	null	`],
	[`	R41.3	`,`	Other amnesia Amnesia NOS Excl.: amnesic syndrome: due to psychoactive substance use (F10-F19 with common fourth character .6) organic (F04) transient global amnesia (G45.4) 	`,`	null	`],
	[`	R41.8	`,`	Other and unspecified symptoms and signs involving cognitive functions and awareness 	`,`	null	`],
	[`	R42	`,`	Dizziness and giddiness Incl.: Light-headedness Vertigo NOS Excl.: vertiginous syndromes (H81.-) 	`,`	null	`],
	[`	R43	`,`	Disturbances of smell and taste 	`,`	null	`],
	[`	R43.0	`,`	Anosmia 	`,`	null	`],
	[`	R43.1	`,`	Parosmia 	`,`	null	`],
	[`	R43.2	`,`	Parageusia 	`,`	null	`],
	[`	R43.8	`,`	Other and unspecified disturbances of smell and taste Mixed disturbance of smell and taste 	`,`	null	`],
	[`	R44	`,`	Other symptoms and signs involving general sensations and perceptions Excl.: disturbances of skin sensation (R20.-) 	`,`	null	`],
	[`	R44.0	`,`	Auditory hallucinations 	`,`	null	`],
	[`	R44.1	`,`	Visual hallucinations 	`,`	null	`],
	[`	R44.2	`,`	Other hallucinations 	`,`	null	`],
	[`	R44.3	`,`	Hallucinations, unspecified 	`,`	null	`],
	[`	R44.8	`,`	Other and unspecified symptoms and signs involving general sensations and perceptions 	`,`	null	`],
	[`	R45	`,`	Symptoms and signs involving emotional state 	`,`	null	`],
	[`	R45.0	`,`	Nervousness Nervous tension 	`,`	null	`],
	[`	R45.1	`,`	Restlessness and agitation 	`,`	null	`],
	[`	R45.2	`,`	Unhappiness Worries NOS 	`,`	null	`],
	[`	R45.3	`,`	Demoralization and apathy 	`,`	null	`],
	[`	R45.4	`,`	Irritability and anger 	`,`	null	`],
	[`	R45.5	`,`	Hostility 	`,`	null	`],
	[`	R45.6	`,`	Physical violence 	`,`	null	`],
	[`	R45.7	`,`	State of emotional shock and stress, unspecified 	`,`	null	`],
	[`	R45.8	`,`	Other symptoms and signs involving emotional state Suicidal ideation (tendencies) Excl.: suicidal ideation constituting part of a mental disorder (F00-F99) 	`,`	null	`],
	[`	R46	`,`	Symptoms and signs involving appearance and behaviour 	`,`	null	`],
	[`	R46.0	`,`	Very low level of personal hygiene 	`,`	null	`],
	[`	R46.1	`,`	Bizarre personal appearance 	`,`	null	`],
	[`	R46.2	`,`	Strange and inexplicable behaviour 	`,`	null	`],
	[`	R46.3	`,`	Overactivity 	`,`	null	`],
	[`	R46.4	`,`	Slowness and poor responsiveness Excl.: stupor (R40.1) 	`,`	null	`],
	[`	R46.5	`,`	Suspiciousness and marked evasiveness 	`,`	null	`],
	[`	R46.6	`,`	Undue concern and preoccupation with stressful events 	`,`	null	`],
	[`	R46.7	`,`	Verbosity and circumstantial detail obscuring reason for contact 	`,`	null	`],
	[`	R46.8	`,`	Other symptoms and signs involving appearance and behaviour Self neglect NOS Excl.: insufficient intake of food and water due to self neglect (R63.6) 	`,`	null	`],
	[`	R47	`,`	Speech disturbances, not elsewhere classified Excl.: autism (F84.0-F84.1) cluttering (F98.6) specific developmental disorders of speech and language (F80.-) stuttering [stammering] (F98.5) 	`,`	null	`],
	[`	R47.0	`,`	Dysphasia and aphasia Excl.: progressive isolated aphasia (G31.0) 	`,`	null	`],
	[`	R47.1	`,`	Dysarthria and anarthria 	`,`	null	`],
	[`	R47.8	`,`	Other and unspecified speech disturbances 	`,`	null	`],
	[`	R48	`,`	Dyslexia and other symbolic dysfunctions, not elsewhere classified Excl.: specific developmental disorders of scholastic skills (F81.-) 	`,`	null	`],
	[`	R48.0	`,`	Dyslexia and alexia 	`,`	null	`],
	[`	R48.1	`,`	Agnosia 	`,`	null	`],
	[`	R48.2	`,`	Apraxia 	`,`	null	`],
	[`	R48.8	`,`	Other and unspecified symbolic dysfunctions Acalculia Agraphia 	`,`	null	`],
	[`	R49	`,`	Voice disturbances Excl.: psychogenic voice disturbance (F44.4) 	`,`	null	`],
	[`	R49.0	`,`	Dysphonia Hoarseness 	`,`	null	`],
	[`	R49.1	`,`	Aphonia Loss of voice 	`,`	null	`],
	[`	R49.2	`,`	Hypernasality and hyponasality 	`,`	null	`],
	[`	R49.8	`,`	Other and unspecified voice disturbances Change in voice NOS 	`,`	null	`],
	[`	R50	`,`	Fever of other and unknown origin Excl.: fever of unknown origin (during)(in): labour (O75.2) newborn (P81.9) puerperal pyrexia NOS (O86.4) 	`,`	null	`],
	[`	R50.2	`,`	Drug-induced fever Use additional external cause code (Chapter XX), if desired, to identify drug. 	`,`	null	`],
	[`	R50.8	`,`	Other specified fever Fever with chills Fever with rigors Persistent fever 	`,`	null	`],
	[`	R50.9	`,`	Fever, unspecified Hyperpyrexia NOS Pyrexia NOS Excl.: malignant hyperthermia due to anaesthesia (T88.3) 	`,`	null	`],
	[`	R51	`,`	Headache Incl.: Facial pain NOS Excl.: atypical facial pain (G50.1) migraine and other headache syndromes (G43-G44) trigeminal neuralgia (G50.0) 	`,`	null	`],
	[`	R52	`,`	Pain, not elsewhere classified Incl.: pain not referable to any one organ or body region Excl.: chronic pain personality syndrome (F62.8) headache (R51) pain (in): abdomen (R10.-) back (M54.9) breast (N64.4) chest (R07.1-R07.4) ear (H92.0) eye (H57.1) joint (M25.5) limb (M79.6) lumbar region (M54.5) pelvic and perineal (R10.2) psychogenic (F45.4) shoulder (M25.5) spine (M54.-) throat (R07.0) tongue (K14.6) tooth (K08.8) renal colic (N23) 	`,`	null	`],
	[`	R52.0	`,`	Acute pain 	`,`	null	`],
	[`	R52.1	`,`	Chronic intractable pain 	`,`	null	`],
	[`	R52.2	`,`	Other chronic pain 	`,`	null	`],
	[`	R52.9	`,`	Pain, unspecified Generalized pain NOS 	`,`	null	`],
	[`	R53	`,`	Malaise and fatigue Incl.: Asthenia NOS Debility: NOS chronic General physical deterioration Lethargy Tiredness Excl.: debility: congenital (P96.9) senile (R54) exhaustion and fatigue (due to)(in): combat (F43.0) excessive exertion (T73.3) exposure (T73.2) heat (T67.-) neurasthenia (F48.0) pregnancy (O26.8) senile asthenia (R54) fatigue syndrome (F48.0) fatigue syndrome postviral (G93.3) 	`,`	null	`],
	[`	R54	`,`	Senility Incl.: Old age Senescence without mention of psychosis Senile: asthenia debility Excl.: senile psychosis (F03) 	`,`	null	`],
	[`	R55	`,`	Syncope and collapse Incl.: Blackout Fainting Excl.: neurocirculatory asthenia (F45.3) orthostatic hypotension (I95.1) neurogenic orthostatic hypotension (G90.3) shock: NOS (R57.9) cardiogenic (R57.0) complicating or following: abortion or ectopic or molar pregnancy (O00-O07, O08.3) labour and delivery (O75.1) postoperative (T81.1) Stokes-Adams attack (I45.9) syncope: carotid sinus (G90.0) heat (T67.1) psychogenic (F48.8) unconsciousness NOS (R40.2) 	`,`	null	`],
	[`	R56	`,`	Convulsions, not elsewhere classified Excl.: convulsions and seizures (in): dissociative (F44.5) epilepsy (G40-G41) newborn (P90) 	`,`	null	`],
	[`	R56.0	`,`	Febrile convulsions 	`,`	null	`],
	[`	R56.8	`,`	Other and unspecified convulsions Fit NOS Seizure (convulsive) NOS 	`,`	null	`],
	[`	R57	`,`	Shock, not elsewhere classified Excl.: shock (due to): anaesthesia (T88.2) anaphylactic (due to): NOS (T78.2) adverse food reaction (T78.0) serum (T80.5) complicating or following abortion or ectopic or molar pregnancy (O00-O07, O08.3) electric (T75.4) lightning (T75.0) obstetric (O75.1) postoperative (T81.1) psychic (F43.0) traumatic (T79.4) toxic shock syndrome (A48.3) 	`,`	null	`],
	[`	R57.0	`,`	Cardiogenic shock 	`,`	null	`],
	[`	R57.1	`,`	Hypovolaemic shock 	`,`	null	`],
	[`	R57.2	`,`	Septic shock 	`,`	null	`],
	[`	R57.8	`,`	Other shock Endotoxic shock 	`,`	null	`],
	[`	R57.9	`,`	Shock, unspecified Failure of peripheral circulation NOS 	`,`	null	`],
	[`	R58	`,`	Haemorrhage, not elsewhere classified Incl.: Haemorrhage NOS 	`,`	null	`],
	[`	R59	`,`	Enlarged lymph nodes Incl.: swollen glands Excl.: lymphadenitis: NOS (I88.9) acute (L04.-) chronic (I88.1) mesenteric (acute)(chronic) (I88.0) 	`,`	null	`],
	[`	R59.0	`,`	Localized enlarged lymph nodes 	`,`	null	`],
	[`	R59.1	`,`	Generalized enlarged lymph nodes Lymphadenopathy NOS Excl.: HIV disease resulting in (persistent) generalized lymphadenopathy (B23.1) 	`,`	null	`],
	[`	R59.9	`,`	Enlarged lymph nodes, unspecified 	`,`	null	`],
	[`	R60	`,`	Oedema, not elsewhere classified Excl.: ascites (R18) hydrops fetalis NOS (P83.2) hydrothorax (J94.8) oedema (of): angioneurotic (T78.3) cerebral (G93.6) cerebral due to birth injury (P11.0) gestational (O12.0) hereditary (Q82.0) larynx (J38.4) malnutrition (E40-E46) nasopharynx (J39.2) newborn (P83.3) pharynx (J39.2) pulmonary (J81) 	`,`	null	`],
	[`	R60.0	`,`	Localized oedema 	`,`	null	`],
	[`	R60.1	`,`	Generalized oedema 	`,`	null	`],
	[`	R60.9	`,`	Oedema, unspecified Fluid retention NOS 	`,`	null	`],
	[`	R61	`,`	Hyperhidrosis 	`,`	null	`],
	[`	R61.0	`,`	Localized hyperhidrosis 	`,`	null	`],
	[`	R61.1	`,`	Generalized hyperhidrosis 	`,`	null	`],
	[`	R61.9	`,`	Hyperhidrosis, unspecified Excessive sweating Night sweats 	`,`	null	`],
	[`	R62	`,`	Lack of expected normal physiological development Excl.: delayed puberty (E30.0) 	`,`	null	`],
	[`	R62.0	`,`	Delayed milestone Delayed attainment of expected physiological developmental stage Late: talker walker 	`,`	null	`],
	[`	R62.8	`,`	Other lack of expected normal physiological development Failure to: gain weight thrive Infantilism NOS Lack of growth Physical retardation Excl.: HIV disease resulting in failure to thrive (B22.2) physical retardation due to malnutrition (E45) 	`,`	null	`],
	[`	R62.9	`,`	Lack of expected normal physiological development, unspecified 	`,`	null	`],
	[`	R63	`,`	Symptoms and signs concerning food and fluid intake Excl.: bulimia NOS (F50.2) eating disorders of nonorganic origin (F50.-) malnutrition (E40-E46) 	`,`	null	`],
	[`	R63.0	`,`	Anorexia Loss of appetite Excl.: anorexia nervosa (F50.0) loss of appetite of nonorganic origin (F50.8) 	`,`	null	`],
	[`	R63.1	`,`	Polydipsia Excessive thirst 	`,`	null	`],
	[`	R63.2	`,`	Polyphagia Excessive eating Hyperalimentation NOS 	`,`	null	`],
	[`	R63.3	`,`	Feeding difficulties and mismanagement Feeding problem NOS Excl.: feeding problems of newborn (P92.-) infant feeding disorder of nonorganic origin (F98.2) 	`,`	null	`],
	[`	R63.4	`,`	Abnormal weight loss 	`,`	null	`],
	[`	R63.5	`,`	Abnormal weight gain Excl.: excessive weight gain in pregnancy (O26.0) obesity (E66.-) 	`,`	null	`],
	[`	R63.6	`,`	Insufficient intake of food and water due to self neglect Excl.: starvation due to anorexia (R63.0) starvation due to privation of food (X53) thirst due to privation of water (X54) self neglect NOS (R46.8) 	`,`	null	`],
	[`	R63.8	`,`	Other symptoms and signs concerning food and fluid intake 	`,`	null	`],
	[`	R64	`,`	Cachexia Excl.: HIV disease resulting in wasting syndrome (B22.2) malignant cachexia (C80.-) nutritional marasmus (E41) 	`,`	null	`],
	[`	R65	`,`	Systemic Inflammatory Response Syndrome [SIRS] Note: This category should never be used in primary coding. The category is for use in multiple coding to identify this condition resulting from any cause. A code from another chapter should be assigned first to indicate the cause or underlying disease. 	`,`	null	`],
	[`	R65.0	`,`	Systemic Inflammatory Response Syndrome of infectious origin without organ failure 	`,`	null	`],
	[`	R65.1	`,`	Systemic Inflammatory Response Syndrome of infectious origin with organ failure Severe sepsis 	`,`	null	`],
	[`	R65.2	`,`	Systemic Inflammatory Response Syndrome of non-infectious origin without organ failure 	`,`	null	`],
	[`	R65.3	`,`	Systemic Inflammatory Response Syndrome of non-infectious origin with organ failure 	`,`	null	`],
	[`	R65.9	`,`	Systemic Inflammatory Response Syndrome, unspecified 	`,`	null	`],
	[`	R68	`,`	Other general symptoms and signs 	`,`	null	`],
	[`	R68.0	`,`	Hypothermia, not associated with low environmental temperature Excl.: hypothermia (due to)(of): NOS (accidental) (T68) anaesthesia (T88.5) low environmental temperature (T68) newborn (P80.-) 	`,`	null	`],
	[`	R68.1	`,`	Nonspecific symptoms peculiar to infancy Excessive crying of infant Irritable infant Excl.: neonatal cerebral irritability (P91.3) teething syndrome (K00.7) 	`,`	null	`],
	[`	R68.2	`,`	Dry mouth, unspecified Excl.: dry mouth due to: dehydration (E86) sicca syndrome [Sjogren] (M35.0) salivary gland hyposecretion (K11.7) 	`,`	null	`],
	[`	R68.3	`,`	Clubbing of fingers Clubbing of nails Excl.: congenital clubfinger (Q68.1) congenital clubnail (Q84.6) 	`,`	null	`],
	[`	R68.8	`,`	Other specified general symptoms and signs 	`,`	null	`],
	[`	R69	`,`	Unknown and unspecified causes of morbidity Incl.: Illness NOS Undiagnosed disease, not specified as to the site or system involved 	`,`	null	`],
	[`	R70	`,`	Elevated erythrocyte sedimentation rate and abnormality of plasma viscosity 	`,`	null	`],
	[`	R70.0	`,`	Elevated erythrocyte sedimentation rate 	`,`	null	`],
	[`	R70.1	`,`	Abnormal plasma viscosity 	`,`	null	`],
	[`	R71	`,`	Abnormality of red blood cells Incl.: Abnormal red-cell: morphology NOS volume NOS Anisocytosis Poikilocytosis Excl.: anaemias (D50-D64) polycythaemia: NOS (D75.1) benign (familial) (D75.0) neonatorum (P61.1) secondary (D75.1) vera (D45) 	`,`	null	`],
	[`	R72	`,`	Abnormality of white blood cells, not elsewhere classified Incl.: Abnormal leukocyte differential NOS Excl.: leukocytosis (D72.8) 	`,`	null	`],
	[`	R73	`,`	Elevated blood glucose level Excl.: diabetes mellitus (E10-E14) diabetes mellitus in pregnancy, childbirth and the puerperium (O24.-) neonatal disorders (P70.0-P70.2) postsurgical hypoinsulinaemia (E89.1) 	`,`	null	`],
	[`	R73.0	`,`	Abnormal glucose tolerance test Diabetes: chemical latent Impaired glucose tolerance Prediabetes 	`,`	null	`],
	[`	R73.9	`,`	Hyperglycaemia, unspecified 	`,`	null	`],
	[`	R74	`,`	Abnormal serum enzyme levels 	`,`	null	`],
	[`	R74.0	`,`	Elevation of levels of transaminase and lactic acid dehydrogenase [LDH] 	`,`	null	`],
	[`	R74.8	`,`	Abnormal levels of other serum enzymes Abnormal level of: acid phosphatase alkaline phosphatase amylase lipase [triacylglycerol lipase] 	`,`	null	`],
	[`	R74.9	`,`	Abnormal level of unspecified serum enzyme 	`,`	null	`],
	[`	R75	`,`	Laboratory evidence of human immunodeficiency virus [HIV] Incl.: Nonconclusive HIV-test finding in infants Excl.: asymptomatic human immunodeficiency virus [HIV] infection status (Z21) human immunodeficiency virus [HIV] disease (B20-B24) human immunodeficiency virus [HIV] disease complicating pregnancy, childbirth and the puerperium (O98.7) 	`,`	null	`],
	[`	R76	`,`	Other abnormal immunological findings in serum 	`,`	null	`],
	[`	R76.0	`,`	Raised antibody titre Excl.: isoimmunization, in pregnancy (O36.0-O36.1) isoimmunization, in pregnancy affecting fetus or newborn (P55.-) 	`,`	null	`],
	[`	R76.1	`,`	Abnormal reaction to tuberculin test Abnormal result of Mantoux test 	`,`	null	`],
	[`	R76.2	`,`	False-positive serological test for syphilis False-positive Wassermann reaction 	`,`	null	`],
	[`	R76.8	`,`	Other specified abnormal immunological findings in serum Raised level of immunoglobulins NOS 	`,`	null	`],
	[`	R76.9	`,`	Abnormal immunological finding in serum, unspecified 	`,`	null	`],
	[`	R77	`,`	Other abnormalities of plasma proteins Excl.: disorders of plasma-protein metabolism (E88.0) 	`,`	null	`],
	[`	R77.0	`,`	Abnormality of albumin 	`,`	null	`],
	[`	R77.1	`,`	Abnormality of globulin Hyperglobulinaemia NOS 	`,`	null	`],
	[`	R77.2	`,`	Abnormality of alphafetoprotein 	`,`	null	`],
	[`	R77.8	`,`	Other specified abnormalities of plasma proteins 	`,`	null	`],
	[`	R77.9	`,`	Abnormality of plasma protein, unspecified 	`,`	null	`],
	[`	R78	`,`	Findings of drugs and other substances, not normally found in blood Excl.: mental and behavioural disorders due to psychoactive substance use (F10-F19) 	`,`	null	`],
	[`	R78.0	`,`	Finding of alcohol in blood Use additional external cause code (Y90), if desired, for detail regarding alcohol level. 	`,`	null	`],
	[`	R78.1	`,`	Finding of opiate drug in blood 	`,`	null	`],
	[`	R78.2	`,`	Finding of cocaine in blood 	`,`	null	`],
	[`	R78.3	`,`	Finding of hallucinogen in blood 	`,`	null	`],
	[`	R78.4	`,`	Finding of other drugs of addictive potential in blood 	`,`	null	`],
	[`	R78.5	`,`	Finding of psychotropic drug in blood 	`,`	null	`],
	[`	R78.6	`,`	Finding of steroid agent in blood 	`,`	null	`],
	[`	R78.7	`,`	Finding of abnormal level of heavy metals in blood 	`,`	null	`],
	[`	R78.8	`,`	Finding of other specified substances, not normally found in blood Finding of abnormal level of lithium in blood 	`,`	null	`],
	[`	R78.9	`,`	Finding of unspecified substance, not normally found in blood 	`,`	null	`],
	[`	R79	`,`	Other abnormal findings of blood chemistry Excl.: abnormality of fluid, electrolyte or acid-base balance (E86-E87) asymptomatic hyperuricaemia (E79.0) hyperglycaemia NOS (R73.9) hypoglycaemia NOS (E16.2) hypoglycaemia NOS neonatal (P70.3-P70.4) specific findings indicating disorder of: amino-acid metabolism (E70-E72) carbohydrate metabolism (E73-E74) lipid metabolism (E75.-) 	`,`	null	`],
	[`	R79.0	`,`	Abnormal level of blood mineral Abnormal blood level of: cobalt copper iron magnesium mineral NEC zinc Excl.: abnormal level of lithium (R78.8) disorders of mineral metabolism (E83.-) neonatal hypomagnesaemia (P71.2) nutritional mineral deficiency (E58-E61) 	`,`	null	`],
	[`	R79.8	`,`	Other specified abnormal findings of blood chemistry Abnormal blood-gas level 	`,`	null	`],
	[`	R79.9	`,`	Abnormal finding of blood chemistry, unspecified 	`,`	null	`],
	[`	R80	`,`	Isolated proteinuria Incl.: Albuminuria NOS Bence Jones proteinuria Proteinuria NOS Excl.: proteinuria: gestational (O12.1) isolated, with specified morphological lesion (N06.-) orthostatic (N39.2) persistent (N39.1) 	`,`	null	`],
	[`	R81	`,`	Glycosuria Excl.: renal glycosuria (E74.8) 	`,`	null	`],
	[`	R82	`,`	Other abnormal findings in urine Excl.: haematuria (R31) 	`,`	null	`],
	[`	R82.0	`,`	Chyluria Excl.: filarial chyluria (B74.-) 	`,`	null	`],
	[`	R82.1	`,`	Myoglobinuria 	`,`	null	`],
	[`	R82.2	`,`	Biliuria 	`,`	null	`],
	[`	R82.3	`,`	Haemoglobinuria Excl.: haemoglobinuria: due to haemolysis from external causes NEC (D59.6) paroxysmal nocturnal [Marchiafava-Micheli] (D59.5) 	`,`	null	`],
	[`	R82.4	`,`	Acetonuria Ketonuria 	`,`	null	`],
	[`	R82.5	`,`	Elevated urine levels of drugs, medicaments and biological substances Elevated urine levels of: catecholamines indoleacetic acid 17-ketosteroids steroids 	`,`	null	`],
	[`	R82.6	`,`	Abnormal urine levels of substances chiefly nonmedicinal as to source Abnormal urine level of heavy metals 	`,`	null	`],
	[`	R82.7	`,`	Abnormal findings on microbiological examination of urine Positive culture findings 	`,`	null	`],
	[`	R82.8	`,`	Abnormal findings on cytological and histological examination of urine 	`,`	null	`],
	[`	R82.9	`,`	Other and unspecified abnormal findings in urine Cells and casts in urine Crystalluria Melanuria 	`,`	null	`],
	[`	0	`,`	Abnormal level of enzymes 	`,`	null	`],
	[`	0.1	`,`	Abnormal level of hormones 	`,`	null	`],
	[`	0.2	`,`	Abnormal level of other drugs, medicaments and biological substances 	`,`	null	`],
	[`	0.3	`,`	Abnormal level of substances chiefly nonmedicinal as to source 	`,`	null	`],
	[`	0.4	`,`	Abnormal immunological findings 	`,`	null	`],
	[`	0.5	`,`	Abnormal microbiological findings Positive culture findings 	`,`	null	`],
	[`	0.6	`,`	Abnormal cytological findings Abnormal Papanicolaou smear 	`,`	null	`],
	[`	0.7	`,`	Abnormal histological findings 	`,`	null	`],
	[`	0.8	`,`	Other abnormal findings Abnormal chromosomal findings 	`,`	null	`],
	[`	0.9	`,`	Unspecified abnormal finding 	`,`	null	`],
	[`	R83	`,`	Abnormal findings in cerebrospinal fluid [See before R83 for subdivisions] 	`,`	null	`],
	[`	R84	`,`	Abnormal findings in specimens from respiratory organs and thorax [See before R83 for subdivisions] Incl.: Abnormal findings in: bronchial washings nasal secretions pleural fluid sputum throat scrapings Excl.: blood-stained sputum (R04.2) 	`,`	null	`],
	[`	R85	`,`	Abnormal findings in specimens from digestive organs and abdominal cavity [See before R83 for subdivisions] Incl.: Abnormal findings in: peritoneal fluid saliva Excl.: faecal abnormalities (R19.5) 	`,`	null	`],
	[`	R86	`,`	Abnormal findings in specimens from male genital organs [See before R83 for subdivisions] Incl.: Abnormal findings in: prostatic secretions semen, seminal fluid Abnormal spermatozoa Excl.: azoospermia (N46) oligospermia (N46) 	`,`	null	`],
	[`	R87	`,`	Abnormal findings in specimens from female genital organs [See before R83 for subdivisions] Incl.: Abnormal findings in secretions and smears from: cervix uteri vagina vulva Excl.: carcinoma in situ (D05-D07.3) dysplasia of: cervix uteri (N87.-) vagina (N89.0-N89.3) vulva (N90.0-N90.3) 	`,`	null	`],
	[`	R89	`,`	Abnormal findings in specimens from other organs, systems and tissues [See before R83 for subdivisions] Incl.: Abnormal findings in: nipple discharge synovial fluid wound secretions 	`,`	null	`],
	[`	R90	`,`	Abnormal findings on diagnostic imaging of central nervous system 	`,`	null	`],
	[`	R90.0	`,`	Intracranial space-occupying lesion 	`,`	null	`],
	[`	R90.8	`,`	Other abnormal findings on diagnostic imaging of central nervous system Abnormal echoencephalogram White matter disease NOS 	`,`	null	`],
	[`	R91	`,`	Abnormal findings on diagnostic imaging of lung Incl.: Coin lesion NOS Lung mass NOS 	`,`	null	`],
	[`	R92	`,`	Abnormal findings on diagnostic imaging of breast 	`,`	null	`],
	[`	R93	`,`	Abnormal findings on diagnostic imaging of other body structures 	`,`	null	`],
	[`	R93.0	`,`	Abnormal findings on diagnostic imaging of skull and head, not elsewhere classified Excl.: intracranial space-occupying lesion (R90.0) 	`,`	null	`],
	[`	R93.1	`,`	Abnormal findings on diagnostic imaging of heart and coronary circulation Abnormal: echocardiogram NOS heart shadow 	`,`	null	`],
	[`	R93.2	`,`	Abnormal findings on diagnostic imaging of liver and biliary tract Nonvisualization of gallbladder 	`,`	null	`],
	[`	R93.3	`,`	Abnormal findings on diagnostic imaging of other parts of digestive tract 	`,`	null	`],
	[`	R93.4	`,`	Abnormal findings on diagnostic imaging of urinary organs Filling defect of: bladder kidney ureter Excl.: hypertrophy of kidney (N28.8) 	`,`	null	`],
	[`	R93.5	`,`	Abnormal findings on diagnostic imaging of other abdominal regions, including retroperitoneum 	`,`	null	`],
	[`	R93.6	`,`	Abnormal findings on diagnostic imaging of limbs Excl.: abnormal finding in skin and subcutaneous tissue (R93.8) 	`,`	null	`],
	[`	R93.7	`,`	Abnormal findings on diagnostic imaging of other parts of musculoskeletal system Excl.: abnormal findings on diagnostic imaging of skull (R93.0) 	`,`	null	`],
	[`	R93.8	`,`	Abnormal findings on diagnostic imaging of other specified body structures Abnormal radiological finding in skin and subcutaneous tissue Mediastinal shift 	`,`	null	`],
	[`	R94	`,`	Abnormal results of function studies Incl.: abnormal results of: radionuclide [radioisotope] uptake studies scintigraphy 	`,`	null	`],
	[`	R94.0	`,`	Abnormal results of function studies of central nervous system Abnormal electroencephalogram [EEG] 	`,`	null	`],
	[`	R94.1	`,`	Abnormal results of function studies of peripheral nervous system and special senses Abnormal: electromyogram [EMG] electro-oculogram [EOG] electroretinogram [ERG] response to nerve stimulation visually evoked potential [VEP] 	`,`	null	`],
	[`	R94.2	`,`	Abnormal results of pulmonary function studies Reduced: ventilatory capacity vital capacity 	`,`	null	`],
	[`	R94.3	`,`	Abnormal results of cardiovascular function studies Abnormal: electrocardiogram [ECG][EKG] electrophysiological intracardiac studies phonocardiogram vectorcardiogram 	`,`	null	`],
	[`	R94.4	`,`	Abnormal results of kidney function studies Abnormal renal function test 	`,`	null	`],
	[`	R94.5	`,`	Abnormal results of liver function studies 	`,`	null	`],
	[`	R94.6	`,`	Abnormal results of thyroid function studies 	`,`	null	`],
	[`	R94.7	`,`	Abnormal results of other endocrine function studies Excl.: abnormal glucose tolerance test (R73.0) 	`,`	null	`],
	[`	R94.8	`,`	Abnormal results of function studies of other organs and systems Abnormal: basal metabolic rate [BMR] bladder function test splenic function test 	`,`	null	`],
	[`	R95	`,`	Sudden infant death syndrome 	`,`	null	`],
	[`	R95.0	`,`	Sudden infant death syndrome with mention of autopsy 	`,`	null	`],
	[`	R95.9	`,`	Sudden infant death syndrome without mention of autopsy Sudden infant death syndrome, unspecified 	`,`	null	`],
	[`	R96	`,`	Other sudden death, cause unknown Excl.: sudden: cardiac death, so described (I46.1) infant death syndrome (R95.-) 	`,`	null	`],
	[`	R96.0	`,`	Instantaneous death Sudden unexplained death in adult Excl.: Sudden death of known aetiology (A00.0-Q99.9, U04.9, V01.0-Y89.9) 	`,`	null	`],
	[`	R96.1	`,`	Death occurring less than 24 hours from onset of symptoms, not otherwise explained Death known not to be violent or instantaneous for which no cause can be discovered Death without sign of disease 	`,`	null	`],
	[`	R98	`,`	Unattended death Incl.: Death in circumstances where the body of the deceased was found and no cause could be discovered Found dead 	`,`	null	`],
	[`	R99	`,`	Other ill-defined and unspecified causes of mortality Incl.: Death NOS Unknown cause of mortality 	`,`	null	`],
							
];							
						
							
				
	
let CodeRangeR ={
	f0:function(val1=(-1),val2=(0)){
		let Range1 = RCodes.slice(val1,val2);
		Range1.reverse();
		document.documentElement.innerHTML += `<br>Showing R Codes ${Range1.length} items(s)`;

		for(value1 in Range1){
			    document.documentElement.style.cssText += "background-color:tan;";
				document.getElementById('rcodesTR').outerHTML += `<tr><td style="background-color:navy;color:white;width:5%;padding:40px;border:2px solid white;font-weight:900;font-size:40px;text-align:center;">${Range1[value1][0]}</td><td style="background-color:black;color:white;width:90%;padding:20px;border:2px solid white;font-size:30px;">${Range1[value1][1]}</td><td style="background-color:navy;color:white;width:5%;padding:20px;border:2px solid white;font-weight:900;font-size:40px;text-align:center;">${Range1[value1][2]}</td></tr>`;			
		}

	},

};

	






	






