							
							
let SCodes = [							
	[`	ID	`,`SYPTOMS / PROBLEMS / ISSUES `,`	SYSTEM	`],
	[`	S00	`,`	Superficial injury of head Excl.: cerebral contusion (diffuse) (S06.2) focal cerebral contusion (diffuse) (S06.3) injury of eye and orbit (S05.-) 	`,`	null	`],
	[`	S00.0	`,`	Superficial injury of scalp 	`,`	null	`],
	[`	S00.1	`,`	Contusion of eyelid and periocular area Black eye Excl.: contusion of eyeball and orbital tissues (S05.1) 	`,`	null	`],
	[`	S00.2	`,`	Other superficial injuries of eyelid and periocular area Excl.: superficial injury of conjunctiva and cornea (S05.0) 	`,`	null	`],
	[`	S00.3	`,`	Superficial injury of nose 	`,`	null	`],
	[`	S00.4	`,`	Superficial injury of ear 	`,`	null	`],
	[`	S00.5	`,`	Superficial injury of lip and oral cavity 	`,`	null	`],
	[`	S00.7	`,`	Multiple superficial injuries of head 	`,`	null	`],
	[`	S00.8	`,`	Superficial injury of other parts of head 	`,`	null	`],
	[`	S00.9	`,`	Superficial injury of head, part unspecified 	`,`	null	`],
	[`	S01	`,`	Open wound of head Excl.: decapitation (S18) injury of eye and orbit (S05.-) traumatic amputation of part of head (S08.-) 	`,`	null	`],
	[`	S01.0	`,`	Open wound of scalp Excl.: avulsion of scalp (S08.0) 	`,`	null	`],
	[`	S01.1	`,`	Open wound of eyelid and periocular area Open wound of eyelid and periocular area with or without involvement of lacrimal passages 	`,`	null	`],
	[`	S01.2	`,`	Open wound of nose 	`,`	null	`],
	[`	S01.3	`,`	Open wound of ear 	`,`	null	`],
	[`	S01.4	`,`	Open wound of cheek and temporomandibular area 	`,`	null	`],
	[`	S01.5	`,`	Open wound of lip and oral cavity Excl.: tooth: dislocation (S03.2) fracture (S02.5) 	`,`	null	`],
	[`	S01.7	`,`	Multiple open wounds of head 	`,`	null	`],
	[`	S01.8	`,`	Open wound of other parts of head 	`,`	null	`],
	[`	S01.9	`,`	Open wound of head, part unspecified 	`,`	null	`],
	[`	S02	`,`	Fracture of skull and facial bones Note: For primary coding of fracture of skull and facial bones with associated intracranial injury, reference should be made to the morbidity or mortality coding rules and guidelines in Volume 2. The following subdivisions are provided for optional use in a supplementary character position where it is not possible or not desired to use multiple coding to identify fracture and open wound; a fracture not indicated as closed or open should be classified as closed. 0 closed 1 open 	`,`	null	`],
	[`	S02.0	`,`	Fracture of vault of skull Frontal bone Parietal bone 	`,`	null	`],
	[`	S02.1	`,`	Fracture of base of skull Fossa: anterior middle posterior Occiput Orbital roof Sinus: ethmoid frontal Sphenoid Temporal bone Excl.: orbit NOS (S02.8) orbital floor (S02.3) 	`,`	null	`],
	[`	S02.2	`,`	Fracture of nasal bones 	`,`	null	`],
	[`	S02.3	`,`	Fracture of orbital floor Excl.: orbit NOS (S02.8) orbital roof (S02.1) 	`,`	null	`],
	[`	S02.4	`,`	Fracture of malar and maxillary bones Superior maxilla Upper jaw (bone) Zygoma 	`,`	null	`],
	[`	S02.5	`,`	Fracture of tooth Broken tooth 	`,`	null	`],
	[`	S02.6	`,`	Fracture of mandible Lower jaw (bone) 	`,`	null	`],
	[`	S02.7	`,`	Multiple fractures involving skull and facial bones 	`,`	null	`],
	[`	S02.8	`,`	Fractures of other skull and facial bones Alveolus Orbit NOS Palate Excl.: orbital: floor (S02.3) roof (S02.1) 	`,`	null	`],
	[`	S02.9	`,`	Fracture of skull and facial bones, part unspecified 	`,`	null	`],
	[`	S03	`,`	Dislocation, sprain and strain of joints and ligaments of head 	`,`	null	`],
	[`	S03.0	`,`	Dislocation of jaw Jaw (cartilage)(meniscus) Mandible Temporomandibular (joint) 	`,`	null	`],
	[`	S03.1	`,`	Dislocation of septal cartilage of nose 	`,`	null	`],
	[`	S03.2	`,`	Dislocation of tooth 	`,`	null	`],
	[`	S03.3	`,`	Dislocation of other and unspecified parts of head 	`,`	null	`],
	[`	S03.4	`,`	Sprain and strain of jaw Temporomandibular (joint)(ligament) 	`,`	null	`],
	[`	S03.5	`,`	Sprain and strain of joints and ligaments of other and unspecified parts of head 	`,`	null	`],
	[`	S04	`,`	Injury of cranial nerves 	`,`	null	`],
	[`	S04.0	`,`	Injury of optic nerve and pathways Optic chiasm 2nd cranial nerve Visual cortex 	`,`	null	`],
	[`	S04.1	`,`	Injury of oculomotor nerve 3rd cranial nerve 	`,`	null	`],
	[`	S04.2	`,`	Injury of trochlear nerve 4th cranial nerve 	`,`	null	`],
	[`	S04.3	`,`	Injury of trigeminal nerve 5th cranial nerve 	`,`	null	`],
	[`	S04.4	`,`	Injury of abducent nerve 6th cranial nerve 	`,`	null	`],
	[`	S04.5	`,`	Injury of facial nerve 7th cranial nerve 	`,`	null	`],
	[`	S04.6	`,`	Injury of acoustic nerve Auditory nerve 8th cranial nerve 	`,`	null	`],
	[`	S04.7	`,`	Injury of accessory nerve 11th cranial nerve 	`,`	null	`],
	[`	S04.8	`,`	Injury of other cranial nerves Glossopharyngeal [9th] nerve Hypoglossal [12th] nerve Olfactory [1st] nerve Vagus [10th] nerve 	`,`	null	`],
	[`	S04.9	`,`	Injury of unspecified cranial nerve 	`,`	null	`],
	[`	S05	`,`	Injury of eye and orbit Excl.: injury of: oculomotor [3rd] nerve (S04.1) optic [2nd] nerve (S04.0) open wound of eyelid and periocular area (S01.1) orbital bone fracture (S02.1, S02.3, S02.8) superficial injury of eyelid (S00.1-S00.2) 	`,`	null	`],
	[`	S05.0	`,`	Injury of conjunctiva and corneal abrasion without mention of foreign body Excl.: foreign body in: conjunctival sac (T15.1) cornea (T15.0) 	`,`	null	`],
	[`	S05.1	`,`	Contusion of eyeball and orbital tissues Traumatic hyphaema Excl.: black eye (S00.1) contusion of eyelid and periocular area (S00.1) 	`,`	null	`],
	[`	S05.2	`,`	Ocular laceration and rupture with prolapse or loss of intraocular tissue 	`,`	null	`],
	[`	S05.3	`,`	Ocular laceration without prolapse or loss of intraocular tissue Laceration of eye NOS 	`,`	null	`],
	[`	S05.4	`,`	Penetrating wound of orbit with or without foreign body Excl.: retained (old) foreign body following penetrating wound of orbit (H05.5) 	`,`	null	`],
	[`	S05.5	`,`	Penetrating wound of eyeball with foreign body Excl.: retained (old) intraocular foreign body (H44.6-H44.7) 	`,`	null	`],
	[`	S05.6	`,`	Penetrating wound of eyeball without foreign body Ocular penetration NOS 	`,`	null	`],
	[`	S05.7	`,`	Avulsion of eye Traumatic enucleation 	`,`	null	`],
	[`	S05.8	`,`	Other injuries of eye and orbit Lacrimal duct injury 	`,`	null	`],
	[`	S05.9	`,`	Injury of eye and orbit, unspecified Injury of eye NOS 	`,`	null	`],
	[`	S06	`,`	Intracranial injury Note: For primary coding of intracranial injuries with associated fractures, reference should be made to the morbidity or mortality coding rules and guidelines in Volume 2. The following subdivisions are provided for optional use in a supplementary character position where it is not possible or not desired to use multiple coding to identify intracranial injury and open wound: 0 without open intracranial wound 1 with open intracranial wound 	`,`	null	`],
	[`	S06.0	`,`	Concussion Commotio cerebri 	`,`	null	`],
	[`	S06.1	`,`	Traumatic cerebral oedema 	`,`	null	`],
	[`	S06.2	`,`	Diffuse brain injury Cerebral: contusion NOS laceration NOS Traumatic compression of brain NOS 	`,`	null	`],
	[`	S06.3	`,`	Focal brain injury Focal: cerebral: contusion laceration traumatic intracerebral haemorrhage 	`,`	null	`],
	[`	S06.4	`,`	Epidural haemorrhage Extradural haemorrhage (traumatic) 	`,`	null	`],
	[`	S06.5	`,`	Traumatic subdural haemorrhage 	`,`	null	`],
	[`	S06.6	`,`	Traumatic subarachnoid haemorrhage 	`,`	null	`],
	[`	S06.7	`,`	Intracranial injury with prolonged coma 	`,`	null	`],
	[`	S06.8	`,`	Other intracranial injuries Traumatic haemorrhage: cerebellar intracranial NOS 	`,`	null	`],
	[`	S06.9	`,`	Intracranial injury, unspecified Brain injury NOS Excl.: head injury NOS (S09.9) 	`,`	null	`],
	[`	S07	`,`	Crushing injury of head 	`,`	null	`],
	[`	S07.0	`,`	Crushing injury of face 	`,`	null	`],
	[`	S07.1	`,`	Crushing injury of skull 	`,`	null	`],
	[`	S07.8	`,`	Crushing injury of other parts of head 	`,`	null	`],
	[`	S07.9	`,`	Crushing injury of head, part unspecified 	`,`	null	`],
	[`	S08	`,`	Traumatic amputation of part of head 	`,`	null	`],
	[`	S08.0	`,`	Avulsion of scalp 	`,`	null	`],
	[`	S08.1	`,`	Traumatic amputation of ear 	`,`	null	`],
	[`	S08.8	`,`	Traumatic amputation of other parts of head 	`,`	null	`],
	[`	S08.9	`,`	Traumatic amputation of unspecified part of head Excl.: decapitation (S18) 	`,`	null	`],
	[`	S09	`,`	Other and unspecified injuries of head 	`,`	null	`],
	[`	S09.0	`,`	Injury of blood vessels of head, not elsewhere classified Excl.: injury of: cerebral blood vessels (S06.-) precerebral blood vessels (S15.-) 	`,`	null	`],
	[`	S09.1	`,`	Injury of muscle and tendon of head 	`,`	null	`],
	[`	S09.2	`,`	Traumatic rupture of ear drum 	`,`	null	`],
	[`	S09.7	`,`	Multiple injuries of head Injuries classifiable to more than one of the categories S00-S09.2 	`,`	null	`],
	[`	S09.8	`,`	Other specified injuries of head 	`,`	null	`],
	[`	S09.9	`,`	Unspecified injury of head Injury of: face NOS ear NOS nose NOS 	`,`	null	`],
	[`	S10	`,`	Superficial injury of neck 	`,`	null	`],
	[`	S10.0	`,`	Contusion of throat Cervical oesophagus Larynx Pharynx Trachea 	`,`	null	`],
	[`	S10.1	`,`	Other and unspecified superficial injuries of throat 	`,`	null	`],
	[`	S10.7	`,`	Multiple superficial injuries of neck 	`,`	null	`],
	[`	S10.8	`,`	Superficial injury of other parts of neck 	`,`	null	`],
	[`	S10.9	`,`	Superficial injury of neck, part unspecified 	`,`	null	`],
	[`	S11	`,`	Open wound of neck Excl.: decapitation (S18) 	`,`	null	`],
	[`	S11.0	`,`	Open wound involving larynx and trachea Trachea: NOS cervical Excl.: thoracic trachea (S27.5) 	`,`	null	`],
	[`	S11.1	`,`	Open wound involving thyroid gland 	`,`	null	`],
	[`	S11.2	`,`	Open wound involving pharynx and cervical oesophagus Excl.: oesophagus NOS (S27.8) 	`,`	null	`],
	[`	S11.7	`,`	Multiple open wounds of neck 	`,`	null	`],
	[`	S11.8	`,`	Open wound of other parts of neck 	`,`	null	`],
	[`	S11.9	`,`	Open wound of neck, part unspecified 	`,`	null	`],
	[`	S12	`,`	Fracture of neck Incl.: cervical: neural arch spine spinous process transverse process vertebra vertebral arch The following subdivisions are provided for optional use in a supplementary character position where it is not possible or not desired to use multiple coding to identify fracture and open wound; a fracture not indicated as closed or open should be classified as closed. 0 closed 1 open 	`,`	null	`],
	[`	S12.0	`,`	Fracture of first cervical vertebra Atlas 	`,`	null	`],
	[`	S12.1	`,`	Fracture of second cervical vertebra Axis 	`,`	null	`],
	[`	S12.2	`,`	Fracture of other specified cervical vertebra Excl.: multiple fractures of cervical spine (S12.7) 	`,`	null	`],
	[`	S12.7	`,`	Multiple fractures of cervical spine 	`,`	null	`],
	[`	S12.8	`,`	Fracture of other parts of neck Hyoid bone Larynx Thyroid cartilage Trachea 	`,`	null	`],
	[`	S12.9	`,`	Fracture of neck, part unspecified Fracture of cervical: spine NOS vertebra NOS 	`,`	null	`],
	[`	S13	`,`	Dislocation, sprain and strain of joints and ligaments at neck level Excl.: rupture or displacement (nontraumatic) of cervical intervertebral disc (M50.-) 	`,`	null	`],
	[`	S13.0	`,`	Traumatic rupture of cervical intervertebral disc 	`,`	null	`],
	[`	S13.1	`,`	Dislocation of cervical vertebra Cervical spine NOS 	`,`	null	`],
	[`	S13.2	`,`	Dislocation of other and unspecified parts of neck 	`,`	null	`],
	[`	S13.3	`,`	Multiple dislocations of neck 	`,`	null	`],
	[`	S13.4	`,`	Sprain and strain of cervical spine Anterior longitudinal (ligament), cervical Atlanto-axial (joints) Atlanto-occipital (joints) Whiplash injury 	`,`	null	`],
	[`	S13.5	`,`	Sprain and strain of thyroid region Cricoarytenoid (joint)(ligament) Cricothyroid (joint)(ligament) Thyroid cartilage 	`,`	null	`],
	[`	S13.6	`,`	Sprain and strain of joints and ligaments of other and unspecified parts of neck 	`,`	null	`],
	[`	S14	`,`	Injury of nerves and spinal cord at neck level 	`,`	null	`],
	[`	S14.0	`,`	Concussion and oedema of cervical spinal cord 	`,`	null	`],
	[`	S14.1	`,`	Other and unspecified injuries of cervical spinal cord Injury of cervical spinal cord NOS 	`,`	null	`],
	[`	S14.2	`,`	Injury of nerve root of cervical spine 	`,`	null	`],
	[`	S14.3	`,`	Injury of brachial plexus 	`,`	null	`],
	[`	S14.4	`,`	Injury of peripheral nerves of neck 	`,`	null	`],
	[`	S14.5	`,`	Injury of cervical sympathetic nerves 	`,`	null	`],
	[`	S14.6	`,`	Injury of other and unspecified nerves of neck 	`,`	null	`],
	[`	S15	`,`	Injury of blood vessels at neck level 	`,`	null	`],
	[`	S15.0	`,`	Injury of carotid artery Carotid artery (common) (external) (internal) 	`,`	null	`],
	[`	S15.1	`,`	Injury of vertebral artery 	`,`	null	`],
	[`	S15.2	`,`	Injury of external jugular vein 	`,`	null	`],
	[`	S15.3	`,`	Injury of internal jugular vein 	`,`	null	`],
	[`	S15.7	`,`	Injury of multiple blood vessels at neck level 	`,`	null	`],
	[`	S15.8	`,`	Injury of other blood vessels at neck level 	`,`	null	`],
	[`	S15.9	`,`	Injury of unspecified blood vessel at neck level 	`,`	null	`],
	[`	S16	`,`	Injury of muscle and tendon at neck level 	`,`	null	`],
	[`	S17	`,`	Crushing injury of neck 	`,`	null	`],
	[`	S17.0	`,`	Crushing injury of larynx and trachea 	`,`	null	`],
	[`	S17.8	`,`	Crushing injury of other parts of neck 	`,`	null	`],
	[`	S17.9	`,`	Crushing injury of neck, part unspecified 	`,`	null	`],
	[`	S18	`,`	Traumatic amputation at neck level Incl.: Decapitation 	`,`	null	`],
	[`	S19	`,`	Other and unspecified injuries of neck 	`,`	null	`],
	[`	S19.7	`,`	Multiple injuries of neck Injuries classifiable to more than one of the categories S10-S18 	`,`	null	`],
	[`	S19.8	`,`	Other specified injuries of neck 	`,`	null	`],
	[`	S19.9	`,`	Unspecified injury of neck 	`,`	null	`],
	[`	S20	`,`	Superficial injury of thorax 	`,`	null	`],
	[`	S20.0	`,`	Contusion of breast 	`,`	null	`],
	[`	S20.1	`,`	Other and unspecified superficial injuries of breast 	`,`	null	`],
	[`	S20.2	`,`	Contusion of thorax 	`,`	null	`],
	[`	S20.3	`,`	Other superficial injuries of front wall of thorax 	`,`	null	`],
	[`	S20.4	`,`	Other superficial injuries of back wall of thorax 	`,`	null	`],
	[`	S20.7	`,`	Multiple superficial injuries of thorax 	`,`	null	`],
	[`	S20.8	`,`	Superficial injury of other and unspecified parts of thorax Thoracic wall NOS 	`,`	null	`],
	[`	S21	`,`	Open wound of thorax Excl.: traumatic: haemopneumothorax (S27.2) haemothorax (S27.1) pneumothorax (S27.0) 	`,`	null	`],
	[`	S21.0	`,`	Open wound of breast 	`,`	null	`],
	[`	S21.1	`,`	Open wound of front wall of thorax 	`,`	null	`],
	[`	S21.2	`,`	Open wound of back wall of thorax 	`,`	null	`],
	[`	S21.7	`,`	Multiple open wounds of thoracic wall 	`,`	null	`],
	[`	S21.8	`,`	Open wound of other parts of thorax 	`,`	null	`],
	[`	S21.9	`,`	Open wound of thorax, part unspecified Thoracic wall NOS 	`,`	null	`],
	[`	S22	`,`	Fracture of rib(s), sternum and thoracic spine Incl.: thoracic: neural arch spinous process transverse process vertebra vertebral arch Excl.: fracture of: clavicle (S42.0) scapula (S42.1) The following subdivisions are provided for optional use in a supplementary character position where it is not possible or not desired to use multiple coding to identify fracture and open wound; a fracture not indicated as closed or open should be classified as closed. 0 closed 1 open 	`,`	null	`],
	[`	S22.0	`,`	Fracture of thoracic vertebra Fracture of thoracic spine NOS 	`,`	null	`],
	[`	S22.1	`,`	Multiple fractures of thoracic spine 	`,`	null	`],
	[`	S22.2	`,`	Fracture of sternum 	`,`	null	`],
	[`	S22.3	`,`	Fracture of rib 	`,`	null	`],
	[`	S22.4	`,`	Multiple fractures of ribs 	`,`	null	`],
	[`	S22.5	`,`	Flail chest 	`,`	null	`],
	[`	S22.8	`,`	Fracture of other parts of bony thorax 	`,`	null	`],
	[`	S22.9	`,`	Fracture of bony thorax, part unspecified 	`,`	null	`],
	[`	S23	`,`	Dislocation, sprain and strain of joints and ligaments of thorax Excl.: dislocation, sprain and strain of sterno-clavicular joint (S43.2, S43.6) rupture or displacement (nontraumatic) of thoracic intervertebral disc (M51.-) 	`,`	null	`],
	[`	S23.0	`,`	Traumatic rupture of thoracic intervertebral disc 	`,`	null	`],
	[`	S23.1	`,`	Dislocation of thoracic vertebra Thoracic spine NOS 	`,`	null	`],
	[`	S23.2	`,`	Dislocation of other and unspecified parts of thorax 	`,`	null	`],
	[`	S23.3	`,`	Sprain and strain of thoracic spine 	`,`	null	`],
	[`	S23.4	`,`	Sprain and strain of ribs and sternum 	`,`	null	`],
	[`	S23.5	`,`	Sprain and strain of other and unspecified parts of thorax 	`,`	null	`],
	[`	S24	`,`	Injury of nerves and spinal cord at thorax level Excl.: injury of brachial plexus (S14.3) 	`,`	null	`],
	[`	S24.0	`,`	Concussion and oedema of thoracic spinal cord 	`,`	null	`],
	[`	S24.1	`,`	Other and unspecified injuries of thoracic spinal cord 	`,`	null	`],
	[`	S24.2	`,`	Injury of nerve root of thoracic spine 	`,`	null	`],
	[`	S24.3	`,`	Injury of peripheral nerves of thorax 	`,`	null	`],
	[`	S24.4	`,`	Injury of thoracic sympathetic nerves Cardiac plexus Oesophageal plexus Pulmonary plexus Stellate ganglion Thoracic sympathetic ganglion 	`,`	null	`],
	[`	S24.5	`,`	Injury of other nerves of thorax 	`,`	null	`],
	[`	S24.6	`,`	Injury of unspecified nerve of thorax 	`,`	null	`],
	[`	S25	`,`	Injury of blood vessels of thorax 	`,`	null	`],
	[`	S25.0	`,`	Injury of thoracic aorta Aorta NOS 	`,`	null	`],
	[`	S25.1	`,`	Injury of innominate or subclavian artery 	`,`	null	`],
	[`	S25.2	`,`	Injury of superior vena cava Vena cava NOS 	`,`	null	`],
	[`	S25.3	`,`	Injury of innominate or subclavian vein 	`,`	null	`],
	[`	S25.4	`,`	Injury of pulmonary blood vessels 	`,`	null	`],
	[`	S25.5	`,`	Injury of intercostal blood vessels 	`,`	null	`],
	[`	S25.7	`,`	Injury of multiple blood vessels of thorax 	`,`	null	`],
	[`	S25.8	`,`	Injury of other blood vessels of thorax Azygos vein Mammary artery or vein 	`,`	null	`],
	[`	S25.9	`,`	Injury of unspecified blood vessel of thorax 	`,`	null	`],
	[`	S26	`,`	Injury of heart Incl.: contusion laceration puncture traumatic rupture of heart The following subdivisions are provided for optional use in a supplementary character position where it is not possible or not desired to use multiple coding: 0 without open wound into thoracic cavity 1 with open wound into thoracic cavity 	`,`	null	`],
	[`	S26.0	`,`	Injury of heart with haemopericardium 	`,`	null	`],
	[`	S26.8	`,`	Other injuries of heart 	`,`	null	`],
	[`	S26.9	`,`	Injury of heart, unspecified 	`,`	null	`],
	[`	S27	`,`	Injury of other and unspecified intrathoracic organs Excl.: injury of: cervical oesophagus (S10-S19) trachea (cervical) (S10-S19) The following subdivisions are provided for optional use in a supplementary character position where it is not possible or not desired to use multiple coding: 0 without open wound into thoracic cavity 1 with open wound into thoracic cavity 	`,`	null	`],
	[`	S27.0	`,`	Traumatic pneumothorax 	`,`	null	`],
	[`	S27.1	`,`	Traumatic haemothorax 	`,`	null	`],
	[`	S27.2	`,`	Traumatic haemopneumothorax 	`,`	null	`],
	[`	S27.3	`,`	Other injuries of lung 	`,`	null	`],
	[`	S27.4	`,`	Injury of bronchus 	`,`	null	`],
	[`	S27.5	`,`	Injury of thoracic trachea 	`,`	null	`],
	[`	S27.6	`,`	Injury of pleura 	`,`	null	`],
	[`	S27.7	`,`	Multiple injuries of intrathoracic organs 	`,`	null	`],
	[`	S27.8	`,`	Injury of other specified intrathoracic organs Diaphragm Lymphatic thoracic duct Oesophagus (thoracic part) Thymus gland 	`,`	null	`],
	[`	S27.9	`,`	Injury of unspecified intrathoracic organ 	`,`	null	`],
	[`	S28	`,`	Crushing injury of thorax and traumatic amputation of part of thorax 	`,`	null	`],
	[`	S28.0	`,`	Crushed chest Excl.: flail chest (S22.5) 	`,`	null	`],
	[`	S28.1	`,`	Traumatic amputation of part of thorax Excl.: transection of thorax (T05.8) 	`,`	null	`],
	[`	S29	`,`	Other and unspecified injuries of thorax 	`,`	null	`],
	[`	S29.0	`,`	Injury of muscle and tendon at thorax level 	`,`	null	`],
	[`	S29.7	`,`	Multiple injuries of thorax Injuries classifiable to more than one of the categories S20-S29.0 	`,`	null	`],
	[`	S29.8	`,`	Other specified injuries of thorax 	`,`	null	`],
	[`	S29.9	`,`	Unspecified injury of thorax 	`,`	null	`],
	[`	S30	`,`	Superficial injury of abdomen, lower back and pelvis Excl.: superficial injury of hip (S70.-) 	`,`	null	`],
	[`	S30.0	`,`	Contusion of lower back and pelvis Buttock 	`,`	null	`],
	[`	S30.1	`,`	Contusion of abdominal wall Flank Groin 	`,`	null	`],
	[`	S30.2	`,`	Contusion of external genital organs Labium (majus)(minus) Penis Perineum Scrotum Testis Vagina Vulva 	`,`	null	`],
	[`	S30.7	`,`	Multiple superficial injuries of abdomen, lower back and pelvis 	`,`	null	`],
	[`	S30.8	`,`	Other superficial injuries of abdomen, lower back and pelvis 	`,`	null	`],
	[`	S30.9	`,`	Superficial injury of abdomen, lower back and pelvis, part unspecified 	`,`	null	`],
	[`	S31	`,`	Open wound of abdomen, lower back and pelvis Excl.: open wound of hip (S71.0) traumatic amputation of part of abdomen, lower back and pelvis (S38.2-S38.3) 	`,`	null	`],
	[`	S31.0	`,`	Open wound of lower back and pelvis Buttock 	`,`	null	`],
	[`	S31.1	`,`	Open wound of abdominal wall Flank Groin 	`,`	null	`],
	[`	S31.2	`,`	Open wound of penis 	`,`	null	`],
	[`	S31.3	`,`	Open wound of scrotum and testes 	`,`	null	`],
	[`	S31.4	`,`	Open wound of vagina and vulva 	`,`	null	`],
	[`	S31.5	`,`	Open wound of other and unspecified external genital organs Excl.: traumatic amputation of external genital organs (S38.2) 	`,`	null	`],
	[`	S31.7	`,`	Multiple open wounds of abdomen, lower back and pelvis 	`,`	null	`],
	[`	S31.8	`,`	Open wound of other and unspecified parts of abdomen 	`,`	null	`],
	[`	S32	`,`	Fracture of lumbar spine and pelvis Incl.: lumbosacral: neural arch spinous process transverse process vertebra vertebral arch Excl.: fracture of hip NOS (S72.0) The following subdivisions are provided for optional use in a supplementary character position where it is not possible or not desired to use multiple coding to identify fracture and open wound; a fracture not indicated as closed or open should be classified as closed. 0 closed 1 open 	`,`	null	`],
	[`	S32.0	`,`	Fracture of lumbar vertebra Fracture of lumbar spine 	`,`	null	`],
	[`	S32.1	`,`	Fracture of sacrum 	`,`	null	`],
	[`	S32.2	`,`	Fracture of coccyx 	`,`	null	`],
	[`	S32.3	`,`	Fracture of ilium 	`,`	null	`],
	[`	S32.4	`,`	Fracture of acetabulum 	`,`	null	`],
	[`	S32.5	`,`	Fracture of pubis 	`,`	null	`],
	[`	S32.7	`,`	Multiple fractures of lumbar spine and pelvis 	`,`	null	`],
	[`	S32.8	`,`	Fracture of other and unspecified parts of lumbar spine and pelvis Fracture of: ischium lumbosacral spine NOS pelvis NOS 	`,`	null	`],
	[`	S33	`,`	Dislocation, sprain and strain of joints and ligaments of lumbar spine and pelvis Excl.: dislocation, sprain and strain of joint and ligaments of hip (S73.-) obstetric damage to pelvic joints and ligaments (O71.6) rupture or displacement (nontraumatic) of lumbar intervertebral disc (M51.-) 	`,`	null	`],
	[`	S33.0	`,`	Traumatic rupture of lumbar intervertebral disc 	`,`	null	`],
	[`	S33.1	`,`	Dislocation of lumbar vertebra Dislocation of lumbar spine NOS 	`,`	null	`],
	[`	S33.2	`,`	Dislocation of sacroiliac and sacrococcygeal joint 	`,`	null	`],
	[`	S33.3	`,`	Dislocation of other and unspecified parts of lumbar spine and pelvis 	`,`	null	`],
	[`	S33.4	`,`	Traumatic rupture of symphysis pubis 	`,`	null	`],
	[`	S33.5	`,`	Sprain and strain of lumbar spine 	`,`	null	`],
	[`	S33.6	`,`	Sprain and strain of sacroiliac joint 	`,`	null	`],
	[`	S33.7	`,`	Sprain and strain of other and unspecified parts of lumbar spine and pelvis 	`,`	null	`],
	[`	S34	`,`	Injury of nerves and lumbar spinal cord at abdomen, lower back and pelvis level 	`,`	null	`],
	[`	S34.0	`,`	Concussion and oedema of lumbar spinal cord 	`,`	null	`],
	[`	S34.1	`,`	Other injury of lumbar spinal cord 	`,`	null	`],
	[`	S34.2	`,`	Injury of nerve root of lumbar and sacral spine 	`,`	null	`],
	[`	S34.3	`,`	Injury of cauda equina 	`,`	null	`],
	[`	S34.4	`,`	Injury of lumbosacral plexus 	`,`	null	`],
	[`	S34.5	`,`	Injury of lumbar, sacral and pelvic sympathetic nerves Coeliac ganglion or plexus Hypogastric plexus Mesenteric plexus (inferior)(superior) Splanchnic nerve 	`,`	null	`],
	[`	S34.6	`,`	Injury of peripheral nerve(s) of abdomen, lower back and pelvis 	`,`	null	`],
	[`	S34.8	`,`	Injury of other and unspecified nerves at abdomen, lower back and pelvis level 	`,`	null	`],
	[`	S35	`,`	Injury of blood vessels at abdomen, lower back and pelvis level 	`,`	null	`],
	[`	S35.0	`,`	Injury of abdominal aorta Excl.: aorta NOS (S25.0) 	`,`	null	`],
	[`	S35.1	`,`	Injury of inferior vena cava Hepatic vein Excl.: vena cava NOS (S25.2) 	`,`	null	`],
	[`	S35.2	`,`	Injury of coeliac or mesenteric artery Gastric artery Gastroduodenal artery Hepatic artery Mesenteric artery (inferior)(superior) Splenic artery 	`,`	null	`],
	[`	S35.3	`,`	Injury of portal or splenic vein Mesenteric vein (inferior)(superior) 	`,`	null	`],
	[`	S35.4	`,`	Injury of renal blood vessels Renal artery or vein 	`,`	null	`],
	[`	S35.5	`,`	Injury of iliac blood vessels Hypogastric artery or vein Iliac artery or vein Uterine artery or vein 	`,`	null	`],
	[`	S35.7	`,`	Injury of multiple blood vessels at abdomen, lower back and pelvis level 	`,`	null	`],
	[`	S35.8	`,`	Injury of other blood vessels at abdomen, lower back and pelvis level Ovarian artery or vein 	`,`	null	`],
	[`	S35.9	`,`	Injury of unspecified blood vessel at abdomen, lower back and pelvis level 	`,`	null	`],
	[`	S36	`,`	Injury of intra-abdominal organs The following subdivisions are provided for optional use in a supplementary character position where it is not possible or not desired to use multiple coding: 0 without open wound into cavity 1 with open wound into cavity 	`,`	null	`],
	[`	S36.0	`,`	Injury of spleen 	`,`	null	`],
	[`	S36.1	`,`	Injury of liver or gallbladder Bile duct 	`,`	null	`],
	[`	S36.2	`,`	Injury of pancreas 	`,`	null	`],
	[`	S36.3	`,`	Injury of stomach 	`,`	null	`],
	[`	S36.4	`,`	Injury of small intestine 	`,`	null	`],
	[`	S36.5	`,`	Injury of colon 	`,`	null	`],
	[`	S36.6	`,`	Injury of rectum 	`,`	null	`],
	[`	S36.7	`,`	Injury of multiple intra-abdominal organs 	`,`	null	`],
	[`	S36.8	`,`	Injury of other intra-abdominal organs Peritoneum Retroperitoneum 	`,`	null	`],
	[`	S36.9	`,`	Injury of unspecified intra-abdominal organ 	`,`	null	`],
	[`	S37	`,`	Injury of urinary and pelvic organs Excl.: peritoneum and retroperitoneum (S36.8) The following subdivisions are provided for optional use in a supplementary character position where it is not possible or not desired to use multiple coding: 0 without open wound into cavity 1 with open wound into cavity 	`,`	null	`],
	[`	S37.0	`,`	Injury of kidney 	`,`	null	`],
	[`	S37.1	`,`	Injury of ureter 	`,`	null	`],
	[`	S37.2	`,`	Injury of bladder 	`,`	null	`],
	[`	S37.3	`,`	Injury of urethra 	`,`	null	`],
	[`	S37.4	`,`	Injury of ovary 	`,`	null	`],
	[`	S37.5	`,`	Injury of fallopian tube 	`,`	null	`],
	[`	S37.6	`,`	Injury of uterus 	`,`	null	`],
	[`	S37.7	`,`	Injury of multiple pelvic organs 	`,`	null	`],
	[`	S37.8	`,`	Injury of other pelvic organs Adrenal gland Prostate Seminal vesicle Vas deferens Excl.: Open wound of other and unspecified external genital organs (S31.5) 	`,`	null	`],
	[`	S37.9	`,`	Injury of unspecified pelvic organ 	`,`	null	`],
	[`	S38	`,`	Crushing injury and traumatic amputation of part of abdomen, lower back and pelvis 	`,`	null	`],
	[`	S38.0	`,`	Crushing injury of external genital organs 	`,`	null	`],
	[`	S38.1	`,`	Crushing injury of other and unspecified parts of abdomen, lower back and pelvis 	`,`	null	`],
	[`	S38.2	`,`	Traumatic amputation of external genital organs Labium (majus)(minus) Penis Scrotum Testis Vulva 	`,`	null	`],
	[`	S38.3	`,`	Traumatic amputation of other and unspecified parts of abdomen, lower back and pelvis Excl.: transection of abdomen (T05.8) 	`,`	null	`],
	[`	S39	`,`	Other and unspecified injuries of abdomen, lower back and pelvis 	`,`	null	`],
	[`	S39.0	`,`	Injury of muscle and tendon of abdomen, lower back and pelvis 	`,`	null	`],
	[`	S39.6	`,`	Injury of intra-abdominal organ(s) with pelvic organ(s) 	`,`	null	`],
	[`	S39.7	`,`	Other multiple injuries of abdomen, lower back and pelvis Injuries classifiable to more than one of the categories S30-S39.6 Excl.: injuries in S36.- with injuries in S37.- (S39.6) 	`,`	null	`],
	[`	S39.8	`,`	Other specified injuries of abdomen, lower back and pelvis 	`,`	null	`],
	[`	S39.9	`,`	Unspecified injury of abdomen, lower back and pelvis 	`,`	null	`],
	[`	S50	`,`	Superficial injury of forearm Excl.: superficial injury of wrist and hand (S60.-) 	`,`	null	`],
	[`	S50.0	`,`	Contusion of elbow 	`,`	null	`],
	[`	S50.1	`,`	Contusion of other and unspecified parts of forearm 	`,`	null	`],
	[`	S50.7	`,`	Multiple superficial injuries of forearm 	`,`	null	`],
	[`	S50.8	`,`	Other superficial injuries of forearm 	`,`	null	`],
	[`	S50.9	`,`	Superficial injury of forearm, unspecified Superficial injury of elbow NOS 	`,`	null	`],
	[`	S51	`,`	Open wound of forearm Excl.: open wound of wrist and hand (S61.-) traumatic amputation of forearm (S58.-) 	`,`	null	`],
	[`	S51.0	`,`	Open wound of elbow 	`,`	null	`],
	[`	S51.7	`,`	Multiple open wounds of forearm 	`,`	null	`],
	[`	S51.8	`,`	Open wound of other parts of forearm 	`,`	null	`],
	[`	S51.9	`,`	Open wound of forearm, part unspecified 	`,`	null	`],
	[`	S52	`,`	Fracture of forearm Excl.: fracture at wrist and hand level (S62.-) The following subdivisions are provided for optional use in a supplementary character position where it is not possible or not desired to use multiple coding to identify fracture and open wound; a fracture not indicated as closed or open should be classified as closed. 0 closed 1 open 	`,`	null	`],
	[`	S52.0	`,`	Fracture of upper end of ulna Coronoid process Elbow NOS Monteggia fracture-dislocation Olecranon process Proximal end 	`,`	null	`],
	[`	S52.1	`,`	Fracture of upper end of radius Head Neck Proximal end 	`,`	null	`],
	[`	S52.2	`,`	Fracture of shaft of ulna 	`,`	null	`],
	[`	S52.3	`,`	Fracture of shaft of radius 	`,`	null	`],
	[`	S52.4	`,`	Fracture of shafts of both ulna and radius 	`,`	null	`],
	[`	S52.5	`,`	Fracture of lower end of radius Colles fracture Smith fracture 	`,`	null	`],
	[`	S52.6	`,`	Fracture of lower end of both ulna and radius 	`,`	null	`],
	[`	S52.7	`,`	Multiple fractures of forearm Excl.: fractures of both ulna and radius: lower end (S52.6) shafts (S52.4) 	`,`	null	`],
	[`	S52.8	`,`	Fracture of other parts of forearm Lower end of ulna Head of ulna 	`,`	null	`],
	[`	S52.9	`,`	Fracture of forearm, part unspecified 	`,`	null	`],
	[`	S53	`,`	Dislocation, sprain and strain of joints and ligaments of elbow S53.0 Dislocation of radial head Radiohumeral joint Excl.: Monteggia fracture-dislocation (S52.0) 	`,`	null	`],
	[`	S53.1	`,`	Dislocation of elbow, unspecified Ulnohumeral joint Excl.: dislocation of radial head alone (S53.0) 	`,`	null	`],
	[`	S53.2	`,`	Traumatic rupture of radial collateral ligament 	`,`	null	`],
	[`	S53.3	`,`	Traumatic rupture of ulnar collateral ligament 	`,`	null	`],
	[`	S53.4	`,`	Sprain and strain of elbow 	`,`	null	`],
	[`	S54	`,`	Injury of nerves at forearm level Excl.: injury of nerves at wrist and hand level (S64.-) 	`,`	null	`],
	[`	S54.0	`,`	Injury of ulnar nerve at forearm level Ulnar nerve NOS 	`,`	null	`],
	[`	S54.1	`,`	Injury of median nerve at forearm level Median nerve NOS 	`,`	null	`],
	[`	S54.2	`,`	Injury of radial nerve at forearm level Radial nerve NOS 	`,`	null	`],
	[`	S54.3	`,`	Injury of cutaneous sensory nerve at forearm level 	`,`	null	`],
	[`	S54.7	`,`	Injury of multiple nerves at forearm level 	`,`	null	`],
	[`	S54.8	`,`	Injury of other nerves at forearm level 	`,`	null	`],
	[`	S54.9	`,`	Injury of unspecified nerve at forearm level 	`,`	null	`],
	[`	S55	`,`	Injury of blood vessels at forearm level Excl.: injury of: blood vessels at wrist and hand level (S65.-) brachial vessels (S45.1-S45.2) 	`,`	null	`],
	[`	S55.0	`,`	Injury of ulnar artery at forearm level 	`,`	null	`],
	[`	S55.1	`,`	Injury of radial artery at forearm level 	`,`	null	`],
	[`	S55.2	`,`	Injury of vein at forearm level 	`,`	null	`],
	[`	S55.7	`,`	Injury of multiple blood vessels at forearm level 	`,`	null	`],
	[`	S55.8	`,`	Injury of other blood vessels at forearm level 	`,`	null	`],
	[`	S55.9	`,`	Injury of unspecified blood vessel at forearm level 	`,`	null	`],
	[`	S56	`,`	Injury of muscle and tendon at forearm level Excl.: injury of muscle and tendon at or below wrist (S66.-) 	`,`	null	`],
	[`	S56.0	`,`	Injury of flexor muscle and tendon of thumb at forearm level 	`,`	null	`],
	[`	S56.1	`,`	Injury of long flexor muscle and tendon of other finger(s) at forearm level 	`,`	null	`],
	[`	S56.2	`,`	Injury of other flexor muscle and tendon at forearm level 	`,`	null	`],
	[`	S56.3	`,`	Injury of extensor or abductor muscles and tendons of thumb at forearm level 	`,`	null	`],
	[`	S56.4	`,`	Injury of extensor muscle and tendon of other finger(s) at forearm level 	`,`	null	`],
	[`	S56.5	`,`	Injury of other extensor muscle and tendon at forearm level 	`,`	null	`],
	[`	S56.7	`,`	Injury of multiple muscles and tendons at forearm level 	`,`	null	`],
	[`	S56.8	`,`	Injury of other and unspecified muscles and tendons at forearm level 	`,`	null	`],
	[`	S57	`,`	Crushing injury of forearm Excl.: crushing injury of wrist and hand (S67.-) 	`,`	null	`],
	[`	S57.0	`,`	Crushing injury of elbow 	`,`	null	`],
	[`	S57.8	`,`	Crushing injury of other parts of forearm 	`,`	null	`],
	[`	S57.9	`,`	Crushing injury of forearm, part unspecified 	`,`	null	`],
	[`	S58	`,`	Traumatic amputation of forearm Excl.: traumatic amputation of wrist and hand (S68.-) 	`,`	null	`],
	[`	S58.0	`,`	Traumatic amputation at elbow level 	`,`	null	`],
	[`	S58.1	`,`	Traumatic amputation at level between elbow and wrist 	`,`	null	`],
	[`	S58.9	`,`	Traumatic amputation of forearm, level unspecified 	`,`	null	`],
	[`	S59	`,`	Other and unspecified injuries of forearm Excl.: other and unspecified injuries of wrist and hand (S69.-) 	`,`	null	`],
	[`	S59.7	`,`	Multiple injuries of forearm Injuries classifiable to more than one of the categories S50-S58 	`,`	null	`],
	[`	S59.8	`,`	Other specified injuries of forearm 	`,`	null	`],
	[`	S59.9	`,`	Unspecified injury of forearm 	`,`	null	`],
	[`	S60	`,`	Superficial injury of wrist and hand 	`,`	null	`],
	[`	S60.0	`,`	Contusion of finger(s) without damage to nail Contusion of finger(s) NOS Excl.: contusion involving nail (matrix) (S60.1) 	`,`	null	`],
	[`	S60.1	`,`	Contusion of finger(s) with damage to nail 	`,`	null	`],
	[`	S60.2	`,`	Contusion of other parts of wrist and hand 	`,`	null	`],
	[`	S60.7	`,`	Multiple superficial injuries of wrist and hand 	`,`	null	`],
	[`	S60.8	`,`	Other superficial injuries of wrist and hand 	`,`	null	`],
	[`	S60.9	`,`	Superficial injury of wrist and hand, unspecified 	`,`	null	`],
	[`	S61	`,`	Open wound of wrist and hand Excl.: traumatic amputation of wrist and hand (S68.-) 	`,`	null	`],
	[`	S61.0	`,`	Open wound of finger(s) without damage to nail Open wound of finger(s) NOS Excl.: open wound involving nail (matrix) (S61.1) 	`,`	null	`],
	[`	S61.1	`,`	Open wound of finger(s) with damage to nail 	`,`	null	`],
	[`	S61.7	`,`	Multiple open wounds of wrist and hand 	`,`	null	`],
	[`	S61.8	`,`	Open wound of other parts of wrist and hand 	`,`	null	`],
	[`	S61.9	`,`	Open wound of wrist and hand, part unspecified 	`,`	null	`],
	[`	S62	`,`	Fracture at wrist and hand level Excl.: fracture of distal parts of ulna and radius (S52.-) The following subdivisions are provided for optional use in a supplementary character position where it is not possible or not desired to use multiple coding to identify fracture and open wound; a fracture not indicated as closed or open should be classified as closed. 0 closed 1 open 	`,`	null	`],
	[`	S62.0	`,`	Fracture of navicular [scaphoid] bone of hand 	`,`	null	`],
	[`	S62.1	`,`	Fracture of other carpal bone(s) Capitate [os magnum] Hamate [unciform] Lunate [semilunar] Pisiform Trapezium [greater multangular] Trapezoid [lesser multangular] Triquetrum [cuneiform of carpus] 	`,`	null	`],
	[`	S62.2	`,`	Fracture of first metacarpal bone Bennett fracture 	`,`	null	`],
	[`	S62.3	`,`	Fracture of other metacarpal bone 	`,`	null	`],
	[`	S62.4	`,`	Multiple fractures of metacarpal bones 	`,`	null	`],
	[`	S62.5	`,`	Fracture of thumb 	`,`	null	`],
	[`	S62.6	`,`	Fracture of other finger 	`,`	null	`],
	[`	S62.7	`,`	Multiple fractures of fingers 	`,`	null	`],
	[`	S62.8	`,`	Fracture of other and unspecified parts of wrist and hand 	`,`	null	`],
	[`	S63	`,`	Dislocation, sprain and strain of joints and ligaments at wrist and hand level 	`,`	null	`],
	[`	S63.0	`,`	Dislocation of wrist Carpal (bone) Carpometacarpal (joint) Metacarpal (bone), proximal end Midcarpal (joint) Radiocarpal (joint) Radioulnar (joint), distal Radius, distal end Ulna, distal end 	`,`	null	`],
	[`	S63.1	`,`	Dislocation of finger Interphalangeal (joint), hand Metacarpal (bone), distal end Metacarpophalangeal (joint) Phalanx, hand Thumb 	`,`	null	`],
	[`	S63.2	`,`	Multiple dislocations of fingers 	`,`	null	`],
	[`	S63.3	`,`	Traumatic rupture of ligament of wrist and carpus Collateral, wrist Radiocarpal (ligament) Ulnocarpal (palmar) 	`,`	null	`],
	[`	S63.4	`,`	Traumatic rupture of ligament of finger at metacarpophalangeal and interphalangeal joint(s) Collateral Palmar Volar plate 	`,`	null	`],
	[`	S63.5	`,`	Sprain and strain of wrist Carpal (joint) Radiocarpal (joint) (ligament) 	`,`	null	`],
	[`	S63.6	`,`	Sprain and strain of finger(s) Interphalangeal (joint), hand Metacarpophalangeal (joint) Phalanx, hand Thumb 	`,`	null	`],
	[`	S63.7	`,`	Sprain and strain of other and unspecified parts of hand 	`,`	null	`],
	[`	S64	`,`	Injury of nerves at wrist and hand level 	`,`	null	`],
	[`	S64.0	`,`	Injury of ulnar nerve at wrist and hand level 	`,`	null	`],
	[`	S64.1	`,`	Injury of median nerve at wrist and hand level 	`,`	null	`],
	[`	S64.2	`,`	Injury of radial nerve at wrist and hand level 	`,`	null	`],
	[`	S64.3	`,`	Injury of digital nerve of thumb 	`,`	null	`],
	[`	S64.4	`,`	Injury of digital nerve of other finger 	`,`	null	`],
	[`	S64.7	`,`	Injury of multiple nerves at wrist and hand level 	`,`	null	`],
	[`	S64.8	`,`	Injury of other nerves at wrist and hand level 	`,`	null	`],
	[`	S64.9	`,`	Injury of unspecified nerve at wrist and hand level 	`,`	null	`],
	[`	S65	`,`	Injury of blood vessels at wrist and hand level 	`,`	null	`],
	[`	S65.0	`,`	Injury of ulnar artery at wrist and hand level 	`,`	null	`],
	[`	S65.1	`,`	Injury of radial artery at wrist and hand level 	`,`	null	`],
	[`	S65.2	`,`	Injury of superficial palmar arch 	`,`	null	`],
	[`	S65.3	`,`	Injury of deep palmar arch 	`,`	null	`],
	[`	S65.4	`,`	Injury of blood vessel(s) of thumb 	`,`	null	`],
	[`	S65.5	`,`	Injury of blood vessel(s) of other finger 	`,`	null	`],
	[`	S65.7	`,`	Injury of multiple blood vessels at wrist and hand level 	`,`	null	`],
	[`	S65.8	`,`	Injury of other blood vessels at wrist and hand level 	`,`	null	`],
	[`	S65.9	`,`	Injury of unspecified blood vessel at wrist and hand level 	`,`	null	`],
	[`	S66	`,`	Injury of muscle and tendon at wrist and hand level 	`,`	null	`],
	[`	S66.0	`,`	Injury of long flexor muscle and tendon of thumb at wrist and hand level 	`,`	null	`],
	[`	S66.1	`,`	Injury of flexor muscle and tendon of other finger at wrist and hand level 	`,`	null	`],
	[`	S66.2	`,`	Injury of extensor muscle and tendon of thumb at wrist and hand level 	`,`	null	`],
	[`	S66.3	`,`	Injury of extensor muscle and tendon of other finger at wrist and hand level 	`,`	null	`],
	[`	S66.4	`,`	Injury of intrinsic muscle and tendon of thumb at wrist and hand level 	`,`	null	`],
	[`	S66.5	`,`	Injury of intrinsic muscle and tendon of other finger at wrist and hand level 	`,`	null	`],
	[`	S66.6	`,`	Injury of multiple flexor muscles and tendons at wrist and hand level 	`,`	null	`],
	[`	S66.7	`,`	Injury of multiple extensor muscles and tendons at wrist and hand level 	`,`	null	`],
	[`	S66.8	`,`	Injury of other muscles and tendons at wrist and hand level 	`,`	null	`],
	[`	S66.9	`,`	Injury of unspecified muscle and tendon at wrist and hand level 	`,`	null	`],
	[`	S67	`,`	Crushing injury of wrist and hand 	`,`	null	`],
	[`	S67.0	`,`	Crushing injury of thumb and other finger(s) 	`,`	null	`],
	[`	S67.8	`,`	Crushing injury of other and unspecified parts of wrist and hand 	`,`	null	`],
	[`	S68	`,`	Traumatic amputation of wrist and hand 	`,`	null	`],
	[`	S68.0	`,`	Traumatic amputation of thumb (complete)(partial) 	`,`	null	`],
	[`	S68.1	`,`	Traumatic amputation of other single finger (complete)(partial) 	`,`	null	`],
	[`	S68.2	`,`	Traumatic amputation of two or more fingers alone (complete)(partial) 	`,`	null	`],
	[`	S68.3	`,`	Combined traumatic amputation of (part of) finger(s) with other parts of wrist and hand 	`,`	null	`],
	[`	S68.4	`,`	Traumatic amputation of hand at wrist level 	`,`	null	`],
	[`	S68.8	`,`	Traumatic amputation of other parts of wrist and hand 	`,`	null	`],
	[`	S68.9	`,`	Traumatic amputation of wrist and hand, level unspecified 	`,`	null	`],
	[`	S69	`,`	Other and unspecified injuries of wrist and hand 	`,`	null	`],
	[`	S69.7	`,`	Multiple injuries of wrist and hand Injuries classifiable to more than one of the categories S60-S68 	`,`	null	`],
	[`	S69.8	`,`	Other specified injuries of wrist and hand 	`,`	null	`],
	[`	S69.9	`,`	Unspecified injury of wrist and hand 	`,`	null	`],
	[`	S70	`,`	Superficial injury of hip and thigh 	`,`	null	`],
	[`	S70.0	`,`	Contusion of hip 	`,`	null	`],
	[`	S70.1	`,`	Contusion of thigh 	`,`	null	`],
	[`	S70.7	`,`	Multiple superficial injuries of hip and thigh 	`,`	null	`],
	[`	S70.8	`,`	Other superficial injuries of hip and thigh 	`,`	null	`],
	[`	S70.9	`,`	Superficial injury of hip and thigh, unspecified 	`,`	null	`],
	[`	S71	`,`	Open wound of hip and thigh Excl.: traumatic amputation of hip and thigh (S78.-) 	`,`	null	`],
	[`	S71.0	`,`	Open wound of hip 	`,`	null	`],
	[`	S71.1	`,`	Open wound of thigh 	`,`	null	`],
	[`	S71.7	`,`	Multiple open wounds of hip and thigh 	`,`	null	`],
	[`	S71.8	`,`	Open wound of other and unspecified parts of pelvic girdle 	`,`	null	`],
	[`	S72	`,`	Fracture of femur The following subdivisions are provided for optional use in a supplementary character position where it is not possible or not desired to use multiple coding to identify fracture and open wound; a fracture not indicated as closed or open should be classified as closed. 0 closed 1 open 	`,`	null	`],
	[`	S72.0	`,`	Fracture of neck of femur Fracture of hip NOS 	`,`	null	`],
	[`	S72.1	`,`	Pertrochanteric fracture Intertrochanteric fracture Trochanteric fracture 	`,`	null	`],
	[`	S72.2	`,`	Subtrochanteric fracture 	`,`	null	`],
	[`	S72.3	`,`	Fracture of shaft of femur 	`,`	null	`],
	[`	S72.4	`,`	Fracture of lower end of femur 	`,`	null	`],
	[`	S72.7	`,`	Multiple fractures of femur 	`,`	null	`],
	[`	S72.8	`,`	Fractures of other parts of femur 	`,`	null	`],
	[`	S72.9	`,`	Fracture of femur, part unspecified 	`,`	null	`],
	[`	S73	`,`	Dislocation, sprain and strain of joint and ligaments of hip 	`,`	null	`],
	[`	S73.0	`,`	Dislocation of hip 	`,`	null	`],
	[`	S73.1	`,`	Sprain and strain of hip 	`,`	null	`],
	[`	S74	`,`	Injury of nerves at hip and thigh level 	`,`	null	`],
	[`	S74.0	`,`	Injury of sciatic nerve at hip and thigh level 	`,`	null	`],
	[`	S74.1	`,`	Injury of femoral nerve at hip and thigh level 	`,`	null	`],
	[`	S74.2	`,`	Injury of cutaneous sensory nerve at hip and thigh level 	`,`	null	`],
	[`	S74.7	`,`	Injury of multiple nerves at hip and thigh level 	`,`	null	`],
	[`	S74.8	`,`	Injury of other nerves at hip and thigh level 	`,`	null	`],
	[`	S74.9	`,`	Injury of unspecified nerve at hip and thigh level 	`,`	null	`],
	[`	S75	`,`	Injury of blood vessels at hip and thigh level Excl.: popliteal artery (S85.0) 	`,`	null	`],
	[`	S75.0	`,`	Injury of femoral artery 	`,`	null	`],
	[`	S75.1	`,`	Injury of femoral vein at hip and thigh level 	`,`	null	`],
	[`	S75.2	`,`	Injury of greater saphenous vein at hip and thigh level Excl.: greater saphenous vein NOS (S85.3) 	`,`	null	`],
	[`	S75.7	`,`	Injury of multiple blood vessels at hip and thigh level 	`,`	null	`],
	[`	S75.8	`,`	Injury of other blood vessels at hip and thigh level 	`,`	null	`],
	[`	S75.9	`,`	Injury of unspecified blood vessel at hip and thigh level 	`,`	null	`],
	[`	S76	`,`	Injury of muscle and tendon at hip and thigh level 	`,`	null	`],
	[`	S76.0	`,`	Injury of muscle and tendon of hip 	`,`	null	`],
	[`	S76.1	`,`	Injury of quadriceps muscle and tendon Patellar ligament (tendon) 	`,`	null	`],
	[`	S76.2	`,`	Injury of adductor muscle and tendon of thigh 	`,`	null	`],
	[`	S76.3	`,`	Injury of muscle and tendon of the posterior muscle group at thigh level 	`,`	null	`],
	[`	S76.4	`,`	Injury of other and unspecified muscles and tendons at thigh level 	`,`	null	`],
	[`	S76.7	`,`	Injury of multiple muscles and tendons at hip and thigh level 	`,`	null	`],
	[`	S77	`,`	Crushing injury of hip and thigh 	`,`	null	`],
	[`	S77.0	`,`	Crushing injury of hip 	`,`	null	`],
	[`	S77.1	`,`	Crushing injury of thigh 	`,`	null	`],
	[`	S77.2	`,`	Crushing injury of hip with thigh 	`,`	null	`],
	[`	S78	`,`	Traumatic amputation of hip and thigh Excl.: traumatic amputation of lower limb, level unspecified (T13.6) 	`,`	null	`],
	[`	S78.0	`,`	Traumatic amputation at hip joint 	`,`	null	`],
	[`	S78.1	`,`	Traumatic amputation at level between hip and knee 	`,`	null	`],
	[`	S78.9	`,`	Traumatic amputation of hip and thigh, level unspecified 	`,`	null	`],
	[`	S79	`,`	Other and unspecified injuries of hip and thigh 	`,`	null	`],
	[`	S79.7	`,`	Multiple injuries of hip and thigh Injuries classifiable to more than one of the categories S70-S78 	`,`	null	`],
	[`	S79.8	`,`	Other specified injuries of hip and thigh 	`,`	null	`],
	[`	S79.9	`,`	Unspecified injury of hip and thigh 	`,`	null	`],
	[`	S80	`,`	Superficial injury of lower leg Excl.: superficial injury of ankle and foot (S90.-) 	`,`	null	`],
	[`	S80.0	`,`	Contusion of knee 	`,`	null	`],
	[`	S80.1	`,`	Contusion of other and unspecified parts of lower leg 	`,`	null	`],
	[`	S80.7	`,`	Multiple superficial injuries of lower leg 	`,`	null	`],
	[`	S80.8	`,`	Other superficial injuries of lower leg 	`,`	null	`],
	[`	S80.9	`,`	Superficial injury of lower leg, unspecified 	`,`	null	`],
	[`	S81	`,`	Open wound of lower leg Excl.: open wound of ankle and foot (S91.-) traumatic amputation of lower leg (S88.-) 	`,`	null	`],
	[`	S81.0	`,`	Open wound of knee 	`,`	null	`],
	[`	S81.7	`,`	Multiple open wounds of lower leg 	`,`	null	`],
	[`	S81.8	`,`	Open wound of other parts of lower leg 	`,`	null	`],
	[`	S81.9	`,`	Open wound of lower leg, part unspecified 	`,`	null	`],
	[`	S82	`,`	Fracture of lower leg, including ankle Incl.: malleolus Excl.: fracture of foot, except ankle (S92.-) The following subdivisions are provided for optional use in a supplementary character position where it is not possible or not desired to use multiple coding to identify fracture and open wound; a fracture not indicated as closed or open should be classified as closed. 0 closed 1 open 	`,`	null	`],
	[`	S82.0	`,`	Fracture of patella Knee cap 	`,`	null	`],
	[`	S82.1	`,`	Fracture of upper end of tibia Tibial: condyles head plateau proximal end tuberosity with or without mention of fracture of fibula 	`,`	null	`],
	[`	S82.2	`,`	Fracture of shaft of tibia With or without mention of fracture of fibula 	`,`	null	`],
	[`	S82.3	`,`	Fracture of lower end of tibia With or without mention of fracture of fibula Excl.: medial malleolus (S82.5) 	`,`	null	`],
	[`	S82.4	`,`	Fracture of fibula alone Excl.: lateral malleolus (S82.6) 	`,`	null	`],
	[`	S82.5	`,`	Fracture of medial malleolus Tibia involving: ankle malleolus 	`,`	null	`],
	[`	S82.6	`,`	Fracture of lateral malleolus Fibula involving: ankle malleolus 	`,`	null	`],
	[`	S82.7	`,`	Multiple fractures of lower leg Excl.: fractures of both tibia and fibula: lower end (S82.3) shafts (S82.2) upper end (S82.1) 	`,`	null	`],
	[`	S82.8	`,`	Fractures of other parts of lower leg Fracture (of): ankle NOS bimalleolar trimalleolar 	`,`	null	`],
	[`	S82.9	`,`	Fracture of lower leg, part unspecified 	`,`	null	`],
	[`	S83	`,`	Dislocation, sprain and strain of joints and ligaments of knee Excl.: derangement of: knee, internal (M23.-) patella (M22.0-M22.3) dislocation of knee: old (M24.3) pathological (M24.3) recurrent (M24.4) 	`,`	null	`],
	[`	S83.0	`,`	Dislocation of patella 	`,`	null	`],
	[`	S83.1	`,`	Dislocation of knee Tibiofibular (joint) 	`,`	null	`],
	[`	S83.2	`,`	Tear of meniscus, current Bucket-handle tear (of): NOS lateral meniscus medial meniscus Excl.: old bucket-handle tear (M23.2) 	`,`	null	`],
	[`	S83.3	`,`	Tear of articular cartilage of knee, current 	`,`	null	`],
	[`	S83.4	`,`	Sprain and strain involving (fibular)(tibial) collateral ligament of knee 	`,`	null	`],
	[`	S83.5	`,`	Sprain and strain involving (anterior)(posterior) cruciate ligament of knee 	`,`	null	`],
	[`	S83.6	`,`	Sprain and strain of other and unspecified parts of knee Tibiofibular joint and ligament, superior Excl.: sprain of patellar ligament (S76.1) 	`,`	null	`],
	[`	S83.7	`,`	Injury to multiple structures of knee Injury to (lateral)(medial) meniscus in combination with (collateral)(cruciate) ligaments 	`,`	null	`],
	[`	S84	`,`	Injury of nerves at lower leg level Excl.: injury of nerves at ankle and foot level (S94.-) 	`,`	null	`],
	[`	S84.0	`,`	Injury of tibial nerve at lower leg level 	`,`	null	`],
	[`	S84.1	`,`	Injury of peroneal nerve at lower leg level 	`,`	null	`],
	[`	S84.2	`,`	Injury of cutaneous sensory nerve at lower leg level 	`,`	null	`],
	[`	S84.7	`,`	Injury of multiple nerves at lower leg level 	`,`	null	`],
	[`	S84.8	`,`	Injury of other nerves at lower leg level 	`,`	null	`],
	[`	S84.9	`,`	Injury of unspecified nerve at lower leg level 	`,`	null	`],
	[`	S85	`,`	Injury of blood vessels at lower leg level Excl.: injury of blood vessels at ankle and foot level (S95.-) 	`,`	null	`],
	[`	S85.0	`,`	Injury of popliteal artery 	`,`	null	`],
	[`	S85.1	`,`	Injury of (anterior)(posterior) tibial artery 	`,`	null	`],
	[`	S85.2	`,`	Injury of peroneal artery 	`,`	null	`],
	[`	S85.3	`,`	Injury of greater saphenous vein at lower leg level Greater saphenous vein NOS 	`,`	null	`],
	[`	S85.4	`,`	Injury of lesser saphenous vein at lower leg level 	`,`	null	`],
	[`	S85.5	`,`	Injury of popliteal vein 	`,`	null	`],
	[`	S85.7	`,`	Injury of multiple blood vessels at lower leg level 	`,`	null	`],
	[`	S85.8	`,`	Injury of other blood vessels at lower leg level 	`,`	null	`],
	[`	S85.9	`,`	Injury of unspecified blood vessel at lower leg level 	`,`	null	`],
	[`	S86	`,`	Injury of muscle and tendon at lower leg level Excl.: injury of: muscle and tendon at or below ankle (S96.-) patellar ligament (tendon) (S76.1) 	`,`	null	`],
	[`	S86.0	`,`	Injury of Achilles tendon 	`,`	null	`],
	[`	S86.1	`,`	Injury of other muscle(s) and tendon(s) of posterior muscle group at lower leg level 	`,`	null	`],
	[`	S86.2	`,`	Injury of muscle(s) and tendon(s) of anterior muscle group at lower leg level 	`,`	null	`],
	[`	S86.3	`,`	Injury of muscle(s) and tendon(s) of peroneal muscle group at lower leg level 	`,`	null	`],
	[`	S86.7	`,`	Injury of multiple muscles and tendons at lower leg level 	`,`	null	`],
	[`	S86.8	`,`	Injury of other muscles and tendons at lower leg level 	`,`	null	`],
	[`	S86.9	`,`	Injury of unspecified muscle and tendon at lower leg level 	`,`	null	`],
	[`	S87	`,`	Crushing injury of lower leg Excl.: crushing injury of ankle and foot (S97.-) 	`,`	null	`],
	[`	S87.0	`,`	Crushing injury of knee 	`,`	null	`],
	[`	S87.8	`,`	Crushing injury of other and unspecified parts of lower leg 	`,`	null	`],
	[`	S88	`,`	Traumatic amputation of lower leg Excl.: traumatic amputation of: ankle and foot (S98.-) leg, level unspecified (T13.6) 	`,`	null	`],
	[`	S88.0	`,`	Traumatic amputation at knee level 	`,`	null	`],
	[`	S88.1	`,`	Traumatic amputation at level between knee and ankle 	`,`	null	`],
	[`	S88.9	`,`	Traumatic amputation of lower leg, level unspecified 	`,`	null	`],
	[`	S89	`,`	Other and unspecified injuries of lower leg Excl.: other and unspecified injuries of ankle and foot (S99.-) 	`,`	null	`],
	[`	S89.7	`,`	Multiple injuries of lower leg Injuries classifiable to more than one of the categories S80-S88 	`,`	null	`],
	[`	S89.8	`,`	Other specified injuries of lower leg 	`,`	null	`],
	[`	S89.9	`,`	Unspecified injury of lower leg 	`,`	null	`],
	[`	S90	`,`	Superficial injury of ankle and foot 	`,`	null	`],
	[`	S90.0	`,`	Contusion of ankle 	`,`	null	`],
	[`	S90.1	`,`	Contusion of toe(s) without damage to nail Contusion of toe(s) NOS 	`,`	null	`],
	[`	S90.2	`,`	Contusion of toe(s) with damage to nail 	`,`	null	`],
	[`	S90.3	`,`	Contusion of other and unspecified parts of foot 	`,`	null	`],
	[`	S90.7	`,`	Multiple superficial injuries of ankle and foot 	`,`	null	`],
	[`	S90.8	`,`	Other superficial injuries of ankle and foot 	`,`	null	`],
	[`	S90.9	`,`	Superficial injury of ankle and foot, unspecified 	`,`	null	`],
	[`	S91	`,`	Open wound of ankle and foot Excl.: traumatic amputation of ankle and foot (S98.-) 	`,`	null	`],
	[`	S91.0	`,`	Open wound of ankle 	`,`	null	`],
	[`	S91.1	`,`	Open wound of toe(s) without damage to nail Open wound of toe(s) NOS 	`,`	null	`],
	[`	S91.2	`,`	Open wound of toe(s) with damage to nail 	`,`	null	`],
	[`	S91.3	`,`	Open wound of other parts of foot Open wound of foot NOS 	`,`	null	`],
	[`	S91.7	`,`	Multiple open wounds of ankle and foot 	`,`	null	`],
	[`	S92	`,`	Fracture of foot, except ankle Excl.: ankle (S82.-) malleolus (S82.-) The followig subdivisions are provided for optional use in a supplementary character position where it is not possible or not desired to use multiple coding to identify fracture and open wound; a fracture not indicated as closed or open should be classified as closed. 0 closed 1 open 	`,`	null	`],
	[`	S92.0	`,`	Fracture of calcaneus Heel bone Os calcis 	`,`	null	`],
	[`	S92.1	`,`	Fracture of talus Astragalus 	`,`	null	`],
	[`	S92.2	`,`	Fracture of other tarsal bone(s) Cuboid Cuneiform, foot (intermediate)(lateral)(medial) Navicular, foot 	`,`	null	`],
	[`	S92.3	`,`	Fracture of metatarsal bone 	`,`	null	`],
	[`	S92.4	`,`	Fracture of great toe 	`,`	null	`],
	[`	S92.5	`,`	Fracture of other toe 	`,`	null	`],
	[`	S92.7	`,`	Multiple fractures of foot 	`,`	null	`],
	[`	S92.9	`,`	Fracture of foot, unspecified 	`,`	null	`],
	[`	S93	`,`	Dislocation, sprain and strain of joints and ligaments at ankle and foot level 	`,`	null	`],
	[`	S93.0	`,`	Dislocation of ankle joint Astragalus Fibula, lower end Talus Tibia, lower end 	`,`	null	`],
	[`	S93.1	`,`	Dislocation of toe(s) Interphalangeal (joint(s)) Metatarsophalangeal (joint(s)) 	`,`	null	`],
	[`	S93.2	`,`	Rupture of ligaments at ankle and foot level 	`,`	null	`],
	[`	S93.3	`,`	Dislocation of other and unspecified parts of foot Navicular, foot Tarsal (joint(s)) Tarsometatarsal (joint(s)) 	`,`	null	`],
	[`	S93.4	`,`	Sprain and strain of ankle Calcaneofibular (ligament) Deltoid (ligament) Internal collateral (ligament) Talofibular (ligament) Tibiofibular (ligament), distal Excl.: injury of Achilles tendon (S86.0) 	`,`	null	`],
	[`	S93.5	`,`	Sprain and strain of toe(s) Interphalangeal (joint(s)) Metatarsophalangeal (joint(s)) 	`,`	null	`],
	[`	S93.6	`,`	Sprain and strain of other and unspecified parts of foot Tarsal (ligament) Tarsometatarsal (ligament) 	`,`	null	`],
	[`	S94	`,`	Injury of nerves at ankle and foot level 	`,`	null	`],
	[`	S94.0	`,`	Injury of lateral plantar nerve 	`,`	null	`],
	[`	S94.1	`,`	Injury of medial plantar nerve 	`,`	null	`],
	[`	S94.2	`,`	Injury of deep peroneal nerve at ankle and foot level Terminal, lateral branch of deep peroneal nerve 	`,`	null	`],
	[`	S94.3	`,`	Injury of cutaneous sensory nerve at ankle and foot level 	`,`	null	`],
	[`	S94.7	`,`	Injury of multiple nerves at ankle and foot level 	`,`	null	`],
	[`	S94.8	`,`	Injury of other nerves at ankle and foot level 	`,`	null	`],
	[`	S94.9	`,`	Injury of unspecified nerve at ankle and foot level 	`,`	null	`],
	[`	S95	`,`	Injury of blood vessels at ankle and foot level Excl.: injury of posterior tibial artery and vein (S85.-) 	`,`	null	`],
	[`	S95.0	`,`	Injury of dorsal artery of foot 	`,`	null	`],
	[`	S95.1	`,`	Injury of plantar artery of foot 	`,`	null	`],
	[`	S95.2	`,`	Injury of dorsal vein of foot 	`,`	null	`],
	[`	S95.7	`,`	Injury of multiple blood vessels at ankle and foot level 	`,`	null	`],
	[`	S95.8	`,`	Injury of other blood vessels at ankle and foot level 	`,`	null	`],
	[`	S95.9	`,`	Injury of unspecified blood vessel at ankle and foot level 	`,`	null	`],
	[`	S96	`,`	Injury of muscle and tendon at ankle and foot level Excl.: injury of Achilles tendon (S86.0) 	`,`	null	`],
	[`	S96.0	`,`	Injury of muscle and tendon of long flexor muscle of toe at ankle and foot level 	`,`	null	`],
	[`	S96.1	`,`	Injury of muscle and tendon of long extensor muscle of toe at ankle and foot level 	`,`	null	`],
	[`	S96.2	`,`	Injury of intrinsic muscle and tendon at ankle and foot level 	`,`	null	`],
	[`	S96.7	`,`	Injury of multiple muscles and tendons at ankle and foot level 	`,`	null	`],
	[`	S96.8	`,`	Injury of other muscles and tendons at ankle and foot level 	`,`	null	`],
	[`	S96.9	`,`	Injury of unspecified muscle and tendon at ankle and foot level 	`,`	null	`],
	[`	S97	`,`	Crushing injury of ankle and foot 	`,`	null	`],
	[`	S97.0	`,`	Crushing injury of ankle 	`,`	null	`],
	[`	S97.1	`,`	Crushing injury of toe(s) 	`,`	null	`],
	[`	S97.8	`,`	Crushing injury of other parts of ankle and foot Crushing injury of foot NOS 	`,`	null	`],
	[`	S98	`,`	Traumatic amputation of ankle and foot 	`,`	null	`],
	[`	S98.0	`,`	Traumatic amputation of foot at ankle level 	`,`	null	`],
	[`	S98.1	`,`	Traumatic amputation of one toe 	`,`	null	`],
	[`	S98.2	`,`	Traumatic amputation of two or more toes 	`,`	null	`],
	[`	S98.3	`,`	Traumatic amputation of other parts of foot Combined traumatic amputation of toe(s) and other parts of foot 	`,`	null	`],
	[`	S98.4	`,`	Traumatic amputation of foot, level unspecified 	`,`	null	`],
	[`	S99	`,`	Other and unspecified injuries of ankle and foot 	`,`	null	`],
	[`	S99.7	`,`	Multiple injuries of ankle and foot Injuries classifiable to more than one of the categories S90-S98 	`,`	null	`],
	[`	S99.8	`,`	Other specified injuries of ankle and foot 	`,`	null	`],
	[`	S99.9	`,`	Unspecified injury of ankle and foot 	`,`	null	`],
							
];					
							
							
				
	
let CodeRangeS ={
	f0:function(val1=(-1),val2=(0)){
		let Range1 = SCodes.slice(val1,val2);
		Range1.reverse();
		document.documentElement.innerHTML += `<br>Showing S Codes ${Range1.length} items(s)`;

		for(value1 in Range1){
			    document.documentElement.style.cssText += "background-color:tan;";
				document.getElementById('scodesTR').outerHTML += `<tr><td style="background-color:navy;color:white;width:5%;padding:40px;border:2px solid white;font-weight:900;font-size:40px;text-align:center;">${Range1[value1][0]}</td><td style="background-color:black;color:white;width:90%;padding:20px;border:2px solid white;font-size:30px;">${Range1[value1][1]}</td><td style="background-color:navy;color:white;width:5%;padding:20px;border:2px solid white;font-weight:900;font-size:40px;text-align:center;">${Range1[value1][2]}</td></tr>`;			
		}

	},

};

	






	






