							
let TCodes = [	 						
	[`	ID	`,`	SYMPTOMS /PROBLEMS /ISSUES	`,`	SYSTEM	`],
	[`	T00	`,`	Superficial injuries involving multiple body regions 	`,`	null	`],
	[`	T00.0	`,`	Superficial injuries involving head with neck Superficial injuries of sites classifiable to S00.- and S10.- Excl.: with involvement of other body region(s) (T00.8) 	`,`	null	`],
	[`	T00.1	`,`	Superficial injuries involving thorax with abdomen, lower back and pelvis Superficial injuries of sites classifiable to S20.-, S30.- and T09.0 Excl.: with involvement of other body region(s) (T00.8) 	`,`	null	`],
	[`	T00.2	`,`	Superficial injuries involving multiple regions of upper limb(s) Superficial injuries of sites classifiable to S40.-, S50.-, S60.- and T11.0 Excl.: with involvement of: lower limb(s) (T00.6) thorax, abdomen, lower back and pelvis (T00.8) 	`,`	null	`],
	[`	T00.3	`,`	Superficial injuries involving multiple regions of lower limb(s) Superficial injuries of sites classifiable to S70.-, S80.-, S90.- and T13.0 Excl.: with involvement of: thorax, abdomen, lower back and pelvis (T00.8) upper limb(s) (T00.6) 	`,`	null	`],
	[`	T00.6	`,`	Superficial injuries involving multiple regions of upper limb(s) with lower limb(s) Superficial injuries of sites classifiable to T00.2 and T00.3 Excl.: with involvement of thorax, abdomen, lower back and pelvis (T00.8) 	`,`	null	`],
	[`	T00.8	`,`	Superficial injuries involving other combinations of body regions 	`,`	null	`],
	[`	T00.9	`,`	Multiple superficial injuries, unspecified Multiple: abrasions blisters (nonthermal) bruises contusions haematomas insect bites (nonvenomous) NOS 	`,`	null	`],
	[`	T01	`,`	Open wounds involving multiple body regions Excl.: traumatic amputations involving multiple body regions (T05.-) 	`,`	null	`],
	[`	T01.0	`,`	Open wounds involving head with neck Open wounds of sites classifiable to S01.- and S11.- Excl.: with involvement of other body region(s) (T01.8) 	`,`	null	`],
	[`	T01.1	`,`	Open wounds involving thorax with abdomen, lower back and pelvis Open wounds of sites classifiable to S21.-, S31.- and T09.1 Excl.: with involvement of other body region(s) (T01.8) 	`,`	null	`],
	[`	T01.2	`,`	Open wounds involving multiple regions of upper limb(s) Open wounds of sites classifiable to S41.-, S51.-, S61.- and T11.1 Excl.: with involvement of: lower limb(s) (T01.6) thorax, abdomen, lower back and pelvis (T01.8) 	`,`	null	`],
	[`	T01.3	`,`	Open wounds involving multiple regions of lower limb(s) Open wounds of sites classifiable to S71.-, S81.-, S91.- and T13.1 Excl.: with involvement of: thorax, abdomen, lower back and pelvis (T01.8) upper limb(s) (T01.6) 	`,`	null	`],
	[`	T01.6	`,`	Open wounds involving multiple regions of upper limb(s) with lower limb(s) Open wounds of sites classifiable to T01.2 and T01.3 Excl.: with involvement of thorax, abdomen, lower back and pelvis (T01.8) 	`,`	null	`],
	[`	T01.8	`,`	Open wounds involving other combinations of body regions 	`,`	null	`],
	[`	T01.9	`,`	Multiple open wounds, unspecified Multiple: animal bites cuts lacerations puncture wounds NOS 	`,`	null	`],
	[`	T02	`,`	Fractures involving multiple body regions The following subdivisions are provided for optional use in a supplementary character position where it is not possible or not desired to use multiple coding to identify fracture and open wound; a fracture not indicated as closed or open should be classified as closed. 0 closed 1 open 	`,`	null	`],
	[`	T02.0	`,`	Fractures involving head with neck Fractures of sites classifiable to S02.- and S12.- Excl.: with involvement of other body region(s) (T02.8) 	`,`	null	`],
	[`	T02.1	`,`	Fractures involving thorax with lower back and pelvis Fractures of sites classifiable to S22.-, S32.- and T08 Excl.: when combined with fractures of: limb(s) (T02.7) other body region(s) (T02.8) 	`,`	null	`],
	[`	T02.2	`,`	Fractures involving multiple regions of one upper limb Fractures of sites classifiable to S42.-, S52.-, S62.- and T10 of one upper limb Excl.: when combined with fractures of: lower limb(s) (T02.6) other upper limb (T02.4) thorax, lower back and pelvis (T02.7) 	`,`	null	`],
	[`	T02.3	`,`	Fractures involving multiple regions of one lower limb Fractures of sites classifiable to S72.-, S82.-, S92.- and T12 of one lower limb Excl.: when combined with fractures of: other lower limb (T02.5) thorax, lower back and pelvis (T02.7) upper limb(s) (T02.6) 	`,`	null	`],
	[`	T02.4	`,`	Fractures involving multiple regions of both upper limbs Fractures of sites classifiable to S42.-, S52.-, S62.- and T10 specified as bilateral Excl.: when combined with fractures of: lower limb(s) (T02.6) thorax, lower back and pelvis (T02.7) 	`,`	null	`],
	[`	T02.5	`,`	Fractures involving multiple regions of both lower limbs Fractures of sites classifiable to S72.-, S82.-, S92.- and T12 specified as bilateral Excl.: when combined with fractures of: thorax, lower back and pelvis (T02.7) upper limb(s) (T02.6) 	`,`	null	`],
	[`	T02.6	`,`	Fractures involving multiple regions of upper limb(s) with lower limb(s) Excl.: when combined with fractures of thorax, lower back and pelvis (T02.7) 	`,`	null	`],
	[`	T02.7	`,`	Fractures involving thorax with lower back and pelvis with limb(s) 	`,`	null	`],
	[`	T02.8	`,`	Fractures involving other combinations of body regions 	`,`	null	`],
	[`	T02.9	`,`	Multiple fractures, unspecified 	`,`	null	`],
	[`	T03	`,`	Dislocations, sprains and strains involving multiple body regions 	`,`	null	`],
	[`	T03.0	`,`	Dislocations, sprains and strains involving head with neck Dislocations, sprains and strains of sites classifiable to S03.- and S13.- Excl.: when combined with dislocations, sprains and strains of other body region(s) (T03.8) 	`,`	null	`],
	[`	T03.1	`,`	Dislocations, sprains and strains involving thorax with lower back and pelvis Dislocations, sprains and strains of sites classifiable to S23.-, S33.- and T09.2 Excl.: when combined with dislocations, sprains and strains of other body region(s) (T03.8) 	`,`	null	`],
	[`	T03.2	`,`	Dislocations, sprains and strains involving multiple regions of upper limb(s) Dislocations, sprains and strains of sites classifiable to S43.-, S53.-, S63.- and T11.2 Excl.: when combined with dislocations, sprains and strains of: lower limb(s) (T03.4) thorax, lower back and pelvis (T03.8) 	`,`	null	`],
	[`	T03.3	`,`	Dislocations, sprains and strains involving multiple regions of lower limb(s) Dislocations, sprains and strains of sites classifiable to S73.-, S83.-, S93.- and T13.2 Excl.: when combined with dislocations, sprains and strains of: thorax, lower back and pelvis (T03.8) upper limb(s) (T03.4) 	`,`	null	`],
	[`	T03.4	`,`	Dislocations, sprains and strains involving multiple regions of upper limb(s) with lower limb(s) Excl.: when combined with dislocations, sprains and strains of thorax, lower back and pelvis (T03.8) 	`,`	null	`],
	[`	T03.8	`,`	Dislocations, sprains and strains involving other combinations of body regions 	`,`	null	`],
	[`	T03.9	`,`	Multiple dislocations, sprains and strains, unspecified 	`,`	null	`],
	[`	T04	`,`	Crushing injuries involving multiple body regions 	`,`	null	`],
	[`	T04.0	`,`	Crushing injuries involving head with neck Crushing injuries of sites classifiable to S07.- and S17.- Excl.: with involvement of other body region(s) (T04.8) 	`,`	null	`],
	[`	T04.1	`,`	Crushing injuries involving thorax with abdomen, lower back and pelvis Crushing injury of: sites classifiable to S28.- and S38.- trunk NOS Excl.: with involvement of: limbs (T04.7) other body regions (T04.8) 	`,`	null	`],
	[`	T04.2	`,`	Crushing injuries involving multiple regions of upper limb(s) Crushing injury of: sites classifiable to S47.-, S57.- and S67.- upper limb NOS Excl.: with involvement of: lower limb(s) (T04.4) thorax, abdomen, lower back and pelvis (T04.7) 	`,`	null	`],
	[`	T04.3	`,`	Crushing injuries involving multiple regions of lower limb(s) Crushing injury of: lower limb NOS sites classifiable to S77.-, S87.- and S97.- Excl.: with involvement of: thorax, abdomen, lower back and pelvis (T04.7) upper limb(s) (T04.4) 	`,`	null	`],
	[`	T04.4	`,`	Crushing injuries involving multiple regions of upper limb(s) with lower limb(s) Excl.: with involvement of thorax, abdomen, lower back and pelvis (T04.7) 	`,`	null	`],
	[`	T04.7	`,`	Crushing injuries of thorax with abdomen, lower back and pelvis with limb(s) 	`,`	null	`],
	[`	T04.8	`,`	Crushing injuries involving other combinations of body regions 	`,`	null	`],
	[`	T04.9	`,`	Multiple crushing injuries, unspecified 	`,`	null	`],
	[`	T05	`,`	Traumatic amputations involving multiple body regions Incl.: avulsion involving multiple body regions Excl.: decapitation (S18) open wounds involving multiple body regions (T01.-) traumatic amputation of: arm NOS (T11.6) leg NOS (T13.6) trunk NOS (T09.6) 	`,`	null	`],
	[`	T05.0	`,`	Traumatic amputation of both hands 	`,`	null	`],
	[`	T05.1	`,`	Traumatic amputation of one hand and other arm [any level, except hand] 	`,`	null	`],
	[`	T05.2	`,`	Traumatic amputation of both arms [any level] 	`,`	null	`],
	[`	T05.3	`,`	Traumatic amputation of both feet 	`,`	null	`],
	[`	T05.4	`,`	Traumatic amputation of one foot and other leg [any level, except foot] 	`,`	null	`],
	[`	T05.5	`,`	Traumatic amputation of both legs [any level] 	`,`	null	`],
	[`	T05.6	`,`	Traumatic amputation of upper and lower limbs, any combination [any level] 	`,`	null	`],
	[`	T05.8	`,`	Traumatic amputations involving other combinations of body regions Transection of: abdomen thorax 	`,`	null	`],
	[`	T05.9	`,`	Multiple traumatic amputations, unspecified 	`,`	null	`],
	[`	T06	`,`	Other injuries involving multiple body regions, not elsewhere classified 	`,`	null	`],
	[`	T06.0	`,`	Injuries of brain and cranial nerves with injuries of nerves and spinal cord at neck level Injuries classifiable to S04.- and S06.- with injuries classifiable to S14.- 	`,`	null	`],
	[`	T06.1	`,`	Injuries of nerves and spinal cord involving other multiple body regions 	`,`	null	`],
	[`	T06.2	`,`	Injuries of nerves involving multiple body regions Multiple injuries of nerves NOS Excl.: with spinal cord involvement (T06.0-T06.1) 	`,`	null	`],
	[`	T06.3	`,`	Injuries of blood vessels involving multiple body regions 	`,`	null	`],
	[`	T06.4	`,`	Injuries of muscles and tendons involving multiple body regions 	`,`	null	`],
	[`	T06.5	`,`	Injuries of intrathoracic organs with intra-abdominal and pelvic organs 	`,`	null	`],
	[`	T06.8	`,`	Other specified injuries involving multiple body regions 	`,`	null	`],
	[`	T07	`,`	Unspecified multiple injuries Excl.: injury NOS (T14.9) 	`,`	null	`],
	[`	T08	`,`	Fracture of spine, level unspecified Excl.: multiple fractures of spine, level unspecified (T02.1) The following subdivisions are provided for optional use in a supplementary character position where it is not possible or not desired to use multiple coding to identify fracture and open wound; a fracture not indicated as closed or open should be classified as closed. 0 closed 1 open 	`,`	null	`],
	[`	T09	`,`	Other injuries of spine and trunk, level unspecified Excl.: crushing injury of trunk NOS (T04.1) multiple injuries of trunk (T00-T06) transection of trunk (T05.8) 	`,`	null	`],
	[`	T09.0	`,`	Superficial injury of trunk, level unspecified 	`,`	null	`],
	[`	T09.1	`,`	Open wound of trunk, level unspecified 	`,`	null	`],
	[`	T09.2	`,`	Dislocation, sprain and strain of unspecified joint and ligament of trunk 	`,`	null	`],
	[`	T09.3	`,`	Injury of spinal cord, level unspecified 	`,`	null	`],
	[`	T09.4	`,`	Injury of unspecified nerve, spinal nerve root and plexus of trunk 	`,`	null	`],
	[`	T09.5	`,`	Injury of unspecified muscle and tendon of trunk 	`,`	null	`],
	[`	T09.6	`,`	Traumatic amputation of trunk, level unspecified 	`,`	null	`],
	[`	T09.8	`,`	Other specified injuries of trunk, level unspecified 	`,`	null	`],
	[`	T09.9	`,`	Unspecified injury of trunk, level unspecified 	`,`	null	`],
	[`	T10	`,`	Fracture of upper limb, level unspecified Incl.: Broken arm NOS Fracture of arm NOS Excl.: multiple fractures of upper limb, level unspecified (T02.-) The following subdivisions are provided for optional use in a supplementary character position where it is not possible or not desired to use multiple coding to identify fracture and open wound; a fracture not indicated as closed or open should be classified as closed. 0 closed 1 open 	`,`	null	`],
	[`	T11	`,`	Other injuries of upper limb, level unspecified Excl.: crushing injury of upper limb NOS (T04.2) fracture of upper limb, level unspecified (T10) injuries involving multiple body regions (T00-T06) 	`,`	null	`],
	[`	T11.0	`,`	Superficial injury of upper limb, level unspecified 	`,`	null	`],
	[`	T11.1	`,`	Open wound of upper limb, level unspecified 	`,`	null	`],
	[`	T11.2	`,`	Dislocation, sprain and strain of unspecified joint and ligament of upper limb, level unspecified 	`,`	null	`],
	[`	T11.3	`,`	Injury of unspecified nerve of upper limb, level unspecified 	`,`	null	`],
	[`	T11.4	`,`	Injury of unspecified blood vessel of upper limb, level unspecified 	`,`	null	`],
	[`	T11.5	`,`	Injury of unspecified muscle and tendon of upper limb, level unspecified 	`,`	null	`],
	[`	T11.6	`,`	Traumatic amputation of upper limb, level unspecified Traumatic amputation of arm NOS 	`,`	null	`],
	[`	T11.8	`,`	Other specified injuries of upper limb, level unspecified 	`,`	null	`],
	[`	T11.9	`,`	Unspecified injury of upper limb, level unspecified Injury of arm NOS 	`,`	null	`],
	[`	T12	`,`	Fracture of lower limb, level unspecified Incl.: Broken leg NOS Fracture of leg NOS Excl.: multiple fractures of leg, level unspecified (T02.-) The following subdivisions are provided for optional use in a supplementary character position where it is not possible or not desired to use multiple coding to identify fracture and open wound; a fracture not indicated as closed or open should be classified as closed. 0 closed 1 open 	`,`	null	`],
	[`	T13	`,`	Other injuries of lower limb, level unspecified Excl.: crushing injury of lower limb NOS (T04.3) fracture of lower limb, level unspecified (T12) injuries involving multiple body regions (T00-T06) 	`,`	null	`],
	[`	T13.0	`,`	Superficial injury of lower limb, level unspecified 	`,`	null	`],
	[`	T13.1	`,`	Open wound of lower limb, level unspecified 	`,`	null	`],
	[`	T13.2	`,`	Dislocation, sprain and strain of unspecified joint and ligament of lower limb, level unspecified 	`,`	null	`],
	[`	T13.3	`,`	Injury of unspecified nerve of lower limb, level unspecified 	`,`	null	`],
	[`	T13.4	`,`	Injury of unspecified blood vessel of lower limb, level unspecified 	`,`	null	`],
	[`	T13.5	`,`	Injury of unspecified muscle and tendon of lower limb, level unspecified 	`,`	null	`],
	[`	T13.6	`,`	Traumatic amputation of lower limb, level unspecified Traumatic amputation of leg NOS 	`,`	null	`],
	[`	T13.8	`,`	Other specified injuries of lower limb, level unspecified 	`,`	null	`],
	[`	T13.9	`,`	Unspecified injury of lower limb, level unspecified Injury of leg NOS 	`,`	null	`],
	[`	T14	`,`	Injury of unspecified body region Excl.: injuries involving multiple body regions (T00-T07) 	`,`	null	`],
	[`	T14.0	`,`	Superficial injury of unspecified body region Abrasion Blister (nonthermal) Bruise Contusion Haematoma Injury from superficial foreign body (splinter) without major open wound Insect bite (nonvenomous) Superficial injury NOS Excl.: multiple superficial injuries NOS (T00.9) 	`,`	null	`],
	[`	T14.1	`,`	Open wound of unspecified body region Animal bite Cut Laceration Open wound Puncture wound with (penetrating) foreign body NOS Excl.: multiple: open wounds NOS (T01.9) traumatic amputations NOS (T05.9) traumatic amputation NOS (T14.7) 	`,`	null	`],
	[`	T14.2	`,`	Fracture of unspecified body region Fracture: NOS closed NOS dislocated NOS displaced NOS open NOS Excl.: multiple fractures NOS (T02.9) The following subdivisions are provided for optional use in a supplementary character position where it is not possible or not desired to use multiple coding to identify fracture and open wound; a fracture not indicated as closed or open should be classified as closed. 0 closed 1 open 	`,`	null	`],
	[`	T14.3	`,`	Dislocation, sprain and strain of unspecified body region Avulsion Laceration Sprain Strain Traumatic: haemarthrosis rupture subluxation tear of joint (capsule) ligament NOS Excl.: multiple dislocations, sprains and strains NOS (T03.9) 	`,`	null	`],
	[`	T14.4	`,`	Injury of nerve(s) of unspecified body region Injury of nerve Traumatic: division of nerve haematomyelia paralysis (transient) NOS Excl.: multiple injuries of nerves NOS (T06.2) 	`,`	null	`],
	[`	T14.5	`,`	Injury of blood vessel(s) of unspecified body region Avulsion Cut Injury Laceration Traumatic: aneurysm or fistula (arteriovenous) arterial haematoma rupture of blood vessel(s) NOS Excl.: multiple injuries of blood vessels NOS (T06.3) 	`,`	null	`],
	[`	T14.6	`,`	Injury of muscles and tendons of unspecified body region Avulsion Cut Injury Laceration Sprain Strain Traumatic rupture of muscle(s) NOS and tendon(s) NOS Excl.: multiple injuries of tendons and muscles NOS (T06.4) 	`,`	null	`],
	[`	T14.7	`,`	Crushing injury and traumatic amputation of unspecified body region Crushing injury NOS Traumatic amputation NOS Excl.: multiple: crushing injuries NOS (T04.9) traumatic amputations NOS (T05.9) 	`,`	null	`],
	[`	T14.8	`,`	Other injuries of unspecified body region 	`,`	null	`],
	[`	T14.9	`,`	Injury, unspecified Excl.: multiple injuries NOS (T07) 	`,`	null	`],
	[`	T15	`,`	Foreign body on external eye Excl.: foreign body in penetrating wound of: orbit and eyeball (S05.4-S05.5) orbit and eyeball retained (old) (H05.5, H44.6-H44.7) retained foreign body in eyelid (H02.8) 	`,`	null	`],
	[`	T15.0	`,`	Foreign body in cornea 	`,`	null	`],
	[`	T15.1	`,`	Foreign body in conjunctival sac 	`,`	null	`],
	[`	T15.8	`,`	Foreign body in other and multiple parts of external eye Foreign body in lacrimal punctum 	`,`	null	`],
	[`	T15.9	`,`	Foreign body on external eye, part unspecified 	`,`	null	`],
	[`	T16	`,`	Foreign body in ear Incl.: Auditory canal 	`,`	null	`],
	[`	T17	`,`	Foreign body in respiratory tract Incl.: asphyxia due to foreign body choked on: food (regurgitated) phlegm inhalation of liquid or vomitus NOS 	`,`	null	`],
	[`	T17.0	`,`	Foreign body in nasal sinus 	`,`	null	`],
	[`	T17.1	`,`	Foreign body in nostril Nose NOS 	`,`	null	`],
	[`	T17.2	`,`	Foreign body in pharynx Nasopharynx Throat NOS 	`,`	null	`],
	[`	T17.3	`,`	Foreign body in larynx 	`,`	null	`],
	[`	T17.4	`,`	Foreign body in trachea 	`,`	null	`],
	[`	T17.5	`,`	Foreign body in bronchus 	`,`	null	`],
	[`	T17.8	`,`	Foreign body in other and multiple parts of respiratory tract Bronchioles Lung 	`,`	null	`],
	[`	T17.9	`,`	Foreign body in respiratory tract, part unspecified 	`,`	null	`],
	[`	T18	`,`	Foreign body in alimentary tract Excl.: foreign body in pharynx (T17.2) 	`,`	null	`],
	[`	T18.0	`,`	Foreign body in mouth 	`,`	null	`],
	[`	T18.1	`,`	Foreign body in oesophagus 	`,`	null	`],
	[`	T18.2	`,`	Foreign body in stomach 	`,`	null	`],
	[`	T18.3	`,`	Foreign body in small intestine 	`,`	null	`],
	[`	T18.4	`,`	Foreign body in colon 	`,`	null	`],
	[`	T18.5	`,`	Foreign body in anus and rectum Rectosigmoid (junction) 	`,`	null	`],
	[`	T18.8	`,`	Foreign body in other and multiple parts of alimentary tract 	`,`	null	`],
	[`	T18.9	`,`	Foreign body in alimentary tract, part unspecified Digestive system NOS Swallowed foreign body NOS 	`,`	null	`],
	[`	T19	`,`	Foreign body in genitourinary tract Excl.: contraceptive device (intrauterine)(vaginal): mechanical complication of (T83.3) presence of (Z97.5) 	`,`	null	`],
	[`	T19.0	`,`	Foreign body in urethra 	`,`	null	`],
	[`	T19.1	`,`	Foreign body in bladder 	`,`	null	`],
	[`	T19.2	`,`	Foreign body in vulva and vagina 	`,`	null	`],
	[`	T19.3	`,`	Foreign body in uterus [any part] 	`,`	null	`],
	[`	T19.8	`,`	Foreign body in other and multiple parts of genitourinary tract 	`,`	null	`],
	[`	T19.9	`,`	Foreign body in genitourinary tract, part unspecified 	`,`	null	`],
	[`	T20	`,`	Burn and corrosion of head and neck Incl.: ear [any part] eye with other parts of face, head and neck lip nose (septum) scalp [any part] temple (region) Excl.: burn and corrosion (of): confined to eye and adnexa (T26.-) mouth and pharynx (T28.-) 	`,`	null	`],
	[`	T20.0	`,`	Burn of unspecified degree of head and neck 	`,`	null	`],
	[`	T20.1	`,`	Burn of first degree of head and neck 	`,`	null	`],
	[`	T20.2	`,`	Burn of second degree of head and neck 	`,`	null	`],
	[`	T20.3	`,`	Burn of third degree of head and neck 	`,`	null	`],
	[`	T20.4	`,`	Corrosion of unspecified degree of head and neck 	`,`	null	`],
	[`	T20.5	`,`	Corrosion of first degree of head and neck 	`,`	null	`],
	[`	T20.6	`,`	Corrosion of second degree of head and neck 	`,`	null	`],
	[`	T20.7	`,`	Corrosion of third degree of head and neck 	`,`	null	`],
	[`	T21	`,`	Burn and corrosion of trunk Incl.: abdominal wall anus back [any part] breast buttock chest wall flank groin interscapular region labium (majus)(minus) penis perineum scrotum testis vulva Excl.: burn and corrosion of: axilla (T22.-) scapular region (T22.-) 	`,`	null	`],
	[`	T21.0	`,`	Burn of unspecified degree of trunk 	`,`	null	`],
	[`	T21.1	`,`	Burn of first degree of trunk 	`,`	null	`],
	[`	T21.2	`,`	Burn of second degree of trunk 	`,`	null	`],
	[`	T21.3	`,`	Burn of third degree of trunk 	`,`	null	`],
	[`	T21.4	`,`	Corrosion of unspecified degree of trunk 	`,`	null	`],
	[`	T21.5	`,`	Corrosion of first degree of trunk 	`,`	null	`],
	[`	T21.6	`,`	Corrosion of second degree of trunk 	`,`	null	`],
	[`	T21.7	`,`	Corrosion of third degree of trunk 	`,`	null	`],
	[`	T22	`,`	Burn and corrosion of shoulder and upper limb, except wrist and hand Incl.: arm [any part, except wrist and hand alone] axilla scapular region Excl.: burn and corrosion of: interscapular region (T21.-) wrist and hand alone (T23.-) 	`,`	null	`],
	[`	T22.0	`,`	Burn of unspecified degree of shoulder and upper limb, except wrist and hand 	`,`	null	`],
	[`	T22.1	`,`	Burn of first degree of shoulder and upper limb, except wrist and hand 	`,`	null	`],
	[`	T22.2	`,`	Burn of second degree of shoulder and upper limb, except wrist and hand 	`,`	null	`],
	[`	T22.3	`,`	Burn of third degree of shoulder and upper limb, except wrist and hand 	`,`	null	`],
	[`	T22.4	`,`	Corrosion of unspecified degree of shoulder and upper limb, except wrist and hand 	`,`	null	`],
	[`	T22.5	`,`	Corrosion of first degree of shoulder and upper limb, except wrist and hand 	`,`	null	`],
	[`	T22.6	`,`	Corrosion of second degree of shoulder and upper limb, except wrist and hand 	`,`	null	`],
	[`	T22.7	`,`	Corrosion of third degree of shoulder and upper limb, except wrist and hand 	`,`	null	`],
	[`	T23	`,`	Burn and corrosion of wrist and hand Incl.: finger (nail) palm thumb (nail) 	`,`	null	`],
	[`	T23.0	`,`	Burn of unspecified degree of wrist and hand 	`,`	null	`],
	[`	T23.1	`,`	Burn of first degree of wrist and hand 	`,`	null	`],
	[`	T23.2	`,`	Burn of second degree of wrist and hand 	`,`	null	`],
	[`	T23.3	`,`	Burn of third degree of wrist and hand 	`,`	null	`],
	[`	T23.4	`,`	Corrosion of unspecified degree of wrist and hand 	`,`	null	`],
	[`	T23.5	`,`	Corrosion of first degree of wrist and hand 	`,`	null	`],
	[`	T23.6	`,`	Corrosion of second degree of wrist and hand 	`,`	null	`],
	[`	T23.7	`,`	Corrosion of third degree of wrist and hand 	`,`	null	`],
	[`	T24	`,`	Burn and corrosion of hip and lower limb, except ankle and foot Incl.: leg [any part, except ankle and foot alone] Excl.: burn and corrosion of ankle and foot alone (T25.-) 	`,`	null	`],
	[`	T24.0	`,`	Burn of unspecified degree of hip and lower limb, except ankle and foot 	`,`	null	`],
	[`	T24.1	`,`	Burn of first degree of hip and lower limb, except ankle and foot 	`,`	null	`],
	[`	T24.2	`,`	Burn of second degree of hip and lower limb, except ankle and foot 	`,`	null	`],
	[`	T24.3	`,`	Burn of third degree of hip and lower limb, except ankle and foot 	`,`	null	`],
	[`	T24.4	`,`	Corrosion of unspecified degree of hip and lower limb, except ankle and foot 	`,`	null	`],
	[`	T24.5	`,`	Corrosion of first degree of hip and lower limb, except ankle and foot 	`,`	null	`],
	[`	T24.6	`,`	Corrosion of second degree of hip and lower limb, except ankle and foot 	`,`	null	`],
	[`	T24.7	`,`	Corrosion of third degree of hip and lower limb, except ankle and foot 	`,`	null	`],
	[`	T25	`,`	Burn and corrosion of ankle and foot Incl.: toe(s) 	`,`	null	`],
	[`	T25.0	`,`	Burn of unspecified degree of ankle and foot 	`,`	null	`],
	[`	T25.1	`,`	Burn of first degree of ankle and foot 	`,`	null	`],
	[`	T25.2	`,`	Burn of second degree of ankle and foot 	`,`	null	`],
	[`	T25.3	`,`	Burn of third degree of ankle and foot 	`,`	null	`],
	[`	T25.4	`,`	Corrosion of unspecified degree of ankle and foot 	`,`	null	`],
	[`	T25.5	`,`	Corrosion of first degree of ankle and foot 	`,`	null	`],
	[`	T25.6	`,`	Corrosion of second degree of ankle and foot 	`,`	null	`],
	[`	T25.7	`,`	Corrosion of third degree of ankle and foot 	`,`	null	`],
	[`	T33.0	`,`	Superficial frostbite of head 	`,`	null	`],
	[`	T33.1	`,`	Superficial frostbite of neck 	`,`	null	`],
	[`	T33.2	`,`	Superficial frostbite of thorax 	`,`	null	`],
	[`	T33.3	`,`	Superficial frostbite of abdominal wall, lower back and pelvis 	`,`	null	`],
	[`	T33.4	`,`	Superficial frostbite of arm Excl.: superficial frostbite of wrist and hand alone (T33.5) 	`,`	null	`],
	[`	T33.5	`,`	Superficial frostbite of wrist and hand 	`,`	null	`],
	[`	T33.6	`,`	Superficial frostbite of hip and thigh 	`,`	null	`],
	[`	T33.7	`,`	Superficial frostbite of knee and lower leg Excl.: superficial frostbite of ankle and foot alone (T33.8) 	`,`	null	`],
	[`	T33.8	`,`	Superficial frostbite of ankle and foot 	`,`	null	`],
	[`	T33.9	`,`	Superficial frostbite of other and unspecified sites Superficial frostbite (of): NOS leg NOS trunk NOS 	`,`	null	`],
	[`	T34	`,`	Frostbite with tissue necrosis Excl.: frostbite with tissue necrosis involving multiple body regions (T35.1) 	`,`	null	`],
	[`	T34.0	`,`	Frostbite with tissue necrosis of head 	`,`	null	`],
	[`	T34.1	`,`	Frostbite with tissue necrosis of neck 	`,`	null	`],
	[`	T34.2	`,`	Frostbite with tissue necrosis of thorax 	`,`	null	`],
	[`	T34.3	`,`	Frostbite with tissue necrosis of abdominal wall, lower back and pelvis 	`,`	null	`],
	[`	T34.4	`,`	Frostbite with tissue necrosis of arm Excl.: frostbite with tissue necrosis of wrist and hand alone (T34.5) 	`,`	null	`],
	[`	T34.5	`,`	Frostbite with tissue necrosis of wrist and hand 	`,`	null	`],
	[`	T34.6	`,`	Frostbite with tissue necrosis of hip and thigh 	`,`	null	`],
	[`	T34.7	`,`	Frostbite with tissue necrosis of knee and lower leg Excl.: frostbite with tissue necrosis of ankle and foot alone (T34.8) 	`,`	null	`],
	[`	T34.8	`,`	Frostbite with tissue necrosis of ankle and foot 	`,`	null	`],
	[`	T34.9	`,`	Frostbite with tissue necrosis of other and unspecified sites Frostbite with tissue necrosis (of): NOS leg NOS trunk NOS 	`,`	null	`],
	[`	T35	`,`	Frostbite involving multiple body regions and unspecified frostbite 	`,`	null	`],
	[`	T35.0	`,`	Superficial frostbite involving multiple body regions Multiple superficial frostbite NOS 	`,`	null	`],
	[`	T35.1	`,`	Frostbite with tissue necrosis involving multiple body regions Multiple frostbite with tissue necrosis NOS 	`,`	null	`],
	[`	T35.2	`,`	Unspecified frostbite of head and neck 	`,`	null	`],
	[`	T35.3	`,`	Unspecified frostbite of thorax, abdomen, lower back and pelvis Frostbite of trunk NOS 	`,`	null	`],
	[`	T35.4	`,`	Unspecified frostbite of upper limb 	`,`	null	`],
	[`	T35.5	`,`	Unspecified frostbite of lower limb 	`,`	null	`],
	[`	T35.6	`,`	Unspecified frostbite involving multiple body regions Multiple frostbite NOS 	`,`	null	`],
	[`	T35.7	`,`	Unspecified frostbite of unspecified site Frostbite NOS 	`,`	null	`],
	[`	T36	`,`	Poisoning by systemic antibiotics Excl.: antibiotics: antineoplastic (T45.1) locally applied NEC (T49.0) topically used for: ear, nose and throat (T49.6) eye (T49.5) 	`,`	null	`],
	[`	T36.0	`,`	Penicillins 	`,`	null	`],
	[`	T36.1	`,`	Cefalosporins and other beta-lactam antibiotics 	`,`	null	`],
	[`	T36.2	`,`	Chloramphenicol group 	`,`	null	`],
	[`	T36.3	`,`	Macrolides 	`,`	null	`],
	[`	T36.4	`,`	Tetracyclines 	`,`	null	`],
	[`	T36.5	`,`	Aminoglycosides Streptomycin 	`,`	null	`],
	[`	T36.6	`,`	Rifamycins 	`,`	null	`],
	[`	T36.7	`,`	Antifungal antibiotics, systemically used 	`,`	null	`],
	[`	T36.8	`,`	Other systemic antibiotics 	`,`	null	`],
	[`	T36.9	`,`	Systemic antibiotic, unspecified 	`,`	null	`],
	[`	T37	`,`	Poisoning by other systemic anti-infectives and antiparasitics Excl.: anti-infectives: locally applied NEC (T49.0) topically used (for): ear, nose and throat (T49.6) eye (T49.5) 	`,`	null	`],
	[`	T37.0	`,`	Sulfonamides 	`,`	null	`],
	[`	T37.1	`,`	Antimycobacterial drugs Excl.: rifamycins (T36.6) streptomycin (T36.5) 	`,`	null	`],
	[`	T37.2	`,`	Antimalarials and drugs acting on other blood protozoa Excl.: hydroxyquinoline derivatives (T37.8) 	`,`	null	`],
	[`	T37.3	`,`	Other antiprotozoal drugs 	`,`	null	`],
	[`	T37.4	`,`	Anthelminthics 	`,`	null	`],
	[`	T37.5	`,`	Antiviral drugs Excl.: amantadine (T42.8) cytarabine (T45.1) 	`,`	null	`],
	[`	T37.8	`,`	Other specified systemic anti-infectives and antiparasitics Hydroxyquinoline derivatives Excl.: antimalarial drugs (T37.2) 	`,`	null	`],
	[`	T37.9	`,`	Systemic anti-infective and antiparasitic, unspecified 	`,`	null	`],
	[`	T38	`,`	Poisoning by hormones and their synthetic substitutes and antagonists, not elsewhere classified Excl.: mineralocorticoids and their antagonists (T50.0) oxytocic hormones (T48.0) parathyroid hormones and derivatives (T50.9) 	`,`	null	`],
	[`	T38.0	`,`	Glucocorticoids and synthetic analogues Excl.: glucocorticoids, topically used (T49.-) 	`,`	null	`],
	[`	T38.1	`,`	Thyroid hormones and substitutes 	`,`	null	`],
	[`	T38.2	`,`	Antithyroid drugs 	`,`	null	`],
	[`	T38.3	`,`	Insulin and oral hypoglycaemic [antidiabetic] drugs T38.4 Oral contraceptives Multiple- and single-ingredient preparations 	`,`	null	`],
	[`	T38.5	`,`	Other estrogens and progestogens Mixtures and substitutes 	`,`	null	`],
	[`	T38.6	`,`	Antigonadotrophins, antiestrogens, antiandrogens, not elsewhere classified Tamoxifen 	`,`	null	`],
	[`	T38.7	`,`	Androgens and anabolic congeners 	`,`	null	`],
	[`	T38.8	`,`	Other and unspecified hormones and their synthetic substitutes Anterior pituitary [adenohypophyseal] hormones 	`,`	null	`],
	[`	T38.9	`,`	Other and unspecified hormone antagonists 	`,`	null	`],
	[`	T39	`,`	Poisoning by nonopioid analgesics, antipyretics and antirheumatics 	`,`	null	`],
	[`	T39.0	`,`	Salicylates T39.1 4-Aminophenol derivatives 	`,`	null	`],
	[`	T39.2	`,`	Pyrazolone derivatives 	`,`	null	`],
	[`	T39.3	`,`	Other nonsteroidal anti-inflammatory drugs [NSAID] 	`,`	null	`],
	[`	T39.4	`,`	Antirheumatics, not elsewhere classified Excl.: glucocorticoids (T38.0) salicylates (T39.0) 	`,`	null	`],
	[`	T39.8	`,`	Other nonopioid analgesics and antipyretics, not elsewhere classified 	`,`	null	`],
	[`	T39.9	`,`	Nonopioid analgesic, antipyretic and antirheumatic, unspecified 	`,`	null	`],
	[`	T40	`,`	Poisoning by narcotics and psychodysleptics [hallucinogens] Excl.: intoxication meaning inebriation (F10-F19) 	`,`	null	`],
	[`	T40.0	`,`	Opium 	`,`	null	`],
	[`	T40.1	`,`	Heroin 	`,`	null	`],
	[`	T40.2	`,`	Other opioids Codeine Morphine 	`,`	null	`],
	[`	T40.3	`,`	Methadone 	`,`	null	`],
	[`	T40.4	`,`	Other synthetic narcotics Pethidine 	`,`	null	`],
	[`	T40.5	`,`	Cocaine 	`,`	null	`],
	[`	T40.6	`,`	Other and unspecified narcotics 	`,`	null	`],
	[`	T40.7	`,`	Cannabis (derivatives) 	`,`	null	`],
	[`	T40.8	`,`	Lysergide [LSD] 	`,`	null	`],
	[`	T40.9	`,`	Other and unspecified psychodysleptics [hallucinogens] Mescaline Psilocin Psilocybine 	`,`	null	`],
	[`	T41	`,`	Poisoning by anaesthetics and therapeutic gases Excl.: benzodiazepines (T42.4) cocaine (T40.5) opioids (T40.0-T40.2) 	`,`	null	`],
	[`	T41.0	`,`	Inhaled anaesthetics Excl.: oxygen (T41.5) 	`,`	null	`],
	[`	T41.1	`,`	Intravenous anaesthetics Thiobarbiturates 	`,`	null	`],
	[`	T41.2	`,`	Other and unspecified general anaesthetics 	`,`	null	`],
	[`	T41.3	`,`	Local anaesthetics 	`,`	null	`],
	[`	T41.4	`,`	Anaesthetic, unspecified 	`,`	null	`],
	[`	T41.5	`,`	Therapeutic gases Carbon dioxide Oxygen 	`,`	null	`],
	[`	T42	`,`	Poisoning by antiepileptic, sedative-hypnotic and antiparkinsonism drugs Excl.: intoxication meaning inebriation (F10-F19) 	`,`	null	`],
	[`	T42.0	`,`	Hydantoin derivatives 	`,`	null	`],
	[`	T42.1	`,`	Iminostilbenes Carbamazepine 	`,`	null	`],
	[`	T42.2	`,`	Succinimides and oxazolidinediones 	`,`	null	`],
	[`	T42.3	`,`	Barbiturates Excl.: thiobarbiturates (T41.1) 	`,`	null	`],
	[`	T42.4	`,`	Benzodiazepines 	`,`	null	`],
	[`	T42.5	`,`	Mixed antiepileptics, not elsewhere classified 	`,`	null	`],
	[`	T42.6	`,`	Other antiepileptic and sedative-hypnotic drugs Methaqualone Valproic acid Excl.: carbamazepine (T42.1) 	`,`	null	`],
	[`	T42.7	`,`	Antiepileptic and sedative-hypnotic drugs, unspecified Sleeping: draught drug tablet NOS 	`,`	null	`],
	[`	T42.8	`,`	Antiparkinsonism drugs and other central muscle-tone depressants Amantadine 	`,`	null	`],
	[`	T43	`,`	Poisoning by psychotropic drugs, not elsewhere classified Excl.: appetite depressants (T50.5) barbiturates (T42.3) benzodiazepines (T42.4) intoxication meaning inebriation (F10-F19) methaqualone (T42.6) psychodysleptics [hallucinogens] (T40.7-T40.9) 	`,`	null	`],
	[`	T43.0	`,`	Tricyclic and tetracyclic antidepressants 	`,`	null	`],
	[`	T43.1	`,`	Monoamine-oxidase-inhibitor antidepressants 	`,`	null	`],
	[`	T43.2	`,`	Other and unspecified antidepressants 	`,`	null	`],
	[`	T43.3	`,`	Phenothiazine antipsychotics and neuroleptics 	`,`	null	`],
	[`	T43.4	`,`	Butyrophenone and thioxanthene neuroleptics 	`,`	null	`],
	[`	T43.5	`,`	Other and unspecified antipsychotics and neuroleptics Excl.: rauwolfia (T46.5) 	`,`	null	`],
	[`	T43.6	`,`	Psychostimulants with abuse potential Excl.: cocaine (T40.5) 	`,`	null	`],
	[`	T43.8	`,`	Other psychotropic drugs, not elsewhere classified 	`,`	null	`],
	[`	T43.9	`,`	Psychotropic drug, unspecified 	`,`	null	`],
	[`	T44	`,`	Poisoning by drugs primarily affecting the autonomic nervous system 	`,`	null	`],
	[`	T44.0	`,`	Anticholinesterase agents 	`,`	null	`],
	[`	T44.1	`,`	Other parasympathomimetics [cholinergics] 	`,`	null	`],
	[`	T44.2	`,`	Ganglionic blocking drugs, not elsewhere classified 	`,`	null	`],
	[`	T44.3	`,`	Other parasympatholytics [anticholinergics and antimuscarinics] and spasmolytics, not elsewhere classified Papaverine 	`,`	null	`],
	[`	T44.4	`,`	Predominantly alpha-adrenoreceptor agonists, not elsewhere classified Metaraminol 	`,`	null	`],
	[`	T44.5	`,`	Predominantly beta-adrenoreceptor agonists, not elsewhere classified Excl.: beta-adrenoreceptor agonists used in asthma therapy (T48.6) 	`,`	null	`],
	[`	T44.6	`,`	Alpha-adrenoreceptor antagonists, not elsewhere classified Excl.: ergot alkaloids (T48.0) 	`,`	null	`],
	[`	T44.7	`,`	Beta-adrenoreceptor antagonists, not elsewhere classified 	`,`	null	`],
	[`	T44.8	`,`	Centrally acting and adrenergic-neuron-blocking agents, not elsewhere classified Excl.: clonidine (T46.5) guanethidine (T46.5) 	`,`	null	`],
	[`	T44.9	`,`	Other and unspecified drugs primarily affecting the autonomic nervous system Drug stimulating both alpha- and beta-adrenoreceptors 	`,`	null	`],
	[`	T45	`,`	Poisoning by primarily systemic and haematological agents, not elsewhere classified 	`,`	null	`],
	[`	T45.0	`,`	Antiallergic and antiemetic drugs Excl.: phenothiazine-based neuroleptics (T43.3) 	`,`	null	`],
	[`	T45.1	`,`	Antineoplastic and immunosuppressive drugs Antineoplastic antibiotics Cytarabine Excl.: tamoxifen (T38.6) 	`,`	null	`],
	[`	T45.2	`,`	Vitamins, not elsewhere classified Excl.: nicotinic acid (derivatives) (T46.7) vitamin K (T45.7) 	`,`	null	`],
	[`	T45.3	`,`	Enzymes, not elsewhere classified 	`,`	null	`],
	[`	T45.4	`,`	Iron and its compounds 	`,`	null	`],
	[`	T45.5	`,`	Anticoagulants 	`,`	null	`],
	[`	T45.6	`,`	Fibrinolysis-affecting drugs 	`,`	null	`],
	[`	T45.7	`,`	Anticoagulant antagonists, vitamin K and other coagulants 	`,`	null	`],
	[`	T45.8	`,`	Other primarily systemic and haematological agents Liver preparations and other antianaemic agents Natural blood and blood products Plasma substitute Excl.: immunoglobulin (T50.9) iron (T45.4) 	`,`	null	`],
	[`	T45.9	`,`	Primarily systemic and haematological agent, unspecified 	`,`	null	`],
	[`	T46	`,`	Poisoning by agents primarily affecting the cardiovascular system Excl.: metaraminol (T44.4) 	`,`	null	`],
	[`	T46.0	`,`	Cardiac-stimulant glycosides and drugs of similar action 	`,`	null	`],
	[`	T46.1	`,`	Calcium-channel blockers 	`,`	null	`],
	[`	T46.2	`,`	Other antidysrhythmic drugs, not elsewhere classified Excl.: beta-adrenoreceptor antagonists (T44.7) 	`,`	null	`],
	[`	T46.3	`,`	Coronary vasodilators, not elsewhere classified Dipyridamole Excl.: beta-adrenoreceptor antagonists (T44.7) calcium-channel blockers (T46.1) 	`,`	null	`],
	[`	T46.4	`,`	Angiotensin-converting-enzyme inhibitors 	`,`	null	`],
	[`	T46.5	`,`	Other antihypertensive drugs, not elsewhere classified Clonidine Guanethidine Rauwolfia Excl.: beta-adrenoreceptor antagonists (T44.7) calcium-channel blockers (T46.1) diuretics (T50.0-T50.2) 	`,`	null	`],
	[`	T46.6	`,`	Antihyperlipidaemic and antiarteriosclerotic drugs 	`,`	null	`],
	[`	T46.7	`,`	Peripheral vasodilators Nicotinic acid (derivatives) Excl.: papaverine (T44.3) 	`,`	null	`],
	[`	T46.8	`,`	Antivaricose drugs, including sclerosing agents 	`,`	null	`],
	[`	T46.9	`,`	Other and unspecified agents primarily affecting the cardiovascular system 	`,`	null	`],
	[`	T47	`,`	Poisoning by agents primarily affecting the gastrointestinal system 	`,`	null	`],
	[`	T47.0	`,`	Histamine H2-receptor antagonists 	`,`	null	`],
	[`	T47.1	`,`	Other antacids and anti-gastric-secretion drugs 	`,`	null	`],
	[`	T47.2	`,`	Stimulant laxatives 	`,`	null	`],
	[`	T47.3	`,`	Saline and osmotic laxatives 	`,`	null	`],
	[`	T47.4	`,`	Other laxatives Intestinal atonia drugs 	`,`	null	`],
	[`	T47.5	`,`	Digestants 	`,`	null	`],
	[`	T47.6	`,`	Antidiarrhoeal drugs Excl.: systemic antibiotics and other anti-infectives (T36-T37) 	`,`	null	`],
	[`	T47.7	`,`	Emetics 	`,`	null	`],
	[`	T47.8	`,`	Other agents primarily affecting the gastrointestinal system 	`,`	null	`],
	[`	T47.9	`,`	Agent primarily affecting the gastrointestinal system, unspecified 	`,`	null	`],
	[`	T48	`,`	Poisoning by agents primarily acting on smooth and skeletal muscles and the respiratory system 	`,`	null	`],
	[`	T48.0	`,`	Oxytocic drugs Excl.: estrogens, progestogens and antagonists (T38.4-T38.6) 	`,`	null	`],
	[`	T48.1	`,`	Skeletal muscle relaxants [neuromuscular blocking agents] 	`,`	null	`],
	[`	T48.2	`,`	Other and unspecified agents primarily acting on muscles 	`,`	null	`],
	[`	T48.3	`,`	Antitussives 	`,`	null	`],
	[`	T48.4	`,`	Expectorants 	`,`	null	`],
	[`	T48.5	`,`	Anti-common-cold drugs 	`,`	null	`],
	[`	T48.6	`,`	Antiasthmatics, not elsewhere classified Beta-adrenoreceptor agonists used in asthma therapy Salbutamol Excl.: beta-adrenoreceptor agonists not used in asthma therapy (T44.5) anterior pituitary [adenohypophyseal] hormones (T38.8) 	`,`	null	`],
	[`	T48.7	`,`	Other and unspecified agents primarily acting on the respiratory system 	`,`	null	`],
	[`	T49	`,`	Poisoning by topical agents primarily affecting skin and mucous membrane and by ophthalmological, otorhinolaryngological and dental drugs Incl.: glucocorticoids, topically used 	`,`	null	`],
	[`	T49.0	`,`	Local antifungal, anti-infective and anti-inflammatory drugs, not elsewhere classified 	`,`	null	`],
	[`	T49.1	`,`	Antipruritics 	`,`	null	`],
	[`	T49.2	`,`	Local astringents and local detergents 	`,`	null	`],
	[`	T49.3	`,`	Emollients, demulcents and protectants 	`,`	null	`],
	[`	T49.4	`,`	Keratolytics, keratoplastics and other hair treatment drugs and preparations 	`,`	null	`],
	[`	T49.5	`,`	Ophthalmological drugs and preparations Eye anti-infectives 	`,`	null	`],
	[`	T49.6	`,`	Otorhinolaryngological drugs and preparations Ear, nose and throat anti-infectives 	`,`	null	`],
	[`	T49.7	`,`	Dental drugs, topically applied 	`,`	null	`],
	[`	T49.8	`,`	Other topical agents Spermicides 	`,`	null	`],
	[`	T49.9	`,`	Topical agent, unspecified 	`,`	null	`],
	[`	T50	`,`	Poisoning by diuretics and other and unspecified drugs, medicaments and biological substances 	`,`	null	`],
	[`	T50.0	`,`	Mineralocorticoids and their antagonists 	`,`	null	`],
	[`	T50.1	`,`	Loop [high-ceiling] diuretics 	`,`	null	`],
	[`	T50.2	`,`	Carbonic-anhydrase inhibitors, benzothiadiazides and other diuretics Acetazolamide 	`,`	null	`],
	[`	T50.3	`,`	Electrolytic, caloric and water-balance agents Oral rehydration salts 	`,`	null	`],
	[`	T50.4	`,`	Drugs affecting uric acid metabolism 	`,`	null	`],
	[`	T50.5	`,`	Appetite depressants 	`,`	null	`],
	[`	T50.6	`,`	Antidotes and chelating agents, not elsewhere classified Alcohol deterrents 	`,`	null	`],
	[`	T50.7	`,`	Analeptics and opioid receptor antagonists 	`,`	null	`],
	[`	T50.8	`,`	Diagnostic agents 	`,`	null	`],
	[`	T50.9	`,`	Other and unspecified drugs, medicaments and biological substances Acidifying agents Alkalizing agents Immunoglobulin Immunologicals Lipotropic drugs Parathyroid hormones and derivatives 	`,`	null	`],
	[`	T51	`,`	Toxic effect of alcohol 	`,`	null	`],
	[`	T51.0	`,`	Ethanol Ethyl alcohol Excl.: acute alcohol intoxication or "hangover" effects (F10.0) drunkenness (F10.0) pathological alcohol intoxication (F10.0) 	`,`	null	`],
	[`	T51.1	`,`	Methanol Methyl alcohol 	`,`	null	`],
	[`	T51.2	`,`	2-Propanol Isopropyl alcohol 	`,`	null	`],
	[`	T51.3	`,`	Fusel oil Alcohol: amyl butyl [1-butanol] propyl [1-propanol] 	`,`	null	`],
	[`	T51.8	`,`	Other alcohols 	`,`	null	`],
	[`	T51.9	`,`	Alcohol, unspecified 	`,`	null	`],
	[`	T52	`,`	Toxic effect of organic solvents Excl.: halogen derivatives of aliphatic and aromatic hydrocarbons (T53.-) 	`,`	null	`],
	[`	T52.0	`,`	Petroleum products Gasoline [petrol] Kerosine [paraffin oil] Paraffin wax Petroleum: ether naphtha spirits 	`,`	null	`],
	[`	T52.1	`,`	Benzene Excl.: homologues of benzene (T52.2) nitroderivatives and aminoderivatives of benzene and its homologues (T65.3) 	`,`	null	`],
	[`	T52.2	`,`	Homologues of benzene Toluene [methylbenzene] Xylene [dimethylbenzene] 	`,`	null	`],
	[`	T52.3	`,`	Glycols 	`,`	null	`],
	[`	T52.4	`,`	Ketones 	`,`	null	`],
	[`	T52.8	`,`	Other organic solvents 	`,`	null	`],
	[`	T52.9	`,`	Organic solvent, unspecified 	`,`	null	`],
	[`	T53	`,`	Toxic effect of halogen derivatives of aliphatic and aromatic hydrocarbons 	`,`	null	`],
	[`	T53.0	`,`	Carbon tetrachloride Tetrachloromethane 	`,`	null	`],
	[`	T53.1	`,`	Chloroform Trichloromethane 	`,`	null	`],
	[`	T53.2	`,`	Trichloroethylene Trichloroethene 	`,`	null	`],
	[`	T53.3	`,`	Tetrachloroethylene Perchloroethylene Tetrachloroethene 	`,`	null	`],
	[`	T53.4	`,`	Dichloromethane Methylene chloride 	`,`	null	`],
	[`	T53.5	`,`	Chlorofluorocarbons 	`,`	null	`],
	[`	T53.6	`,`	Other halogen derivatives of aliphatic hydrocarbons 	`,`	null	`],
	[`	T53.7	`,`	Other halogen derivatives of aromatic hydrocarbons 	`,`	null	`],
	[`	T53.9	`,`	Halogen derivative of aliphatic and aromatic hydrocarbons, unspecified 	`,`	null	`],
	[`	T54	`,`	Toxic effect of corrosive substances 	`,`	null	`],
	[`	T54.0	`,`	Phenol and phenol homologues 	`,`	null	`],
	[`	T54.1	`,`	Other corrosive organic compounds 	`,`	null	`],
	[`	T54.2	`,`	Corrosive acids and acid-like substances Acid: hydrochloric sulfuric 	`,`	null	`],
	[`	T54.3	`,`	Corrosive alkalis and alkali-like substances Potassium hydroxide Sodium hydroxide 	`,`	null	`],
	[`	T54.9	`,`	Corrosive substance, unspecified 	`,`	null	`],
	[`	T55	`,`	Toxic effect of soaps and detergents 	`,`	null	`],
	[`	T56	`,`	Toxic effect of metals Incl.: fumes and vapours of metals metals from all sources, except medicinal substances Excl.: arsenic and its compounds (T57.0) manganese and its compounds (T57.2) 	`,`	null	`],
	[`	T56.0	`,`	Lead and its compounds 	`,`	null	`],
	[`	T56.1	`,`	Mercury and its compounds 	`,`	null	`],
	[`	T56.2	`,`	Chromium and its compounds 	`,`	null	`],
	[`	T56.3	`,`	Cadmium and its compounds 	`,`	null	`],
	[`	T56.4	`,`	Copper and its compounds 	`,`	null	`],
	[`	T56.5	`,`	Zinc and its compounds 	`,`	null	`],
	[`	T56.6	`,`	Tin and its compounds 	`,`	null	`],
	[`	T56.7	`,`	Beryllium and its compounds 	`,`	null	`],
	[`	T56.8	`,`	Other metals Thallium 	`,`	null	`],
	[`	T56.9	`,`	Metal, unspecified 	`,`	null	`],
	[`	T57	`,`	Toxic effect of other inorganic substances 	`,`	null	`],
	[`	T57.0	`,`	Arsenic and its compounds 	`,`	null	`],
	[`	T57.1	`,`	Phosphorus and its compounds Excl.: organophosphate insecticides (T60.0) 	`,`	null	`],
	[`	T57.2	`,`	Manganese and its compounds 	`,`	null	`],
	[`	T57.3	`,`	Hydrogen cyanide 	`,`	null	`],
	[`	T57.8	`,`	Other specified inorganic substances 	`,`	null	`],
	[`	T57.9	`,`	Inorganic substance, unspecified 	`,`	null	`],
	[`	T58	`,`	Toxic effect of carbon monoxide Incl.: From all sources 	`,`	null	`],
	[`	T59	`,`	Toxic effect of other gases, fumes and vapours Incl.: aerosol propellants Excl.: chlorofluorocarbons (T53.5) 	`,`	null	`],
	[`	T59.0	`,`	Nitrogen oxides 	`,`	null	`],
	[`	T59.1	`,`	Sulfur dioxide 	`,`	null	`],
	[`	T59.2	`,`	Formaldehyde 	`,`	null	`],
	[`	T59.3	`,`	Lacrimogenic gas Tear gas 	`,`	null	`],
	[`	T59.4	`,`	Chlorine gas 	`,`	null	`],
	[`	T59.5	`,`	Fluorine gas and hydrogen fluoride 	`,`	null	`],
	[`	T59.6	`,`	Hydrogen sulfide 	`,`	null	`],
	[`	T59.7	`,`	Carbon dioxide 	`,`	null	`],
	[`	T59.8	`,`	Other specified gases, fumes and vapours 	`,`	null	`],
	[`	T59.9	`,`	Gases, fumes and vapours, unspecified 	`,`	null	`],
	[`	T60	`,`	Toxic effect of pesticides Incl.: wood preservatives 	`,`	null	`],
	[`	T60.0	`,`	Organophosphate and carbamate insecticides 	`,`	null	`],
	[`	T60.1	`,`	Halogenated insecticides Excl.: chlorinated hydrocarbons (T53.-) 	`,`	null	`],
	[`	T60.2	`,`	Other insecticides 	`,`	null	`],
	[`	T60.3	`,`	Herbicides and fungicides 	`,`	null	`],
	[`	T60.4	`,`	Rodenticides Excl.: strychnine and its salts (T65.1) 	`,`	null	`],
	[`	T60.8	`,`	Other pesticides 	`,`	null	`],
	[`	T60.9	`,`	Pesticide, unspecified 	`,`	null	`],
	[`	T61	`,`	Toxic effect of noxious substances eaten as seafood Excl.: allergic reaction to food, such as: anaphylactic shock due to adverse food reaction (T78.0) dermatitis (L23.6, L25.4, L27.2) gastroenteritis (noninfective) (K52.-) bacterial foodborne intoxications (A05.-) toxic effect of food contaminants, such as: aflatoxin and other mycotoxins (T64) cyanides (T65.0) hydrogen cyanide (T57.3) mercury (T56.1) 	`,`	null	`],
	[`	T61.0	`,`	Ciguatera fish poisoning 	`,`	null	`],
	[`	T61.1	`,`	Scombroid fish poisoning Histamine-like syndrome 	`,`	null	`],
	[`	T61.2	`,`	Other fish and shellfish poisoning 	`,`	null	`],
	[`	T61.8	`,`	Toxic effect of other seafoods 	`,`	null	`],
	[`	T61.9	`,`	Toxic effect of unspecified seafood 	`,`	null	`],
	[`	T62	`,`	Toxic effect of other noxious substances eaten as food Excl.: allergic reaction to food, such as: anaphylactic shock due to adverse food reaction (T78.0) dermatitis (L23.6, L25.4, L27.2) gastroenteritis (noninfective) (K52.-) bacterial foodborne intoxications (A05.-) toxic effect of food contaminants, such as: aflatoxin and other mycotoxins (T64) cyanides (T65.0) hydrogen cyanide (T57.3) mercury (T56.1) 	`,`	null	`],
	[`	T62.0	`,`	Ingested mushrooms 	`,`	null	`],
	[`	T62.1	`,`	Ingested berries 	`,`	null	`],
	[`	T62.2	`,`	Other ingested (parts of) plant(s) 	`,`	null	`],
	[`	T62.8	`,`	Other specified noxious substances eaten as food 	`,`	null	`],
	[`	T62.9	`,`	Noxious substance eaten as food, unspecified 	`,`	null	`],
	[`	T63	`,`	Toxic effect of contact with venomous animals 	`,`	null	`],
	[`	T63.0	`,`	Snake venom Sea-snake venom 	`,`	null	`],
	[`	T63.1	`,`	Venom of other reptiles Lizard venom 	`,`	null	`],
	[`	T63.2	`,`	Venom of scorpion 	`,`	null	`],
	[`	T63.3	`,`	Venom of spider 	`,`	null	`],
	[`	T63.4	`,`	Venom of other arthropods Insect bite or sting, venomous 	`,`	null	`],
	[`	T63.5	`,`	Toxic effect of contact with fish Excl.: poisoning by ingestion of fish (T61.0-T61.2) 	`,`	null	`],
	[`	T63.6	`,`	Toxic effect of contact with other marine animals Jellyfish Sea anemone Shellfish Starfish Excl.: poisoning by ingestion of shellfish (T61.2) sea-snake venom (T63.0) 	`,`	null	`],
	[`	T63.8	`,`	Toxic effect of contact with other venomous animals Venom of amphibian 	`,`	null	`],
	[`	T63.9	`,`	Toxic effect of contact with unspecified venomous animal 	`,`	null	`],
	[`	T64	`,`	Toxic effect of aflatoxin and other mycotoxin food contaminants 	`,`	null	`],
	[`	T65	`,`	Toxic effect of other and unspecified substances 	`,`	null	`],
	[`	T65.0	`,`	Cyanides Excl.: hydrogen cyanide (T57.3) 	`,`	null	`],
	[`	T65.1	`,`	Strychnine and its salts 	`,`	null	`],
	[`	T65.2	`,`	Tobacco and nicotine 	`,`	null	`],
	[`	T65.3	`,`	Nitroderivatives and aminoderivatives of benzene and its homologues Aniline [benzenamine] Nitrobenzene Trinitrotoluene 	`,`	null	`],
	[`	T65.4	`,`	Carbon disulfide 	`,`	null	`],
	[`	T65.5	`,`	Nitroglycerin and other nitric acids and esters 1,2,3-Propanetriol trinitrate 	`,`	null	`],
	[`	T65.6	`,`	Paints and dyes, not elsewhere classified 	`,`	null	`],
	[`	T65.8	`,`	Toxic effect of other specified substances 	`,`	null	`],
	[`	T65.9	`,`	Toxic effect of unspecified substance Poisoning NOS 	`,`	null	`],
	[`	T66	`,`	Unspecified effects of radiation Incl.: Radiation sickness Excl.: specified adverse effects of radiation, such as: burns (T20-T31) leukaemia (C91-C95) radiation: gastroenteritis and colitis (K52.0) pneumonitis (J70.0) related disorders of the skin and subcutaneous tissue (L55-L59) sunburn (L55.-) 	`,`	null	`],
	[`	T67	`,`	Effects of heat and light Excl.: burns (T20-T31) erythema [dermatitis] ab igne (L59.0) malignant hyperthermia due to anaesthesia (T88.3) radiation-related disorders of the skin and subcutaneous tissue (L55-L59) sunburn (L55.-) sweat disorders due to heat (L74-L75) 	`,`	null	`],
	[`	T67.0	`,`	Heatstroke and sunstroke Heat: apoplexy pyrexia Siriasis Thermoplegia 	`,`	null	`],
	[`	T67.1	`,`	Heat syncope Heat collapse 	`,`	null	`],
	[`	T67.2	`,`	Heat cramp 	`,`	null	`],
	[`	T67.3	`,`	Heat exhaustion, anhydrotic Heat prostration due to water depletion Excl.: heat exhaustion due to salt depletion (T67.4) 	`,`	null	`],
	[`	T67.4	`,`	Heat exhaustion due to salt depletion Heat prostration due to salt (and water) depletion 	`,`	null	`],
	[`	T67.5	`,`	Heat exhaustion, unspecified Heat prostration NOS 	`,`	null	`],
	[`	T67.6	`,`	Heat fatigue, transient 	`,`	null	`],
	[`	T67.7	`,`	Heat oedema 	`,`	null	`],
	[`	T67.8	`,`	Other effects of heat and light 	`,`	null	`],
	[`	T67.9	`,`	Effect of heat and light, unspecified 	`,`	null	`],
	[`	T68	`,`	Hypothermia Incl.: Accidental hypothermia Excl.: frostbite (T33-T35) hypothermia (of): following anaesthesia (T88.5) newborn (P80.-) not associated with low environmental temperature (R68.0) 	`,`	null	`],
	[`	T69	`,`	Other effects of reduced temperature Excl.: frostbite (T33-T35) 	`,`	null	`],
	[`	T69.0	`,`	Immersion hand and foot Trench foot 	`,`	null	`],
	[`	T69.1	`,`	Chilblains 	`,`	null	`],
	[`	T69.8	`,`	Other specified effects of reduced temperature 	`,`	null	`],
	[`	T69.9	`,`	Effect of reduced temperature, unspecified 	`,`	null	`],
	[`	T70	`,`	Effects of air pressure and water pressure 	`,`	null	`],
	[`	T70.0	`,`	Otitic barotrauma Aero-otitis media Effects of change in ambient atmospheric pressure or water pressure on ears 	`,`	null	`],
	[`	T70.1	`,`	Sinus barotrauma Aerosinusitis Effects of change in ambient atmospheric pressure on sinuses 	`,`	null	`],
	[`	T70.2	`,`	Other and unspecified effects of high altitude Alpine sickness Anoxia due to high altitude Barotrauma NOS Hypobaropathy Mountain sickness Excl.: polycythaemia due to high altitude (D75.1) 	`,`	null	`],
	[`	T70.3	`,`	Caisson disease [decompression sickness] Compressed-air disease Diver palsy or paralysis 	`,`	null	`],
	[`	T70.4	`,`	Effects of high-pressure fluids Traumatic jet injection (industrial) 	`,`	null	`],
	[`	T70.8	`,`	Other effects of air pressure and water pressure Blast injury syndrome 	`,`	null	`],
	[`	T70.9	`,`	Effect of air pressure and water pressure, unspecified 	`,`	null	`],
	[`	T71	`,`	Asphyxiation Incl.: Suffocation (by strangulation) Systemic oxygen deficiency due to: low oxygen content in ambient air mechanical threat to breathing Excl.: anoxia due to high altitude (T70.2) asphyxia from: carbon monoxide (T58) inhalation of food or foreign body (T17.-) other gases, fumes and vapours (T59.-) respiratory distress: syndrome in adult (J80) in newborn (P22.-) 	`,`	null	`],
	[`	T73	`,`	Effects of other deprivation 	`,`	null	`],
	[`	T73.0	`,`	Effects of hunger Deprivation of food Starvation 	`,`	null	`],
	[`	T73.1	`,`	Effects of thirst Deprivation of water 	`,`	null	`],
	[`	T73.2	`,`	Exhaustion due to exposure 	`,`	null	`],
	[`	T73.3	`,`	Exhaustion due to excessive exertion Overexertion 	`,`	null	`],
	[`	T73.8	`,`	Other effects of deprivation 	`,`	null	`],
	[`	T73.9	`,`	Effect of deprivation, unspecified 	`,`	null	`],
	[`	T74	`,`	Maltreatment syndromes Use additional code, if desired, to identify current injury. 	`,`	null	`],
	[`	T74.0	`,`	Neglect or abandonment 	`,`	null	`],
	[`	T74.1	`,`	Physical abuse Battered: baby or child syndrome NOS spouse syndrome NOS 	`,`	null	`],
	[`	T74.2	`,`	Sexual abuse 	`,`	null	`],
	[`	T74.3	`,`	Psychological abuse 	`,`	null	`],
	[`	T74.8	`,`	Other maltreatment syndromes Mixed forms 	`,`	null	`],
	[`	T74.9	`,`	Maltreatment syndrome, unspecified Effects of: abuse of adult NOS child abuse NOS 	`,`	null	`],
	[`	T75	`,`	Effects of other external causes Excl.: adverse effects NEC (T78.-) burns (electric) (T20-T31) 	`,`	null	`],
	[`	T75.0	`,`	Effects of lightning Shock from lightning Struck by lightning NOS 	`,`	null	`],
	[`	T75.1	`,`	Drowning and nonfatal submersion Immersion Swimmer cramp 	`,`	null	`],
	[`	T75.2	`,`	Effects of vibration Pneumatic hammer syndrome Traumatic vasospastic syndrome Vertigo from infrasound 	`,`	null	`],
	[`	T75.3	`,`	Motion sickness Airsickness Seasickness Travel sickness 	`,`	null	`],
	[`	T75.4	`,`	Effects of electric current Electrocution Shock from electric current 	`,`	null	`],
	[`	T75.8	`,`	Other specified effects of external causes Effects of: abnormal gravitation [G] forces weightlessness 	`,`	null	`],
	[`	T78	`,`	Adverse effects, not elsewhere classified Note: This category is to be used as the primary code to identify the effects, not elsewhere classifiable, of unknown, undetermined or ill-defined causes. For multiple coding purposes this category may be used as an additional code to identify the effects of conditions classified elsewhere. Excl.: complications of surgical and medical care NEC (T80-T88) 	`,`	null	`],
	[`	T78.0	`,`	Anaphylactic shock due to adverse food reaction 	`,`	null	`],
	[`	T78.1	`,`	Other adverse food reactions, not elsewhere classified Excl.: bacterial foodborne intoxications (A05.-) dermatitis due to food (L27.2) dermatitis due to food in contact with the skin (L23.6, L24.6, L25.4) 	`,`	null	`],
	[`	T78.2	`,`	Anaphylactic shock, unspecified Allergic shock Anaphylactic reaction Anaphylaxis NOS Excl.: anaphylactic shock due to: adverse effect of correct medicinal substance properly administered (T88.6) adverse food reaction (T78.0) serum (T80.5) 	`,`	null	`],
	[`	T78.3	`,`	Angioneurotic oedema Giant urticaria Quincke oedema Excl.: urticaria (L50.-) urticaria serum (T80.6) 	`,`	null	`],
	[`	T78.4	`,`	Allergy, unspecified Allergic reaction NOS Hypersensitivity NOS Idiosyncracy NOS Excl.: allergic reaction NOS to correct medicinal substance properly administered (T88.7) specified types of allergic reaction such as: allergic gastroenteritis and colitis (K52.2) dermatitis (L23-L25, L27.-) hay fever (J30.1) 	`,`	null	`],
	[`	T78.8	`,`	Other adverse effects, not elsewhere classified 	`,`	null	`],
	[`	T78.9	`,`	Adverse effect, unspecified Excl.: adverse effect of surgical and medical care NOS (T88.9) 	`,`	null	`],
	[`	T79	`,`	Certain early complications of trauma, not elsewhere classified Excl.: complications of surgical and medical care NEC (T80-T88) respiratory distress: syndrome of adult (J80) in newborn (P22.-) when occurring during or following medical procedures (T80-T88) 	`,`	null	`],
	[`	T79.0	`,`	Air embolism (traumatic) Excl.: air embolism complicating: abortion or ectopic or molar pregnancy (O00-O07, O08.2) pregnancy, childbirth and the puerperium (O88.0) 	`,`	null	`],
	[`	T79.1	`,`	Fat embolism (traumatic) Excl.: fat embolism complicating: abortion or ectopic or molar pregnancy (O00-O07, O08.2) pregnancy, childbirth and the puerperium (O88.8) 	`,`	null	`],
	[`	T79.2	`,`	Traumatic secondary and recurrent haemorrhage 	`,`	null	`],
	[`	T79.3	`,`	Post-traumatic wound infection, not elsewhere classified Use additional code (B95-B98), if desired, to identify infectious agent. 	`,`	null	`],
	[`	T79.4	`,`	Traumatic shock Shock (immediate)(delayed) following injury Excl.: shock: anaesthetic (T88.2) anaphylactic: NOS (T78.2) due to: adverse food reaction (T78.0) correct medicinal substance properly administered (T88.6) serum (T80.5) complicating abortion or ectopic or molar pregnancy (O00-O07, O08.3) electric (T75.4) lightning (T75.0) nontraumatic NEC (R57.-) obstetric (O75.1) postoperative (T81.1) 	`,`	null	`],
	[`	T79.5	`,`	Traumatic anuria Crush syndrome Renal failure following crushing 	`,`	null	`],
	[`	T79.6	`,`	Traumatic ischaemia of muscle Compartment syndrome Volkmann ischaemic contracture Excl.: anterior tibial syndrome (M76.8) 	`,`	null	`],
	[`	T79.7	`,`	Traumatic subcutaneous emphysema Excl.: emphysema (subcutaneous) resulting from a procedure (T81.8) 	`,`	null	`],
	[`	T79.8	`,`	Other early complications of trauma 	`,`	null	`],
	[`	T79.9	`,`	Unspecified early complication of trauma 	`,`	null	`],
	[`	T80	`,`	Complications following infusion, transfusion and therapeutic injection Incl.: perfusion Excl.: bone-marrow transplant rejection (T86.0) 	`,`	null	`],
	[`	T80.0	`,`	Air embolism following infusion, transfusion and therapeutic injection 	`,`	null	`],
	[`	T80.1	`,`	Vascular complications following infusion, transfusion and therapeutic injection Phlebitis Thromboembolism Thrombophlebitis following infusion, transfusion and therapeutic injection Excl.: the listed conditions when specified as: due to prosthetic devices, implants and grafts (T82.8, T83.8, T84.8, T85.8) postprocedural (T81.7) 	`,`	null	`],
	[`	T80.2	`,`	Infections following infusion, transfusion and therapeutic injection Infection Sepsis following infusion, transfusion and therapeutic injection Use additional code (R57.2) , if desired, to identify septic shock Excl.: the listed conditions when specified as: due to prosthetic devices, implants and grafts (T82.6-T82.7, T83.5-T83.6, T84.5-T84.7, T85.7) postprocedural (T81.4) 	`,`	null	`],
	[`	T80.3	`,`	ABO incompatibility reaction Incompatible blood transfusion Reaction to blood-group incompatibility in infusion or transfusion 	`,`	null	`],
	[`	T80.4	`,`	Rh incompatibility reaction Reaction due to Rh factor in infusion or transfusion 	`,`	null	`],
	[`	T80.5	`,`	Anaphylactic shock due to serum Excl.: shock: allergic NOS (T78.2) anaphylactic: NOS (T78.2) due to adverse effect of correct medicinal substance properly administered (T88.6) 	`,`	null	`],
	[`	T80.6	`,`	Other serum reactions Intoxication by serum Protein sickness Serum: rash sickness urticaria Excl.: serum hepatitis (B16.-) 	`,`	null	`],
	[`	T80.8	`,`	Other complications following infusion, transfusion and therapeutic injection 	`,`	null	`],
	[`	T80.9	`,`	Unspecified complication following infusion, transfusion and therapeutic injection Transfusion reaction NOS 	`,`	null	`],
	[`	T81	`,`	Complications of procedures, not elsewhere classified Excl.: adverse effect of drug NOS (T88.7) complication following: immunization (T88.0-T88.1) infusion, transfusion and therapeutic injection (T80.-) specified complications classified elsewhere, such as: complications of prosthetic devices, implants and grafts (T82-T85) dermatitis due to drugs and medicaments (L23.3, L24.4, L25.1, L27.0-L27.1) failure and rejection of transplanted organs and tissues (T86.-) poisoning and toxic effects of drugs and chemicals (T36-T65) 	`,`	null	`],
	[`	T81.0	`,`	Haemorrhage and haematoma complicating a procedure, not elsewhere classified Haemorrhage at any site resulting from a procedure Excl.: haematoma of obstetric wound (O90.2) haemorrhage due to prosthetic devices, implants and grafts (T82.8, T83.8, T84.8, T85.8) 	`,`	null	`],
	[`	T81.1	`,`	Shock during or resulting from a procedure, not elsewhere classified Collapse NOS Shock (endotoxic)(hypovolaemic) during or following a procedure Postoperative shock NOS Use additional code (R57.2) , if desired, to identify septic shock Excl.: shock: anaesthetic (T88.2) anaphylactic: NOS (T78.2) due to: correct medicinal substance properly administered (T88.6) serum (T80.5) electric (T75.4) following abortion or ectopic or molar pregnancy (O00-O07, O08.3) obstetric (O75.1) traumatic (T79.4) 	`,`	null	`],
	[`	T81.2	`,`	Accidental puncture and laceration during a procedure, not elsewhere classified Accidental perforation of: blood vessel nerve organ by catheter endoscope instrument probe during a procedure Excl.: damage from instruments during delivery (O70-O71) perforation, puncture or laceration caused by device or implant intentionally left in operation wound (T82-T85) specified complications classified elsewhere, such as broad ligament laceration syndrome [Allen-Masters] (N83.8) 	`,`	null	`],
	[`	T81.3	`,`	Disruption of operation wound, not elsewhere classified Dehiscence Rupture of operation wound Excl.: disruption of: caesarean-section wound (O90.0) perineal obstetric wound (O90.1) 	`,`	null	`],
	[`	T81.4	`,`	Infection following a procedure, not elsewhere classified Abscess: intra-abdominal stitch subphrenic wound Sepsis postprocedural Use additional code, if desired, to identify other manifestations of infection, such as sepsis or abscess. Excl.: infection due to: infusion, transfusion and therapeutic injection (T80.2) prosthetic devices, implants and grafts (T82.6-T82.7, T83.5-T83.6, T84.5-T84.7, T85.7) obstetric surgical wound infection (O86.0) 	`,`	null	`],
	[`	T81.5	`,`	Foreign body accidentally left in body cavity or operation wound following a procedure Adhesions Obstruction Perforation due to foreign body accidentally left in operation wound or body cavity Excl.: obstruction or perforation due to prosthetic devices and implants intentionally left in body (T82.0-T82.5, T83.0-T83.4, T84.0-T84.4, T85.0-T85.6) 	`,`	null	`],
	[`	T81.6	`,`	Acute reaction to foreign substance accidentally left during a procedure Peritonitis: aseptic chemical 	`,`	null	`],
	[`	T81.7	`,`	Vascular complications following a procedure, not elsewhere classified Air embolism following procedure NEC Excl.: embolism: complicating: abortion or ectopic or molar pregnancy (O00-O07, O08.2) pregnancy, childbirth and the puerperium (O88.-) due to prosthetic devices, implants and grafts (T82.8, T83.8, T84.8, T85.8) following infusion, transfusion and therapeutic injection (T80.0) traumatic (T79.0) 	`,`	null	`],
	[`	T81.8	`,`	Other complications of procedures, not elsewhere classified Complication of inhalation therapy Emphysema (subcutaneous) resulting from a procedure Persistent postoperative fistula Excl.: hypothermia following anaesthesia (T88.5) malignant hyperthermia due to anaesthesia (T88.3) 	`,`	null	`],
	[`	T81.9	`,`	Unspecified complication of procedure 	`,`	null	`],
	[`	T82	`,`	Complications of cardiac and vascular prosthetic devices, implants and grafts Excl.: failure and rejection of transplanted organs and tissues (T86.-) 	`,`	null	`],
	[`	T82.0	`,`	Mechanical complication of heart valve prosthesis Breakdown (mechanical) Displacement Leakage Malposition Obstruction, mechanical Perforation Protrusion due to heart valve prosthesis 	`,`	null	`],
	[`	T82.1	`,`	Mechanical complication of cardiac electronic device Conditions listed in T82.0 due to: electrodes pulse generator (battery) 	`,`	null	`],
	[`	T82.2	`,`	Mechanical complication of coronary artery bypass and valve grafts Conditions listed in T82.0 due to coronary artery bypass and valve grafts 	`,`	null	`],
	[`	T82.3	`,`	Mechanical complication of other vascular grafts Conditions listed in T82.0 due to: aortic (bifurcation) graft (replacement) arterial (carotid) (femoral) graft (bypass) 	`,`	null	`],
	[`	T82.4	`,`	Mechanical complication of vascular dialysis catheter Conditions listed in T82.0 due to vascular dialysis catheter Excl.: mechanical complication of intraperitoneal dialysis catheter (T85.6) 	`,`	null	`],
	[`	T82.5	`,`	Mechanical complication of other cardiac and vascular devices and implants Conditions listed in T82.0 due to: arteriovenous: fistula, surgically created shunt, surgically created artificial heart balloon (counterpulsation) device infusion catheter umbrella device Excl.: mechanical complication of epidural and subdural infusion catheter (T85.6) 	`,`	null	`],
	[`	T82.6	`,`	Infection and inflammatory reaction due to cardiac valve prosthesis 	`,`	null	`],
	[`	T82.7	`,`	Infection and inflammatory reaction due to other cardiac and vascular devices, implants and grafts 	`,`	null	`],
	[`	T82.8	`,`	Other specified complications of cardiac and vascular prosthetic devices, implants and grafts Embolism Fibrosis Haemorrhage Pain Stenosis Thrombosis due to cardiac and vascular prosthetic devices, implants and grafts 	`,`	null	`],
	[`	T82.9	`,`	Unspecified complication of cardiac and vascular prosthetic device, implant and graft 	`,`	null	`],
	[`	T83	`,`	Complications of genitourinary prosthetic devices, implants and grafts Excl.: failure and rejection of transplanted organs and tissues (T86.-) 	`,`	null	`],
	[`	T83.0	`,`	Mechanical complication of urinary (indwelling) catheter Conditions listed in T82.0 due to: catheter: cystostomy urethral, indwelling 	`,`	null	`],
	[`	T83.1	`,`	Mechanical complication of other urinary devices and implants Conditions listed in T82.0 due to: urinary: electronic stimulator device sphincter implant stent 	`,`	null	`],
	[`	T83.2	`,`	Mechanical complication of graft of urinary organ Conditions listed in T82.0 due to graft of urinary organ 	`,`	null	`],
	[`	T83.3	`,`	Mechanical complication of intrauterine contraceptive device Conditions listed in T82.0 due to intrauterine contraceptive device 	`,`	null	`],
	[`	T83.4	`,`	Mechanical complication of other prosthetic devices, implants and grafts in genital tract Conditions listed in T82.0 due to (implanted) penile prosthesis 	`,`	null	`],
	[`	T83.5	`,`	Infection and inflammatory reaction due to prosthetic device, implant and graft in urinary system 	`,`	null	`],
	[`	T83.6	`,`	Infection and inflammatory reaction due to prosthetic device, implant and graft in genital tract 	`,`	null	`],
	[`	T83.8	`,`	Other complications of genitourinary prosthetic devices, implants and grafts Conditions listed in T82.8 due to genitourinary prosthetic devices, implants and grafts 	`,`	null	`],
	[`	T83.9	`,`	Unspecified complication of genitourinary prosthetic device, implant and graft 	`,`	null	`],
	[`	T84	`,`	Complications of internal orthopaedic prosthetic devices, implants and grafts Excl.: failure and rejection of transplanted organs and tissues (T86.-) fracture of bone following insertion of orthopaedic implant, joint prosthesis or bone plate (M96.6) 	`,`	null	`],
	[`	T84.0	`,`	Mechanical complication of internal joint prosthesis Conditions listed in T82.0 due to joint prosthesis 	`,`	null	`],
	[`	T84.1	`,`	Mechanical complication of internal fixation device of bones of limb Conditions listed in T82.0 due to internal fixation device of bones of limb 	`,`	null	`],
	[`	T84.2	`,`	Mechanical complication of internal fixation device of other bones Conditions listed in T82.0 due to internal fixation device of other bones 	`,`	null	`],
	[`	T84.3	`,`	Mechanical complication of other bone devices, implants and grafts Conditions listed in T82.0 due to: bone graft electronic bone stimulator 	`,`	null	`],
	[`	T84.4	`,`	Mechanical complication of other internal orthopaedic devices, implants and grafts Conditions listed in T82.0 due to muscle and tendon graft 	`,`	null	`],
	[`	T84.5	`,`	Infection and inflammatory reaction due to internal joint prosthesis 	`,`	null	`],
	[`	T84.6	`,`	Infection and inflammatory reaction due to internal fixation device [any site] 	`,`	null	`],
	[`	T84.7	`,`	Infection and inflammatory reaction due to other internal orthopaedic prosthetic devices, implants and grafts 	`,`	null	`],
	[`	T84.8	`,`	Other complications of internal orthopaedic prosthetic devices, implants and grafts Conditions listed in T82.8 due to internal orthopaedic prosthetic devices, implants and grafts 	`,`	null	`],
	[`	T84.9	`,`	Unspecified complication of internal orthopaedic prosthetic device, implant and graft 	`,`	null	`],
	[`	T85	`,`	Complications of other internal prosthetic devices, implants and grafts Excl.: failure and rejection of transplanted organs and tissues (T86.-) 	`,`	null	`],
	[`	T85.0	`,`	Mechanical complication of ventricular intracranial (communicating) shunt Conditions listed in T82.0 due to ventricular intracranial (communicating) shunt 	`,`	null	`],
	[`	T85.1	`,`	Mechanical complication of implanted electronic stimulator of nervous system Conditions listed in T82.0 due to electronic neurostimulator (electrode) of: brain peripheral nerve spinal cord 	`,`	null	`],
	[`	T85.2	`,`	Mechanical complication of intraocular lens Conditions listed in T82.0 due to intraocular lens 	`,`	null	`],
	[`	T85.3	`,`	Mechanical complication of other ocular prosthetic devices, implants and grafts Conditions listed in T82.0 due to: corneal graft prosthetic orbit of eye 	`,`	null	`],
	[`	T85.4	`,`	Mechanical complication of breast prosthesis and implant Conditions listed in T82.0 due to breast prosthesis and implant 	`,`	null	`],
	[`	T85.5	`,`	Mechanical complication of gastrointestinal prosthetic devices, implants and grafts Conditions listed in T82.0 due to: bile-duct prosthesis oesophageal anti-reflux device 	`,`	null	`],
	[`	T85.6	`,`	Mechanical complication of other specified internal prosthetic devices, implants and grafts Conditions listed in T82.0 due to: epidural and subdural infusion catheter intraperitoneal dialysis catheter nonabsorbable surgical material NOS permanent sutures Excl.: mechanical complication of permanent (wire) suture used in bone repair (T84.1-T84.2) 	`,`	null	`],
	[`	T85.7	`,`	Infection and inflammatory reaction due to other internal prosthetic devices, implants and grafts 	`,`	null	`],
	[`	T85.8	`,`	Other complications of internal prosthetic devices, implants and grafts, not elsewhere classified Conditions listed in T82.8 due to internal prosthetic devices, implants and grafts NEC 	`,`	null	`],
	[`	T85.9	`,`	Unspecified complication of internal prosthetic device, implant and graft Complication of internal prosthetic device, implant and graft NOS 	`,`	null	`],
	[`	T86	`,`	Failure and rejection of transplanted organs and tissues 	`,`	null	`],
	[`	T86.0	`,`	Bone-marrow transplant rejection Graft-versus-host reaction or disease 	`,`	null	`],
	[`	T86.1	`,`	Kidney transplant failure and rejection 	`,`	null	`],
	[`	T86.2	`,`	Heart transplant failure and rejection Excl.: complication of: artificial heart device (T82.5) heart-lung transplant (T86.3) 	`,`	null	`],
	[`	T86.3	`,`	Heart-lung transplant failure and rejection 	`,`	null	`],
	[`	T86.4	`,`	Liver transplant failure and rejection 	`,`	null	`],
	[`	T86.8	`,`	Failure and rejection of other transplanted organs and tissues Transplant failure or rejection of: bone intestine lung pancreas skin (allograft) (autograft) 	`,`	null	`],
	[`	T86.9	`,`	Failure and rejection of unspecified transplanted organ and tissue 	`,`	null	`],
	[`	T87	`,`	Complications peculiar to reattachment and amputation 	`,`	null	`],
	[`	T87.0	`,`	Complications of reattached (part of) upper extremity 	`,`	null	`],
	[`	T87.1	`,`	Complications of reattached (part of) lower extremity 	`,`	null	`],
	[`	T87.2	`,`	Complications of other reattached body part 	`,`	null	`],
	[`	T87.3	`,`	Neuroma of amputation stump 	`,`	null	`],
	[`	T87.4	`,`	Infection of amputation stump 	`,`	null	`],
	[`	T87.5	`,`	Necrosis of amputation stump 	`,`	null	`],
	[`	T87.6	`,`	Other and unspecified complications of amputation stump Amputation stump: contracture (flexion)(of next proximal joint) haematoma oedema Excl.: phantom limb syndrome (G54.6-G54.7) 	`,`	null	`],
	[`	T88	`,`	Other complications of surgical and medical care, not elsewhere classified Excl.: accidental puncture or laceration during a procedure (T81.2) complications following: infusion, transfusion and therapeutic injection (T80.-) procedure NEC (T81.-) specified complications classified elsewhere, such as: complications of: anaesthesia in: labour and delivery (O74.-) pregnancy (O29.-) puerperium (O89.-) devices, implants and grafts (T82-T85) obstetric surgery and procedures (O75.4) dermatitis due to drugs and medicaments (L23.3, L24.4, L25.1, L27.0-L27.1) poisoning and toxic effects of drugs and chemicals (T36-T65) 	`,`	null	`],
	[`	T88.0	`,`	Infection following immunization Sepsis following immunization 	`,`	null	`],
	[`	T88.1	`,`	Other complications following immunization, not elsewhere classified Rash following immunization Excl.: anaphylactic shock due to serum (T80.5) other serum reactions (T80.6) postimmunization: arthropathy (M02.2) encephalitis (G04.0) 	`,`	null	`],
	[`	T88.2	`,`	Shock due to anaesthesia Shock due to anaesthesia in which the correct substance was properly administered Excl.: complications of anaesthesia (in): from overdose or wrong substance given (T36-T50) labour and delivery (O74.-) pregnancy (O29.-) puerperium (O89.-) postoperative shock NOS (T81.1) 	`,`	null	`],
	[`	T88.3	`,`	Malignant hyperthermia due to anaesthesia 	`,`	null	`],
	[`	T88.4	`,`	Failed or difficult intubation 	`,`	null	`],
	[`	T88.5	`,`	Other complications of anaesthesia Hypothermia following anaesthesia 	`,`	null	`],
	[`	T88.6	`,`	Anaphylactic shock due to adverse effect of correct drug or medicament properly administered Excl.: anaphylactic shock due to serum (T80.5) 	`,`	null	`],
	[`	T88.7	`,`	Unspecified adverse effect of drug or medicament Adverse effect of Allergic reaction to Hypersensitivity to Idiosyncracy to correct drug or medicament properly administered Drug: hypersensitivity NOS reaction NOS Excl.: specified adverse effects of drugs and medicaments (A00-R99, T80-T88.6, T88.8) 	`,`	null	`],
	[`	T88.8	`,`	Other specified complications of surgical and medical care, not elsewhere classified 	`,`	null	`],
	[`	T88.9	`,`	Complication of surgical and medical care, unspecified Excl.: adverse effect NOS (T78.9) 	`,`	null	`],
	[`	T90	`,`	Sequelae of injuries of head 	`,`	null	`],
	[`	T90.0	`,`	Sequelae of superficial injury of head Sequelae of injury classified to S00.- 	`,`	null	`],
	[`	T90.1	`,`	Sequelae of open wound of head Sequelae of injury classifiable to S01.- 	`,`	null	`],
	[`	T90.2	`,`	Sequelae of fracture of skull and facial bones Sequelae of injury classifiable to S02.- 	`,`	null	`],
	[`	T90.3	`,`	Sequelae of injury of cranial nerves Sequelae of injury classifiable to S04.- 	`,`	null	`],
	[`	T90.4	`,`	Sequelae of injury of eye and orbit Sequelae of injury classifiable to S05.- 	`,`	null	`],
	[`	T90.5	`,`	Sequelae of intracranial injury Sequelae of injury classifiable to S06.- 	`,`	null	`],
	[`	T90.8	`,`	Sequelae of other specified injuries of head Sequelae of injury classifiable to S03.-, S07-S08 and S09.0-S09.8 	`,`	null	`],
	[`	T90.9	`,`	Sequelae of unspecified injury of head Sequelae of injury classifiable to S09.9 	`,`	null	`],
	[`	T91	`,`	Sequelae of injuries of neck and trunk 	`,`	null	`],
	[`	T91.0	`,`	Sequelae of superficial injury and open wound of neck and trunk Sequelae of injury classifiable to S10-S11, S20-S21, S30-S31 and T09.0-T09.1 	`,`	null	`],
	[`	T91.1	`,`	Sequelae of fracture of spine Sequelae of injury classifiable to S12.-, S22.0-S22.1, S32.0, S32.7 and T08 	`,`	null	`],
	[`	T91.2	`,`	Sequelae of other fracture of thorax and pelvis Sequelae of injury classifiable to S22.2-S22.9, S32.1-S32.5 and S32.8 	`,`	null	`],
	[`	T91.3	`,`	Sequelae of injury of spinal cord Sequelae of injury classifiable to S14.0-S14.1, S24.0-S24.1, S34.0-S34.1 and T09.3 	`,`	null	`],
	[`	T91.4	`,`	Sequelae of injury of intrathoracic organs Sequelae of injury classifiable to S26-S27 	`,`	null	`],
	[`	T91.5	`,`	Sequelae of injury of intra-abdominal and pelvic organs Sequelae of injury classifiable to S36-S37 	`,`	null	`],
	[`	T91.8	`,`	Sequelae of other specified injuries of neck and trunk Sequelae of injury classifiable to S13.-, S14.2-S14.6, S15-S18, S19.7-S19.8, S23.-, S24.2-S24.6, S25.-, S28.-, S29.0-S29.8, S33.-, S34.2-S34.8, S35.-, S38.-, S39.0-S39.8, T09.2 and T09.4 -T09.8 	`,`	null	`],
	[`	T91.9	`,`	Sequelae of unspecified injury of neck and trunk Sequelae of injury classifiable to S19.9, S29.9, S39.9 and T09.9 	`,`	null	`],
	[`	T92	`,`	Sequelae of injuries of upper limb 	`,`	null	`],
	[`	T92.0	`,`	Sequelae of open wound of upper limb Sequelae of injury classifiable to S41.-, S51.-, S61.- and T11.1 	`,`	null	`],
	[`	T92.1	`,`	Sequelae of fracture of arm Sequelae of injury classifiable to S42.-, S52.- and T10 	`,`	null	`],
	[`	T92.2	`,`	Sequelae of fracture at wrist and hand level Sequelae of injury classifiable to S62.- 	`,`	null	`],
	[`	T92.3	`,`	Sequelae of dislocation, sprain and strain of upper limb Sequelae of injury classifiable to S43.-, S53.-, S63.- and T11.2 	`,`	null	`],
	[`	T92.4	`,`	Sequelae of injury of nerve of upper limb Sequelae of injury classifiable to S44.-, S54.-, S64.- and T11.3 	`,`	null	`],
	[`	T92.5	`,`	Sequelae of injury of muscle and tendon of upper limb Sequelae of injury classifiable to S46.-, S56.-, S66.- and T11.5 	`,`	null	`],
	[`	T92.6	`,`	Sequelae of crushing injury and traumatic amputation of upper limb Sequelae of injury classifiable to S47-S48, S57-S58, S67-S68 and T11.6 	`,`	null	`],
	[`	T92.8	`,`	Sequelae of other specified injuries of upper limb Sequelae of injury classifiable to S40.-, S45.-, S49.7-S49.8, S50.-,S55.-, S59.7-S59.8, S60.-, S65.-, S69.7-S69.8, T11.0, T11.4 and T11.8 	`,`	null	`],
	[`	T92.9	`,`	Sequelae of unspecified injury of upper limb Sequelae of injury classifiable to S49.9, S59.9, S69.9 and T11.9 	`,`	null	`],
	[`	T93	`,`	Sequelae of injuries of lower limb 	`,`	null	`],
	[`	T93.0	`,`	Sequelae of open wound of lower limb Sequelae of injury classifiable to S71.-, S81.-, S91.- and T13.1 	`,`	null	`],
	[`	T93.1	`,`	Sequelae of fracture of femur Sequelae of injury classifiable to S72.- 	`,`	null	`],
	[`	T93.2	`,`	Sequelae of other fractures of lower limb Sequelae of injury classifiable to S82.-, S92.- and T12 	`,`	null	`],
	[`	T93.3	`,`	Sequelae of dislocation, sprain and strain of lower limb Sequelae of injury classifiable to S73.-, S83.-, S93.- and T13.2 	`,`	null	`],
	[`	T93.4	`,`	Sequelae of injury of nerve of lower limb Sequelae of injury classifiable to S74.-, S84.-, S94.- and T13.3 	`,`	null	`],
	[`	T93.5	`,`	Sequelae of injury of muscle and tendon of lower limb Sequelae of injury classifiable to S76.-, S86.-, S96.- and T13.5 	`,`	null	`],
	[`	T93.6	`,`	Sequelae of crushing injury and traumatic amputation of lower limb Sequelae of injury classifiable to S77-S78, S87-S88, S97-S98 and T13.6 	`,`	null	`],
	[`	T93.8	`,`	Sequelae of other specified injuries of lower limb Sequelae of injury classifiable to S70.-, S75.-, S79.7-S79.8, S80.-, S85.-, S89.7-S89.8, S90.-, S95.-, S99.7-S99.8, T13.0, T13.4 and T13.8 	`,`	null	`],
	[`	T93.9	`,`	Sequelae of unspecified injury of lower limb Sequelae of injury classifiable to S79.9, S89.9, S99.9 and T13.9 	`,`	null	`],
	[`	T94	`,`	Sequelae of injuries involving multiple and unspecified body regions T94.0 Sequelae of injuries involving multiple body regions Sequelae of injury classifiable to T00-T07 	`,`	null	`],
	[`	T94.1	`,`	Sequelae of injuries, not specified by body region Sequelae of injury classifiable to T14.- 	`,`	null	`],
	[`	T95	`,`	Sequelae of burns, corrosions and frostbite 	`,`	null	`],
	[`	T95.0	`,`	Sequelae of burn, corrosion and frostbite of head and neck Sequelae of injury classifiable to T20.-, T33.0-T33.1, T34.0-T34.1 and T35.2 	`,`	null	`],
	[`	T95.1	`,`	Sequelae of burn, corrosion and frostbite of trunk Sequelae of injury classifiable to T21.-, T33.2-T33.3, T34.2-T34.3 and T35.3 	`,`	null	`],
	[`	T95.2	`,`	Sequelae of burn, corrosion and frostbite of upper limb Sequelae of injury classifiable to T22-T23, T33.4-T33.5, T34.4-T34.5 and T35.4 	`,`	null	`],
	[`	T95.3	`,`	Sequelae of burn, corrosion and frostbite of lower limb Sequelae of injury classifiable to T24-T25, T33.6-T33.8, T34.6-T34.8 and T35.5 	`,`	null	`],
	[`	T95.4	`,`	Sequelae of burn and corrosion classifiable only according to extent of body surface involved Sequelae of injury classifiable to T31-T32 	`,`	null	`],
	[`	T95.8	`,`	Sequelae of other specified burn, corrosion and frostbite Sequelae of injury classifiable T26-T29, T35.0-T35.1 and T35.6 	`,`	null	`],
	[`	T95.9	`,`	Sequelae of unspecified burn, corrosion and frostbite Sequelae of injury classifiable to T30.-, T33.9, T34.9 and T35.7 	`,`	null	`],
	[`	T96	`,`	Sequelae of poisoning by drugs, medicaments and biological substances Incl.: Sequelae of poisoning classifiable to T36-T50 	`,`	null	`],
	[`	T97	`,`	Sequelae of toxic effects of substances chiefly nonmedicinal as to source Incl.: Sequelae of toxic effects classifiable to T51-T65 	`,`	null	`],
	[`	T98	`,`	Sequelae of other and unspecified effects of external causes 	`,`	null	`],
	[`	T98.0	`,`	Sequelae of effects of foreign body entering through natural orifice Sequelae of effects classifiable to T15-T19 	`,`	null	`],
	[`	T98.1	`,`	Sequelae of other and unspecified effects of external causes Sequelae of effects classifiable to T66-T78 	`,`	null	`],
	[`	T98.2	`,`	Sequelae of certain early complications of trauma Sequelae of complications classifiable to T79.- 	`,`	null	`],
	[`	T98.3	`,`	Sequelae of complications of surgical and medical care, not elsewhere classified Sequelae of complications classifiable to T80-T88 	`,`	null	`],
							
							
];							
							
							
					
							
							
				
	
let CodeRangeT ={
	f0:function(val1=(-1),val2=(0)){
		let Range1 = TCodes.slice(val1,val2);
		Range1.reverse();
		document.documentElement.innerHTML += `<br>Showing T Codes ${Range1.length} items(s)`;

		for(value1 in Range1){
			    document.documentElement.style.cssText += "background-color:tan;";
				document.getElementById('tcodesTR').outerHTML += `<tr><td style="background-color:navy;color:white;width:5%;padding:40px;border:2px solid white;font-weight:900;font-size:40px;text-align:center;">${Range1[value1][0]}</td><td style="background-color:black;color:white;width:90%;padding:20px;border:2px solid white;font-size:30px;">${Range1[value1][1]}</td><td style="background-color:navy;color:white;width:5%;padding:20px;border:2px solid white;font-weight:900;font-size:40px;text-align:center;">${Range1[value1][2]}</td></tr>`;			
		}

	},

};

	






	






