let YCodes = [							
	[`	ID	`,`	SYMPTOMS / PROBLEMS / ISSUES	`,`	SYSTEM	`],
	[`	Y00	`,`	Assault by blunt object 	`,`	null	`],
	[`	Y01	`,`	Assault by pushing from high place 	`,`	null	`],
	[`	Y02	`,`	Assault by pushing or placing victim before moving object 	`,`	null	`],
	[`	Y03	`,`	Assault by crashing of motor vehicle Incl.: deliberately hitting or running over with motor vehicle 	`,`	null	`],
	[`	Y04	`,`	Assault by bodily force Incl.: unarmed brawl or fight Excl.: assault by: strangulation (X91) submersion (X92) use of weapon (X93-X95, X99, Y00) sexual assault by bodily force (Y05) 	`,`	null	`],
	[`	Y05	`,`	Sexual assault by bodily force Incl.: rape (attempted) sodomy (attempted) 	`,`	null	`],
	[`	Y06	`,`	Neglect and abandonment 	`,`	null	`],
	[`	Y06.0	`,`	By spouse or partner 	`,`	null	`],
	[`	Y06.1	`,`	By parent 	`,`	null	`],
	[`	Y06.2	`,`	By acquaintance or friend 	`,`	null	`],
	[`	Y06.8	`,`	By other specified persons 	`,`	null	`],
	[`	Y06.9	`,`	By unspecified person 	`,`	null	`],
	[`	Y07	`,`	Other maltreatment Incl.: mental cruelty physical abuse sexual abuse torture Excl.: neglect and abandonment (Y06.-) sexual assault by bodily force (Y05) 	`,`	null	`],
	[`	Y07.0	`,`	By spouse or partner 	`,`	null	`],
	[`	Y07.1	`,`	By parent 	`,`	null	`],
	[`	Y07.2	`,`	By acquaintance or friend 	`,`	null	`],
	[`	Y07.3	`,`	By official authorities 	`,`	null	`],
	[`	Y07.8	`,`	By other specified persons 	`,`	null	`],
	[`	Y07.9	`,`	By unspecified person 	`,`	null	`],
	[`	Y08	`,`	Assault by other specified means 	`,`	null	`],
	[`	Y09	`,`	Assault by unspecified means Incl.: assassination (attempt) NOS homicide (attempt) NOS manslaughter (nonaccidental) murder (attempt) NOS 	`,`	null	`],
	[`	Y10	`,`	Poisoning by and exposure to nonopioid analgesics, antipyretics and antirheumatics, undetermined intent Incl.: 4-aminophenol derivatives nonsteroidal anti-inflammatory drugs [NSAID] pyrazolone derivatives salicylates 	`,`	null	`],
	[`	Y11	`,`	Poisoning by and exposure to antiepileptic, sedative-hypnotic, antiparkinsonism and psychotropic drugs, not elsewhere classified, undetermined intent Incl.: antidepressants barbiturates hydantoin derivatives iminostilbenes methaqualone compounds neuroleptics psychostimulants succinimides and oxazolidinediones tranquillizers 	`,`	null	`],
	[`	Y12	`,`	Poisoning by and exposure to narcotics and psychodysleptics [hallucinogens], not elsewhere classified, undetermined intent Incl.: cannabis (derivatives) cocaine codeine heroin lysergide [LSD] mescaline methadone morphine opium (alkaloids) 	`,`	null	`],
	[`	Y13	`,`	Poisoning by and exposure to other drugs acting on the autonomic nervous system, undetermined intent Incl.: parasympatholytics [anticholinergics and antimuscarinics] and spasmolytics parasympathomimetics [cholinergics] sympatholytics [antiadrenergics] sympathomimetics [adrenergics] 	`,`	null	`],
	[`	Y14	`,`	Poisoning by and exposure to other and unspecified drugs, medicaments and biological substances, undetermined intent Incl.: agents primarily acting on smooth and skeletal muscles and the respiratory system anaesthetics (general)(local) drugs affecting the: cardiovascular system gastrointestinal system hormones and synthetic substitutes systemic and haematological agents systemic antibiotics and other anti-infectives therapeutic gases topical preparations vaccines water-balance agents and drugs affecting mineral and uric acid metabolism 	`,`	null	`],
	[`	Y15	`,`	Poisoning by and exposure to alcohol, undetermined intent Incl.: alcohol: NOS butyl [1-butanol] ethyl [ethanol] isopropyl [2-propanol] methyl [methanol] propyl [1-propanol] fusel oil 	`,`	null	`],
	[`	Y16	`,`	Poisoning by and exposure to organic solvents and halogenated hydrocarbons and their vapours, undetermined intent Incl.: benzene and homologues carbon tetrachloride [tetrachloromethane] chlorofluorocarbons petroleum (derivatives) 	`,`	null	`],
	[`	Y17	`,`	Poisoning by and exposure to other gases and vapours, undetermined intent Incl.: carbon monoxide helium (nonmedicinal) NEC lacrimogenic gas [tear gas] motor (vehicle) exhaust gas nitrogen oxides sulfur dioxide utility gas Excl.: metal fumes and vapours (Y19) 	`,`	null	`],
	[`	Y18	`,`	Poisoning by and exposure to pesticides, undetermined intent Incl.: fumigants fungicides herbicides insecticides rodenticides wood preservatives Excl.: plant foods and fertilizers (Y19) 	`,`	null	`],
	[`	Y19	`,`	Poisoning by and exposure to other and unspecified chemicals and noxious substances, undetermined intent Incl.: corrosive aromatics, acids and caustic alkalis glues and adhesives metals including fumes and vapours paints and dyes plant foods and fertilizers poisonous foodstuffs and poisonous plants soaps and detergents 	`,`	null	`],
	[`	Y20	`,`	Hanging, strangulation and suffocation, undetermined intent 	`,`	null	`],
	[`	Y21	`,`	Drowning and submersion, undetermined intent 	`,`	null	`],
	[`	Y22	`,`	Handgun discharge, undetermined intent 	`,`	null	`],
	[`	Y23	`,`	Rifle, shotgun and larger firearm discharge, undetermined intent 	`,`	null	`],
	[`	Y24	`,`	Other and unspecified firearm discharge, undetermined intent 	`,`	null	`],
	[`	Y25	`,`	Contact with explosive material, undetermined intent 	`,`	null	`],
	[`	Y26	`,`	Exposure to smoke, fire and flames, undetermined intent 	`,`	null	`],
	[`	Y27	`,`	Contact with steam, hot vapours and hot objects, undetermined intent 	`,`	null	`],
	[`	Y28	`,`	Contact with sharp object, undetermined intent 	`,`	null	`],
	[`	Y29	`,`	Contact with blunt object, undetermined intent 	`,`	null	`],
	[`	Y30	`,`	Falling, jumping or pushed from a high place, undetermined intent Incl.: victim falling from one level to another, undetermined intent 	`,`	null	`],
	[`	Y31	`,`	Falling, lying or running before or into moving object, undetermined intent 	`,`	null	`],
	[`	Y32	`,`	Crashing of motor vehicle, undetermined intent 	`,`	null	`],
	[`	Y33	`,`	Other specified events, undetermined intent 	`,`	null	`],
	[`	Y34	`,`	Unspecified event, undetermined intent 	`,`	null	`],
	[`	Y35	`,`	Legal intervention Incl.: injuries inflicted by the police or other law-enforcing agents, including military on duty, in the course of arresting or attempting to arrest lawbreakers, suppressing disturbances, maintaining order, and other legal action 	`,`	null	`],
	[`	Y35.0	`,`	Legal intervention involving firearm discharge Legal intervention with: machine gun revolver rifle pellet or rubber bullet 	`,`	null	`],
	[`	Y35.1	`,`	Legal intervention involving explosives Legal intervention with: dynamite explosive shell grenade mortar bomb 	`,`	null	`],
	[`	Y35.2	`,`	Legal intervention involving gas Asphyxiation by gas Injury by tear gas Poisoning by gas due to legal intervention 	`,`	null	`],
	[`	Y35.3	`,`	Legal intervention involving blunt objects Hit, struck by: baton blunt object stave during legal intervention 	`,`	null	`],
	[`	Y35.4	`,`	Legal intervention involving sharp objects Cut Injured by bayonet Stabbed during legal intervention 	`,`	null	`],
	[`	Y35.5	`,`	Legal execution Any execution performed at the behest of the judiciary or ruling authority [whether permanent or temporary], such as: asphyxiation by gas beheading, decapitation (by guillotine) capital punishment electrocution hanging poisoning shooting 	`,`	null	`],
	[`	Y35.6	`,`	Legal intervention involving other specified means Manhandling 	`,`	null	`],
	[`	Y35.7	`,`	Legal intervention, means unspecified 	`,`	null	`],
	[`	Y36	`,`	Operations of war Note: Injuries due to operations of war occurring after cessation of hostilities are classified to Y36.8. Incl.: injuries to military personnel and civilians caused by war and civil insurrection 	`,`	null	`],
	[`	Y36.0	`,`	War operations involving explosion of marine weapons Depth-charge Marine mine Mine NOS, at sea or in harbour Sea-based artillery shell Torpedo Underwater blast 	`,`	null	`],
	[`	Y36.1	`,`	War operations involving destruction of aircraft Aircraft: burned exploded shot down Crushed by falling aircraft 	`,`	null	`],
	[`	Y36.2	`,`	War operations involving other explosions and fragments Accidental explosion of: munitions being used in war own weapons Antipersonnel bomb (fragments) Explosion (of): artillery shell breech-block cannon block mortar bomb Fragments from: artillery shell bomb grenade guided missile land-mine rocket shell shrapnel Mine NOS during war operations 	`,`	null	`],
	[`	Y36.3	`,`	War operations involving fires, conflagrations and hot substances Asphyxia Burns Other injury originating from fire caused directly by a fire-producing device or indirectly by any conventional weapon Petrol bomb 	`,`	null	`],
	[`	Y36.4	`,`	War operations involving firearm discharge and other forms of conventional warfare Battle wounds Bayonet injury Bullet: carbine machine gun pistol rifle rubber (rifle) Drowned in war operations NOS Pellets (shotgun) 	`,`	null	`],
	[`	Y36.5	`,`	War operations involving nuclear weapons Blast effects Exposure to ionizing radiation from nuclear weapon Fireball effects Heat Other direct and secondary effects of nuclear weapons 	`,`	null	`],
	[`	Y36.6	`,`	War operations involving biological weapons 	`,`	null	`],
	[`	Y36.7	`,`	War operations involving chemical weapons and other forms of unconventional warfare Gases, fumes and chemicals Lasers 	`,`	null	`],
	[`	Y36.8	`,`	War operations occurring after cessation of hostilities Injuries by explosion of bombs or mines placed in the course of operations of war, if the explosion occurred after cessation of hostilities Injuries due to operations of war and classifiable to Y36.0-Y36.7 or Y36.9 but occurring after cessation of hostilities 	`,`	null	`],
	[`	Y36.9	`,`	War operations, unspecified 	`,`	null	`],
	[`	Y40	`,`	Systemic antibiotics Excl.: antibiotics, topically used (Y56.-) antineoplastic antibiotics (Y43.3) 	`,`	null	`],
	[`	Y40.0	`,`	Penicillins 	`,`	null	`],
	[`	Y40.1	`,`	Cefalosporins and other beta-lactam antibiotics 	`,`	null	`],
	[`	Y40.2	`,`	Chloramphenicol group 	`,`	null	`],
	[`	Y40.3	`,`	Macrolides 	`,`	null	`],
	[`	Y40.4	`,`	Tetracyclines 	`,`	null	`],
	[`	Y40.5	`,`	Aminoglycosides Streptomycin 	`,`	null	`],
	[`	Y40.6	`,`	Rifamycins 	`,`	null	`],
	[`	Y40.7	`,`	Antifungal antibiotics, systemically used 	`,`	null	`],
	[`	Y40.8	`,`	Other systemic antibiotics 	`,`	null	`],
	[`	Y40.9	`,`	Systemic antibiotic, unspecified 	`,`	null	`],
	[`	Y41	`,`	Other systemic anti-infectives and antiparasitics Excl.: anti-infectives, topically used (Y56.-) 	`,`	null	`],
	[`	Y41.0	`,`	Sulfonamides 	`,`	null	`],
	[`	Y41.1	`,`	Antimycobacterial drugs Excl.: rifamycins (Y40.6) streptomycin (Y40.5) 	`,`	null	`],
	[`	Y41.2	`,`	Antimalarials and drugs acting on other blood protozoa Excl.: hydroxyquinoline derivatives (Y41.8) 	`,`	null	`],
	[`	Y41.3	`,`	Other antiprotozoal drugs 	`,`	null	`],
	[`	Y41.4	`,`	Anthelminthics 	`,`	null	`],
	[`	Y41.5	`,`	Antiviral drugs Excl.: amantadine (Y46.7) cytarabine (Y43.1) 	`,`	null	`],
	[`	Y41.8	`,`	Other specified systemic anti-infectives and antiparasitics Hydroxyquinoline derivatives Excl.: antimalarial drugs (Y41.2) 	`,`	null	`],
	[`	Y41.9	`,`	Systemic anti-infective and antiparasitic, unspecified 	`,`	null	`],
	[`	Y42	`,`	Hormones and their synthetic substitutes and antagonists, not elsewhere classified Excl.: mineralocorticoids and their antagonists (Y54.0-Y54.1) oxytocic hormones (Y55.0) parathyroid hormones and derivatives (Y54.7) 	`,`	null	`],
	[`	Y42.0	`,`	Glucocorticoids and synthetic analogues Excl.: glucocorticoids, topically used (Y56.-) 	`,`	null	`],
	[`	Y42.1	`,`	Thyroid hormones and substitutes 	`,`	null	`],
	[`	Y42.2	`,`	Antithyroid drugs 	`,`	null	`],
	[`	Y42.3	`,`	Insulin and oral hypoglycaemic [antidiabetic] drugs 	`,`	null	`],
	[`	Y42.4	`,`	Oral contraceptives Multiple- and single-ingredient preparations 	`,`	null	`],
	[`	Y42.5	`,`	Other estrogens and progestogens Mixtures and substitutes 	`,`	null	`],
	[`	Y42.6	`,`	Antigonadotrophins, antiestrogens, antiandrogens, not elsewhere classified Tamoxifen 	`,`	null	`],
	[`	Y42.7	`,`	Androgens and anabolic congeners 	`,`	null	`],
	[`	Y42.8	`,`	Other and unspecified hormones and their synthetic substitutes Anterior pituitary [adenohypophyseal] hormones 	`,`	null	`],
	[`	Y42.9	`,`	Other and unspecified hormone antagonists 	`,`	null	`],
	[`	Y43	`,`	Primarily systemic agents Excl.: vitamins NEC (Y57.7) 	`,`	null	`],
	[`	Y43.0	`,`	Antiallergic and antiemetic drugs Excl.: phenothiazine-based neuroleptics (Y49.3) 	`,`	null	`],
	[`	Y43.1	`,`	Antineoplastic antimetabolites Cytarabine 	`,`	null	`],
	[`	Y43.2	`,`	Antineoplastic natural products 	`,`	null	`],
	[`	Y43.3	`,`	Other antineoplastic drugs Antineoplastic antibiotics Excl.: tamoxifen (Y42.6) 	`,`	null	`],
	[`	Y43.4	`,`	Immunosuppressive agents 	`,`	null	`],
	[`	Y43.5	`,`	Acidifying and alkalizing agents 	`,`	null	`],
	[`	Y43.6	`,`	Enzymes, not elsewhere classified 	`,`	null	`],
	[`	Y43.8	`,`	Other primarily systemic agents, not elsewhere classified Heavy-metal antagonists 	`,`	null	`],
	[`	Y43.9	`,`	Primarily systemic agent, unspecified 	`,`	null	`],
	[`	Y44	`,`	Agents primarily affecting blood constituents 	`,`	null	`],
	[`	Y44.0	`,`	Iron preparations and other anti-hypochromic-anaemia preparations 	`,`	null	`],
	[`	Y44.1	`,`	Vitamin B12, folic acid and other anti-megaloblastic-anaemia preparations 	`,`	null	`],
	[`	Y44.2	`,`	Anticoagulants 	`,`	null	`],
	[`	Y44.3	`,`	Anticoagulant antagonists, vitamin K and other coagulants 	`,`	null	`],
	[`	Y44.4	`,`	Antithrombotic drugs [platelet-aggregation inhibitors] Excl.: acetylsalicylic acid (Y45.1) dipyridamole (Y52.3) 	`,`	null	`],
	[`	Y44.5	`,`	Thrombolytic drugs 	`,`	null	`],
	[`	Y44.6	`,`	Natural blood and blood products Excl.: immunoglobulin (Y59.3) 	`,`	null	`],
	[`	Y44.7	`,`	Plasma substitutes 	`,`	null	`],
	[`	Y44.9	`,`	Other and unspecified agents affecting blood constituents 	`,`	null	`],
	[`	Y45	`,`	Analgesics, antipyretics and anti-inflammatory drugs 	`,`	null	`],
	[`	Y45.0	`,`	Opioids and related analgesics 	`,`	null	`],
	[`	Y45.1	`,`	Salicylates 	`,`	null	`],
	[`	Y45.2	`,`	Propionic acid derivatives Propanoic acid derivatives 	`,`	null	`],
	[`	Y45.3	`,`	Other nonsteroidal anti-inflammatory drugs [NSAID] 	`,`	null	`],
	[`	Y45.4	`,`	Antirheumatics Excl.: chloroquine (Y41.2) glucocorticoids (Y42.0) salicylates (Y45.1) 	`,`	null	`],
	[`	Y45.5	`,`	4-Aminophenol derivatives 	`,`	null	`],
	[`	Y45.8	`,`	Other analgesics and antipyretics 	`,`	null	`],
	[`	Y45.9	`,`	Analgesic, antipyretic and anti-inflammatory drug, unspecified 	`,`	null	`],
	[`	Y46	`,`	Antiepileptics and antiparkinsonism drugs Excl.: acetazolamide (Y54.2) barbiturates NEC (Y47.0) benzodiazepines (Y47.1) paraldehyde (Y47.3) 	`,`	null	`],
	[`	Y46.0	`,`	Succinimides 	`,`	null	`],
	[`	Y46.1	`,`	Oxazolidinediones 	`,`	null	`],
	[`	Y46.2	`,`	Hydantoin derivatives 	`,`	null	`],
	[`	Y46.3	`,`	Deoxybarbiturates 	`,`	null	`],
	[`	Y46.4	`,`	Iminostilbenes Carbamazepine 	`,`	null	`],
	[`	Y46.5	`,`	Valproic acid 	`,`	null	`],
	[`	Y46.6	`,`	Other and unspecified antiepileptics 	`,`	null	`],
	[`	Y46.7	`,`	Antiparkinsonism drugs Amantadine 	`,`	null	`],
	[`	Y46.8	`,`	Antispasticity drugs Excl.: benzodiazepines (Y47.1) 	`,`	null	`],
	[`	Y47	`,`	Sedatives, hypnotics and antianxiety drugs 	`,`	null	`],
	[`	Y47.0	`,`	Barbiturates, not elsewhere classified Excl.: deoxybarbiturates (Y46.3) thiobarbiturates (Y48.1) 	`,`	null	`],
	[`	Y47.1	`,`	Benzodiazepines 	`,`	null	`],
	[`	Y47.2	`,`	Cloral derivatives 	`,`	null	`],
	[`	Y47.3	`,`	Paraldehyde 	`,`	null	`],
	[`	Y47.4	`,`	Bromine compounds 	`,`	null	`],
	[`	Y47.5	`,`	Mixed sedatives and hypnotics, not elsewhere classified 	`,`	null	`],
	[`	Y47.8	`,`	Other sedatives, hypnotics and antianxiety drugs Methaqualone 	`,`	null	`],
	[`	Y47.9	`,`	Sedative, hypnotic and antianxiety drug, unspecified Sleeping: draught drug tablet NOS 	`,`	null	`],
	[`	Y48	`,`	Anaesthetics and therapeutic gases 	`,`	null	`],
	[`	Y48.0	`,`	Inhaled anaesthetics 	`,`	null	`],
	[`	Y48.1	`,`	Parenteral anaesthetics Thiobarbiturates 	`,`	null	`],
	[`	Y48.2	`,`	Other and unspecified general anaesthetics 	`,`	null	`],
	[`	Y48.3	`,`	Local anaesthetics 	`,`	null	`],
	[`	Y48.4	`,`	Anaesthetic, unspecified 	`,`	null	`],
	[`	Y48.5	`,`	Therapeutic gases 	`,`	null	`],
	[`	Y49	`,`	Psychotropic drugs, not elsewhere classified Excl.: appetite depressants [anorectics] (Y57.0) barbiturates NEC (Y47.0) benzodiazepines (Y47.1) caffeine (Y50.2) cocaine (Y48.3) methaqualone (Y47.8) 	`,`	null	`],
	[`	Y49.0	`,`	Tricyclic and tetracyclic antidepressants 	`,`	null	`],
	[`	Y49.1	`,`	Monoamine-oxidase-inhibitor antidepressants 	`,`	null	`],
	[`	Y49.2	`,`	Other and unspecified antidepressants 	`,`	null	`],
	[`	Y49.3	`,`	Phenothiazine antipsychotics and neuroleptics 	`,`	null	`],
	[`	Y49.4	`,`	Butyrophenone and thioxanthene neuroleptics 	`,`	null	`],
	[`	Y49.5	`,`	Other antipsychotics and neuroleptics Excl.: rauwolfia (Y52.5) 	`,`	null	`],
	[`	Y49.6	`,`	Psychodysleptics [hallucinogens] 	`,`	null	`],
	[`	Y49.7	`,`	Psychostimulants with abuse potential 	`,`	null	`],
	[`	Y49.8	`,`	Other psychotropic drugs, not elsewhere classified 	`,`	null	`],
	[`	Y49.9	`,`	Psychotropic drug, unspecified 	`,`	null	`],
	[`	Y50	`,`	Central nervous system stimulants, not elsewhere classified 	`,`	null	`],
	[`	Y50.0	`,`	Analeptics 	`,`	null	`],
	[`	Y50.1	`,`	Opioid receptor antagonists 	`,`	null	`],
	[`	Y50.2	`,`	Methylxanthines, not elsewhere classified Caffeine Excl.: aminophylline (Y55.6) theobromine (Y55.6) theophylline (Y55.6) 	`,`	null	`],
	[`	Y50.8	`,`	Other central nervous system stimulants 	`,`	null	`],
	[`	Y50.9	`,`	Central nervous system stimulant, unspecified 	`,`	null	`],
	[`	Y51	`,`	Drugs primarily affecting the autonomic nervous system 	`,`	null	`],
	[`	Y51.0	`,`	Anticholinesterase agents 	`,`	null	`],
	[`	Y51.1	`,`	Other parasympathomimetics [cholinergics] 	`,`	null	`],
	[`	Y51.2	`,`	Ganglionic blocking drugs, not elsewhere classified 	`,`	null	`],
	[`	Y51.3	`,`	Other parasympatholytics [anticholinergics and antimuscarinics] and spasmolytics, not elsewhere classified Papaverine 	`,`	null	`],
	[`	Y51.4	`,`	Predominantly alpha-adrenoreceptor agonists, not elsewhere classified Metaraminol 	`,`	null	`],
	[`	Y51.5	`,`	Predominantly beta-adrenoreceptor agonists, not elsewhere classified Excl.: salbutamol (Y55.6) 	`,`	null	`],
	[`	Y51.6	`,`	Alpha-adrenoreceptor antagonists, not elsewhere classified Excl.: ergot alkaloids (Y55.0) 	`,`	null	`],
	[`	Y51.7	`,`	Beta-adrenoreceptor antagonists, not elsewhere classified 	`,`	null	`],
	[`	Y51.8	`,`	Centrally acting and adrenergic-neuron-blocking agents, not elsewhere classified Excl.: clonidine (Y52.5) guanethidine (Y52.5) 	`,`	null	`],
	[`	Y51.9	`,`	Other and unspecified drugs primarily affecting the autonomic nervous system Drugs stimulating both alpha- and beta-adrenoreceptors 	`,`	null	`],
	[`	Y52	`,`	Agents primarily affecting the cardiovascular system Excl.: metaraminol (Y51.4) 	`,`	null	`],
	[`	Y52.0	`,`	Cardiac-stimulant glycosides and drugs of similar action 	`,`	null	`],
	[`	Y52.1	`,`	Calcium-channel blockers 	`,`	null	`],
	[`	Y52.2	`,`	Other antidysrhythmic drugs, not elsewhere classified Excl.: beta-adrenoreceptor antagonists (Y51.7) 	`,`	null	`],
	[`	Y52.3	`,`	Coronary vasodilators, not elsewhere classified Dipyridamole Excl.: beta-adrenoreceptor antagonists (Y51.7) calcium-channel blockers (Y52.1) 	`,`	null	`],
	[`	Y52.4	`,`	Angiotensin-converting-enzyme inhibitors 	`,`	null	`],
	[`	Y52.5	`,`	Other antihypertensive drugs, not elsewhere classified Clonidine Guanethidine Rauwolfia Excl.: beta-adrenoreceptor antagonists (Y51.7) calcium-channel blockers (Y52.1) diuretics (Y54.0-Y54.5) 	`,`	null	`],
	[`	Y52.6	`,`	Antihyperlipidaemic and antiarteriosclerotic drugs 	`,`	null	`],
	[`	Y52.7	`,`	Peripheral vasodilators Nicotinic acid (derivatives) Excl.: papaverine (Y51.3) 	`,`	null	`],
	[`	Y52.8	`,`	Antivaricose drugs, including sclerosing agents 	`,`	null	`],
	[`	Y52.9	`,`	Other and unspecified agents primarily affecting the cardiovascular system 	`,`	null	`],
	[`	Y53	`,`	Agents primarily affecting the gastrointestinal system 	`,`	null	`],
	[`	Y53.0	`,`	Histamine H2-receptor antagonists 	`,`	null	`],
	[`	Y53.1	`,`	Other antacids and anti-gastric-secretion drugs 	`,`	null	`],
	[`	Y53.2	`,`	Stimulant laxatives 	`,`	null	`],
	[`	Y53.3	`,`	Saline and osmotic laxatives 	`,`	null	`],
	[`	Y53.4	`,`	Other laxatives Intestinal atonia drugs 	`,`	null	`],
	[`	Y53.5	`,`	Digestants 	`,`	null	`],
	[`	Y53.6	`,`	Antidiarrhoeal drugs Excl.: systemic antibiotics and other anti-infectives (Y40-Y41) 	`,`	null	`],
	[`	Y53.7	`,`	Emetics 	`,`	null	`],
	[`	Y53.8	`,`	Other agents primarily affecting the gastrointestinal system 	`,`	null	`],
	[`	Y53.9	`,`	Agent primarily affecting the gastrointestinal system, unspecified 	`,`	null	`],
	[`	Y54	`,`	Agents primarily affecting water-balance and mineral and uric acid metabolism 	`,`	null	`],
	[`	Y54.0	`,`	Mineralocorticoids 	`,`	null	`],
	[`	Y54.1	`,`	Mineralocorticoid antagonists [aldosterone antagonists] 	`,`	null	`],
	[`	Y54.2	`,`	Carbonic-anhydrase inhibitors Acetazolamide 	`,`	null	`],
	[`	Y54.3	`,`	Benzothiadiazine derivatives 	`,`	null	`],
	[`	Y54.4	`,`	Loop [high-ceiling] diuretics 	`,`	null	`],
	[`	Y54.5	`,`	Other diuretics 	`,`	null	`],
	[`	Y54.6	`,`	Electrolytic, caloric and water-balance agents Oral rehydration salts 	`,`	null	`],
	[`	Y54.7	`,`	Agents affecting calcification Parathyroid hormones and derivatives Vitamin D group 	`,`	null	`],
	[`	Y54.8	`,`	Agents affecting uric acid metabolism 	`,`	null	`],
	[`	Y54.9	`,`	Mineral salts, not elsewhere classified 	`,`	null	`],
	[`	Y55	`,`	Agents primarily acting on smooth and skeletal muscles and the respiratory system 	`,`	null	`],
	[`	Y55.0	`,`	Oxytocic drugs Ergot alkaloids Excl.: estrogens, progestogens and antagonists (Y42.5-Y42.6) 	`,`	null	`],
	[`	Y55.1	`,`	Skeletal muscle relaxants [neuromuscular blocking agents] Excl.: antispasticity drugs (Y46.8) 	`,`	null	`],
	[`	Y55.2	`,`	Other and unspecified agents primarily acting on muscles 	`,`	null	`],
	[`	Y55.3	`,`	Antitussives 	`,`	null	`],
	[`	Y55.4	`,`	Expectorants 	`,`	null	`],
	[`	Y55.5	`,`	Anti-common-cold drugs 	`,`	null	`],
	[`	Y55.6	`,`	Antiasthmatics, not elsewhere classified Aminophylline Salbutamol Theobromine Theophylline Excl.: beta-adrenoreceptor agonists (Y51.5) anterior pituitary [adenohypophyseal] hormones (Y42.8) 	`,`	null	`],
	[`	Y55.7	`,`	Other and unspecified agents primarily acting on the respiratory system 	`,`	null	`],
	[`	Y56	`,`	Topical agents primarily affecting skin and mucous membrane and ophthalmological, otorhinolaryngological and dental drugs Incl.: glucocorticoids, topically used 	`,`	null	`],
	[`	Y56.0	`,`	Local antifungal, anti-infective and anti-inflammatory drugs, not elsewhere classified 	`,`	null	`],
	[`	Y56.1	`,`	Antipruritics 	`,`	null	`],
	[`	Y56.2	`,`	Local astringents and local detergents 	`,`	null	`],
	[`	Y56.3	`,`	Emollients, demulcents and protectants 	`,`	null	`],
	[`	Y56.4	`,`	Keratolytics, keratoplastics and other hair treatment drugs and preparations 	`,`	null	`],
	[`	Y56.5	`,`	Ophthalmological drugs and preparations 	`,`	null	`],
	[`	Y56.6	`,`	Otorhinolaryngological drugs and preparations 	`,`	null	`],
	[`	Y56.7	`,`	Dental drugs, topically applied 	`,`	null	`],
	[`	Y56.8	`,`	Other topical agents Spermicides 	`,`	null	`],
	[`	Y56.9	`,`	Topical agent, unspecified 	`,`	null	`],
	[`	Y57	`,`	Other and unspecified drugs and medicaments 	`,`	null	`],
	[`	Y57.0	`,`	Appetite depressants [anorectics] 	`,`	null	`],
	[`	Y57.1	`,`	Lipotropic drugs 	`,`	null	`],
	[`	Y57.2	`,`	Antidotes and chelating agents, not elsewhere classified 	`,`	null	`],
	[`	Y57.3	`,`	Alcohol deterrents 	`,`	null	`],
	[`	Y57.4	`,`	Pharmaceutical excipients 	`,`	null	`],
	[`	Y57.5	`,`	X-ray contrast media 	`,`	null	`],
	[`	Y57.6	`,`	Other diagnostic agents 	`,`	null	`],
	[`	Y57.7	`,`	Vitamins, not elsewhere classified Excl.: nicotinic acid (Y52.7) vitamin B12 (Y44.1) vitamin D (Y54.7) vitamin K (Y44.3) 	`,`	null	`],
	[`	Y57.8	`,`	Other drugs and medicaments 	`,`	null	`],
	[`	Y57.9	`,`	Drug or medicament, unspecified 	`,`	null	`],
	[`	Y58	`,`	Bacterial vaccines 	`,`	null	`],
	[`	Y58.0	`,`	BCG vaccine 	`,`	null	`],
	[`	Y58.1	`,`	Typhoid and paratyphoid vaccine 	`,`	null	`],
	[`	Y58.2	`,`	Cholera vaccine 	`,`	null	`],
	[`	Y58.3	`,`	Plague vaccine 	`,`	null	`],
	[`	Y58.4	`,`	Tetanus vaccine 	`,`	null	`],
	[`	Y58.5	`,`	Diphtheria vaccine 	`,`	null	`],
	[`	Y58.6	`,`	Pertussis vaccine, including combinations with a pertussis component 	`,`	null	`],
	[`	Y58.8	`,`	Mixed bacterial vaccines, except combinations with a pertussis component 	`,`	null	`],
	[`	Y58.9	`,`	Other and unspecified bacterial vaccines 	`,`	null	`],
	[`	Y59	`,`	Other and unspecified vaccines and biological substances 	`,`	null	`],
	[`	Y59.0	`,`	Viral vaccines 	`,`	null	`],
	[`	Y59.1	`,`	Rickettsial vaccines 	`,`	null	`],
	[`	Y59.2	`,`	Protozoal vaccines 	`,`	null	`],
	[`	Y59.3	`,`	Immunoglobulin 	`,`	null	`],
	[`	Y59.8	`,`	Other specified vaccines and biological substances 	`,`	null	`],
	[`	Y59.9	`,`	Vaccine or biological substance, unspecified 	`,`	null	`],
	[`	Y60	`,`	Unintentional cut, puncture, perforation or haemorrhage during surgical and medical care 	`,`	null	`],
	[`	Y60.0	`,`	During surgical operation 	`,`	null	`],
	[`	Y60.1	`,`	During infusion or transfusion 	`,`	null	`],
	[`	Y60.2	`,`	During kidney dialysis or other perfusion 	`,`	null	`],
	[`	Y60.3	`,`	During injection or immunization 	`,`	null	`],
	[`	Y60.4	`,`	During endoscopic examination 	`,`	null	`],
	[`	Y60.5	`,`	During heart catheterization 	`,`	null	`],
	[`	Y60.6	`,`	During aspiration, puncture and other catheterization 	`,`	null	`],
	[`	Y60.7	`,`	During administration of enema 	`,`	null	`],
	[`	Y60.8	`,`	During other surgical and medical care 	`,`	null	`],
	[`	Y60.9	`,`	During unspecified surgical and medical care 	`,`	null	`],
	[`	Y61	`,`	Foreign object accidentally left in body during surgical and medical care 	`,`	null	`],
	[`	Y61.0	`,`	During surgical operation 	`,`	null	`],
	[`	Y61.1	`,`	During infusion or transfusion 	`,`	null	`],
	[`	Y61.2	`,`	During kidney dialysis or other perfusion 	`,`	null	`],
	[`	Y61.3	`,`	During injection or immunization 	`,`	null	`],
	[`	Y61.4	`,`	During endoscopic examination 	`,`	null	`],
	[`	Y61.5	`,`	During heart catheterization 	`,`	null	`],
	[`	Y61.6	`,`	During aspiration, puncture and other catheterization 	`,`	null	`],
	[`	Y61.7	`,`	During removal of catheter or packing 	`,`	null	`],
	[`	Y61.8	`,`	During other surgical and medical care 	`,`	null	`],
	[`	Y61.9	`,`	During unspecified surgical and medical care 	`,`	null	`],
	[`	Y62	`,`	Failure of sterile precautions during surgical and medical care 	`,`	null	`],
	[`	Y62.0	`,`	During surgical operation 	`,`	null	`],
	[`	Y62.1	`,`	During infusion or transfusion 	`,`	null	`],
	[`	Y62.2	`,`	During kidney dialysis or other perfusion 	`,`	null	`],
	[`	Y62.3	`,`	During injection or immunization 	`,`	null	`],
	[`	Y62.4	`,`	During endoscopic examination 	`,`	null	`],
	[`	Y62.5	`,`	During heart catheterization 	`,`	null	`],
	[`	Y62.6	`,`	During aspiration, puncture and other catheterization 	`,`	null	`],
	[`	Y62.8	`,`	During other surgical and medical care 	`,`	null	`],
	[`	Y62.9	`,`	During unspecified surgical and medical care 	`,`	null	`],
	[`	Y63	`,`	Failure in dosage during surgical and medical care Excl.: accidental overdose of drug or wrong drug given in error (X40-X44) 	`,`	null	`],
	[`	Y63.0	`,`	Excessive amount of blood or other fluid given during transfusion or infusion 	`,`	null	`],
	[`	Y63.1	`,`	Incorrect dilution of fluid used during infusion 	`,`	null	`],
	[`	Y63.2	`,`	Overdose of radiation given during therapy 	`,`	null	`],
	[`	Y63.3	`,`	Inadvertent exposure of patient to radiation during medical care 	`,`	null	`],
	[`	Y63.4	`,`	Failure in dosage in electroshock or insulin-shock therapy 	`,`	null	`],
	[`	Y63.5	`,`	Inappropriate temperature in local application and packing 	`,`	null	`],
	[`	Y63.6	`,`	Nonadministration of necessary drug, medicament or biological substance 	`,`	null	`],
	[`	Y63.8	`,`	Failure in dosage during other surgical and medical care 	`,`	null	`],
	[`	Y63.9	`,`	Failure in dosage during unspecified surgical and medical care 	`,`	null	`],
	[`	Y64	`,`	Contaminated medical or biological substances 	`,`	null	`],
	[`	Y64.0	`,`	Contaminated medical or biological substance, transfused or infused 	`,`	null	`],
	[`	Y64.1	`,`	Contaminated medical or biological substance, injected or used for immunization 	`,`	null	`],
	[`	Y64.8	`,`	Contaminated medical or biological substance administered by other means 	`,`	null	`],
	[`	Y64.9	`,`	Contaminated medical or biological substance administered by unspecified means Administered contaminated medical or biological substance NOS 	`,`	null	`],
	[`	Y65	`,`	Other misadventures during surgical and medical care 	`,`	null	`],
	[`	Y65.0	`,`	Mismatched blood used in transfusion 	`,`	null	`],
	[`	Y65.1	`,`	Wrong fluid used in infusion 	`,`	null	`],
	[`	Y65.2	`,`	Failure in suture or ligature during surgical operation 	`,`	null	`],
	[`	Y65.3	`,`	Endotracheal tube wrongly placed during anaesthetic procedure 	`,`	null	`],
	[`	Y65.4	`,`	Failure to introduce or to remove other tube or instrument 	`,`	null	`],
	[`	Y65.5	`,`	Performance of inappropriate operation 	`,`	null	`],
	[`	Y65.8	`,`	Other specified misadventures during surgical and medical care 	`,`	null	`],
	[`	Y66	`,`	Nonadministration of surgical and medical care Incl.: Premature cessation of surgical and medical care 	`,`	null	`],
	[`	Y69	`,`	Unspecified misadventure during surgical and medical care 	`,`	null	`],
	[`	Y70	`,`	Anaesthesiology devices associated with adverse incidents [See before Y70 for subdivisions] 	`,`	null	`],
	[`	Y71	`,`	Cardiovascular devices associated with adverse incidents [See before Y70 for subdivisions] 	`,`	null	`],
	[`	Y72	`,`	Otorhinolaryngological devices associated with adverse incidents [See before Y70 for subdivisions] 	`,`	null	`],
	[`	Y73	`,`	Gastroenterology and urology devices associated with adverse incidents [See before Y70 for subdivisions] 	`,`	null	`],
	[`	Y74	`,`	General hospital and personal-use devices associated with adverse incidents [See before Y70 for subdivisions] 	`,`	null	`],
	[`	Y75	`,`	Neurological devices associated with adverse incidents [See before Y70 for subdivisions] 	`,`	null	`],
	[`	Y76	`,`	Obstetric and gynaecological devices associated with adverse incidents [See before Y70 for subdivisions] 	`,`	null	`],
	[`	Y77	`,`	Ophthalmic devices associated with adverse incidents [See before Y70 for subdivisions] 	`,`	null	`],
	[`	Y78	`,`	Radiological devices associated with adverse incidents [See before Y70 for subdivisions] 	`,`	null	`],
	[`	Y79	`,`	Orthopaedic devices associated with adverse incidents [See before Y70 for subdivisions] 	`,`	null	`],
	[`	Y80	`,`	Physical medicine devices associated with adverse incidents [See before Y70 for subdivisions] 	`,`	null	`],
	[`	Y81	`,`	General- and plastic-surgery devices associated with adverse incidents [See before Y70 for subdivisions] 	`,`	null	`],
	[`	Y82	`,`	Other and unspecified medical devices associated with adverse incidents [See before Y70 for subdivisions] 	`,`	null	`],
	[`	Y83	`,`	Surgical operation and other surgical procedures as the cause of abnormal reaction of the patient, or of later complication, without mention of misadventure at the time of the procedure 	`,`	null	`],
	[`	Y83.0	`,`	Surgical operation with transplant of whole organ 	`,`	null	`],
	[`	Y83.1	`,`	Surgical operation with implant of artificial internal device 	`,`	null	`],
	[`	Y83.2	`,`	Surgical operation with anastomosis, bypass or graft 	`,`	null	`],
	[`	Y83.3	`,`	Surgical operation with formation of external stoma 	`,`	null	`],
	[`	Y83.4	`,`	Other reconstructive surgery 	`,`	null	`],
	[`	Y83.5	`,`	Amputation of limb(s) 	`,`	null	`],
	[`	Y83.6	`,`	Removal of other organ (partial) (total) 	`,`	null	`],
	[`	Y83.8	`,`	Other surgical procedures 	`,`	null	`],
	[`	Y83.9	`,`	Surgical procedure, unspecified 	`,`	null	`],
	[`	Y84	`,`	Other medical procedures as the cause of abnormal reaction of the patient, or of later complication, without mention of misadventure at the time of the procedure 	`,`	null	`],
	[`	Y84.0	`,`	Cardiac catheterization 	`,`	null	`],
	[`	Y84.1	`,`	Kidney dialysis 	`,`	null	`],
	[`	Y84.2	`,`	Radiological procedure and radiotherapy 	`,`	null	`],
	[`	Y84.3	`,`	Shock therapy 	`,`	null	`],
	[`	Y84.4	`,`	Aspiration of fluid 	`,`	null	`],
	[`	Y84.5	`,`	Insertion of gastric or duodenal sound 	`,`	null	`],
	[`	Y84.6	`,`	Urinary catheterization 	`,`	null	`],
	[`	Y84.7	`,`	Blood-sampling 	`,`	null	`],
	[`	Y84.8	`,`	Other medical procedures 	`,`	null	`],
	[`	Y84.9	`,`	Medical procedure, unspecified 	`,`	null	`],
	[`	Y85	`,`	Sequelae of transport accidents 	`,`	null	`],
	[`	Y85.0	`,`	Sequelae of motor-vehicle accident 	`,`	null	`],
	[`	Y85.9	`,`	Sequelae of other and unspecified transport accidents 	`,`	null	`],
	[`	Y86	`,`	Sequelae of other accidents 	`,`	null	`],
	[`	Y87	`,`	Sequelae of intentional self-harm, assault and events of undetermined intent 	`,`	null	`],
	[`	Y87.0	`,`	Sequelae of intentional self-harm 	`,`	null	`],
	[`	Y87.1	`,`	Sequelae of assault 	`,`	null	`],
	[`	Y87.2	`,`	Sequelae of events of undetermined intent 	`,`	null	`],
	[`	Y88	`,`	Sequelae with surgical and medical care as external cause 	`,`	null	`],
	[`	Y88.0	`,`	Sequelae of adverse effects caused by drugs, medicaments and biological substances in therapeutic use 	`,`	null	`],
	[`	Y88.1	`,`	Sequelae of misadventures to patients during surgical and medical procedures 	`,`	null	`],
	[`	Y88.2	`,`	Sequelae of adverse incidents associated with medical devices in diagnostic and therapeutic use 	`,`	null	`],
	[`	Y88.3	`,`	Sequelae of surgical and medical procedures as the cause of abnormal reaction of the patient, or of later complication, without mention of misadventure at the time of the procedure 	`,`	null	`],
	[`	Y89	`,`	Sequelae of other external causes 	`,`	null	`],
	[`	Y89.0	`,`	Sequelae of legal intervention 	`,`	null	`],
	[`	Y89.1	`,`	Sequelae of war operations 	`,`	null	`],
	[`	Y89.9	`,`	Sequelae of unspecified external cause 	`,`	null	`],
	[`	Y90	`,`	Evidence of alcohol involvement determined by blood alcohol level 	`,`	null	`],
	[`	Y90.0	`,`	Blood alcohol level of less than 20 mg/100 ml 	`,`	null	`],
	[`	Y90.1	`,`	Blood alcohol level of 20-39 mg/100 ml 	`,`	null	`],
	[`	Y90.2	`,`	Blood alcohol level of 40-59 mg/100 ml 	`,`	null	`],
	[`	Y90.3	`,`	Blood alcohol level of 60-79 mg/100 ml 	`,`	null	`],
	[`	Y90.4	`,`	Blood alcohol level of 80-99 mg/100 ml 	`,`	null	`],
	[`	Y90.5	`,`	Blood alcohol level of 100-119 mg/100 ml 	`,`	null	`],
	[`	Y90.6	`,`	Blood alcohol level of 120-199 mg/100 ml 	`,`	null	`],
	[`	Y90.7	`,`	Blood alcohol level of 200-239 mg/100 ml 	`,`	null	`],
	[`	Y90.8	`,`	Blood alcohol level of 240 mg/100 ml or more 	`,`	null	`],
	[`	Y90.9	`,`	Presence of alcohol in blood, level not specified Y91 Evidence of alcohol involvement determined by level of intoxication Excl.: evidence of alcohol involvement determined by blood alcohol content (Y90.-) 	`,`	null	`],
	[`	Y91.0	`,`	Mild alcohol intoxication Smell of alcohol on breath, slight behavioural disturbance in functions and responses, or slight difficulty in coordination. 	`,`	null	`],
	[`	Y91.1	`,`	Moderate alcohol intoxication Smell of alcohol on breath, moderate behavioural disturbance in functions and responses, or moderate difficulty in coordination. 	`,`	null	`],
	[`	Y91.2	`,`	Severe alcohol intoxication Severe disturbance in functions and responses, severe difficulty in coordination, or impaired ability to cooperate. 	`,`	null	`],
	[`	Y91.3	`,`	Very severe alcohol intoxication Very severe disturbance in functions and responses, very severe difficulty in coordination, or loss of ability to cooperate. 	`,`	null	`],
	[`	Y91.9	`,`	Alcohol involvement, not otherwise specified Suspected alcohol involvement NOS 	`,`	null	`],
	[`	Y95	`,`	Nosocomial condition 	`,`	null	`],
	[`	Y96	`,`	Work-related condition 	`,`	null	`],
	[`	Y97	`,`	Environmental-pollution-related condition 	`,`	null	`],
	[`	Y98	`,`	Lifestyle-related condition 	`,`	null	`]
							
							
							
];								
				
	
let CodeRangeY ={
	f0:function(val1=(-1),val2=(0)){
		let yRange1 = YCodes.slice(val1,val2);
		yRange1.reverse();
		document.documentElement.innerHTML += `Showing Y Codes ${yRange1.length} items(s)`;

		for(value2 in yRange1){
			    document.documentElement.style.cssText += "background-color:tan;";
				document.getElementById('ycodesTR').outerHTML += `<tr><td style="background-color:navy;color:white;width:5%;padding:40px;border:2px solid white;font-weight:900;font-size:40px;text-align:center;">${yRange1[value2][0]}</td><td style="background-color:black;color:white;width:90%;padding:20px;border:2px solid white;font-size:30px;">${yRange1[value2][1]}</td><td style="background-color:navy;color:white;width:5%;padding:20px;border:2px solid white;font-weight:900;font-size:40px;text-align:center;">${yRange1[value2][2]}</td></tr>`;			
		}

	},

};

	






	






