let ZCodes = [								
		[`	ID	`,`	SYMPTOMS / PROBLEMS / ISSUES	`,`	SYSTEM	`],	
		[`	Z00	`,`	General examination and investigation of persons without complaint and reported diagnosis Excl.: examination for administrative purposes (Z02.-) special screening examinations (Z11-Z13) 	`,`	null	`],	
		[`	Z00.0	`,`	General medical examination Health check-up NOS Periodic examination (annual)(physical) Excl.: general health check-up of: defined subpopulations (Z10.-) infant or child (Z00.1) 	`,`	null	`],	
		[`	Z00.1	`,`	Routine child health examination Development testing of infant or child Excl.: health supervision of foundling or other healthy infant or child (Z76.1-Z76.2) 	`,`	null	`],	
		[`	Z00.2	`,`	Examination for period of rapid growth in childhood 	`,`	null	`],	
		[`	Z00.3	`,`	Examination for adolescent development state Puberty development state 	`,`	null	`],	
		[`	Z00.4	`,`	General psychiatric examination, not elsewhere classified Excl.: examination requested for medicolegal reasons (Z04.6) 	`,`	null	`],	
		[`	Z00.5	`,`	Examination of potential donor of organ and tissue 	`,`	null	`],	
		[`	Z00.6	`,`	Examination for normal comparison and control in clinical research programme 	`,`	null	`],	
		[`	Z00.8	`,`	Other general examinations Health examination in population surveys 	`,`	null	`],	
		[`	Z01	`,`	Other special examinations and investigations of persons without complaint or reported diagnosis Incl.: routine examination of specific system Excl.: examination for: administrative purposes (Z02.-) suspected conditions, not proven (Z03.-) special screening examinations (Z11-Z13) 	`,`	null	`],	
		[`	Z01.0	`,`	Examination of eyes and vision Excl.: examination for driving licence (Z02.4) 	`,`	null	`],	
		[`	Z01.1	`,`	Examination of ears and hearing 	`,`	null	`],	
		[`	Z01.2	`,`	Dental examination 	`,`	null	`],	
		[`	Z01.3	`,`	Examination of blood pressure 	`,`	null	`],	
		[`	Z01.4	`,`	Gynaecological examination (general)(routine) Papanicolaou smear of cervix Pelvic examination (annual)(periodic) Excl.: pregnancy examination or test (Z32.-) routine examination for contraceptive maintenance (Z30.4-Z30.5) 	`,`	null	`],	
		[`	Z01.5	`,`	Diagnostic skin and sensitization tests Allergy tests Skin tests for: bacterial disease hypersensitivity 	`,`	null	`],	
		[`	Z01.6	`,`	Radiological examination, not elsewhere classified Routine: chest X-ray mammogram 	`,`	null	`],	
		[`	Z01.7	`,`	Laboratory examination 	`,`	null	`],	
		[`	Z01.8	`,`	Other specified special examinations 	`,`	null	`],	
		[`	Z01.9	`,`	Special examination, unspecified 	`,`	null	`],	
		[`	Z02	`,`	Examination and encounter for administrative purposes 	`,`	null	`],	
		[`	Z02.0	`,`	Examination for admission to educational institution Examination for admission to preschool (education) 	`,`	null	`],	
		[`	Z02.1	`,`	Pre-employment examination Excl.: occupational health examination (Z10.0) 	`,`	null	`],	
		[`	Z02.2	`,`	Examination for admission to residential institutions Excl.: examination for admission to prison (Z02.8) general health check-up of inhabitants of institutions (Z10.1) 	`,`	null	`],	
		[`	Z02.3	`,`	Examination for recruitment to armed forces Excl.: general health check-up of armed forces (Z10.2) 	`,`	null	`],	
		[`	Z02.4	`,`	Examination for driving licence 	`,`	null	`],	
		[`	Z02.5	`,`	Examination for participation in sport Excl.: blood-alcohol and blood-drug test (Z04.0) general health check-up of sports teams (Z10.3) 	`,`	null	`],	
		[`	Z02.6	`,`	Examination for insurance purposes 	`,`	null	`],	
		[`	Z02.7	`,`	Issue of medical certificate Issue of medical certificate of: cause of death fitness incapacity invalidity Excl.: encounter for general medical examination (Z00-Z01, Z02.0-Z02.6, Z02.8-Z02.9, Z10.-) 	`,`	null	`],	
		[`	Z02.8	`,`	Other examinations for administrative purposes Examination (for): admission to: prison summer camp adoption immigration naturalization premarital Excl.: health supervision of foundling or other healthy infant or child (Z76.1-Z76.2) 	`,`	null	`],	
		[`	Z02.9	`,`	Examination for administrative purposes, unspecified 	`,`	null	`],	
		[`	Z03	`,`	Medical observation and evaluation for suspected diseases and conditions Incl.: persons who present some symptoms or evidence of an abnormal condition which requires study, but who, after examination and observation, show no need for further treatment or medical care Excl.: person with feared complaint in whom no diagnosis is made (Z71.1) 	`,`	null	`],	
		[`	Z03.0	`,`	Observation for suspected tuberculosis 	`,`	null	`],	
		[`	Z03.1	`,`	Observation for suspected malignant neoplasm 	`,`	null	`],	
		[`	Z03.2	`,`	Observation for suspected mental and behavioural disorders Observation for: dissocial behaviour fire-setting gang activity shop lifting without manifest psychiatric disorder 	`,`	null	`],	
		[`	Z03.3	`,`	Observation for suspected nervous system disorder 	`,`	null	`],	
		[`	Z03.4	`,`	Observation for suspected myocardial infarction 	`,`	null	`],	
		[`	Z03.5	`,`	Observation for other suspected cardiovascular diseases 	`,`	null	`],	
		[`	Z03.6	`,`	Observation for suspected toxic effect from ingested substance Observation for suspected: adverse effect from drug poisoning 	`,`	null	`],	
		[`	Z03.8	`,`	Observation for other suspected diseases and conditions 	`,`	null	`],	
		[`	Z03.9	`,`	Observation for suspected disease or condition, unspecified 	`,`	null	`],	
		[`	Z04	`,`	Examination and observation for other reasons Incl.: examination for medicolegal reasons 	`,`	null	`],	
		[`	Z04.0	`,`	Blood-alcohol and blood-drug test Excl.: presence of: alcohol in blood (R78.0) drugs in blood (R78.-) 	`,`	null	`],	
		[`	Z04.1	`,`	Examination and observation following transport accident Excl.: following work accident (Z04.2) 	`,`	null	`],	
		[`	Z04.2	`,`	Examination and observation following work accident 	`,`	null	`],	
		[`	Z04.3	`,`	Examination and observation following other accident 	`,`	null	`],	
		[`	Z04.4	`,`	Examination and observation following alleged rape and seduction Examination of victim or culprit following alleged rape or seduction 	`,`	null	`],	
		[`	Z04.5	`,`	Examination and observation following other inflicted injury Examination of victim or culprit following other inflicted injury 	`,`	null	`],	
		[`	Z04.6	`,`	General psychiatric examination, requested by authority 	`,`	null	`],	
		[`	Z04.8	`,`	Examination and observation for other specified reasons Request for expert evidence 	`,`	null	`],	
		[`	Z04.9	`,`	Examination and observation for unspecified reason Observation NOS 	`,`	null	`],	
		[`	Z08	`,`	Follow-up examination after treatment for malignant neoplasms Incl.: medical surveillance following treatment Excl.: follow-up medical care and convalescence (Z42-Z51, Z54.-) 	`,`	null	`],	
		[`	Z08.0	`,`	Follow-up examination after surgery for malignant neoplasm 	`,`	null	`],	
		[`	Z08.1	`,`	Follow-up examination after radiotherapy for malignant neoplasm Excl.: radiotherapy session (Z51.0) 	`,`	null	`],	
		[`	Z08.2	`,`	Follow-up examination after chemotherapy for malignant neoplasm Excl.: chemotherapy session (Z51.1) 	`,`	null	`],	
		[`	Z08.7	`,`	Follow-up examination after combined treatment for malignant neoplasm 	`,`	null	`],	
		[`	Z08.8	`,`	Follow-up examination after other treatment for malignant neoplasm 	`,`	null	`],	
		[`	Z08.9	`,`	Follow-up examination after unspecified treatment for malignant neoplasm 	`,`	null	`],	
		[`	Z09	`,`	Follow-up examination after treatment for conditions other than malignant neoplasms Incl.: medical surveillance following treatment Excl.: follow-up medical care and convalescence (Z42-Z51, Z54.-) medical surveillance following treatment for malignant neoplasms (Z08.-) surveillance of: contraception (Z30.4-Z30.5) prosthetic and other medical devices (Z44-Z46) 	`,`	null	`],	
		[`	Z09.0	`,`	Follow-up examination after surgery for other conditions 	`,`	null	`],	
		[`	Z09.1	`,`	Follow-up examination after radiotherapy for other conditions Excl.: radiotherapy session (Z51.0) 	`,`	null	`],	
		[`	Z09.2	`,`	Follow-up examination after chemotherapy for other conditions Excl.: maintenance chemotherapy (Z51.1-Z51.2) 	`,`	null	`],	
		[`	Z09.3	`,`	Follow-up examination after psychotherapy 	`,`	null	`],	
		[`	Z09.4	`,`	Follow-up examination after treatment of fracture 	`,`	null	`],	
		[`	Z09.7	`,`	Follow-up examination after combined treatment for other conditions 	`,`	null	`],	
		[`	Z09.8	`,`	Follow-up examination after other treatment for other conditions 	`,`	null	`],	
		[`	Z09.9	`,`	Follow-up examination after unspecified treatment for other conditions 	`,`	null	`],	
		[`	Z10	`,`	Routine general health check-up of defined subpopulation Excl.: medical examination for administrative purposes (Z02.-) 	`,`	null	`],	
		[`	Z10.0	`,`	Occupational health examination Excl.: pre-employment examination (Z02.1) 	`,`	null	`],	
		[`	Z10.1	`,`	Routine general health check-up of inhabitants of institutions Excl.: admission examination (Z02.2) 	`,`	null	`],	
		[`	Z10.2	`,`	Routine general health check-up of armed forces Excl.: recruitment examination (Z02.3) 	`,`	null	`],	
		[`	Z10.3	`,`	Routine general health check-up of sports teams Excl.: blood-alcohol and blood-drug test (Z04.0) examination for participation in sport (Z02.5) 	`,`	null	`],	
		[`	Z10.8	`,`	Routine general health check-up of other defined subpopulations Schoolchildren Students 	`,`	null	`],	
		[`	Z11	`,`	Special screening examination for infectious and parasitic diseases 	`,`	null	`],	
		[`	Z11.0	`,`	Special screening examination for intestinal infectious diseases 	`,`	null	`],	
		[`	Z11.1	`,`	Special screening examination for respiratory tuberculosis 	`,`	null	`],	
		[`	Z11.2	`,`	Special screening examination for other bacterial diseases 	`,`	null	`],	
		[`	Z11.3	`,`	Special screening examination for infections with a predominantly sexual mode of transmission 	`,`	null	`],	
		[`	Z11.4	`,`	Special screening examination for human immunodeficiency virus [HIV] 	`,`	null	`],	
		[`	Z11.5	`,`	Special screening examination for other viral diseases Excl.: viral intestinal disease (Z11.0) 	`,`	null	`],	
		[`	Z11.6	`,`	Special screening examination for other protozoal diseases and helminthiases Excl.: protozoal intestinal disease (Z11.0) 	`,`	null	`],	
		[`	Z11.8	`,`	Special screening examination for other infectious and parasitic diseases Chlamydial Rickettsial Spirochaetal diseases Mycoses 	`,`	null	`],	
		[`	Z11.9	`,`	Special screening examination for infectious and parasitic diseases, unspecified 	`,`	null	`],	
		[`	Z12	`,`	Special screening examination for neoplasms 	`,`	null	`],	
		[`	Z12.0	`,`	Special screening examination for neoplasm of stomach 	`,`	null	`],	
		[`	Z12.1	`,`	Special screening examination for neoplasm of intestinal tract 	`,`	null	`],	
		[`	Z12.2	`,`	Special screening examination for neoplasm of respiratory organs 	`,`	null	`],	
		[`	Z12.3	`,`	Special screening examination for neoplasm of breast Excl.: routine mammogram (Z01.6) 	`,`	null	`],	
		[`	Z12.4	`,`	Special screening examination for neoplasm of cervix Excl.: when routine test or as part of general gynaecological examination (Z01.4) 	`,`	null	`],	
		[`	Z12.5	`,`	Special screening examination for neoplasm of prostate 	`,`	null	`],	
		[`	Z12.6	`,`	Special screening examination for neoplasm of bladder 	`,`	null	`],	
		[`	Z12.8	`,`	Special screening examination for neoplasms of other sites 	`,`	null	`],	
		[`	Z12.9	`,`	Special screening examination for neoplasm, unspecified 	`,`	null	`],	
		[`	Z13	`,`	Special screening examination for other diseases and disorders 	`,`	null	`],	
		[`	Z13.0	`,`	Special screening examination for diseases of the blood and blood-forming organs and certain disorders involving the immune mechanism 	`,`	null	`],	
		[`	Z13.1	`,`	Special screening examination for diabetes mellitus 	`,`	null	`],	
		[`	Z13.2	`,`	Special screening examination for nutritional disorders 	`,`	null	`],	
		[`	Z13.3	`,`	Special screening examination for mental and behavioural disorders Alcoholism Depression Mental retardation 	`,`	null	`],	
		[`	Z13.4	`,`	Special screening examination for certain developmental disorders in childhood Excl.: routine development testing of infant or child (Z00.1) 	`,`	null	`],	
		[`	Z13.5	`,`	Special screening examination for eye and ear disorders 	`,`	null	`],	
		[`	Z13.6	`,`	Special screening examination for cardiovascular disorders 	`,`	null	`],	
		[`	Z13.7	`,`	Special screening examination for congenital malformations, deformations and chromosomal abnormalities 	`,`	null	`],	
		[`	Z13.8	`,`	Special screening examination for other specified diseases and disorders Dental disorder Endocrine and metabolic disorders Excl.: diabetes mellitus (Z13.1) 	`,`	null	`],	
		[`	Z13.9	`,`	Special screening examination, unspecified 	`,`	null	`],	
		[`	Z20	`,`	Contact with and exposure to communicable diseases 	`,`	null	`],	
		[`	Z20.0	`,`	Contact with and exposure to intestinal infectious diseases 	`,`	null	`],	
		[`	Z20.1	`,`	Contact with and exposure to tuberculosis 	`,`	null	`],	
		[`	Z20.2	`,`	Contact with and exposure to infections with a predominantly sexual mode of transmission 	`,`	null	`],	
		[`	Z20.3	`,`	Contact with and exposure to rabies 	`,`	null	`],	
		[`	Z20.4	`,`	Contact with and exposure to rubella 	`,`	null	`],	
		[`	Z20.5	`,`	Contact with and exposure to viral hepatitis 	`,`	null	`],	
		[`	Z20.6	`,`	Contact with and exposure to human immunodeficiency virus [HIV] 	`,`	null	`],	
		[`	Z20.7	`,`	Contact with and exposure to pediculosis, acariasis and other infestations 	`,`	null	`],	
		[`	Z20.8	`,`	Contact with and exposure to other communicable diseases 	`,`	null	`],	
		[`	Z20.9	`,`	Contact with and exposure to unspecified communicable disease 	`,`	null	`],	
		[`	Z21	`,`	Asymptomatic human immunodeficiency virus [HIV] infection status 	`,`	null	`],	
		[`	Z22	`,`	Carrier of infectious disease 	`,`	null	`],	
		[`	Z22.0	`,`	Carrier of typhoid 	`,`	null	`],	
		[`	Z22.1	`,`	Carrier of other intestinal infectious diseases 	`,`	null	`],	
		[`	Z22.2	`,`	Carrier of diphtheria 	`,`	null	`],	
		[`	Z22.3	`,`	Carrier of other specified bacterial diseases Carrier of bacterial disease due to: meningococci staphylococci streptococci 	`,`	null	`],	
		[`	Z22.4	`,`	Carrier of infections with a predominantly sexual mode of transmission Carrier of: gonorrhoea syphilis 	`,`	null	`],	
		[`	Z22.5	`,`	Carrier of viral hepatitis Hepatitis B surface antigen [HBsAg] carrier 	`,`	null	`],	
		[`	Z22.6	`,`	Carrier of human T-lymphotropic virus type- 1 [HTLV-1] infection 	`,`	null	`],	
		[`	Z22.8	`,`	Carrier of other infectious diseases 	`,`	null	`],	
		[`	Z22.9	`,`	Carrier of infectious disease, unspecified 	`,`	null	`],	
		[`	Z23	`,`	Need for immunization against single bacterial diseases 	`,`	null	`],	
		[`	Z23.0	`,`	Need for immunization against cholera alone 	`,`	null	`],	
		[`	Z23.1	`,`	Need for immunization against typhoid-paratyphoid alone [TAB] 	`,`	null	`],	
		[`	Z23.2	`,`	Need for immunization against tuberculosis [BCG] 	`,`	null	`],	
		[`	Z23.3	`,`	Need for immunization against plague 	`,`	null	`],	
		[`	Z23.4	`,`	Need for immunization against tularaemia 	`,`	null	`],	
		[`	Z23.5	`,`	Need for immunization against tetanus alone 	`,`	null	`],	
		[`	Z23.6	`,`	Need for immunization against diphtheria alone 	`,`	null	`],	
		[`	Z23.7	`,`	Need for immunization against pertussis alone 	`,`	null	`],	
		[`	Z23.8	`,`	Need for immunization against other single bacterial diseases 	`,`	null	`],	
		[`	Z24	`,`	Need for immunization against certain single viral diseases 	`,`	null	`],	
		[`	Z24.0	`,`	Need for immunization against poliomyelitis 	`,`	null	`],	
		[`	Z24.1	`,`	Need for immunization against arthropod-borne viral encephalitis 	`,`	null	`],	
		[`	Z24.2	`,`	Need for immunization against rabies 	`,`	null	`],	
		[`	Z24.3	`,`	Need for immunization against yellow fever 	`,`	null	`],	
		[`	Z24.4	`,`	Need for immunization against measles alone 	`,`	null	`],	
		[`	Z24.5	`,`	Need for immunization against rubella alone 	`,`	null	`],	
		[`	Z24.6	`,`	Need for immunization against viral hepatitis 	`,`	null	`],	
		[`	Z25	`,`	Need for immunization against other single viral diseases 	`,`	null	`],	
		[`	Z25.0	`,`	Need for immunization against mumps alone 	`,`	null	`],	
		[`	Z25.1	`,`	Need for immunization against influenza 	`,`	null	`],	
		[`	Z25.8	`,`	Need for immunization against other specified single viral diseases 	`,`	null	`],	
		[`	Z26	`,`	Need for immunization against other single infectious diseases 	`,`	null	`],	
		[`	Z26.0	`,`	Need for immunization against leishmaniasis 	`,`	null	`],	
		[`	Z26.8	`,`	Need for immunization against other specified single infectious diseases 	`,`	null	`],	
		[`	Z26.9	`,`	Need for immunization against unspecified infectious disease 	`,`	null	`],	
		[`	Z27	`,`	Need for immunization against combinations of infectious diseases 	`,`	null	`],	
		[`	Z27.0	`,`	Need for immunization against cholera with typhoid-paratyphoid [cholera + TAB] 	`,`	null	`],	
		[`	Z27.1	`,`	Need for immunization against diphtheria-tetanus-pertussis, combined [DTP] 	`,`	null	`],	
		[`	Z27.2	`,`	Need for immunization against diphtheria-tetanus-pertussis with typhoid-paratyphoid [DTP + TAB] 	`,`	null	`],	
		[`	Z27.3	`,`	Need for immunization against diphtheria-tetanus-pertussis with poliomyelitis [DTP + polio] 	`,`	null	`],	
		[`	Z27.4	`,`	Need for immunization against measles-mumps-rubella [MMR] 	`,`	null	`],	
		[`	Z27.8	`,`	Need for immunization against other combinations of infectious diseases 	`,`	null	`],	
		[`	Z27.9	`,`	Need for immunization against unspecified combinations of infectious diseases 	`,`	null	`],	
		[`	Z28	`,`	Immunization not carried out 	`,`	null	`],	
		[`	Z28.0	`,`	Immunization not carried out because of contraindication 	`,`	null	`],	
		[`	Z28.1	`,`	Immunization not carried out because of patient's decision for reasons of belief or group pressure 	`,`	null	`],	
		[`	Z28.2	`,`	Immunization not carried out because of patient's decision for other and unspecified reasons 	`,`	null	`],	
		[`	Z28.8	`,`	Immunization not carried out for other reasons 	`,`	null	`],	
		[`	Z28.9	`,`	Immunization not carried out for unspecified reason 	`,`	null	`],	
		[`	Z29	`,`	Need for other prophylactic measures 	`,`	null	`],	
		[`	Z29.0	`,`	Isolation Admission to protect the individual from his or her surroundings or for isolation of individual after contact with infectious disease 	`,`	null	`],	
		[`	Z29.1	`,`	Prophylactic immunotherapy Administration of immunoglobulin 	`,`	null	`],	
		[`	Z29.2	`,`	Other prophylactic chemotherapy Chemoprophylaxis Prophylactic antibiotic therapy 	`,`	null	`],	
		[`	Z29.8	`,`	Other specified prophylactic measures 	`,`	null	`],	
		[`	Z29.9	`,`	Prophylactic measure, unspecified 	`,`		`],	
		[`	Z30	`,`	Contraceptive management 	`,`	null	`],	
		[`	Z30.0	`,`	General counselling and advice on contraception 	`,`	null	`],	
		[`	Z30.1	`,`	Insertion of (intrauterine) contraceptive device 	`,`	null	`],	
		[`	Z30.2	`,`	Sterilization Admission for interruption of fallopian tubes or vasa deferentia 	`,`	null	`],	
		[`	Z30.3	`,`	Menstrual extraction 	`,`	null	`],	
		[`	Z30.4	`,`	Surveillance of contraceptive drugs 	`,`	null	`],	
		[`	Z30.5	`,`	Surveillance of (intrauterine) contraceptive device 	`,`	null	`],	
		[`	Z30.8	`,`	Other contraceptive management 	`,`	null	`],	
		[`	Z30.9	`,`	Contraceptive management, unspecified 	`,`	null	`],	
		[`	Z31	`,`	Procreative management 	`,`	null	`],	
		[`	Z31.0	`,`	Tuboplasty or vasoplasty after previous sterilization 	`,`	null	`],	
		[`	Z31.1	`,`	Artificial insemination 	`,`	null	`],	
		[`	Z31.2	`,`	In vitro fertilization 	`,`	null	`],	
		[`	Z31.3	`,`	Other assisted fertilization methods 	`,`	null	`],	
		[`	Z31.4	`,`	Procreative investigation and testing 	`,`	null	`],	
		[`	Z31.5	`,`	Genetic counselling 	`,`	null	`],	
		[`	Z31.6	`,`	General counselling and advice on procreation 	`,`	null	`],	
		[`	Z31.8	`,`	Other procreative management 	`,`	null	`],	
		[`	Z31.9	`,`	Procreative management, unspecified 	`,`	null	`],	
		[`	Z32	`,`	Pregnancy examination and test 	`,`	null	`],	
		[`	Z32.0	`,`	Pregnancy, not (yet) confirmed 	`,`	null	`],	
		[`	Z32.1	`,`	Pregnancy confirmed 	`,`	null	`],	
		[`	Z33	`,`	Pregnant state, incidental 	`,`	null	`],	
		[`	Z34	`,`	Supervision of normal pregnancy 	`,`	null	`],	
		[`	Z34.0	`,`	Supervision of normal first pregnancy 	`,`	null	`],	
		[`	Z34.8	`,`	Supervision of other normal pregnancy 	`,`	null	`],	
		[`	Z34.9	`,`	Supervision of normal pregnancy, unspecified 	`,`	null	`],	
		[`	Z35	`,`	Supervision of high-risk pregnancy 	`,`	null	`],	
		[`	Z35.0	`,`	Supervision of pregnancy with history of infertility 	`,`	null	`],	
		[`	Z35.1	`,`	Supervision of pregnancy with history of abortive outcome 	`,`	null	`],	
		[`	Z35.2	`,`	Supervision of pregnancy with other poor reproductive or obstetric history 	`,`	null	`],	
		[`	Z35.3	`,`	irth Supervision of pregnancy with history of insufficient antenatal care 	`,`	null	`],	
		[`	Z35.4	`,`	Supervision of pregnancy with grand multiparity 	`,`	null	`],	
		[`	Z35.5	`,`	Supervision of elderly primigravida 	`,`	null	`],	
		[`	Z35.6	`,`	Supervision of very young primigravida 	`,`	null	`],	
		[`	Z35.7	`,`	Supervision of high-risk pregnancy due to social problems 	`,`	null	`],	
		[`	Z35.8	`,`	Supervision of other high-risk pregnancies 	`,`	null	`],	
		[`	Z35.9	`,`	Supervision of high-risk pregnancy, unspecified 	`,`	null	`],	
		[`	Z36	`,`	Antenatal screening 	`,`	null	`],	
		[`	Z36.0	`,`	Antenatal screening for chromosomal anomalies 	`,`	null	`],	
		[`	Z36.1	`,`	Antenatal screening for raised alphafetoprotein level 	`,`	null	`],	
		[`	Z36.2	`,`	Other antenatal screening based on amniocentesis 	`,`	null	`],	
		[`	Z36.3	`,`	Antenatal screening for malformations using ultrasound and other physical methods 	`,`	null	`],	
		[`	Z36.4	`,`	Antenatal screening for fetal growth retardation using ultrasound and other physical methods 	`,`	null	`],	
		[`	Z36.5	`,`	Antenatal screening for isoimmunization 	`,`	null	`],	
		[`	Z36.8	`,`	Other antenatal screening 	`,`	null	`],	
		[`	Z36.9	`,`	Antenatal screening, unspecified 	`,`	null	`],	
		[`	Z37	`,`	Outcome of delivery 	`,`	null	`],	
		[`	Z37.0	`,`	Single live birth 	`,`	null	`],	
		[`	Z37.1	`,`	Single stillbirth 	`,`	null	`],	
		[`	Z37.2	`,`	Twins, both liveborn 	`,`	null	`],	
		[`	Z37.3	`,`	Twins, one liveborn and one stillborn 	`,`	null	`],	
		[`	Z37.4	`,`	Twins, both stillborn 	`,`	null	`],	
		[`	Z37.5	`,`	Other multiple births, all liveborn 	`,`	null	`],	
		[`	Z37.6	`,`	Other multiple births, some liveborn 	`,`	null	`],	
		[`	Z37.7	`,`	Other multiple births, all stillborn 	`,`	null	`],	
		[`	Z37.9	`,`	Outcome of delivery, unspecified 	`,`	null	`],	
		[`	Z38	`,`	Liveborn infants according to place of birth 	`,`	null	`],	
		[`	Z38.0	`,`	Singleton, born in hospital 	`,`	null	`],	
		[`	Z38.1	`,`	Singleton, born outside hospital 	`,`	null	`],	
		[`	Z38.2	`,`	Singleton, unspecified as to place of birth 	`,`	null	`],	
		[`	Z38.3	`,`	Twin, born in hospital 	`,`	null	`],	
		[`	Z38.4	`,`	Twin, born outside hospital 	`,`	null	`],	
		[`	Z38.5	`,`	Twin, unspecified as to place of birth 	`,`	null	`],	
		[`	Z38.6	`,`	Other multiple, born in hospital 	`,`	null	`],	
		[`	Z38.7	`,`	Other multiple, born outside hospital 	`,`	null	`],	
		[`	Z38.8	`,`	Other multiple, unspecified as to place of birth 	`,`	null	`],	
		[`	Z39	`,`	Postpartum care and examination 	`,`	null	`],	
		[`	Z39.0	`,`	Care and examination immediately after delivery 	`,`	null	`],	
		[`	Z39.1	`,`	Care and examination of lactating mother 	`,`	null	`],	
		[`	Z39.2	`,`	Routine postpartum follow-up 	`,`	null	`],	
		[`	Z40	`,`	Prophylactic surgery 	`,`	null	`],	
		[`	Z40.0	`,`	Prophylactic surgery for risk-factors related to malignant neoplasms 	`,`	null	`],	
		[`	Z40.8	`,`	Other prophylactic surgery 	`,`	null	`],	
		[`	Z40.9	`,`	Prophylactic surgery, unspecified 	`,`	null	`],	
		[`	Z41	`,`	Procedures for purposes other than remedying health state 	`,`	null	`],	
		[`	Z41.0	`,`	Hair transplant 	`,`	null	`],	
		[`	Z41.1	`,`	Other plastic surgery for unacceptable cosmetic appearance 	`,`	null	`],	
		[`	Z41.2	`,`	Routine and ritual circumcision 	`,`	null	`],	
		[`	Z41.3	`,`	Ear piercing 	`,`	null	`],	
		[`	Z41.8	`,`	Other procedures for purposes other than remedying health state 	`,`	null	`],	
		[`	Z41.9	`,`	Procedure for purposes other than remedying health state, unspecified 	`,`	null	`],	
		[`	Z42	`,`	Follow-up care involving plastic surgery 	`,`	null	`],	
		[`	Z42.0	`,`	Follow-up care involving plastic surgery of head and neck 	`,`	null	`],	
		[`	Z42.1	`,`	Follow-up care involving plastic surgery of breast 	`,`	null	`],	
		[`	Z42.2	`,`	Follow-up care involving plastic surgery of other parts of trunk 	`,`	null	`],	
		[`	Z42.3	`,`	Follow-up care involving plastic surgery of upper extremity 	`,`	null	`],	
		[`	Z42.4	`,`	Follow-up care involving plastic surgery of lower extremity 	`,`	null	`],	
		[`	Z42.8	`,`	Follow-up care involving plastic surgery of other body part 	`,`	null	`],	
		[`	Z42.9	`,`	Follow-up care involving plastic surgery, unspecified 	`,`	null	`],	
		[`	Z43	`,`	Attention to artificial openings 	`,`	null	`],	
		[`	Z43.0	`,`	Attention to tracheostomy 	`,`	null	`],	
		[`	Z43.1	`,`	Attention to gastrostomy 	`,`	null	`],	
		[`	Z43.2	`,`	Attention to ileostomy 	`,`	null	`],	
		[`	Z43.3	`,`	Attention to colostomy 	`,`	null	`],	
		[`	Z43.4	`,`	Attention to other artificial openings of digestive tract 	`,`	null	`],	
		[`	Z43.5	`,`	Attention to cystostomy 	`,`	null	`],	
		[`	Z43.6	`,`	Attention to other artificial openings of urinary tract 	`,`	null	`],	
		[`	Z43.7	`,`	Attention to artificial vagina 	`,`	null	`],	
		[`	Z43.8	`,`	Attention to other artificial openings 	`,`	null	`],	
		[`	Z43.9	`,`	Attention to unspecified artificial opening 	`,`	null	`],	
		[`	Z44	`,`	Fitting and adjustment of external prosthetic device 	`,`	null	`],	
		[`	Z44.0	`,`	Fitting and adjustment of artificial arm (complete)(partial) 	`,`	null	`],	
		[`	Z44.1	`,`	Fitting and adjustment of artificial leg (complete)(partial) 	`,`	null	`],	
		[`	Z44.2	`,`	Fitting and adjustment of artificial eye 	`,`	null	`],	
		[`	Z44.3	`,`	Fitting and adjustment of external breast prosthesis 	`,`	null	`],	
		[`	Z44.8	`,`	Fitting and adjustment of other external prosthetic devices 	`,`	null	`],	
		[`	Z44.9	`,`	Fitting and adjustment of unspecified external prosthetic device 	`,`	null	`],	
		[`	Z45	`,`	Adjustment and management of implanted device 	`,`	null	`],	
		[`	Z45.0	`,`	Adjustment and management of cardiac devices 	`,`	null	`],	
		[`	Z45.1	`,`	Adjustment and management of infusion pump 	`,`	null	`],	
		[`	Z45.2	`,`	Adjustment and management of vascular access device 	`,`	null	`],	
		[`	Z45.3	`,`	Adjustment and management of implanted hearing device 	`,`	null	`],	
		[`	Z45.8	`,`	Adjustment and management of other implanted devices 	`,`	null	`],	
		[`	Z45.9	`,`	Adjustment and management of unspecified implanted device 	`,`	null	`],	
		[`	Z46	`,`	Fitting and adjustment of other devices 	`,`	null	`],	
		[`	Z46.0	`,`	Fitting and adjustment of spectacles and contact lenses 	`,`	null	`],	
		[`	Z46.1	`,`	Fitting and adjustment of hearing aid 	`,`	null	`],	
		[`	Z46.2	`,`	Fitting and adjustment of other devices related to nervous system and special senses 	`,`	null	`],	
		[`	Z46.3	`,`	Fitting and adjustment of dental prosthetic device 	`,`	null	`],	
		[`	Z46.4	`,`	Fitting and adjustment of orthodontic device 	`,`	null	`],	
		[`	Z46.5	`,`	Fitting and adjustment of ileostomy and other intestinal appliances 	`,`	null	`],	
		[`	Z46.6	`,`	Fitting and adjustment of urinary device 	`,`	null	`],	
		[`	Z46.7	`,`	Fitting and adjustment of orthopaedic device 	`,`	null	`],	
		[`	Z46.8	`,`	Fitting and adjustment of other specified devices 	`,`	null	`],	
		[`	Z46.9	`,`	Fitting and adjustment of unspecified device 	`,`	null	`],	
		[`	Z47	`,`	Other orthopaedic follow-up care 	`,`	null	`],	
		[`	Z47.0	`,`	Follow-up care involving removal of fracture plate and other internal fixation device 	`,`	null	`],	
		[`	Z47.8	`,`	Other specified orthopaedic follow-up care 	`,`	null	`],	
		[`	Z47.9	`,`	Orthopaedic follow-up care, unspecified 	`,`	null	`],	
		[`	Z48	`,`	Other surgical follow-up care 	`,`	null	`],	
		[`	Z48.0	`,`	Attention to surgical dressings and sutures 	`,`	null	`],	
		[`	Z48.8	`,`	Other specified surgical follow-up care 	`,`	null	`],	
		[`	Z48.9	`,`	Surgical follow-up care, unspecified 	`,`	null	`],	
		[`	Z49	`,`	Care involving dialysis 	`,`	null	`],	
		[`	Z49.0	`,`	Preparatory care for dialysis 	`,`	null	`],	
		[`	Z49.1	`,`	Extracorporeal dialysis 	`,`	null	`],	
		[`	Z49.2	`,`	Other dialysis 	`,`	null	`],	
		[`	Z50	`,`	Care involving use of rehabilitation procedures 	`,`	null	`],	
		[`	Z50.0	`,`	Cardiac rehabilitation 	`,`	null	`],	
		[`	Z50.1	`,`	Other physical therapy 	`,`	null	`],	
		[`	Z50.2	`,`	Alcohol rehabilitation 	`,`	null	`],	
		[`	Z50.3	`,`	Drug rehabilitation 	`,`	null	`],	
		[`	Z50.4	`,`	Psychotherapy, not elsewhere classified 	`,`	null	`],	
		[`	Z50.5	`,`	Speech therapy 	`,`	null	`],	
		[`	Z50.6	`,`	Orthoptic training 	`,`	null	`],	
		[`	Z50.7	`,`	Occupational therapy and vocational rehabilitation, not elsewhere classified 	`,`	null	`],	
		[`	Z50.8	`,`	Care involving use of other rehabilitation procedures 	`,`	null	`],	
		[`	Z50.9	`,`	Care involving use of rehabilitation procedure, unspecified 	`,`	null	`],	
		[`	Z51	`,`	Other medical care 	`,`	null	`],	
		[`	Z51.0	`,`	Radiotherapy session 	`,`	null	`],	
		[`	Z51.1	`,`	Chemotherapy session for neoplasm 	`,`	null	`],	
		[`	Z51.2	`,`	Other chemotherapy 	`,`	null	`],	
		[`	Z51.3	`,`	Blood transfusion (without reported diagnosis) 	`,`	null	`],	
		[`	Z51.4	`,`	Preparatory care for subsequent treatment, not elsewhere classified 	`,`	null	`],	
		[`	Z51.5	`,`	Palliative care 	`,`	null	`],	
		[`	Z51.6	`,`	Desensitization to allergens 	`,`	null	`],	
		[`	Z51.8	`,`	Other specified medical care 	`,`	null	`],	
		[`	Z51.9	`,`	Medical care, unspecified 	`,`	null	`],	
		[`	Z52	`,`	Donors of organs and tissues 	`,`	null	`],	
		[`	Z52.0	`,`	Blood donor 	`,`	null	`],	
		[`	Z52.1	`,`	Skin donor 	`,`	null	`],	
		[`	Z52.2	`,`	Bone donor 	`,`	null	`],	
		[`	Z52.3	`,`	Bone marrow donor 	`,`	null	`],	
		[`	Z52.4	`,`	Kidney donor 	`,`	null	`],	
		[`	Z52.5	`,`	Cornea donor 	`,`	null	`],	
		[`	Z52.6	`,`	Liver donor 	`,`	null	`],	
		[`	Z52.7	`,`	Heart donor 	`,`	null	`],	
		[`	Z52.8	`,`	Donor of other organs and tissues 	`,`	null	`],	
		[`	Z52.9	`,`	Donor of unspecified organ or tissue 	`,`	null	`],	
		[`	Z53	`,`	Persons encountering health services for specific procedures, not carried out 	`,`	null	`],	
		[`	Z53.0	`,`	Procedure not carried out because of contraindication 	`,`	null	`],	
		[`	Z53.1	`,`	Procedure not carried out because of patient's decision for reasons of belief and group pressure 	`,`	null	`],	
		[`	Z53.2	`,`	Procedure not carried out because of patient's decision for other and unspecified reasons 	`,`	null	`],	
		[`	Z53.8	`,`	Procedure not carried out for other reasons 	`,`	null	`],	
		[`	Z53.9	`,`	Procedure not carried out, unspecified reason 	`,`	null	`],	
		[`	Z54	`,`	Convalescence 	`,`	null	`],	
		[`	Z54.0	`,`	Convalescence following surgery 	`,`	null	`],	
		[`	Z54.1	`,`	Convalescence following radiotherapy 	`,`	null	`],	
		[`	Z54.2	`,`	Convalescence following chemotherapy 	`,`	null	`],	
		[`	Z54.3	`,`	Convalescence following psychotherapy 	`,`	null	`],	
		[`	Z54.4	`,`	Convalescence following treatment of fracture 	`,`	null	`],	
		[`	Z54.7	`,`	Convalescence following combined treatment 	`,`	null	`],	
		[`	Z54.8	`,`	Convalescence following other treatment 	`,`	null	`],	
		[`	Z54.9	`,`	Convalescence following unspecified treatment 	`,`	null	`],	
		[`	Z55	`,`	Problems related to education and literacy 	`,`	null	`],	
		[`	Z55.0	`,`	Illiteracy and low-level literacy 	`,`	null	`],	
		[`	Z55.1	`,`	Schooling unavailable and unattainable 	`,`	null	`],	
		[`	Z55.2	`,`	Failed examinations 	`,`	null	`],	
		[`	Z55.3	`,`	Underachievement in school 	`,`	null	`],	
		[`	Z55.4	`,`	Educational maladjustment and discord with teachers and classmates 	`,`	null	`],	
		[`	Z55.8	`,`	Other problems related to education and literacy 	`,`	null	`],	
		[`	Z55.9	`,`	Problem related to education and literacy, unspecified 	`,`	null	`],	
		[`	Z56	`,`	Problems related to employment and unemployment 	`,`	null	`],	
		[`	Z56.0	`,`	Unemployment, unspecified 	`,`	null	`],	
		[`	Z56.1	`,`	Change of job 	`,`	null	`],	
		[`	Z56.2	`,`	Threat of job loss 	`,`	null	`],	
		[`	Z56.3	`,`	Stressful work schedule 	`,`	null	`],	
		[`	Z56.4	`,`	Discord with boss and workmates 	`,`	null	`],	
		[`	Z56.5	`,`	Uncongenial work 	`,`	null	`],	
		[`	Z56.6	`,`	Other physical and mental strain related to work 	`,`	null	`],	
		[`	Z56.7	`,`	Other and unspecified problems related to employment 	`,`	null	`],	
		[`	Z57	`,`	Occupational exposure to risk-factors 	`,`	null	`],	
		[`	Z57.0	`,`	Occupational exposure to noise 	`,`	null	`],	
		[`	Z57.1	`,`	Occupational exposure to radiation 	`,`	null	`],	
		[`	Z57.2	`,`	Occupational exposure to dust 	`,`	null	`],	
		[`	Z57.3	`,`	Occupational exposure to other air contaminants 	`,`	null	`],	
		[`	Z57.4	`,`	Occupational exposure to toxic agents in agriculture 	`,`	null	`],	
		[`	Z57.5	`,`	Occupational exposure to toxic agents in other industries 	`,`	null	`],	
		[`	Z57.6	`,`	Occupational exposure to extreme temperature 	`,`	null	`],	
		[`	Z57.7	`,`	Occupational exposure to vibration 	`,`	null	`],	
		[`	Z57.8	`,`	Occupational exposure to other risk-factors 	`,`	null	`],	
		[`	Z57.9	`,`	Occupational exposure to unspecified risk-factor 	`,`	null	`],	
		[`	Z58	`,`	Problems related to physical environment 	`,`	null	`],	
		[`	Z58.0	`,`	Exposure to noise 	`,`	null	`],	
		[`	Z58.1	`,`	Exposure to air pollution 	`,`	null	`],	
		[`	Z58.2	`,`	Exposure to water pollution 	`,`	null	`],	
		[`	Z58.3	`,`	Exposure to soil pollution 	`,`	null	`],	
		[`	Z58.4	`,`	Exposure to radiation 	`,`	null	`],	
		[`	Z58.5	`,`	Exposure to other pollution 	`,`	null	`],	
		[`	Z58.6	`,`	Inadequate drinking-water supply 	`,`	null	`],	
		[`	Z58.7	`,`	Exposure to tobacco smoke 	`,`	null	`],	
		[`	Z58.8	`,`	Other problems related to physical environment 	`,`	null	`],	
		[`	Z58.9	`,`	Problem related to physical environment, unspecified 	`,`	null	`],	
		[`	Z59	`,`	Problems related to housing and economic circumstances 	`,`	null	`],	
		[`	Z59.0	`,`	Homelessness 	`,`	null	`],	
		[`	Z59.1	`,`	Inadequate housing 	`,`	null	`],	
		[`	Z59.2	`,`	Discord with neighbours, lodgers and landlord 	`,`	null	`],	
		[`	Z59.3	`,`	Problems related to living in residential institution 	`,`	null	`],	
		[`	Z59.4	`,`	Lack of adequate food 	`,`	null	`],	
		[`	Z59.5	`,`	Extreme poverty 	`,`	null	`],	
		[`	Z59.6	`,`	Low income 	`,`	null	`],	
		[`	Z59.7	`,`	Insufficient social insurance and welfare support 	`,`	null	`],	
		[`	Z59.8	`,`	Other problems related to housing and economic circumstances 	`,`	null	`],	
		[`	Z59.9	`,`	Problem related to housing and economic circumstances, unspecified 	`,`	null	`],	
		[`	Z60	`,`	Problems related to social environment 	`,`	null	`],	
		[`	Z60.0	`,`	Problems of adjustment to life-cycle transitions 	`,`	null	`],	
		[`	Z60.1	`,`	Atypical parenting situation 	`,`	null	`],	
		[`	Z60.2	`,`	Living alone 	`,`	null	`],	
		[`	Z60.3	`,`	Acculturation difficulty 	`,`	null	`],	
		[`	Z60.4	`,`	Social exclusion and rejection 	`,`	null	`],	
		[`	Z60.5	`,`	Target of perceived adverse discrimination and persecution 	`,`	null	`],	
		[`	Z60.8	`,`	Other problems related to social environment 	`,`	null	`],	
		[`	Z60.9	`,`	Problem related to social environment, unspecified 	`,`	null	`],	
		[`	Z61	`,`	Problems related to negative life events in childhood 	`,`	null	`],	
		[`	Z61.0	`,`	Loss of love relationship in childhood 	`,`	null	`],	
		[`	Z61.1	`,`	Removal from home in childhood 	`,`	null	`],	
		[`	Z61.2	`,`	Altered pattern of family relationships in childhood 	`,`	null	`],	
		[`	Z61.3	`,`	Events resulting in loss of self-esteem in childhood 	`,`	null	`],	
		[`	Z61.4	`,`	Problems related to alleged sexual abuse of child by person within primary support group 	`,`	null	`],	
		[`	Z61.5	`,`	Problems related to alleged sexual abuse of child by person outside primary support group 	`,`	null	`],	
		[`	Z61.6	`,`	Problems related to alleged physical abuse of child 	`,`	null	`],	
		[`	Z61.7	`,`	Personal frightening experience in childhood 	`,`	null	`],	
		[`	Z61.8	`,`	Other negative life events in childhood 	`,`	null	`],	
		[`	Z61.9	`,`	Negative life event in childhood, unspecified 	`,`	null	`],	
		[`	Z62	`,`	Other problems related to upbringing 	`,`	null	`],	
		[`	Z62.0	`,`	Inadequate parental supervision and control 	`,`	null	`],	
		[`	Z62.1	`,`	Parental overprotection 	`,`	null	`],	
		[`	Z62.2	`,`	Institutional upbringing 	`,`	null	`],	
		[`	Z62.3	`,`	Hostility towards and scapegoating of child 	`,`	null	`],	
		[`	Z62.4	`,`	Emotional neglect of child 	`,`	null	`],	
		[`	Z62.5	`,`	Other problems related to neglect in upbringing 	`,`	null	`],	
		[`	Z62.6	`,`	Inappropriate parental pressure and other abnormal qualities of upbringing 	`,`	null	`],	
		[`	Z62.8	`,`	Other specified problems related to upbringing 	`,`	null	`],	
		[`	Z62.9	`,`	Problem related to upbringing, unspecified 	`,`	null	`],	
		[`	Z63	`,`	Other problems related to primary support group, including family circumstances 	`,`	null	`],	
		[`	Z63.0	`,`	Problems in relationship with spouse or partner 	`,`	null	`],	
		[`	Z63.1	`,`	Problems in relationship with parents and in-laws 	`,`	null	`],	
		[`	Z63.2	`,`	Inadequate family support 	`,`	null	`],	
		[`	Z63.3	`,`	Absence of family member 	`,`	null	`],	
		[`	Z63.4	`,`	Disappearance and death of family member 	`,`	null	`],	
		[`	Z63.5	`,`	Disruption of family by separation and divorce 	`,`	null	`],	
		[`	Z63.6	`,`	Dependent relative needing care at home 	`,`	null	`],	
		[`	Z63.7	`,`	Other stressful life events affecting family and household 	`,`	null	`],	
		[`	Z63.8	`,`	Other specified problems related to primary support group 	`,`	null	`],	
		[`	Z63.9	`,`	Problem related to primary support group, unspecified 	`,`	null	`],	
		[`	Z64	`,`	Problems related to certain psychosocial circumstances 	`,`	null	`],	
		[`	Z64.0	`,`	Problems related to unwanted pregnancy 	`,`	null	`],	
		[`	Z64.1	`,`	Problems related to multiparity 	`,`	null	`],	
		[`	Z64.2	`,`	Seeking and accepting physical, nutritional and chemical interventions known to be hazardous and harmful 	`,`	null	`],	
		[`	Z64.3	`,`	Seeking and accepting behavioural and psychological interventions known to be hazardous and harmful 	`,`	null	`],	
		[`	Z64.4	`,`	Discord with counsellors 	`,`	null	`],	
		[`	Z65	`,`	Problems related to other psychosocial circumstances 	`,`	null	`],	
		[`	Z65.0	`,`	Conviction in civil and criminal proceedings without imprisonment 	`,`	null	`],	
		[`	Z65.1	`,`	Imprisonment and other incarceration 	`,`	null	`],	
		[`	Z65.2	`,`	Problems related to release from prison 	`,`	null	`],	
		[`	Z65.3	`,`	Problems related to other legal circumstances 	`,`	null	`],	
		[`	Z65.4	`,`	Victim of crime and terrorism 	`,`	null	`],	
		[`	Z65.5	`,`	Exposure to disaster, war and other hostilities 	`,`	null	`],	
		[`	Z65.8	`,`	Other specified problems related to psychosocial circumstances 	`,`	null	`],	
		[`	Z65.9	`,`	Problem related to unspecified psychosocial circumstances 	`,`	null	`],	
		[`	Z70	`,`	Counselling related to sexual attitude, behaviour and orientation 	`,`	null	`],	
		[`	Z70.0	`,`	Counselling related to sexual attitude 	`,`	null	`],	
		[`	Z70.1	`,`	Counselling related to patient's sexual behaviour and orientation 	`,`	null	`],	
		[`	Z70.2	`,`	Counselling related to sexual behaviour and orientation of third party 	`,`	null	`],	
		[`	Z70.3	`,`	Counselling related to combined concerns regarding sexual attitude, behaviour and orientation 	`,`	null	`],	
		[`	Z70.8	`,`	Other sex counselling 	`,`	null	`],	
		[`	Z70.9	`,`	Sex counselling, unspecified 	`,`	null	`],	
		[`	Z71	`,`	Persons encountering health services for other counselling and medical advice, not elsewhere classified 	`,`	null	`],	
		[`	Z71.0	`,`	Person consulting on behalf of another person 	`,`	null	`],	
		[`	Z71.1	`,`	Person with feared complaint in whom no diagnosis is made 	`,`	null	`],	
		[`	Z71.2	`,`	Person consulting for explanation of investigation findings 	`,`	null	`],	
		[`	Z71.3	`,`	Dietary counselling and surveillance 	`,`	null	`],	
		[`	Z71.4	`,`	Alcohol abuse counselling and surveillance 	`,`	null	`],	
		[`	Z71.5	`,`	Drug abuse counselling and surveillance 	`,`	null	`],	
		[`	Z71.6	`,`	Tobacco abuse counselling 	`,`	null	`],	
		[`	Z71.7	`,`	Human immunodeficiency virus [HIV] counselling 	`,`	null	`],	
		[`	Z71.8	`,`	Other specified counselling 	`,`	null	`],	
		[`	Z71.9	`,`	Counselling, unspecified 	`,`	null	`],	
		[`	Z72	`,`	Problems related to lifestyle 	`,`	null	`],	
		[`	Z72.0	`,`	Tobacco use 	`,`	null	`],	
		[`	Z72.1	`,`	Alcohol use 	`,`	null	`],	
		[`	Z72.2	`,`	Drug use 	`,`	null	`],	
		[`	Z72.3	`,`	Lack of physical exercise 	`,`	null	`],	
		[`	Z72.4	`,`	Inappropriate diet and eating habits 	`,`	null	`],	
		[`	Z72.5	`,`	High-risk sexual behaviour 	`,`	null	`],	
		[`	Z72.6	`,`	Gambling and betting 	`,`	null	`],	
		[`	Z72.8	`,`	Other problems related to lifestyle 	`,`	null	`],	
		[`	Z72.9	`,`	Problem related to lifestyle, unspecified 	`,`	null	`],	
		[`	Z73	`,`	Problems related to life-management difficulty 	`,`	null	`],	
		[`	Z73.0	`,`	Burn-out 	`,`	null	`],	
		[`	Z73.1	`,`	Accentuation of personality traits 	`,`	null	`],	
		[`	Z73.2	`,`	Lack of relaxation and leisure 	`,`	null	`],	
		[`	Z73.3	`,`	Stress, not elsewhere classified 	`,`	null	`],	
		[`	Z73.4	`,`	Inadequate social skills, not elsewhere classified 	`,`	null	`],	
		[`	Z73.5	`,`	Social role conflict, not elsewhere classified 	`,`	null	`],	
		[`	Z73.6	`,`	Limitation of activities due to disability 	`,`	null	`],	
		[`	Z73.8	`,`	Other problems related to life-management difficulty 	`,`	null	`],	
		[`	Z73.9	`,`	Problem related to life-management difficulty, unspecified 	`,`	null	`],	
		[`	Z74	`,`	Problems related to care-provider dependency 	`,`	null	`],	
		[`	Z74.0	`,`	Need for assistance due to reduced mobility 	`,`	null	`],	
		[`	Z74.1	`,`	Need for assistance with personal care 	`,`	null	`],	
		[`	Z74.2	`,`	Need for assistance at home and no other household member able to render care 	`,`	null	`],	
		[`	Z74.3	`,`	Need for continuous supervision 	`,`	null	`],	
		[`	Z74.8	`,`	Other problems related to care-provider dependency 	`,`	null	`],	
		[`	Z74.9	`,`	Problem related to care-provider dependency, unspecified 	`,`	null	`],	
		[`	Z75	`,`	Problems related to medical facilities and other health care 	`,`	null	`],	
		[`	Z75.0	`,`	Medical services not available in home 	`,`	null	`],	
		[`	Z75.1	`,`	Person awaiting admission to adequate facility elsewhere 	`,`	null	`],	
		[`	Z75.2	`,`	Other waiting period for investigation and treatment 	`,`	null	`],	
		[`	Z75.3	`,`	Unavailability and inaccessibility of health-care facilities 	`,`	null	`],	
		[`	Z75.4	`,`	Unavailability and inaccessibility of other helping agencies 	`,`	null	`],	
		[`	Z75.5	`,`	Holiday relief care 	`,`	null	`],	
		[`	Z75.8	`,`	Other problems related to medical facilities and other health care 	`,`	null	`],	
		[`	Z75.9	`,`	Unspecified problem related to medical facilities and other health care 	`,`	null	`],	
		[`	Z76	`,`	Persons encountering health services in other circumstances 	`,`	null	`],	
		[`	Z76.0	`,`	Issue of repeat prescription 	`,`	null	`],	
		[`	Z76.1	`,`	Health supervision and care of foundling 	`,`	null	`],	
		[`	Z76.2	`,`	Health supervision and care of other healthy infant and child 	`,`	null	`],	
		[`	Z76.3	`,`	Healthy person accompanying sick person 	`,`	null	`],	
		[`	Z76.4	`,`	Other boarder in health-care facility 	`,`	null	`],	
		[`	Z76.5	`,`	Malingerer [conscious simulation] 	`,`	null	`],	
		[`	Z76.8	`,`	Persons encountering health services in other specified circumstances 	`,`	null	`],	
		[`	Z76.9	`,`	Person encountering health services in unspecified circumstances 	`,`	null	`],	
		[`	Z80	`,`	Family history of malignant neoplasm 	`,`	null	`],	
		[`	Z80.0	`,`	Family history of malignant neoplasm of digestive organs 	`,`	null	`],	
		[`	Z80.1	`,`	Family history of malignant neoplasm of trachea, bronchus and lung 	`,`	null	`],	
		[`	Z80.2	`,`	Family history of malignant neoplasm of other respiratory and intrathoracic organs 	`,`	null	`],	
		[`	Z80.3	`,`	Family history of malignant neoplasm of breast 	`,`	null	`],	
		[`	Z80.4	`,`	Family history of malignant neoplasm of genital organs 	`,`	null	`],	
		[`	Z80.5	`,`	Family history of malignant neoplasm of urinary tract 	`,`	null	`],	
		[`	Z80.6	`,`	Family history of leukaemia 	`,`	null	`],	
		[`	Z80.7	`,`	Family history of other malignant neoplasms of lymphoid, haematopoietic and related tissues 	`,`	null	`],	
		[`	Z80.8	`,`	Family history of malignant neoplasm of other organs or systems 	`,`	null	`],	
		[`	Z80.9	`,`	Family history of malignant neoplasm, unspecified 	`,`	null	`],	
		[`	Z81	`,`	Family history of mental and behavioural disorders 	`,`	null	`],	
		[`	Z81.0	`,`	Family history of mental retardation 	`,`	null	`],	
		[`	Z81.1	`,`	Family history of alcohol abuse 	`,`	null	`],	
		[`	Z81.2	`,`	Family history of tobacco abuse 	`,`	null	`],	
		[`	Z81.3	`,`	Family history of other psychoactive substance abuse 	`,`	null	`],	
		[`	Z81.4	`,`	Family history of other substance abuse 	`,`	null	`],	
		[`	Z81.8	`,`	Family history of other mental and behavioural disorders 	`,`	null	`],	
		[`	Z82	`,`	Family history of certain disabilities and chronic diseases leading to disablement 	`,`	null	`],	
		[`	Z82.0	`,`	Family history of epilepsy and other diseases of the nervous system 	`,`	null	`],	
		[`	Z82.1	`,`	Family history of blindness and visual loss 	`,`	null	`],	
		[`	Z82.2	`,`	Family history of deafness and hearing loss 	`,`	null	`],	
		[`	Z82.3	`,`	Family history of stroke 	`,`	null	`],	
		[`	Z82.4	`,`	Family history of ischaemic heart disease and other diseases of the circulatory system 	`,`	null	`],	
		[`	Z82.5	`,`	Family history of asthma and other chronic lower respiratory diseases 	`,`	null	`],	
		[`	Z82.6	`,`	Family history of arthritis and other diseases of the musculoskeletal system and connective tissue 	`,`	null	`],	
		[`	Z82.7	`,`	Family history of congenital malformations, deformations and chromosomal abnormalities 	`,`	null	`],	
		[`	Z82.8	`,`	Family history of other disabilities and chronic diseases leading to disablement, not elsewhere classified 	`,`	null	`],	
		[`	Z83	`,`	Family history of other specific disorders 	`,`	null	`],	
		[`	Z83.0	`,`	Family history of human immunodeficiency virus [HIV] disease 	`,`	null	`],	
		[`	Z83.1	`,`	Family history of other infectious and parasitic diseases 	`,`	null	`],	
		[`	Z83.2	`,`	Family history of diseases of the blood and blood-forming organs and certain disorders involving the immune mechanism 	`,`	null	`],	
		[`	Z83.3	`,`	Family history of diabetes mellitus 	`,`	null	`],	
		[`	Z83.4	`,`	Family history of other endocrine, nutritional and metabolic diseases 	`,`	null	`],	
		[`	Z83.5	`,`	Family history of eye and ear disorders 	`,`	null	`],	
		[`	Z83.6	`,`	Family history of diseases of the respiratory system 	`,`	null	`],	
		[`	Z83.7	`,`	Family history of diseases of the digestive system 	`,`	null	`],	
		[`	Z84	`,`	Family history of other conditions 	`,`	null	`],	
		[`	Z84.0	`,`	Family history of diseases of the skin and subcutaneous tissue 	`,`	null	`],	
		[`	Z84.1	`,`	Family history of disorders of kidney and ureter 	`,`	null	`],	
		[`	Z84.2	`,`	Family history of other diseases of the genitourinary system 	`,`	null	`],	
		[`	Z84.3	`,`	Family history of consanguinity 	`,`	null	`],	
		[`	Z84.8	`,`	Family history of other specified conditions 	`,`	null	`],	
		[`	Z85	`,`	Personal history of malignant neoplasm 	`,`	null	`],	
		[`	Z85.0	`,`	Personal history of malignant neoplasm of digestive organs 	`,`	null	`],	
		[`	Z85.1	`,`	Personal history of malignant neoplasm of trachea, bronchus and lung 	`,`	null	`],	
		[`	Z85.2	`,`	Personal history of malignant neoplasm of other respiratory and intrathoracic organs 	`,`	null	`],	
		[`	Z85.3	`,`	Personal history of malignant neoplasm of breast 	`,`	null	`],	
		[`	Z85.4	`,`	Personal history of malignant neoplasm of genital organs 	`,`	null	`],	
		[`	Z85.5	`,`	Personal history of malignant neoplasm of urinary tract 	`,`	null	`],	
		[`	Z85.6	`,`	Personal history of leukaemia 	`,`	null	`],	
		[`	Z85.7	`,`	Personal history of other malignant neoplasms of lymphoid, haematopoietic and related tissues 	`,`	null	`],	
		[`	Z85.8	`,`	Personal history of malignant neoplasms of other organs and systems 	`,`	null	`],	
		[`	Z85.9	`,`	Personal history of malignant neoplasm, unspecified 	`,`	null	`],	
		[`	Z86	`,`	Personal history of certain other diseases 	`,`	null	`],	
		[`	Z86.0	`,`	Personal history of other neoplasms 	`,`	null	`],	
		[`	Z86.1	`,`	Personal history of infectious and parasitic diseases 	`,`	null	`],	
		[`	Z86.2	`,`	Personal history of diseases of the blood and blood-forming organs and certain disorders involving the immune mechanism 	`,`	null	`],	
		[`	Z86.3	`,`	Personal history of endocrine, nutritional and metabolic diseases 	`,`	null	`],	
		[`	Z86.4	`,`	Personal history of psychoactive substance abuse 	`,`	null	`],	
		[`	Z86.5	`,`	Personal history of other mental and behavioural disorders 	`,`	null	`],	
		[`	Z86.6	`,`	Personal history of diseases of the nervous system and sense organs 	`,`	null	`],	
		[`	Z86.7	`,`	Personal history of diseases of the circulatory system 	`,`	null	`],	
		[`	Z87	`,`	Z87 Personal history of other diseases and conditions 	`,`	null	`],	
		[`	Z87.0	`,`	Personal history of diseases of the respiratory system 	`,`	null	`],	
		[`	Z87.1	`,`	Personal history of diseases of the digestive system 	`,`	null	`],	
		[`	Z87.2	`,`	Personal history of diseases of the skin and subcutaneous tissue 	`,`	null	`],	
		[`	Z87.3	`,`	Personal history of diseases of the musculoskeletal system and connective tissue 	`,`	null	`],	
		[`	Z87.4	`,`	Personal history of diseases of the genitourinary system 	`,`	null	`],	
		[`	Z87.5	`,`	Personal history of complications of pregnancy, childbirth and the puerperium 	`,`	null	`],	
		[`	Z87.6	`,`	Personal history of certain conditions arising in the perinatal period 	`,`	null	`],	
		[`	Z87.7	`,`	Personal history of congenital malformations, deformations and chromosomal abnormalities 	`,`	null	`],	
		[`	Z87.8	`,`	Personal history of other specified conditions 	`,`	null	`],	
		[`	Z88	`,`	Personal history of allergy to drugs, medicaments and biological substances 	`,`	null	`],	
		[`	Z88.0	`,`	Personal history of allergy to penicillin 	`,`	null	`],	
		[`	Z88.1	`,`	Personal history of allergy to other antibiotic agents 	`,`	null	`],	
		[`	Z88.2	`,`	Personal history of allergy to sulfonamides 	`,`	null	`],	
		[`	Z88.3	`,`	Personal history of allergy to other anti-infective agents 	`,`	null	`],	
		[`	Z88.4	`,`	Personal history of allergy to anaesthetic agent 	`,`	null	`],	
		[`	Z88.5	`,`	Personal history of allergy to narcotic agent 	`,`	null	`],	
		[`	Z88.6	`,`	Personal history of allergy to analgesic agent 	`,`	null	`],	
		[`	Z88.7	`,`	Personal history of allergy to serum and vaccine 	`,`	null	`],	
		[`	Z88.8	`,`	Personal history of allergy to other drugs, medicaments and biological substances 	`,`	null	`],	
		[`	Z88.9	`,`	Personal history of allergy to unspecified drugs, medicaments and biological substances 	`,`	null	`],	
		[`	Z89	`,`	Acquired absence of limb 	`,`	null	`],	
		[`	Z89.0	`,`	Acquired absence of finger(s) [including thumb], unilateral 	`,`	null	`],	
		[`	Z89.1	`,`	Acquired absence of hand and wrist 	`,`	null	`],	
		[`	Z89.2	`,`	Acquired absence of upper limb above wrist 	`,`	null	`],	
		[`	Z89.3	`,`	Acquired absence of both upper limbs [any level] 	`,`	null	`],	
		[`	Z89.4	`,`	Acquired absence of foot and ankle 	`,`	null	`],	
		[`	Z89.5	`,`	Acquired absence of leg at or below knee 	`,`	null	`],	
		[`	Z89.6	`,`	Acquired absence of leg above knee 	`,`	null	`],	
		[`	Z89.7	`,`	Acquired absence of both lower limbs [any level, except toes alone] 	`,`	null	`],	
		[`	Z89.8	`,`	Acquired absence of upper and lower limbs [any level] 	`,`	null	`],	
		[`	Z89.9	`,`	Acquired absence of limb, unspecified 	`,`	null	`],	
		[`	Z90	`,`	Acquired absence of organs, not elsewhere classified 	`,`	null	`],	
		[`	Z90.0	`,`	Acquired absence of part of head and neck 	`,`	null	`],	
		[`	Z90.1	`,`	Acquired absence of breast(s) 	`,`	null	`],	
		[`	Z90.2	`,`	Acquired absence of lung [part of] 	`,`	null	`],	
		[`	Z90.3	`,`	Acquired absence of part of stomach 	`,`	null	`],	
		[`	Z90.4	`,`	Acquired absence of other parts of digestive tract 	`,`	null	`],	
		[`	Z90.5	`,`	Acquired absence of kidney 	`,`	null	`],	
		[`	Z90.6	`,`	Acquired absence of other organs of urinary tract 	`,`	null	`],	
		[`	Z90.7	`,`	Acquired absence of genital organ(s) 	`,`	null	`],	
		[`	Z90.8	`,`	Acquired absence of other organs 	`,`	null	`],	
		[`	Z91	`,`	Personal history of risk-factors, not elsewhere classified 	`,`	null	`],	
		[`	Z91.0	`,`	Personal history of allergy, other than to drugs and biological substances 	`,`	null	`],	
		[`	Z91.1	`,`	Personal history of noncompliance with medical treatment and regimen 	`,`	null	`],	
		[`	Z91.2	`,`	Personal history of poor personal hygiene 	`,`	null	`],	
		[`	Z91.3	`,`	Personal history of unhealthy sleep-wake schedule 	`,`	null	`],	
		[`	Z91.4	`,`	Personal history of psychological trauma, not elsewhere classified 	`,`	null	`],	
		[`	Z91.5	`,`	Personal history of self-harm 	`,`	null	`],	
		[`	Z91.6	`,`	Personal history of other physical trauma 	`,`	null	`],	
		[`	Z91.8	`,`	Personal history of other specified risk-factors, not elsewhere classified 	`,`	null	`],	
		[`	Z92	`,`	Personal history of medical treatment 	`,`	null	`],	
		[`	Z92.0	`,`	Personal history of contraception 	`,`	null	`],	
		[`	Z92.1	`,`	Personal history of long-term (current) use of anticoagulants 	`,`	null	`],	
		[`	Z92.2	`,`	Personal history of long-term (current) use of other medicaments Aspirin 	`,`	null	`],	
		[`	Z92.3	`,`	Personal history of irradiation 	`,`	null	`],	
		[`	Z92.4	`,`	Personal history of major surgery, not elsewhere classified 	`,`	null	`],	
		[`	Z92.5	`,`	Personal history of rehabilitation measures 	`,`	null	`],	
		[`	Z92.6	`,`	Personal history of chemotherapy for neoplastic disease 	`,`	null	`],	
		[`	Z92.8	`,`	Personal history of other medical treatment 	`,`	null	`],	
		[`	Z92.9	`,`	Personal history of medical treatment, unspecified 	`,`	null	`],	
		[`	Z93	`,`	Artificial opening status 	`,`	null	`],	
		[`	Z93.0	`,`	Tracheostomy status 	`,`	null	`],	
		[`	Z93.1	`,`	Gastrostomy status 	`,`	null	`],	
		[`	Z93.2	`,`	Ileostomy status 	`,`	null	`],	
		[`	Z93.3	`,`	Colostomy status 	`,`	null	`],	
		[`	Z93.4	`,`	Other artificial openings of gastrointestinal tract status 	`,`	null	`],	
		[`	Z93.5	`,`	Cystostomy status 	`,`	null	`],	
		[`	Z93.6	`,`	Other artificial openings of urinary tract status 	`,`	null	`],	
		[`	Z93.8	`,`	Other artificial opening status 	`,`	null	`],	
		[`	Z93.9	`,`	Artificial opening status, unspecified 	`,`	null	`],	
		[`	Z94	`,`	Transplanted organ and tissue status 	`,`	null	`],	
		[`	Z94.0	`,`	Kidney transplant status 	`,`	null	`],	
		[`	Z94.1	`,`	Heart transplant status 	`,`	null	`],	
		[`	Z94.2	`,`	Lung transplant status 	`,`	null	`],	
		[`	Z94.3	`,`	Heart and lungs transplant status 	`,`	null	`],	
		[`	Z94.4	`,`	Liver transplant status 	`,`	null	`],	
		[`	Z94.5	`,`	Skin transplant status 	`,`	null	`],	
		[`	Z94.6	`,`	Bone transplant status 	`,`	null	`],	
		[`	Z94.7	`,`	Corneal transplant status 	`,`	null	`],	
		[`	Z94.8	`,`	Other transplanted organ and tissue status 	`,`	null	`],	
		[`	Z94.9	`,`	Transplanted organ and tissue status, unspecified 	`,`	null	`],	
		[`	Z95	`,`	Presence of cardiac and vascular implants and grafts 	`,`	null	`],	
		[`	Z95.0	`,`	Presence of electronic cardiac devices 	`,`	null	`],	
		[`	Z95.1	`,`	Presence of aortocoronary bypass graft 	`,`	null	`],	
		[`	Z95.2	`,`	Presence of prosthetic heart valve 	`,`	null	`],	
		[`	Z95.3	`,`	Presence of xenogenic heart valve 	`,`	null	`],	
		[`	Z95.4	`,`	Presence of other heart-valve replacement 	`,`	null	`],	
		[`	Z95.5	`,`	Presence of coronary angioplasty implant and graft 	`,`	null	`],	
		[`	Z95.8	`,`	Presence of other cardiac and vascular implants and grafts 	`,`	null	`],	
		[`	Z95.9	`,`	Presence of cardiac and vascular implant and graft, unspecified 	`,`	null	`],	
		[`	Z96	`,`	Presence of other functional implants 	`,`	null	`],	
		[`	Z96.0	`,`	Presence of urogenital implants 	`,`	null	`],	
		[`	Z96.1	`,`	Presence of intraocular lens 	`,`	null	`],	
		[`	Z96.2	`,`	Presence of otological and audiological implants 	`,`	null	`],	
		[`	Z96.3	`,`	Presence of artificial larynx 	`,`	null	`],	
		[`	Z96.4	`,`	Presence of endocrine implants 	`,`	null	`],	
		[`	Z96.5	`,`	Presence of tooth-root and mandibular implants 	`,`	null	`],	
		[`	Z96.6	`,`	Presence of orthopaedic joint implants 	`,`	null	`],	
		[`	Z96.7	`,`	Presence of other bone and tendon implants 	`,`	null	`],	
		[`	Z96.8	`,`	Presence of other specified functional implants 	`,`	null	`],	
		[`	Z96.9	`,`	Presence of functional implant, unspecified 	`,`	null	`],	
		[`	Z97	`,`	Presence of other devices 	`,`	null	`],	
		[`	Z97.0	`,`	Presence of artificial eye 	`,`	null	`],	
		[`	Z97.1	`,`	Presence of artificial limb (complete)(partial) 	`,`	null	`],	
		[`	Z97.2	`,`	Presence of dental prosthetic device (complete)(partial) 	`,`	null	`],	
		[`	Z97.3	`,`	Presence of spectacles and contact lenses 	`,`	null	`],	
		[`	Z97.4	`,`	Presence of external hearing-aid 	`,`	null	`],	
		[`	Z97.5	`,`	Presence of (intrauterine) contraceptive device 	`,`	null	`],	
		[`	Z97.8	`,`	Presence of other specified devices 	`,`	null	`],	
		[`	Z98	`,`	Other postsurgical states 	`,`	null	`],	
		[`	Z98.0	`,`	Intestinal bypass and anastomosis status 	`,`	null	`],	
		[`	Z98.1	`,`	Arthrodesis status 	`,`	null	`],	
		[`	Z98.2	`,`	Presence of cerebrospinal fluid drainage device CSF shunt 	`,`	null	`],	
		[`	Z98.8	`,`	Other specified postsurgical states 	`,`	null	`],	
		[`	Z99	`,`	Z99 Dependence on enabling machines and devices, not elsewhere classified 	`,`	null	`],	
		[`	Z99.0	`,`	Dependence on aspirator 	`,`	null	`],	
		[`	Z99.1	`,`	Dependence on respirator 	`,`	null	`],	
		[`	Z99.2	`,`	Dependence on renal dialysis 	`,`	null	`],	
		[`	Z99.3	`,`	Dependence on wheelchair 	`,`	null	`],	
		[`	Z99.4	`,`	Dependence on artificial heart 	`,`	null	`],	
		[`	Z99.8	`,`	Dependence on other enabling machines and devices 	`,`	null	`],	
		[`	Z99.9	`,`	Dependence on unspecified enabling machine and device 	`,`	null	`]
									
	];								
				
	
let CodeRangeZ ={
	f0:function(val1=(-1),val2=(0)){
		let Range1 = ZCodes.slice(val1,val2);
		Range1.reverse();
		document.documentElement.innerHTML += `<br>Showing Z Codes ${Range1.length} items(s)<br>`;

		for(value1 in Range1){
			    document.documentElement.style.cssText = "background-color:tan;";
				document.getElementById('zcodesTR').outerHTML += `<tr><td style="background-color:navy;color:white;width:5%;padding:40px;border:2px solid white;font-weight:900;font-size:40px;text-align:center;">${Range1[value1][0]}</td><td style="background-color:black;color:white;width:90%;padding:20px;border:2px solid white;font-size:30px;">${Range1[value1][1]}</td><td style="background-color:navy;color:white;width:5%;padding:20px;border:2px solid white;font-weight:900;font-size:40px;text-align:center;">${Range1[value1][2]}</td></tr>`;			
		}

	},

};

	






	






